// Sekolah Rendah - Bahasa Melayu
// Silibus mengikut KSSR (Darjah 1-6)

export const sekolah_bahasa_melayu = [
  // ===== DARJAH 1 =====
  { title: 'Huruf Besar A-Z', type: 'letter_match', emoji: '🔤', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Epal', options: ['A','B','C','D'], answer: 0 },
    { letter: 'B', emoji: '🐦', word: 'Burung', options: ['A','B','C','D'], answer: 1 },
    { letter: 'C', emoji: '🐱', word: 'Kucing', options: ['A','B','C','D'], answer: 2 },
    { letter: 'D', emoji: '🐕', word: 'Anjing', options: ['A','B','C','D'], answer: 3 },
    { letter: 'E', emoji: '🐘', word: 'Gajah', options: ['D','E','F','G'], answer: 1 },
    { letter: 'F', emoji: '🐟', word: 'Ikan', options: ['D','E','F','G'], answer: 2 },
    { letter: 'G', emoji: '🍇', word: 'Anggur', options: ['E','F','G','H'], answer: 2 },
    { letter: 'H', emoji: '🏠', word: 'Rumah', options: ['F','G','H','I'], answer: 2 },
  ]}},
  { title: 'Suku Kata KV (ka, bu, si)', type: 'word_builder', emoji: '🔡', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: 'Bunyi: ka + ki = ?', options: ['kaki','kuku','kaki'], answer: 0 },
    { problem: 'Bunyi: bu + ku = ?', options: ['buku','baka','boke'], answer: 0 },
    { problem: 'Bunyi: ma + ta = ?', options: ['mata','mota','muta'], answer: 0 },
    { problem: 'Bunyi: su + su = ?', options: ['sosi','susu','sisu'], answer: 1 },
    { problem: 'Bunyi: pi + pi = ?', options: ['popi','pipi','pupu'], answer: 1 },
    { problem: 'Bunyi: da + da = ?', options: ['dada','didi','dudu'], answer: 0 },
    { problem: 'Bunyi: ku + da = ?', options: ['koda','kuda','kada'], answer: 1 },
    { problem: 'Bunyi: sa + ya = ?', options: ['siyu','saya','suyu'], answer: 1 },
  ]}},
  { title: 'Nama Haiwan Mudah', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '🐱', options: ['Kucing','Anjing','Arnab'], answer: 0 },
    { image: '🐶', options: ['Kucing','Anjing','Burung'], answer: 1 },
    { image: '🐟', options: ['Ikan','Sotong','Ketam'], answer: 0 },
    { image: '🐓', options: ['Itik','Ayam','Angsa'], answer: 1 },
    { image: '🐘', options: ['Gajah','Kuda','Badak'], answer: 0 },
    { image: '🦁', options: ['Singa','Harimau','Beruang'], answer: 0 },
    { image: '🐧', options: ['Penguin','Ayam','Itik'], answer: 0 },
    { image: '🐰', options: ['Arnab','Tupai','Tikus'], answer: 0 },
  ]}},

  // ===== DARJAH 2 =====
  { title: 'Perkataan Dua Suku Kata', type: 'word_builder', emoji: '📖', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'r-m-h', options: ['rumah','ramah','rimah'], answer: 0 },
    { problem: 'b-k-', options: ['buku','baka','boke'], answer: 0 },
    { problem: 'p-g-', options: ['pagi','pige','poagi'], answer: 0 },
    { problem: 'm-l-m', options: ['malam','malim','milam'], answer: 0 },
    { problem: 'k-d-', options: ['kedai','kuda','kodak'], answer: 0 },
    { problem: 's-k-l', options: ['sekolah','seket','sokol'], answer: 0 },
    { problem: 'k-r-t', options: ['kereta','karata','korat'], answer: 0 },
    { problem: 'j-l-n', options: ['jalan','jilon','julan'], answer: 0 },
  ]}},
  { title: 'Kata Nama Am - Benda', type: 'multiple_choice', emoji: '📝', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'Manakah kata nama?', options: ['berlari','buku','cantik'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['meja','tidur','merah'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['melompat','sekolah','besar'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['hijau','menangis','bunga'], answer: 2 },
    { problem: 'Manakah kata nama?', options: ['pokok','berlari','kuat'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['kecil','minum','kereta'], answer: 2 },
    { problem: 'Manakah kata nama?', options: ['terbang','burung','tinggi'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['sungai','berenang','sejuk'], answer: 0 },
  ]}},
  { title: 'Ejaan Mudah Darjah 2', type: 'spelling', emoji: '🔡', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'Ejaan betul "rmah"?', options: ['rumah','ramah','rimah'], answer: 0 },
    { problem: 'Ejaan betul "bljar"?', options: ['belajar','beljar','blakar'], answer: 0 },
    { problem: 'Ejaan betul "kreta"?', options: ['kereta','kareta','kretas'], answer: 0 },
    { problem: 'Ejaan betul "ptang"?', options: ['patang','petang','poteng'], answer: 1 },
    { problem: 'Ejaan betul "mlm"?', options: ['malam','malim','milam'], answer: 0 },
    { problem: 'Ejaan betul "pgi"?', options: ['pagi','pige','poagi'], answer: 0 },
    { problem: 'Ejaan betul "skola"?', options: ['sekolah','sekola','skolar'], answer: 0 },
    { problem: 'Ejaan betul "mkan"?', options: ['makanan','makan','mekkan'], answer: 1 },
  ]}},

  // ===== DARJAH 3 =====
  { title: 'Kata Kerja Darjah 3', type: 'multiple_choice', emoji: '⚡', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Manakah kata kerja?', options: ['berlari','buku','cantik'], answer: 0 },
    { problem: 'Manakah kata kerja?', options: ['meja','tidur','merah'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['melompat','sekolah','besar'], answer: 0 },
    { problem: 'Manakah kata kerja?', options: ['hijau','menangis','bunga'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['pokok','berlari','kuat'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['kecil','minum','kereta'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['terbang','burung','tinggi'], answer: 0 },
    { problem: 'Manakah kata kerja?', options: ['sungai','berenang','sejuk'], answer: 1 },
  ]}},
  { title: 'Antonim Darjah 3', type: 'multiple_choice', emoji: '↔️', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Lawan kata "besar"?', options: ['kecil','sederhana','panjang'], answer: 0 },
    { problem: 'Lawan kata "panas"?', options: ['suam','sejuk','lembap'], answer: 1 },
    { problem: 'Lawan kata "gelap"?', options: ['redup','cerah','kusam'], answer: 1 },
    { problem: 'Lawan kata "tua"?', options: ['muda','dewasa','remaja'], answer: 0 },
    { problem: 'Lawan kata "naik"?', options: ['pergi','turun','jatuh'], answer: 1 },
    { problem: 'Lawan kata "siang"?', options: ['petang','malam','subuh'], answer: 1 },
    { problem: 'Lawan kata "keras"?', options: ['lembut','halus','licin'], answer: 0 },
    { problem: 'Lawan kata "awal"?', options: ['lewat','lambat','cepat'], answer: 1 },
  ]}},
  { title: 'Ayat Mudah - Baca dan Faham', type: 'reading', emoji: '📖', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Ali ada seekor kucing. Apakah yang Ali ada?', options: ['Anjing','Kucing','Arnab'], answer: 1 },
    { problem: 'Siti makan epal setiap hari. Apakah yang Siti makan?', options: ['Oren','Epal','Pisang'], answer: 1 },
    { problem: 'Matahari terbit pada waktu pagi. Bilakah?', options: ['Petang','Pagi','Malam'], answer: 1 },
    { problem: 'Tom membaca buku di perpustakaan. Di mana Tom?', options: ['Rumah','Sekolah','Perpustakaan'], answer: 2 },
    { problem: 'Burung terbang di langit. Di mana burung terbang?', options: ['Dalam laut','Di langit','Di tanah'], answer: 1 },
    { problem: 'Dia ada dua ekor kucing dan seekor anjing. Berapa haiwan?', options: ['Dua','Tiga','Satu'], answer: 1 },
    { problem: 'Kanak-kanak bermain selepas sekolah. Bilakah?', options: ['Sebelum','Selepas','Semasa'], answer: 1 },
    { problem: 'Amir lebih tinggi daripada Bakar. Siapa lebih tinggi?', options: ['Bakar','Amir','Sama'], answer: 1 },
  ]}},

  // ===== DARJAH 4 =====
  { title: 'Imbuhan me- Darjah 4', type: 'word_builder', emoji: '📝', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'me- + makan = ?', options: ['makan','memakan','dimakan'], answer: 1 },
    { problem: 'me- + baca = ?', options: ['membaca','terbaca','dibaca'], answer: 0 },
    { problem: 'me- + tulis = ?', options: ['ditulis','menulis','tertulis'], answer: 1 },
    { problem: 'me- + lihat = ?', options: ['dilihat','terlihat','melihat'], answer: 2 },
    { problem: 'me- + beli = ?', options: ['membeli','terbeli','dibeli'], answer: 0 },
    { problem: 'me- + jual = ?', options: ['terjual','dijual','menjual'], answer: 2 },
    { problem: 'me- + tanya = ?', options: ['bertanya','ditanya','menanya'], answer: 2 },
    { problem: 'me- + buat = ?', options: ['membuat','terbuat','dibuat'], answer: 0 },
  ]}},
  { title: 'Imbuhan ber- Darjah 4', type: 'word_builder', emoji: '📝', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'ber- + main = ?', options: ['bermain','termain','dimain'], answer: 0 },
    { problem: 'ber- + lari = ?', options: ['terlari','berlari','dilari'], answer: 1 },
    { problem: 'ber- + jalan = ?', options: ['berjalan','terjalan','dijalan'], answer: 0 },
    { problem: 'ber- + nyanyi = ?', options: ['dinyanyikan','ternyayi','bernyanyi'], answer: 2 },
    { problem: 'ber- + cakap = ?', options: ['bercakap','tercakap','dicakap'], answer: 0 },
    { problem: 'ber- + tanya = ?', options: ['bertanya','tertanya','ditanya'], answer: 0 },
    { problem: 'ber- + kerja = ?', options: ['terkerja','dikerja','bekerja'], answer: 2 },
    { problem: 'ber- + senam = ?', options: ['bersenam','tersenam','disenam'], answer: 0 },
  ]}},
  { title: 'Sinonim Darjah 4', type: 'multiple_choice', emoji: '🔄', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'Sinonim "cantik"?', options: ['hodoh','indah','kotor'], answer: 1 },
    { problem: 'Sinonim "gembira"?', options: ['sedih','marah','suka'], answer: 2 },
    { problem: 'Sinonim "besar"?', options: ['kecil','agam','tinggi'], answer: 1 },
    { problem: 'Sinonim "cepat"?', options: ['laju','lambat','diam'], answer: 0 },
    { problem: 'Sinonim "pintar"?', options: ['bodoh','bijak','malas'], answer: 1 },
    { problem: 'Sinonim "lapar"?', options: ['kenyang','haus','dahaga'], answer: 1 },
    { problem: 'Sinonim "bahaya"?', options: ['selamat','merbahaya','aman'], answer: 1 },
    { problem: 'Sinonim "kawan"?', options: ['musuh','rakan','lawan'], answer: 1 },
  ]}},

  // ===== DARJAH 5 =====
  { title: 'Kata Sendi Nama Darjah 5', type: 'multiple_choice', emoji: '📌', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Saya pergi ___ sekolah.', options: ['di','ke','dari'], answer: 1 },
    { problem: 'Buku itu ada ___ meja.', options: ['ke','dari','di'], answer: 2 },
    { problem: 'Dia datang ___ Johor.', options: ['di','ke','dari'], answer: 2 },
    { problem: 'Kucing itu duduk ___ kerusi.', options: ['di atas','ke bawah','dari dalam'], answer: 0 },
    { problem: 'Mereka bermain ___ taman.', options: ['ke','di','dari'], answer: 1 },
    { problem: 'Ibu membeli sayur ___ pasar.', options: ['di','ke','dari'], answer: 0 },
    { problem: 'Ayah pulang ___ pejabat.', options: ['di','ke','dari'], answer: 2 },
    { problem: 'Kami pergi ___ pantai semasa cuti.', options: ['dari','ke','di'], answer: 1 },
  ]}},
  { title: 'Peribahasa Darjah 5', type: 'multiple_choice', emoji: '📜', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '"Bersatu teguh bercerai ___"', options: ['kuat','roboh','lemah'], answer: 1 },
    { problem: '"Sediakan payung sebelum ___"', options: ['panas','hujan','ribut'], answer: 1 },
    { problem: '"Rajin pangkal ___"', options: ['kaya','pandai','muda'], answer: 0 },
    { problem: '"Sikit-sikit lama-lama jadi ___"', options: ['banyak','bukit','tinggi'], answer: 1 },
    { problem: '"Air yang tenang jangan ___"', options: ['diminum','dipanik','disangka'], answer: 2 },
    { problem: '"Berani kerana benar takut kerana ___"', options: ['salah','benar','bodoh'], answer: 0 },
    { problem: '"Melentur buluh biarlah dari ___"', options: ['atas','rebungnya','bawah'], answer: 1 },
    { problem: '"Seperti aur dengan ___"', options: ['tebing','sungai','batu'], answer: 0 },
  ]}},
  { title: 'Pembentukan Kata Majmuk Darjah 5', type: 'word_builder', emoji: '🔗', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'buku + cerita = ?', options: ['Buku Cerita','Bercerita','Cerita Buku'], answer: 0 },
    { problem: 'meja + makan = ?', options: ['Meja Makan','Memakan','Makan Meja'], answer: 0 },
    { problem: 'rumah + sakit = ?', options: ['Rumah Sakit','Sakit Rumah','Berumah'], answer: 0 },
    { problem: 'kapal + terbang = ?', options: ['Terbang Kapal','Kapal Terbang','Berterbang'], answer: 1 },
    { problem: 'mata + pelajaran = ?', options: ['Pelajaran Mata','Mata Pelajaran','Berpelajaran'], answer: 1 },
    { problem: 'surat + khabar = ?', options: ['Surat Khabar','Khabar Surat','Bersurat'], answer: 0 },
    { problem: 'bola + sepak = ?', options: ['Bola Sepak','Sepak Bola','Menyepak'], answer: 0 },
    { problem: 'air + mata = ?', options: ['Mata Air','Air Mata','Bermata'], answer: 1 },
  ]}},

  // ===== DARJAH 6 =====
  { title: 'Peribahasa Lanjutan Darjah 6', type: 'multiple_choice', emoji: '📜', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: '"Bagai aur dengan tebing" bermaksud?', options: ['Berpecah belah','Tolong-menolong','Bergaduh'], answer: 1 },
    { problem: '"Sediakan payung sebelum hujan" bermaksud?', options: ['Bersedia untuk masa depan','Takut hujan','Beli payung'], answer: 0 },
    { problem: '"Seperti kacang lupakan kulit" bermaksud?', options: ['Lupa akan asal usul','Suka makan kacang','Kulit kacang tebal'], answer: 0 },
    { problem: '"Buah jatuh tidak jauh dari pokok" bermaksud?', options: ['Anak seperti ibu bapa','Buah selalu jatuh','Pokok buah rendah'], answer: 0 },
    { problem: '"Tong kosong nyaring bunyinya" bermaksud?', options: ['Tong penuh','Orang sombong banyak cakap','Bunyi kuat'], answer: 1 },
    { problem: '"Harimau mati meninggalkan belang" bermaksud?', options: ['Harimau berbahaya','Nama baik kekal selepas mati','Belang harimau indah'], answer: 1 },
    { problem: '"Berdiri sama tinggi duduk sama rendah" bermaksud?', options: ['Fizikal sama','Kesaksamaan','Sama tinggi'], answer: 1 },
    { problem: '"Carik-carik bulu ayam, lama-lama bercantum juga" bermaksud?', options: ['Perbalahan dalam keluarga akan baik','Bulu ayam cantik','Menyatukan semula'], answer: 0 },
  ]}},
  { title: 'Ayat Aktif & Pasif Darjah 6', type: 'reading', emoji: '✍️', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Ayat aktif: "Ibu memasak nasi." Ayat pasifnya?', options: ['Nasi dimasak ibu','Memasak nasi ibu','Ibu nasi memasak'], answer: 0 },
    { problem: 'Manakah ayat aktif?', options: ['Buku dibeli Ali','Ali membeli buku','Buku itu Ali'], answer: 1 },
    { problem: 'Manakah ayat pasif?', options: ['Dia menanam pokok','Pokok ditanam oleh dia','Pokok itu hijau'], answer: 1 },
    { problem: '"Pelajar menulis karangan." Ubah ke pasif:', options: ['Karangan ditulis pelajar','Menulis karangan pelajar','Pelajar karangan menulis'], answer: 0 },
    { problem: 'Kata pemeri yang betul: "Dia ___ pelajar"', options: ['adalah','ialah','adalah'], answer: 1 },
    { problem: 'Kata nafi yang betul: "Dia ___ pergi sekolah"', options: ['bukan','tidak','tiada'], answer: 1 },
    { problem: 'Manakah subjek: "Guru mengajar murid"?', options: ['Guru','mengajar','murid'], answer: 0 },
    { problem: 'Manakah objek: "Ali memukul bola"?', options: ['Ali','memukul','bola'], answer: 2 },
  ]}},
  { title: 'Penulisan Karangan - Struktur Darjah 6', type: 'reading', emoji: '✍️', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Ayat pembuka karangan yang baik?', options: ['Saya tidak tahu','Pada suatu hari yang cerah...','Tamat'], answer: 1 },
    { problem: 'Kata hubung yang betul: "Saya suka nasi ___ lauk pauk"', options: ['tetapi','dan','kerana'], answer: 1 },
    { problem: '"___ hari Jumaat, kami pergi ke masjid"', options: ['Pada','Di','Ke'], answer: 0 },
    { problem: 'Tanda baca di hujung ayat penyata?', options: ['?','!','.'], answer: 2 },
    { problem: 'Tanda baca di hujung ayat tanya?', options: ['?','!','.'], answer: 0 },
    { problem: 'Paragraf pertama karangan dipanggil?', options: ['Penutup','Pendahuluan','Isi'], answer: 1 },
    { problem: 'Paragraf terakhir karangan dipanggil?', options: ['Penutup','Pendahuluan','Isi'], answer: 0 },
    { problem: 'Karangan fakta berbeza dengan karangan cerita kerana?', options: ['Fakta menggunakan cerita','Fakta menggunakan maklumat benar','Tiada perbezaan'], answer: 1 },
  ]}},
];