// Sekolah Rendah - Sains
// Silibus mengikut KSSR (Darjah 1-6)

export const sekolah_science = [
  // ===== DARJAH 1 =====
  { title: 'Deria Lima Darjah 1', type: 'picture_quiz', emoji: '👁️', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '👁️', options: ['Mata - Melihat','Hidung - Menghidu','Telinga - Mendengar'], answer: 0 },
    { image: '👃', options: ['Mata - Melihat','Hidung - Menghidu','Mulut - Merasa'], answer: 1 },
    { image: '👂', options: ['Mata - Melihat','Hidung - Menghidu','Telinga - Mendengar'], answer: 2 },
    { image: '👅', options: ['Lidah - Merasa','Hidung - Menghidu','Telinga - Mendengar'], answer: 0 },
    { image: '✋', options: ['Mata - Melihat','Tangan - Menyentuh','Telinga - Mendengar'], answer: 1 },
    { image: '🌹', options: ['Kita lihat dengan mata','Kita hidu dengan hidung','Kita dengar dengan telinga'], answer: 1 },
    { image: '🎵', options: ['Kita lihat dengan mata','Kita hidu dengan hidung','Kita dengar dengan telinga'], answer: 2 },
    { image: '🍋', options: ['Masam - rasa dengan lidah','Harum - hidu dengan hidung','Panas - sentuh dengan tangan'], answer: 0 },
  ]}},
  { title: 'Haiwan dan Tumbuhan Darjah 1', type: 'picture_quiz', emoji: '🌱', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '🌳', options: ['Haiwan','Tumbuhan','Batu'], answer: 1 },
    { image: '🐱', options: ['Haiwan','Tumbuhan','Manusia'], answer: 0 },
    { image: '🌸', options: ['Haiwan','Tumbuhan','Batu'], answer: 1 },
    { image: '🐟', options: ['Haiwan','Tumbuhan','Air'], answer: 0 },
    { image: '🍎', options: ['Daripada haiwan','Daripada tumbuhan','Daripada batu'], answer: 1 },
    { image: '🥛', options: ['Daripada haiwan','Daripada tumbuhan','Daripada batu'], answer: 0 },
    { image: '🌻', options: ['Haiwan','Tumbuhan','Mineral'], answer: 1 },
    { image: '🐔', options: ['Haiwan','Tumbuhan','Mineral'], answer: 0 },
  ]}},
  { title: 'Cuaca Hari Ini Darjah 1', type: 'picture_quiz', emoji: '☀️', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '☀️', options: ['Panas dan Cerah','Sejuk dan Hujan','Berangin'], answer: 0 },
    { image: '🌧️', options: ['Panas dan Cerah','Sejuk dan Hujan','Berangin'], answer: 1 },
    { image: '🌬️', options: ['Panas','Hujan','Berangin'], answer: 2 },
    { image: '⛅', options: ['Cerah','Berawan','Hujan'], answer: 1 },
    { image: '❄️', options: ['Panas','Sejuk','Berangin'], answer: 1 },
    { image: '🌩️', options: ['Ribut','Cerah','Berangin'], answer: 0 },
    { image: '☂️', options: ['Waktu hujan guna payung','Waktu panas guna payung','Waktu sejuk guna payung'], answer: 0 },
    { image: '🌈', options: ['Pelangi selepas hujan','Pelangi masa panas','Pelangi sebelum hujan'], answer: 0 },
  ]}},

  // ===== DARJAH 2 =====
  { title: 'Bahan dan Kegunaan Darjah 2', type: 'multiple_choice', emoji: '🧱', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'Apa bahan buat kerusi kayu?', options: ['Besi','Kayu','Plastik'], answer: 1 },
    { problem: 'Apa bahan buat tali?', options: ['Kaca','Kayu','Getah/Nilon'], answer: 2 },
    { problem: 'Apa bahan buat cermin?', options: ['Kaca','Kayu','Besi'], answer: 0 },
    { problem: 'Apa bahan buat duit syiling?', options: ['Plastik','Logam','Kaca'], answer: 1 },
    { problem: 'Apa bahan buat botol air mineral?', options: ['Kaca','Plastik','Besi'], answer: 1 },
    { problem: 'Apa bahan buat beg sekolah?', options: ['Logam','Kain/Kulit','Kaca'], answer: 1 },
    { problem: 'Bahan manakah yang berat?', options: ['Bulu','Besi','Plastik'], answer: 1 },
    { problem: 'Bahan manakah yang telus?', options: ['Besi','Kayu','Kaca'], answer: 2 },
  ]}},
  { title: 'Air dan Kegunaannya Darjah 2', type: 'multiple_choice', emoji: '💧', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'Air digunakan untuk?', options: ['Bermain sahaja','Minum, mandi, masak','Tidur'], answer: 1 },
    { problem: 'Air yang selamat diminum?', options: ['Air kotor','Air bersih/ditapis','Air sungai mentah'], answer: 1 },
    { problem: 'Bagaimana kita jimat air?', options: ['Biarkan paip terbuka','Tutup paip bila tidak guna','Mandi sangat lama'], answer: 1 },
    { problem: 'Air boleh bertukar menjadi ais bila?', options: ['Dipanaskan','Dibekukan','Dikacau'], answer: 1 },
    { problem: 'Air mendidih pada suhu?', options: ['50°C','80°C','100°C'], answer: 2 },
    { problem: 'Air membeku pada suhu?', options: ['0°C','10°C','20°C'], answer: 0 },
    { problem: 'Makhluk hidup yang perlukan air?', options: ['Haiwan sahaja','Tumbuhan sahaja','Haiwan dan Tumbuhan'], answer: 2 },
    { problem: 'Air yang tercemar boleh menyebabkan?', options: ['Sihat','Sakit','Kuat'], answer: 1 },
  ]}},
  { title: 'Tumbuhan di Sekeliling Darjah 2', type: 'picture_quiz', emoji: '🌿', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { image: '🌳', options: ['Pokok','Rumput','Bunga'], answer: 0 },
    { image: '🌸', options: ['Pokok','Bunga','Daun'], answer: 1 },
    { image: '🍂', options: ['Akar','Batang','Daun'], answer: 2 },
    { image: '🍎', options: ['Daun','Buah','Bunga'], answer: 1 },
    { image: '🌱', options: ['Anak pokok','Buah','Bunga'], answer: 0 },
    { image: '🌵', options: ['Kaktus - tumbuh di padang pasir','Pokok kelapa - tumbuh di pantai','Padi - tumbuh di sawah'], answer: 0 },
    { image: '🍀', options: ['Tumbuhan darat','Tumbuhan air','Tumbuhan gunung'], answer: 0 },
    { image: '🌊🌿', options: ['Tumbuhan darat','Tumbuhan air','Tumbuhan gunung'], answer: 1 },
  ]}},

  // ===== DARJAH 3 =====
  { title: 'Jenis-Jenis Haiwan Darjah 3', type: 'picture_quiz', emoji: '🦁', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { image: '🐟', options: ['Mamalia','Ikan','Reptilia'], answer: 1 },
    { image: '🐸', options: ['Amfibia','Ikan','Reptilia'], answer: 0 },
    { image: '🐍', options: ['Mamalia','Amfibia','Reptilia'], answer: 2 },
    { image: '🐦', options: ['Mamalia','Burung','Reptilia'], answer: 1 },
    { image: '🐘', options: ['Mamalia','Reptilia','Burung'], answer: 0 },
    { image: '🦋', options: ['Cacing','Serangga','Amfibia'], answer: 1 },
    { image: '🐢', options: ['Amfibia','Ikan','Reptilia'], answer: 2 },
    { image: '🦇', options: ['Mamalia','Burung','Serangga'], answer: 0 },
  ]}},
  { title: 'Kitaran Hidup Haiwan Darjah 3', type: 'multiple_choice', emoji: '🦋', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Kupu-kupu bermula dari?', options: ['Telur → ulat → kepompong → kupu-kupu','Telur → kupu-kupu','Anak → kupu-kupu'], answer: 0 },
    { problem: 'Katak bermula dari?', options: ['Telur → kecebong → katak','Telur → katak','Anak → katak'], answer: 0 },
    { problem: 'Ayam bermula dari?', options: ['Beranak','Telur','Bercambah'], answer: 1 },
    { problem: 'Kucing membiak melalui?', options: ['Telur','Beranak','Bercambah'], answer: 1 },
    { problem: 'Ikan bermula dari?', options: ['Beranak','Telur','Bercambah'], answer: 1 },
    { problem: 'Metamorfosis berlaku pada?', options: ['Kucing','Kupu-kupu','Ikan'], answer: 1 },
    { problem: 'Peringkat terakhir kitaran kupu-kupu?', options: ['Ulat','Kepompong','Kupu-kupu'], answer: 2 },
    { problem: 'Haiwan manakah yang bertelur?', options: ['Anjing','Ayam','Kuda'], answer: 1 },
  ]}},
  { title: 'Keadaan Bahan Darjah 3', type: 'multiple_choice', emoji: '🧪', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Batu adalah dalam keadaan?', options: ['Pepejal','Cecair','Gas'], answer: 0 },
    { problem: 'Jus oren adalah dalam keadaan?', options: ['Pepejal','Cecair','Gas'], answer: 1 },
    { problem: 'Oksigen adalah dalam keadaan?', options: ['Pepejal','Cecair','Gas'], answer: 2 },
    { problem: 'Apabila air dipanaskan, ia berubah menjadi?', options: ['Ais','Wap air','Batu'], answer: 1 },
    { problem: 'Apabila air dibekukan, ia berubah menjadi?', options: ['Ais','Wap air','Batu'], answer: 0 },
    { problem: 'Pepejal mempunyai bentuk yang?', options: ['Sentiasa berubah','Tetap','Tiada bentuk'], answer: 1 },
    { problem: 'Cecair mengikut bentuk?', options: ['Bekas yang mengisinya','Bentuk sendiri','Tiada bentuk'], answer: 0 },
    { problem: 'Gas mengisi seluruh?', options: ['Sebahagian bekas','Seluruh bekas','Tiada'], answer: 1 },
  ]}},

  // ===== DARJAH 4 =====
  { title: 'Sistem Tubuh Manusia Darjah 4', type: 'multiple_choice', emoji: '🏃', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'Sistem yang menggerakkan badan?', options: ['Penghadaman','Rangka & Otot','Pernafasan'], answer: 1 },
    { problem: 'Sistem yang memproses makanan?', options: ['Penghadaman','Saraf','Rangka'], answer: 0 },
    { problem: 'Paru-paru adalah sebahagian dari sistem?', options: ['Peredaran Darah','Pernafasan','Penghadaman'], answer: 1 },
    { problem: 'Jantung adalah sebahagian dari sistem?', options: ['Peredaran Darah','Pernafasan','Penghadaman'], answer: 0 },
    { problem: 'Otak adalah pusat kawalan sistem?', options: ['Penghadaman','Saraf','Peredaran Darah'], answer: 1 },
    { problem: 'Tulang melindungi organ penting — sistem?', options: ['Rangka','Otot','Saraf'], answer: 0 },
    { problem: 'Kita bernafas dengan?', options: ['Jantung','Paru-paru','Hati'], answer: 1 },
    { problem: 'Darah dipam oleh?', options: ['Paru-paru','Jantung','Hati'], answer: 1 },
  ]}},
  { title: 'Tenaga Darjah 4', type: 'multiple_choice', emoji: '⚡', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'Sumber tenaga matahari dikenali sebagai?', options: ['Tenaga Angin','Tenaga Solar','Tenaga Air'], answer: 1 },
    { problem: 'Kipas angin menggunakan tenaga?', options: ['Tenaga Panas','Tenaga Elektrik','Tenaga Bunyi'], answer: 1 },
    { problem: 'Lampu menghasilkan tenaga?', options: ['Cahaya sahaja','Haba sahaja','Cahaya dan Haba'], answer: 2 },
    { problem: 'Bateri menyimpan tenaga?', options: ['Tenaga Kimia','Tenaga Solar','Tenaga Angin'], answer: 0 },
    { problem: 'Matahari adalah sumber tenaga?', options: ['Tidak boleh dibaharui','Boleh dibaharui','Tidak bertenaga'], answer: 1 },
    { problem: 'Petrol adalah bahan?', options: ['Boleh dibaharui','Tidak boleh dibaharui','Tenaga bersih'], answer: 1 },
    { problem: 'Tenaga yang menghasilkan bunyi?', options: ['Tenaga Haba','Tenaga Bunyi','Tenaga Cahaya'], answer: 1 },
    { problem: 'Panel solar menukar tenaga solar kepada?', options: ['Tenaga angin','Tenaga elektrik','Tenaga haba'], answer: 1 },
  ]}},
  { title: 'Sistem Suria Darjah 4', type: 'picture_quiz', emoji: '🌍', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { image: '☀️', options: ['Bumi','Matahari','Bulan'], answer: 1 },
    { image: '🌍', options: ['Bumi','Marikh','Musytari'], answer: 0 },
    { image: '🌙', options: ['Planet','Bulan','Bintang'], answer: 1 },
    { image: '⭐', options: ['Satelit','Planet','Bintang'], answer: 2 },
    { image: '🔴', options: ['Bumi','Marikh','Zuhal'], answer: 1 },
    { image: '🪐', options: ['Bumi','Marikh','Zuhal'], answer: 2 },
    { image: '🌑', options: ['Gerhana','Bulan Penuh','Bulan Baru'], answer: 2 },
    { image: '🌕', options: ['Bulan Baru','Bulan Penuh','Bintang'], answer: 1 },
  ]}},

  // ===== DARJAH 4 — TAMBAHAN =====
  { title: 'Ekosistem dan Habitat Darjah 4', type: 'multiple_choice', emoji: '🌿', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'Ekosistem hutan mengandungi?', options: ['Ikan sahaja','Pelbagai tumbuhan dan haiwan','Batu sahaja'], answer: 1 },
    { problem: 'Habitat ikan ialah?', options: ['Tanah kering','Air','Udara'], answer: 1 },
    { problem: 'Haiwan yang boleh hidup di dua habitat?', options: ['Singa','Katak','Ikan'], answer: 1 },
    { problem: 'Penebangan hutan menjejaskan?', options: ['Hanya cuaca','Habitat hidupan liar','Lautan'], answer: 1 },
    { problem: 'Apa berlaku jika sumber air habis?', options: ['Ekosistem lestari','Hidupan terancam','Cuaca baik'], answer: 1 },
    { problem: 'Spesies terancam bermaksud?', options: ['Haiwan biasa','Bilangan semakin berkurangan','Haiwan baru'], answer: 1 },
    { problem: 'Cara perlindungan habitat liar?', options: ['Bina lebih kilang','Tubuh taman negara','Tebang lebih pokok'], answer: 1 },
    { problem: 'Biodiversiti bermaksud?', options: ['Satu spesies sahaja','Kepelbagaian spesies','Ketiadaan hidupan'], answer: 1 },
  ]}},
  { title: 'Pembiakan Manusia & Haiwan D4', type: 'multiple_choice', emoji: '🧬', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'Haiwan yang melahirkan anak hidup?', options: ['Ayam','Ikan','Kucing'], answer: 2 },
    { problem: 'Haiwan yang mengerami telur?', options: ['Lembu','Burung','Arnab'], answer: 1 },
    { problem: 'Manusia membiak melalui?', options: ['Bertelur','Melahirkan anak','Bercambah'], answer: 1 },
    { problem: 'Tempoh mengandung manusia?', options: ['6 bulan','9 bulan','12 bulan'], answer: 1 },
    { problem: 'Katak bertelur di?', options: ['Tanah kering','Air','Pokok'], answer: 1 },
    { problem: 'Telur ikan disebut?', options: ['Benih','Telur','Roe'], answer: 2 },
    { problem: 'Haiwan yang boleh membiak tanpa pasangan?', options: ['Kucing','Cacing tanah','Harimau'], answer: 1 },
    { problem: 'Bayi manusia minum?', options: ['Air biasa','Susu ibu','Jus buah'], answer: 1 },
  ]}},

  // ===== DARJAH 5 =====
  { title: 'Daya dan Gerakan Darjah 5', type: 'multiple_choice', emoji: '⚙️', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Daya tarikan bumi dipanggil?', options: ['Daya Magnet','Graviti','Daya Tolak'], answer: 1 },
    { problem: 'Benda jatuh ke bawah kerana?', options: ['Angin','Graviti','Magnet'], answer: 1 },
    { problem: 'Geseran menyebabkan?', options: ['Kelajuan','Haba dan perlambatan','Daya lebih'], answer: 1 },
    { problem: 'Magnet menarik bahan?', options: ['Semua logam','Logam besi','Semua benda'], answer: 1 },
    { problem: 'Kutub magnet yang sama akan?', options: ['Tarik menarik','Tolak menolak','Tiada kesan'], answer: 1 },
    { problem: 'Kutub magnet yang berbeza akan?', options: ['Tarik menarik','Tolak menolak','Tiada kesan'], answer: 0 },
    { problem: 'Daya yang diperlukan untuk menggerakkan benda?', options: ['Tenaga','Daya','Kerja'], answer: 1 },
    { problem: 'Mesin mudah yang membantu kerja?', options: ['Tayar','Tuas','Bateri'], answer: 1 },
  ]}},
  { title: 'Cahaya dan Bunyi Darjah 5', type: 'multiple_choice', emoji: '💡', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Cahaya bergerak dalam?', options: ['Garis bengkok','Garis lurus','Garis bulat'], answer: 1 },
    { problem: 'Bunyi memerlukan ___ untuk bergerak?', options: ['Vakum','Medium','Cahaya'], answer: 1 },
    { problem: 'Bunyi TIDAK boleh bergerak melalui?', options: ['Udara','Air','Vakum'], answer: 2 },
    { problem: 'Cermin memantulkan?', options: ['Bunyi','Cahaya','Haba'], answer: 1 },
    { problem: 'Gema adalah pantulan?', options: ['Cahaya','Bunyi','Haba'], answer: 1 },
    { problem: 'Sumber cahaya semula jadi?', options: ['Lampu','Matahari','Lilin'], answer: 1 },
    { problem: 'Bahan yang membenarkan cahaya lalu sepenuhnya?', options: ['Legap','Lutsinar','Lut sinar'], answer: 2 },
    { problem: 'Warna asas cahaya putih ialah?', options: ['3 warna','5 warna','7 warna (pelangi)'], answer: 2 },
  ]}},
  { title: 'Rantai Makanan Darjah 5', type: 'multiple_choice', emoji: '🌿', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Tumbuhan dalam rantai makanan ialah?', options: ['Pengguna','Pengeluar','Pengurai'], answer: 1 },
    { problem: 'Harimau dalam rantai makanan ialah?', options: ['Pengeluar','Pengguna','Pengurai'], answer: 1 },
    { problem: 'Cacing dalam ekosistem berfungsi sebagai?', options: ['Pengguna','Pengeluar','Pengurai'], answer: 2 },
    { problem: 'Rantai makanan bermula dengan?', options: ['Haiwan','Tumbuhan','Kulat'], answer: 1 },
    { problem: 'Arnab memakan rumput. Arnab ialah?', options: ['Herbivor','Karnivor','Omnivor'], answer: 0 },
    { problem: 'Singa memakan daging. Singa ialah?', options: ['Herbivor','Karnivor','Omnivor'], answer: 1 },
    { problem: 'Manusia makan sayur dan daging. Manusia ialah?', options: ['Herbivor','Karnivor','Omnivor'], answer: 2 },
    { problem: 'Pokok → Ulat → Burung. Siapa pengguna pertama?', options: ['Pokok','Ulat','Burung'], answer: 1 },
  ]}},

  // ===== DARJAH 5 — TAMBAHAN =====
  { title: 'Perubahan Jirim Darjah 5', type: 'multiple_choice', emoji: '🔬', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Air dipanaskan → menjadi?', options: ['Ais','Wap air','Batu'], answer: 1 },
    { problem: 'Air dibekukan → menjadi?', options: ['Wap','Ais','Gas'], answer: 1 },
    { problem: 'Perubahan fizikal contohnya?', options: ['Kayu terbakar','Ais cair','Besi berkarat'], answer: 1 },
    { problem: 'Perubahan kimia contohnya?', options: ['Air beku','Kayu dipotong','Kertas terbakar'], answer: 2 },
    { problem: 'Besi berkarat adalah perubahan?', options: ['Fizikal','Kimia','Tiada'], answer: 1 },
    { problem: 'Ais cair adalah perubahan?', options: ['Fizikal','Kimia','Tiada'], answer: 0 },
    { problem: 'Perubahan kimia boleh dikembalikan?', options: ['Ya','Tidak','Kadang-kadang'], answer: 1 },
    { problem: 'Memanaskan gula → karamel adalah?', options: ['Fizikal','Kimia','Tiada perubahan'], answer: 1 },
  ]}},
  { title: 'Haiwan Vertebrat & Invertebrat D5', type: 'multiple_choice', emoji: '🦴', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Vertebrat bermaksud?', options: ['Tiada tulang belakang','Ada tulang belakang','Ada cengkerang'], answer: 1 },
    { problem: 'Ikan tergolong dalam?', options: ['Vertebrat','Invertebrat','Amfibia'], answer: 0 },
    { problem: 'Cacing tergolong dalam?', options: ['Vertebrat','Invertebrat','Reptilia'], answer: 1 },
    { problem: 'Serangga tergolong dalam?', options: ['Vertebrat','Invertebrat','Mamalia'], answer: 1 },
    { problem: 'Manusia tergolong dalam?', options: ['Invertebrat','Vertebrat Mamalia','Reptilia'], answer: 1 },
    { problem: 'Ketam tergolong dalam?', options: ['Vertebrat','Invertebrat Krustasea','Mamalia'], answer: 1 },
    { problem: 'Burung tergolong dalam?', options: ['Reptilia','Amfibia','Vertebrat Burung'], answer: 2 },
    { problem: 'Bintang laut tergolong dalam?', options: ['Vertebrat','Invertebrat','Mamalia'], answer: 1 },
  ]}},

  // ===== DARJAH 6 =====
  { title: 'Alam Sekitar & Pemuliharaan Darjah 6', type: 'multiple_choice', emoji: '🌍', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Pencemaran udara disebabkan oleh?', options: ['Pokok banyak','Asap kilang dan kenderaan','Hujan lebat'], answer: 1 },
    { problem: 'Cara terbaik kurangkan sampah?', options: ['Bakar sampah','3R: Reduce, Reuse, Recycle','Buang ke sungai'], answer: 1 },
    { problem: 'Pemanasan global disebabkan oleh?', options: ['Gas rumah hijau berlebihan','Terlalu banyak pokok','Hujan lebat'], answer: 0 },
    { problem: 'Cara jimat air?', options: ['Biarkan air mengalir','Tutup paip bila tidak guna','Mandi lama'], answer: 1 },
    { problem: 'Penebangan hutan menyebabkan?', options: ['Lebih hujan','Lebih oksigen','Banjir dan hakisan'], answer: 2 },
    { problem: 'Cara jimat elektrik?', options: ['Biarkan lampu terbuka','Padam lampu bila keluar','Guna lebih alatan'], answer: 1 },
    { problem: 'Bahan kitar semula yang betul?', options: ['Sisa makanan','Botol plastik','Tulang'], answer: 1 },
    { problem: 'Biodiversiti bermaksud?', options: ['Kepelbagaian spesies hidupan','Pencemaran alam','Penebangan hutan'], answer: 0 },
  ]}},
  { title: 'Sains Teknologi Darjah 6', type: 'picture_quiz', emoji: '🔬', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { image: '🔬', options: ['Mikroskop - lihat benda kecil','Teleskop - lihat bintang','Kamera'], answer: 0 },
    { image: '🔭', options: ['Mikroskop','Teleskop - lihat benda jauh','Kompas'], answer: 1 },
    { image: '🧲', options: ['Magnet - tarik logam','Wayar','Cermin'], answer: 0 },
    { image: '☀️🔋', options: ['Panel Solar','Pemanas','Penjana'], answer: 0 },
    { image: '🌡️', options: ['Termometer','Barometer','Higrometer'], answer: 0 },
    { image: '⚖️', options: ['Neraca - ukur jisim','Pembaris','Jam'], answer: 0 },
    { image: '📡', options: ['Antena - isyarat','Teleskop','Radar'], answer: 0 },
    { image: '💉', options: ['Jarum suntikan - vaksin','Ubat biasa','Alat bedah'], answer: 0 },
  ]}},
  { title: 'Kaedah Saintifik Darjah 6', type: 'multiple_choice', emoji: '⚗️', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Langkah pertama kaedah saintifik?', options: ['Hipotesis','Eksperimen','Mengenal pasti masalah'], answer: 2 },
    { problem: 'Hipotesis ialah?', options: ['Keputusan eksperimen','Andaian yang perlu diuji','Peralatan yang digunakan'], answer: 1 },
    { problem: 'Pembolehubah yang diubah ialah?', options: ['Pembolehubah dimanipulasi','Pembolehubah bergerakbalas','Pembolehubah kawalan'], answer: 0 },
    { problem: 'Data dikumpul melalui?', options: ['Hipotesis','Pemerhatian','Kesimpulan'], answer: 1 },
    { problem: 'Kesimpulan dibuat selepas?', options: ['Hipotesis','Eksperimen','Menganalisis data'], answer: 2 },
    { problem: 'Alat ukur suhu?', options: ['Pembaris','Termometer','Jangka masa'], answer: 1 },
    { problem: 'Alat ukur jisim?', options: ['Neraca','Pembaris','Jangka tukul'], answer: 0 },
    { problem: 'Alat ukur isipadu cecair?', options: ['Bikar','Pembaris','Neraca'], answer: 0 },
  ]}},
];