export const prasekolah_mathematics = [
  { title: 'Kira 1 hingga 5', type: 'counting', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['1','2','3'], answer: 0 },
    { image: '🍎🍎', options: ['1','2','3'], answer: 1 },
    { image: '🍎🍎🍎', options: ['2','3','4'], answer: 1 },
    { image: '🍎🍎🍎🍎', options: ['3','4','5'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎', options: ['4','5','6'], answer: 1 },
    { image: '🌟🌟', options: ['1','2','3'], answer: 1 },
    { image: '🌟🌟🌟', options: ['2','3','4'], answer: 1 },
    { image: '🌟🌟🌟🌟', options: ['3','4','5'], answer: 1 },
  ]}},
  { title: 'Kira 6 hingga 10', type: 'counting', emoji: '🔟', difficulty: 'easy', gameData: { questions: [
    { image: '🍎🍎🍎🍎🍎🍎', options: ['5','6','7'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎', options: ['6','7','8'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎', options: ['7','8','9'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['8','9','10'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['9','10','11'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
  ]}},
  { title: 'Nombor 1 hingga 10', type: 'number_match', emoji: '1️⃣', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐', options: ['1','2','3'], answer: 0 },
    { problem: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['1','2','3'], answer: 2 },
    { problem: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['4','5','6'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
  ]}},
  { title: 'Tambah 1+1 hingga 5+5', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '1+1', options: ['3','2','4','1'], answer: 1 },
    { problem: '2+1', options: ['4','3','5','2'], answer: 1 },
    { problem: '1+2', options: ['4','3','5','2'], answer: 1 },
    { problem: '2+2', options: ['6','4','5','3'], answer: 1 },
    { problem: '3+1', options: ['6','4','5','2'], answer: 1 },
    { problem: '2+3', options: ['7','5','6','4'], answer: 1 },
    { problem: '4+1', options: ['7','5','6','4'], answer: 1 },
    { problem: '3+3', options: ['7','6','8','5'], answer: 1 },
  ]}},
  { title: 'Bentuk Geometri Mudah', type: 'shape_sort', emoji: '🔵', difficulty: 'easy', gameData: { questions: [
    { image: '⭕', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 0 },
    { image: '⬜', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 2 },
    { image: '▭', options: ['Segiempat Tepat','Segi Empat','Bujur'], answer: 0 },
    { image: '⭐', options: ['Bintang','Bulatan','Segi Tiga'], answer: 0 },
    { image: '🔶', options: ['Berlian','Heksagon','Segi Empat'], answer: 0 },
    { image: '🔷', options: ['Berlian','Bujur','Segi Tiga'], answer: 0 },
    { image: '🔴', options: ['Bola','Bulatan','Cakera'], answer: 1 },
  ]}},
  { title: 'Lebih Besar atau Lebih Kecil', type: 'math_puzzle', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: '3 atau 5?', options: ['3 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '7 atau 4?', options: ['7 lebih besar','4 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 2?', options: ['2 lebih besar','2 lebih kecil','Sama'], answer: 2 },
    { problem: '1 atau 9?', options: ['1 lebih besar','9 lebih besar','Sama'], answer: 1 },
    { problem: '6 atau 3?', options: ['6 lebih besar','3 lebih besar','Sama'], answer: 0 },
    { problem: '5 atau 8?', options: ['5 lebih besar','8 lebih besar','Sama'], answer: 1 },
    { problem: '4 atau 4?', options: ['4 lebih besar','4 lebih kecil','Sama'], answer: 2 },
    { problem: '10 atau 7?', options: ['10 lebih besar','7 lebih besar','Sama'], answer: 0 },
  ]}},
  { title: 'Tolak Mudah', type: 'math_puzzle', emoji: '➖', difficulty: 'easy', gameData: { questions: [
    { problem: '3-1', options: ['1','2','3','4'], answer: 1 },
    { problem: '5-2', options: ['2','3','4','5'], answer: 1 },
    { problem: '4-1', options: ['2','3','4','5'], answer: 1 },
    { problem: '6-3', options: ['2','3','4','5'], answer: 1 },
    { problem: '7-2', options: ['4','5','6','7'], answer: 1 },
    { problem: '8-4', options: ['3','4','5','6'], answer: 1 },
    { problem: '9-3', options: ['5','6','7','8'], answer: 1 },
    { problem: '10-5', options: ['4','5','6','7'], answer: 1 },
  ]}},
  { title: 'Susunan Nombor', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: 'Selepas 3 ialah?', options: ['2','4','5','3'], answer: 1 },
    { problem: 'Selepas 6 ialah?', options: ['5','7','8','6'], answer: 1 },
    { problem: 'Sebelum 5 ialah?', options: ['6','4','3','5'], answer: 1 },
    { problem: 'Sebelum 9 ialah?', options: ['10','8','7','9'], answer: 1 },
    { problem: 'Antara 4 dan 6?', options: ['3','5','7','4'], answer: 1 },
    { problem: 'Antara 1 dan 3?', options: ['0','2','4','1'], answer: 1 },
    { problem: 'Selepas 8 ialah?', options: ['7','9','10','8'], answer: 1 },
    { problem: 'Sebelum 2 ialah?', options: ['3','1','0','2'], answer: 1 },
  ]}},
  { title: 'Wang Syiling Kecil', type: 'counting', emoji: '💰', difficulty: 'medium', gameData: { questions: [
    { image: '🪙', options: ['10 sen','20 sen','50 sen'], answer: 0 },
    { image: '🪙🪙', options: ['10 sen','20 sen','30 sen'], answer: 1 },
    { image: '🪙🪙🪙', options: ['20 sen','30 sen','40 sen'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙', options: ['40 sen','50 sen','60 sen'], answer: 1 },
    { image: '💵', options: ['RM 1','RM 2','RM 5'], answer: 0 },
    { image: '💵💵', options: ['RM 1','RM 2','RM 3'], answer: 1 },
    { image: '💵💵💵', options: ['RM 2','RM 3','RM 4'], answer: 1 },
    { image: '💵💵💵💵💵', options: ['RM 4','RM 5','RM 6'], answer: 1 },
  ]}},
  { title: 'Corak dan Urutan', type: 'pattern_fill', emoji: '🔷', difficulty: 'medium', gameData: { questions: [
    { problem: '🔴🔵🔴🔵?', options: ['🔴','🔵','🟢'], answer: 0 },
    { problem: '⭐🌙⭐🌙?', options: ['⭐','🌙','☀️'], answer: 0 },
    { problem: '1, 2, 3, ?', options: ['3','4','5'], answer: 1 },
    { problem: '2, 4, 6, ?', options: ['7','8','9'], answer: 1 },
    { problem: '🔺🔺🔵🔺🔺?', options: ['🔺','🔵','🔷'], answer: 1 },
    { problem: '5, 10, 15, ?', options: ['18','20','25'], answer: 1 },
    { problem: '🟡🟡🔴🟡🟡?', options: ['🟡','🔴','🔵'], answer: 1 },
    { problem: '1, 3, 5, ?', options: ['6','7','8'], answer: 1 },
  ]}},
  { title: 'Nombor 11 hingga 20', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '11 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 0 },
    { problem: '12 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 1 },
    { problem: '15 biji epal', options: ['Empat Belas','Lima Belas','Enam Belas'], answer: 1 },
    { problem: '17 biji epal', options: ['Enam Belas','Tujuh Belas','Lapan Belas'], answer: 1 },
    { problem: '20 biji epal', options: ['Sembilan Belas','Dua Puluh','Dua Puluh Satu'], answer: 1 },
    { problem: 'Lima belas = ?', options: ['14','15','16'], answer: 1 },
    { problem: 'Dua belas = ?', options: ['11','12','13'], answer: 1 },
    { problem: 'Dua puluh = ?', options: ['19','20','21'], answer: 1 },
  ]}},
  { title: 'Tambah hingga 10', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '4+5', options: ['7','9','8','10'], answer: 1 },
    { problem: '3+6', options: ['7','9','8','10'], answer: 1 },
    { problem: '5+4', options: ['7','9','8','10'], answer: 1 },
    { problem: '6+4', options: ['9','10','11','8'], answer: 1 },
    { problem: '7+3', options: ['9','10','11','8'], answer: 1 },
    { problem: '8+2', options: ['9','10','11','8'], answer: 1 },
    { problem: '5+5', options: ['9','10','11','8'], answer: 1 },
    { problem: '3+7', options: ['9','10','11','8'], answer: 1 },
  ]}},
  { title: 'Pasangan Nombor Sama', type: 'number_match', emoji: '🎯', difficulty: 'easy', gameData: { questions: [
    { problem: 'Lima = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Tiga = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Lapan = ?', options: ['7','8','9'], answer: 1 },
    { problem: 'Satu = ?', options: ['1','2','3'], answer: 0 },
    { problem: 'Sepuluh = ?', options: ['8','9','10'], answer: 2 },
    { problem: 'Dua = ?', options: ['1','2','3'], answer: 1 },
    { problem: 'Tujuh = ?', options: ['6','7','8'], answer: 1 },
    { problem: 'Sembilan = ?', options: ['8','9','10'], answer: 1 },
  ]}},
  { title: 'Bahagi Mudah', type: 'math_puzzle', emoji: '➗', difficulty: 'medium', gameData: { questions: [
    { problem: '4÷2', options: ['1','2','3'], answer: 1 },
    { problem: '6÷2', options: ['2','3','4'], answer: 1 },
    { problem: '6÷3', options: ['1','2','3'], answer: 2 },
    { problem: '8÷2', options: ['3','4','5'], answer: 1 },
    { problem: '10÷2', options: ['4','5','6'], answer: 1 },
    { problem: '9÷3', options: ['2','3','4'], answer: 1 },
    { problem: '4÷4', options: ['1','2','3'], answer: 0 },
    { problem: '10÷5', options: ['1','2','3'], answer: 1 },
  ]}},
  { title: 'Masa - Jam', type: 'multiple_choice', emoji: '⏰', difficulty: 'easy', gameData: { questions: [
    { problem: '1 jam = berapa minit?', options: ['30','60','100'], answer: 1 },
    { problem: 'Pagi bermula pada?', options: ['12 malam','12 tengahari','6 pagi'], answer: 2 },
    { problem: 'Tengahari pada pukul?', options: ['10 pagi','12 tengahari','2 petang'], answer: 1 },
    { problem: 'Malam bermula selepas?', options: ['Pagi','Tengahari','Petang'], answer: 2 },
    { problem: 'Separuh jam = berapa minit?', options: ['15','30','45'], answer: 1 },
    { problem: '1 hari = berapa jam?', options: ['12','24','48'], answer: 1 },
    { problem: 'Pukul 3 petang - 2 jam kemudian?', options: ['Pukul 4','Pukul 5','Pukul 6'], answer: 1 },
    { problem: 'Subuh adalah waktu?', options: ['Malam','Awal pagi','Petang'], answer: 1 },
  ]}},
  { title: 'Darab Mudah ×2 dan ×5', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', gameData: { questions: [
    { problem: '2×2', options: ['2','4','6'], answer: 1 },
    { problem: '2×3', options: ['4','6','8'], answer: 1 },
    { problem: '2×4', options: ['6','8','10'], answer: 1 },
    { problem: '2×5', options: ['8','10','12'], answer: 1 },
    { problem: '5×1', options: ['4','5','6'], answer: 1 },
    { problem: '5×2', options: ['8','10','12'], answer: 1 },
    { problem: '5×3', options: ['13','15','17'], answer: 1 },
    { problem: '5×4', options: ['18','20','22'], answer: 1 },
  ]}},
  { title: 'Ukuran - Panjang Pendek', type: 'multiple_choice', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: 'Mana lebih panjang?', options: ['Pensel','Pembaris','Sama'], answer: 1 },
    { problem: 'Mana lebih pendek?', options: ['Jari','Tangan','Sama'], answer: 0 },
    { problem: 'Mana lebih tinggi?', options: ['Kerusi','Meja','Sama'], answer: 1 },
    { problem: 'Mana lebih rendah?', options: ['Semut','Gajah','Sama'], answer: 0 },
    { problem: 'Mana lebih besar?', options: ['Kucing','Singa','Sama'], answer: 1 },
    { problem: 'Mana lebih kecil?', options: ['Gajah','Tikus','Sama'], answer: 1 },
    { problem: 'Mana lebih berat?', options: ['Buku','Pensel','Sama'], answer: 0 },
    { problem: 'Mana lebih ringan?', options: ['Batu','Bulu','Sama'], answer: 1 },
  ]}},
  { title: 'Nombor Ganjil dan Genap', type: 'multiple_choice', emoji: '🔢', difficulty: 'medium', gameData: { questions: [
    { problem: '2 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '3 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '4 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '7 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '10 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '5 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '8 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '1 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
  ]}},
  { title: 'Tolak hingga 20', type: 'math_puzzle', emoji: '➖', difficulty: 'medium', gameData: { questions: [
    { problem: '10-6', options: ['3','4','5'], answer: 1 },
    { problem: '12-5', options: ['6','7','8'], answer: 1 },
    { problem: '15-8', options: ['6','7','8'], answer: 1 },
    { problem: '18-9', options: ['8','9','10'], answer: 1 },
    { problem: '20-10', options: ['9','10','11'], answer: 1 },
    { problem: '14-7', options: ['6','7','8'], answer: 1 },
    { problem: '16-8', options: ['7','8','9'], answer: 1 },
    { problem: '11-4', options: ['6','7','8'], answer: 1 },
  ]}},
  { title: 'Berat - Ringan Berat', type: 'multiple_choice', emoji: '⚖️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Gajah atau semut — mana lebih berat?', options: ['Semut','Gajah','Sama'], answer: 1 },
    { problem: 'Batu atau kapas — mana lebih ringan?', options: ['Batu','Kapas','Sama'], answer: 1 },
    { problem: '1 kg atau 2 kg — mana lebih berat?', options: ['1 kg','2 kg','Sama'], answer: 1 },
    { problem: 'Kereta atau basikal — mana lebih berat?', options: ['Kereta','Basikal','Sama'], answer: 0 },
    { problem: 'Buku atau pensel — mana lebih berat?', options: ['Pensel','Buku','Sama'], answer: 1 },
    { problem: '500g atau 1kg — mana lebih ringan?', options: ['500g','1kg','Sama'], answer: 0 },
    { problem: 'Kamus atau buku cerita — mana lebih berat?', options: ['Buku cerita','Kamus','Sama'], answer: 1 },
    { problem: 'Cikgu atau murid — mana lebih berat biasanya?', options: ['Murid','Cikgu','Sama'], answer: 1 },
  ]}},
];