export const sekolah_science = [
  { title: 'Anggota Badan Manusia', type: 'picture_quiz', emoji: '🧠', difficulty: 'medium', gameData: { questions: [
    { image: '👁️', options: ['Mata','Hidung','Telinga'], answer: 0 },
    { image: '👃', options: ['Mata','Hidung','Telinga'], answer: 1 },
    { image: '👂', options: ['Mata','Hidung','Telinga'], answer: 2 },
    { image: '👅', options: ['Lidah','Gigi','Bibir'], answer: 0 },
    { image: '🦷', options: ['Lidah','Gigi','Bibir'], answer: 1 },
    { image: '👄', options: ['Lidah','Gigi','Bibir'], answer: 2 },
    { image: '🧠', options: ['Otak','Jantung','Paru'], answer: 0 },
    { image: '❤️', options: ['Otak','Jantung','Paru'], answer: 1 },
  ]}},
  { title: 'Cuaca & Musim', type: 'picture_quiz', emoji: '☀️', difficulty: 'medium', gameData: { questions: [
    { image: '☀️', options: ['Panas','Sejuk','Hujan'], answer: 0 },
    { image: '❄️', options: ['Panas','Sejuk','Hujan'], answer: 1 },
    { image: '🌧️', options: ['Panas','Sejuk','Hujan'], answer: 2 },
    { image: '⛅', options: ['Awan','Panas','Gelap'], answer: 0 },
    { image: '🌩️', options: ['Ribut','Tenang','Berangin'], answer: 0 },
    { image: '🌈', options: ['Pelangi','Matahari','Hujan'], answer: 0 },
    { image: '🌬️', options: ['Angin','Hujan','Panas'], answer: 0 },
    { image: '💨', options: ['Angin Kencang','Hujan','Panas'], answer: 0 },
  ]}},
  { title: 'Sistem Suria', type: 'picture_quiz', emoji: '🌍', difficulty: 'medium', gameData: { questions: [
    { image: '☀️', options: ['Bumi','Matahari','Bulan'], answer: 1 },
    { image: '🌍', options: ['Bumi','Marikh','Musytari'], answer: 0 },
    { image: '🌙', options: ['Planet','Bulan','Bintang'], answer: 1 },
    { image: '⭐', options: ['Satelit','Planet','Bintang'], answer: 2 },
    { image: '🔴', options: ['Bumi','Marikh','Zuhal'], answer: 1 },
    { image: '🪐', options: ['Bumi','Marikh','Zuhal'], answer: 2 },
    { image: '🌑', options: ['Gerhana','Bulan Penuh','Bulan Baru'], answer: 2 },
    { image: '🌕', options: ['Bulan Baru','Bulan Penuh','Bintang'], answer: 1 },
  ]}},
  { title: 'Kitaran Air', type: 'picture_quiz', emoji: '💧', difficulty: 'medium', gameData: { questions: [
    { image: '☀️💧', options: ['Penyejatan','Pemendapan','Pemeluwapan'], answer: 0 },
    { image: '☁️💧', options: ['Penyejatan','Pemendapan','Pemeluwapan'], answer: 2 },
    { image: '🌧️', options: ['Penyejatan','Hujan/Pemendapan','Pemeluwapan'], answer: 1 },
    { image: '🌊➡️☁️', options: ['Penyejatan','Pemendapan','Pengaliran'], answer: 0 },
    { image: '💧🌱', options: ['Air diserap tumbuhan','Air menguap','Air mengalir'], answer: 0 },
    { image: '❄️➡️💧', options: ['Pembekuan','Pencairan','Pengewapan'], answer: 1 },
    { image: '💧➡️❄️', options: ['Pembekuan','Pencairan','Pengewapan'], answer: 0 },
    { image: '🌊🏞️', options: ['Laut','Sungai','Tasik'], answer: 1 },
  ]}},
  { title: 'Jenis-Jenis Haiwan', type: 'picture_quiz', emoji: '🦁', difficulty: 'medium', gameData: { questions: [
    { image: '🐟', options: ['Mamalia','Ikan','Reptilia'], answer: 1 },
    { image: '🐸', options: ['Amfibia','Ikan','Reptilia'], answer: 0 },
    { image: '🐍', options: ['Mamalia','Amfibia','Reptilia'], answer: 2 },
    { image: '🐦', options: ['Mamalia','Burung','Reptilia'], answer: 1 },
    { image: '🐘', options: ['Mamalia','Reptilia','Burung'], answer: 0 },
    { image: '🦋', options: ['Cacing','Serangga','Amfibia'], answer: 1 },
    { image: '🐢', options: ['Amfibia','Ikan','Reptilia'], answer: 2 },
    { image: '🦇', options: ['Mamalia','Burung','Serangga'], answer: 0 },
  ]}},
  { title: 'Bahan dan Sifatnya', type: 'multiple_choice', emoji: '🧪', difficulty: 'medium', gameData: { questions: [
    { problem: 'Besi adalah bahan yang...', options: ['Lembut','Keras','Elastik'], answer: 1 },
    { problem: 'Air adalah bahan yang...', options: ['Pepejal','Cecair','Gas'], answer: 1 },
    { problem: 'Kayu adalah bahan yang...', options: ['Logam','Bukan Logam','Cecair'], answer: 1 },
    { problem: 'Udara adalah dalam keadaan...', options: ['Pepejal','Cecair','Gas'], answer: 2 },
    { problem: 'Ais adalah keadaan...', options: ['Pepejal','Cecair','Gas'], answer: 0 },
    { problem: 'Getah boleh meregang, ini sifatnya...', options: ['Keras','Elastik','Tegar'], answer: 1 },
    { problem: 'Bahan manakah yang boleh mengalir?', options: ['Besi','Air','Batu'], answer: 1 },
    { problem: 'Bahan manakah yang boleh menyalur elektrik?', options: ['Kayu','Plastik','Tembaga'], answer: 2 },
  ]}},
  { title: 'Tenaga di Sekeliling Kita', type: 'multiple_choice', emoji: '⚡', difficulty: 'medium', gameData: { questions: [
    { problem: 'Sumber tenaga matahari dikenali sebagai?', options: ['Tenaga Angin','Tenaga Solar','Tenaga Air'], answer: 1 },
    { problem: 'Kipas angin menggunakan tenaga...', options: ['Tenaga Panas','Tenaga Elektrik','Tenaga Bunyi'], answer: 1 },
    { problem: 'Lampu menghasilkan tenaga...', options: ['Tenaga Cahaya','Tenaga Haba','Semua betul'], answer: 2 },
    { problem: 'Tayar kereta menggunakan tenaga...', options: ['Tenaga Kimia','Tenaga Kinetik','Tenaga Cahaya'], answer: 1 },
    { problem: 'Bateri menyimpan tenaga...', options: ['Tenaga Kimia','Tenaga Solar','Tenaga Angin'], answer: 0 },
    { problem: 'Matahari adalah sumber tenaga...', options: ['Tidak boleh dibaharui','Boleh dibaharui','Tidak bertenaga'], answer: 1 },
    { problem: 'Petrol adalah bahan...', options: ['Boleh dibaharui','Tidak boleh dibaharui','Tenaga bersih'], answer: 1 },
    { problem: 'Tenaga yang menghasilkan bunyi dipanggil?', options: ['Tenaga Haba','Tenaga Bunyi','Tenaga Cahaya'], answer: 1 },
  ]}},
  { title: 'Ekosistem & Rantai Makanan', type: 'multiple_choice', emoji: '🌿', difficulty: 'hard', gameData: { questions: [
    { problem: 'Tumbuhan dalam rantai makanan ialah...', options: ['Pengguna','Pengeluar','Pengurai'], answer: 1 },
    { problem: 'Harimau dalam rantai makanan ialah...', options: ['Pengeluar','Pengguna','Pengurai'], answer: 1 },
    { problem: 'Cacing dalam ekosistem berfungsi sebagai...', options: ['Pengguna','Pengeluar','Pengurai'], answer: 2 },
    { problem: 'Rantai makanan bermula dengan...', options: ['Haiwan','Tumbuhan','Kulat'], answer: 1 },
    { problem: 'Arnab memakan rumput. Arnab ialah...', options: ['Herbivor','Karnivor','Omnivor'], answer: 0 },
    { problem: 'Singa memakan daging. Singa ialah...', options: ['Herbivor','Karnivor','Omnivor'], answer: 1 },
    { problem: 'Manusia makan sayur dan daging. Manusia ialah...', options: ['Herbivor','Karnivor','Omnivor'], answer: 2 },
    { problem: 'Pokok → Ulat → Burung. Siapa pengguna pertama?', options: ['Pokok','Ulat','Burung'], answer: 1 },
  ]}},
  { title: 'Sistem Tubuh Manusia', type: 'multiple_choice', emoji: '🏃', difficulty: 'hard', gameData: { questions: [
    { problem: 'Sistem yang menggerakkan badan?', options: ['Sistem Penghadaman','Sistem Rangka & Otot','Sistem Pernafasan'], answer: 1 },
    { problem: 'Sistem yang memproses makanan?', options: ['Sistem Penghadaman','Sistem Saraf','Sistem Rangka'], answer: 0 },
    { problem: 'Paru-paru adalah sebahagian dari sistem?', options: ['Peredaran Darah','Pernafasan','Penghadaman'], answer: 1 },
    { problem: 'Jantung adalah sebahagian dari sistem?', options: ['Peredaran Darah','Pernafasan','Penghadaman'], answer: 0 },
    { problem: 'Otak adalah pusat kawalan sistem?', options: ['Penghadaman','Saraf','Peredaran Darah'], answer: 1 },
    { problem: 'Tulang melindungi organ penting. Ini fungsi sistem?', options: ['Rangka','Otot','Saraf'], answer: 0 },
    { problem: 'Kita bernafas dengan?', options: ['Jantung','Paru-paru','Hati'], answer: 1 },
    { problem: 'Darah dipam oleh?', options: ['Paru-paru','Jantung','Hati'], answer: 1 },
  ]}},
  { title: 'Teknologi dalam Sains', type: 'picture_quiz', emoji: '🔬', difficulty: 'medium', gameData: { questions: [
    { image: '🔬', options: ['Mikroskop - lihat benda kecil','Teleskop - lihat bintang','Kamera'], answer: 0 },
    { image: '🔭', options: ['Mikroskop','Teleskop - lihat benda jauh','Kompas'], answer: 1 },
    { image: '🧲', options: ['Magnet - tarik logam','Wayar','Cermin'], answer: 0 },
    { image: '💡', options: ['Tenaga Haba','Tenaga Cahaya','Tenaga Bunyi'], answer: 1 },
    { image: '☀️🔋', options: ['Panel Solar','Pemanas','Penjana'], answer: 0 },
    { image: '🌡️', options: ['Termometer','Barometer','Higrometer'], answer: 0 },
    { image: '⚖️', options: ['Neraca - ukur jisim','Pembaris','Jam'], answer: 0 },
    { image: '📡', options: ['Antena - isyarat','Teleskop','Radar'], answer: 0 },
  ]}},
  { title: 'Proses Sains - Pembiakan', type: 'multiple_choice', emoji: '🌱', difficulty: 'medium', gameData: { questions: [
    { problem: 'Tumbuhan berbunga membiak melalui?', options: ['Spora','Biji benih','Keratan'], answer: 1 },
    { problem: 'Kucing membiak melalui?', options: ['Telur','Beranak','Bercambah'], answer: 1 },
    { problem: 'Ayam membiak melalui?', options: ['Beranak','Telur','Bercambah'], answer: 1 },
    { problem: 'Pokok pisang boleh membiak melalui?', options: ['Biji benih','Tunas','Spora'], answer: 1 },
    { problem: 'Kulat membiak melalui?', options: ['Biji benih','Spora','Beranak'], answer: 1 },
    { problem: 'Ikan membiak melalui?', options: ['Beranak','Telur','Bercambah'], answer: 1 },
    { problem: 'Pokok melalui proses fotosintesis memerlukan?', options: ['Udara sahaja','Cahaya matahari, air, dan CO2','Air sahaja'], answer: 1 },
    { problem: 'Benih bercambah memerlukan?', options: ['Cahaya sahaja','Air, udara, dan suhu sesuai','Tanah sahaja'], answer: 1 },
  ]}},
  { title: 'Cahaya dan Bunyi', type: 'multiple_choice', emoji: '💡', difficulty: 'medium', gameData: { questions: [
    { problem: 'Cahaya bergerak dalam?', options: ['Garis bengkok','Garis lurus','Garis bulat'], answer: 1 },
    { problem: 'Bunyi memerlukan ___ untuk bergerak?', options: ['Vakum','Medium','Cahaya'], answer: 1 },
    { problem: 'Bunyi TIDAK boleh bergerak melalui?', options: ['Udara','Air','Vakum'], answer: 2 },
    { problem: 'Cermin memantulkan?', options: ['Bunyi','Cahaya','Haba'], answer: 1 },
    { problem: 'Warna pelangi mengikut turutan?', options: ['MEJKBHUI','MEJIKHBU','MEJAKBHI'], answer: 0 },
    { problem: 'Sumber cahaya semula jadi?', options: ['Lampu','Matahari','Lilin'], answer: 1 },
    { problem: 'Gema adalah pantulan?', options: ['Cahaya','Bunyi','Haba'], answer: 1 },
    { problem: 'Bahan yang membenarkan cahaya lalu sepenuhnya?', options: ['Legap','Lutsinar','Lut sinar'], answer: 2 },
  ]}},
  { title: 'Daya dan Gerakan', type: 'multiple_choice', emoji: '⚙️', difficulty: 'hard', gameData: { questions: [
    { problem: 'Daya tarikan bumi dipanggil?', options: ['Daya Magnet','Graviti','Daya Tolak'], answer: 1 },
    { problem: 'Benda jatuh ke bawah kerana?', options: ['Angin','Graviti','Magnet'], answer: 1 },
    { problem: 'Geseran menyebabkan?', options: ['Kelajuan','Haba dan perlambatan','Daya lebih'], answer: 1 },
    { problem: 'Magnet menarik bahan?', options: ['Semua logam','Logam besi','Semua benda'], answer: 1 },
    { problem: 'Kutub magnet yang sama akan?', options: ['Tarik menarik','Tolak menolak','Tiada kesan'], answer: 1 },
    { problem: 'Kutub magnet yang berbeza akan?', options: ['Tarik menarik','Tolak menolak','Tiada kesan'], answer: 0 },
    { problem: 'Daya yang diperlukan untuk menggerakkan benda?', options: ['Tenaga','Daya','Kerja'], answer: 1 },
    { problem: 'Mesin mudah yang membantu kerja?', options: ['Tayar','Tuas','Bateri'], answer: 1 },
  ]}},
  { title: 'Alam Sekitar dan Pemuliharaan', type: 'multiple_choice', emoji: '🌍', difficulty: 'medium', gameData: { questions: [
    { problem: 'Pencemaran udara disebabkan oleh?', options: ['Pokok banyak','Asap kilang dan kenderaan','Hujan lebat'], answer: 1 },
    { problem: 'Cara terbaik kurangkan sampah?', options: ['Bakar sampah','3R: Reduce, Reuse, Recycle','Buang ke sungai'], answer: 1 },
    { problem: 'Pemanasan global disebabkan oleh?', options: ['Gas rumah hijau berlebihan','Terlalu banyak pokok','Hujan lebat'], answer: 0 },
    { problem: 'Cara jimat air?', options: ['Biarkan air mengalir','Tutup paip bila tidak guna','Mandi lama'], answer: 1 },
    { problem: 'Penebangan hutan menyebabkan?', options: ['Lebih hujan','Lebih oksigen','Banjir dan hakisan'], answer: 2 },
    { problem: 'Cara jimat elektrik?', options: ['Biarkan lampu terbuka','Padam lampu bila keluar','Guna lebih alatan'], answer: 1 },
    { problem: 'Bahan kitar semula yang betul?', options: ['Sisa makanan','Botol plastik','Tulang'], answer: 1 },
    { problem: 'Apa yang boleh ditanam untuk bantu alam sekitar?', options: ['Pokok','Plastik','Besi'], answer: 0 },
  ]}},
  { title: 'Sumber Alam dan Penggunaan', type: 'multiple_choice', emoji: '🌏', difficulty: 'medium', gameData: { questions: [
    { problem: 'Sumber alam yang tidak boleh dibaharui?', options: ['Pokok','Petroleum','Angin'], answer: 1 },
    { problem: 'Sumber alam yang boleh dibaharui?', options: ['Arang batu','Minyak semulajadi','Tenaga solar'], answer: 2 },
    { problem: 'Air adalah sumber alam yang?', options: ['Tidak terhad','Terhad dan perlu dijaga','Tidak penting'], answer: 1 },
    { problem: 'Penggunaan tenaga solar adalah?', options: ['Mencemarkan','Mesra alam','Mahal dan berbahaya'], answer: 1 },
    { problem: 'Mengapa kita perlu jimat sumber alam?', options: ['Untuk berseronok','Untuk generasi akan datang','Untuk menjual'], answer: 1 },
    { problem: 'Pertanian organik adalah?', options: ['Menggunakan banyak baja kimia','Tidak menggunakan racun dan baja kimia','Lebih mahal sahaja'], answer: 1 },
    { problem: 'Cara kitar semula kertas membantu?', options: ['Kurangkan penebangan pokok','Tambah pokok','Bersihkan air'], answer: 0 },
    { problem: 'Biodiversiti bermaksud?', options: ['Kepelbagaian spesies hidupan','Pencemaran alam','Penebangan hutan'], answer: 0 },
  ]}},
  { title: 'Sains Bahan - Pepejal Cecair Gas', type: 'multiple_choice', emoji: '🧪', difficulty: 'medium', gameData: { questions: [
    { problem: 'Batu adalah dalam keadaan?', options: ['Pepejal','Cecair','Gas'], answer: 0 },
    { problem: 'Jus oren adalah dalam keadaan?', options: ['Pepejal','Cecair','Gas'], answer: 1 },
    { problem: 'Oksigen adalah dalam keadaan?', options: ['Pepejal','Cecair','Gas'], answer: 2 },
    { problem: 'Apabila air dipanaskan, ia berubah menjadi?', options: ['Ais','Wap air','Batu'], answer: 1 },
    { problem: 'Apabila air dibekukan, ia berubah menjadi?', options: ['Ais','Wap air','Batu'], answer: 0 },
    { problem: 'Pepejal mempunyai bentuk yang?', options: ['Sentiasa berubah','Tetap','Tiada bentuk'], answer: 1 },
    { problem: 'Cecair mengikut bentuk?', options: ['Bekas yang mengisinya','Bentuk sendiri','Tiada bentuk'], answer: 0 },
    { problem: 'Gas mengisi seluruh?', options: ['Sebahagian bekas','Seluruh bekas','Tiada'], answer: 1 },
  ]}},
  { title: 'Haiwan Vertebrata dan Invertebrata', type: 'multiple_choice', emoji: '🦴', difficulty: 'hard', gameData: { questions: [
    { problem: 'Haiwan bertulang belakang dipanggil?', options: ['Invertebrata','Vertebrata','Serangga'], answer: 1 },
    { problem: 'Haiwan tidak bertulang belakang dipanggil?', options: ['Vertebrata','Reptilia','Invertebrata'], answer: 2 },
    { problem: 'Ikan adalah?', options: ['Vertebrata','Invertebrata','Serangga'], answer: 0 },
    { problem: 'Siput adalah?', options: ['Vertebrata','Invertebrata','Amfibia'], answer: 1 },
    { problem: 'Katak adalah kelas?', options: ['Mamalia','Reptilia','Amfibia'], answer: 2 },
    { problem: 'Burung bertelur — ini ciri?', options: ['Mamalia','Burung','Reptilia'], answer: 1 },
    { problem: 'Ular bersisik — ini ciri?', options: ['Mamalia','Burung','Reptilia'], answer: 2 },
    { problem: 'Manusia menyusukan anak — ini ciri?', options: ['Mamalia','Burung','Amfibia'], answer: 0 },
  ]}},
  { title: 'Eksperimen Sains Mudah', type: 'multiple_choice', emoji: '⚗️', difficulty: 'medium', gameData: { questions: [
    { problem: 'Dalam eksperimen, pembolehubah yang diubah ialah?', options: ['Pembolehubah dimanipulasi','Pembolehubah bergerakbalas','Pembolehubah kawalan'], answer: 0 },
    { problem: 'Hipotesis ialah?', options: ['Keputusan eksperimen','Andaian yang perlu diuji','Peralatan yang digunakan'], answer: 1 },
    { problem: 'Alat ukur suhu?', options: ['Pembaris','Termometer','Jangka masa'], answer: 1 },
    { problem: 'Alat ukur jisim?', options: ['Neraca','Pembaris','Jangka tukul'], answer: 0 },
    { problem: 'Alat ukur isipadu cecair?', options: ['Bikar','Pembaris','Neraca'], answer: 0 },
    { problem: 'Langkah pertama kaedah saintifik?', options: ['Hipotesis','Eksperimen','Mengenal pasti masalah'], answer: 2 },
    { problem: 'Data dikumpul melalui?', options: ['Hipotesis','Pemerhatian','Kesimpulan'], answer: 1 },
    { problem: 'Kesimpulan dibuat selepas?', options: ['Hipotesis','Eksperimen','Menganalisis data'], answer: 2 },
  ]}},
];