export const sekolah_bahasa_mandarin = [
  {
    title: '汉字认识 一到十 Darjah 1',
    type: 'letter_match',
    emoji: '🔤',
    difficulty: 'easy',
    darjah: 1,
    gameData: { questions: [
      { letter: '一', options: ['一', '二', '三', '四'], answer: 0 },
      { letter: '二', options: ['一', '二', '三', '四'], answer: 1 },
      { letter: '三', options: ['一', '二', '三', '四'], answer: 2 },
      { letter: '四', options: ['一', '二', '三', '四'], answer: 3 },
      { letter: '五', options: ['五', '六', '七', '八'], answer: 0 },
      { letter: '六', options: ['五', '六', '七', '八'], answer: 1 },
      { letter: '七', options: ['五', '六', '七', '八'], answer: 2 },
      { letter: '八', options: ['五', '六', '七', '八'], answer: 3 },
    ]}
  },
  {
    title: '动物词汇 Darjah 1',
    type: 'picture_quiz',
    emoji: '🐾',
    difficulty: 'easy',
    darjah: 1,
    gameData: { questions: [
      { image: '🐱', options: ['猫', '狗', '兔子'], answer: 0 },
      { image: '🐶', options: ['猫', '狗', '鸟'], answer: 1 },
      { image: '🐟', options: ['鱼', '螃蟹', '乌龟'], answer: 0 },
      { image: '🐔', options: ['鸭子', '鸡', '鹅'], answer: 1 },
      { image: '🐘', options: ['大象', '马', '斑马'], answer: 0 },
      { image: '🦁', options: ['狮子', '老虎', '熊'], answer: 0 },
      { image: '🐧', options: ['企鹅', '鸡', '鸭'], answer: 0 },
      { image: '🐰', options: ['兔子', '松鼠', '老鼠'], answer: 0 },
    ]}
  },
  {
    title: '问候语 Darjah 1',
    type: 'multiple_choice',
    emoji: '👋',
    difficulty: 'easy',
    darjah: 1,
    gameData: { questions: [
      { problem: '早上打招呼?', options: ['晚安', '早上好', '再见'], answer: 1 },
      { problem: '"你好"是什么意思?', options: ['再见', '你好', '谢谢'], answer: 1 },
      { problem: '"谢谢"的回答?', options: ['对不起', '不客气', '再见'], answer: 1 },
      { problem: '离开时说?', options: ['你好', '再见', '谢谢'], answer: 1 },
      { problem: '道歉时说?', options: ['谢谢', '对不起', '再见'], answer: 1 },
      { problem: '我 = ?', options: ['你', '我', '他'], answer: 1 },
      { problem: '你 = ?', options: ['我', '你', '他'], answer: 1 },
      { problem: '他/她 = ?', options: ['我', '你', '他/她'], answer: 2 },
    ]}
  },
  {
    title: '名词和动词 Darjah 2',
    type: 'multiple_choice',
    emoji: '📝',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: '哪个是名词?', options: ['跑', '书', '高兴'], answer: 1 },
      { problem: '哪个是动词?', options: ['桌子', '睡觉', '红色'], answer: 1 },
      { problem: '哪个是名词?', options: ['跳', '学校', '大'], answer: 1 },
      { problem: '哪个是动词?', options: ['绿色', '哭', '花'], answer: 1 },
      { problem: '哪个是名词?', options: ['树', '跑', '强'], answer: 0 },
      { problem: '哪个是动词?', options: ['小', '喝', '车'], answer: 1 },
      { problem: '哪个是名词?', options: ['飞', '鸟', '高'], answer: 1 },
      { problem: '哪个是动词?', options: ['河流', '游泳', '冷'], answer: 1 },
    ]}
  },
  {
    title: '颜色和形状 Darjah 2',
    type: 'picture_quiz',
    emoji: '🌈',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { image: '🔴', options: ['红色', '蓝色', '绿色'], answer: 0 },
      { image: '🔵', options: ['红色', '蓝色', '黄色'], answer: 1 },
      { image: '🟢', options: ['紫色', '绿色', '橙色'], answer: 1 },
      { image: '🟡', options: ['黄色', '橙色', '白色'], answer: 0 },
      { image: '⭕', options: ['正方形', '圆形', '三角形'], answer: 1 },
      { image: '⬜', options: ['圆形', '正方形', '三角形'], answer: 1 },
      { image: '△', options: ['圆形', '正方形', '三角形'], answer: 2 },
      { image: '⭐', options: ['星形', '叉形', '菱形'], answer: 0 },
    ]}
  },
  {
    title: '现在时态 Darjah 2',
    type: 'multiple_choice',
    emoji: '⏰',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: '她每天___学校。', options: ['去', '去了', '去过'], answer: 0 },
      { problem: '他们___足球。', options: ['踢了', '踢', '踢过'], answer: 1 },
      { problem: '他___一本书。', options: ['读', '读了', '读过'], answer: 0 },
      { problem: '我们是___。', options: ['朋友们', '朋友', '一个朋友'], answer: 1 },
      { problem: '狗跑___很快。', options: ['了', '着', '得'], answer: 2 },
      { problem: '鸟在天空___飞。', options: ['飞', '飞了', '飞着'], answer: 2 },
      { problem: '她___一只猫。', options: ['有', '有了', '拥有'], answer: 0 },
      { problem: '我___午饭吃米饭。', options: ['吃', '吃了', '吃着'], answer: 0 },
    ]}
  },
  {
    title: '反义词 Darjah 3',
    type: 'multiple_choice',
    emoji: '↔️',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '"大"的反义词?', options: ['小', '中', '长'], answer: 0 },
      { problem: '"热"的反义词?', options: ['温暖', '冷', '凉'], answer: 1 },
      { problem: '"黑暗"的反义词?', options: ['暗淡', '明亮', '昏暗'], answer: 1 },
      { problem: '"老"的反义词?', options: ['年轻', '成年', '青少年'], answer: 0 },
      { problem: '"上"的反义词?', options: ['去', '下', '落'], answer: 1 },
      { problem: '"白天"的反义词?', options: ['傍晚', '夜晚', '黎明'], answer: 1 },
      { problem: '"硬"的反义词?', options: ['软', '细', '光滑'], answer: 0 },
      { problem: '"快"的反义词?', options: ['晚', '慢', '快一点'], answer: 1 },
    ]}
  },
  {
    title: '声调练习 Darjah 3',
    type: 'multiple_choice',
    emoji: '🔊',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '"妈"是第几声?', options: ['一声', '二声', '三声'], answer: 0 },
      { problem: '"马"是第几声?', options: ['一声', '二声', '三声'], answer: 2 },
      { problem: '"骂"是第几声?', options: ['三声', '四声', '轻声'], answer: 1 },
      { problem: '"麻"是第几声?', options: ['一声', '二声', '三声'], answer: 1 },
      { problem: '一声是什么调?', options: ['上升调', '平调', '下降调'], answer: 1 },
      { problem: '四声是什么调?', options: ['平调', '升降调', '下降调'], answer: 2 },
      { problem: '"吗"是什么声?', options: ['一声', '轻声', '四声'], answer: 1 },
      { problem: '普通话有几个声调?', options: ['3', '4', '5'], answer: 1 },
    ]}
  },
  {
    title: '形容词和副词 Darjah 4',
    type: 'multiple_choice',
    emoji: '🎨',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '哪个是形容词?', options: ['跑', '书', '高兴'], answer: 2 },
      { problem: '哪个是副词?', options: ['桌子', '快速地', '红色'], answer: 1 },
      { problem: '哪个是形容词?', options: ['跳', '学校', '大'], answer: 2 },
      { problem: '哪个是副词?', options: ['绿色', '慢慢地', '花'], answer: 1 },
      { problem: '哪个是形容词?', options: ['树', '跑', '强壮'], answer: 2 },
      { problem: '哪个是副词?', options: ['小', '轻轻地', '车'], answer: 1 },
      { problem: '哪个是形容词?', options: ['飞', '鸟', '高'], answer: 2 },
      { problem: '哪个是副词?', options: ['河流', '游泳', '幸福地'], answer: 2 },
    ]}
  },
  {
    title: '介词用法 Darjah 4',
    type: 'multiple_choice',
    emoji: '📌',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '书___桌子上。', options: ['在', '从', '到'], answer: 0 },
      { problem: '猫躲___椅子下面。', options: ['在', '在', '到'], answer: 1 },
      { problem: '她住___吉隆坡。', options: ['到', '在', '从'], answer: 1 },
      { problem: '他把包放___门旁边。', options: ['在', '从', '到'], answer: 0 },
      { problem: '鸟飞___房子上面。', options: ['从', '在', '过'], answer: 2 },
      { problem: '她坐___朋友中间。', options: ['在', '从', '向'], answer: 0 },
      { problem: '他___8点到了。', options: ['在', '到', '从'], answer: 0 },
      { problem: '我们___星期一去学校。', options: ['在', '从', '到'], answer: 0 },
    ]}
  },
  {
    title: '同义词 Darjah 4',
    type: 'multiple_choice',
    emoji: '🔄',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '"高兴"的同义词?', options: ['难过', '快乐', '生气'], answer: 1 },
      { problem: '"大"的同义词?', options: ['小', '巨大', '微小'], answer: 1 },
      { problem: '"快"的同义词?', options: ['慢', '迅速', '懒'], answer: 1 },
      { problem: '"美丽"的同义词?', options: ['丑陋', '漂亮', '普通'], answer: 1 },
      { problem: '"聪明"的同义词?', options: ['笨', '聪颖', '傻'], answer: 1 },
      { problem: '"开始"的同义词?', options: ['结束', '开始着手', '停止'], answer: 1 },
      { problem: '"疲倦"的同义词?', options: ['精力充沛', '精疲力竭', '清醒'], answer: 1 },
      { problem: '"朋友"的同义词?', options: ['敌人', '同伴', '陌生人'], answer: 1 },
    ]}
  },
  {
    title: '将来时态 Darjah 5',
    type: 'multiple_choice',
    emoji: '🔮',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: '明天我___去学校。', options: ['去了', '将会去', '去着'], answer: 1 },
      { problem: '她___今晚煮饭。', options: ['煮了', '将会煮', '是'], answer: 1 },
      { problem: '他们___下周踢足球。', options: ['踢了', '将会踢', '踢着'], answer: 1 },
      { problem: '正确的句子?', options: ['我将会去了家', '我将会回家', '我回家将会'], answer: 1 },
      { problem: '"将会"用于什么时态?', options: ['过去', '将来', '现在'], answer: 1 },
      { problem: '她将会___（吃）?', options: ['吃了', '吃着', '吃'], answer: 2 },
      { problem: '他们将会___（玩）?', options: ['玩了', '玩着', '玩'], answer: 2 },
      { problem: '下周___发生什么?', options: ['已经发生', '将要发生', '正在发生'], answer: 1 },
    ]}
  },
  {
    title: '阅读理解 - 短文 Darjah 5',
    type: 'reading',
    emoji: '📚',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: '阿里有一只狗。狗是棕色的。狗是什么颜色?', options: ['黑色', '白色', '棕色'], answer: 2 },
      { problem: '西蒂每天吃苹果。西蒂吃什么?', options: ['橙子', '苹果', '香蕉'], answer: 1 },
      { problem: '太阳早上升起。太阳什么时候升起?', options: ['傍晚', '早上', '夜晚'], answer: 1 },
      { problem: '汤姆在图书馆读书。汤姆在哪里读书?', options: ['家', '学校', '图书馆'], answer: 2 },
      { problem: '鸟在天空飞翔。鸟在哪里飞?', options: ['海里', '天空', '地上'], answer: 1 },
      { problem: '她有两只猫和一只狗。共有几只宠物?', options: ['两只', '三只', '一只'], answer: 1 },
      { problem: '孩子们放学后玩耍。他们什么时候玩?', options: ['上学前', '放学后', '上学时'], answer: 1 },
      { problem: '约翰比阿里高。谁更高?', options: ['阿里', '约翰', '两个人一样'], answer: 1 },
    ]}
  },
  {
    title: '被动语态 Darjah 5',
    type: 'multiple_choice',
    emoji: '✍️',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: '主动: "阿里吃苹果。" 被动?', options: ['苹果被阿里吃了', '苹果吃了阿里', '阿里的苹果'], answer: 0 },
      { problem: '哪句是被动语态?', options: ['她读书', '书被她读了', '她在读书'], answer: 1 },
      { problem: '被动形式是?', options: ['我吃', '我被吃了', '吃'], answer: 1 },
      { problem: '"蛋糕被妈妈烤了" - 主语是?', options: ['妈妈', '蛋糕', '烤'], answer: 1 },
      { problem: '"信___他写的。"', options: ['是', '被', '让'], answer: 1 },
      { problem: '主动: "他们建了房子。" 被动?', options: ['房子建了他们', '房子被他们建了', '他们在建房'], answer: 1 },
      { problem: '"球___男孩踢了。"', options: ['是', '被', '让'], answer: 1 },
      { problem: '被动语态强调?', options: ['执行动作的人', '被做的事情', '时间'], answer: 1 },
    ]}
  },
  {
    title: '复合句 Darjah 5',
    type: 'multiple_choice',
    emoji: '📝',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: '复合句有几个分句?', options: ['一个', '两个或以上', '三个'], answer: 1 },
      { problem: '"虽然下雨，我们还是去了" - 分句类型?', options: ['独立分句', '从属分句', '两者都有'], answer: 2 },
      { problem: '并列句使用?', options: ['因为', '和，但，或', '如果'], answer: 1 },
      { problem: '"她努力学习并通过了" - 连词?', options: ['虽然', '因为', '并'], answer: 2 },
      { problem: '独立分句可以___?', options: ['从不', '独立存在', '不确定'], answer: 1 },
      { problem: '"如果你帮我，我会..." 是?', options: ['简单句', '复合句', '并列句'], answer: 1 },
      { problem: '从属连词?', options: ['和', '因为', '但'], answer: 1 },
      { problem: '"当铃声响起，离开" 是?', options: ['简单句', '并列句', '复合句'], answer: 2 },
    ]}
  },
  {
    title: '复合词 Darjah 6',
    type: 'word_builder',
    emoji: '🔗',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: '太 + 阳 = ?', options: ['太阳', '阳太', '阳光'], answer: 0 },
      { problem: '学 + 校 = ?', options: ['校学', '学校', '学生'], answer: 1 },
      { problem: '图 + 书馆 = ?', options: ['图书馆', '书馆图', '馆书图'], answer: 0 },
      { problem: '朋 + 友 = ?', options: ['朋友', '友朋', '朋伴'], answer: 0 },
      { problem: '电 + 脑 = ?', options: ['脑电', '电脑', '电话'], answer: 1 },
      { problem: '飞 + 机 = ?', options: ['机飞', '飞机', '飞鸟'], answer: 1 },
      { problem: '自 + 行车 = ?', options: ['行车自', '自行车', '自车行'], answer: 1 },
      { problem: '书 + 包 = ?', options: ['包书', '书包', '书本'], answer: 1 },
    ]}
  },
  {
    title: '人称代词 Darjah 6',
    type: 'multiple_choice',
    emoji: '❓',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: '代替"阿里": "___很高。"', options: ['她', '他', '它'], answer: 1 },
      { problem: '代替"西蒂": "___很聪明。"', options: ['他', '她', '它'], answer: 1 },
      { problem: '"___是你的名字?" - 问人', options: ['哪里', '什么', '谁'], answer: 2 },
      { problem: '"___你住?" - 问地方', options: ['什么时候', '在哪里', '为什么'], answer: 1 },
      { problem: '"___你去学校?" - 问时间', options: ['在哪里', '谁', '什么时候'], answer: 2 },
      { problem: '"___你迟到?" - 问原因', options: ['怎么', '为什么', '在哪里'], answer: 1 },
      { problem: '我告诉___（阿里）了。', options: ['他', '他的', '他自己'], answer: 0 },
      { problem: '这是___（西蒂的）书。', options: ['她', '她的', '她自己'], answer: 1 },
    ]}
  },
  {
    title: '作文结构 Darjah 6',
    type: 'reading',
    emoji: '✍️',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: '我的名字___阿里。', options: ['们', '是', '在'], answer: 1 },
      { problem: '我___嘉阳小学的学生。', options: ['们', '是', '在'], answer: 1 },
      { problem: '昨天，我___去学校。', options: ['去', '去了', '去着'], answer: 1 },
      { problem: '明天，她___来拜访我们。', options: ['来', '来了', '将会来'], answer: 2 },
      { problem: '他们___从早上玩到现在。', options: ['已经', '正在', '将会'], answer: 0 },
      { problem: '好文章有引言、主体和___?', options: ['标题', '结论', '索引'], answer: 1 },
      { problem: '主题句通常在段落的___?', options: ['结尾', '中间', '开头'], answer: 2 },
      { problem: '哪个是连接词?', options: ['苹果', '但是', '跑'], answer: 1 },
    ]}
  },
  {
    title: '成语学习 Darjah 6',
    type: 'multiple_choice',
    emoji: '💬',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: '"一石二鸟"的意思是?', options: ['打鸟', '一举两得', '两只鸟'], answer: 1 },
      { problem: '"马到成功"的意思是?', options: ['马来了', '立即成功', '骑马'], answer: 1 },
      { problem: '"半途而废"的意思是?', options: ['走了一半', '中途放弃', '成功'], answer: 1 },
      { problem: '"亡羊补牢"的意思是?', options: ['羊不见了', '出了问题才补救', '建围栏'], answer: 1 },
      { problem: '"一鸣惊人"的意思是?', options: ['鸟叫', '一举成名', '惊吓人'], answer: 1 },
      { problem: '"百闻不如一见"的意思是?', options: ['听很多次', '亲眼看比听说好', '看一次'], answer: 1 },
      { problem: '"掩耳盗铃"的意思是?', options: ['偷铃', '自欺欺人', '堵耳朵'], answer: 1 },
      { problem: '"对牛弹琴"的意思是?', options: ['给牛弹音乐', '白费力气', '音乐很好'], answer: 1 },
    ]}
  },
  {
    title: '阅读 - 市场 Darjah 4',
    type: 'multiple_choice',
    emoji: '🏪',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '文章: "市场很热闹。摊贩卖水果、蔬菜和鱼。人们买新鲜食物。" - 这是哪里?', options: ['学校', '市场', '医院'], answer: 1 },
      { problem: '摊贩卖什么?', options: ['书', '水果、蔬菜、鱼', '衣服'], answer: 1 },
      { problem: '市场怎么样?', options: ['空', '安静', '热闹'], answer: 2 },
      { problem: '什么食物?', options: ['旧的', '新鲜的', '冷冻的'], answer: 1 },
      { problem: '人们为什么去那里?', options: ['运动', '买食物', '玩耍'], answer: 1 },
      { problem: '文章类型是?', options: ['故事', '描述', '诗歌'], answer: 1 },
      { problem: '人们的活动是?', options: ['只卖', '只买', '买和卖'], answer: 2 },
      { problem: '主题是关于什么?', options: ['一个摊贩', '市场活动', '一个人'], answer: 1 },
    ]}
  },
  {
    title: '理解 - 家庭时光 Darjah 4',
    type: 'multiple_choice',
    emoji: '👨‍👩‍👧‍👦',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '文章: "星期天对我家来说很特别。我们一起吃早饭。我们去公园放松。" - 什么日子?', options: ['星期一', '星期天', '星期六'], answer: 1 },
      { problem: '那天什么特别?', options: ['工作', '家庭时光', '学校'], answer: 1 },
      { problem: '他们先做什么?', options: ['去公园', '吃早饭', '睡觉'], answer: 1 },
      { problem: '他们去哪里?', options: ['学校', '工作', '公园'], answer: 2 },
      { problem: '去公园的目的?', options: ['运动', '放松', '工作'], answer: 1 },
      { problem: '家庭活动是?', options: ['独自', '一起', '分开'], answer: 1 },
      { problem: '文章讲的是?', options: ['学校', '工作日常', '家庭时光'], answer: 2 },
      { problem: '文章的感受是?', options: ['悲伤', '快乐', '生气'], answer: 1 },
    ]}
  },
  {
    title: '听力 - 我的学校日 Darjah 3',
    type: 'multiple_choice',
    emoji: '👂',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '故事: "我6点起床。我7点吃早饭。我8点去学校。" - 学生什么时候吃早饭?', options: ['6点', '7点', '8点'], answer: 1 },
      { problem: '学生先做什么?', options: ['吃', '起床', '去学校'], answer: 1 },
      { problem: '上学时间是?', options: ['7点', '6点', '8点'], answer: 2 },
      { problem: '故事关于什么?', options: ['玩耍', '日常作息', '睡觉'], answer: 1 },
      { problem: '提到几件事?', options: ['2', '3', '4'], answer: 1 },
      { problem: '早饭在___之间?', options: ['6-7点', '7-8点', '5-6点'], answer: 0 },
      { problem: '故事的主要内容是关于时间?', options: ['没有', '是', '也许'], answer: 1 },
      { problem: '起床和上学中间做什么?', options: ['睡觉', '吃早饭', '运动'], answer: 1 },
    ]}
  },
  {
    title: '诗歌欣赏 Darjah 4',
    type: 'multiple_choice',
    emoji: '🌙',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '诗: "月亮明亮地照耀，星星在夜空中闪烁。" - 什么明亮地照耀?', options: ['太阳', '月亮', '灯'], answer: 1 },
      { problem: '月亮的光是?', options: ['昏暗', '明亮', '微弱'], answer: 1 },
      { problem: '什么在闪烁?', options: ['月亮', '星星', '云'], answer: 1 },
      { problem: '诗中是什么时间?', options: ['白天', '傍晚', '夜晚'], answer: 2 },
      { problem: '诗中的语言特点?', options: ['普通', '优美有韵律', '简短'], answer: 1 },
      { problem: '诗中的感受?', options: ['悲伤', '优美宁静', '愤怒'], answer: 1 },
      { problem: '诗的目的是?', options: ['告知时间表', '描述夜晚的美', '教算术'], answer: 1 },
      { problem: '"闪烁"是什么意思?', options: ['消失', '发光', '变暗'], answer: 1 },
    ]}
  },
  {
    title: '行动动词 Darjah 5',
    type: 'multiple_choice',
    emoji: '💪',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: '"他___书" - 正确动词?', options: ['跳', '读', '唱'], answer: 1 },
      { problem: '"他们___学校" - 正确动词?', options: ['睡', '去', '写'], answer: 1 },
      { problem: '"我___早饭" - 正确动词?', options: ['跑', '吃', '游'], answer: 1 },
      { problem: '"她在花园里___花" - 正确动词?', options: ['喝', '种', '开'], answer: 1 },
      { problem: '"我们___球" - 正确动词?', options: ['扔', '画', '做'], answer: 0 },
      { problem: '"你___得很好" - 正确动词?', options: ['睡', '说', '画'], answer: 1 },
      { problem: '"他___作业" - 正确动词?', options: ['做饭', '打扫', '做'], answer: 2 },
      { problem: '"我___歌" - 正确动词?', options: ['写', '画', '唱'], answer: 2 },
    ]}
  },
  {
    title: '语法 - 情态动词 Darjah 6',
    type: 'multiple_choice',
    emoji: '🔧',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: '礼貌地请求许可?', options: ['我要去', '可以让我去吗?', '我去了'], answer: 1 },
      { problem: '"你___戴头盔。" (义务)', options: ['可能', '必须', '应该'], answer: 1 },
      { problem: '"她___游得很好。" (能力)', options: ['必须', '能', '应该'], answer: 1 },
      { problem: '"今天___会下雨。" (可能性)', options: ['必须', '能', '可能'], answer: 2 },
      { problem: '"你___吃蔬菜。" (建议)', options: ['必须', '应该', '可能'], answer: 1 },
      { problem: '"___我借你的笔?" (请求)', options: ['会', '能', '应该'], answer: 1 },
      { problem: '"他___在家。" (确定性)', options: ['可能', '必须', '应该'], answer: 1 },
      { problem: '"你___在走廊跑。" (禁止)', options: ['应该', '不必', '不能'], answer: 2 },
    ]}
  },
  {
    title: '文学体裁 Darjah 6',
    type: 'multiple_choice',
    emoji: '📖',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: '短篇故事的主要特点?', options: ['很长', '简短精练', '发展'], answer: 1 },
      { problem: '诗歌是使用___的文学?', options: ['普通散文', '有想象力和节奏的语言', '只有对话'], answer: 1 },
      { problem: '戏剧的特点是?', options: ['没有对话', '有大量对话和动作', '只有独白'], answer: 1 },
      { problem: '小说通常是?', options: ['非常短', '长篇发展性', '中等长度'], answer: 1 },
      { problem: '寓言讲的是?', options: ['古代人类', '有人类特征的动物', '神秘生物'], answer: 1 },
      { problem: '传说是?', options: ['未来的故事', '发展了的历史故事', '纯幻想'], answer: 1 },
      { problem: '散文诗是?', options: ['像诗一样的散文', '普通的故事', '两者都不是'], answer: 0 },
      { problem: '神话是关于?', options: ['现代人', '神灵和英雄', '只有动物'], answer: 1 },
    ]}
  },
];