export const prasekolah_bahasa_melayu = [
  { title: 'Huruf ABC - A hingga F', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Epal', options: ['A','B','C','D'], answer: 0 },
    { letter: 'B', emoji: '🐦', word: 'Burung', options: ['A','B','C','D'], answer: 1 },
    { letter: 'C', emoji: '🐱', word: 'Kucing', options: ['A','B','C','D'], answer: 2 },
    { letter: 'D', emoji: '🐕', word: 'Anjing', options: ['A','B','C','D'], answer: 3 },
    { letter: 'E', emoji: '🐘', word: 'Gajah', options: ['D','E','F','G'], answer: 1 },
    { letter: 'F', emoji: '🐟', word: 'Ikan', options: ['D','E','F','G'], answer: 2 },
    { letter: 'G', emoji: '🍇', word: 'Anggur', options: ['E','F','G','H'], answer: 2 },
    { letter: 'H', emoji: '🏠', word: 'Rumah', options: ['F','G','H','I'], answer: 2 },
  ]}},
  { title: 'Huruf Vokal A, E, I, O, U', type: 'letter_match', emoji: '🅰️', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Epal', options: ['A','E','I','O'], answer: 0 },
    { letter: 'E', emoji: '🥚', word: 'Telur', options: ['A','E','I','O'], answer: 1 },
    { letter: 'I', emoji: '🍦', word: 'Ais Krim', options: ['A','E','I','O'], answer: 2 },
    { letter: 'O', emoji: '🍊', word: 'Oren', options: ['A','E','I','O'], answer: 3 },
    { letter: 'U', emoji: '☂️', word: 'Payung', options: ['I','U','E','O'], answer: 1 },
    { letter: 'A', emoji: '🐊', word: 'Buaya', options: ['U','A','I','O'], answer: 1 },
    { letter: 'E', emoji: '🦅', word: 'Helang', options: ['A','E','U','I'], answer: 1 },
    { letter: 'I', emoji: '🐟', word: 'Ikan', options: ['U','O','I','A'], answer: 2 },
  ]}},
  { title: 'Nama Haiwan', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Kucing','Anjing','Kelinci'], answer: 0 },
    { image: '🐶', options: ['Kucing','Anjing','Burung'], answer: 1 },
    { image: '🦁', options: ['Singa','Harimau','Beruang'], answer: 0 },
    { image: '🐘', options: ['Gajah','Kuda','Zebra'], answer: 0 },
    { image: '🐧', options: ['Penguin','Ayam','Itik'], answer: 0 },
    { image: '🦒', options: ['Jerapah','Rusa','Kuda'], answer: 0 },
    { image: '🐻', options: ['Beruang','Serigala','Singa'], answer: 0 },
    { image: '🦓', options: ['Zebra','Kuda','Kijang'], answer: 0 },
  ]}},
  { title: 'Suara Haiwan', type: 'sound_match', emoji: '🔊', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Meow','Woof','Moo','Baa'], answer: 0 },
    { image: '🐶', options: ['Meow','Woof','Moo','Baa'], answer: 1 },
    { image: '🐄', options: ['Meow','Woof','Moo','Baa'], answer: 2 },
    { image: '🐑', options: ['Meow','Woof','Moo','Baa'], answer: 3 },
    { image: '🦆', options: ['Quack','Hiss','Chirp','Roar'], answer: 0 },
    { image: '🐍', options: ['Quack','Hiss','Chirp','Roar'], answer: 1 },
    { image: '🐦', options: ['Quack','Hiss','Chirp','Roar'], answer: 2 },
    { image: '🦁', options: ['Quack','Hiss','Chirp','Roar'], answer: 3 },
  ]}},
  { title: 'Nama Buah-Buahan', type: 'picture_quiz', emoji: '🍓', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['Epal','Oren','Pisang'], answer: 0 },
    { image: '🍊', options: ['Epal','Oren','Mangga'], answer: 1 },
    { image: '🍌', options: ['Pisang','Betik','Ciku'], answer: 0 },
    { image: '🍇', options: ['Anggur','Strawberi','Ceri'], answer: 0 },
    { image: '🍓', options: ['Anggur','Strawberi','Epal'], answer: 1 },
    { image: '🍉', options: ['Tembikai','Betik','Mangga'], answer: 0 },
    { image: '🥭', options: ['Betik','Mangga','Durian'], answer: 1 },
    { image: '🍋', options: ['Limau','Oren','Lemon'], answer: 2 },
  ]}},
  { title: 'Nama Warna', type: 'picture_quiz', emoji: '🎨', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Merah','Biru','Hijau'], answer: 0 },
    { image: '🔵', options: ['Merah','Biru','Kuning'], answer: 1 },
    { image: '🟢', options: ['Ungu','Hijau','Oren'], answer: 1 },
    { image: '🟡', options: ['Kuning','Oren','Putih'], answer: 0 },
    { image: '🟠', options: ['Kuning','Oren','Merah'], answer: 1 },
    { image: '💜', options: ['Ungu','Merah Jambu','Biru'], answer: 0 },
    { image: '🤎', options: ['Hitam','Coklat','Kelabu'], answer: 1 },
    { image: '⚪', options: ['Putih','Hitam','Kelabu'], answer: 0 },
  ]}},
  { title: 'Nama Sayur-Sayuran', type: 'picture_quiz', emoji: '🥦', difficulty: 'easy', gameData: { questions: [
    { image: '🥕', options: ['Lobak Merah','Tomato','Bawang'], answer: 0 },
    { image: '🍅', options: ['Lobak','Tomato','Betik'], answer: 1 },
    { image: '🥦', options: ['Brokoli','Kobis','Bayam'], answer: 0 },
    { image: '🌽', options: ['Jagung','Timun','Labu'], answer: 0 },
    { image: '🥒', options: ['Timun','Lobak','Labu'], answer: 0 },
    { image: '🧅', options: ['Bawang','Kentang','Halia'], answer: 0 },
    { image: '🥔', options: ['Ubi','Kentang','Lobak'], answer: 1 },
    { image: '🌶️', options: ['Cili','Tomato','Lobak'], answer: 0 },
  ]}},
  { title: 'Anggota Keluarga', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['Ayah','Ibu','Abang'], answer: 0 },
    { image: '👩', options: ['Ayah','Ibu','Kakak'], answer: 1 },
    { image: '👦', options: ['Abang','Adik Lelaki','Datuk'], answer: 1 },
    { image: '👧', options: ['Kakak','Nenek','Ibu'], answer: 0 },
    { image: '👴', options: ['Ayah','Datuk','Abang'], answer: 1 },
    { image: '👵', options: ['Ibu','Nenek','Kakak'], answer: 1 },
    { image: '👶', options: ['Bayi','Adik','Budak'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['Keluarga','Kawan','Jiran'], answer: 0 },
  ]}},
  { title: 'Huruf I hingga N', type: 'letter_match', emoji: '🔡', difficulty: 'easy', gameData: { questions: [
    { letter: 'I', emoji: '🐟', word: 'Ikan', options: ['I','J','K','L'], answer: 0 },
    { letter: 'J', emoji: '🌉', word: 'Jambatan', options: ['I','J','K','L'], answer: 1 },
    { letter: 'K', emoji: '🐴', word: 'Kuda', options: ['I','J','K','L'], answer: 2 },
    { letter: 'L', emoji: '🌊', word: 'Laut', options: ['I','J','K','L'], answer: 3 },
    { letter: 'M', emoji: '🌙', word: 'Malam', options: ['M','N','O','P'], answer: 0 },
    { letter: 'N', emoji: '🌰', word: 'Nangka', options: ['M','N','O','P'], answer: 1 },
    { letter: 'O', emoji: '🐙', word: 'Sotong', options: ['M','N','O','P'], answer: 2 },
    { letter: 'P', emoji: '🦚', word: 'Merak', options: ['M','N','O','P'], answer: 3 },
  ]}},
  { title: 'Perkataan Pertama Saya', type: 'picture_quiz', emoji: '💬', difficulty: 'easy', gameData: { questions: [
    { image: '🏠', options: ['Rumah','Sekolah','Kedai'], answer: 0 },
    { image: '🚗', options: ['Bas','Kereta','Lori'], answer: 1 },
    { image: '📚', options: ['Buku','Pensil','Kertas'], answer: 0 },
    { image: '🎒', options: ['Beg','Buku','Kotak'], answer: 0 },
    { image: '✏️', options: ['Pen','Pensil','Pensel'], answer: 1 },
    { image: '🍽️', options: ['Pinggan','Mangkuk','Cawan'], answer: 0 },
    { image: '🛏️', options: ['Katil','Kerusi','Meja'], answer: 0 },
    { image: '🪑', options: ['Meja','Kerusi','Almari'], answer: 1 },
  ]}},
  { title: 'Huruf O hingga S', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'O', emoji: '🐙', word: 'Sotong', options: ['O','P','Q','R'], answer: 0 },
    { letter: 'P', emoji: '🦚', word: 'Merak', options: ['O','P','Q','R'], answer: 1 },
    { letter: 'Q', emoji: '👑', word: 'Mahkota', options: ['O','P','Q','R'], answer: 2 },
    { letter: 'R', emoji: '🌹', word: 'Ros', options: ['O','P','Q','R'], answer: 3 },
    { letter: 'S', emoji: '⭐', word: 'Bintang', options: ['R','S','T','U'], answer: 1 },
    { letter: 'T', emoji: '🐯', word: 'Harimau', options: ['R','S','T','U'], answer: 2 },
    { letter: 'U', emoji: '☂️', word: 'Payung', options: ['R','S','T','U'], answer: 3 },
    { letter: 'V', emoji: '🎻', word: 'Biola', options: ['S','T','U','V'], answer: 3 },
  ]}},
  { title: 'Nama Pakaian', type: 'picture_quiz', emoji: '👕', difficulty: 'easy', gameData: { questions: [
    { image: '👕', options: ['Baju','Seluar','Kasut'], answer: 0 },
    { image: '👖', options: ['Baju','Seluar','Topi'], answer: 1 },
    { image: '👟', options: ['Sandal','Kasut','Stokin'], answer: 1 },
    { image: '🧦', options: ['Stokin','Kasut','Sarung'], answer: 0 },
    { image: '🧢', options: ['Topi','Tudung','Skaf'], answer: 0 },
    { image: '👗', options: ['Baju','Gaun','Seluar'], answer: 1 },
    { image: '🧥', options: ['Jaket','Baju','Seluar'], answer: 0 },
    { image: '👔', options: ['Baju Kemeja','T-shirt','Baju Melayu'], answer: 0 },
  ]}},
  { title: 'Nama Pengangkutan', type: 'picture_quiz', emoji: '🚗', difficulty: 'easy', gameData: { questions: [
    { image: '🚗', options: ['Kereta','Bas','Lori'], answer: 0 },
    { image: '🚌', options: ['Kereta','Bas','Van'], answer: 1 },
    { image: '✈️', options: ['Kapal Terbang','Helikopter','Kapal'], answer: 0 },
    { image: '🚢', options: ['Bot','Feri','Kapal'], answer: 2 },
    { image: '🚂', options: ['LRT','Kereta Api','Tram'], answer: 1 },
    { image: '🏍️', options: ['Basikal','Motosikal','Kereta'], answer: 1 },
    { image: '🚲', options: ['Basikal','Motosikal','Troli'], answer: 0 },
    { image: '🚁', options: ['Kapal Terbang','Helikopter','Dron'], answer: 1 },
  ]}},
  { title: 'Nama Bilik di Rumah', type: 'picture_quiz', emoji: '🏠', difficulty: 'easy', gameData: { questions: [
    { image: '🛋️', options: ['Bilik Tidur','Ruang Tamu','Dapur'], answer: 1 },
    { image: '🛁', options: ['Bilik Air','Bilik Tidur','Dapur'], answer: 0 },
    { image: '🍳', options: ['Ruang Makan','Dapur','Stor'], answer: 1 },
    { image: '🛏️', options: ['Bilik Tidur','Ruang Tamu','Bilik Air'], answer: 0 },
    { image: '🍽️', options: ['Dapur','Ruang Makan','Ruang Tamu'], answer: 1 },
    { image: '📺', options: ['Bilik Tidur','Ruang Tamu','Dapur'], answer: 1 },
    { image: '📚', options: ['Bilik Belajar','Bilik Tidur','Ruang Tamu'], answer: 0 },
    { image: '🚪', options: ['Tingkap','Pintu','Pagar'], answer: 1 },
  ]}},
  { title: 'Nama Jenis Makanan', type: 'picture_quiz', emoji: '🍜', difficulty: 'easy', gameData: { questions: [
    { image: '🍚', options: ['Nasi','Roti','Mee'], answer: 0 },
    { image: '🍞', options: ['Nasi','Roti','Biskut'], answer: 1 },
    { image: '🍜', options: ['Mihun','Mee','Spaghetti'], answer: 1 },
    { image: '🍳', options: ['Telur Goreng','Telur Rebus','Telur Dadar'], answer: 0 },
    { image: '🥘', options: ['Sup','Kari','Gulai'], answer: 1 },
    { image: '🍰', options: ['Kek','Kuih','Donat'], answer: 0 },
    { image: '🍱', options: ['Bento','Nasi Lemak','Nasi Kotak'], answer: 0 },
    { image: '🥞', options: ['Waffle','Pancake','Crepe'], answer: 1 },
  ]}},
  { title: 'Penjodoh Bilangan Mudah', type: 'multiple_choice', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: 'Seekor ___', options: ['kereta','kucing','buku'], answer: 1 },
    { problem: 'Sebuah ___', options: ['burung','pokok','kereta'], answer: 2 },
    { problem: 'Sebatang ___', options: ['pensil','kucing','kereta'], answer: 0 },
    { problem: 'Sehelai ___', options: ['buku','kertas','botol'], answer: 1 },
    { problem: 'Sepasang ___', options: ['kasut','buku','pokok'], answer: 0 },
    { problem: 'Sekawan ___', options: ['pokok','burung','kereta'], answer: 1 },
    { problem: 'Sebiji ___', options: ['pisang','ikan','kucing'], answer: 0 },
    { problem: 'Seorang ___', options: ['anjing','budak','pokok'], answer: 1 },
  ]}},
  { title: 'Kata Ganti Nama', type: 'multiple_choice', emoji: '👤', difficulty: 'easy', gameData: { questions: [
    { problem: 'Kata ganti nama diri pertama?', options: ['Dia','Saya','Mereka'], answer: 1 },
    { problem: 'Kata ganti nama diri kedua?', options: ['Saya','Kamu','Mereka'], answer: 1 },
    { problem: 'Kata ganti nama diri ketiga?', options: ['Saya','Kamu','Dia'], answer: 2 },
    { problem: '"___ pergi ke sekolah" (diri sendiri)', options: ['Dia','Saya','Kamu'], answer: 1 },
    { problem: '"___ suka bermain" (kawan)', options: ['Saya','Dia','Kami'], answer: 1 },
    { problem: '"___ semua bersama" (ramai)', options: ['Saya','Kamu','Kami'], answer: 2 },
    { problem: '"___ buku saya" (kepunyaan)', options: ['Ini','Di sini','Itu'], answer: 0 },
    { problem: '"___ rumah kamu?" (bertanya)', options: ['Mana','Di mana','Bagaimana'], answer: 1 },
  ]}},
  { title: 'Pantun Mudah - Lengkapkan', type: 'multiple_choice', emoji: '📜', difficulty: 'easy', gameData: { questions: [
    { problem: 'Hujan emas di negeri orang, hujan ___ di negeri sendiri', options: ['emas','perak','batu'], answer: 1 },
    { problem: 'Buat baik ___ dibalas', options: ['jahat','baik','buruk'], answer: 1 },
    { problem: 'Rajin belajar, ___ pandai', options: ['jadi','mesti','akan'], answer: 0 },
    { problem: 'Kasih sayang ___ keluarga', options: ['dari','untuk','bersama'], answer: 1 },
    { problem: 'Bangun pagi, ___ muka', options: ['gosok','basuh','lap'], answer: 1 },
    { problem: 'Tolong ___ adalah mulia', options: ['menolong','bergaduh','bercakap'], answer: 0 },
    { problem: 'Makan ___ kenyang', options: ['sampai','hingga','supaya'], answer: 1 },
    { problem: 'Ibu ___ kita sayang', options: ['bapa','kita','ayah'], answer: 0 },
  ]}},
  { title: 'Huruf T hingga Z', type: 'letter_match', emoji: '🔠', difficulty: 'easy', gameData: { questions: [
    { letter: 'T', emoji: '🐯', word: 'Harimau', options: ['T','U','V','W'], answer: 0 },
    { letter: 'U', emoji: '☂️', word: 'Payung', options: ['T','U','V','W'], answer: 1 },
    { letter: 'V', emoji: '🎻', word: 'Biola', options: ['T','U','V','W'], answer: 2 },
    { letter: 'W', emoji: '🐋', word: 'Ikan Paus', options: ['T','U','V','W'], answer: 3 },
    { letter: 'X', emoji: '🎮', word: 'Xbox', options: ['W','X','Y','Z'], answer: 1 },
    { letter: 'Y', emoji: '🪀', word: 'Yo-yo', options: ['W','X','Y','Z'], answer: 2 },
    { letter: 'Z', emoji: '🦓', word: 'Zebra', options: ['W','X','Y','Z'], answer: 3 },
    { letter: 'A', emoji: '🐊', word: 'Buaya', options: ['A','B','C','D'], answer: 0 },
  ]}},
  { title: 'Nama Peralatan Sekolah', type: 'picture_quiz', emoji: '✏️', difficulty: 'easy', gameData: { questions: [
    { image: '✏️', options: ['Pensil','Pen','Krayon'], answer: 0 },
    { image: '📏', options: ['Pembaris','Gunting','Pemadam'], answer: 0 },
    { image: '🖊️', options: ['Pensil','Pen','Marker'], answer: 1 },
    { image: '📐', options: ['Jangka','Pembaris Sudut','Penggaris'], answer: 1 },
    { image: '📚', options: ['Buku','Majalah','Nota'], answer: 0 },
    { image: '🎒', options: ['Beg Sekolah','Beg Tangan','Beg Sukan'], answer: 0 },
    { image: '🗂️', options: ['Fail','Buku','Kotak'], answer: 0 },
    { image: '🖍️', options: ['Pensil Warna','Krayon','Pen'], answer: 1 },
  ]}},
];