export const prasekolah_bahasa_mandarin = [
  {
    title: '数字 1-10 (Nombor 1-10)',
    type: 'number_match',
    emoji: '🔢',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '⭐', options: ['一', '二', '三'], answer: 0 },
      { problem: '⭐⭐', options: ['一', '二', '三'], answer: 1 },
      { problem: '⭐⭐⭐', options: ['二', '三', '四'], answer: 1 },
      { problem: '⭐⭐⭐⭐', options: ['三', '四', '五'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐', options: ['四', '五', '六'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐', options: ['五', '六', '七'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['六', '七', '八'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['七', '八', '九'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['八', '九', '十'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['九', '十', '十一'], answer: 1 },
      { problem: '一 = ?', options: ['1', '2', '3'], answer: 0 },
      { problem: '三 = ?', options: ['1', '2', '3'], answer: 2 },
      { problem: '五 = ?', options: ['4', '5', '6'], answer: 1 },
      { problem: '七 = ?', options: ['6', '7', '8'], answer: 1 },
      { problem: '九 = ?', options: ['8', '9', '10'], answer: 1 },
      { problem: '十 = ?', options: ['8', '9', '10'], answer: 2 },
      { problem: '二 = ?', options: ['1', '2', '3'], answer: 1 },
      { problem: '四 = ?', options: ['3', '4', '5'], answer: 1 },
      { problem: '六 = ?', options: ['5', '6', '7'], answer: 1 },
      { problem: '八 = ?', options: ['7', '8', '9'], answer: 1 },
    ]}
  },
  {
    title: '动物名字 (Nama Haiwan)',
    type: 'picture_quiz',
    emoji: '🐾',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🐱', options: ['猫', '狗', '兔子'], answer: 0 },
      { image: '🐶', options: ['猫', '狗', '鸟'], answer: 1 },
      { image: '🐘', options: ['大象', '马', '斑马'], answer: 0 },
      { image: '🦁', options: ['老虎', '狮子', '熊'], answer: 1 },
      { image: '🐄', options: ['牛', '羊', '猪'], answer: 0 },
      { image: '🐟', options: ['鱼', '螃蟹', '乌龟'], answer: 0 },
      { image: '🦋', options: ['蜻蜓', '蝴蝶', '蜜蜂'], answer: 1 },
      { image: '🐦', options: ['鸡', '鸟', '鸭'], answer: 1 },
      { image: '🐢', options: ['乌龟', '蛇', '蜥蜴'], answer: 0 },
      { image: '🐸', options: ['青蛙', '蟹', '虾'], answer: 0 },
      { image: '🦅', options: ['鹰', '隼', '猫头鹰'], answer: 0 },
      { image: '🐮', options: ['牛', '马', '羊'], answer: 0 },
      { image: '🐷', options: ['猪', '牛', '羊'], answer: 0 },
      { image: '🐑', options: ['羊', '牛', '马'], answer: 0 },
      { image: '🐴', options: ['马', '驴', '骡'], answer: 0 },
      { image: '🦒', options: ['长颈鹿', '斑马', '狮子'], answer: 0 },
      { image: '🦓', options: ['斑马', '狮子', '猎豹'], answer: 0 },
      { image: '🐆', options: ['豹', '虎', '狮'], answer: 0 },
    ]}
  },
  {
    title: '颜色 (Warna)',
    type: 'picture_quiz',
    emoji: '🌈',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🔴', options: ['红色', '蓝色', '绿色'], answer: 0 },
      { image: '🔵', options: ['红色', '蓝色', '黄色'], answer: 1 },
      { image: '🟢', options: ['紫色', '绿色', '橙色'], answer: 1 },
      { image: '🟡', options: ['黄色', '橙色', '白色'], answer: 0 },
      { image: '🟠', options: ['黄色', '橙色', '红色'], answer: 1 },
      { image: '💜', options: ['紫色', '粉红色', '蓝色'], answer: 0 },
      { image: '⚫', options: ['棕色', '黑色', '灰色'], answer: 1 },
      { image: '⚪', options: ['白色', '黑色', '灰色'], answer: 0 },
      { image: '🟤', options: ['棕色', '灰色', '黑色'], answer: 0 },
      { image: '🟥', options: ['红色', '蓝色', '绿色'], answer: 0 },
      { image: '🟦', options: ['蓝色', '红色', '绿色'], answer: 0 },
      { image: '🟩', options: ['绿色', '红色', '蓝色'], answer: 0 },
      { image: '🟪', options: ['紫色', '蓝色', '红色'], answer: 0 },
      { image: '🟨', options: ['黄色', '绿色', '红色'], answer: 0 },
      { image: '⬛', options: ['黑色', '白色', '灰色'], answer: 0 },
      { image: '⬜', options: ['白色', '黑色', '灰色'], answer: 0 },
    ]}
  },
  {
    title: '水果名字 (Nama Buah)',
    type: 'picture_quiz',
    emoji: '🍎',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🍎', options: ['苹果', '橙子', '香蕉'], answer: 0 },
      { image: '🍌', options: ['苹果', '香蕉', '芒果'], answer: 1 },
      { image: '🍊', options: ['橙子', '柠檬', '葡萄'], answer: 0 },
      { image: '🍇', options: ['葡萄', '草莓', '樱桃'], answer: 0 },
      { image: '🍓', options: ['葡萄', '草莓', '苹果'], answer: 1 },
      { image: '🥭', options: ['木瓜', '芒果', '榴莲'], answer: 1 },
      { image: '🍉', options: ['西瓜', '木瓜', '芒果'], answer: 0 },
      { image: '🍋', options: ['柠檬', '橙子', '葡萄'], answer: 0 },
      { image: '🍑', options: ['桃子', '梨', '李子'], answer: 0 },
      { image: '🍒', options: ['樱桃', '杨梅', '蓝莓'], answer: 0 },
      { image: '🍍', options: ['菠萝', '芒果', '番茄'], answer: 0 },
      { image: '🥝', options: ['猕猴桃', '葡萄', '蓝莓'], answer: 0 },
      { image: '🍓', options: ['草莓', '蓝莓', '黑莓'], answer: 0 },
      { image: '🫐', options: ['蓝莓', '黑莓', '覆盆子'], answer: 0 },
      { image: '🍅', options: ['番茄', '苹果', '辣椒'], answer: 0 },
      { image: '🥭', options: ['芒果', '桃子', '梨'], answer: 0 },
    ]}
  },
  {
    title: '家庭成员 (Keluarga)',
    type: 'picture_quiz',
    emoji: '👨‍👩‍👧‍👦',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👨', options: ['爸爸', '妈妈', '哥哥'], answer: 0 },
      { image: '👩', options: ['爸爸', '妈妈', '姐姐'], answer: 1 },
      { image: '👴', options: ['爸爸', '爷爷', '哥哥'], answer: 1 },
      { image: '👵', options: ['妈妈', '奶奶', '姐姐'], answer: 1 },
      { image: '👦', options: ['哥哥', '弟弟', '爷爷'], answer: 0 },
      { image: '👧', options: ['姐姐', '妹妹', '奶奶'], answer: 0 },
      { image: '👶', options: ['宝宝', '弟弟', '小孩'], answer: 0 },
      { image: '👨‍👩‍👧', options: ['家庭', '朋友', '邻居'], answer: 0 },
      { image: '👪', options: ['家庭', '学校', '工作'], answer: 0 },
      { image: '👨‍👩‍👦', options: ['家庭', '朋友', '邻居'], answer: 0 },
      { image: '👨‍👩‍👧‍👦', options: ['大家庭', '小家庭', '邻居'], answer: 0 },
      { image: '👨‍👨‍👧', options: ['爸爸们', '兄弟们', '朋友们'], answer: 0 },
      { image: '👩‍👩‍👦', options: ['妈妈们', '姐妹们', '朋友们'], answer: 0 },
      { image: '👨‍👧', options: ['父女', '父子', '兄妹'], answer: 0 },
      { image: '👩‍👦', options: ['母子', '母女', '姐弟'], answer: 0 },
      { image: '👶', options: ['婴儿', '孩子', '宝宝'], answer: 0 },
      { image: '👴‍👵', options: ['祖父母', '父母', '叔婶'], answer: 0 },
    ]}
  },
  {
    title: '身体部位 (Anggota Badan)',
    type: 'picture_quiz',
    emoji: '🧒',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👁️', options: ['眼睛', '鼻子', '耳朵'], answer: 0 },
      { image: '👃', options: ['眼睛', '鼻子', '嘴巴'], answer: 1 },
      { image: '👂', options: ['眼睛', '鼻子', '耳朵'], answer: 2 },
      { image: '👄', options: ['嘴巴', '鼻子', '嘴唇'], answer: 0 },
      { image: '✋', options: ['脚', '手', '肩膀'], answer: 1 },
      { image: '🦶', options: ['脚', '手', '手臂'], answer: 0 },
      { image: '💇', options: ['头', '身体', '肚子'], answer: 0 },
      { image: '🧠', options: ['心脏', '大脑', '肺'], answer: 1 },
      { image: '🦷', options: ['牙齿', '舌头', '嘴唇'], answer: 0 },
      { image: '👅', options: ['舌头', '嘴唇', '牙齿'], answer: 0 },
      { image: '💋', options: ['嘴唇', '鼻子', '下巴'], answer: 0 },
      { image: '👃', options: ['鼻子', '耳朵', '眼睛'], answer: 0 },
      { image: '🦴', options: ['骨头', '肌肉', '皮肤'], answer: 0 },
      { image: '🩸', options: ['血液', '骨头', '肌肉'], answer: 0 },
      { image: '💪', options: ['肌肉', '脂肪', '皮肤'], answer: 0 },
      { image: '🦵', options: ['腿', '脚', '膝盖'], answer: 0 },
      { image: '❤️', options: ['心脏', '肺', '肝脏'], answer: 0 },
      { image: '🫀', options: ['心脏', '大脑', '肠'], answer: 0 },
    ]}
  },
  {
    title: '蔬菜名字 (Sayur-Sayuran)',
    type: 'picture_quiz',
    emoji: '🥦',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🥕', options: ['胡萝卜', '番茄', '洋葱'], answer: 0 },
      { image: '🍅', options: ['胡萝卜', '番茄', '木瓜'], answer: 1 },
      { image: '🥦', options: ['西兰花', '卷心菜', '菠菜'], answer: 0 },
      { image: '🌽', options: ['玉米', '黄瓜', '南瓜'], answer: 0 },
      { image: '🥒', options: ['黄瓜', '胡萝卜', '南瓜'], answer: 0 },
      { image: '🧅', options: ['洋葱', '马铃薯', '生姜'], answer: 0 },
      { image: '🥔', options: ['红薯', '马铃薯', '胡萝卜'], answer: 1 },
      { image: '🌶️', options: ['辣椒', '番茄', '胡萝卜'], answer: 0 },
      { image: '🧄', options: ['大蒜', '洋葱', '生姜'], answer: 0 },
      { image: '🧅', options: ['洋葱', '大蒜', '土豆'], answer: 0 },
      { image: '🥬', options: ['生菜', '卷心菜', '菠菜'], answer: 0 },
      { image: '🥒', options: ['黄瓜', '冬瓜', '南瓜'], answer: 0 },
      { image: '🌽', options: ['玉米', '小麦', '大麦'], answer: 0 },
      { image: '🫑', options: ['彩椒', '灯笼椒', '辣椒'], answer: 0 },
      { image: '🥔', options: ['土豆', '红薯', '山药'], answer: 0 },
      { image: '🍆', options: ['茄子', '黄瓜', '冬瓜'], answer: 0 },
      { image: '🥕', options: ['胡萝卜', '白萝卜', '红萝卜'], answer: 0 },
      { image: '🧈', options: ['黄油', '油', '猪油'], answer: 0 },
    ]}
  },
  {
    title: '汉字笔画 (Huruf Cina Mudah)',
    type: 'letter_match',
    emoji: '📝',
    difficulty: 'easy',
    gameData: { questions: [
      { letter: '一', options: ['一', '二', '三', '四'], answer: 0 },
      { letter: '二', options: ['一', '二', '三', '四'], answer: 1 },
      { letter: '三', options: ['一', '二', '三', '四'], answer: 2 },
      { letter: '四', options: ['一', '二', '三', '四'], answer: 3 },
      { letter: '五', options: ['五', '六', '七', '八'], answer: 0 },
      { letter: '六', options: ['五', '六', '七', '八'], answer: 1 },
      { letter: '七', options: ['五', '六', '七', '八'], answer: 2 },
      { letter: '八', options: ['五', '六', '七', '八'], answer: 3 },
      { letter: '十', options: ['九', '十', '十一', '十二'], answer: 1 },
      { letter: '九', options: ['七', '八', '九', '十'], answer: 2 },
      { letter: '人', options: ['人', '大', '小', '木'], answer: 0 },
      { letter: '大', options: ['人', '大', '小', '木'], answer: 1 },
      { letter: '小', options: ['人', '大', '小', '木'], answer: 2 },
      { letter: '木', options: ['人', '大', '小', '木'], answer: 3 },
      { letter: '日', options: ['日', '月', '星', '天'], answer: 0 },
      { letter: '月', options: ['日', '月', '星', '天'], answer: 1 },
      { letter: '天', options: ['日', '月', '星', '天'], answer: 3 },
      { letter: '山', options: ['山', '水', '火', '风'], answer: 0 },
    ]}
  },
  {
    title: '问候语 (Ucapan Salam)',
    type: 'multiple_choice',
    emoji: '👋',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '早上打招呼用什么?', options: ['晚安', '早上好', '再见'], answer: 1 },
      { problem: '下午打招呼?', options: ['早上好', '下午好', '晚安'], answer: 1 },
      { problem: '晚上打招呼?', options: ['早上好', '下午好', '晚安'], answer: 2 },
      { problem: '"谢谢"的回答?', options: ['对不起', '不客气', '再见'], answer: 1 },
      { problem: '离别时说?', options: ['你好', '再见', '谢谢'], answer: 1 },
      { problem: '"你好"是什么意思?', options: ['再见', '你好', '谢谢'], answer: 1 },
      { problem: '道歉时说?', options: ['谢谢', '对不起', '再见'], answer: 1 },
      { problem: '请人帮忙时说?', options: ['对不起', '谢谢', '请'], answer: 2 },
      { problem: '很高兴认识你?', options: ['很高兴认识你', '谢谢', '对不起'], answer: 0 },
      { problem: '您好是什么?', options: ['你好的尊敬形式', '再见', '谢谢'], answer: 0 },
      { problem: '晚安时说?', options: ['早上好', '下午好', '晚安'], answer: 2 },
      { problem: '对方介绍自己?', options: ['你叫什么?', '谢谢', '对不起'], answer: 0 },
      { problem: '委婉说对不起?', options: ['谢谢', '不好意思', '再见'], answer: 1 },
      { problem: '表示同意?', options: ['是的', '不是', '也许'], answer: 0 },
      { problem: '表示不同意?', options: ['是的', '不是', '也许'], answer: 1 },
      { problem: '见到朋友说?', options: ['你好', '再见', '晚安'], answer: 0 },
      { problem: '最后再见?', options: ['你好', '再见', '晚安'], answer: 1 },
    ]}
  },
  {
    title: '食物名字 (Makanan)',
    type: 'picture_quiz',
    emoji: '🍜',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🍚', options: ['米饭', '面包', '面条'], answer: 0 },
      { image: '🍞', options: ['米饭', '面包', '饼干'], answer: 1 },
      { image: '🍜', options: ['米粉', '面条', '意大利面'], answer: 1 },
      { image: '🥛', options: ['牛奶', '水', '果汁'], answer: 0 },
      { image: '🍰', options: ['蛋糕', '糕点', '甜甜圈'], answer: 0 },
      { image: '🍳', options: ['煮鸡蛋', '煎鸡蛋', '炒鸡蛋'], answer: 1 },
      { image: '🥘', options: ['汤', '咖喱', '炖菜'], answer: 1 },
      { image: '🥪', options: ['三明治', '汉堡', '吐司'], answer: 0 },
      { image: '🍔', options: ['汉堡', '热狗', '三明治'], answer: 0 },
      { image: '🌭', options: ['热狗', '香肠', '腊肠'], answer: 0 },
      { image: '🍕', options: ['披萨', '馅饼', '派'], answer: 0 },
      { image: '🍝', options: ['意大利面', '拉面', '面条'], answer: 0 },
      { image: '🥟', options: ['饺子', '包子', '馄饨'], answer: 0 },
      { image: '🍱', options: ['便当', '盒饭', '套餐'], answer: 0 },
      { image: '🍣', options: ['寿司', '生鱼片', '海鲜'], answer: 0 },
      { image: '🥘', options: ['咖喱', '炖菜', '汤'], answer: 0 },
      { image: '🍲', options: ['汤', '粥', '煲'], answer: 0 },
      { image: '🥗', options: ['沙拉', '蔬菜', '水果'], answer: 0 },
    ]}
  },
  {
    title: '交通工具 (Kenderaan)',
    type: 'picture_quiz',
    emoji: '🚗',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🚗', options: ['汽车', '公共汽车', '卡车'], answer: 0 },
      { image: '🚌', options: ['汽车', '公共汽车', '面包车'], answer: 1 },
      { image: '✈️', options: ['飞机', '直升机', '轮船'], answer: 0 },
      { image: '🚂', options: ['地铁', '火车', '电车'], answer: 1 },
      { image: '🚲', options: ['自行车', '摩托车', '推车'], answer: 0 },
      { image: '🚁', options: ['飞机', '直升机', '无人机'], answer: 1 },
      { image: '🚢', options: ['船', '渡轮', '轮船'], answer: 2 },
      { image: '🏍️', options: ['自行车', '摩托车', '汽车'], answer: 1 },
      { image: '🚗', options: ['小车', '跑车', '越野车'], answer: 0 },
      { image: '🚕', options: ['出租车', '公共汽车', '面包车'], answer: 0 },
      { image: '🚙', options: ['吉普车', '越野车', '小货车'], answer: 0 },
      { image: '🚌', options: ['公交车', '大巴', '长途汽车'], answer: 0 },
      { image: '🚎', options: ['有轨电车', '公交车', '火车'], answer: 0 },
      { image: '🏎️', options: ['赛车', '跑车', '超级跑车'], answer: 0 },
      { image: '🚓', options: ['警车', '救护车', '消防车'], answer: 0 },
      { image: '🚑', options: ['救护车', '警车', '消防车'], answer: 0 },
      { image: '🚒', options: ['消防车', '警车', '救护车'], answer: 0 },
      { image: '🚐', options: ['面包车', '小巴', '小货车'], answer: 0 },
    ]}
  },
  {
    title: '情绪表达 (Perasaan)',
    type: 'picture_quiz',
    emoji: '😊',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '😊', options: ['高兴', '难过', '生气'], answer: 0 },
      { image: '😢', options: ['高兴', '难过', '害怕'], answer: 1 },
      { image: '😠', options: ['高兴', '累了', '生气'], answer: 2 },
      { image: '😨', options: ['害怕', '生气', '高兴'], answer: 0 },
      { image: '😴', options: ['难过', '累了', '无聊'], answer: 1 },
      { image: '😂', options: ['笑', '哭', '微笑'], answer: 0 },
      { image: '🤗', options: ['拥抱', '爱', '高兴'], answer: 0 },
      { image: '😍', options: ['惊喜', '爱', '高兴'], answer: 1 },
      { image: '😘', options: ['亲吻', '爱', '高兴'], answer: 0 },
      { image: '😜', options: ['顽皮', '玩笑', '开玩笑'], answer: 0 },
      { image: '🤣', options: ['大笑', '微笑', '嘿嘿'], answer: 0 },
      { image: '😱', options: ['惊讶', '害怕', '吃惊'], answer: 0 },
      { image: '😳', options: ['脸红', '害羞', '尴尬'], answer: 0 },
      { image: '🥰', options: ['爱心眼', '高兴', '可爱'], answer: 0 },
      { image: '😎', options: ['酷', '自信', '潇洒'], answer: 0 },
      { image: '🤬', options: ['生气', '发怒', '愤怒'], answer: 0 },
      { image: '😤', options: ['哼', '不满', '生气'], answer: 0 },
      { image: '🤔', options: ['思考', '沉思', '疑惑'], answer: 0 },
    ]}
  },
  {
    title: '房间名字 (Nama Bilik)',
    type: 'picture_quiz',
    emoji: '🏠',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🛋️', options: ['卧室', '客厅', '厨房'], answer: 1 },
      { image: '🛁', options: ['浴室', '卧室', '厨房'], answer: 0 },
      { image: '🍳', options: ['饭厅', '厨房', '储藏室'], answer: 1 },
      { image: '🛏️', options: ['卧室', '客厅', '浴室'], answer: 0 },
      { image: '📺', options: ['卧室', '客厅', '厨房'], answer: 1 },
      { image: '📚', options: ['书房', '卧室', '客厅'], answer: 0 },
      { image: '🚪', options: ['窗户', '门', '围栏'], answer: 1 },
      { image: '🏠', options: ['房子', '学校', '商店'], answer: 0 },
      { image: '🛌', options: ['床', '沙发', '椅子'], answer: 0 },
      { image: '🪑', options: ['椅子', '凳子', '座位'], answer: 0 },
      { image: '🚪', options: ['门', '窗户', '墙'], answer: 0 },
      { image: '🪟', options: ['窗户', '门', '墙'], answer: 0 },
      { image: '🔦', options: ['手电筒', '灯', '烛火'], answer: 0 },
      { image: '💡', options: ['灯泡', '灯', '光'], answer: 0 },
      { image: '🚿', options: ['淋浴', '洗澡', '泼水'], answer: 0 },
      { image: '🛁', options: ['浴缸', '浴室', '洗澡'], answer: 0 },
      { image: '🧻', options: ['卫生纸', '纸', '纸巾'], answer: 0 },
      { image: '🪤', options: ['陷阱', '网', '笼'], answer: 0 },
    ]}
  },
  {
    title: '学校用品 (Peralatan Sekolah)',
    type: 'picture_quiz',
    emoji: '✏️',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '✏️', options: ['铅笔', '钢笔', '蜡笔'], answer: 0 },
      { image: '📏', options: ['尺子', '剪刀', '橡皮擦'], answer: 0 },
      { image: '📚', options: ['书', '杂志', '笔记'], answer: 0 },
      { image: '🎒', options: ['书包', '手提包', '运动包'], answer: 0 },
      { image: '🖊️', options: ['铅笔', '钢笔', '马克笔'], answer: 1 },
      { image: '📐', options: ['三角尺', '尺子', '圆规'], answer: 0 },
      { image: '🖍️', options: ['彩色铅笔', '蜡笔', '钢笔'], answer: 1 },
      { image: '📓', options: ['练习本', '教科书', '日记'], answer: 0 },
      { image: '✏️', options: ['铅笔', '钢笔', '彩笔'], answer: 0 },
      { image: '🖊️', options: ['钢笔', '铅笔', '中性笔'], answer: 0 },
      { image: '🖋️', options: ['钢笔', '毛笔', '签字笔'], answer: 0 },
      { image: '✒️', options: ['墨笔', '毛笔', '钢笔'], answer: 0 },
      { image: '📝', options: ['笔记', '写字', '记录'], answer: 0 },
      { image: '🖍️', options: ['蜡笔', '彩笔', '记号笔'], answer: 0 },
      { image: '🖌️', options: ['刷子', '笔刷', '画笔'], answer: 0 },
      { image: '📐', options: ['三角尺', '量角器', '直尺'], answer: 0 },
      { image: '📏', options: ['直尺', '三角尺', '量尺'], answer: 0 },
      { image: '📌', options: ['图钉', '钉子', '夹子'], answer: 0 },
    ]}
  },
  {
    title: '星期 (Hari Dalam Seminggu)',
    type: 'multiple_choice',
    emoji: '📅',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '一周的第一天?', options: ['星期一', '星期日', '星期六'], answer: 1 },
      { problem: '星期一之后是?', options: ['星期日', '星期三', '星期二'], answer: 2 },
      { problem: '一周中间是?', options: ['星期二', '星期三', '星期四'], answer: 1 },
      { problem: '一周有几天?', options: ['5', '6', '7'], answer: 2 },
      { problem: '周末是哪几天?', options: ['星期一星期二', '星期六星期日', '星期三星期四'], answer: 1 },
      { problem: '学校上课是哪几天?', options: ['周末', '星期一到星期五', '每天'], answer: 1 },
      { problem: '星期五之后是?', options: ['星期四', '星期六', '星期日'], answer: 1 },
      { problem: '星期三之前是?', options: ['星期四', '星期二', '星期一'], answer: 1 },
      { problem: '星期二之后是?', options: ['星期一', '星期三', '星期四'], answer: 1 },
      { problem: '星期四之前是?', options: ['星期三', '星期五', '星期二'], answer: 0 },
      { problem: '星期五是第几天?', options: ['4', '5', '6'], answer: 1 },
      { problem: '今天是星期一，明天是?', options: ['星期二', '星期日', '星期三'], answer: 0 },
      { problem: '放学日是?', options: ['星期五', '星期六', '星期一'], answer: 0 },
      { problem: '周一到周五共?', options: ['4天', '5天', '6天'], answer: 1 },
      { problem: '学校休息是?', options: ['星期五', '周末', '周一'], answer: 1 },
      { problem: '昨天是星期六，今天是?', options: ['星期五', '星期日', '星期一'], answer: 1 },
      { problem: '星期日之前是?', options: ['星期五', '星期六', '星期一'], answer: 1 },
    ]}
  },
  {
    title: '反义词 (Lawan Kata)',
    type: 'multiple_choice',
    emoji: '↔️',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '"大"的反义词?', options: ['小', '长', '高'], answer: 0 },
      { problem: '"热"的反义词?', options: ['温暖', '冷', '湿'], answer: 1 },
      { problem: '"白天"的反义词?', options: ['傍晚', '黑夜', '早晨'], answer: 1 },
      { problem: '"上"的反义词?', options: ['走', '下', '去'], answer: 1 },
      { problem: '"老"的反义词?', options: ['年轻', '小', '矮'], answer: 0 },
      { problem: '"硬"的反义词?', options: ['粗糙', '软', '细'], answer: 1 },
      { problem: '"亮"的反义词?', options: ['暗淡', '黑暗', '昏暗'], answer: 1 },
      { problem: '"胖"的反义词?', options: ['瘦', '小', '矮'], answer: 0 },
      { problem: '"长"的反义词?', options: ['短', '宽', '窄'], answer: 0 },
      { problem: '"宽"的反义词?', options: ['窄', '长', '高'], answer: 0 },
      { problem: '"高"的反义词?', options: ['矮', '长', '宽'], answer: 0 },
      { problem: '"新"的反义词?', options: ['旧', '古', '老'], answer: 0 },
      { problem: '"美"的反义词?', options: ['丑', '不好', '坏'], answer: 0 },
      { problem: '"好"的反义词?', options: ['坏', '不好', '差'], answer: 0 },
      { problem: '"快乐"的反义词?', options: ['悲伤', '生气', '厌烦'], answer: 0 },
      { problem: '"白"的反义词?', options: ['黑', '灰', '暗'], answer: 0 },
      { problem: '"多"的反义词?', options: ['少', '稀少', '有限'], answer: 0 },
    ]}
  },
  {
    title: '月份 (Bulan Dalam Setahun)',
    type: 'multiple_choice',
    emoji: '📆',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '一年的第一个月?', options: ['二月', '一月', '三月'], answer: 1 },
      { problem: '一年有几个月?', options: ['10', '11', '12'], answer: 2 },
      { problem: '一年的最后一个月?', options: ['十一月', '十月', '十二月'], answer: 2 },
      { problem: '四月之后是?', options: ['三月', '五月', '六月'], answer: 1 },
      { problem: '第六个月是?', options: ['五月', '六月', '七月'], answer: 1 },
      { problem: '十二月之前是?', options: ['十月', '十一月', '九月'], answer: 1 },
      { problem: '情人节是哪个月?', options: ['一月', '二月', '三月'], answer: 1 },
      { problem: '第二个月是?', options: ['一月', '二月', '三月'], answer: 1 },
      { problem: '夏天是哪个月?', options: ['6月', '7月', '8月'], answer: 0 },
      { problem: '秋天是几月?', options: ['8月', '9月', '10月'], answer: 1 },
      { problem: '冬天是几月?', options: ['11月', '12月', '1月'], answer: 1 },
      { problem: '春天开始是?', options: ['二月', '三月', '四月'], answer: 1 },
      { problem: '十月叫?', options: ['十月', '十一月', '十二月'], answer: 0 },
      { problem: '一月是第?月?', options: ['1', '2', '3'], answer: 0 },
      { problem: '六月有?天?', options: ['30', '31', '28'], answer: 0 },
      { problem: '二月有?天?', options: ['28', '30', '31'], answer: 0 },
      { problem: '十二月有?天?', options: ['30', '31', '28'], answer: 1 },
    ]}
  },
  {
    title: '自然界 (Alam Semula Jadi)',
    type: 'picture_quiz',
    emoji: '🌿',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🌳', options: ['树', '草', '花'], answer: 0 },
      { image: '🌸', options: ['树', '花', '叶子'], answer: 1 },
      { image: '🌊', options: ['河流', '海洋', '湖泊'], answer: 1 },
      { image: '☀️', options: ['太阳', '月亮', '星星'], answer: 0 },
      { image: '🌙', options: ['太阳', '月亮', '星星'], answer: 1 },
      { image: '🌧️', options: ['晴天', '下雨', '刮风'], answer: 1 },
      { image: '🌈', options: ['雨后彩虹', '白天', '晚上'], answer: 0 },
      { image: '⛰️', options: ['山丘', '山', '平原'], answer: 1 },
      { image: '🌋', options: ['火山', '山', '山丘'], answer: 0 },
      { image: '🗻', options: ['富士山', '高山', '峰'], answer: 0 },
      { image: '🏔️', options: ['雪山', '高山', '峰'], answer: 0 },
      { image: '🌌', options: ['银河', '夜空', '星空'], answer: 0 },
      { image: '🌃', options: ['夜景', '日落', '黄昏'], answer: 0 },
      { image: '🌆', options: ['城市', '黄昏', '日落'], answer: 0 },
      { image: '🏞️', options: ['风景', '山水', '自然'], answer: 0 },
      { image: '🌲', options: ['松树', '树', '杉树'], answer: 0 },
      { image: '🌴', options: ['椰子树', '棕榈树', '香蕉树'], answer: 0 },
      { image: '🌱', options: ['嫩芽', '小草', '幼苗'], answer: 0 },
    ]}
  },
  {
    title: '健康生活 (Gaya Hidup Sihat)',
    type: 'multiple_choice',
    emoji: '💪',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '保持健康需要什么?', options: ['多吃甜食', '吃蔬菜水果', '吃炸食'], answer: 1 },
      { problem: '儿童每天需要几小时睡眠?', options: ['4小时', '8小时', '10-12小时'], answer: 2 },
      { problem: '每天要喝多少水?', options: ['很少', '足够多', '每年一次'], answer: 1 },
      { problem: '游泳是什么?', options: ['玩耍', '休息', '运动'], answer: 2 },
      { problem: '吃饭前要做什么?', options: ['学习', '睡觉', '洗手'], answer: 2 },
      { problem: '刷牙几次?', options: ['只早上', '早晚各一次', '每周一次'], answer: 1 },
      { problem: '运动对我们有什么好处?', options: ['生病', '保持健康', '疲劳'], answer: 1 },
      { problem: '骑自行车是什么?', options: ['玩耍', '运动', '工作'], answer: 1 },
      { problem: '跑步是什么?', options: ['游戏', '运动', '工作'], answer: 1 },
      { problem: '为什么要运动?', options: ['浪费时间', '保持健康', '变得懒'], answer: 1 },
      { problem: '什么时候运动最好?', options: ['睡觉时', '早上或傍晚', '午餐时'], answer: 1 },
      { problem: '每天运动多久好?', options: ['30分钟', '1小时', '2小时'], answer: 0 },
      { problem: '饮水很重要吗?', options: ['不重要', '很重要', '有点重要'], answer: 1 },
      { problem: '蔬菜对健康?', options: ['有害', '没帮助', '有益'], answer: 2 },
      { problem: '甜食吃多了?', options: ['健康', '有害', '没影响'], answer: 1 },
      { problem: '充足睡眠对?', options: ['没用', '很重要', '不需要'], answer: 1 },
      { problem: '早餐应该吃?', options: ['不吃', '吃一点', '吃得好'], answer: 2 },
    ]}
  },
  {
    title: '汉字认识 - 基础 (Huruf Cina Asas)',
    type: 'letter_match',
    emoji: '🔤',
    difficulty: 'easy',
    gameData: { questions: [
      { letter: '人', options: ['人', '大', '小', '山'], answer: 0 },
      { letter: '大', options: ['人', '大', '小', '山'], answer: 1 },
      { letter: '小', options: ['人', '大', '小', '山'], answer: 2 },
      { letter: '山', options: ['人', '大', '小', '山'], answer: 3 },
      { letter: '水', options: ['水', '火', '土', '木'], answer: 0 },
      { letter: '火', options: ['水', '火', '土', '木'], answer: 1 },
      { letter: '土', options: ['水', '火', '土', '木'], answer: 2 },
      { letter: '木', options: ['水', '火', '土', '木'], answer: 3 },
      { letter: '火', options: ['水', '火', '土', '木'], answer: 1 },
      { letter: '土', options: ['水', '火', '土', '木'], answer: 2 },
      { letter: '口', options: ['口', '囗', '□', '日'], answer: 0 },
      { letter: '门', options: ['门', '闩', '扉', '户'], answer: 0 },
      { letter: '手', options: ['手', '手指', '掌', '拳'], answer: 0 },
      { letter: '脚', options: ['脚', '足', '踏', '踩'], answer: 0 },
      { letter: '女', options: ['女', '妇', '女子', '姑'], answer: 0 },
      { letter: '子', options: ['子', '孩', '儿', '仔'], answer: 0 },
      { letter: '心', options: ['心', '心脏', '灵', '魂'], answer: 0 },
      { letter: '眼', options: ['眼', '眼睛', '目', '睛'], answer: 0 },
    ]}
  },
  {
    title: '小故事 - 小猫和小狗',
    type: 'multiple_choice',
    emoji: '📖',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '故事: "小猫和小狗是好朋友。他们在公园里玩。" - 谁是好朋友?', options: ['小猫和小鸟', '小猫和小狗', '小狗和小鸟'], answer: 1 },
      { problem: '他们在哪里玩?', options: ['学校', '公园', '家里'], answer: 1 },
      { problem: '故事里有几只动物?', options: ['1', '2', '3'], answer: 1 },
      { problem: '他们的关系是?', options: ['敌人', '好朋友', '陌生人'], answer: 1 },
      { problem: '故事教给我们什么?', options: ['打架', '交朋友', '跑步'], answer: 1 },
      { problem: '小猫在哪里?', options: ['学校', '公园', '家里'], answer: 1 },
      { problem: '小狗做了什么?', options: ['睡觉', '玩耍', '吃东西'], answer: 1 },
      { problem: '故事是关于什么的?', options: ['食物', '友谊', '学习'], answer: 1 },
      { problem: '小猫怎么看待小狗?', options: ['不喜欢', '好朋友', '敌人'], answer: 1 },
      { problem: '故事有什么教训?', options: ['要玩', '要多吃', '友谊很重要'], answer: 2 },
      { problem: '他们经常?', options: ['吵架', '玩耍', '睡觉'], answer: 1 },
      { problem: '这个故事是?', options: ['悲伤的', '快乐的', '生气的'], answer: 1 },
      { problem: '小狗的朋友是?', options: ['小猫', '小鸟', '小鱼'], answer: 0 },
      { problem: '他们都?', options: ['讨厌', '喜欢', '害怕'], answer: 1 },
      { problem: '故事里有几个主角?', options: ['1', '2', '3'], answer: 1 },
      { problem: '他们的友谊?', options: ['弱', '强', '没有'], answer: 1 },
      { problem: '故事教我们?', options: ['要吵架', '要友好', '要孤独'], answer: 1 },
    ]}
  },
  {
    title: '好习惯 (Adab Baik)',
    type: 'multiple_choice',
    emoji: '🙏',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '吃饭前要做什么?', options: ['玩耍', '洗手', '跑步'], answer: 1 },
      { problem: '见到老师要说什么?', options: ['嗨!', '老师好!', '随便'], answer: 1 },
      { problem: '别人帮助你后要说什么?', options: ['没关系', '谢谢!', '走开'], answer: 1 },
      { problem: '做错事要说什么?', options: ['不管', '对不起', '不知道'], answer: 1 },
      { problem: '垃圾应该放在哪里?', options: ['地上', '垃圾桶', '任何地方'], answer: 1 },
      { problem: '在教室里应该做什么?', options: ['大声喊叫', '认真听课', '睡觉'], answer: 1 },
      { problem: '帮助朋友是?', options: ['不好的', '好的', '不对的'], answer: 1 },
      { problem: '要排队等待是?', options: ['浪费时间', '礼貌的行为', '不必要的'], answer: 1 },
      { problem: '不打人或踢人是?', options: ['虚弱', '暴力', '有礼貌'], answer: 2 },
      { problem: '尊敬老师?', options: ['不重要', '很重要', '可选'], answer: 1 },
      { problem: '帮助父母是?', options: ['坏的', '好的', '懒的'], answer: 1 },
      { problem: '说谢谢是?', options: ['浪费话', '良好的礼貌', '不需要'], answer: 1 },
      { problem: '不打扰别人是?', options: ['无聊', '尊重', '坏'], answer: 1 },
      { problem: '分享玩具是?', options: ['坏的', '友好的', '愚蠢的'], answer: 1 },
      { problem: '听父母的话?', options: ['不好', '很好', '无关'], answer: 1 },
      { problem: '不说谎是?', options: ['不必要', '很重要', '可选'], answer: 1 },
      { problem: '做完作业后?', options: ['玩', '告诉父母', '去睡觉'], answer: 1 },
    ]}
  },
  {
    title: '植物认识 (Tumbuhan)',
    type: 'picture_quiz',
    emoji: '🌱',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🌹', options: ['玫瑰', '向日葵', '郁金香'], answer: 0 },
      { image: '🌻', options: ['玫瑰', '向日葵', '百合'], answer: 1 },
      { image: '🌺', options: ['芙蓉花', '兰花', '玫瑰'], answer: 0 },
      { image: '🌴', options: ['椰子树', '酸豆树', '榴莲树'], answer: 0 },
      { image: '🍃', options: ['叶子', '根', '茎'], answer: 0 },
      { image: '🌾', options: ['稻米', '玉米', '椰子树'], answer: 0 },
      { image: '🌵', options: ['仙人掌', '玫瑰', '稻米'], answer: 0 },
      { image: '🍄', options: ['蘑菇', '花', '树'], answer: 0 },
      { image: '🌵', options: ['仙人掌', '灌木', '树'], answer: 0 },
      { image: '🎋', options: ['竹子', '树', '草'], answer: 0 },
      { image: '🎍', options: ['松树', '杉树', '柏树'], answer: 0 },
      { image: '🌾', options: ['水稻', '小麦', '玉米'], answer: 0 },
      { image: '💐', options: ['花束', '花', '玫瑰'], answer: 0 },
      { image: '🌻', options: ['向日葵', '菊花', '向日花'], answer: 0 },
      { image: '🌷', options: ['郁金香', '玫瑰', '牡丹'], answer: 0 },
      { image: '🌹', options: ['玫瑰', '郁金香', '兰花'], answer: 0 },
      { image: '🥀', options: ['花朵', '玫瑰', '牡丹'], answer: 0 },
    ]}
  },
  {
    title: '天气认识 (Cuaca)',
    type: 'picture_quiz',
    emoji: '⛅',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '☀️', options: ['下雨', '晴天', '寒冷'], answer: 1 },
      { image: '🌧️', options: ['晴天', '下雨', '刮风'], answer: 1 },
      { image: '🌈', options: ['雨后', '白天', '夜晚'], answer: 0 },
      { image: '⛈️', options: ['暴风雨', '晴天', '刮风'], answer: 0 },
      { image: '☁️', options: ['云', '下雨', '晴天'], answer: 0 },
      { image: '❄️', options: ['晴天', '寒冷', '下雨'], answer: 1 },
      { image: '💨', options: ['下雨', '晴天', '刮风'], answer: 2 },
      { image: '🌤️', options: ['局部多云', '晴天', '下雨'], answer: 0 },
      { image: '⛅', options: ['晴间多云', '晴天', '下雨'], answer: 0 },
      { image: '🌥️', options: ['多云', '晴天', '下雨'], answer: 0 },
      { image: '☁️', options: ['云', '雾', '烟'], answer: 0 },
      { image: '🌦️', options: ['雨天', '雷雨', '阵雨'], answer: 0 },
      { image: '🌩️', options: ['雷暴', '闪电', '打雷'], answer: 0 },
      { image: '⛈️', options: ['暴风雨', '雷雨', '闪电'], answer: 0 },
      { image: '❄️', options: ['雪', '冰', '冷'], answer: 0 },
      { image: '☃️', options: ['雪人', '冰', '雪'], answer: 0 },
      { image: '⛄', options: ['雪球', '雪人', '冰'], answer: 0 },
    ]}
  },
  {
    title: '职业认识 (Kerjaya)',
    type: 'picture_quiz',
    emoji: '👔',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👨‍⚕️', options: ['医生', '老师', '工程师'], answer: 0 },
      { image: '👩‍🏫', options: ['医生', '老师', '护士'], answer: 1 },
      { image: '👮', options: ['消防员', '警察', '医生'], answer: 1 },
      { image: '🧑‍🍳', options: ['厨师', '老师', '医生'], answer: 0 },
      { image: '🧑‍🌾', options: ['医生', '农民', '木匠'], answer: 1 },
      { image: '✈️', options: ['飞行员', '医生', '船长'], answer: 0 },
      { image: '🚒', options: ['警察', '消防员', '医生'], answer: 1 },
      { image: '📚', options: ['老师', '医生', '工程师'], answer: 0 },
      { image: '👨‍💼', options: ['商人', '学生', '工人'], answer: 0 },
      { image: '👩‍💼', options: ['女商人', '学生', '工人'], answer: 0 },
      { image: '👨‍🔧', options: ['修理工', '木匠', '电工'], answer: 0 },
      { image: '👩‍🔧', options: ['女工', '修理工', '木匠'], answer: 0 },
      { image: '👨‍🌾', options: ['农民', '牧民', '园丁'], answer: 0 },
      { image: '🧑‍🚀', options: ['宇航员', '飞行员', '航海家'], answer: 0 },
      { image: '🧑‍⚖️', options: ['法官', '律师', '警察'], answer: 0 },
      { image: '🧑‍🔬', options: ['科学家', '医生', '工程师'], answer: 0 },
      { image: '🧑‍🎨', options: ['艺术家', '画家', '雕塑家'], answer: 0 },
    ]}
  },
  {
    title: '数字 11-20 (Nombor 11-20)',
    type: 'number_match',
    emoji: '🔢',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '11', options: ['十一', '十二', '十三'], answer: 0 },
      { problem: '12', options: ['十一', '十二', '十三'], answer: 1 },
      { problem: '15', options: ['十四', '十五', '十六'], answer: 1 },
      { problem: '17', options: ['十六', '十七', '十八'], answer: 1 },
      { problem: '20', options: ['十九', '二十', '二十一'], answer: 1 },
      { problem: '十五 = ?', options: ['14', '15', '16'], answer: 1 },
      { problem: '十二 = ?', options: ['11', '12', '13'], answer: 1 },
      { problem: '二十 = ?', options: ['19', '20', '21'], answer: 1 },
      { problem: '11 + 2 = ?', options: ['十二', '十三', '十四'], answer: 1 },
      { problem: '15 - 3 = ?', options: ['十二', '十三', '十四'], answer: 0 },
      { problem: '13是?', options: ['12', '13', '14'], answer: 1 },
      { problem: '19在?之前?', options: ['十八', '十七', '二十'], answer: 2 },
      { problem: '十四 = ?', options: ['13', '14', '15'], answer: 1 },
      { problem: '十八 = ?', options: ['17', '18', '19'], answer: 1 },
      { problem: '11 + 5 = ?', options: ['15', '16', '17'], answer: 0 },
      { problem: '20 - 1 = ?', options: ['18', '19', '20'], answer: 1 },
      { problem: '12 + 3 = ?', options: ['15', '14', '16'], answer: 0 },
    ]}
  },
  {
    title: '形状认识 (Bentuk)',
    type: 'picture_quiz',
    emoji: '🔵',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '⭕', options: ['圆形', '正方形', '三角形'], answer: 0 },
      { image: '⬜', options: ['圆形', '正方形', '三角形'], answer: 1 },
      { image: '△', options: ['圆形', '正方形', '三角形'], answer: 2 },
      { image: '▭', options: ['长方形', '正方形', '椭圆形'], answer: 0 },
      { image: '⭐', options: ['星形', '圆形', '三角形'], answer: 0 },
      { image: '🔶', options: ['菱形', '六边形', '正方形'], answer: 0 },
      { image: '🔷', options: ['菱形', '椭圆形', '三角形'], answer: 0 },
      { image: '🟣', options: ['球', '圆形', '椭圆形'], answer: 1 },
      { image: '🔷', options: ['蓝色菱形', '菱形', '五边形'], answer: 1 },
      { image: '🔶', options: ['橙色菱形', '菱形', '六边形'], answer: 0 },
      { image: '🔹', options: ['黄色菱形', '菱形', '五边形'], answer: 0 },
      { image: '🔸', options: ['红色菱形', '菱形', '六边形'], answer: 0 },
      { image: '⬛', options: ['黑色正方形', '正方形', '矩形'], answer: 0 },
      { image: '⬜', options: ['白色正方形', '正方形', '矩形'], answer: 0 },
      { image: '🟫', options: ['棕色正方形', '正方形', '矩形'], answer: 0 },
      { image: '⭐', options: ['星形', '五角星', '星'], answer: 0 },
      { image: '✡️', options: ['大卫之星', '星', '六角星'], answer: 0 },
    ]}
  },
];