export const prasekolah_math_expansion = [
export const prasekolah_mathematics_expansion = [
  { title: 'Kira 1 hingga 5 Lanjutan', type: 'counting', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['1','2','3'], answer: 0 },
    { image: '🍎🍎', options: ['1','2','3'], answer: 1 },
    { image: '🍎🍎🍎', options: ['1','2','3'], answer: 2 },
    { image: '🍎🍎🍎🍎', options: ['3','4','5'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎', options: ['4','5','6'], answer: 1 },
    { image: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { image: '⭐⭐⭐', options: ['2','3','4'], answer: 1 },
    { image: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { image: '🍊', options: ['1','2','3'], answer: 0 },
    { image: '🍊🍊', options: ['1','2','3'], answer: 1 },
    { image: '🍊🍊🍊', options: ['1','2','3'], answer: 2 },
    { image: '🍊🍊🍊🍊', options: ['3','4','5'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊', options: ['4','5','6'], answer: 1 },
    { image: '🎈🎈', options: ['1','2','3'], answer: 1 },
    { image: '🎈🎈🎈', options: ['2','3','4'], answer: 1 },
    { image: '🎈🎈🎈🎈', options: ['3','4','5'], answer: 1 },
    { image: '🎁', options: ['1','2','3'], answer: 0 },
    { image: '🎁🎁', options: ['1','2','3'], answer: 1 },
    { image: '🎁🎁🎁', options: ['2','3','4'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁', options: ['4','5','6'], answer: 1 },
    { image: '🌸', options: ['1','2','3'], answer: 0 },
    { image: '🌸🌸', options: ['1','2','3'], answer: 1 },
    { image: '🌸🌸🌸', options: ['2','3','4'], answer: 1 },
    { image: '🌸🌸🌸🌸', options: ['3','4','5'], answer: 1 },
    { image: '🌸🌸🌸🌸🌸', options: ['4','5','6'], answer: 1 },
    { image: '🐱', options: ['1','2','3'], answer: 0 },
    { image: '🐱🐱', options: ['1','2','3'], answer: 1 },
    { image: '🐱🐱🐱', options: ['2','3','4'], answer: 1 },
    { image: '🐱🐱🐱🐱', options: ['3','4','5'], answer: 1 },
    { image: '🐱🐱🐱🐱🐱', options: ['4','5','6'], answer: 1 },
    { image: '🏀', options: ['1','2','3'], answer: 0 },
    { image: '🏀🏀🏀', options: ['2','3','4'], answer: 1 },
    { image: '🏀🏀🏀🏀🏀', options: ['4','5','6'], answer: 1 },
    { image: '🐟🐟', options: ['1','2','3'], answer: 1 },
    { image: '🐟🐟🐟🐟', options: ['3','4','5'], answer: 1 },
    { image: '🍕', options: ['1','2','3'], answer: 0 },
    { image: '🍕🍕🍕', options: ['2','3','4'], answer: 1 },
    { image: '🍕🍕🍕🍕🍕', options: ['4','5','6'], answer: 1 },
    { image: '🌟🌟🌟', options: ['2','3','4'], answer: 1 },
    { image: '🌟🌟🌟🌟🌟', options: ['4','5','6'], answer: 1 },
  ]}},
  { title: 'Kira 6 hingga 10 Lanjutan', type: 'counting', emoji: '🔟', difficulty: 'easy', gameData: { questions: [
    { image: '🍎🍎🍎🍎🍎🍎', options: ['5','6','7'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎', options: ['6','7','8'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎', options: ['7','8','9'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['8','9','10'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['9','10','11'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊', options: ['5','6','7'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊', options: ['6','7','8'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊🍊', options: ['7','8','9'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊🍊🍊', options: ['8','9','10'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊', options: ['9','10','11'], answer: 1 },
    { image: '🎈🎈🎈🎈🎈🎈', options: ['5','6','7'], answer: 1 },
    { image: '🎈🎈🎈🎈🎈🎈🎈', options: ['6','7','8'], answer: 1 },
    { image: '🎈🎈🎈🎈🎈🎈🎈🎈', options: ['7','8','9'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁', options: ['5','6','7'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁🎁', options: ['6','7','8'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁🎁🎁', options: ['7','8','9'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁🎁🎁🎁', options: ['8','9','10'], answer: 1 },
    { image: '🌸🌸🌸🌸🌸🌸', options: ['5','6','7'], answer: 1 },
    { image: '🌸🌸🌸🌸🌸🌸🌸', options: ['6','7','8'], answer: 1 },
    { image: '🌸🌸🌸🌸🌸🌸🌸🌸', options: ['7','8','9'], answer: 1 },
    { image: '🌸🌸🌸🌸🌸🌸🌸🌸🌸', options: ['8','9','10'], answer: 1 },
    { image: '🌸🌸🌸🌸🌸🌸🌸🌸🌸🌸', options: ['9','10','11'], answer: 1 },
    { image: '🐱🐱🐱🐱🐱🐱', options: ['5','6','7'], answer: 1 },
    { image: '🐱🐱🐱🐱🐱🐱🐱🐱', options: ['7','8','9'], answer: 1 },
    { image: '🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱', options: ['9','10','11'], answer: 1 },
    { image: '🏀🏀🏀🏀🏀🏀🏀', options: ['6','7','8'], answer: 1 },
    { image: '🏀🏀🏀🏀🏀🏀🏀🏀🏀', options: ['8','9','10'], answer: 1 },
    { image: '🍕🍕🍕🍕🍕🍕', options: ['5','6','7'], answer: 1 },
    { image: '🍕🍕🍕🍕🍕🍕🍕🍕', options: ['7','8','9'], answer: 1 },
    { image: '🍕🍕🍕🍕🍕🍕🍕🍕🍕🍕', options: ['9','10','11'], answer: 1 },
    { image: '🌟🌟🌟🌟🌟🌟🌟', options: ['6','7','8'], answer: 1 },
    { image: '🌟🌟🌟🌟🌟🌟🌟🌟🌟', options: ['8','9','10'], answer: 1 },
    { image: '🌟🌟🌟🌟🌟🌟', options: ['5','6','7'], answer: 1 },
    { image: '🌟🌟🌟🌟🌟🌟🌟🌟', options: ['7','8','9'], answer: 1 },
    { image: '🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟', options: ['9','10','11'], answer: 1 },
    { image: '💎💎💎💎💎💎💎💎', options: ['7','8','9'], answer: 1 },
    { image: '💎💎💎💎💎💎💎💎💎💎', options: ['9','10','11'], answer: 1 },
  ]}},
  { title: 'Nombor 1 hingga 10 Lanjutan', type: 'number_match', emoji: '1️⃣', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐', options: ['1','2','3'], answer: 0 },
    { problem: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['1','2','3'], answer: 2 },
    { problem: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['4','5','6'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['8','9','10'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['9','10','11'], answer: 1 },
    { problem: '🍎', options: ['1','2','3'], answer: 0 },
    { problem: '🍎🍎', options: ['1','2','3'], answer: 1 },
    { problem: '🍎🍎🍎', options: ['1','2','3'], answer: 2 },
    { problem: '🍎🍎🍎🍎', options: ['3','4','5'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎', options: ['4','5','6'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎', options: ['5','6','7'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎', options: ['6','7','8'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎🍎', options: ['7','8','9'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['8','9','10'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['9','10','11'], answer: 1 },
    { problem: '🍊', options: ['1','2','3'], answer: 0 },
    { problem: '🍊🍊🍊', options: ['2','3','4'], answer: 1 },
    { problem: '🍊🍊🍊🍊🍊', options: ['4','5','6'], answer: 1 },
    { problem: '🍊🍊🍊🍊🍊🍊🍊', options: ['6','7','8'], answer: 1 },
    { problem: '🍊🍊🍊🍊🍊🍊🍊🍊🍊', options: ['8','9','10'], answer: 1 },
    { problem: 'Satu = ?', options: ['1','2','3'], answer: 0 },
    { problem: 'Dua = ?', options: ['1','2','3'], answer: 1 },
    { problem: 'Tiga = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Empat = ?', options: ['3','4','5'], answer: 1 },
    { problem: 'Lima = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Enam = ?', options: ['5','6','7'], answer: 1 },
    { problem: 'Tujuh = ?', options: ['6','7','8'], answer: 1 },
    { problem: 'Lapan = ?', options: ['7','8','9'], answer: 1 },
    { problem: 'Sembilan = ?', options: ['8','9','10'], answer: 1 },
    { problem: 'Sepuluh = ?', options: ['9','10','11'], answer: 1 },
    { problem: 'Sifar = ?', options: ['0','1','2'], answer: 0 },
    { problem: '1 + 0 = ?', options: ['0','1','2'], answer: 1 },
    { problem: '0 + 0 = ?', options: ['0','1','2'], answer: 0 },
    { problem: '5 + 0 = ?', options: ['4','5','6'], answer: 1 },
    { problem: '10 - 0 = ?', options: ['9','10','11'], answer: 1 },
  ]}},
  { title: 'Tambah 1+1 hingga 5+5 Lanjutan', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '1+1', options: ['3','2','4','1'], answer: 1 },
    { problem: '2+1', options: ['4','3','5','2'], answer: 1 },
    { problem: '1+2', options: ['4','3','5','2'], answer: 1 },
    { problem: '2+2', options: ['6','4','5','3'], answer: 1 },
    { problem: '3+1', options: ['6','4','5','2'], answer: 1 },
    { problem: '2+3', options: ['7','5','6','4'], answer: 1 },
    { problem: '4+1', options: ['7','5','6','4'], answer: 1 },
    { problem: '3+3', options: ['7','6','8','5'], answer: 1 },
    { problem: '1+3', options: ['5','4','3','2'], answer: 1 },
    { problem: '4+2', options: ['7','6','8','5'], answer: 1 },
    { problem: '1+4', options: ['6','5','4','3'], answer: 1 },
    { problem: '2+4', options: ['7','6','8','5'], answer: 1 },
    { problem: '3+2', options: ['6','5','4','3'], answer: 1 },
    { problem: '5+1', options: ['7','6','8','4'], answer: 1 },
    { problem: '1+5', options: ['7','6','8','4'], answer: 1 },
    { problem: '4+3', options: ['8','7','6','5'], answer: 1 },
    { problem: '2+5', options: ['8','7','6','4'], answer: 1 },
    { problem: '5+2', options: ['8','7','6','4'], answer: 1 },
    { problem: '3+4', options: ['8','7','6','5'], answer: 1 },
    { problem: '5+5', options: ['11','10','9','8'], answer: 1 },
    { problem: '0+5', options: ['4','5','6'], answer: 1 },
    { problem: '5+0', options: ['4','5','6'], answer: 1 },
    { problem: '0+0', options: ['0','1','2'], answer: 0 },
    { problem: '3+0', options: ['2','3','4'], answer: 1 },
    { problem: '0+4', options: ['3','4','5'], answer: 1 },
    { problem: '4+4', options: ['7','8','9'], answer: 1 },
    { problem: '3+5', options: ['7','8','9'], answer: 1 },
    { problem: '5+3', options: ['7','8','9'], answer: 1 },
    { problem: '4+5', options: ['8','9','10'], answer: 1 },
    { problem: '5+4', options: ['8','9','10'], answer: 1 },
    { problem: '2+0', options: ['1','2','3'], answer: 1 },
    { problem: '1+0', options: ['0','1','2'], answer: 1 },
    { problem: '2+2', options: ['3','4','5'], answer: 1 },
    { problem: '3+3', options: ['5','6','7'], answer: 1 },
    { problem: 'Dua tambah tiga = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Empat tambah satu = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Tiga tambah dua = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Lima tambah dua = ?', options: ['6','7','8'], answer: 1 },
    { problem: 'Satu tambah empat = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Dua tambah dua = ?', options: ['3','4','5'], answer: 1 },
  ]}},
  { title: 'Bentuk Geometri Mudah Lanjutan', type: 'shape_sort', emoji: '🔵', difficulty: 'easy', gameData: { questions: [
    { image: '⭕', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 0 },
    { image: '⬜', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 2 },
    { image: '▭', options: ['Segiempat Tepat','Segi Empat','Bujur'], answer: 0 },
    { image: '⭐', options: ['Bintang','Bulatan','Segi Tiga'], answer: 0 },
    { image: '🔶', options: ['Heksagon','Berlian','Segi Empat'], answer: 1 },
    { image: '🔷', options: ['Berlian','Bujur','Segi Tiga'], answer: 0 },
    { image: '🔴', options: ['Bulatan','Bola','Cakera'], answer: 1 },
    { image: '⭕', options: ['Bulatan','Segi Tiga','Berlian'], answer: 0 },
    { image: '△', options: ['Segi Empat','Segi Tiga','Bulatan'], answer: 1 },
    { image: '⬜', options: ['Segi Tiga','Segi Empat','Bulatan'], answer: 1 },
    { image: '🔷', options: ['Bulatan','Segi Tiga','Berlian'], answer: 2 },
    { image: '🔶', options: ['Bulatan','Segi Empat','Heksagon'], answer: 2 },
    { image: '⭐', options: ['Bulatan','Bintang','Segi Empat'], answer: 1 },
    { image: '🔵', options: ['Berlian','Bulatan','Segi Tiga'], answer: 1 },
    { image: '🟢', options: ['Segi Empat','Bulatan','Segi Tiga'], answer: 1 },
    { image: '▭', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Segi Empat','Bulatan','Segi Tiga'], answer: 2 },
    { image: '⬜', options: ['Segi Empat','Bulatan','Berlian'], answer: 0 },
    { image: '⭐', options: ['Segi Empat','Segi Tiga','Bintang'], answer: 2 },
    { problem: 'Segi tiga mempunyai berapa sisi?', options: ['2','3','4'], answer: 1 },
    { problem: 'Segi empat mempunyai berapa sisi?', options: ['3','4','5'], answer: 1 },
    { problem: 'Bulatan mempunyai berapa bucu?', options: ['0','1','2'], answer: 0 },
    { problem: 'Segi enam mempunyai berapa sisi?', options: ['5','6','7'], answer: 1 },
    { problem: 'Pentagon mempunyai berapa sisi?', options: ['4','5','6'], answer: 1 },
    { problem: 'Bentuk apakah seperti bola?', options: ['Kiub','Sfera','Silinder'], answer: 1 },
    { problem: 'Bentuk apakah seperti tin?', options: ['Kiub','Sfera','Silinder'], answer: 2 },
    { problem: 'Bentuk apakah seperti kotak?', options: ['Kiub/Kuboid','Sfera','Silinder'], answer: 0 },
    { problem: 'Manakah yang tiada sudut?', options: ['Segi Empat','Segi Tiga','Bulatan'], answer: 2 },
    { problem: 'Bentuk pizza biasanya?', options: ['Bulat','Segi Empat','Segi Tiga'], answer: 0 },
    { problem: 'Bentuk buku biasanya?', options: ['Bulatan','Segi Empat Tepat','Segi Tiga'], answer: 1 },
    { problem: 'Bentuk roda kereta?', options: ['Segi Empat','Bulatan','Segi Tiga'], answer: 1 },
    { problem: 'Berapakah sisi segi tiga?', options: ['2','3','4'], answer: 1 },
    { problem: 'Berapakah sudut segi empat?', options: ['2','3','4'], answer: 2 },
    { problem: 'Octagon mempunyai berapa sisi?', options: ['6','7','8'], answer: 2 },
    { problem: 'Kubus mempunyai berapa muka?', options: ['4','5','6'], answer: 2 },
    { problem: 'Berlian (diamond) mempunyai berapa sisi?', options: ['3','4','5'], answer: 1 },
    { problem: 'Bentuk bintang mempunyai berapa mata?', options: ['4','5','6'], answer: 1 },
    { problem: 'Trapezium mempunyai berapa sisi?', options: ['3','4','5'], answer: 1 },
    { problem: 'Segi empat tepat — panjang dan lebar?', options: ['Semua sama','Berlainan panjang & lebar','Tiada panjang'], answer: 1 },
  ]}},
  { title: 'Lebih Besar atau Lebih Kecil Lanjutan', type: 'math_puzzle', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: '3 atau 5?', options: ['3 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '7 atau 4?', options: ['7 lebih besar','4 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 2?', options: ['2 lebih besar','2 lebih kecil','Sama'], answer: 2 },
    { problem: '1 atau 9?', options: ['1 lebih besar','9 lebih besar','Sama'], answer: 1 },
    { problem: '6 atau 3?', options: ['6 lebih besar','3 lebih besar','Sama'], answer: 0 },
    { problem: '5 atau 8?', options: ['5 lebih besar','8 lebih besar','Sama'], answer: 1 },
    { problem: '4 atau 4?', options: ['4 lebih besar','4 lebih kecil','Sama'], answer: 2 },
    { problem: '10 atau 7?', options: ['10 lebih besar','7 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 8?', options: ['2 lebih besar','8 lebih besar','Sama'], answer: 1 },
    { problem: '9 atau 6?', options: ['9 lebih besar','6 lebih besar','Sama'], answer: 0 },
    { problem: '5 atau 5?', options: ['5 lebih besar','5 lebih kecil','Sama'], answer: 2 },
    { problem: '3 atau 1?', options: ['3 lebih besar','1 lebih besar','Sama'], answer: 0 },
    { problem: '4 atau 7?', options: ['4 lebih besar','7 lebih besar','Sama'], answer: 1 },
    { problem: '8 atau 8?', options: ['8 lebih besar','8 lebih kecil','Sama'], answer: 2 },
    { problem: '6 atau 9?', options: ['6 lebih besar','9 lebih besar','Sama'], answer: 1 },
    { problem: '10 atau 3?', options: ['10 lebih besar','3 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 5?', options: ['2 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '7 atau 7?', options: ['7 lebih besar','7 lebih kecil','Sama'], answer: 2 },
    { problem: '1 atau 5?', options: ['1 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '9 atau 9?', options: ['9 lebih besar','9 lebih kecil','Sama'], answer: 2 },
    { problem: 'Nombor terbesar antara 5, 3, 8?', options: ['5','3','8'], answer: 2 },
    { problem: 'Nombor terkecil antara 2, 7, 4?', options: ['2','7','4'], answer: 0 },
    { problem: 'Susun dari kecil ke besar: 3, 1, 5?', options: ['3,1,5','1,3,5','5,3,1'], answer: 1 },
    { problem: 'Susun dari besar ke kecil: 2, 8, 4?', options: ['2,8,4','4,8,2','8,4,2'], answer: 2 },
    { problem: 'Lambang ">" bermaksud?', options: ['Sama dengan','Lebih besar dari','Lebih kecil dari'], answer: 1 },
    { problem: 'Lambang "<" bermaksud?', options: ['Sama dengan','Lebih besar dari','Lebih kecil dari'], answer: 2 },
    { problem: 'Lambang "=" bermaksud?', options: ['Sama dengan','Lebih besar','Lebih kecil'], answer: 0 },
    { problem: 'Nombor selepas 9 ialah?', options: ['8','10','11'], answer: 1 },
    { problem: 'Nombor sebelum 5 ialah?', options: ['6','4','3'], answer: 1 },
    { problem: 'Nombor antara 3 dan 5 ialah?', options: ['2','4','6'], answer: 1 },
    { problem: 'Nombor terbesar 1 digit?', options: ['8','9','10'], answer: 1 },
    { problem: 'Nombor terkecil lebih dari 0?', options: ['0','1','2'], answer: 1 },
    { problem: 'Mana lebih besar: 15 atau 12?', options: ['15','12','Sama'], answer: 0 },
    { problem: 'Mana lebih kecil: 20 atau 18?', options: ['20','18','Sama'], answer: 1 },
    { problem: '0 atau 1?', options: ['0 lebih besar','1 lebih besar','Sama'], answer: 1 },
    { problem: 'Nombor antara 7 dan 9?', options: ['6','8','10'], answer: 1 },
    { problem: '12 adalah lebih besar dari?', options: ['15','13','10'], answer: 2 },
    { problem: 'Mana yang paling kecil: 100, 10, 1000?', options: ['100','10','1000'], answer: 1 },
    { problem: '5 lebih dari 3 bermaksud?', options: ['5 < 3','5 > 3','5 = 3'], answer: 1 },
    { problem: '2 kurang dari 6 bermaksud?', options: ['2 > 6','2 = 6','2 < 6'], answer: 2 },
  ]}},
  { title: 'Tolak Mudah Lanjutan', type: 'math_puzzle', emoji: '➖', difficulty: 'easy', gameData: { questions: [
    { problem: '3-1', options: ['1','2','3','4'], answer: 1 },
    { problem: '5-2', options: ['2','3','4','5'], answer: 1 },
    { problem: '4-1', options: ['2','3','4','5'], answer: 1 },
    { problem: '6-3', options: ['2','3','4','5'], answer: 1 },
    { problem: '7-2', options: ['4','5','6','7'], answer: 1 },
    { problem: '8-4', options: ['3','4','5','6'], answer: 1 },
    { problem: '9-3', options: ['5','6','7','8'], answer: 1 },
    { problem: '10-5', options: ['4','5','6','7'], answer: 1 },
    { problem: '4-2', options: ['1','2','3','4'], answer: 1 },
    { problem: '6-1', options: ['4','5','6','7'], answer: 1 },
    { problem: '5-3', options: ['1','2','3','4'], answer: 1 },
    { problem: '8-2', options: ['5','6','7','8'], answer: 1 },
    { problem: '7-4', options: ['2','3','4','5'], answer: 1 },
    { problem: '5-1', options: ['3','4','5','6'], answer: 1 },
    { problem: '9-4', options: ['4','5','6','7'], answer: 1 },
    { problem: '6-2', options: ['3','4','5','6'], answer: 1 },
    { problem: '8-3', options: ['4','5','6','7'], answer: 1 },
    { problem: '7-3', options: ['3','4','5','6'], answer: 1 },
    { problem: '4-3', options: ['0','1','2','3'], answer: 1 },
    { problem: '10-6', options: ['3','4','5','6'], answer: 1 },
    { problem: '2-1', options: ['0','1','2'], answer: 1 },
    { problem: '10-9', options: ['0','1','2'], answer: 1 },
    { problem: '5-5', options: ['0','1','2'], answer: 0 },
    { problem: '6-6', options: ['0','1','2'], answer: 0 },
    { problem: '7-7', options: ['0','1','2'], answer: 0 },
    { problem: '10-0', options: ['9','10','11'], answer: 1 },
    { problem: '9-0', options: ['8','9','10'], answer: 1 },
    { problem: '10-1', options: ['8','9','10'], answer: 1 },
    { problem: '10-2', options: ['7','8','9'], answer: 1 },
    { problem: '10-3', options: ['6','7','8'], answer: 1 },
    { problem: '9-5', options: ['3','4','5'], answer: 1 },
    { problem: '8-6', options: ['1','2','3'], answer: 1 },
    { problem: '7-5', options: ['1','2','3'], answer: 1 },
    { problem: '9-2', options: ['6','7','8'], answer: 1 },
    { problem: '8-1', options: ['6','7','8'], answer: 1 },
    { problem: 'Lima tolak dua = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Enam tolak tiga = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Sepuluh tolak empat = ?', options: ['5','6','7'], answer: 1 },
    { problem: 'Lapan tolak lima = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Sembilan tolak satu = ?', options: ['7','8','9'], answer: 1 },
  ]}},
  { title: 'Susunan Nombor Lanjutan', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: 'Selepas 3 ialah?', options: ['2','4','5','3'], answer: 1 },
    { problem: 'Selepas 6 ialah?', options: ['5','7','8','6'], answer: 1 },
    { problem: 'Sebelum 5 ialah?', options: ['6','4','3','5'], answer: 1 },
    { problem: 'Sebelum 9 ialah?', options: ['10','8','7','9'], answer: 1 },
    { problem: 'Antara 4 dan 6?', options: ['3','5','7','4'], answer: 1 },
    { problem: 'Antara 1 dan 3?', options: ['0','2','4','1'], answer: 1 },
    { problem: 'Selepas 8 ialah?', options: ['7','9','10','8'], answer: 1 },
    { problem: 'Sebelum 2 ialah?', options: ['3','1','0','2'], answer: 1 },
    { problem: 'Selepas 1 ialah?', options: ['0','2','3','1'], answer: 1 },
    { problem: 'Selepas 7 ialah?', options: ['6','8','9','7'], answer: 1 },
    { problem: 'Sebelum 10 ialah?', options: ['11','9','8','10'], answer: 1 },
    { problem: 'Sebelum 4 ialah?', options: ['5','3','2','4'], answer: 1 },
    { problem: 'Antara 7 dan 9?', options: ['6','8','10','7'], answer: 1 },
    { problem: 'Antara 2 dan 4?', options: ['1','3','5','2'], answer: 1 },
    { problem: 'Selepas 4 ialah?', options: ['3','5','6','4'], answer: 1 },
    { problem: 'Selepas 9 ialah?', options: ['8','10','11','9'], answer: 1 },
    { problem: 'Sebelum 7 ialah?', options: ['8','6','5','7'], answer: 1 },
    { problem: 'Sebelum 3 ialah?', options: ['4','2','1','3'], answer: 1 },
    { problem: 'Antara 5 dan 7?', options: ['4','6','8','5'], answer: 1 },
    { problem: 'Antara 8 dan 10?', options: ['7','9','11','8'], answer: 1 },
    { problem: 'Hitung: 1,2,3,4,5,?,7', options: ['5','6','8'], answer: 1 },
    { problem: 'Hitung: 3,4,?,6,7', options: ['4','5','6'], answer: 1 },
    { problem: 'Hitung: 8,9,?,11', options: ['7','10','12'], answer: 1 },
    { problem: 'Hitung: 2,4,6,?,10', options: ['7','8','9'], answer: 1 },
    { problem: 'Hitung: 1,3,5,?,9', options: ['6','7','8'], answer: 1 },
    { problem: 'Selepas 10 ialah?', options: ['9','11','12'], answer: 1 },
    { problem: 'Selepas 15 ialah?', options: ['14','16','17'], answer: 1 },
    { problem: 'Sebelum 20 ialah?', options: ['21','19','18'], answer: 1 },
    { problem: 'Antara 10 dan 12?', options: ['9','11','13'], answer: 1 },
    { problem: 'Nombor genap selepas 4?', options: ['5','6','7'], answer: 1 },
    { problem: 'Nombor ganjil selepas 5?', options: ['6','7','8'], answer: 1 },
    { problem: 'Nombor genap selepas 8?', options: ['9','10','11'], answer: 1 },
    { problem: 'Nombor ganjil selepas 7?', options: ['8','9','10'], answer: 1 },
    { problem: 'Hitung melompat 2: 0,2,4,?', options: ['5','6','7'], answer: 1 },
    { problem: 'Hitung melompat 5: 5,10,?,20', options: ['14','15','16'], answer: 1 },
    { problem: 'Nombor yang habis bahagi 2 dipanggil?', options: ['Nombor ganjil','Nombor genap','Nombor prima'], answer: 1 },
    { problem: '1, 2, 3, ... nombor ini?', options: ['Nombor genap','Nombor bulat asli','Nombor negatif'], answer: 1 },
    { problem: 'Nombor bulat sebelum 10?', options: ['11','9','8'], answer: 1 },
    { problem: 'Berapa nombor antara 1 dan 5?', options: ['2','3','4'], answer: 1 },
    { problem: 'Hitung melompat 2: 10,8,6,?', options: ['5','4','3'], answer: 1 },
  ]}},
];