export const prasekolah_science = [
  { title: 'Haiwan & Tempat Tinggal', type: 'picture_quiz', emoji: '🦁', difficulty: 'easy', gameData: { questions: [
    { image: '🐠', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🐦', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐿️', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦈', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦅', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐜', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🐢', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦆', options: ['Air','Udara','Tanah'], answer: 1 },
  ]}},
  { title: 'Warna-Warni di Alam', type: 'color_match', emoji: '🌈', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Merah','Biru','Hijau'], answer: 0 },
    { image: '🔵', options: ['Merah','Biru','Hijau'], answer: 1 },
    { image: '🟢', options: ['Merah','Biru','Hijau'], answer: 2 },
    { image: '🟡', options: ['Kuning','Oren','Merah'], answer: 0 },
    { image: '🟠', options: ['Kuning','Oren','Merah'], answer: 1 },
    { image: '💜', options: ['Ungu','Merah Jambu','Biru'], answer: 0 },
    { image: '🤎', options: ['Coklat','Hitam','Kelabu'], answer: 0 },
    { image: '⚫', options: ['Coklat','Hitam','Kelabu'], answer: 1 },
  ]}},
  { title: 'Makanan Sihat', type: 'picture_quiz', emoji: '🥗', difficulty: 'easy', gameData: { questions: [
    { image: '🥦', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍕', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥕', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍩', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🍎', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍔', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥛', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍬', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
  ]}},
  { title: 'Siang dan Malam', type: 'picture_quiz', emoji: '🌙', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['Siang','Malam','Petang'], answer: 0 },
    { image: '🌙', options: ['Siang','Malam','Pagi'], answer: 1 },
    { image: '🌅', options: ['Pagi','Tengahari','Malam'], answer: 0 },
    { image: '🌇', options: ['Pagi','Petang','Malam'], answer: 1 },
    { image: '⭐', options: ['Siang','Malam','Pagi'], answer: 1 },
    { image: '🌄', options: ['Pagi','Malam','Petang'], answer: 0 },
    { image: '🌤️', options: ['Siang','Malam','Subuh'], answer: 0 },
    { image: '🌃', options: ['Siang','Malam','Pagi'], answer: 1 },
  ]}},
  { title: 'Pancaindera', type: 'picture_quiz', emoji: '👁️', difficulty: 'easy', gameData: { questions: [
    { image: '👁️', options: ['Lihat','Dengar','Rasa'], answer: 0 },
    { image: '👂', options: ['Lihat','Dengar','Bau'], answer: 1 },
    { image: '👃', options: ['Lihat','Rasa','Bau'], answer: 2 },
    { image: '👅', options: ['Bau','Rasa','Dengar'], answer: 1 },
    { image: '✋', options: ['Lihat','Dengar','Sentuh'], answer: 2 },
    { image: '🌹', options: ['Harum','Berbunyi','Pahit'], answer: 0 },
    { image: '🍋', options: ['Manis','Masam','Masin'], answer: 1 },
    { image: '🥁', options: ['Berbunyi','Harum','Rasa'], answer: 0 },
  ]}},
  { title: 'Tumbuhan di Sekeliling Kita', type: 'picture_quiz', emoji: '🌱', difficulty: 'easy', gameData: { questions: [
    { image: '🌳', options: ['Pokok','Bunga','Rumput'], answer: 0 },
    { image: '🌸', options: ['Pokok','Bunga','Daun'], answer: 1 },
    { image: '🍀', options: ['Bunga','Daun','Biji'], answer: 1 },
    { image: '🌵', options: ['Kaktus','Pokok Epal','Pokok Kelapa'], answer: 0 },
    { image: '🌻', options: ['Ros','Bunga Matahari','Orkid'], answer: 1 },
    { image: '🍄', options: ['Cendawan','Bunga','Pokok'], answer: 0 },
    { image: '🌿', options: ['Rumput','Daun','Akar'], answer: 1 },
    { image: '🌾', options: ['Padi','Rumput','Gandum'], answer: 0 },
  ]}},
  { title: 'Langit dan Cuaca', type: 'picture_quiz', emoji: '⛅', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['Panas','Sejuk','Hujan'], answer: 0 },
    { image: '🌧️', options: ['Panas','Sejuk','Hujan'], answer: 2 },
    { image: '⛅', options: ['Awan','Panas','Gelap'], answer: 0 },
    { image: '🌈', options: ['Pelangi','Kilat','Hujan'], answer: 0 },
    { image: '💨', options: ['Angin','Hujan','Panas'], answer: 0 },
    { image: '🌩️', options: ['Kilat','Pelangi','Awan'], answer: 0 },
    { image: '❄️', options: ['Ais','Hujan','Salji'], answer: 2 },
    { image: '🌫️', options: ['Kabus','Asap','Awan'], answer: 0 },
  ]}},
  { title: 'Haiwan Peliharaan', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🐶', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🐰', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🦁', options: ['Peliharaan','Liar','Ternakan'], answer: 1 },
    { image: '🐄', options: ['Peliharaan','Liar','Ternakan'], answer: 2 },
    { image: '🐍', options: ['Peliharaan','Liar','Bahaya'], answer: 1 },
    { image: '🐠', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🐔', options: ['Peliharaan','Liar','Ternakan'], answer: 2 },
  ]}},
  { title: 'Benda Hidup dan Benda Mati', type: 'picture_quiz', emoji: '🌿', difficulty: 'easy', gameData: { questions: [
    { image: '🌳', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🪑', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🐶', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '📚', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🐟', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🪨', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🌸', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🚗', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
  ]}},
  { title: 'Musim dan Perubahan Alam', type: 'picture_quiz', emoji: '🍂', difficulty: 'easy', gameData: { questions: [
    { image: '🌧️🌧️🌧️', options: ['Musim Hujan','Musim Panas','Musim Bunga'], answer: 0 },
    { image: '☀️☀️☀️', options: ['Musim Hujan','Musim Panas','Musim Salji'], answer: 1 },
    { image: '🍂🍁', options: ['Musim Luruh','Musim Bunga','Musim Panas'], answer: 0 },
    { image: '❄️⛄', options: ['Musim Panas','Musim Luruh','Musim Sejuk'], answer: 2 },
    { image: '🌸🌷', options: ['Musim Bunga','Musim Luruh','Musim Panas'], answer: 0 },
    { image: '🌈', options: ['Selepas Hujan','Semasa Panas','Waktu Malam'], answer: 0 },
    { image: '⛈️', options: ['Ribut Petir','Hari Cerah','Hari Berangin'], answer: 0 },
    { image: '🌬️', options: ['Angin Kencang','Hujan Lebat','Hari Panas'], answer: 0 },
  ]}},
  { title: 'Bahagian Tumbuhan', type: 'picture_quiz', emoji: '🌱', difficulty: 'easy', gameData: { questions: [
    { image: '🌱', options: ['Akar','Batang','Daun'], answer: 1 },
    { image: '🍂', options: ['Bunga','Daun','Buah'], answer: 1 },
    { image: '🌸', options: ['Daun','Bunga','Biji'], answer: 1 },
    { image: '🍎', options: ['Biji','Batang','Buah'], answer: 2 },
    { image: '🌿', options: ['Dahan','Daun','Akar'], answer: 1 },
    { image: '🌰', options: ['Biji','Daun','Bunga'], answer: 0 },
    { image: '🪵', options: ['Dahan','Batang','Akar'], answer: 1 },
    { image: '🌲', options: ['Semak','Pokok','Herba'], answer: 1 },
  ]}},
  { title: 'Aktiviti Menggunakan Deria', type: 'picture_quiz', emoji: '🔬', difficulty: 'easy', gameData: { questions: [
    { image: '📖', options: ['Dengar','Baca/Lihat','Rasa'], answer: 1 },
    { image: '🎵', options: ['Dengar','Bau','Sentuh'], answer: 0 },
    { image: '🌹', options: ['Rasa','Bau','Lihat'], answer: 1 },
    { image: '🍰', options: ['Sentuh','Dengar','Rasa'], answer: 2 },
    { image: '🧸', options: ['Sentuh','Bau','Dengar'], answer: 0 },
    { image: '🌅', options: ['Dengar','Lihat','Rasa'], answer: 1 },
    { image: '🌊', options: ['Lihat & Dengar','Rasa','Bau'], answer: 0 },
    { image: '🔥', options: ['Sejuk','Panas','Halus'], answer: 1 },
  ]}},
  { title: 'Haiwan Laut dan Darat', type: 'picture_quiz', emoji: '🌊', difficulty: 'easy', gameData: { questions: [
    { image: '🐳', options: ['Laut','Darat','Udara'], answer: 0 },
    { image: '🦁', options: ['Laut','Darat','Udara'], answer: 1 },
    { image: '🦅', options: ['Laut','Darat','Udara'], answer: 2 },
    { image: '🐙', options: ['Laut','Darat','Udara'], answer: 0 },
    { image: '🐘', options: ['Laut','Darat','Udara'], answer: 1 },
    { image: '🦋', options: ['Laut','Darat','Udara'], answer: 2 },
    { image: '🦈', options: ['Laut','Darat','Udara'], answer: 0 },
    { image: '🐍', options: ['Laut','Darat','Udara'], answer: 1 },
  ]}},
  { title: 'Keperluan Asas Manusia', type: 'picture_quiz', emoji: '🏠', difficulty: 'easy', gameData: { questions: [
    { image: '🍚', options: ['Keperluan','Kemahuan','Tiada'], answer: 0 },
    { image: '🏠', options: ['Keperluan','Kemahuan','Tiada'], answer: 0 },
    { image: '👕', options: ['Keperluan','Kemahuan','Tiada'], answer: 0 },
    { image: '💊', options: ['Keperluan','Kemahuan','Tiada'], answer: 0 },
    { image: '🎮', options: ['Keperluan','Kemahuan','Tiada'], answer: 1 },
    { image: '💧', options: ['Keperluan','Kemahuan','Tiada'], answer: 0 },
    { image: '🍫', options: ['Keperluan','Kemahuan','Tiada'], answer: 1 },
    { image: '📚', options: ['Keperluan','Kemahuan','Tiada'], answer: 0 },
  ]}},
  { title: 'Bahan di Alam Sekitar', type: 'multiple_choice', emoji: '🧪', difficulty: 'easy', gameData: { questions: [
    { problem: 'Air boleh berubah jadi?', options: ['Api','Wap','Tanah'], answer: 1 },
    { problem: 'Salji adalah air dalam keadaan?', options: ['Cecair','Pepejal','Gas'], answer: 1 },
    { problem: 'Udara adalah dalam keadaan?', options: ['Pepejal','Cecair','Gas'], answer: 2 },
    { problem: 'Besi adalah jenis bahan?', options: ['Logam','Plastik','Kayu'], answer: 0 },
    { problem: 'Batu adalah jenis bahan?', options: ['Logam','Batu','Plastik'], answer: 1 },
    { problem: 'Kertas diperbuat dari?', options: ['Plastik','Kayu','Besi'], answer: 1 },
    { problem: 'Balon diperbuat dari?', options: ['Kaca','Getah','Besi'], answer: 1 },
    { problem: 'Kaca adalah bahan yang?', options: ['Lut Cahaya','Gelap','Lembut'], answer: 0 },
  ]}},
  { title: 'Bunyi di Sekeliling Kita', type: 'multiple_choice', emoji: '🔊', difficulty: 'easy', gameData: { questions: [
    { problem: 'Bunyi hujan adalah?', options: ['Tok-tok','Titik-titik','Boom'], answer: 1 },
    { problem: 'Bunyi harimau adalah?', options: ['Meow','Roar','Baa'], answer: 1 },
    { problem: 'Bunyi loceng adalah?', options: ['Ding-dong','Vroom','Splash'], answer: 0 },
    { problem: 'Bunyi kereta adalah?', options: ['Beep','Vroom','Kedua-dua'], answer: 2 },
    { problem: 'Tempat yang paling senyap?', options: ['Jalan raya','Perpustakaan','Padang'], answer: 1 },
    { problem: 'Bunyi dibuat oleh?', options: ['Getaran','Cahaya','Bau'], answer: 0 },
    { problem: 'Bunyi dapat didengar menggunakan?', options: ['Mata','Hidung','Telinga'], answer: 2 },
    { problem: 'Bunyi yang kuat dipanggil?', options: ['Bising','Senyap','Perlahan'], answer: 0 },
  ]}},
  { title: 'Makanan Haiwan', type: 'picture_quiz', emoji: '🦁', difficulty: 'easy', gameData: { questions: [
    { image: '🦁', options: ['Daun','Daging','Biji'], answer: 1 },
    { image: '🐇', options: ['Rumput','Daging','Ikan'], answer: 0 },
    { image: '🐼', options: ['Daging','Buluh','Ikan'], answer: 1 },
    { image: '🦅', options: ['Rumput','Biji','Ikan/Tikus'], answer: 2 },
    { image: '🐄', options: ['Daging','Rumput','Serangga'], answer: 1 },
    { image: '🐸', options: ['Rumput','Serangga','Biji'], answer: 1 },
    { image: '🦋', options: ['Nektar Bunga','Daging','Rumput'], answer: 0 },
    { image: '🐟', options: ['Rumput','Plankton/Ikan kecil','Daging'], answer: 1 },
  ]}},
  { title: 'Kebersihan dan Kesihatan', type: 'picture_quiz', emoji: '🧼', difficulty: 'easy', gameData: { questions: [
    { image: '🧼', options: ['Basuh tangan','Mandi','Gosok gigi'], answer: 0 },
    { image: '🪥', options: ['Basuh tangan','Gosok gigi','Cuci muka'], answer: 1 },
    { image: '🚿', options: ['Mandi','Berenang','Basuh baju'], answer: 0 },
    { image: '😷', options: ['Sakit','Sihat','Lapar'], answer: 0 },
    { image: '💊', options: ['Makanan','Ubat','Vitamin'], answer: 2 },
    { image: '🏃', options: ['Bersenam','Tidur','Makan'], answer: 0 },
    { image: '🥗', options: ['Makanan Sihat','Makanan Lazat','Makanan Mahal'], answer: 0 },
    { image: '💤', options: ['Berehat','Tidur Awal','Tidur Lewat'], answer: 0 },
  ]}},
  { title: 'Alam Semulajadi', type: 'picture_quiz', emoji: '🏔️', difficulty: 'easy', gameData: { questions: [
    { image: '🏔️', options: ['Bukit','Gunung','Lembah'], answer: 1 },
    { image: '🌊', options: ['Sungai','Laut','Tasik'], answer: 1 },
    { image: '🏖️', options: ['Pantai','Sungai','Tasik'], answer: 0 },
    { image: '🌲🌲🌲', options: ['Kebun','Hutan','Taman'], answer: 1 },
    { image: '🏞️', options: ['Sungai','Tasik','Laut'], answer: 0 },
    { image: '🌋', options: ['Bukit','Gunung Berapi','Cerun'], answer: 1 },
    { image: '🏝️', options: ['Semenanjung','Pulau','Tanah Besar'], answer: 1 },
    { image: '🌵🏜️', options: ['Hutan','Padang Rumput','Gurun'], answer: 2 },
  ]}},
];