// Expansion for SR Math - adds more games AND more questions per game
export const sekolah_mathematics_expansion = [
  // ===== DARJAH 1 EXPANDED =====
  { title: 'Nombor 1-10 Lanjutan D1', type: 'number_match', emoji: '1️⃣', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: '⭐', options: ['1','2','3'], answer: 0 },
    { problem: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['1','2','3'], answer: 2 },
    { problem: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['4','5','6'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['8','9','10'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['9','10','11'], answer: 1 },
    { problem: 'Satu = ?', options: ['1','2','3'], answer: 0 },
    { problem: 'Tiga = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Lima = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Tujuh = ?', options: ['6','7','8'], answer: 1 },
    { problem: 'Sembilan = ?', options: ['8','9','10'], answer: 1 },
    { problem: 'Dua = ?', options: ['1','2','3'], answer: 1 },
    { problem: 'Empat = ?', options: ['3','4','5'], answer: 1 },
    { problem: 'Enam = ?', options: ['5','6','7'], answer: 1 },
    { problem: 'Lapan = ?', options: ['7','8','9'], answer: 1 },
    { problem: 'Sepuluh = ?', options: ['9','10','11'], answer: 1 },
  ]}},
  { title: 'Tambah Mudah D1', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: '1+1', options: ['3','2','4','1'], answer: 1 },
    { problem: '2+1', options: ['4','3','5','2'], answer: 1 },
    { problem: '1+2', options: ['4','3','5','2'], answer: 1 },
    { problem: '2+2', options: ['6','4','5','3'], answer: 1 },
    { problem: '3+1', options: ['6','4','5','2'], answer: 1 },
    { problem: '2+3', options: ['7','5','6','4'], answer: 1 },
    { problem: '4+1', options: ['7','5','6','4'], answer: 1 },
    { problem: '3+2', options: ['6','5','4','7'], answer: 1 },
    { problem: '1+4', options: ['6','5','4','3'], answer: 1 },
    { problem: '4+2', options: ['7','6','8','5'], answer: 1 },
    { problem: '3+3', options: ['7','6','8','5'], answer: 1 },
    { problem: '5+1', options: ['7','6','8','4'], answer: 1 },
    { problem: '4+3', options: ['8','7','6','5'], answer: 1 },
    { problem: '2+5', options: ['8','7','6','4'], answer: 1 },
    { problem: '5+3', options: ['9','8','7','6'], answer: 0 },
    { problem: '4+4', options: ['9','8','7','6'], answer: 1 },
    { problem: '5+4', options: ['10','9','8','7'], answer: 1 },
    { problem: '5+5', options: ['11','10','9','8'], answer: 1 },
    { problem: '0+5', options: ['4','5','6'], answer: 1 },
    { problem: '3+0', options: ['2','3','4'], answer: 1 },
  ]}},
  { title: 'Bentuk Mudah D1', type: 'shape_sort', emoji: '🔵', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '⭕', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 0 },
    { image: '⬜', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 2 },
    { image: '▭', options: ['Segiempat Tepat','Segi Empat','Bujur'], answer: 0 },
    { image: '⭐', options: ['Bintang','Bulatan','Segi Tiga'], answer: 0 },
    { image: '🔶', options: ['Berlian','Heksagon','Segi Empat'], answer: 0 },
    { image: '🟡', options: ['Bulatan','Segi Empat','Bintang'], answer: 0 },
    { image: '🔷', options: ['Berlian','Bujur','Segi Tiga'], answer: 0 },
    { problem: 'Segi tiga ada berapa sisi?', options: ['2','3','4'], answer: 1 },
    { problem: 'Segi empat ada berapa sisi?', options: ['3','4','5'], answer: 1 },
    { problem: 'Bulatan ada berapa bucu?', options: ['0','1','2'], answer: 0 },
    { problem: 'Bentuk roda?', options: ['Segi Tiga','Bulatan','Segi Empat'], answer: 1 },
    { problem: 'Bentuk buku?', options: ['Bulatan','Segi Empat Tepat','Segi Tiga'], answer: 1 },
    { problem: 'Bentuk pizza?', options: ['Bulat','Segi Empat','Segi Tiga'], answer: 0 },
    { problem: 'Segi empat mempunyai berapa sudut?', options: ['2','3','4'], answer: 2 },
    { problem: 'Segi tiga mempunyai berapa sudut?', options: ['2','3','4'], answer: 1 },
    { image: '⬛', options: ['Bulatan','Segi Empat Hitam','Segi Tiga'], answer: 1 },
    { image: '🔴', options: ['Bulatan Merah','Segi Empat','Segi Tiga'], answer: 0 },
    { image: '🟢', options: ['Segi Empat','Bulatan Hijau','Segi Tiga'], answer: 1 },
    { problem: 'Pentagon ada berapa sisi?', options: ['4','5','6'], answer: 1 },
  ]}},
  // ===== DARJAH 2 EXPANDED =====
  { title: 'Tambah hingga 20 Lanjutan D2', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: '5+3', options: ['6','8','9','7'], answer: 1 },
    { problem: '7+4', options: ['9','11','12','10'], answer: 1 },
    { problem: '10+5', options: ['13','15','16','14'], answer: 1 },
    { problem: '6+7', options: ['11','13','14','12'], answer: 1 },
    { problem: '8+5', options: ['11','13','14','12'], answer: 1 },
    { problem: '9+6', options: ['13','15','16','14'], answer: 1 },
    { problem: '7+8', options: ['13','15','16','14'], answer: 1 },
    { problem: '11+4', options: ['13','15','16','14'], answer: 1 },
    { problem: '6+6', options: ['10','11','12'], answer: 2 },
    { problem: '7+7', options: ['12','13','14'], answer: 2 },
    { problem: '8+8', options: ['14','15','16'], answer: 2 },
    { problem: '9+9', options: ['16','17','18'], answer: 2 },
    { problem: '8+4', options: ['11','12','13'], answer: 1 },
    { problem: '9+3', options: ['11','12','13'], answer: 1 },
    { problem: '7+6', options: ['11','12','13'], answer: 2 },
    { problem: '10+8', options: ['16','17','18'], answer: 2 },
    { problem: '10+9', options: ['18','19','20'], answer: 1 },
    { problem: '9+7', options: ['15','16','17'], answer: 1 },
    { problem: '8+7', options: ['13','14','15'], answer: 2 },
    { problem: '6+8', options: ['12','13','14'], answer: 2 },
  ]}},
  { title: 'Tolak hingga 20 Lanjutan D2', type: 'math_puzzle', emoji: '➖', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: '10-3', options: ['5','7','8','6'], answer: 1 },
    { problem: '15-5', options: ['8','10','11','9'], answer: 1 },
    { problem: '20-8', options: ['10','12','13','11'], answer: 1 },
    { problem: '18-7', options: ['9','11','12','10'], answer: 1 },
    { problem: '16-4', options: ['10','12','13','11'], answer: 1 },
    { problem: '14-6', options: ['6','8','9','7'], answer: 1 },
    { problem: '19-9', options: ['8','10','11','9'], answer: 1 },
    { problem: '17-5', options: ['10','12','13','11'], answer: 1 },
    { problem: '20-5', options: ['13','15','17'], answer: 1 },
    { problem: '18-9', options: ['7','9','11'], answer: 1 },
    { problem: '16-8', options: ['7','8','9'], answer: 1 },
    { problem: '15-7', options: ['7','8','9'], answer: 1 },
    { problem: '14-7', options: ['6','7','8'], answer: 1 },
    { problem: '20-12', options: ['7','8','9'], answer: 1 },
    { problem: '19-4', options: ['13','15','17'], answer: 1 },
    { problem: '17-8', options: ['8','9','10'], answer: 1 },
    { problem: '20-7', options: ['11','12','13'], answer: 2 },
    { problem: '18-6', options: ['11','12','13'], answer: 1 },
    { problem: '15-6', options: ['8','9','10'], answer: 1 },
    { problem: '20-15', options: ['4','5','6'], answer: 1 },
  ]}},
  { title: 'Nombor 11-50 Lanjutan D2', type: 'number_match', emoji: '🔢', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: '11 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 0 },
    { problem: '12 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 1 },
    { problem: '15 biji epal', options: ['Empat Belas','Lima Belas','Enam Belas'], answer: 1 },
    { problem: '20 = ?', options: ['Sembilan Belas','Dua Puluh','Dua Puluh Satu'], answer: 1 },
    { problem: '30 = ?', options: ['Dua Puluh','Tiga Puluh','Empat Puluh'], answer: 1 },
    { problem: '40 = ?', options: ['Tiga Puluh','Empat Puluh','Lima Puluh'], answer: 1 },
    { problem: '50 = ?', options: ['Empat Puluh','Lima Puluh','Enam Puluh'], answer: 1 },
    { problem: '25 = ?', options: ['Dua Puluh','Dua Puluh Lima','Tiga Puluh'], answer: 1 },
    { problem: '13 = ?', options: ['Dua Belas','Tiga Belas','Empat Belas'], answer: 1 },
    { problem: '14 = ?', options: ['Tiga Belas','Empat Belas','Lima Belas'], answer: 1 },
    { problem: '16 = ?', options: ['Lima Belas','Enam Belas','Tujuh Belas'], answer: 1 },
    { problem: '17 = ?', options: ['Enam Belas','Tujuh Belas','Lapan Belas'], answer: 1 },
    { problem: '18 = ?', options: ['Tujuh Belas','Lapan Belas','Sembilan Belas'], answer: 1 },
    { problem: '19 = ?', options: ['Lapan Belas','Sembilan Belas','Dua Puluh'], answer: 1 },
    { problem: '21 = ?', options: ['Dua Puluh','Dua Puluh Satu','Dua Puluh Dua'], answer: 1 },
    { problem: '35 = ?', options: ['Tiga Puluh','Tiga Puluh Lima','Empat Puluh'], answer: 1 },
    { problem: '45 = ?', options: ['Empat Puluh','Empat Puluh Lima','Lima Puluh'], answer: 1 },
    { problem: 'Dua Puluh Lima = ?', options: ['24','25','26'], answer: 1 },
    { problem: 'Tiga Puluh = ?', options: ['29','30','31'], answer: 1 },
    { problem: 'Empat Puluh Lima = ?', options: ['44','45','46'], answer: 1 },
  ]}},
  // ===== DARJAH 3 EXPANDED =====
  { title: 'Darab 2 & 5 Lanjutan D3', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: '2×3', options: ['4','6','8','5'], answer: 1 },
    { problem: '2×5', options: ['8','10','12','9'], answer: 1 },
    { problem: '5×2', options: ['8','10','12','9'], answer: 1 },
    { problem: '5×3', options: ['13','15','17','14'], answer: 1 },
    { problem: '2×7', options: ['12','14','16','10'], answer: 1 },
    { problem: '5×4', options: ['18','20','22','16'], answer: 1 },
    { problem: '2×9', options: ['16','18','20','14'], answer: 1 },
    { problem: '5×6', options: ['28','30','32','26'], answer: 1 },
    { problem: '2×1', options: ['1','2','3'], answer: 1 },
    { problem: '5×1', options: ['4','5','6'], answer: 1 },
    { problem: '2×4', options: ['6','8','10'], answer: 1 },
    { problem: '2×6', options: ['10','12','14'], answer: 1 },
    { problem: '2×8', options: ['14','16','18'], answer: 1 },
    { problem: '2×10', options: ['18','20','22'], answer: 1 },
    { problem: '5×5', options: ['20','25','30'], answer: 1 },
    { problem: '5×7', options: ['32','35','38'], answer: 1 },
    { problem: '5×8', options: ['38','40','42'], answer: 1 },
    { problem: '5×9', options: ['42','45','48'], answer: 1 },
    { problem: '5×10', options: ['48','50','52'], answer: 1 },
    { problem: '2×2', options: ['2','4','6'], answer: 1 },
  ]}},
  { title: 'Bahagi Mudah Lanjutan D3', type: 'math_puzzle', emoji: '➗', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: '6÷2', options: ['2','3','4','5'], answer: 1 },
    { problem: '10÷2', options: ['4','5','6','7'], answer: 1 },
    { problem: '9÷3', options: ['2','3','4','5'], answer: 1 },
    { problem: '15÷5', options: ['2','3','4','5'], answer: 1 },
    { problem: '12÷4', options: ['2','3','4','5'], answer: 1 },
    { problem: '20÷5', options: ['3','4','5','6'], answer: 1 },
    { problem: '16÷2', options: ['7','8','9','10'], answer: 1 },
    { problem: '25÷5', options: ['4','5','6','7'], answer: 1 },
    { problem: '4÷2', options: ['1','2','3'], answer: 1 },
    { problem: '6÷3', options: ['1','2','3'], answer: 2 },
    { problem: '8÷2', options: ['3','4','5'], answer: 1 },
    { problem: '8÷4', options: ['1','2','3'], answer: 1 },
    { problem: '10÷5', options: ['1','2','3'], answer: 1 },
    { problem: '12÷3', options: ['3','4','5'], answer: 1 },
    { problem: '14÷2', options: ['6','7','8'], answer: 1 },
    { problem: '18÷2', options: ['8','9','10'], answer: 1 },
    { problem: '18÷3', options: ['5','6','7'], answer: 1 },
    { problem: '20÷4', options: ['4','5','6'], answer: 1 },
    { problem: '15÷3', options: ['4','5','6'], answer: 1 },
    { problem: '12÷6', options: ['1','2','3'], answer: 1 },
  ]}},
  { title: 'Pecahan Mudah Lanjutan D3', type: 'multiple_choice', emoji: '🍕', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: '1/2 bermaksud?', options: ['Satu dari tiga','Satu dari dua','Dua dari satu'], answer: 1 },
    { problem: '1/4 pizza — berapa bahagian?', options: ['Satu dari empat','Empat dari satu','Dua dari empat'], answer: 0 },
    { problem: '1/2 + 1/2 = ?', options: ['1/4','1','2'], answer: 1 },
    { problem: 'Pecahan manakah lebih besar?', options: ['1/4','1/2','Sama'], answer: 1 },
    { problem: '3/4 bermaksud berapa bahagian?', options: ['Tiga dari empat','Empat dari tiga','Tiga sahaja'], answer: 0 },
    { problem: 'Pizza dibahagi 4, ambil 2. Berapa pecahan?', options: ['1/4','2/4','3/4'], answer: 1 },
    { problem: 'Manakah bersamaan dengan 1/2?', options: ['2/4','1/3','3/4'], answer: 0 },
    { problem: '1/3 + 1/3 = ?', options: ['1/3','2/3','3/3'], answer: 1 },
    { problem: '1/4 + 1/4 = ?', options: ['1/4','1/2','3/4'], answer: 1 },
    { problem: 'Separuh dari 10 = ?', options: ['3','5','7'], answer: 1 },
    { problem: 'Satu perempat dari 20 = ?', options: ['3','5','7'], answer: 1 },
    { problem: 'Mana lebih kecil: 1/3 atau 1/2?', options: ['1/3','1/2','Sama'], answer: 0 },
    { problem: '2/4 = ?', options: ['1/4','1/2','3/4'], answer: 1 },
    { problem: '4/4 = ?', options: ['Separuh','Satu','Satu setengah'], answer: 1 },
    { problem: 'Separuh dari 8 = ?', options: ['3','4','5'], answer: 1 },
    { problem: '1/2 + 1/4 = ?', options: ['1/4','1/2','3/4'], answer: 2 },
    { problem: 'Satu penuh = berapa perempat?', options: ['2','3','4'], answer: 2 },
    { problem: 'Mana lebih besar: 2/4 atau 3/4?', options: ['2/4','3/4','Sama'], answer: 1 },
    { problem: 'Separuh dari 12 = ?', options: ['5','6','7'], answer: 1 },
    { problem: '1/3 bermaksud?', options: ['Separuh','Satu pertiga','Satu perempat'], answer: 1 },
  ]}},
  // ===== DARJAH 4 EXPANDED =====
  { title: 'Darab 3,4,6 Lanjutan D4', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: '3×4', options: ['10','12','14','11'], answer: 1 },
    { problem: '4×4', options: ['14','16','18','15'], answer: 1 },
    { problem: '6×3', options: ['16','18','20','15'], answer: 1 },
    { problem: '3×7', options: ['19','21','23','18'], answer: 1 },
    { problem: '4×6', options: ['22','24','26','20'], answer: 1 },
    { problem: '6×5', options: ['28','30','32','26'], answer: 1 },
    { problem: '3×9', options: ['25','27','29','24'], answer: 1 },
    { problem: '4×8', options: ['30','32','34','28'], answer: 1 },
    { problem: '3×3', options: ['6','9','12'], answer: 1 },
    { problem: '3×5', options: ['13','15','17'], answer: 1 },
    { problem: '3×6', options: ['16','18','20'], answer: 1 },
    { problem: '3×8', options: ['22','24','26'], answer: 1 },
    { problem: '3×10', options: ['28','30','32'], answer: 1 },
    { problem: '4×3', options: ['10','12','14'], answer: 1 },
    { problem: '4×5', options: ['18','20','22'], answer: 1 },
    { problem: '4×7', options: ['26','28','30'], answer: 1 },
    { problem: '4×9', options: ['34','36','38'], answer: 1 },
    { problem: '4×10', options: ['38','40','42'], answer: 1 },
    { problem: '6×4', options: ['22','24','26'], answer: 1 },
    { problem: '6×6', options: ['34','36','38'], answer: 1 },
  ]}},
  { title: 'Wang Malaysia Lanjutan D4', type: 'counting', emoji: '💰', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: '💵💵💵 — berapa ringgit?', options: ['RM 2','RM 3','RM 4'], answer: 1 },
    { problem: '🪙🪙🪙🪙🪙 (10sen each) — berapa?', options: ['40 sen','50 sen','60 sen'], answer: 1 },
    { problem: '💵💵💵💵💵 — berapa ringgit?', options: ['RM 4','RM 5','RM 6'], answer: 1 },
    { problem: 'Beli RM 5. Bayar RM 10. Baki?', options: ['RM 3','RM 5','RM 7'], answer: 1 },
    { problem: 'Beli roti RM 2.50. Bayar RM 5. Baki?', options: ['RM 2','RM 2.50','RM 3'], answer: 1 },
    { problem: '3 buku × RM 2 = ?', options: ['RM 4','RM 6','RM 8'], answer: 1 },
    { problem: 'RM 10 - RM 3.50 = ?', options: ['RM 5.50','RM 6.50','RM 7.50'], answer: 1 },
    { problem: '2 pen × RM 1.50 = ?', options: ['RM 2.50','RM 3.00','RM 3.50'], answer: 1 },
    { problem: 'RM 1 = berapa sen?', options: ['10','100','1000'], answer: 1 },
    { problem: 'RM 5 + RM 3 = ?', options: ['RM 7','RM 8','RM 9'], answer: 1 },
    { problem: 'RM 10 - RM 7 = ?', options: ['RM 2','RM 3','RM 4'], answer: 1 },
    { problem: '5 × RM 2 = ?', options: ['RM 8','RM 10','RM 12'], answer: 1 },
    { problem: '50 sen + 50 sen = ?', options: ['RM 0.75','RM 1.00','RM 1.50'], answer: 1 },
    { problem: 'Beli makan RM 3.50, bayar RM 10. Baki?', options: ['RM 5.50','RM 6.50','RM 7.50'], answer: 1 },
    { problem: 'Nota RM 50 = berapa nota RM 10?', options: ['3','4','5'], answer: 2 },
    { problem: 'RM 20 - RM 8 = ?', options: ['RM 10','RM 12','RM 14'], answer: 1 },
    { problem: 'RM 2.50 + RM 2.50 = ?', options: ['RM 4','RM 5','RM 6'], answer: 1 },
    { problem: 'Beli 4 ayam RM 3 setiap satu. Bayar berapa?', options: ['RM 10','RM 12','RM 14'], answer: 1 },
    { problem: 'RM 100 - RM 65 = ?', options: ['RM 30','RM 35','RM 40'], answer: 1 },
    { problem: 'Beli buku RM 8.90, bayar RM 10. Baki?', options: ['RM 0.90','RM 1.10','RM 1.20'], answer: 2 },
  ]}},
  { title: 'Masa dan Waktu Lanjutan D4', type: 'multiple_choice', emoji: '⏰', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: '1 jam = berapa minit?', options: ['30 minit','60 minit','100 minit'], answer: 1 },
    { problem: '1 minit = berapa saat?', options: ['60 saat','30 saat','100 saat'], answer: 0 },
    { problem: '1 hari = berapa jam?', options: ['12 jam','24 jam','48 jam'], answer: 1 },
    { problem: '1 minggu = berapa hari?', options: ['5 hari','6 hari','7 hari'], answer: 2 },
    { problem: '1 bulan = lebih kurang berapa hari?', options: ['20 hari','30 hari','40 hari'], answer: 1 },
    { problem: '1 tahun = berapa bulan?', options: ['10 bulan','12 bulan','14 bulan'], answer: 1 },
    { problem: 'Setengah jam = berapa minit?', options: ['20 minit','30 minit','45 minit'], answer: 1 },
    { problem: 'Pukul 8:30 + 30 minit = ?', options: ['8:00','9:00','9:30'], answer: 1 },
    { problem: '2 jam = berapa minit?', options: ['90','120','150'], answer: 1 },
    { problem: '1 tahun = berapa hari?', options: ['360','365','370'], answer: 1 },
    { problem: 'Suku jam = berapa minit?', options: ['10','15','20'], answer: 1 },
    { problem: 'Pukul 3 petang + 2 jam = ?', options: ['Pukul 4','Pukul 5','Pukul 6'], answer: 1 },
    { problem: '2 minggu = berapa hari?', options: ['12','13','14'], answer: 2 },
    { problem: '3 jam = berapa minit?', options: ['150','180','210'], answer: 1 },
    { problem: 'Pukul 7:45 + 15 minit = ?', options: ['7:55','8:00','8:15'], answer: 1 },
    { problem: 'Dari pukul 6 pagi hingga pukul 2 petang = berapa jam?', options: ['6','7','8'], answer: 2 },
    { problem: '1 jam 30 minit = berapa minit?', options: ['80','90','100'], answer: 1 },
    { problem: 'Pukul 11:00 malam + 2 jam = ?', options: ['1 pagi','12 malam','2 pagi'], answer: 0 },
    { problem: '1 hari = berapa minit?', options: ['1000','1440','2400'], answer: 1 },
    { problem: '1 bulan ada berapa minggu kira-kira?', options: ['2','3','4'], answer: 2 },
  ]}},
  // ===== DARJAH 5 EXPANDED =====
  { title: 'Darab 7,8,9 Lanjutan D5', type: 'math_puzzle', emoji: '✖️', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '7×4', options: ['26','28','30','24'], answer: 1 },
    { problem: '8×3', options: ['22','24','26','20'], answer: 1 },
    { problem: '9×2', options: ['16','18','20','14'], answer: 1 },
    { problem: '7×7', options: ['47','49','51','45'], answer: 1 },
    { problem: '8×8', options: ['62','64','66','60'], answer: 1 },
    { problem: '9×9', options: ['79','81','83','77'], answer: 1 },
    { problem: '7×9', options: ['61','63','65','59'], answer: 1 },
    { problem: '8×6', options: ['46','48','50','44'], answer: 1 },
    { problem: '7×1', options: ['6','7','8'], answer: 1 },
    { problem: '8×1', options: ['7','8','9'], answer: 1 },
    { problem: '9×1', options: ['8','9','10'], answer: 1 },
    { problem: '7×2', options: ['12','14','16'], answer: 1 },
    { problem: '8×2', options: ['14','16','18'], answer: 1 },
    { problem: '9×3', options: ['25','27','29'], answer: 1 },
    { problem: '7×5', options: ['33','35','37'], answer: 1 },
    { problem: '8×4', options: ['30','32','34'], answer: 1 },
    { problem: '9×4', options: ['34','36','38'], answer: 1 },
    { problem: '7×6', options: ['40','42','44'], answer: 1 },
    { problem: '8×7', options: ['54','56','58'], answer: 1 },
    { problem: '9×8', options: ['70','72','74'], answer: 1 },
  ]}},
  { title: 'Nombor 2 Digit Tambah & Tolak D5', type: 'math_puzzle', emoji: '➕', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '23+45', options: ['66','68','70','64'], answer: 1 },
    { problem: '36+27', options: ['61','63','65','59'], answer: 1 },
    { problem: '54+38', options: ['90','92','94','88'], answer: 1 },
    { problem: '50-23', options: ['25','27','29','23'], answer: 1 },
    { problem: '68-34', options: ['32','34','36','30'], answer: 1 },
    { problem: '75-48', options: ['25','27','29','23'], answer: 1 },
    { problem: '83-26', options: ['55','57','59','53'], answer: 1 },
    { problem: '90-55', options: ['33','35','37','31'], answer: 1 },
    { problem: '47+36', options: ['81','83','85'], answer: 1 },
    { problem: '64+29', options: ['91','93','95'], answer: 1 },
    { problem: '85-37', options: ['46','48','50'], answer: 1 },
    { problem: '72-45', options: ['25','27','29'], answer: 1 },
    { problem: '56+44', options: ['98','100','102'], answer: 1 },
    { problem: '99-48', options: ['49','51','53'], answer: 1 },
    { problem: '77+15', options: ['90','92','94'], answer: 1 },
    { problem: '100-37', options: ['61','63','65'], answer: 1 },
    { problem: '45+58', options: ['101','103','105'], answer: 1 },
    { problem: '91-28', options: ['61','63','65'], answer: 1 },
    { problem: '67+24', options: ['89','91','93'], answer: 1 },
    { problem: '84-16', options: ['66','68','70'], answer: 1 },
  ]}},
  { title: 'Perpuluhan Lanjutan D5', type: 'math_puzzle', emoji: '🔢', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '0.5 + 0.3 = ?', options: ['0.7','0.8','0.9'], answer: 1 },
    { problem: '1.2 + 0.8 = ?', options: ['1.8','2.0','2.2'], answer: 1 },
    { problem: '2.5 - 1.2 = ?', options: ['1.1','1.3','1.5'], answer: 1 },
    { problem: '0.75 + 0.25 = ?', options: ['0.90','1.00','1.10'], answer: 1 },
    { problem: '3.0 - 1.5 = ?', options: ['1.0','1.5','2.0'], answer: 1 },
    { problem: '0.4 × 2 = ?', options: ['0.6','0.8','1.0'], answer: 1 },
    { problem: '1.6 ÷ 2 = ?', options: ['0.6','0.8','1.0'], answer: 1 },
    { problem: '2.5 × 4 = ?', options: ['8','10','12'], answer: 1 },
    { problem: '0.1 + 0.9 = ?', options: ['0.9','1.0','1.1'], answer: 1 },
    { problem: '3.5 - 1.5 = ?', options: ['1.5','2.0','2.5'], answer: 1 },
    { problem: '4.8 + 1.2 = ?', options: ['5.8','6.0','6.2'], answer: 1 },
    { problem: '5.0 - 2.5 = ?', options: ['2.0','2.5','3.0'], answer: 1 },
    { problem: '0.3 × 3 = ?', options: ['0.6','0.9','1.2'], answer: 1 },
    { problem: '2.0 ÷ 4 = ?', options: ['0.3','0.5','0.7'], answer: 1 },
    { problem: '6.4 + 0.6 = ?', options: ['6.8','7.0','7.2'], answer: 1 },
    { problem: '0.7 + 0.8 = ?', options: ['1.3','1.5','1.7'], answer: 1 },
    { problem: '9.5 - 4.5 = ?', options: ['4.5','5.0','5.5'], answer: 1 },
    { problem: '1.5 × 2 = ?', options: ['2.5','3.0','3.5'], answer: 1 },
    { problem: '7.2 ÷ 2 = ?', options: ['3.2','3.6','4.0'], answer: 1 },
    { problem: '4.4 + 3.6 = ?', options: ['7.8','8.0','8.2'], answer: 1 },
  ]}},
  { title: 'Pecahan Tak Wajar & Nombor Bercampur D5', type: 'math_puzzle', emoji: '🍕', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '7/4 sebagai nombor bercampur?', options: ['1¾','2¼','1½'], answer: 0 },
    { problem: '2½ sebagai pecahan tak wajar?', options: ['3/2','5/2','4/2'], answer: 1 },
    { problem: '1¾ + 2¼ = ?', options: ['3','4','3½'], answer: 1 },
    { problem: '3½ - 1¼ = ?', options: ['2¼','2½','2¾'], answer: 0 },
    { problem: '9/4 sebagai nombor bercampur?', options: ['2¼','2½','2¾'], answer: 0 },
    { problem: '3¾ sebagai pecahan tak wajar?', options: ['13/4','15/4','11/4'], answer: 0 },
    { problem: '2⅓ + 1⅔ = ?', options: ['3','4','3⅓'], answer: 1 },
    { problem: '5/3 sebagai nombor bercampur?', options: ['1⅓','1⅔','2⅓'], answer: 1 },
    { problem: '11/4 sebagai nombor bercampur?', options: ['2½','2¾','3¼'], answer: 1 },
    { problem: '1½ sebagai pecahan tak wajar?', options: ['2/2','3/2','4/2'], answer: 1 },
    { problem: '3¼ sebagai pecahan tak wajar?', options: ['11/4','13/4','15/4'], answer: 0 },
    { problem: '2¾ sebagai pecahan tak wajar?', options: ['9/4','11/4','13/4'], answer: 1 },
    { problem: '4⅓ - 1⅓ = ?', options: ['2⅓','3','3⅓'], answer: 2 },
    { problem: '5½ - 2¼ = ?', options: ['3¼','3½','2¾'], answer: 0 },
    { problem: '1⅔ + 2⅓ = ?', options: ['3','4','3⅔'], answer: 2 },
    { problem: '7/2 sebagai nombor bercampur?', options: ['3','3½','4'], answer: 1 },
    { problem: '4½ sebagai pecahan tak wajar?', options: ['7/2','9/2','11/2'], answer: 1 },
    { problem: '6/4 dalam bentuk terendah?', options: ['1/2','3/2','2/3'], answer: 1 },
    { problem: '8/3 sebagai nombor bercampur?', options: ['2⅓','2⅔','3⅓'], answer: 1 },
    { problem: '2⅕ sebagai pecahan tak wajar?', options: ['10/5','11/5','12/5'], answer: 1 },
  ]}},
  { title: 'Nisbah dan Kadar D5', type: 'math_puzzle', emoji: '📊', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Nisbah 2:4 dalam bentuk paling mudah?', options: ['1:2','2:4','1:3'], answer: 0 },
    { problem: 'Nisbah merah:biru = 3:5. Ada 8 bola, berapa merah?', options: ['2','3','5'], answer: 1 },
    { problem: '6:9 = 2:?', options: ['2','3','4'], answer: 1 },
    { problem: 'Harga 3 buku = RM15. Harga 1 buku?', options: ['RM3','RM5','RM6'], answer: 1 },
    { problem: '5 pen = RM10. 8 pen = ?', options: ['RM14','RM16','RM20'], answer: 1 },
    { problem: 'Nisbah pelajar lelaki:perempuan = 2:3. 20 lelaki, berapa perempuan?', options: ['25','30','15'], answer: 1 },
    { problem: '10:15 = ?:3', options: ['1','2','4'], answer: 1 },
    { problem: 'Harga 4 epal = RM8. Harga 6 epal?', options: ['RM10','RM12','RM14'], answer: 1 },
    { problem: 'Nisbah 4:8 dipermudah = ?', options: ['1:2','2:4','4:8'], answer: 0 },
    { problem: 'Kadar: 60 km/jam × 2 jam = ?', options: ['100 km','120 km','140 km'], answer: 1 },
    { problem: 'Nisbah 6:10 dipermudah = ?', options: ['2:5','3:5','4:5'], answer: 1 },
    { problem: '3 pens cost RM9. Cost of 7 pens?', options: ['RM19','RM21','RM23'], answer: 1 },
    { problem: 'Nisbah 15:25 dipermudah = ?', options: ['2:4','3:5','4:6'], answer: 1 },
    { problem: '12 buku = RM60. Harga 5 buku?', options: ['RM20','RM25','RM30'], answer: 1 },
    { problem: 'Nisbah 9:12 dipermudah = ?', options: ['3:4','2:3','1:2'], answer: 0 },
    { problem: '100 km dalam 2 jam. Kelajuan = ?', options: ['40 km/j','50 km/j','60 km/j'], answer: 1 },
    { problem: 'Nisbah 1:3. Ada 12 bola. Berapa bahagian 1?', options: ['2','3','4'], answer: 1 },
    { problem: 'Kadar: 200 km ÷ 4 jam = ?', options: ['40 km/j','50 km/j','60 km/j'], answer: 1 },
    { problem: 'RM30 untuk 6 orang. Setiap orang bayar?', options: ['RM4','RM5','RM6'], answer: 1 },
    { problem: '5 orang bayar RM25. 8 orang bayar?', options: ['RM35','RM40','RM45'], answer: 1 },
  ]}},
  // ===== DARJAH 6 EXPANDED =====
  { title: 'Perimeter dan Luas Lanjutan D6', type: 'multiple_choice', emoji: '📐', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Perimeter segi empat 4cm × 4cm?', options: ['12cm','16cm','8cm'], answer: 1 },
    { problem: 'Luas segi empat 5cm × 3cm?', options: ['8cm²','15cm²','16cm²'], answer: 1 },
    { problem: 'Perimeter segi empat tepat 6cm × 4cm?', options: ['20cm','24cm','10cm'], answer: 0 },
    { problem: 'Luas segi empat 4cm × 4cm?', options: ['8cm²','16cm²','20cm²'], answer: 1 },
    { problem: 'Segi tiga 3cm, 4cm, 5cm. Perimeter?', options: ['10cm','12cm','14cm'], answer: 1 },
    { problem: 'Luas segi empat 7cm × 2cm?', options: ['9cm²','14cm²','18cm²'], answer: 1 },
    { problem: 'Perimeter = ?', options: ['Panjang × Lebar','Jumlah semua sisi','Panjang + Lebar'], answer: 1 },
    { problem: 'Luas = ?', options: ['Jumlah semua sisi','Panjang × Lebar','Panjang + Lebar'], answer: 1 },
    { problem: 'Luas segi tiga tapak=6cm, tinggi=4cm?', options: ['10cm²','12cm²','24cm²'], answer: 1 },
    { problem: 'Isipadu kiub sisi 3cm?', options: ['9cm³','27cm³','18cm³'], answer: 1 },
    { problem: 'Isipadu kuboid 4×3×2?', options: ['20cm³','24cm³','28cm³'], answer: 1 },
    { problem: 'Perimeter segi empat sama sisi 5cm?', options: ['15cm','20cm','25cm'], answer: 1 },
    { problem: 'Luas segi empat tepat 10cm × 4cm?', options: ['28cm²','40cm²','44cm²'], answer: 1 },
    { problem: 'Perimeter segi empat tepat 8cm × 3cm?', options: ['22cm','24cm','26cm'], answer: 0 },
    { problem: 'Luas segi empat sama 6cm × 6cm?', options: ['24cm²','36cm²','12cm²'], answer: 1 },
    { problem: 'Isipadu kiub sisi 5cm?', options: ['25cm³','100cm³','125cm³'], answer: 2 },
    { problem: 'Perimeter segitiga sama kaki 4,4,3?', options: ['10cm','11cm','12cm'], answer: 1 },
    { problem: 'Luas segi tiga tapak=10, tinggi=6?', options: ['28cm²','30cm²','60cm²'], answer: 1 },
    { problem: 'Isipadu kuboid 5×4×3?', options: ['55cm³','60cm³','65cm³'], answer: 1 },
    { problem: 'Perimeter segi enam sama sisi 4cm?', options: ['20cm','24cm','28cm'], answer: 1 },
  ]}},
  { title: 'Statistik Graf & Data Lanjutan D6', type: 'multiple_choice', emoji: '📊', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Graf palang digunakan untuk?', options: ['Tunjukkan arah','Bandingkan data','Ukur sudut'], answer: 1 },
    { problem: 'Paksi x pada graf palang ialah?', options: ['Nilai','Kategori','Nombor'], answer: 1 },
    { problem: 'Paksi y pada graf palang ialah?', options: ['Nilai/Kekerapan','Kategori','Nama'], answer: 0 },
    { problem: '5 murid suka epal, 8 suka oren. Lebih berapa?', options: ['2','3','4'], answer: 1 },
    { problem: 'Jumlah 3 + 5 + 7 + 2 = ?', options: ['15','17','19'], answer: 1 },
    { problem: 'Nilai terbesar dari: 12, 8, 15, 10?', options: ['12','8','15'], answer: 2 },
    { problem: 'Nilai terkecil dari: 12, 8, 15, 10?', options: ['12','8','15'], answer: 1 },
    { problem: 'Min (purata) dari 2, 4, 6 ialah?', options: ['3','4','5'], answer: 1 },
    { problem: 'Mod ialah?', options: ['Nilai tengah','Nilai paling kerap','Nilai terbesar'], answer: 1 },
    { problem: 'Median ialah?', options: ['Nilai tengah data tersusun','Nilai terbesar','Nilai paling kerap'], answer: 0 },
    { problem: 'Min = jumlah data ÷ ?', options: ['nilai terbesar','bilangan data','nilai tengah'], answer: 1 },
    { problem: 'Data: 2,3,3,5,7. Modnya?', options: ['2','3','5'], answer: 1 },
    { problem: 'Data: 1,2,3,4,5. Min = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Julat = nilai terbesar ___ nilai terkecil?', options: ['+ ','-','×'], answer: 1 },
    { problem: 'Data: 4,6,8,10,12. Median = ?', options: ['7','8','9'], answer: 1 },
    { problem: 'Graf yang tunjuk perubahan masa ialah?', options: ['Carta Pai','Graf Garis','Carta Bar'], answer: 1 },
    { problem: 'Carta pai tunjuk?', options: ['Perubahan masa','Perbandingan bahagian dari keseluruhan','Frekuensi'], answer: 1 },
    { problem: 'Data: 1,1,2,3,3,3. Mod = ?', options: ['1','2','3'], answer: 2 },
    { problem: '15 murid, min ujian = 80. Jumlah markah = ?', options: ['1100','1200','1300'], answer: 1 },
    { problem: 'Cara susun data secara menaik = ?', options: ['Besar ke kecil','Kecil ke besar','Rawak'], answer: 1 },
  ]}},
  { title: 'Pecahan & Peratus Lanjutan D6', type: 'math_puzzle', emoji: '🍕', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: '1/4 + 2/4 = ?', options: ['1/4','3/4','4/4'], answer: 1 },
    { problem: '3/5 - 1/5 = ?', options: ['1/5','2/5','3/5'], answer: 1 },
    { problem: 'Tukar 3/4 ke perpuluhan?', options: ['0.25','0.50','0.75'], answer: 2 },
    { problem: 'Tukar 1/2 ke peratus?', options: ['25%','50%','75%'], answer: 1 },
    { problem: '1/4 dalam peratus?', options: ['10%','25%','50%'], answer: 1 },
    { problem: '3/4 dalam peratus?', options: ['50%','75%','80%'], answer: 1 },
    { problem: '50% daripada 80 = ?', options: ['30','40','50'], answer: 1 },
    { problem: '25% daripada 100 = ?', options: ['20','25','30'], answer: 1 },
    { problem: '75% daripada 200 = ?', options: ['100','150','175'], answer: 1 },
    { problem: '10% daripada 500 = ?', options: ['40','50','60'], answer: 1 },
    { problem: '1/5 dalam peratus?', options: ['15%','20%','25%'], answer: 1 },
    { problem: '2/5 dalam peratus?', options: ['35%','40%','45%'], answer: 1 },
    { problem: '1/10 dalam peratus?', options: ['5%','10%','15%'], answer: 1 },
    { problem: '30% daripada 60 = ?', options: ['15','18','20'], answer: 1 },
    { problem: 'RM200, diskaun 15%. Harga akhir?', options: ['RM160','RM170','RM180'], answer: 1 },
    { problem: '0.3 dalam peratus?', options: ['20%','30%','40%'], answer: 1 },
    { problem: '0.25 sebagai pecahan?', options: ['1/4','1/2','3/4'], answer: 0 },
    { problem: '0.75 sebagai pecahan?', options: ['1/2','3/4','1/3'], answer: 1 },
    { problem: '40% daripada 150 = ?', options: ['55','60','65'], answer: 1 },
    { problem: '20% daripada 75 = ?', options: ['13','15','17'], answer: 1 },
  ]}},
  { title: 'Nombor Negatif Lanjutan D6', type: 'math_puzzle', emoji: '➖', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: '-3 + 5 = ?', options: ['1','2','3'], answer: 1 },
    { problem: '-4 + (-2) = ?', options: ['-5','-6','-7'], answer: 1 },
    { problem: '7 - 10 = ?', options: ['-2','-3','-4'], answer: 1 },
    { problem: '-5 × 2 = ?', options: ['-8','-10','-12'], answer: 1 },
    { problem: '-6 ÷ 2 = ?', options: ['-2','-3','-4'], answer: 1 },
    { problem: 'Mana lebih besar: -3 atau -7?', options: ['-7','-3','Sama'], answer: 1 },
    { problem: '-2 + 2 = ?', options: ['-1','0','1'], answer: 1 },
    { problem: '(-4) × (-3) = ?', options: ['10','12','14'], answer: 1 },
    { problem: '-8 + 3 = ?', options: ['-6','-5','-4'], answer: 1 },
    { problem: '5 + (-8) = ?', options: ['-2','-3','-4'], answer: 1 },
    { problem: '-10 + 4 = ?', options: ['-7','-6','-5'], answer: 1 },
    { problem: '(-6) × (-2) = ?', options: ['10','12','14'], answer: 1 },
    { problem: '-15 ÷ 3 = ?', options: ['-3','-5','-7'], answer: 1 },
    { problem: '-4 - 3 = ?', options: ['-5','-7','-9'], answer: 1 },
    { problem: '0 - 7 = ?', options: ['-5','-7','-9'], answer: 1 },
    { problem: '-9 × 2 = ?', options: ['-16','-18','-20'], answer: 1 },
    { problem: '-12 ÷ (-4) = ?', options: ['2','3','4'], answer: 1 },
    { problem: '-3 × (-5) = ?', options: ['12','15','18'], answer: 1 },
    { problem: '(-7) + (-8) = ?', options: ['-13','-15','-17'], answer: 1 },
    { problem: '10 - (-5) = ?', options: ['13','15','17'], answer: 1 },
  ]}},
  { title: 'Algebra Asas Lanjutan D6', type: 'math_puzzle', emoji: '🔢', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'x + 5 = 9, x = ?', options: ['3','4','5'], answer: 1 },
    { problem: '2x = 10, x = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'x - 3 = 7, x = ?', options: ['9','10','11'], answer: 1 },
    { problem: '3x + 2 = 11, x = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'x/4 = 3, x = ?', options: ['10','12','14'], answer: 1 },
    { problem: '2x - 4 = 8, x = ?', options: ['5','6','7'], answer: 1 },
    { problem: 'Nilai 3x jika x = 4?', options: ['10','12','14'], answer: 1 },
    { problem: 'Nilai x² jika x = 5?', options: ['20','25','30'], answer: 1 },
    { problem: '4x = 20, x = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'x + 8 = 15, x = ?', options: ['5','6','7'], answer: 2 },
    { problem: '5x - 5 = 20, x = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Nilai 2x + 3 jika x = 5?', options: ['11','13','15'], answer: 1 },
    { problem: 'x/3 + 1 = 4, x = ?', options: ['7','9','11'], answer: 1 },
    { problem: '3(x + 2) = 15, x = ?', options: ['3','4','5'], answer: 0 },
    { problem: 'Nilai x³ jika x = 2?', options: ['6','8','10'], answer: 1 },
    { problem: '2x + x = 12, x = ?', options: ['3','4','5'], answer: 1 },
    { problem: 'Jika a = 3, b = 4. a + b = ?', options: ['5','6','7'], answer: 2 },
    { problem: 'Jika p = 5, q = 2. p × q = ?', options: ['8','10','12'], answer: 1 },
    { problem: '7x = 49, x = ?', options: ['6','7','8'], answer: 1 },
    { problem: 'Nilai 4x - 1 jika x = 3?', options: ['10','11','12'], answer: 1 },
  ]}},
];