export const sekolah_bahasa_melayu = [
  { title: 'Huruf G-N', type: 'letter_match', emoji: '🔤', difficulty: 'medium', gameData: { questions: [
    { letter: 'G', emoji: '🍇', word: 'Anggur', options: ['G','H','I','J'], answer: 0 },
    { letter: 'H', emoji: '🏠', word: 'Rumah', options: ['G','H','I','J'], answer: 1 },
    { letter: 'I', emoji: '🍦', word: 'Ais Krim', options: ['G','H','I','J'], answer: 2 },
    { letter: 'J', emoji: '🌉', word: 'Jambatan', options: ['G','H','I','J'], answer: 3 },
    { letter: 'K', emoji: '🐴', word: 'Kuda', options: ['J','K','L','M'], answer: 1 },
    { letter: 'L', emoji: '🌊', word: 'Laut', options: ['J','K','L','M'], answer: 2 },
    { letter: 'M', emoji: '🌙', word: 'Bulan', options: ['J','K','L','M'], answer: 3 },
    { letter: 'N', emoji: '🌰', word: 'Nangka', options: ['M','N','O','P'], answer: 1 },
  ]}},
  { title: 'Ayat Senang - Baca', type: 'reading', emoji: '📖', difficulty: 'medium', gameData: { questions: [
    { problem: 'Saya suka bermain.', options: ['Bermain','Tidur','Makan'], answer: 0 },
    { problem: 'Kucing itu comel.', options: ['Comel','Besar','Kecil'], answer: 0 },
    { problem: 'Mak memasak nasi.', options: ['Nasi','Roti','Mee'], answer: 0 },
    { problem: 'Ayah memperbaiki kereta.', options: ['Kereta','Basikal','Bas'], answer: 0 },
    { problem: 'Adik bermain bola.', options: ['Bola','Wayang','Boneka'], answer: 0 },
    { problem: 'Sekolah ditutup hari ini.', options: ['Hari ini','Esok','Seminggu'], answer: 0 },
    { problem: 'Kami bermain di taman.', options: ['Taman','Rumah','Sekolah'], answer: 0 },
    { problem: 'Adik minum susu panas.', options: ['Susu','Air','Jus'], answer: 0 },
  ]}},
  { title: 'Kata-Kata Hari-Hari', type: 'word_builder', emoji: '🔠', difficulty: 'medium', gameData: { questions: [
    { problem: 'r-m-h', options: ['rumah','rokok','rimau'], answer: 0 },
    { problem: 's-k-l-h', options: ['sekolah','sakat','sakti'], answer: 0 },
    { problem: 'k-l-r-g-', options: ['keluarga','kemarau','kelapa'], answer: 0 },
    { problem: 'm-k-n-n', options: ['makanan','martabak','meriam'], answer: 0 },
    { problem: 'm-i-n-n', options: ['mainan','manisan','mesin'], answer: 0 },
    { problem: 'k-p-l', options: ['kapal','kapel','kopel'], answer: 0 },
    { problem: 'b-k-', options: ['buku','baka','boke'], answer: 0 },
    { problem: 'p-n-s-l', options: ['pensil','pental','pinta'], answer: 0 },
  ]}},
  { title: 'Tatabahasa - Kata Nama', type: 'multiple_choice', emoji: '📝', difficulty: 'medium', gameData: { questions: [
    { problem: 'Manakah kata nama?', options: ['berlari','buku','cantik'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['meja','tidur','merah'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['melompat','sekolah','besar'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['hijau','menangis','bunga'], answer: 2 },
    { problem: 'Manakah kata nama?', options: ['pokok','berlari','kuat'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['kecil','minum','kereta'], answer: 2 },
    { problem: 'Manakah kata nama?', options: ['terbang','burung','tinggi'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['sungai','berenang','sejuk'], answer: 0 },
  ]}},
  { title: 'Tatabahasa - Kata Kerja', type: 'multiple_choice', emoji: '⚡', difficulty: 'medium', gameData: { questions: [
    { problem: 'Manakah kata kerja?', options: ['berlari','buku','cantik'], answer: 0 },
    { problem: 'Manakah kata kerja?', options: ['meja','tidur','merah'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['melompat','sekolah','besar'], answer: 0 },
    { problem: 'Manakah kata kerja?', options: ['hijau','menangis','bunga'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['pokok','berlari','kuat'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['kecil','minum','kereta'], answer: 1 },
    { problem: 'Manakah kata kerja?', options: ['terbang','burung','tinggi'], answer: 0 },
    { problem: 'Manakah kata kerja?', options: ['sungai','berenang','sejuk'], answer: 1 },
  ]}},
  { title: 'Ejaan Betul', type: 'spelling', emoji: '🔡', difficulty: 'medium', gameData: { questions: [
    { problem: 'Ejaan betul untuk "rmah"?', options: ['rumah','ramah','rimah'], answer: 0 },
    { problem: 'Ejaan betul untuk "bljar"?', options: ['belajar','beljar','blakar'], answer: 0 },
    { problem: 'Ejaan betul untuk "mkan"?', options: ['makanan','makan','mekkan'], answer: 1 },
    { problem: 'Ejaan betul untuk "kreta"?', options: ['kereta','kareta','kretas'], answer: 0 },
    { problem: 'Ejaan betul untuk "ptang"?', options: ['patang','petang','poteng'], answer: 1 },
    { problem: 'Ejaan betul untuk "skola"?', options: ['sekolah','sekola','skolar'], answer: 0 },
    { problem: 'Ejaan betul untuk "mlm"?', options: ['malam','malim','milam'], answer: 0 },
    { problem: 'Ejaan betul untuk "pgi"?', options: ['pagi','pige','poagi'], answer: 0 },
  ]}},
  { title: 'Antonim (Lawan Kata)', type: 'multiple_choice', emoji: '↔️', difficulty: 'medium', gameData: { questions: [
    { problem: 'Lawan kata "besar"?', options: ['kecil','sederhana','panjang'], answer: 0 },
    { problem: 'Lawan kata "panas"?', options: ['suam','sejuk','lembap'], answer: 1 },
    { problem: 'Lawan kata "gelap"?', options: ['redup','cerah','kusam'], answer: 1 },
    { problem: 'Lawan kata "tua"?', options: ['muda','dewasa','remaja'], answer: 0 },
    { problem: 'Lawan kata "naik"?', options: ['pergi','turun','jatuh'], answer: 1 },
    { problem: 'Lawan kata "siang"?', options: ['petang','malam','subuh'], answer: 1 },
    { problem: 'Lawan kata "keras"?', options: ['lembut','halus','licin'], answer: 0 },
    { problem: 'Lawan kata "awal"?', options: ['lewat','lambat','cepat'], answer: 1 },
  ]}},
  { title: 'Sinonim (Perkataan Sama Makna)', type: 'multiple_choice', emoji: '🔄', difficulty: 'medium', gameData: { questions: [
    { problem: 'Sinonim "cantik"?', options: ['hodoh','indah','kotor'], answer: 1 },
    { problem: 'Sinonim "gembira"?', options: ['sedih','marah','suka'], answer: 2 },
    { problem: 'Sinonim "besar"?', options: ['kecil','agam','tinggi'], answer: 1 },
    { problem: 'Sinonim "cepat"?', options: ['laju','lambat','diam'], answer: 0 },
    { problem: 'Sinonim "pintar"?', options: ['bodoh','bijak','malas'], answer: 1 },
    { problem: 'Sinonim "lapar"?', options: ['kenyang','haus','dahaga'], answer: 1 },
    { problem: 'Sinonim "bahaya"?', options: ['selamat','merbahaya','aman'], answer: 1 },
    { problem: 'Sinonim "kawan"?', options: ['musuh','rakan','lawan'], answer: 1 },
  ]}},
  { title: 'Peribahasa Mudah', type: 'multiple_choice', emoji: '📜', difficulty: 'hard', gameData: { questions: [
    { problem: '"Bersatu teguh bercerai ___"', options: ['kuat','roboh','lemah'], answer: 1 },
    { problem: '"Sediakan payung sebelum ___"', options: ['panas','hujan','ribut'], answer: 1 },
    { problem: '"Rajin pangkal ___"', options: ['kaya','pandai','muda'], answer: 0 },
    { problem: '"Sikit-sikit lama-lama jadi ___"', options: ['banyak','bukit','tinggi'], answer: 1 },
    { problem: '"Air yang tenang jangan ___"', options: ['diminum','dipanik','disangka'], answer: 2 },
    { problem: '"Berani kerana benar takut kerana ___"', options: ['salah','benar','bodoh'], answer: 0 },
    { problem: '"Melentur buluh biarlah dari ___"', options: ['atas','rebungnya','bawah'], answer: 1 },
    { problem: '"Seperti aur dengan ___"', options: ['tebing','sungai','batu'], answer: 0 },
  ]}},
  { title: 'Ayat Tanya dan Jawab', type: 'reading', emoji: '❓', difficulty: 'medium', gameData: { questions: [
    { problem: '"Siapa nama kamu?" — Kata ganti nama yang sesuai?', options: ['Saya','Dia','Mereka'], answer: 0 },
    { problem: '"Di mana kamu duduk?" — Kata tanya yang digunakan?', options: ['Siapa','Di mana','Bila'], answer: 1 },
    { problem: '"Berapa umur kamu?" — Jawab: "Saya _____ tahun"', options: ['berumur','ada','ialah'], answer: 0 },
    { problem: '"Bila kamu makan?" — Kata tanya yang digunakan?', options: ['Bagaimana','Berapa','Bila'], answer: 2 },
    { problem: '"Mengapa kamu menangis?" — Jawab: "Saya menangis _____ jatuh"', options: ['sebab','kerana','dengan'], answer: 1 },
    { problem: '"Bagaimana keadaan kamu?" — Jawab: "Saya _____"', options: ['baik','makan','tidur'], answer: 0 },
    { problem: '"Dengan siapa kamu pergi?" — Jawab: "Saya pergi _____ ibu"', options: ['dan','dengan','bersama'], answer: 2 },
    { problem: '"Apa yang kamu buat?" — Kata tanya yang digunakan?', options: ['Siapa','Apa','Bila'], answer: 1 },
  ]}},
  { title: 'Tatabahasa - Kata Adjektif', type: 'multiple_choice', emoji: '🎨', difficulty: 'medium', gameData: { questions: [
    { problem: 'Manakah kata adjektif?', options: ['berlari','buku','cantik'], answer: 2 },
    { problem: 'Manakah kata adjektif?', options: ['meja','tidur','merah'], answer: 2 },
    { problem: 'Manakah kata adjektif?', options: ['melompat','sekolah','besar'], answer: 2 },
    { problem: 'Manakah kata adjektif?', options: ['hijau','menangis','bunga'], answer: 0 },
    { problem: 'Manakah kata adjektif?', options: ['pokok','berlari','kuat'], answer: 2 },
    { problem: 'Manakah kata adjektif?', options: ['kecil','minum','kereta'], answer: 0 },
    { problem: 'Manakah kata adjektif?', options: ['terbang','burung','tinggi'], answer: 2 },
    { problem: 'Manakah kata adjektif?', options: ['sungai','berenang','sejuk'], answer: 2 },
  ]}},
  { title: 'Pembentukan Kata Majmuk', type: 'word_builder', emoji: '🔗', difficulty: 'medium', gameData: { questions: [
    { problem: 'buku + cerita = ?', options: ['Buku Cerita','Bercerita','Cerita Buku'], answer: 0 },
    { problem: 'meja + makan = ?', options: ['Meja Makan','Memakan','Makan Meja'], answer: 0 },
    { problem: 'rumah + sakit = ?', options: ['Rumah Sakit','Sakit Rumah','Berumah'], answer: 0 },
    { problem: 'kapal + terbang = ?', options: ['Terbang Kapal','Kapal Terbang','Berterbang'], answer: 1 },
    { problem: 'mata + pelajaran = ?', options: ['Pelajaran Mata','Mata Pelajaran','Berpelajaran'], answer: 1 },
    { problem: 'surat + khabar = ?', options: ['Surat Khabar','Khabar Surat','Bersurat'], answer: 0 },
    { problem: 'bola + sepak = ?', options: ['Bola Sepak','Sepak Bola','Menyepak'], answer: 0 },
    { problem: 'air + mata = ?', options: ['Mata Air','Air Mata','Bermata'], answer: 1 },
  ]}},
  { title: 'Membaca Petikan Pendek', type: 'reading', emoji: '📚', difficulty: 'medium', gameData: { questions: [
    { problem: 'Ali ada seekor kucing. Kucing itu berbulu putih. Apakah warna bulu kucing itu?', options: ['Hitam','Putih','Coklat'], answer: 1 },
    { problem: 'Siti makan epal setiap hari. Apakah yang Siti makan?', options: ['Oren','Epal','Pisang'], answer: 1 },
    { problem: 'Matahari terbit pada waktu pagi. Bilakah matahari terbit?', options: ['Petang','Pagi','Malam'], answer: 1 },
    { problem: 'Tom membaca buku di perpustakaan. Di manakah Tom membaca?', options: ['Rumah','Sekolah','Perpustakaan'], answer: 2 },
    { problem: 'Burung terbang di langit. Di manakah burung terbang?', options: ['Dalam laut','Di langit','Di tanah'], answer: 1 },
    { problem: 'Dia ada dua ekor kucing dan seekor anjing. Berapa haiwan dia ada?', options: ['Dua','Tiga','Satu'], answer: 1 },
    { problem: 'Kanak-kanak bermain selepas sekolah. Bilakah mereka bermain?', options: ['Sebelum sekolah','Selepas sekolah','Semasa sekolah'], answer: 1 },
    { problem: 'Amir lebih tinggi daripada Bakar. Siapakah yang lebih tinggi?', options: ['Bakar','Amir','Sama tinggi'], answer: 1 },
  ]}},
  { title: 'Imbuhan Awalan me-', type: 'word_builder', emoji: '📝', difficulty: 'medium', gameData: { questions: [
    { problem: 'me- + makan = ?', options: ['makan','memakan','dimakan'], answer: 1 },
    { problem: 'me- + baca = ?', options: ['membaca','terbaca','dibaca'], answer: 0 },
    { problem: 'me- + tulis = ?', options: ['ditulis','menulis','tertulis'], answer: 1 },
    { problem: 'me- + lihat = ?', options: ['dilihat','terlihat','melihat'], answer: 2 },
    { problem: 'me- + beli = ?', options: ['membeli','terbeli','dibeli'], answer: 0 },
    { problem: 'me- + jual = ?', options: ['terjual','dijual','menjual'], answer: 2 },
    { problem: 'me- + tanya = ?', options: ['bertanya','ditanya','menanya'], answer: 2 },
    { problem: 'me- + buat = ?', options: ['membuat','terbuat','dibuat'], answer: 0 },
  ]}},
  { title: 'Imbuhan Awalan ber-', type: 'word_builder', emoji: '📝', difficulty: 'medium', gameData: { questions: [
    { problem: 'ber- + main = ?', options: ['bermain','termain','dimain'], answer: 0 },
    { problem: 'ber- + lari = ?', options: ['terlari','berlari','dilari'], answer: 1 },
    { problem: 'ber- + jalan = ?', options: ['berjalan','terjalan','dijalan'], answer: 0 },
    { problem: 'ber- + nyayi = ?', options: ['dinyanyikan','ternyayi','bernyanyi'], answer: 2 },
    { problem: 'ber- + cakap = ?', options: ['bercakap','tercakap','dicakap'], answer: 0 },
    { problem: 'ber- + tanya = ?', options: ['bertanya','tertanya','ditanya'], answer: 0 },
    { problem: 'ber- + kerja = ?', options: ['terkerja','dikerja','bekerja'], answer: 2 },
    { problem: 'ber- + senam = ?', options: ['bersenam','tersenam','disenam'], answer: 0 },
  ]}},
  { title: 'Karangan Mudah - Pilihan', type: 'reading', emoji: '✍️', difficulty: 'hard', gameData: { questions: [
    { problem: 'Ayat pembuka karangan yang baik?', options: ['Saya tidak tahu','Pada suatu hari yang cerah...','Tamat'], answer: 1 },
    { problem: 'Kata hubung yang betul: "Saya suka nasi ___ lauk pauk"', options: ['tetapi','dan','kerana'], answer: 1 },
    { problem: 'Ayat yang betul?', options: ['Berlari saya','Saya berlari','Berlari-lari saya'], answer: 1 },
    { problem: '"___ hari Jumaat, kami pergi ke masjid"', options: ['Pada','Di','Ke'], answer: 0 },
    { problem: 'Tanda baca di hujung ayat penyata?', options: ['?','!','.'], answer: 2 },
    { problem: 'Tanda baca di hujung ayat tanya?', options: ['?','!','.'], answer: 0 },
    { problem: 'Kata ganti nama "saya" merujuk kepada?', options: ['Orang lain','Diri sendiri','Semua orang'], answer: 1 },
    { problem: 'Ejaan yang betul?', options: ['sekolaj','sekolah','sakolah'], answer: 1 },
  ]}},
  { title: 'Suku Kata Terbuka dan Tertutup', type: 'multiple_choice', emoji: '🔤', difficulty: 'medium', gameData: { questions: [
    { problem: '"ru-mah" — berapa suku kata?', options: ['1','2','3'], answer: 1 },
    { problem: '"se-ko-lah" — berapa suku kata?', options: ['2','3','4'], answer: 1 },
    { problem: '"bu-ku" — berapa suku kata?', options: ['1','2','3'], answer: 1 },
    { problem: '"ke-lu-ar-ga" — berapa suku kata?', options: ['3','4','5'], answer: 1 },
    { problem: '"ma-kan" — berapa suku kata?', options: ['1','2','3'], answer: 1 },
    { problem: '"pen-sil" — berapa suku kata?', options: ['1','2','3'], answer: 1 },
    { problem: '"ma-ta-ha-ri" — berapa suku kata?', options: ['3','4','5'], answer: 1 },
    { problem: '"a-yah" — berapa suku kata?', options: ['1','2','3'], answer: 1 },
  ]}},
  { title: 'Kata Sendi Nama', type: 'multiple_choice', emoji: '📌', difficulty: 'medium', gameData: { questions: [
    { problem: 'Saya pergi ___ sekolah.', options: ['di','ke','dari'], answer: 1 },
    { problem: 'Buku itu ada ___ meja.', options: ['ke','dari','di'], answer: 2 },
    { problem: 'Dia datang ___ Johor.', options: ['di','ke','dari'], answer: 2 },
    { problem: 'Kucing itu duduk ___ kerusi.', options: ['di atas','ke bawah','dari dalam'], answer: 0 },
    { problem: 'Mereka bermain ___ taman.', options: ['ke','di','dari'], answer: 1 },
    { problem: 'Ibu membeli sayur ___ pasar.', options: ['di','ke','dari'], answer: 0 },
    { problem: 'Ayah pulang ___ pejabat.', options: ['di','ke','dari'], answer: 2 },
    { problem: 'Kami pergi ___ pantai semasa cuti.', options: ['dari','ke','di'], answer: 1 },
  ]}},
  { title: 'Perbendaharaan Kata Peribahasa', type: 'multiple_choice', emoji: '📜', difficulty: 'hard', gameData: { questions: [
    { problem: '"Bagai aur dengan tebing" bermaksud?', options: ['Berpecah belah','Tolong-menolong','Bergaduh'], answer: 1 },
    { problem: '"Sediakan payung sebelum hujan" bermaksud?', options: ['Bersedia untuk masa depan','Takut hujan','Beli payung'], answer: 0 },
    { problem: '"Rajin pangkal pandai" bermaksud?', options: ['Jangan malas belajar','Pandai tanpa usaha','Malas belajar'], answer: 0 },
    { problem: '"Bersatu kita teguh" bermaksud?', options: ['Bergaduh baik','Perpaduan penting','Berpisah lebih baik'], answer: 1 },
    { problem: '"Seperti kacang lupakan kulit" bermaksud?', options: ['Lupa akan asal usul','Suka makan kacang','Kulit kacang tebal'], answer: 0 },
    { problem: '"Buah jatuh tidak jauh dari pokok" bermaksud?', options: ['Anak seperti ibu bapa','Buah selalu jatuh','Pokok buah rendah'], answer: 0 },
    { problem: '"Tong kosong nyaring bunyinya" bermaksud?', options: ['Tong yang penuh','Orang sombong banyak cakap','Bunyi kuat'], answer: 1 },
    { problem: '"Harimau mati meninggalkan belang" bermaksud?', options: ['Harimau berbahaya','Nama baik kekal selepas mati','Belang harimau indah'], answer: 1 },
  ]}},
  { title: 'Penulisan Ayat - Lengkap', type: 'reading', emoji: '✍️', difficulty: 'medium', gameData: { questions: [
    { problem: 'Manakah ayat yang lengkap?', options: ['Berlari cepat','Ali berlari cepat','Sangat cepat berlari'], answer: 1 },
    { problem: 'Manakah subjek dalam ayat "Siti makan nasi"?', options: ['Siti','makan','nasi'], answer: 0 },
    { problem: 'Manakah predikat dalam ayat "Ayah membaca surat khabar"?', options: ['Ayah','membaca surat khabar','surat khabar'], answer: 1 },
    { problem: 'Ayat aktif: "Ibu memasak nasi." — Ayat pasifnya?', options: ['Nasi dimasak ibu','Memasak nasi ibu','Ibu nasi memasak'], answer: 0 },
    { problem: 'Ayat manakah yang menggunakan tanda baca betul?', options: ['Siapa nama kamu.','Siapa nama kamu?','siapa nama kamu?'], answer: 1 },
    { problem: 'Kata pemeri yang betul: "Bunga itu ___ cantik"', options: ['adalah','ialah','adalah'], answer: 0 },
    { problem: 'Kata nafi yang betul: "Saya ___ pergi ke sekolah"', options: ['bukan','tidak','tiada'], answer: 1 },
    { problem: 'Kata tanya yang betul: "___ nama kamu?"', options: ['Bila','Siapa','Di mana'], answer: 1 },
  ]}},
];