// Sekolah Rendah - Jawi
// Silibus mengikut KSSR (Darjah 1-6)

export const sekolah_jawi = [
  // ===== DARJAH 1 =====
  { title: 'Alif hingga Dal Darjah 1', type: 'letter_match', emoji: '🕌', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { letter: 'ا', emoji: '🍎', word: 'Alif', options: ['ا','ب','ت','ث'], answer: 0 },
    { letter: 'ب', emoji: '🐦', word: 'Ba', options: ['ا','ب','ت','ث'], answer: 1 },
    { letter: 'ت', emoji: '🐯', word: 'Ta', options: ['ا','ب','ت','ث'], answer: 2 },
    { letter: 'ث', emoji: '🧊', word: 'Tha', options: ['ا','ب','ت','ث'], answer: 3 },
    { letter: 'ج', emoji: '🦒', word: 'Jim', options: ['ج','ح','خ','د'], answer: 0 },
    { letter: 'ح', emoji: '🌸', word: 'Ha', options: ['ج','ح','خ','د'], answer: 1 },
    { letter: 'خ', emoji: '🌾', word: 'Kha', options: ['ج','ح','خ','د'], answer: 2 },
    { letter: 'د', emoji: '💎', word: 'Dal', options: ['ج','ح','خ','د'], answer: 3 },
  ]}},
  { title: 'Sebutan Huruf Jawi Darjah 1', type: 'sound_match', emoji: '🔊', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: 'ا', options: ['Alif','Ba','Ta'], answer: 0 },
    { image: 'ب', options: ['Alif','Ba','Ta'], answer: 1 },
    { image: 'ت', options: ['Ba','Ta','Jim'], answer: 1 },
    { image: 'ج', options: ['Ta','Jim','Kha'], answer: 1 },
    { image: 'ر', options: ['Za','Ra','Sin'], answer: 1 },
    { image: 'ك', options: ['Qaf','Kaf','Lam'], answer: 1 },
    { image: 'م', options: ['Lam','Mim','Nun'], answer: 1 },
    { image: 'ن', options: ['Mim','Nun','Wau'], answer: 1 },
  ]}},
  { title: 'Jawi - Nama Haiwan Mudah Darjah 1', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '🐱', options: ['كوچيڠ','انجيڠ','ايام'], answer: 0 },
    { image: '🐶', options: ['كوچيڠ','انجيڠ','برونو'], answer: 1 },
    { image: '🐟', options: ['ايكن','بوروڠ','اولر'], answer: 0 },
    { image: '🐦', options: ['ايكن','بوروڠ','اولر'], answer: 1 },
    { image: '☀️', options: ['ماتاهاري','بولن','بيماكيڠ'], answer: 0 },
    { image: '🌙', options: ['ماتاهاري','بولن','بيماكيڠ'], answer: 1 },
    { image: '🍎', options: ['ايڤل','اورين','پيساڠ'], answer: 0 },
    { image: '🍌', options: ['ايڤل','اورين','پيساڠ'], answer: 2 },
  ]}},

  // ===== DARJAH 2 =====
  { title: 'Zal hingga Sin Darjah 2', type: 'letter_match', emoji: '🕌', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { letter: 'ذ', emoji: '🦌', word: 'Dzal', options: ['ذ','ر','ز','س'], answer: 0 },
    { letter: 'ر', emoji: '🌹', word: 'Ra', options: ['ذ','ر','ز','س'], answer: 1 },
    { letter: 'ز', emoji: '🌺', word: 'Zain', options: ['ذ','ر','ز','س'], answer: 2 },
    { letter: 'س', emoji: '⭐', word: 'Sin', options: ['ذ','ر','ز','س'], answer: 3 },
    { letter: 'ش', emoji: '☀️', word: 'Shin', options: ['ش','ص','ض','ط'], answer: 0 },
    { letter: 'ص', emoji: '🦅', word: 'Sad', options: ['ش','ص','ض','ط'], answer: 1 },
    { letter: 'ض', emoji: '🐊', word: 'Dad', options: ['ش','ص','ض','ط'], answer: 2 },
    { letter: 'ط', emoji: '🦚', word: 'Ta', options: ['ش','ص','ض','ط'], answer: 3 },
  ]}},
  { title: 'Jawi - Anggota Badan Darjah 2', type: 'picture_quiz', emoji: '🧒', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { image: '👁️', options: ['مات','هيدوڠ','تليڠ'], answer: 0 },
    { image: '👃', options: ['مات','هيدوڠ','تليڠ'], answer: 1 },
    { image: '👂', options: ['مات','هيدوڠ','تليڠ'], answer: 2 },
    { image: '👄', options: ['موله','هيدوڠ','بيبير'], answer: 0 },
    { image: '✋', options: ['كاكي','تاڠن','بادن'], answer: 1 },
    { image: '🦶', options: ['كاكي','تاڠن','لنڬن'], answer: 0 },
    { image: '🧠', options: ['جنتوڠ','اوتق','ڤاروه'], answer: 1 },
    { image: '❤️', options: ['اوتق','جنتوڠ','ڤاروه'], answer: 1 },
  ]}},
  { title: 'Nombor Jawi Darjah 2', type: 'number_match', emoji: '🔢', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: '١', options: ['Satu','Dua','Tiga'], answer: 0 },
    { problem: '٢', options: ['Satu','Dua','Tiga'], answer: 1 },
    { problem: '٣', options: ['Dua','Tiga','Empat'], answer: 1 },
    { problem: '٤', options: ['Tiga','Empat','Lima'], answer: 1 },
    { problem: '٥', options: ['Empat','Lima','Enam'], answer: 1 },
    { problem: '٦', options: ['Lima','Enam','Tujuh'], answer: 1 },
    { problem: '٧', options: ['Enam','Tujuh','Lapan'], answer: 1 },
    { problem: '١٠', options: ['Sembilan','Sepuluh','Sebelas'], answer: 1 },
  ]}},

  // ===== DARJAH 3 =====
  { title: 'Ain hingga Ya Darjah 3', type: 'letter_match', emoji: '🕌', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { letter: 'ظ', emoji: '🦁', word: 'Zha', options: ['ظ','ع','غ','ف'], answer: 0 },
    { letter: 'ع', emoji: '🍇', word: 'Ain', options: ['ظ','ع','غ','ف'], answer: 1 },
    { letter: 'غ', emoji: '🦜', word: 'Ghain', options: ['ظ','ع','غ','ف'], answer: 2 },
    { letter: 'ف', emoji: '🦋', word: 'Fa', options: ['ظ','ع','غ','ف'], answer: 3 },
    { letter: 'ق', emoji: '🐸', word: 'Qaf', options: ['ق','ك','ل','م'], answer: 0 },
    { letter: 'ن', emoji: '🌟', word: 'Nun', options: ['ن','و','ه','ي'], answer: 0 },
    { letter: 'و', emoji: '🌼', word: 'Wau', options: ['ن','و','ه','ي'], answer: 1 },
    { letter: 'ي', emoji: '🌿', word: 'Ya', options: ['ن','و','ه','ي'], answer: 3 },
  ]}},
  { title: 'Perkataan Jawi Mudah Darjah 3', type: 'picture_quiz', emoji: '📖', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { image: '🏠', options: ['رومه','سكوله','كدي'], answer: 0 },
    { image: '📚', options: ['بوكو','قلم','كرتس'], answer: 0 },
    { image: '🏫', options: ['سكوله','مسجيد','كدي'], answer: 0 },
    { image: '🕌', options: ['سكوله','مسجيد','بندر'], answer: 1 },
    { image: '🚗', options: ['كرتس','كيرتا','باس'], answer: 1 },
    { image: '🌳', options: ['ڤوكوق','بوڠ','داون'], answer: 0 },
    { image: '🌸', options: ['ڤوكوق','بوڠ','بويه'], answer: 1 },
    { image: '🍎', options: ['ايڤل','اورين','پيساڠ'], answer: 0 },
  ]}},
  { title: 'Harakat Jawi Darjah 3', type: 'multiple_choice', emoji: '🔤', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Baris fathah (atas) berbunyi?', options: ['a','i','u'], answer: 0 },
    { problem: 'Baris kasrah (bawah) berbunyi?', options: ['a','i','u'], answer: 1 },
    { problem: 'Baris dhammah (depan) berbunyi?', options: ['a','i','u'], answer: 2 },
    { problem: 'بَ dengan baris fathah berbunyi?', options: ['ba','bi','bu'], answer: 0 },
    { problem: 'بِ dengan baris kasrah berbunyi?', options: ['ba','bi','bu'], answer: 1 },
    { problem: 'بُ dengan baris dhammah berbunyi?', options: ['ba','bi','bu'], answer: 2 },
    { problem: 'مَ berbunyi?', options: ['ma','mi','mu'], answer: 0 },
    { problem: 'كُ berbunyi?', options: ['ka','ki','ku'], answer: 2 },
  ]}},

  // ===== DARJAH 4 =====
  { title: 'Huruf Jawi yang Serupa Darjah 4', type: 'letter_match', emoji: '🔍', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { letter: 'ب', emoji: '📍', word: 'Ba (1 titik bawah)', options: ['ب','ت','ث','ن'], answer: 0 },
    { letter: 'ت', emoji: '📍📍', word: 'Ta (2 titik atas)', options: ['ب','ت','ث','ن'], answer: 1 },
    { letter: 'ث', emoji: '📍📍📍', word: 'Tha (3 titik atas)', options: ['ب','ت','ث','ن'], answer: 2 },
    { letter: 'ن', emoji: '📍', word: 'Nun (1 titik dalam)', options: ['ب','ت','ث','ن'], answer: 3 },
    { letter: 'ج', emoji: '📍', word: 'Jim (1 titik bawah)', options: ['ج','ح','خ','ع'], answer: 0 },
    { letter: 'ح', emoji: '❌', word: 'Ha (tanpa titik)', options: ['ج','ح','خ','ع'], answer: 1 },
    { letter: 'خ', emoji: '📍', word: 'Kha (1 titik atas)', options: ['ج','ح','خ','ع'], answer: 2 },
    { letter: 'د', emoji: '❌', word: 'Dal (tanpa titik)', options: ['د','ذ','ر','ز'], answer: 0 },
  ]}},
  { title: 'Jawi - Kata Kerja Harian Darjah 4', type: 'multiple_choice', emoji: '⚡', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: 'Jawi untuk "makan" ialah?', options: ['ماكن','مينوم','تيدور'], answer: 0 },
    { problem: 'Jawi untuk "minum" ialah?', options: ['ماكن','مينوم','برجالن'], answer: 1 },
    { problem: 'Jawi untuk "tidur" ialah?', options: ['تيدور','بانڬون','دودوق'], answer: 0 },
    { problem: 'Jawi untuk "belajar" ialah?', options: ['برمين','بلاجر','مڠاجر'], answer: 1 },
    { problem: 'Jawi untuk "berlari" ialah?', options: ['برلاري','برجالن','تربڠ'], answer: 0 },
    { problem: 'Jawi untuk "menulis" ialah?', options: ['مباچ','منوليس','مڠيرا'], answer: 1 },
    { problem: 'Jawi untuk "membaca" ialah?', options: ['مباچ','منوليس','برچاكڤ'], answer: 0 },
    { problem: 'Jawi untuk "bermain" ialah?', options: ['برمين','بلاجر','برسوكان'], answer: 0 },
  ]}},
  { title: 'Jawi - Kosa Kata Alam Darjah 4', type: 'picture_quiz', emoji: '🌿', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { image: '🌳', options: ['ڤوكوق','بوڠ','داون'], answer: 0 },
    { image: '🌸', options: ['ڤوكوق','بوڠ','بويه'], answer: 1 },
    { image: '🌊', options: ['لاوت','سوڠاي','تاسيق'], answer: 0 },
    { image: '⛰️', options: ['بوكيت','ڬونوڠ','داتاران'], answer: 1 },
    { image: '🌙', options: ['ماتاهاري','بولن','بيماكيڠ'], answer: 1 },
    { image: '☀️', options: ['ماتاهاري','بولن','بيماكيڠ'], answer: 0 },
    { image: '🌧️', options: ['انيڠ','هوجن','ريبوت'], answer: 1 },
    { image: '🌈', options: ['ڤلاڠي','كيلت','ڤتير'], answer: 0 },
  ]}},

  // ===== DARJAH 5 =====
  { title: 'Ayat Jawi Pendek Darjah 5', type: 'reading', emoji: '📜', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'ساي سوك بلاجر', options: ['Saya suka belajar','Saya pergi sekolah','Saya makan nasi'], answer: 0 },
    { problem: 'ايبو مماسق ناسي', options: ['Ibu membeli nasi','Ibu memasak nasi','Ibu memakan nasi'], answer: 1 },
    { problem: 'اياه برق كرج', options: ['Ayah balik kerja','Ayah pergi kerja','Ayah cari kerja'], answer: 1 },
    { problem: 'كامي برمين بولا', options: ['Kami beli bola','Kami tengok bola','Kami bermain bola'], answer: 2 },
    { problem: 'بوڠ ايت ميره', options: ['Bunga itu biru','Bunga itu merah','Bunga itu kuning'], answer: 1 },
    { problem: 'كوچيڠ ايت چومل', options: ['Kucing itu besar','Kucing itu hitam','Kucing itu comel'], answer: 2 },
    { problem: 'لاڠيت ايت بيرو', options: ['Langit itu merah','Langit itu biru','Langit itu hijau'], answer: 1 },
    { problem: 'ادق تيدور اوله', options: ['Adik makan sudah','Adik tidur sudah','Adik mandi sudah'], answer: 1 },
  ]}},
  { title: 'Jawi - Warna dan Sifat Darjah 5', type: 'picture_quiz', emoji: '🎨', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { image: '🔴', options: ['ميره','بيرو','هيجاو'], answer: 0 },
    { image: '🔵', options: ['ميره','بيرو','كونيڠ'], answer: 1 },
    { image: '🟢', options: ['اوڠو','هيجاو','اورن'], answer: 1 },
    { image: '🟡', options: ['كونيڠ','اورن','ڤوتيه'], answer: 0 },
    { image: '💜', options: ['اوڠو','ميره جمبو','بيرو'], answer: 0 },
    { image: '⚫', options: ['چوكلات','هيتم','كلابو'], answer: 1 },
    { image: '⚪', options: ['ڤوتيه','هيتم','كلابو'], answer: 0 },
    { image: '🤎', options: ['چوكلات','هيتم','كلابو'], answer: 0 },
  ]}},
  { title: 'Jawi - Keluarga Darjah 5', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { image: '👨', options: ['اياه','ايبو','اباڠ'], answer: 0 },
    { image: '👩', options: ['اياه','ايبو','كاكق'], answer: 1 },
    { image: '👦', options: ['اباڠ','اديق','داتوق'], answer: 1 },
    { image: '👧', options: ['كاكق','نينيق','ايبو'], answer: 0 },
    { image: '👴', options: ['اياه','داتوق','اباڠ'], answer: 1 },
    { image: '👵', options: ['ايبو','نينيق','كاكق'], answer: 1 },
    { image: '👶', options: ['بايي','اديق','بوداق'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['كلوارڬ','كاوان','جيران'], answer: 0 },
  ]}},

  // ===== DARJAH 6 =====
  { title: 'Jawi - Ayat Lengkap Darjah 6', type: 'reading', emoji: '📜', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'كامي برمين دي تامن بوڠ', options: ['Kami bermain di taman bunga','Kami tidur di taman bunga','Kami makan di taman'], answer: 0 },
    { problem: 'ايبو مبلي بوه-بواهن دي ڤسر', options: ['Ibu menjual buah di pasar','Ibu membeli buah-buahan di pasar','Ibu pergi ke pasar'], answer: 1 },
    { problem: 'اياه ڤرڬي كرج نايق كرتس', options: ['Ayah pergi kerja naik kereta','Ayah balik kerja naik bas','Ayah pergi sekolah naik kereta'], answer: 0 },
    { problem: 'سايا سوك ماكن ناسي لماق', options: ['Saya suka makan nasi lemak','Saya suka makan roti','Saya suka minum teh'], answer: 0 },
    { problem: 'بوروڠ تربڠ دي لاڠيت دڠن رياڠ', options: ['Burung berenang di sungai','Burung terbang di langit dengan riang','Burung duduk di pokok'], answer: 1 },
    { problem: 'كامي برسيوكور كڤد الله', options: ['Kami berdoa kepada ibu bapa','Kami bersyukur kepada Allah','Kami bermain setiap hari'], answer: 1 },
    { problem: 'لاڠيت ڤاد ماس سياڠ بروارن بيرو', options: ['Langit pada waktu malam hitam','Langit pada masa siang berwarna biru','Langit pada waktu petang merah'], answer: 1 },
    { problem: 'اديق سايا سوك مين بولا', options: ['Abang saya suka main bola','Adik saya suka main bola','Kakak saya suka main bola'], answer: 1 },
  ]}},
  { title: 'Jawi - Makanan & Minuman Darjah 6', type: 'picture_quiz', emoji: '🍎', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { image: '🍎', options: ['ايڤل','اورين','پيساڠ'], answer: 0 },
    { image: '🍊', options: ['ايڤل','اورين','مڠڬ'], answer: 1 },
    { image: '🍌', options: ['پيساڠ','ڤڤاي','مڠڬ'], answer: 0 },
    { image: '🍚', options: ['ناسي','روتي','مي'], answer: 0 },
    { image: '🍞', options: ['ناسي','روتي','بيسكوت'], answer: 1 },
    { image: '🥛', options: ['سوسو','اير','جوس'], answer: 0 },
    { image: '🍰', options: ['كيق','كوييه','دونوت'], answer: 0 },
    { image: '🍜', options: ['ناسي','مي','بيهون'], answer: 1 },
  ]}},
  { title: 'Jawi - Tempat & Lokasi Darjah 6', type: 'picture_quiz', emoji: '🗺️', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { image: '🏫', options: ['سكوله','مسجيد','كدي'], answer: 0 },
    { image: '🕌', options: ['سكوله','مسجيد','بندر'], answer: 1 },
    { image: '🏪', options: ['رومه','كدي','سكوله'], answer: 1 },
    { image: '🏥', options: ['هوسڤيتل','سكوله','مسجيد'], answer: 0 },
    { image: '🌳', options: ['تامن','هوتن','كبون'], answer: 1 },
    { image: '🌊', options: ['لاوت','سوڠاي','كولم'], answer: 0 },
    { image: '🛒', options: ['ڤسر','كدي','بندر'], answer: 0 },
    { image: '🏠', options: ['رومه','سكوله','كدي'], answer: 0 },
  ]}},
  { title: 'Jawi - Huruf Bersambung Darjah 3', type: 'letter_match', emoji: '✍️', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { letter: 'ب', emoji: '📖', word: 'Buku - بوكو', options: ['ب','ت','ث','ج'], answer: 0 },
    { letter: 'ت', emoji: '🍅', word: 'Tomat - تومات', options: ['ب','ت','ث','ج'], answer: 1 },
    { letter: 'ج', emoji: '🌉', word: 'Jambatan - جمباتن', options: ['ث','ج','ح','خ'], answer: 1 },
    { letter: 'ح', emoji: '🌿', word: 'Hijau - حيجاو', options: ['ج','ح','خ','د'], answer: 1 },
    { letter: 'ر', emoji: '🌹', word: 'Ros - روس', options: ['ذ','ر','ز','س'], answer: 1 },
    { letter: 'س', emoji: '⭐', word: 'Satu - ساتو', options: ['ر','س','ش','ص'], answer: 1 },
    { letter: 'ع', emoji: '🦅', word: 'Elang - عيلڠ', options: ['ض','ط','ظ','ع'], answer: 3 },
    { letter: 'ق', emoji: '👸', word: 'Queen - قوين', options: ['ف','ق','ك','ل'], answer: 1 },
  ]}},
  { title: 'Jawi - Kata Nama Am Darjah 4', type: 'picture_quiz', emoji: '🔤', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { image: '📚', options: ['بوكو','ڤنسيل','كرتس'], answer: 0 },
    { image: '✏️', options: ['بوكو','ڤنسيل','ڤنهاڤوس'], answer: 1 },
    { image: '🚗', options: ['باس','كريتا','لوري'], answer: 1 },
    { image: '🌳', options: ['ڤوكوق','بوڠ','رومڤوت'], answer: 0 },
    { image: '🏠', options: ['سكوله','رومه','كدي'], answer: 1 },
    { image: '💧', options: ['اير','انڬين','تنه'], answer: 0 },
    { image: '☀️', options: ['بولن','ماتهاري','بينتڠ'], answer: 1 },
    { image: '🌊', options: ['سوڠاي','لاوت','تسيق'], answer: 1 },
  ]}},
  { title: 'Jawi - Kata Kerja Darjah 5', type: 'multiple_choice', emoji: '⚡', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Tulisan Jawi "berlari"?', options: ['برلاري','برمين','برجالن'], answer: 0 },
    { problem: 'Tulisan Jawi "membaca"?', options: ['مليهت','مامباچ','منوليس'], answer: 1 },
    { problem: 'Tulisan Jawi "menulis"?', options: ['مامباچ','منوليس','مليهت'], answer: 1 },
    { problem: 'Tulisan Jawi "bermain"?', options: ['برمين','برلاري','برتيدور'], answer: 0 },
    { problem: 'Tulisan Jawi "makan"?', options: ['مينوم','ماكن','تيدور'], answer: 1 },
    { problem: 'Tulisan Jawi "minum"?', options: ['ماكن','مينوم','برلاري'], answer: 1 },
    { problem: 'Tulisan Jawi "tidur"?', options: ['تيدور','ماكن','برمين'], answer: 0 },
    { problem: 'Tulisan Jawi "belajar"?', options: ['برمين','بلاجر','برلاري'], answer: 1 },
  ]}},
  { title: 'Membaca Jawi - Ayat Mudah', type: 'multiple_choice', emoji: '📖', difficulty: 'medium', darjah: 5, gameData: { questions: [
   { problem: 'Baca: "السلام عليكم ورحمة الله وبركاته" - Makna?', options: ['Maafkan aku','Salam sejahtera','Terima kasih'], answer: 1 },
   { problem: 'Baca: "بسم الله الرحمن الرحيم" - Permulaan apa?', options: ['Surat','Doa','Cerita'], answer: 0 },
   { problem: 'Jawi mewakili?', options: ['Inggeris','Bahasa Melayu','Cina'], answer: 1 },
   { problem: 'Arah membaca Jawi?', options: ['Kiri ke kanan','Kanan ke kiri','Atas ke bawah'], answer: 1 },
   { problem: 'Kalimah "والسلام عليكم" - maksud?', options: ['Terima kasih','Salam akhir','Selamat malam'], answer: 1 },
   { problem: 'Harakat dalam Jawi bertujuan?', options: ['Hiasan','Tunjuk sebutan','Panjangkan ayat'], answer: 1 },
   { problem: 'Jawi tulisan apa yang asli?', options: ['Baru','Kuno dan warisan','Asing'], answer: 1 },
   { problem: 'Bacaan Jawi dalam ibadah?', options: ['Pilihan','Penting dalam Al-Quran','Tidak perlu'], answer: 1 },
  ]}},
  { title: 'Padanan Jawi-Rumi Mudah', type: 'multiple_choice', emoji: '🔤', difficulty: 'medium', darjah: 4, gameData: { questions: [
   { problem: '"الكتاب" (Al-Kitab) bermakna?', options: ['Pensel','Buku','Papan'], answer: 1 },
   { problem: '"القلم" (Al-Qalam) bermakna?', options: ['Buku','Pensel','Meja'], answer: 1 },
   { problem: '"المدرسة" (Al-Madarasah) bermakna?', options: ['Rumah','Sekolah','Pasar'], answer: 1 },
   { problem: '"الحديقة" (Al-Hadiqah) bermakna?', options: ['Taman','Jalan','Kedai'], answer: 0 },
   { problem: '"الماء" (Al-Ma\'u) bermakna?', options: ['Api','Air','Tanah'], answer: 1 },
   { problem: '"الشمس" (Ash-Shams) bermakna?', options: ['Bulan','Bintang','Matahari'], answer: 2 },
   { problem: '"القمر" (Al-Qamar) bermakna?', options: ['Matahari','Bulan','Bintang'], answer: 1 },
   { problem: '"الرياح" (Ar-Riyah) bermakna?', options: ['Air','Angin','Tanah'], answer: 1 },
  ]}},
  { title: 'Jawi - Ayat Pendek Darjah 5', type: 'reading', emoji: '📖', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '"علي ڤرڬي ك سكوله" bermaksud?', options: ['Ali pergi ke kedai','Ali pergi ke sekolah','Ali balik sekolah'], answer: 1 },
    { problem: '"سيت ماكن ناسي" bermaksud?', options: ['Siti minum air','Siti makan nasi','Siti tidur'], answer: 1 },
    { problem: '"اير اداله ڤنتيڠ" bermaksud?', options: ['Air adalah panas','Air adalah penting','Air adalah sejuk'], answer: 1 },
    { problem: '"بوڠ ايت ايندهّ" bermaksud?', options: ['Bunga itu kecil','Bunga itu cantik/indah','Bunga itu besar'], answer: 1 },
    { problem: '"راجين بلاجر سوڤيا ڤاندي" bermaksud?', options: ['Rajin tidur supaya pandai','Rajin belajar supaya pandai','Rajin bermain sahaja'], answer: 1 },
    { problem: 'Huruf Jawi ada berapa?', options: ['26','28','30'], answer: 1 },
    { problem: 'Jawi ditulis dari?', options: ['Kiri ke kanan','Kanan ke kiri','Atas ke bawah'], answer: 1 },
    { problem: 'Jawi berasal dari tulisan?', options: ['Cina','Arab','India'], answer: 1 },
  ]}},
  { title: 'Jawi - Imbuhan Darjah 6', type: 'word_builder', emoji: '🔡', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Jawi untuk "memakan"?', options: ['ممكن','ممبچ','منوليس'], answer: 0 },
    { problem: 'Jawi untuk "berlari"?', options: ['برمين','برلاري','برتاڽ'], answer: 1 },
    { problem: 'Jawi untuk "dimakan"?', options: ['ديماكن','ممكن','ترماكن'], answer: 0 },
    { problem: 'Jawi untuk "termakan"?', options: ['ديماكن','ممكن','ترماكن'], answer: 2 },
    { problem: 'Imbuhan "me-" dalam Jawi?', options: ['بر','دي','م/من/مم/منج/منڬ'], answer: 2 },
    { problem: 'Imbuhan "ber-" dalam Jawi?', options: ['بر','دي','ت'], answer: 0 },
    { problem: 'Imbuhan "di-" dalam Jawi?', options: ['بر','دي','ت'], answer: 1 },
    { problem: 'Imbuhan "ter-" dalam Jawi?', options: ['بر','دي','تر'], answer: 2 },
  ]}},
  { title: 'Jawi - Ejaan Betul Darjah 6', type: 'spelling', emoji: '🔤', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Ejaan Jawi "kereta" yang betul?', options: ['كريتا','كرتا','كيريتا'], answer: 0 },
    { problem: 'Ejaan Jawi "sekolah" yang betul?', options: ['سكول','سكوله','سيكوله'], answer: 1 },
    { problem: 'Ejaan Jawi "Malaysia" yang betul?', options: ['ملايسيا','مليسيا','ملايسا'], answer: 0 },
    { problem: 'Ejaan Jawi "belajar" yang betul?', options: ['بلاجار','بلاجر','بيلاجر'], answer: 1 },
    { problem: 'Ejaan Jawi "matahari" yang betul?', options: ['ماتهاري','ماتاهاري','مته هاري'], answer: 0 },
    { problem: 'Ejaan Jawi "permainan" yang betul?', options: ['ڤرمينن','ڤرمايينن','ڤيرمينن'], answer: 0 },
    { problem: 'Ejaan Jawi "ibu bapa" yang betul?', options: ['ايبو باڤ','ايبو باڤا','ايبوباڤ'], answer: 1 },
    { problem: 'Ejaan Jawi "perjalanan" yang betul?', options: ['ڤرجالانن','ڤيرجلنن','ڤرجلنن'], answer: 0 },
  ]}},
];