// Prasekolah - Matematik - Expansion (10 games)
export const prasekolah_mathematics_expansion = [
  { title: 'Nombor Ganda Mudah', type: 'math_puzzle', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: 'Nombor ganda 1 ialah?', options: ['1','2','3'], answer: 1 },
    { problem: 'Nombor ganda 2 ialah?', options: ['2','4','6'], answer: 1 },
    { problem: 'Nombor ganda 3 ialah?', options: ['3','6','9'], answer: 1 },
    { problem: 'Nombor ganda 4 ialah?', options: ['4','8','12'], answer: 1 },
    { problem: 'Nombor ganda 5 ialah?', options: ['5','10','15'], answer: 1 },
    { problem: 'Nombor ganda 6 ialah?', options: ['6','12','18'], answer: 1 },
    { problem: 'Nombor ganda 7 ialah?', options: ['7','14','21'], answer: 1 },
    { problem: 'Nombor ganda 8 ialah?', options: ['8','16','24'], answer: 1 },
  ]}},
  { title: 'Susunan Nombor 1-20 Menaik', type: 'number_match', emoji: '📈', difficulty: 'easy', gameData: { questions: [
    { problem: 'Susun menaik: 5, 3, 8, 1', options: ['1, 3, 5, 8','8, 5, 3, 1','3, 1, 5, 8'], answer: 0 },
    { problem: 'Susun menaik: 12, 7, 15, 10', options: ['7, 10, 12, 15','15, 12, 10, 7','12, 7, 10, 15'], answer: 0 },
    { problem: 'Mana paling kecil: 9, 6, 3, 12?', options: ['9','6','3'], answer: 2 },
    { problem: 'Mana paling besar: 8, 14, 5, 11?', options: ['8','14','5'], answer: 1 },
    { problem: '1 hingga 5 menaik?', options: ['1, 2, 3, 4, 5','5, 4, 3, 2, 1','3, 1, 4, 2, 5'], answer: 0 },
    { problem: '15 hingga 20 menaik?', options: ['15, 16, 17, 18, 19, 20','20, 19, 18, 17, 16, 15','16, 17, 18, 19, 20, 15'], answer: 0 },
    { problem: 'Susun: 18, 3, 9, 12 — menaik?', options: ['3, 9, 12, 18','18, 12, 9, 3','12, 3, 18, 9'], answer: 0 },
    { problem: 'Susun: 20, 10, 5, 15 — menaik?', options: ['5, 10, 15, 20','20, 15, 10, 5','10, 5, 20, 15'], answer: 0 },
  ]}},
  { title: 'Operasi Asas - Gabung Angka', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '2 + 3 + 1 = ?', options: ['5','6','7'], answer: 0 },
    { problem: '1 + 2 + 3 = ?', options: ['5','6','7'], answer: 0 },
    { problem: '2 + 2 + 2 = ?', options: ['5','6','7'], answer: 1 },
    { problem: '3 + 2 + 1 = ?', options: ['5','6','7'], answer: 0 },
    { problem: '4 + 1 + 1 = ?', options: ['5','6','7'], answer: 0 },
    { problem: '2 + 3 + 2 = ?', options: ['5','6','7'], answer: 1 },
    { problem: '3 + 3 + 1 = ?', options: ['5','6','7'], answer: 1 },
    { problem: '1 + 1 + 1 = ?', options: ['2','3','4'], answer: 1 },
  ]}},
  { title: 'Operasi Tolak Dua Angka Sederhana', type: 'math_puzzle', emoji: '➖', difficulty: 'easy', gameData: { questions: [
    { problem: '5 - 2 = ?', options: ['2','3','4'], answer: 1 },
    { problem: '6 - 1 = ?', options: ['4','5','6'], answer: 1 },
    { problem: '7 - 3 = ?', options: ['3','4','5'], answer: 1 },
    { problem: '8 - 2 = ?', options: ['5','6','7'], answer: 1 },
    { problem: '9 - 4 = ?', options: ['4','5','6'], answer: 1 },
    { problem: '10 - 5 = ?', options: ['4','5','6'], answer: 1 },
    { problem: '6 - 3 = ?', options: ['2','3','4'], answer: 1 },
    { problem: '4 - 2 = ?', options: ['1','2','3'], answer: 1 },
  ]}},
  { title: 'Pola Angka Mudah', type: 'pattern_fill', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '2, 4, 6, ?', options: ['7','8','9'], answer: 1 },
    { problem: '1, 3, 5, ?', options: ['6','7','8'], answer: 1 },
    { problem: '5, 10, 15, ?', options: ['18','20','22'], answer: 1 },
    { problem: '1, 2, 3, ?', options: ['3','4','5'], answer: 1 },
    { problem: '10, 8, 6, ?', options: ['3','4','5'], answer: 1 },
    { problem: '2, 4, 6, 8, ?', options: ['9','10','11'], answer: 1 },
    { problem: '3, 6, 9, ?', options: ['11','12','13'], answer: 1 },
    { problem: '5, 5, 5, ?', options: ['5','6','7'], answer: 0 },
  ]}},
  { title: 'Jumlah Mudah - Kumpulan Benda', type: 'counting', emoji: '📦', difficulty: 'easy', gameData: { questions: [
    { problem: 'Berapa garis? |||||', options: ['4','5','6'], answer: 1 },
    { problem: 'Berapa segitiga? △△△△', options: ['3','4','5'], answer: 1 },
    { problem: 'Berapa bulatan? ●●●●●●', options: ['5','6','7'], answer: 1 },
    { problem: 'Berapa bintang? ⭐⭐⭐', options: ['2','3','4'], answer: 1 },
    { problem: 'Berapa persegi? ◻◻◻◻', options: ['3','4','5'], answer: 1 },
    { problem: 'Berapa jantung? ❤❤❤❤❤', options: ['4','5','6'], answer: 1 },
    { problem: 'Berapa bulan? 🌙🌙🌙', options: ['2','3','4'], answer: 1 },
    { problem: 'Berapa matahari? ☀☀', options: ['1','2','3'], answer: 1 },
  ]}},
  { title: 'Pasangan Bilangan Sejumlah 10', type: 'math_puzzle', emoji: '🔟', difficulty: 'medium', gameData: { questions: [
    { problem: '1 + ? = 10', options: ['8','9','10'], answer: 1 },
    { problem: '2 + ? = 10', options: ['7','8','9'], answer: 1 },
    { problem: '3 + ? = 10', options: ['6','7','8'], answer: 1 },
    { problem: '4 + ? = 10', options: ['5','6','7'], answer: 1 },
    { problem: '5 + ? = 10', options: ['4','5','6'], answer: 1 },
    { problem: '6 + ? = 10', options: ['3','4','5'], answer: 1 },
    { problem: '7 + ? = 10', options: ['2','3','4'], answer: 1 },
    { problem: '9 + ? = 10', options: ['0','1','2'], answer: 1 },
  ]}},
  { title: 'Bilangan Berurutan Lengkap', type: 'number_match', emoji: '1️⃣2️⃣3️⃣', difficulty: 'easy', gameData: { questions: [
    { problem: '1, ?, 3', options: ['2','4','5'], answer: 0 },
    { problem: '4, ?, 6', options: ['5','7','8'], answer: 0 },
    { problem: '7, ?, 9', options: ['8','10','11'], answer: 0 },
    { problem: '10, ?, 12', options: ['11','13','14'], answer: 0 },
    { problem: '2, ?, 4', options: ['3','5','6'], answer: 0 },
    { problem: '5, ?, 7', options: ['6','8','9'], answer: 0 },
    { problem: '8, ?, 10', options: ['9','11','12'], answer: 0 },
    { problem: '3, ?, 5', options: ['4','6','7'], answer: 0 },
  ]}},
  { title: 'Perbandingan Bilangan Besar Kecil', type: 'multiple_choice', emoji: '⚖️', difficulty: 'easy', gameData: { questions: [
    { problem: '5 atau 3 — mana lebih besar?', options: ['3','5','Sama'], answer: 1 },
    { problem: '8 atau 6 — mana lebih kecil?', options: ['6','8','Sama'], answer: 0 },
    { problem: '10 atau 10 — lebih mana?', options: ['10 besar','10 kecil','Sama'], answer: 2 },
    { problem: '7 atau 9 — mana lebih besar?', options: ['7','9','Sama'], answer: 1 },
    { problem: '4 atau 2 — mana lebih kecil?', options: ['4','2','Sama'], answer: 1 },
    { problem: '6 atau 8 — mana lebih besar?', options: ['6','8','Sama'], answer: 1 },
    { problem: '15 atau 12 — mana lebih kecil?', options: ['12','15','Sama'], answer: 0 },
    { problem: '20 atau 15 — mana lebih besar?', options: ['15','20','Sama'], answer: 1 },
  ]}},
  { title: 'Aturan Bilangan Genap Ganjil', type: 'multiple_choice', emoji: '🔢', difficulty: 'medium', gameData: { questions: [
    { problem: '2 adalah bilangan?', options: ['Ganjil','Genap','Neutral'], answer: 1 },
    { problem: '3 adalah bilangan?', options: ['Ganjil','Genap','Neutral'], answer: 0 },
    { problem: '4 adalah bilangan?', options: ['Ganjil','Genap','Neutral'], answer: 1 },
    { problem: '5 adalah bilangan?', options: ['Ganjil','Genap','Neutral'], answer: 0 },
    { problem: '6 adalah bilangan?', options: ['Ganjil','Genap','Neutral'], answer: 1 },
    { problem: '7 adalah bilangan?', options: ['Ganjil','Genap','Neutral'], answer: 0 },
    { problem: 'Bilangan genap contohnya?', options: ['3, 5, 7','2, 4, 6','1, 3, 5'], answer: 1 },
    { problem: 'Bilangan ganjil contohnya?', options: ['2, 4, 6','1, 3, 5','4, 6, 8'], answer: 1 },
  ]}},
];