export const prasekolah_mathematics = [
  { title: 'Kira 1 hingga 5', type: 'counting', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['1','2','3'], answer: 0 },
    { image: '🍎🍎', options: ['1','2','3'], answer: 1 },
    { image: '🍎🍎🍎', options: ['1','2','3'], answer: 2 },
    { image: '🍎🍎🍎🍎', options: ['3','4','5'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎', options: ['4','5','6'], answer: 1 },
    { image: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { image: '⭐⭐⭐', options: ['2','3','4'], answer: 1 },
    { image: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { image: '🍊', options: ['1','2','3'], answer: 0 },
    { image: '🍊🍊', options: ['1','2','3'], answer: 1 },
    { image: '🍊🍊🍊', options: ['1','2','3'], answer: 2 },
    { image: '🍊🍊🍊🍊', options: ['3','4','5'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊', options: ['4','5','6'], answer: 1 },
    { image: '🎈🎈', options: ['1','2','3'], answer: 1 },
    { image: '🎈🎈🎈', options: ['2','3','4'], answer: 1 },
    { image: '🎈🎈🎈🎈', options: ['3','4','5'], answer: 1 },
    { image: '🎁', options: ['1','2','3'], answer: 0 },
    { image: '🎁🎁', options: ['1','2','3'], answer: 1 },
    { image: '🎁🎁🎁', options: ['2','3','4'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁', options: ['4','5','6'], answer: 1 },
  ]}},
  { title: 'Kira 6 hingga 10', type: 'counting', emoji: '🔟', difficulty: 'easy', gameData: { questions: [
    { image: '🍎🍎🍎🍎🍎🍎', options: ['5','6','7'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎', options: ['6','7','8'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎', options: ['7','8','9'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['8','9','10'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['9','10','11'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊', options: ['5','6','7'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊', options: ['6','7','8'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊🍊', options: ['7','8','9'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊🍊🍊', options: ['8','9','10'], answer: 1 },
    { image: '🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊', options: ['9','10','11'], answer: 1 },
    { image: '🎈🎈🎈🎈🎈🎈', options: ['5','6','7'], answer: 1 },
    { image: '🎈🎈🎈🎈🎈🎈🎈', options: ['6','7','8'], answer: 1 },
    { image: '🎈🎈🎈🎈🎈🎈🎈🎈', options: ['7','8','9'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁', options: ['5','6','7'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁🎁', options: ['6','7','8'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁🎁🎁', options: ['7','8','9'], answer: 1 },
    { image: '🎁🎁🎁🎁🎁🎁🎁🎁🎁', options: ['8','9','10'], answer: 1 },
  ]}},
  { title: 'Nombor 1 hingga 10', type: 'number_match', emoji: '1️⃣', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐', options: ['1','2','3'], answer: 0 },
    { problem: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['1','2','3'], answer: 2 },
    { problem: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['4','5','6'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
    { problem: '🍎', options: ['1','2','3'], answer: 0 },
    { problem: '🍎🍎', options: ['1','2','3'], answer: 1 },
    { problem: '🍎🍎🍎', options: ['1','2','3'], answer: 2 },
    { problem: '🍎🍎🍎🍎', options: ['3','4','5'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎', options: ['4','5','6'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎', options: ['5','6','7'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎', options: ['6','7','8'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎🍎', options: ['7','8','9'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['8','9','10'], answer: 1 },
    { problem: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['9','10','11'], answer: 1 },
    { problem: '🍊', options: ['1','2','3'], answer: 0 },
    { problem: '🍊🍊🍊', options: ['2','3','4'], answer: 1 },
  ]}},
  { title: 'Tambah 1+1 hingga 5+5', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '1+1', options: ['3','2','4','1'], answer: 1 },
    { problem: '2+1', options: ['4','3','5','2'], answer: 1 },
    { problem: '1+2', options: ['4','3','5','2'], answer: 1 },
    { problem: '2+2', options: ['6','4','5','3'], answer: 1 },
    { problem: '3+1', options: ['6','4','5','2'], answer: 1 },
    { problem: '2+3', options: ['7','5','6','4'], answer: 1 },
    { problem: '4+1', options: ['7','5','6','4'], answer: 1 },
    { problem: '3+3', options: ['7','6','8','5'], answer: 1 },
    { problem: '1+3', options: ['5','4','3','2'], answer: 1 },
    { problem: '4+2', options: ['7','6','8','5'], answer: 1 },
    { problem: '1+4', options: ['6','5','4','3'], answer: 1 },
    { problem: '2+4', options: ['7','6','8','5'], answer: 1 },
    { problem: '3+2', options: ['6','5','4','3'], answer: 1 },
    { problem: '5+1', options: ['7','6','8','4'], answer: 1 },
    { problem: '1+5', options: ['7','6','8','4'], answer: 1 },
    { problem: '4+3', options: ['8','7','6','5'], answer: 1 },
    { problem: '2+5', options: ['8','7','6','4'], answer: 1 },
    { problem: '5+2', options: ['8','7','6','4'], answer: 1 },
    { problem: '3+4', options: ['8','7','6','5'], answer: 1 },
    { problem: '5+5', options: ['11','10','9','8'], answer: 1 },
  ]}},
  { title: 'Bentuk Geometri Mudah', type: 'shape_sort', emoji: '🔵', difficulty: 'easy', gameData: { questions: [
    { image: '⭕', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 0 },
    { image: '⬜', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 2 },
    { image: '▭', options: ['Segiempat Tepat','Segi Empat','Bujur'], answer: 0 },
    { image: '⭐', options: ['Bintang','Bulatan','Segi Tiga'], answer: 0 },
    { image: '🔶', options: ['Heksagon','Berlian','Segi Empat'], answer: 0 },
    { image: '🔷', options: ['Berlian','Bujur','Segi Tiga'], answer: 0 },
    { image: '🔴', options: ['Bulatan','Bola','Cakera'], answer: 1 },
    { image: '⭕', options: ['Bulatan','Segi Tiga','Berlian'], answer: 0 },
    { image: '△', options: ['Segi Empat','Segi Tiga','Bulatan'], answer: 1 },
    { image: '⬜', options: ['Segi Tiga','Segi Empat','Bulatan'], answer: 1 },
    { image: '🔷', options: ['Bulatan','Segi Tiga','Berlian'], answer: 2 },
    { image: '🔶', options: ['Bulatan','Segi Empat','Heksagon'], answer: 2 },
    { image: '⭐', options: ['Bulatan','Bintang','Segi Empat'], answer: 1 },
    { image: '🔵', options: ['Berlian','Bulatan','Segi Tiga'], answer: 1 },
    { image: '🟢', options: ['Segi Empat','Bulatan','Segi Tiga'], answer: 1 },
    { image: '▭', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Segi Empat','Bulatan','Segi Tiga'], answer: 2 },
    { image: '⬜', options: ['Segi Empat','Bulatan','Berlian'], answer: 0 },
    { image: '⭐', options: ['Segi Empat','Segi Tiga','Bintang'], answer: 2 },
  ]}},
  { title: 'Lebih Besar atau Lebih Kecil', type: 'math_puzzle', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: '3 atau 5?', options: ['3 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '7 atau 4?', options: ['7 lebih besar','4 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 2?', options: ['2 lebih besar','2 lebih kecil','Sama'], answer: 2 },
    { problem: '1 atau 9?', options: ['1 lebih besar','9 lebih besar','Sama'], answer: 1 },
    { problem: '6 atau 3?', options: ['6 lebih besar','3 lebih besar','Sama'], answer: 0 },
    { problem: '5 atau 8?', options: ['5 lebih besar','8 lebih besar','Sama'], answer: 1 },
    { problem: '4 atau 4?', options: ['4 lebih besar','4 lebih kecil','Sama'], answer: 2 },
    { problem: '10 atau 7?', options: ['10 lebih besar','7 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 8?', options: ['2 lebih besar','8 lebih besar','Sama'], answer: 1 },
    { problem: '9 atau 6?', options: ['9 lebih besar','6 lebih besar','Sama'], answer: 0 },
    { problem: '5 atau 5?', options: ['5 lebih besar','5 lebih kecil','Sama'], answer: 2 },
    { problem: '3 atau 1?', options: ['3 lebih besar','1 lebih besar','Sama'], answer: 0 },
    { problem: '4 atau 7?', options: ['4 lebih besar','7 lebih besar','Sama'], answer: 1 },
    { problem: '8 atau 8?', options: ['8 lebih besar','8 lebih kecil','Sama'], answer: 2 },
    { problem: '6 atau 9?', options: ['6 lebih besar','9 lebih besar','Sama'], answer: 1 },
    { problem: '10 atau 3?', options: ['10 lebih besar','3 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 5?', options: ['2 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '7 atau 7?', options: ['7 lebih besar','7 lebih kecil','Sama'], answer: 2 },
    { problem: '1 atau 5?', options: ['1 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '9 atau 9?', options: ['9 lebih besar','9 lebih kecil','Sama'], answer: 2 },
  ]}},
  { title: 'Tolak Mudah', type: 'math_puzzle', emoji: '➖', difficulty: 'easy', gameData: { questions: [
    { problem: '3-1', options: ['1','2','3','4'], answer: 1 },
    { problem: '5-2', options: ['2','3','4','5'], answer: 1 },
    { problem: '4-1', options: ['2','3','4','5'], answer: 1 },
    { problem: '6-3', options: ['2','3','4','5'], answer: 1 },
    { problem: '7-2', options: ['4','5','6','7'], answer: 1 },
    { problem: '8-4', options: ['3','4','5','6'], answer: 1 },
    { problem: '9-3', options: ['5','6','7','8'], answer: 1 },
    { problem: '10-5', options: ['4','5','6','7'], answer: 1 },
    { problem: '4-2', options: ['1','2','3','4'], answer: 1 },
    { problem: '6-1', options: ['4','5','6','7'], answer: 1 },
    { problem: '5-3', options: ['1','2','3','4'], answer: 1 },
    { problem: '8-2', options: ['5','6','7','8'], answer: 1 },
    { problem: '7-4', options: ['2','3','4','5'], answer: 1 },
    { problem: '5-1', options: ['3','4','5','6'], answer: 1 },
    { problem: '9-4', options: ['4','5','6','7'], answer: 1 },
    { problem: '6-2', options: ['3','4','5','6'], answer: 1 },
    { problem: '8-3', options: ['4','5','6','7'], answer: 1 },
    { problem: '7-3', options: ['3','4','5','6'], answer: 1 },
    { problem: '4-3', options: ['0','1','2','3'], answer: 1 },
    { problem: '10-6', options: ['3','4','5','6'], answer: 1 },
  ]}},
  { title: 'Susunan Nombor', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: 'Selepas 3 ialah?', options: ['2','4','5','3'], answer: 1 },
    { problem: 'Selepas 6 ialah?', options: ['5','7','8','6'], answer: 1 },
    { problem: 'Sebelum 5 ialah?', options: ['6','4','3','5'], answer: 1 },
    { problem: 'Sebelum 9 ialah?', options: ['10','8','7','9'], answer: 1 },
    { problem: 'Antara 4 dan 6?', options: ['3','5','7','4'], answer: 1 },
    { problem: 'Antara 1 dan 3?', options: ['0','2','4','1'], answer: 1 },
    { problem: 'Selepas 8 ialah?', options: ['7','9','10','8'], answer: 1 },
    { problem: 'Sebelum 2 ialah?', options: ['3','1','0','2'], answer: 1 },
    { problem: 'Selepas 1 ialah?', options: ['0','2','3','1'], answer: 1 },
    { problem: 'Selepas 7 ialah?', options: ['6','8','9','7'], answer: 1 },
    { problem: 'Sebelum 10 ialah?', options: ['11','9','8','10'], answer: 1 },
    { problem: 'Sebelum 4 ialah?', options: ['5','3','2','4'], answer: 1 },
    { problem: 'Antara 7 dan 9?', options: ['6','8','10','7'], answer: 1 },
    { problem: 'Antara 2 dan 4?', options: ['1','3','5','2'], answer: 1 },
    { problem: 'Selepas 4 ialah?', options: ['3','5','6','4'], answer: 1 },
    { problem: 'Selepas 9 ialah?', options: ['8','10','11','9'], answer: 1 },
    { problem: 'Sebelum 7 ialah?', options: ['8','6','5','7'], answer: 1 },
    { problem: 'Sebelum 3 ialah?', options: ['4','2','1','3'], answer: 1 },
    { problem: 'Antara 5 dan 7?', options: ['4','6','8','5'], answer: 1 },
    { problem: 'Antara 8 dan 10?', options: ['7','9','11','8'], answer: 1 },
  ]}},
  { title: 'Wang Syiling Kecil', type: 'counting', emoji: '💰', difficulty: 'medium', gameData: { questions: [
    { image: '🪙', options: ['10 sen','20 sen','50 sen'], answer: 0 },
    { image: '🪙🪙', options: ['10 sen','20 sen','30 sen'], answer: 1 },
    { image: '🪙🪙🪙', options: ['20 sen','30 sen','40 sen'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙', options: ['40 sen','50 sen','60 sen'], answer: 1 },
    { image: '💵', options: ['RM 1','RM 2','RM 5'], answer: 0 },
    { image: '💵💵', options: ['RM 1','RM 2','RM 3'], answer: 1 },
    { image: '💵💵💵', options: ['RM 2','RM 3','RM 4'], answer: 1 },
    { image: '💵💵💵💵💵', options: ['RM 4','RM 5','RM 6'], answer: 1 },
    { image: '🪙🪙🪙🪙', options: ['30 sen','40 sen','50 sen'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙🪙', options: ['50 sen','60 sen','70 sen'], answer: 1 },
    { image: '💵💵💵💵', options: ['RM 3','RM 4','RM 5'], answer: 1 },
    { image: '💵💵💵💵💵💵', options: ['RM 5','RM 6','RM 7'], answer: 1 },
    { image: '🪙', options: ['10 sen','20 sen','5 sen'], answer: 0 },
    { image: '🪙🪙🪙🪙🪙🪙🪙', options: ['60 sen','70 sen','80 sen'], answer: 1 },
    { image: '💵💵💵💵💵💵💵', options: ['RM 6','RM 7','RM 8'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙🪙🪙🪙', options: ['70 sen','80 sen','90 sen'], answer: 1 },
    { image: '💵💵💵💵💵💵💵💵', options: ['RM 7','RM 8','RM 9'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙🪙🪙🪙🪙', options: ['80 sen','90 sen','100 sen'], answer: 1 },
    { image: '💵💵💵💵💵💵💵💵💵', options: ['RM 8','RM 9','RM 10'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙🪙🪙🪙🪙🪙', options: ['90 sen','100 sen','110 sen'], answer: 1 },
  ]}},
  { title: 'Corak dan Urutan', type: 'pattern_fill', emoji: '🔷', difficulty: 'medium', gameData: { questions: [
    { problem: '🔴🔵🔴🔵?', options: ['🔴','🔵','🟢'], answer: 0 },
    { problem: '⭐🌙⭐🌙?', options: ['⭐','🌙','☀️'], answer: 0 },
    { problem: '1, 2, 3, ?', options: ['3','4','5'], answer: 1 },
    { problem: '2, 4, 6, ?', options: ['7','8','9'], answer: 1 },
    { problem: '🔺🔺🔵🔺🔺?', options: ['🔺','🔵','🔷'], answer: 1 },
    { problem: '5, 10, 15, ?', options: ['18','20','25'], answer: 1 },
    { problem: '🟡🟡🔴🟡🟡?', options: ['🟡','🔴','🔵'], answer: 1 },
    { problem: '1, 3, 5, ?', options: ['6','7','8'], answer: 1 },
    { problem: '🔵🔴🔵🔴?', options: ['🔵','🔴','🟢'], answer: 0 },
    { problem: '🌙⭐🌙⭐?', options: ['🌙','⭐','☀️'], answer: 0 },
    { problem: '2, 4, 6, 8, ?', options: ['9','10','11'], answer: 1 },
    { problem: '1, 4, 7, 10, ?', options: ['11','12','13'], answer: 1 },
    { problem: '🔴🔴🔵🔴🔴?', options: ['🔴','🔵','🟢'], answer: 1 },
    { problem: '3, 6, 9, ?', options: ['10','11','12'], answer: 1 },
    { problem: '🟢🟢🟡🟢🟢?', options: ['🟢','🟡','🔴'], answer: 1 },
    { problem: '2, 6, 10, ?', options: ['12','13','14'], answer: 1 },
    { problem: '1, 2, 2, 3, 3, 3, ?', options: ['3','4','5'], answer: 1 },
    { problem: '🔷🔷🔶🔷🔷?', options: ['🔷','🔶','⭐'], answer: 1 },
    { problem: '4, 8, 12, ?', options: ['14','15','16'], answer: 1 },
    { problem: '1, 5, 9, ?', options: ['12','13','14'], answer: 1 },
  ]}},
  { title: 'Nombor 11 hingga 20', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '11 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 0 },
    { problem: '12 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 1 },
    { problem: '15 biji epal', options: ['Empat Belas','Lima Belas','Enam Belas'], answer: 1 },
    { problem: '17 biji epal', options: ['Enam Belas','Tujuh Belas','Lapan Belas'], answer: 1 },
    { problem: '20 biji epal', options: ['Sembilan Belas','Dua Puluh','Dua Puluh Satu'], answer: 1 },
    { problem: 'Lima belas = ?', options: ['14','15','16'], answer: 1 },
    { problem: 'Dua belas = ?', options: ['11','12','13'], answer: 1 },
    { problem: 'Dua puluh = ?', options: ['19','20','21'], answer: 1 },
    { problem: '13 biji epal', options: ['Dua Belas','Tiga Belas','Empat Belas'], answer: 1 },
    { problem: '14 biji epal', options: ['Tiga Belas','Empat Belas','Lima Belas'], answer: 1 },
    { problem: '16 biji epal', options: ['Lima Belas','Enam Belas','Tujuh Belas'], answer: 1 },
    { problem: '18 biji epal', options: ['Tujuh Belas','Lapan Belas','Sembilan Belas'], answer: 1 },
    { problem: '19 biji epal', options: ['Lapan Belas','Sembilan Belas','Dua Puluh'], answer: 1 },
    { problem: 'Tiga belas = ?', options: ['12','13','14'], answer: 1 },
    { problem: 'Empat belas = ?', options: ['13','14','15'], answer: 1 },
    { problem: 'Enam belas = ?', options: ['15','16','17'], answer: 1 },
    { problem: 'Tujuh belas = ?', options: ['16','17','18'], answer: 1 },
    { problem: 'Lapan belas = ?', options: ['17','18','19'], answer: 1 },
    { problem: 'Sembilan belas = ?', options: ['18','19','20'], answer: 1 },
    { problem: 'Sebelas = ?', options: ['10','11','12'], answer: 1 },
  ]}},
  { title: 'Tambah hingga 10', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '4+5', options: ['7','9','8','10'], answer: 1 },
    { problem: '3+6', options: ['7','9','8','10'], answer: 1 },
    { problem: '5+4', options: ['7','9','8','10'], answer: 1 },
    { problem: '6+4', options: ['9','10','11','8'], answer: 1 },
    { problem: '7+3', options: ['9','10','11','8'], answer: 1 },
    { problem: '8+2', options: ['9','10','11','8'], answer: 1 },
    { problem: '5+5', options: ['9','10','11','8'], answer: 1 },
    { problem: '3+7', options: ['9','10','11','8'], answer: 1 },
    { problem: '2+8', options: ['8','9','10','11'], answer: 1 },
    { problem: '1+9', options: ['8','9','10','11'], answer: 1 },
    { problem: '6+3', options: ['8','9','10','11'], answer: 1 },
    { problem: '4+6', options: ['8','9','10','11'], answer: 1 },
    { problem: '2+7', options: ['8','9','10','11'], answer: 1 },
    { problem: '7+2', options: ['8','9','10','11'], answer: 1 },
    { problem: '8+1', options: ['8','9','10','11'], answer: 1 },
    { problem: '1+8', options: ['8','9','10','11'], answer: 1 },
    { problem: '9+1', options: ['9','10','11','12'], answer: 1 },
    { problem: '6+2', options: ['7','8','9','10'], answer: 1 },
    { problem: '2+6', options: ['7','8','9','10'], answer: 1 },
    { problem: '5+3', options: ['7','8','9','10'], answer: 1 },
  ]}},
  { title: 'Pasangan Nombor Sama', type: 'number_match', emoji: '🎯', difficulty: 'easy', gameData: { questions: [
    { problem: 'Lima = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Tiga = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Lapan = ?', options: ['7','8','9'], answer: 1 },
    { problem: 'Satu = ?', options: ['1','2','3'], answer: 0 },
    { problem: 'Sepuluh = ?', options: ['8','9','10'], answer: 2 },
    { problem: 'Dua = ?', options: ['1','2','3'], answer: 1 },
    { problem: 'Tujuh = ?', options: ['6','7','8'], answer: 1 },
    { problem: 'Sembilan = ?', options: ['8','9','10'], answer: 1 },
    { problem: 'Empat = ?', options: ['3','4','5'], answer: 1 },
    { problem: 'Enam = ?', options: ['5','6','7'], answer: 1 },
    { problem: 'Sifar = ?', options: ['0','1','2'], answer: 0 },
    { problem: 'Sembilan = ?', options: ['8','9','10'], answer: 1 },
    { problem: 'Satu = ?', options: ['0','1','2'], answer: 1 },
    { problem: 'Tiga = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Enam = ?', options: ['5','6','7'], answer: 1 },
    { problem: 'Lapan = ?', options: ['7','8','9'], answer: 1 },
    { problem: 'Dua = ?', options: ['1','2','3'], answer: 1 },
    { problem: 'Empat = ?', options: ['3','4','5'], answer: 1 },
    { problem: 'Sepuluh = ?', options: ['9','10','11'], answer: 1 },
    { problem: 'Tujuh = ?', options: ['6','7','8'], answer: 1 },
  ]}},
  { title: 'Bahagi Mudah', type: 'math_puzzle', emoji: '➗', difficulty: 'medium', gameData: { questions: [
    { problem: '4÷2', options: ['1','2','3'], answer: 1 },
    { problem: '6÷2', options: ['2','3','4'], answer: 1 },
    { problem: '6÷3', options: ['1','2','3'], answer: 2 },
    { problem: '8÷2', options: ['3','4','5'], answer: 1 },
    { problem: '10÷2', options: ['4','5','6'], answer: 1 },
    { problem: '9÷3', options: ['2','3','4'], answer: 1 },
    { problem: '4÷4', options: ['1','2','3'], answer: 0 },
    { problem: '10÷5', options: ['1','2','3'], answer: 1 },
    { problem: '8÷4', options: ['1','2','3'], answer: 1 },
    { problem: '12÷2', options: ['5','6','7'], answer: 1 },
    { problem: '12÷3', options: ['3','4','5'], answer: 1 },
    { problem: '12÷4', options: ['2','3','4'], answer: 1 },
    { problem: '15÷3', options: ['4','5','6'], answer: 1 },
    { problem: '16÷2', options: ['7','8','9'], answer: 1 },
    { problem: '18÷2', options: ['8','9','10'], answer: 1 },
    { problem: '20÷2', options: ['9','10','11'], answer: 1 },
    { problem: '20÷4', options: ['4','5','6'], answer: 1 },
    { problem: '2÷2', options: ['0','1','2'], answer: 1 },
    { problem: '14÷2', options: ['6','7','8'], answer: 1 },
    { problem: '16÷4', options: ['3','4','5'], answer: 1 },
  ]}},
  { title: 'Masa - Jam', type: 'multiple_choice', emoji: '⏰', difficulty: 'easy', gameData: { questions: [
    { problem: '1 jam = berapa minit?', options: ['30','60','100'], answer: 1 },
    { problem: 'Pagi bermula pada?', options: ['12 malam','12 tengahari','6 pagi'], answer: 2 },
    { problem: 'Tengahari pada pukul?', options: ['10 pagi','12 tengahari','2 petang'], answer: 1 },
    { problem: 'Malam bermula selepas?', options: ['Pagi','Tengahari','Petang'], answer: 2 },
    { problem: 'Separuh jam = berapa minit?', options: ['15','30','45'], answer: 1 },
    { problem: '1 hari = berapa jam?', options: ['12','24','48'], answer: 1 },
    { problem: 'Pukul 3 petang - 2 jam kemudian?', options: ['Pukul 4','Pukul 5','Pukul 6'], answer: 1 },
    { problem: 'Subuh adalah waktu?', options: ['Malam','Awal pagi','Petang'], answer: 1 },
    { problem: 'Suku jam = berapa minit?', options: ['10','15','20'], answer: 1 },
    { problem: 'Pukul 10 pagi - 1 jam kemudian?', options: ['Pukul 10','Pukul 11','Pukul 12'], answer: 1 },
    { problem: '2 jam = berapa minit?', options: ['90','120','150'], answer: 1 },
    { problem: 'Petang bermula pada?', options: ['12 siang','2 petang','6 petang'], answer: 1 },
    { problem: '3 jam = berapa minit?', options: ['150','180','210'], answer: 1 },
    { problem: 'Pukul 1 malam - berapa jam seterusnya pukul 4 pagi?', options: ['2','3','4'], answer: 1 },
    { problem: '30 minit + 30 minit = ?', options: ['30 minit','1 jam','1.5 jam'], answer: 1 },
    { problem: 'Pukul 6 pagi + 3 jam = ?', options: ['Pukul 8 pagi','Pukul 9 pagi','Pukul 7 pagi'], answer: 1 },
    { problem: '1 minggu = berapa hari?', options: ['5','7','10'], answer: 1 },
    { problem: '1 bulan kira-kira berapa minggu?', options: ['2','3','4'], answer: 1 },
    { problem: 'Pukul 12 malam juga dipanggil?', options: ['Tengahari','Tengah malam','Petang'], answer: 1 },
    { problem: 'Pukul 12 siang juga dipanggil?', options: ['Pagi','Tengahari','Petang'], answer: 1 },
  ]}},
  { title: 'Darab Mudah ×2 dan ×5', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', gameData: { questions: [
    { problem: '2×2', options: ['2','4','6'], answer: 1 },
    { problem: '2×3', options: ['4','6','8'], answer: 1 },
    { problem: '2×4', options: ['6','8','10'], answer: 1 },
    { problem: '2×5', options: ['8','10','12'], answer: 1 },
    { problem: '5×1', options: ['4','5','6'], answer: 1 },
    { problem: '5×2', options: ['8','10','12'], answer: 1 },
    { problem: '5×3', options: ['13','15','17'], answer: 1 },
    { problem: '5×4', options: ['18','20','22'], answer: 1 },
    { problem: '2×1', options: ['1','2','3'], answer: 1 },
    { problem: '2×6', options: ['10','12','14'], answer: 1 },
    { problem: '2×7', options: ['12','14','16'], answer: 1 },
    { problem: '2×8', options: ['14','16','18'], answer: 1 },
    { problem: '5×5', options: ['20','25','30'], answer: 1 },
    { problem: '5×6', options: ['28','30','32'], answer: 1 },
    { problem: '2×9', options: ['16','18','20'], answer: 1 },
    { problem: '2×10', options: ['18','20','22'], answer: 1 },
    { problem: '5×7', options: ['32','35','38'], answer: 1 },
    { problem: '5×8', options: ['38','40','42'], answer: 1 },
    { problem: '5×9', options: ['42','45','48'], answer: 1 },
    { problem: '5×10', options: ['48','50','52'], answer: 1 },
  ]}},
  { title: 'Ukuran - Panjang Pendek', type: 'multiple_choice', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: 'Mana lebih panjang?', options: ['Pensel','Pembaris','Sama'], answer: 1 },
    { problem: 'Mana lebih pendek?', options: ['Jari','Tangan','Sama'], answer: 0 },
    { problem: 'Mana lebih tinggi?', options: ['Kerusi','Meja','Sama'], answer: 1 },
    { problem: 'Mana lebih rendah?', options: ['Semut','Gajah','Sama'], answer: 0 },
    { problem: 'Mana lebih besar?', options: ['Kucing','Singa','Sama'], answer: 1 },
    { problem: 'Mana lebih kecil?', options: ['Gajah','Tikus','Sama'], answer: 1 },
    { problem: 'Mana lebih berat?', options: ['Buku','Pensel','Sama'], answer: 0 },
    { problem: 'Mana lebih ringan?', options: ['Batu','Bulu','Sama'], answer: 1 },
    { problem: 'Tali atau dawai - mana lebih panjang?', options: ['Tali','Dawai','Sama'], answer: 0 },
    { problem: 'Pokok atau rumah - mana lebih tinggi?', options: ['Pokok','Rumah','Sama'], answer: 1 },
    { problem: 'Tali penerjemah atau tali kasut - mana lebih panjang?', options: ['Tali penerjemah','Tali kasut','Sama'], answer: 0 },
    { problem: 'Meja atau kerusi - mana lebih tinggi?', options: ['Meja','Kerusi','Sama'], answer: 0 },
    { problem: 'Pensil atau pensel - mana lebih pendek?', options: ['Pensil','Pensel','Sama'], answer: 0 },
    { problem: 'Jalan atau lorong - mana lebih panjang?', options: ['Jalan','Lorong','Sama'], answer: 0 },
    { problem: 'Buku tebal atau buku nipis - mana lebih tebal?', options: ['Buku tebal','Buku nipis','Sama'], answer: 0 },
    { problem: 'Kepala atau badan - mana lebih kecil?', options: ['Kepala','Badan','Sama'], answer: 0 },
    { problem: 'Rumah besar atau rumah kecil - mana lebih besar?', options: ['Rumah besar','Rumah kecil','Sama'], answer: 0 },
    { problem: 'Benang atau tali - mana lebih halus?', options: ['Benang','Tali','Sama'], answer: 0 },
    { problem: 'Lautan atau tasik - mana lebih luas?', options: ['Lautan','Tasik','Sama'], answer: 0 },
    { problem: 'Masjid atau rumah - mana lebih besar?', options: ['Masjid','Rumah','Sama'], answer: 0 },
  ]}},
  { title: 'Nombor Ganjil dan Genap', type: 'multiple_choice', emoji: '🔢', difficulty: 'medium', gameData: { questions: [
    { problem: '2 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '3 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '4 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '7 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '10 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '5 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '8 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '1 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '6 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '9 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '11 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '12 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '13 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '14 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '15 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '16 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '17 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '18 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '19 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '20 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
  ]}},
  { title: 'Tolak hingga 20', type: 'math_puzzle', emoji: '➖', difficulty: 'medium', gameData: { questions: [
    { problem: '10-6', options: ['3','4','5'], answer: 1 },
    { problem: '12-5', options: ['6','7','8'], answer: 1 },
    { problem: '15-8', options: ['6','7','8'], answer: 1 },
    { problem: '18-9', options: ['8','9','10'], answer: 1 },
    { problem: '20-10', options: ['9','10','11'], answer: 1 },
    { problem: '14-7', options: ['6','7','8'], answer: 1 },
    { problem: '16-8', options: ['7','8','9'], answer: 1 },
    { problem: '11-4', options: ['6','7','8'], answer: 1 },
    { problem: '13-6', options: ['6','7','8'], answer: 1 },
    { problem: '17-9', options: ['7','8','9'], answer: 1 },
    { problem: '19-10', options: ['8','9','10'], answer: 1 },
    { problem: '11-5', options: ['5','6','7'], answer: 1 },
    { problem: '13-7', options: ['5','6','7'], answer: 1 },
    { problem: '15-7', options: ['7','8','9'], answer: 1 },
    { problem: '17-8', options: ['8','9','10'], answer: 1 },
    { problem: '19-9', options: ['9','10','11'], answer: 1 },
    { problem: '12-6', options: ['5','6','7'], answer: 1 },
    { problem: '14-8', options: ['5','6','7'], answer: 1 },
    { problem: '16-7', options: ['8','9','10'], answer: 1 },
    { problem: '18-10', options: ['7','8','9'], answer: 1 },
  ]}},
  { title: 'Berat - Ringan Berat', type: 'multiple_choice', emoji: '⚖️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Gajah atau semut — mana lebih berat?', options: ['Semut','Gajah','Sama'], answer: 1 },
    { problem: 'Batu atau kapas — mana lebih ringan?', options: ['Batu','Kapas','Sama'], answer: 1 },
    { problem: '1 kg atau 2 kg — mana lebih berat?', options: ['1 kg','2 kg','Sama'], answer: 1 },
    { problem: 'Kereta atau basikal — mana lebih berat?', options: ['Kereta','Basikal','Sama'], answer: 0 },
    { problem: 'Buku atau pensel — mana lebih berat?', options: ['Pensel','Buku','Sama'], answer: 1 },
    { problem: '500g atau 1kg — mana lebih ringan?', options: ['500g','1kg','Sama'], answer: 0 },
    { problem: 'Kamus atau buku cerita — mana lebih berat?', options: ['Buku cerita','Kamus','Sama'], answer: 1 },
    { problem: 'Cikgu atau murid — mana lebih berat biasanya?', options: ['Murid','Cikgu','Sama'], answer: 1 },
    { problem: 'Bola emas atau bola busa - mana lebih berat?', options: ['Bola emas','Bola busa','Sama'], answer: 0 },
    { problem: 'Tepung atau gula - mana lebih berat dalam jumlah sama?', options: ['Tepung','Gula','Sama'], answer: 1 },
    { problem: 'Air atau minyak - mana lebih berat dalam jumlah sama?', options: ['Air','Minyak','Sama'], answer: 0 },
    { problem: 'Bola pingpong atau bola boling - mana lebih berat?', options: ['Bola pingpong','Bola boling','Sama'], answer: 1 },
    { problem: 'Plastik atau besi - mana lebih berat?', options: ['Plastik','Besi','Sama'], answer: 1 },
    { problem: 'Kertas atau logam - mana lebih berat?', options: ['Kertas','Logam','Sama'], answer: 1 },
    { problem: 'Buih atau pasir - mana lebih berat dalam kuantiti sama?', options: ['Buih','Pasir','Sama'], answer: 1 },
    { problem: 'Tembaga atau emas - mana lebih berat dalam saiz sama?', options: ['Tembaga','Emas','Sama'], answer: 1 },
    { problem: 'Kayu atau batu - mana lebih berat?', options: ['Kayu','Batu','Sama'], answer: 1 },
    { problem: 'Bola beracun atau bola karet - mana lebih berat?', options: ['Bola beracun','Bola karet','Sama'], answer: 0 },
    { problem: 'Bulu atau logam - mana lebih ringan?', options: ['Bulu','Logam','Sama'], answer: 0 },
    { problem: 'Ais atau air - mana lebih berat dalam jumlah sama?', options: ['Ais','Air','Sama'], answer: 1 },
  ]}},
  { title: 'Tambah hingga 20', type: 'math_puzzle', emoji: '➕', difficulty: 'medium', gameData: { questions: [
    { problem: '8+5', options: ['11','13','12'], answer: 1 },
    { problem: '9+6', options: ['14','15','16'], answer: 1 },
    { problem: '7+8', options: ['14','15','16'], answer: 1 },
    { problem: '6+7', options: ['12','13','14'], answer: 1 },
    { problem: '9+9', options: ['17','18','19'], answer: 1 },
    { problem: '8+8', options: ['15','16','17'], answer: 1 },
    { problem: '7+7', options: ['13','14','15'], answer: 1 },
    { problem: '9+8', options: ['16','17','18'], answer: 1 },
    { problem: '7+9', options: ['15','16','17'], answer: 1 },
    { problem: '6+8', options: ['13','14','15'], answer: 1 },
    { problem: '6+9', options: ['14','15','16'], answer: 1 },
    { problem: '7+6', options: ['12','13','14'], answer: 1 },
    { problem: '8+9', options: ['16','17','18'], answer: 1 },
    { problem: '5+9', options: ['13','14','15'], answer: 1 },
    { problem: '8+7', options: ['14','15','16'], answer: 1 },
    { problem: '9+7', options: ['15','16','17'], answer: 1 },
    { problem: '5+8', options: ['12','13','14'], answer: 1 },
    { problem: '6+6', options: ['11','12','13'], answer: 1 },
    { problem: '9+5', options: ['13','14','15'], answer: 1 },
    { problem: '8+6', options: ['13','14','15'], answer: 1 },
  ]}},
  { title: 'Darab ×3 dan ×4', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', gameData: { questions: [
    { problem: '3×2', options: ['4','6','8'], answer: 1 },
    { problem: '3×3', options: ['6','9','12'], answer: 1 },
    { problem: '3×4', options: ['10','12','14'], answer: 1 },
    { problem: '3×5', options: ['13','15','17'], answer: 1 },
    { problem: '4×2', options: ['6','8','10'], answer: 1 },
    { problem: '4×3', options: ['10','12','14'], answer: 1 },
    { problem: '4×4', options: ['14','16','18'], answer: 1 },
    { problem: '4×5', options: ['18','20','22'], answer: 1 },
    { problem: '3×1', options: ['2','3','4'], answer: 1 },
    { problem: '3×6', options: ['16','18','20'], answer: 1 },
    { problem: '3×7', options: ['19','21','23'], answer: 1 },
    { problem: '3×8', options: ['22','24','26'], answer: 1 },
    { problem: '4×1', options: ['3','4','5'], answer: 1 },
    { problem: '4×6', options: ['22','24','26'], answer: 1 },
    { problem: '4×7', options: ['26','28','30'], answer: 1 },
    { problem: '4×8', options: ['30','32','34'], answer: 1 },
    { problem: '3×9', options: ['25','27','29'], answer: 1 },
    { problem: '3×10', options: ['28','30','32'], answer: 1 },
    { problem: '4×9', options: ['34','36','38'], answer: 1 },
    { problem: '4×10', options: ['38','40','42'], answer: 1 },
  ]}},
  { title: 'Nombor 21 hingga 50', type: 'number_match', emoji: '🔢', difficulty: 'medium', gameData: { questions: [
    { problem: '21 = ?', options: ['Dua Puluh','Dua Puluh Satu','Dua Puluh Dua'], answer: 1 },
    { problem: '30 = ?', options: ['Dua Puluh','Tiga Puluh','Empat Puluh'], answer: 1 },
    { problem: '35 = ?', options: ['Tiga Puluh Lima','Empat Puluh Lima','Lima Puluh'], answer: 0 },
    { problem: '40 = ?', options: ['Tiga Puluh','Empat Puluh','Lima Puluh'], answer: 1 },
    { problem: '45 = ?', options: ['Empat Puluh','Empat Puluh Lima','Lima Puluh'], answer: 1 },
    { problem: '50 = ?', options: ['Empat Puluh','Lima Puluh','Enam Puluh'], answer: 1 },
    { problem: 'Tiga puluh satu = ?', options: ['30','31','32'], answer: 1 },
    { problem: 'Empat puluh dua = ?', options: ['41','42','43'], answer: 1 },
    { problem: '22 = ?', options: ['Dua Puluh Satu','Dua Puluh Dua','Dua Puluh Tiga'], answer: 1 },
    { problem: '25 = ?', options: ['Dua Puluh Empat','Dua Puluh Lima','Dua Puluh Enam'], answer: 1 },
    { problem: '32 = ?', options: ['Tiga Puluh Satu','Tiga Puluh Dua','Tiga Puluh Tiga'], answer: 1 },
    { problem: '38 = ?', options: ['Tiga Puluh Tujuh','Tiga Puluh Lapan','Tiga Puluh Sembilan'], answer: 1 },
    { problem: '41 = ?', options: ['Empat Puluh','Empat Puluh Satu','Empat Puluh Dua'], answer: 1 },
    { problem: '48 = ?', options: ['Empat Puluh Tujuh','Empat Puluh Lapan','Empat Puluh Sembilan'], answer: 1 },
    { problem: 'Dua puluh dua = ?', options: ['20','21','22'], answer: 2 },
    { problem: 'Tiga puluh tiga = ?', options: ['32','33','34'], answer: 1 },
    { problem: 'Empat puluh empat = ?', options: ['42','43','44'], answer: 2 },
    { problem: 'Lima puluh = ?', options: ['49','50','51'], answer: 1 },
    { problem: '29 = ?', options: ['Dua Puluh Lapan','Dua Puluh Sembilan','Tiga Puluh'], answer: 1 },
    { problem: '44 = ?', options: ['Empat Puluh Tiga','Empat Puluh Empat','Empat Puluh Lima'], answer: 1 },
  ]}},
  { title: 'Pecahan Mudah', type: 'math_puzzle', emoji: '🍕', difficulty: 'medium', gameData: { questions: [
    { problem: '1/2 bermaksud?', options: ['1 bahagian dari 3','Separuh','Satu pertiga'], answer: 1 },
    { problem: '1/4 bermaksud?', options: ['Separuh','Satu pertiga','Satu perempat'], answer: 2 },
    { problem: 'Pizza dibahagi 2 sama — tiap bahagian?', options: ['1/3','1/2','1/4'], answer: 1 },
    { problem: 'Kek dibahagi 4 — tiap bahagian?', options: ['1/2','1/3','1/4'], answer: 2 },
    { problem: '1/2 + 1/2 = ?', options: ['1/2','1','2'], answer: 1 },
    { problem: 'Mana lebih besar?', options: ['1/4','1/2','Sama'], answer: 1 },
    { problem: '3/4 bermaksud berapa bahagian dari 4?', options: ['2','3','4'], answer: 1 },
    { problem: 'Satu penuh = berapa separuh?', options: ['1','2','3'], answer: 1 },
    { problem: '1/3 bermaksud?', options: ['Separuh','Satu pertiga','Satu perempat'], answer: 1 },
    { problem: '2/4 = ?', options: ['1/4','1/2','3/4'], answer: 1 },
    { problem: 'Separuh dari separuh = ?', options: ['1/4','1/2','1'], answer: 0 },
    { problem: '1/2 + 1/4 = ?', options: ['1/4','1/2','3/4'], answer: 2 },
    { problem: 'Buah dibahagi 3 — tiap bahagian?', options: ['1/2','1/3','1/4'], answer: 1 },
    { problem: 'Mana lebih kecil - 1/3 atau 1/2?', options: ['1/3','1/2','Sama'], answer: 0 },
    { problem: '1/4 + 1/4 = ?', options: ['1/4','1/2','1'], answer: 1 },
    { problem: 'Mana lebih besar - 2/4 atau 3/4?', options: ['2/4','3/4','Sama'], answer: 1 },
    { problem: 'Tali dibahagi 2 — tiap bahagian?', options: ['1/2','1/3','1/4'], answer: 0 },
    { problem: '1/2 - 1/4 = ?', options: ['0','1/4','1/2'], answer: 1 },
    { problem: '4/4 = ?', options: ['Separuh','Satu','Satu setengah'], answer: 1 },
    { problem: 'Mana paling kecil - 1/4, 1/3, 1/2?', options: ['1/4','1/3','1/2'], answer: 0 },
  ]}},
  { title: 'Isipadu — Penuh dan Kosong', type: 'multiple_choice', emoji: '🥛', difficulty: 'easy', gameData: { questions: [
    { problem: 'Botol penuh — ada lebih atau kurang air?', options: ['Kurang','Lebih','Tiada'], answer: 1 },
    { problem: 'Botol kosong — ada berapa air?', options: ['Banyak','Sedikit','Tiada'], answer: 2 },
    { problem: 'Mana yang boleh tampung lebih air?', options: ['Sudu','Baldi','Cawan'], answer: 1 },
    { problem: '1 liter = berapa mililiter (ml)?', options: ['100','500','1000'], answer: 2 },
    { problem: 'Kurang dari separuh penuh bermaksud?', options: ['Hampir penuh','Hampir kosong','Penuh'], answer: 1 },
    { problem: 'Mana muat lebih banyak?', options: ['Cawan kecil','Tong besar','Sama'], answer: 1 },
    { problem: 'Jika tuang air dari baldi besar ke baldi kecil?', options: ['Muat semua','Melimpah','Tiada perubahan'], answer: 1 },
    { problem: 'Cara ukur isipadu cecair?', options: ['Timbang','Ukur panjang','Guna cawan ukur'], answer: 2 },
    { problem: 'Separuh penuh bermaksud?', options: ['Hampir kosong','Separuh','Hampir penuh'], answer: 1 },
    { problem: 'Cawan atau botol - mana muat lebih banyak?', options: ['Cawan','Botol','Sama'], answer: 1 },
    { problem: 'Sudu atau cawan - mana muat lebih sedikit?', options: ['Sudu','Cawan','Sama'], answer: 0 },
    { problem: '500 ml = ?', options: ['Lebih daripada 1 liter','Separuh liter','Sama dengan 1 liter'], answer: 1 },
    { problem: 'Bekas yang penuh dengan air atau bekas setengah penuh?', options: ['Penuh ada lebih banyak','Setengah penuh ada lebih banyak','Sama'], answer: 0 },
    { problem: '2 liter = berapa ml?', options: ['1000','2000','3000'], answer: 1 },
    { problem: 'Gelas atau jug - mana lebih besar?', options: ['Gelas','Jug','Sama'], answer: 1 },
    { problem: 'Satu perempat penuh bermaksud?', options: ['25%','50%','75%'], answer: 0 },
    { problem: 'Tiga perempat penuh bermaksud?', options: ['25%','50%','75%'], answer: 2 },
    { problem: 'Jika ada 2 liter air dalam bekas 5 liter, berapa yang kosong?', options: ['2 liter','3 liter','4 liter'], answer: 1 },
    { problem: 'Jika tuang 500ml + 500ml air?', options: ['Setengah liter','1 liter','1.5 liter'], answer: 1 },
    { problem: 'Bekas A muat 1 liter, bekas B muat 2 liter. Bekas mana lebih besar?', options: ['A','B','Sama'], answer: 1 },
  ]}},
  { title: 'Tolak hingga 50', type: 'math_puzzle', emoji: '➖', difficulty: 'medium', gameData: { questions: [
    { problem: '20-8', options: ['10','12','14'], answer: 1 },
    { problem: '25-10', options: ['13','15','17'], answer: 1 },
    { problem: '30-15', options: ['13','15','17'], answer: 1 },
    { problem: '40-20', options: ['18','20','22'], answer: 1 },
    { problem: '35-15', options: ['18','20','22'], answer: 1 },
    { problem: '50-25', options: ['23','25','27'], answer: 1 },
    { problem: '28-14', options: ['12','14','16'], answer: 1 },
    { problem: '45-30', options: ['13','15','17'], answer: 1 },
    { problem: '22-11', options: ['10','11','12'], answer: 1 },
    { problem: '33-12', options: ['19','21','23'], answer: 1 },
    { problem: '42-20', options: ['20','22','24'], answer: 1 },
    { problem: '38-18', options: ['18','20','22'], answer: 1 },
    { problem: '48-24', options: ['22','24','26'], answer: 1 },
    { problem: '31-15', options: ['14','16','18'], answer: 1 },
    { problem: '44-22', options: ['20','22','24'], answer: 1 },
    { problem: '36-18', options: ['16','18','20'], answer: 1 },
    { problem: '50-30', options: ['18','20','22'], answer: 1 },
    { problem: '26-13', options: ['11','13','15'], answer: 1 },
    { problem: '41-20', options: ['18','20','22'], answer: 1 },
    { problem: '39-19', options: ['18','20','22'], answer: 1 },
  ]}},
  { title: 'Jadual Waktu', type: 'multiple_choice', emoji: '⏰', difficulty: 'medium', gameData: { questions: [
    { problem: 'Kamu bangun pagi pukul 6. 1 jam kemudian?', options: ['Pukul 6','Pukul 7','Pukul 8'], answer: 1 },
    { problem: 'Sekolah bermula pukul 7:30. 30 minit sebelum?', options: ['Pukul 6:30','Pukul 7:00','Pukul 7:30'], answer: 1 },
    { problem: 'Rehat pukul 10:00. 15 minit kemudian?', options: ['Pukul 10:05','Pukul 10:15','Pukul 10:30'], answer: 1 },
    { problem: '1 minit = berapa saat?', options: ['30','60','100'], answer: 1 },
    { problem: '1 jam = berapa saat?', options: ['600','3600','600'], answer: 1 },
    { problem: 'Tengahari ke petang = berapa jam?', options: ['2','3','4'], answer: 1 },
    { problem: 'Pagi ke malam = berapa jam kira-kira?', options: ['6','12','8'], answer: 1 },
    { problem: '1 minggu = berapa hari?', options: ['5','6','7'], answer: 2 },
    { problem: 'Berehat pada pukul 3 petang. 2 jam kemudian pulang?', options: ['Pukul 4','Pukul 5','Pukul 6'], answer: 1 },
    { problem: 'Makan tengahari pukul 12. Makan malam pukul 7. Berapa jam selisih?', options: ['5','6','7'], answer: 1 },
    { problem: 'Bantai pukul 8 pagi, selesai pukul 3 petang. Berapa lama?', options: ['6','7','8'], answer: 0 },
    { problem: 'Perjalanan 2 jam, pergi pukul 9 pagi. Sampai pukul?', options: ['10','11','12'], answer: 1 },
    { problem: 'Tidur pukul 10 malam, bangun pukul 7 pagi. Berapa jam tidur?', options: ['8','9','10'], answer: 1 },
    { problem: '2 minggu = berapa hari?', options: ['12','13','14'], answer: 2 },
    { problem: '1 tahun = berapa minggu kira-kira?', options: ['48','50','52'], answer: 2 },
    { problem: 'Pukul 2 sore + 3 jam = ?', options: ['Pukul 4','Pukul 5','Pukul 6'], answer: 1 },
    { problem: '30 minit + 30 minit = ?', options: ['30 minit','1 jam','1.5 jam'], answer: 1 },
    { problem: 'Pukul 8 malam sekarang. Dalam 4 jam akan pukul?', options: ['12 malam','1 pagi','2 pagi'], answer: 0 },
    { problem: '3 jam 45 minit = berapa minit?', options: ['195','225','245'], answer: 1 },
    { problem: 'Dari Isnin ke Jumaat = berapa hari?', options: ['3','4','5'], answer: 1 },
  ]}},
  { title: 'Wang — Duit Syiling dan Nota', type: 'counting', emoji: '💰', difficulty: 'medium', gameData: { questions: [
    { image: '🪙🪙🪙🪙🪙', options: ['40 sen','50 sen','60 sen'], answer: 1 },
    { image: '💵', options: ['RM 1','RM 2','RM 5'], answer: 0 },
    { image: '💵💵', options: ['RM 1','RM 2','RM 3'], answer: 1 },
    { image: '💵💵💵💵💵', options: ['RM 4','RM 5','RM 6'], answer: 1 },
    { image: '🪙×10', options: ['RM 1','RM 2','RM 3'], answer: 0 },
    { image: '💵+🪙🪙', options: ['RM 1.10','RM 1.20','RM 2.10'], answer: 1 },
    { image: '💵💵+🪙🪙🪙', options: ['RM 2.20','RM 2.30','RM 3.30'], answer: 1 },
    { image: '💵💵💵+🪙×5', options: ['RM 3.40','RM 3.50','RM 4.50'], answer: 1 },
    { image: '🪙🪙🪙🪙', options: ['30 sen','40 sen','50 sen'], answer: 1 },
    { image: '💵💵💵💵', options: ['RM 3','RM 4','RM 5'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙🪙', options: ['50 sen','60 sen','70 sen'], answer: 1 },
    { image: '💵💵💵💵💵💵', options: ['RM 5','RM 6','RM 7'], answer: 1 },
    { image: '💵+🪙', options: ['RM 1.05','RM 1.10','RM 1.20'], answer: 1 },
    { image: '💵💵+🪙🪙', options: ['RM 2.10','RM 2.20','RM 2.30'], answer: 1 },
    { image: '🪙×20', options: ['RM 1.50','RM 2.00','RM 2.50'], answer: 1 },
    { image: '💵💵💵+🪙', options: ['RM 3.05','RM 3.10','RM 3.20'], answer: 1 },
    { image: '💵+🪙🪙🪙', options: ['RM 1.25','RM 1.30','RM 1.35'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙🪙🪙🪙', options: ['70 sen','80 sen','90 sen'], answer: 1 },
    { image: '💵💵💵💵💵💵💵', options: ['RM 6','RM 7','RM 8'], answer: 1 },
    { image: '💵💵💵💵💵💵💵💵', options: ['RM 7','RM 8','RM 9'], answer: 1 },
  ]}},
  { title: 'Geometri — Sisi dan Bucu', type: 'shape_sort', emoji: '📐', difficulty: 'medium', gameData: { questions: [
    { image: '△', options: ['2 sisi','3 sisi','4 sisi'], answer: 1 },
    { image: '⬜', options: ['3 sisi','4 sisi','5 sisi'], answer: 1 },
    { image: '⭕', options: ['0 sisi','1 sisi','2 sisi'], answer: 0 },
    { image: '▭', options: ['3 sisi','4 sisi','5 sisi'], answer: 1 },
    { image: '⭐', options: ['4 mata','5 mata','6 mata'], answer: 1 },
    { problem: 'Segi enam mempunyai berapa sisi?', options: ['5','6','7'], answer: 1 },
    { problem: 'Segi tiga mempunyai berapa bucu?', options: ['2','3','4'], answer: 1 },
    { problem: 'Segi empat sama mempunyai berapa sisi sama panjang?', options: ['2','3','4'], answer: 2 },
    { image: '🔷', options: ['3 sisi','4 sisi','5 sisi'], answer: 1 },
    { problem: 'Bulatan mempunyai berapa bucu?', options: ['0','1','2'], answer: 0 },
    { problem: 'Pentagon mempunyai berapa sisi?', options: ['4','5','6'], answer: 1 },
    { problem: 'Segi empat tepat mempunyai berapa sisi?', options: ['2','3','4'], answer: 2 },
    { problem: 'Heptagon mempunyai berapa sisi?', options: ['6','7','8'], answer: 1 },
    { problem: 'Oktagon mempunyai berapa sisi?', options: ['7','8','9'], answer: 1 },
    { problem: 'Segi tiga mempunyai berapa sisi sama panjang dalam sama sisi?', options: ['1','2','3'], answer: 2 },
    { image: '⭐', options: ['5 bucu','6 bucu','7 bucu'], answer: 0 },
    { problem: 'Segi empat tepat mempunyai berapa bucu?', options: ['2','3','4'], answer: 2 },
    { problem: 'Trapezium mempunyai berapa sisi?', options: ['3','4','5'], answer: 1 },
    { problem: 'Segi lima (Pentagon) mempunyai berapa bucu?', options: ['4','5','6'], answer: 1 },
    { problem: 'Segi enam (Heksagon) mempunyai berapa bucu?', options: ['5','6','7'], answer: 1 },
  ]}},
  { title: 'Nombor 51 hingga 100', type: 'number_match', emoji: '💯', difficulty: 'medium', gameData: { questions: [
    { problem: '60 = ?', options: ['Lima Puluh','Enam Puluh','Tujuh Puluh'], answer: 1 },
    { problem: '75 = ?', options: ['Tujuh Puluh Lima','Lapan Puluh Lima','Sembilan Puluh Lima'], answer: 0 },
    { problem: '80 = ?', options: ['Tujuh Puluh','Lapan Puluh','Sembilan Puluh'], answer: 1 },
    { problem: '100 = ?', options: ['Sembilan Puluh','Seratus','Satu Ratus Satu'], answer: 1 },
    { problem: 'Lima puluh = ?', options: ['40','50','60'], answer: 1 },
    { problem: 'Sembilan puluh = ?', options: ['80','90','100'], answer: 1 },
    { problem: 'Tujuh puluh lima = ?', options: ['65','75','85'], answer: 1 },
    { problem: 'Enam puluh enam = ?', options: ['56','66','76'], answer: 1 },
    { problem: '55 = ?', options: ['Lima Puluh Empat','Lima Puluh Lima','Lima Puluh Enam'], answer: 1 },
    { problem: '68 = ?', options: ['Enam Puluh Tujuh','Enam Puluh Lapan','Enam Puluh Sembilan'], answer: 1 },
    { problem: '90 = ?', options: ['Lapan Puluh','Sembilan Puluh','Seratus'], answer: 1 },
    { problem: '72 = ?', options: ['Tujuh Puluh Satu','Tujuh Puluh Dua','Tujuh Puluh Tiga'], answer: 1 },
    { problem: '85 = ?', options: ['Lapan Puluh Empat','Lapan Puluh Lima','Lapan Puluh Enam'], answer: 1 },
    { problem: '99 = ?', options: ['Sembilan Puluh Lapan','Sembilan Puluh Sembilan','Seratus'], answer: 1 },
    { problem: 'Enam puluh = ?', options: ['59','60','61'], answer: 1 },
    { problem: 'Tujuh puluh = ?', options: ['69','70','71'], answer: 1 },
    { problem: 'Lapan puluh = ?', options: ['79','80','81'], answer: 1 },
    { problem: 'Empat puluh lima = ?', options: ['44','45','46'], answer: 1 },
    { problem: 'Lima puluh lima = ?', options: ['54','55','56'], answer: 1 },
    { problem: 'Enam puluh enam = ?', options: ['65','66','67'], answer: 1 },
  ]}},
  { title: 'Tambah Tiga Digit Mudah', type: 'math_puzzle', emoji: '➕', difficulty: 'medium', gameData: { questions: [
    { problem: '50+30', options: ['70','80','90'], answer: 0 },
    { problem: '40+40', options: ['70','80','90'], answer: 1 },
    { problem: '60+20', options: ['70','80','90'], answer: 0 },
    { problem: '30+50', options: ['70','80','90'], answer: 0 },
    { problem: '25+25', options: ['40','50','60'], answer: 1 },
    { problem: '45+5', options: ['50','60','70'], answer: 0 },
    { problem: '35+15', options: ['45','50','55'], answer: 1 },
    { problem: '20+20+20', options: ['50','60','70'], answer: 1 },
    { problem: '30+30', options: ['50','60','70'], answer: 1 },
    { problem: '40+20', options: ['50','60','70'], answer: 1 },
    { problem: '25+35', options: ['50','60','70'], answer: 1 },
    { problem: '15+35', options: ['45','50','55'], answer: 1 },
    { problem: '50+40', options: ['80','90','100'], answer: 0 },
    { problem: '60+30', options: ['80','90','100'], answer: 1 },
    { problem: '70+20', options: ['80','90','100'], answer: 0 },
    { problem: '55+25', options: ['75','80','85'], answer: 1 },
    { problem: '48+12', options: ['55','60','65'], answer: 1 },
    { problem: '33+27', options: ['55','60','65'], answer: 1 },
    { problem: '44+26', options: ['65','70','75'], answer: 1 },
    { problem: '52+28', options: ['75','80','85'], answer: 1 },
  ]}},
  { title: 'Tolak Tiga Digit Mudah', type: 'math_puzzle', emoji: '➖', difficulty: 'medium', gameData: { questions: [
    { problem: '50-20', options: ['20','30','40'], answer: 1 },
    { problem: '80-30', options: ['40','50','60'], answer: 1 },
    { problem: '100-50', options: ['40','50','60'], answer: 1 },
    { problem: '70-40', options: ['20','30','40'], answer: 1 },
    { problem: '60-15', options: ['35','40','45'], answer: 2 },
    { problem: '90-30', options: ['50','60','70'], answer: 1 },
    { problem: '55-5', options: ['40','50','60'], answer: 1 },
    { problem: '75-25', options: ['40','50','60'], answer: 1 },
    { problem: '60-20', options: ['30','40','50'], answer: 1 },
    { problem: '70-30', options: ['30','40','50'], answer: 1 },
    { problem: '80-20', options: ['50','60','70'], answer: 1 },
    { problem: '85-35', options: ['45','50','55'], answer: 1 },
    { problem: '95-45', options: ['45','50','55'], answer: 1 },
    { problem: '100-40', options: ['55','60','65'], answer: 1 },
    { problem: '88-38', options: ['45','50','55'], answer: 1 },
    { problem: '72-22', options: ['45','50','55'], answer: 1 },
    { problem: '65-25', options: ['35','40','45'], answer: 1 },
    { problem: '92-42', options: ['45','50','55'], answer: 1 },
    { problem: '78-28', options: ['45','50','55'], answer: 1 },
    { problem: '50-10', options: ['35','40','45'], answer: 1 },
  ]}},
  { title: 'Darab ×6 dan ×7', type: 'math_puzzle', emoji: '✖️', difficulty: 'hard', gameData: { questions: [
    { problem: '6×2', options: ['10','12','14'], answer: 1 },
    { problem: '6×3', options: ['15','18','21'], answer: 1 },
    { problem: '6×4', options: ['20','24','28'], answer: 1 },
    { problem: '6×5', options: ['28','30','35'], answer: 1 },
    { problem: '7×2', options: ['12','14','16'], answer: 1 },
    { problem: '7×3', options: ['18','21','24'], answer: 1 },
    { problem: '7×4', options: ['24','28','32'], answer: 1 },
    { problem: '7×5', options: ['30','35','40'], answer: 1 },
    { problem: '6×1', options: ['5','6','7'], answer: 1 },
    { problem: '6×6', options: ['34','36','38'], answer: 1 },
    { problem: '6×7', options: ['40','42','44'], answer: 1 },
    { problem: '6×8', options: ['46','48','50'], answer: 1 },
    { problem: '6×9', options: ['52','54','56'], answer: 1 },
    { problem: '6×10', options: ['58','60','62'], answer: 1 },
    { problem: '7×1', options: ['6','7','8'], answer: 1 },
    { problem: '7×6', options: ['40','42','44'], answer: 1 },
    { problem: '7×7', options: ['46','48','49'], answer: 2 },
    { problem: '7×8', options: ['54','56','58'], answer: 1 },
    { problem: '7×9', options: ['61','63','65'], answer: 1 },
    { problem: '7×10', options: ['68','70','72'], answer: 1 },
  ]}},
  { title: 'Pecahan - Separuh dan Satu Perempat', type: 'math_puzzle', emoji: '🍕', difficulty: 'hard', gameData: { questions: [
    { problem: 'Pizza dibahagi 2 - tiap bahagian?', options: ['1/3','1/2','1/4'], answer: 1 },
    { problem: '1/2 sama dengan?', options: ['25%','50%','75%'], answer: 1 },
    { problem: 'Separuh dari 10?', options: ['3','5','7'], answer: 1 },
    { problem: 'Satu perempat dari 20?', options: ['3','5','7'], answer: 1 },
    { problem: '1/2 + 1/2 = ?', options: ['1/2','1','2'], answer: 1 },
    { problem: 'Kek dibahagi 4 - tiap bahagian?', options: ['1/2','1/3','1/4'], answer: 2 },
    { problem: 'Mana lebih besar - 1/2 atau 1/4?', options: ['1/4','1/2','Sama'], answer: 1 },
    { problem: '3/4 bermaksud berapa bahagian dari 4?', options: ['2','3','4'], answer: 1 },
    { problem: 'Separuh dari 16?', options: ['6','8','10'], answer: 1 },
    { problem: 'Satu perempat dari 16?', options: ['3','4','5'], answer: 1 },
    { problem: '1/4 + 1/4 = ?', options: ['1/4','1/2','3/4'], answer: 1 },
    { problem: '2/4 = ?', options: ['1/4','1/2','3/4'], answer: 1 },
    { problem: 'Separuh dari 12?', options: ['5','6','7'], answer: 1 },
    { problem: 'Satu perempat dari 12?', options: ['2','3','4'], answer: 1 },
    { problem: '3/4 sama dengan?', options: ['50%','65%','75%'], answer: 2 },
    { problem: '1/4 sama dengan?', options: ['20%','25%','30%'], answer: 1 },
    { problem: '1/2 + 1/4 = ?', options: ['1/4','1/2','3/4'], answer: 2 },
    { problem: 'Satu penuh = berapa perempat?', options: ['2','3','4'], answer: 2 },
    { problem: 'Separuh dari 8?', options: ['3','4','5'], answer: 1 },
    { problem: '3/4 + 1/4 = ?', options: ['1/2','3/4','1'], answer: 2 },
  ]}},
  { title: 'Perbandingan - Lebih Berat Lebih Ringan', type: 'multiple_choice', emoji: '⚖️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Gajah atau semut - siapa lebih berat?', options: ['Semut','Gajah','Sama'], answer: 1 },
    { problem: 'Kapas atau besi - siapa lebih ringan?', options: ['Besi','Kapas','Sama'], answer: 1 },
    { problem: '1 kg atau 500g - mana lebih berat?', options: ['500g','1 kg','Sama'], answer: 1 },
    { problem: 'Buku atau pensel - mana lebih berat?', options: ['Pensel','Buku','Sama'], answer: 1 },
    { problem: 'Baldi air penuh atau kosong - mana lebih berat?', options: ['Kosong','Penuh','Sama'], answer: 1 },
    { problem: 'Bulu ayam atau batu - siapa lebih ringan?', options: ['Batu','Bulu','Sama'], answer: 1 },
    { problem: 'Kamus tebal atau buku nipis - mana lebih berat?', options: ['Buku Nipis','Kamus','Sama'], answer: 1 },
    { problem: 'Kapal atau mainan kapal - mana lebih berat?', options: ['Mainan','Kapal Sebenar','Sama'], answer: 1 },
    { problem: 'Seribu gram atau 1 kilogram - sama berat?', options: ['Berbeza','Sama','Seribu gram lebih berat'], answer: 1 },
    { problem: 'Bom atau balon - mana lebih berat?', options: ['Balon','Bom','Sama'], answer: 1 },
    { problem: 'Besi atau kayu - siapa lebih berat untuk saiz sama?', options: ['Kayu','Besi','Sama'], answer: 1 },
    { problem: 'Ekor atau kepala kucing - mana lebih berat?', options: ['Ekor','Kepala','Sama'], answer: 1 },
    { problem: 'Bapa atau anak - siapa biasanya lebih berat?', options: ['Anak','Bapa','Sama'], answer: 1 },
    { problem: 'Paku atau jarum - mana lebih berat?', options: ['Jarum','Paku','Sama'], answer: 1 },
    { problem: 'Payung atau basah - mana lebih berat?', options: ['Payung','Basah','Sama'], answer: 0 },
    { problem: 'Mangga atau anggur - mana biasanya lebih berat?', options: ['Anggur','Mangga','Sama'], answer: 1 },
    { problem: 'Surat atau buku - mana lebih berat?', options: ['Surat','Buku','Sama'], answer: 1 },
    { problem: 'Kertas atau logam untuk saiz sama?', options: ['Kertas','Logam','Sama'], answer: 1 },
    { problem: 'Telur atau keajaiban - mana lebih berat?', options: ['Keajaiban','Telur','Sama'], answer: 1 },
    { problem: 'Emas atau perak untuk saiz sama - mana lebih berat?', options: ['Perak','Emas','Sama'], answer: 1 },
  ]}},
  { title: 'Ukuran Panjang Pendek Tinggi Rendah', type: 'multiple_choice', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: 'Pensel atau pembaris - mana lebih panjang?', options: ['Pensel','Pembaris','Sama'], answer: 1 },
    { problem: 'Jari atau tangan - mana lebih panjang?', options: ['Jari','Tangan','Sama'], answer: 1 },
    { problem: 'Kerusi atau meja - mana lebih tinggi?', options: ['Kerusi','Meja','Sama'], answer: 1 },
    { problem: 'Semut atau gajah - mana lebih tinggi?', options: ['Semut','Gajah','Sama'], answer: 1 },
    { problem: 'Kucing atau singa - mana lebih besar?', options: ['Kucing','Singa','Sama'], answer: 1 },
    { problem: 'Gajah atau tikus - mana lebih besar?', options: ['Tikus','Gajah','Sama'], answer: 1 },
    { problem: 'Kayu atau benang - mana lebih keras?', options: ['Benang','Kayu','Sama'], answer: 1 },
    { problem: 'Kapas atau batu - mana lebih lembut?', options: ['Batu','Kapas','Sama'], answer: 1 },
    { problem: 'Tali panjang atau tali pendek?', options: ['Panjang','Pendek','Sama'], answer: 0 },
    { problem: 'Pokok tinggi atau rumah tinggi - mana biasanya lebih tinggi?', options: ['Pokok','Rumah','Sama'], answer: 0 },
    { problem: 'Ular panjang atau tali panjang - mana biasanya lebih panjang?', options: ['Ular','Tali','Sama'], answer: 1 },
    { problem: 'Bola besar atau bola kecil - mana lebih besar?', options: ['Besar','Kecil','Sama'], answer: 0 },
    { problem: 'Jalan lebar atau jalan sempit - mana lebih lebar?', options: ['Lebar','Sempit','Sama'], answer: 0 },
    { problem: 'Rumah besar atau rumah kecil - mana lebih besar?', options: ['Besar','Kecil','Sama'], answer: 0 },
    { problem: 'Rambut panjang atau rambut pendek - mana lebih panjang?', options: ['Panjang','Pendek','Sama'], answer: 0 },
    { problem: 'Buku tebal atau buku nipis - mana lebih tebal?', options: ['Tebal','Nipis','Sama'], answer: 0 },
    { problem: 'Pensil panjang atau pensil pendek - mana lebih panjang?', options: ['Panjang','Pendek','Sama'], answer: 0 },
    { problem: 'Kaki panjang atau kaki pendek - mana lebih panjang?', options: ['Panjang','Pendek','Sama'], answer: 0 },
    { problem: 'Lorong panjang atau lorong pendek - mana lebih panjang?', options: ['Panjang','Pendek','Sama'], answer: 0 },
    { problem: 'Bendera tinggi atau bendera rendah - mana lebih tinggi?', options: ['Tinggi','Rendah','Sama'], answer: 0 },
  ]}},
  { title: 'Bentuk 3D - Kubus Sfera Silinder', type: 'shape_sort', emoji: '3️⃣', difficulty: 'hard', gameData: { questions: [
    { image: '⬜', options: ['Kubus','Sfera','Silinder'], answer: 0 },
    { image: '🔵', options: ['Kubus','Sfera','Silinder'], answer: 1 },
    { image: '🥫', options: ['Kubus','Sfera','Silinder'], answer: 2 },
    { image: '🎁', options: ['Kubus','Sfera','Piramid'], answer: 0 },
    { image: '🏀', options: ['Kubus','Sfera','Silinder'], answer: 1 },
    { image: '🍌', options: ['Silinder Bengkok','Silinder','Sfera'], answer: 0 },
    { image: '📦', options: ['Kubus','Sfera','Piramid'], answer: 0 },
    { image: '🎯', options: ['Sfera','Kubus','Silinder'], answer: 0 },
    { image: '🎲', options: ['Kubus','Sfera','Silinder'], answer: 0 },
    { image: '🏈', options: ['Kubus','Sfera','Elipsoid'], answer: 2 },
    { image: '🎺', options: ['Kubus','Sfera','Silinder'], answer: 2 },
    { image: '🍎', options: ['Kubus','Sfera','Silinder'], answer: 1 },
    { image: '🎈', options: ['Kubus','Sfera','Silinder'], answer: 1 },
    { problem: 'Kubus mempunyai berapa muka?', options: ['4','5','6'], answer: 2 },
    { problem: 'Sfera mempunyai berapa muka rata?', options: ['0','1','2'], answer: 0 },
    { problem: 'Silinder mempunyai berapa muka?', options: ['2','3','4'], answer: 1 },
    { problem: 'Kon mempunyai berapa muka?', options: ['1','2','3'], answer: 1 },
    { problem: 'Kubus mempunyai berapa bucu?', options: ['6','8','10'], answer: 1 },
    { problem: 'Piramid tapak persegi mempunyai berapa bucu?', options: ['4','5','6'], answer: 1 },
    { problem: 'Silinder mempunyai berapa bucu?', options: ['0','2','4'], answer: 0 },
  ]}},
  { title: 'Waktu - Pagi Siang Malam', type: 'multiple_choice', emoji: '🕐', difficulty: 'easy', gameData: { questions: [
    { problem: 'Pagi adalah waktu?', options: ['6 pagi - 12 tengahari','12 tengahari - 6 petang','6 petang - 6 pagi'], answer: 0 },
    { problem: 'Siang adalah waktu?', options: ['Pagi Awal','Tengah Hari','Petang Akhir'], answer: 1 },
    { problem: 'Malam adalah waktu?', options: ['Awal Pagi','Petang Akhir - Pagi','Tengah Hari'], answer: 1 },
    { problem: 'Sekolah bermula pagi - jam berapa?', options: ['7:30','12:30','19:30'], answer: 0 },
    { problem: 'Makan tengahari pada?', options: ['Pagi','Tengah Hari','Malam'], answer: 1 },
    { problem: 'Tidur malam pada?', options: ['9 pagi','9 malam','9 petang'], answer: 1 },
    { problem: 'Berapa jam dari pagi ke malam?', options: ['8','12','24'], answer: 1 },
    { problem: 'Satu hari = ?', options: ['12 jam','24 jam','36 jam'], answer: 1 },
    { problem: 'Awal pagi bermula pada?', options: ['3 pagi','6 pagi','9 pagi'], answer: 1 },
    { problem: 'Sore bermula pada?', options: ['12 tengahari','3 petang','6 petang'], answer: 1 },
    { problem: 'Malam bermula pada?', options: ['6 petang','9 malam','12 malam'], answer: 0 },
    { problem: 'Tengah malam adalah jam?', options: ['10 malam','12 malam','1 pagi'], answer: 1 },
    { problem: 'Fajar terjadi apabila?', options: ['Matahari terbit','Matahari terbenam','Tengah malam'], answer: 0 },
    { problem: 'Senja terjadi apabila?', options: ['Matahari terbit','Matahari terbenam','Tengah siang'], answer: 1 },
    { problem: 'Pukul 13:00 adalah jam?', options: ['1 pagi','1 petang','Tengah malam'], answer: 1 },
    { problem: 'Pukul 14:00 adalah jam?', options: ['2 pagi','2 petang','Tengah malam'], answer: 1 },
    { problem: 'Pukul 22:00 adalah jam?', options: ['10 pagi','10 petang','10 malam'], answer: 2 },
    { problem: 'Pukul 23:00 adalah jam?', options: ['11 pagi','11 petang','11 malam'], answer: 2 },
    { problem: 'Subuh adalah waktu?', options: ['Pagi awal','Siang','Malam'], answer: 0 },
    { problem: 'Dhuha adalah waktu?', options: ['Pagi tua','Siang','Malam'], answer: 0 },
  ]}},
  ];