export const prasekolah_bahasa_mandarin_expansion = [
  { title: '数字 1 到 10 - 扩展', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐', options: ['一', '二', '三'], answer: 0 },
    { problem: '⭐⭐', options: ['一', '二', '三'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['二', '三', '四'], answer: 1 },
    { problem: '⭐⭐⭐⭐', options: ['三', '四', '五'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['四', '五', '六'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['五', '六', '七'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['六', '七', '八'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['七', '八', '九'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['八', '九', '十'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['九', '十', '十一'], answer: 1 },
    { problem: '一 = ?', options: ['1', '2', '3'], answer: 0 },
    { problem: '二 = ?', options: ['1', '2', '3'], answer: 1 },
    { problem: '三 = ?', options: ['2', '3', '4'], answer: 1 },
    { problem: '四 = ?', options: ['3', '4', '5'], answer: 1 },
    { problem: '五 = ?', options: ['4', '5', '6'], answer: 1 },
    { problem: '六 = ?', options: ['5', '6', '7'], answer: 1 },
    { problem: '七 = ?', options: ['6', '7', '8'], answer: 1 },
    { problem: '八 = ?', options: ['7', '8', '9'], answer: 1 },
    { problem: '九 = ?', options: ['8', '9', '10'], answer: 1 },
    { problem: '十 = ?', options: ['9', '10', '11'], answer: 1 },
  ]}},
  { title: '颜色词汇 - 扩展', type: 'picture_quiz', emoji: '🌈', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['红色', '蓝色', '绿色'], answer: 0 },
    { image: '🔵', options: ['红色', '蓝色', '黄色'], answer: 1 },
    { image: '🟢', options: ['紫色', '绿色', '橙色'], answer: 1 },
    { image: '🟡', options: ['黄色', '橙色', '白色'], answer: 0 },
    { image: '🟠', options: ['黄色', '橙色', '红色'], answer: 1 },
    { image: '💜', options: ['紫色', '粉红色', '蓝色'], answer: 0 },
    { image: '🤎', options: ['黑色', '棕色', '灰色'], answer: 1 },
    { image: '⚪', options: ['白色', '黑色', '灰色'], answer: 0 },
    { image: '⚫', options: ['白色', '黑色', '棕色'], answer: 1 },
    { image: '💚', options: ['蓝色', '绿色', '黄色'], answer: 1 },
    { image: '💙', options: ['蓝色', '绿色', '紫色'], answer: 0 },
    { image: '❤️', options: ['黄色', '红色', '绿色'], answer: 1 },
    { image: '💛', options: ['黄色', '橙色', '白色'], answer: 0 },
    { image: '🌈', options: ['白色', '彩虹', '黑色'], answer: 1 },
    { image: '☀️', options: ['红色', '黄色', '蓝色'], answer: 1 },
    { image: '🌿', options: ['棕色', '绿色', '黄色'], answer: 1 },
    { image: '🌊', options: ['棕色', '绿色', '蓝色'], answer: 2 },
    { image: '🍎', options: ['黄色', '红色', '蓝色'], answer: 1 },
    { image: '🍌', options: ['黄色', '红色', '绿色'], answer: 0 },
    { image: '🍇', options: ['红色', '紫色', '棕色'], answer: 1 },
  ]}},
  { title: '动物词汇 - 扩展', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['猫', '狗', '兔子'], answer: 0 },
    { image: '🐶', options: ['猫', '狗', '鸟'], answer: 1 },
    { image: '🦁', options: ['狮子', '老虎', '熊'], answer: 0 },
    { image: '🐯', options: ['狮子', '老虎', '豹'], answer: 1 },
    { image: '🐘', options: ['大象', '马', '斑马'], answer: 0 },
    { image: '🦒', options: ['骆驼', '长颈鹿', '鹿'], answer: 1 },
    { image: '🐻', options: ['熊', '狼', '狐狸'], answer: 0 },
    { image: '🐧', options: ['企鹅', '鸡', '鸭子'], answer: 0 },
    { image: '🦅', options: ['乌鸦', '鹰', '麻雀'], answer: 1 },
    { image: '🐍', options: ['乌龟', '鳄鱼', '蛇'], answer: 2 },
    { image: '🐢', options: ['乌龟', '鳄鱼', '蛇'], answer: 0 },
    { image: '🦋', options: ['蜜蜂', '苍蝇', '蝴蝶'], answer: 2 },
    { image: '🐝', options: ['蜜蜂', '苍蝇', '蝴蝶'], answer: 0 },
    { image: '🐸', options: ['青蛙', '乌龟', '蛇'], answer: 0 },
    { image: '🦓', options: ['马', '斑马', '驴子'], answer: 1 },
    { image: '🦊', options: ['狗', '狐狸', '狼'], answer: 1 },
    { image: '🐰', options: ['兔子', '松鼠', '老鼠'], answer: 0 },
    { image: '🐔', options: ['鸭子', '鸡', '鹅'], answer: 1 },
    { image: '🐄', options: ['牛', '马', '羊'], answer: 0 },
    { image: '🐑', options: ['牛', '马', '羊'], answer: 2 },
  ]}},
  { title: '水果和蔬菜 - 扩展', type: 'picture_quiz', emoji: '🍎', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['苹果', '橙子', '香蕉'], answer: 0 },
    { image: '🍊', options: ['苹果', '橙子', '芒果'], answer: 1 },
    { image: '🍌', options: ['香蕉', '木瓜', '芒果'], answer: 0 },
    { image: '🍇', options: ['葡萄', '草莓', '樱桃'], answer: 0 },
    { image: '🍓', options: ['葡萄', '草莓', '苹果'], answer: 1 },
    { image: '🍉', options: ['西瓜', '木瓜', '芒果'], answer: 0 },
    { image: '🥭', options: ['木瓜', '芒果', '榴莲'], answer: 1 },
    { image: '🥕', options: ['胡萝卜', '西红柿', '洋葱'], answer: 0 },
    { image: '🍅', options: ['胡萝卜', '西红柿', '木瓜'], answer: 1 },
    { image: '🥦', options: ['西蓝花', '卷心菜', '菠菜'], answer: 0 },
    { image: '🌽', options: ['玉米', '黄瓜', '南瓜'], answer: 0 },
    { image: '🥒', options: ['黄瓜', '胡萝卜', '南瓜'], answer: 0 },
    { image: '🧅', options: ['洋葱', '土豆', '姜'], answer: 0 },
    { image: '🥔', options: ['红薯', '土豆', '胡萝卜'], answer: 1 },
    { image: '🌶️', options: ['辣椒', '西红柿', '胡萝卜'], answer: 0 },
    { image: '🍋', options: ['柠檬', '橙子', '苹果'], answer: 0 },
    { image: '🍍', options: ['菠萝', '芒果', '香蕉'], answer: 0 },
    { image: '🍒', options: ['樱桃', '葡萄', '草莓'], answer: 0 },
    { image: '🥝', options: ['奇异果', '苹果', '葡萄'], answer: 0 },
    { image: '🍑', options: ['芒果', '桃子', '橙子'], answer: 1 },
  ]}},
  { title: '家庭成员 - 扩展', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['爸爸', '妈妈', '哥哥'], answer: 0 },
    { image: '👩', options: ['爸爸', '妈妈', '姐姐'], answer: 1 },
    { image: '👦', options: ['哥哥', '弟弟', '爷爷'], answer: 1 },
    { image: '👧', options: ['姐姐', '奶奶', '妈妈'], answer: 0 },
    { image: '👴', options: ['爸爸', '爷爷', '叔叔'], answer: 1 },
    { image: '👵', options: ['妈妈', '奶奶', '姑姑'], answer: 1 },
    { image: '👶', options: ['宝宝', '孩子', '大人'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['朋友', '家庭', '班级'], answer: 1 },
    { image: '👫', options: ['朋友', '家庭', '婚姻'], answer: 0 },
    { image: '👨‍👩‍👧‍👦', options: ['学校', '家庭', '人群'], answer: 1 },
    { image: '👴', options: ['爸爸', '爷爷', '叔叔'], answer: 1 },
    { image: '👵', options: ['妈妈', '奶奶', '阿姨'], answer: 1 },
    { image: '👶', options: ['弟弟', '哥哥', '宝宝'], answer: 2 },
    { image: '👧', options: ['女儿', '女孩', '都可以'], answer: 2 },
    { image: '👦', options: ['儿子', '男孩', '都可以'], answer: 2 },
    { image: '👨', options: ['爸爸', '叔叔', '都可以'], answer: 2 },
    { image: '👩', options: ['妈妈', '阿姨', '都可以'], answer: 2 },
    { image: '💑', options: ['家庭', '夫妻', '朋友'], answer: 1 },
    { image: '👨‍👦', options: ['爸爸和儿子', '兄弟', '朋友'], answer: 0 },
    { image: '👩‍👧', options: ['妈妈和女儿', '姐妹', '朋友'], answer: 0 },
  ]}},
  { title: '日常活动 - 扩展', type: 'picture_quiz', emoji: '⏰', difficulty: 'easy', gameData: { questions: [
    { image: '😴', options: ['睡觉', '洗澡', '吃饭'], answer: 0 },
    { image: '🍳', options: ['洗澡', '吃饭', '玩耍'], answer: 1 },
    { image: '🚿', options: ['洗澡', '睡觉', '吃饭'], answer: 0 },
    { image: '🎒', options: ['上学', '睡觉', '玩耍'], answer: 0 },
    { image: '✏️', options: ['玩耍', '学习写字', '吃饭'], answer: 1 },
    { image: '🏃', options: ['玩耍', '睡觉', '学习'], answer: 0 },
    { image: '📚', options: ['睡觉', '学习', '玩耍'], answer: 1 },
    { image: '🛏️', options: ['洗澡', '玩耍', '睡觉'], answer: 2 },
    { image: '🧼', options: ['饭前洗手', '睡前', '上学前'], answer: 0 },
    { image: '🪥', options: ['早上', '晚上', '两次都要'], answer: 2 },
    { image: '🍚', options: ['米饭', '面条', '包子'], answer: 0 },
    { image: '☕', options: ['茶', '咖啡', '牛奶'], answer: 1 },
    { image: '📖', options: ['玩耍', '阅读', '吃饭'], answer: 1 },
    { image: '🎮', options: ['玩游戏', '学习', '睡觉'], answer: 0 },
    { image: '🚌', options: ['上学', '回家', '都可以'], answer: 2 },
    { image: '👗', options: ['洗澡', '穿衣服', '吃饭'], answer: 1 },
    { image: '🌙', options: ['早上', '下午', '晚上'], answer: 2 },
    { image: '☀️', options: ['早上', '下午', '晚上'], answer: 0 },
    { image: '🌆', options: ['早上', '下午', '晚上'], answer: 1 },
    { image: '🙏', options: ['吵架', '打招呼', '玩耍'], answer: 1 },
  ]}},
  { title: '基本问候语 - 扩展', type: 'multiple_choice', emoji: '👋', difficulty: 'easy', gameData: { questions: [
    { problem: '早上的问候?', options: ['晚安', '早上好', '晚上好'], answer: 1 },
    { problem: '下午的问候?', options: ['早上好', '下午好', '晚上好'], answer: 1 },
    { problem: '晚上的问候?', options: ['下午好', '晚上好', '早上好'], answer: 1 },
    { problem: '睡前的问候?', options: ['晚安', '早上好', '再见'], answer: 0 },
    { problem: '离开时说什么?', options: ['你好', '再见', '请'], answer: 1 },
    { problem: '感谢别人说什么?', options: ['对不起', '谢谢', '你好'], answer: 1 },
    { problem: '道歉说什么?', options: ['谢谢', '对不起', '再见'], answer: 1 },
    { problem: '初次见面说什么?', options: ['再见', '你好', '晚安'], answer: 1 },
    { problem: '"谢谢"的回答?', options: ['对不起', '不客气', '再见'], answer: 1 },
    { problem: '问别人名字怎么说?', options: ['你叫什么名字？', '你在哪里？', '你吃饭了吗？'], answer: 0 },
    { problem: '问别人好不好怎么问?', options: ['你叫什么？', '你好吗？', '你在哪里？'], answer: 1 },
    { problem: '"你好吗"的回答?', options: ['我很好', '我在这里', '我叫...'], answer: 0 },
    { problem: '请求帮忙说什么?', options: ['给我！', '请帮帮我', '我要'], answer: 1 },
    { problem: '礼貌请求用什么词?', options: ['给我', '请', '拿来'], answer: 1 },
    { problem: '同意说什么?', options: ['不', '好的', '也许'], answer: 1 },
    { problem: '不同意说什么?', options: ['是', '不是', '也许'], answer: 1 },
    { problem: '祝贺时说什么?', options: ['辛苦了', '恭喜', '对不起'], answer: 1 },
    { problem: '生日时说什么?', options: ['再见', '生日快乐', '新年快乐'], answer: 1 },
    { problem: '新年时说什么?', options: ['生日快乐', '新年快乐', '晚安'], answer: 1 },
    { problem: '询问时间怎么说?', options: ['现在几点？', '你在哪里？', '今天几号？'], answer: 0 },
  ]}},
  { title: '形状和大小 - 扩展', type: 'picture_quiz', emoji: '🔵', difficulty: 'easy', gameData: { questions: [
    { image: '⭕', options: ['圆形', '方形', '三角形'], answer: 0 },
    { image: '⬜', options: ['圆形', '方形', '三角形'], answer: 1 },
    { image: '△', options: ['圆形', '方形', '三角形'], answer: 2 },
    { image: '▭', options: ['长方形', '方形', '椭圆形'], answer: 0 },
    { image: '⭐', options: ['星形', '圆形', '菱形'], answer: 0 },
    { image: '🔶', options: ['菱形', '六边形', '方形'], answer: 0 },
    { image: '🔷', options: ['菱形', '椭圆形', '三角形'], answer: 0 },
    { image: '🔵', options: ['方形', '圆形', '三角形'], answer: 1 },
    { problem: '大的反义词是?', options: ['小', '长', '高'], answer: 0 },
    { problem: '长的反义词是?', options: ['宽', '短', '细'], answer: 1 },
    { problem: '高的反义词是?', options: ['矮', '胖', '细'], answer: 0 },
    { problem: '胖的反义词是?', options: ['高', '瘦', '大'], answer: 1 },
    { problem: '圆形有几条边?', options: ['0', '1', '2'], answer: 0 },
    { problem: '三角形有几条边?', options: ['2', '3', '4'], answer: 1 },
    { problem: '方形有几条边?', options: ['3', '4', '5'], answer: 1 },
    { problem: '哪个更大 - 大象还是猫?', options: ['猫', '大象', '一样'], answer: 1 },
    { problem: '哪个更小 - 蚂蚁还是鸟?', options: ['蚂蚁', '鸟', '一样'], answer: 0 },
    { problem: '哪个更长 - 铅笔还是直尺?', options: ['铅笔', '直尺', '一样'], answer: 1 },
    { problem: '哪个更高 - 树还是草?', options: ['草', '树', '一样'], answer: 1 },
    { problem: '哪个更重 - 石头还是棉花?', options: ['石头', '棉花', '一样'], answer: 0 },
  ]}},
  { title: '基础汉字 - 扩展', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: '人', options: ['人', '大', '小', '山'], answer: 0 },
    { letter: '大', options: ['人', '大', '小', '山'], answer: 1 },
    { letter: '小', options: ['人', '大', '小', '山'], answer: 2 },
    { letter: '山', options: ['人', '大', '小', '山'], answer: 3 },
    { letter: '水', options: ['水', '火', '土', '木'], answer: 0 },
    { letter: '火', options: ['水', '火', '土', '木'], answer: 1 },
    { letter: '土', options: ['水', '火', '土', '木'], answer: 2 },
    { letter: '木', options: ['水', '火', '土', '木'], answer: 3 },
    { letter: '日', options: ['日', '月', '年', '天'], answer: 0 },
    { letter: '月', options: ['日', '月', '年', '天'], answer: 1 },
    { letter: '年', options: ['日', '月', '年', '天'], answer: 2 },
    { letter: '天', options: ['日', '月', '年', '天'], answer: 3 },
    { letter: '上', options: ['上', '下', '左', '右'], answer: 0 },
    { letter: '下', options: ['上', '下', '左', '右'], answer: 1 },
    { letter: '左', options: ['上', '下', '左', '右'], answer: 2 },
    { letter: '右', options: ['上', '下', '左', '右'], answer: 3 },
    { letter: '口', options: ['口', '手', '足', '目'], answer: 0 },
    { letter: '手', options: ['口', '手', '足', '目'], answer: 1 },
    { letter: '足', options: ['口', '手', '足', '目'], answer: 2 },
    { letter: '目', options: ['口', '手', '足', '目'], answer: 3 },
  ]}},
  { title: '天气和季节 - 扩展', type: 'picture_quiz', emoji: '⛅', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['晴天', '雨天', '阴天'], answer: 0 },
    { image: '🌧️', options: ['晴天', '雨天', '阴天'], answer: 1 },
    { image: '☁️', options: ['晴天', '雨天', '阴天'], answer: 2 },
    { image: '❄️', options: ['热', '冷', '暖'], answer: 1 },
    { image: '💨', options: ['雨', '风', '雪'], answer: 1 },
    { image: '⛈️', options: ['晴天', '雷雨', '阴天'], answer: 1 },
    { image: '🌈', options: ['雨后彩虹', '晴天', '雨天'], answer: 0 },
    { image: '🌫️', options: ['云', '雾', '烟'], answer: 1 },
    { problem: '春天的特点?', options: ['花开', '下雪', '落叶'], answer: 0 },
    { problem: '夏天的特点?', options: ['下雪', '很热', '落叶'], answer: 1 },
    { problem: '秋天的特点?', options: ['花开', '很热', '落叶'], answer: 2 },
    { problem: '冬天的特点?', options: ['下雪', '很热', '花开'], answer: 0 },
    { problem: '一年有几个季节?', options: ['2', '3', '4'], answer: 2 },
    { problem: '马来西亚通常什么天气?', options: ['下雪', '热带雨林气候', '非常冷'], answer: 1 },
    { problem: '雨后什么时候能看到彩虹?', options: ['下雨时', '雨后晴天', '晚上'], answer: 1 },
    { problem: '下雨时需要带什么?', options: ['帽子', '雨伞', '手套'], answer: 1 },
    { problem: '太阳出来时天气怎么样?', options: ['冷', '热', '刮风'], answer: 1 },
    { problem: '哪个季节花朵最多?', options: ['冬天', '夏天', '春天'], answer: 2 },
    { image: '🌡️', options: ['温度计', '时钟', '秤'], answer: 0 },
    { problem: '天气预报预测什么?', options: ['食物', '明天的天气', '交通'], answer: 1 },
  ]}},
];