export const sekolah_bahasa_melayu_expansion = [
  {
    title: 'Ungkapan Peribahasa Kompleks',
    type: 'multiple_choice',
    emoji: '💬',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: '"Seperti api dalam sekam" bermaksud?', options: ['Sangat panas', 'Masalah yang tersembunyi', 'Bahaya tersembunyi'], answer: 2 },
      { problem: '"Membuang batu menyembunyikan tangan" bermaksud?', options: ['Berbuat jahat sambil menyembunyikan', 'Membuang sampah', 'Bermain batu'], answer: 0 },
      { problem: '"Bikin duit dari angin" bermaksud?', options: ['Mencari rezeki mudah', 'Berbuat curang', 'Bisnes yang jujur'], answer: 1 },
      { problem: '"Melukis kaca" bermaksud?', options: ['Seni menggambar', 'Perbuatan sia-sia', 'Kerja tangan'], answer: 1 },
      { problem: '"Membawa air ke lautan" bermaksud?', options: ['Membantu orang', 'Perbuatan sia-sia', 'Aktiviti laut'], answer: 1 },
      { problem: '"Mencabar harimau" bermaksud?', options: ['Bermain dengan binatang', 'Berani menghadapi risiko besar', 'Membuat kemarahan'], answer: 1 },
      { problem: '"Ikut piala terbang" bermaksud?', options: ['Mengikuti kegembiraan sementara', 'Mengikuti kesuksesan', 'Mengejar cita-cita'], answer: 0 },
      { problem: '"Seperti mencari jarum dalam tandan jerami" bermaksud?', options: ['Mencari barang hilang', 'Mencari sesuatu yang tidak mungkin', 'Kerja berat'], answer: 1 },
      { problem: '"Tunggang langgang" bermaksud?', options: ['Semata-mata', 'Kacau-bilau', 'Bersenak'], answer: 1 },
      { problem: '"Taling telinga pembohong" bermaksud?', options: ['Bahagian telinga', 'Bukti yang nyata', 'Cacat tubuh'], answer: 1 },
      { problem: '"Nila setitik rusak susu sebelanga" bermaksud?', options: ['Sedikit keburukan memusnahkan kebaikan', 'Nila dan susu', 'Sesuatu yang cemar'], answer: 0 },
      { problem: '"Berkati-kati akan sampai ke tujuan" bermaksud?', options: ['Berlari cepat', 'Usaha berterusan akan berjaya', 'Jalan yang panjang'], answer: 1 },
      { problem: '"Kucing dalam karung" bermaksud?', options: ['Binatang dalam kain', 'Sesuatu yang tersembunyi', 'Mainan anak'], answer: 1 },
      { problem: '"Air mata buaya" bermaksud?', options: ['Haiwan yang menangis', 'Kepalsuan atau tipu daya', 'Kesedihan sejati'], answer: 1 },
      { problem: '"Mengambil resiko" bermaksud?', options: ['Ambil barang', 'Berani menghadapi bahaya', 'Mainan berisiko'], answer: 1 },
      { problem: '"Jatuh ke batu dari batu" bermaksud?', options: ['Kecelakaan beruntun', 'Bernasib malang', 'Batu yang keras'], answer: 1 },
      { problem: '"Mentari terbit dari barat" bermaksud?', options: ['Kejadian aneh yang mustahil', 'Waktu matahari'], answer: 0 },
      { problem: '"Madu dalam bibir, bisa dalam hati" bermaksud?', options: ['Mulut manis tetapi hati jahat', 'Madu yang beracun', 'Dusta yang indah'], answer: 0 },
      { problem: '"Cakap serupa perbuatan" bermaksud?', options: ['Ucapan sama dengan tindakan', 'Berbicara panjang', 'Tingkah laku aneh'], answer: 0 },
      { problem: '"Tepukan tanpa suara" bermaksud?', options: ['Tepukan sunyi', 'Pujian yang diam-diam', 'Bunyi lemah'], answer: 1 },
    ]}
  },
  {
    title: 'Tatabahasa - Penggunaan Kata Hubung',
    type: 'multiple_choice',
    emoji: '🔗',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '"Dia ___ belajar ___ bermain" - kata hubung yang sesuai?', options: ['dan, dan', 'tetapi, atau', 'kerana, supaya'], answer: 0 },
      { problem: '"Saya pergi ke sekolah ___ hujan turun" - kata hubung?', options: ['walaupun', 'kerana', 'maka'], answer: 0 },
      { problem: '"Dia rajin belajar ___ dia ingin lulus peperiksaan" - kata hubung?', options: ['tetapi', 'kerana', 'atau'], answer: 1 },
      { problem: '"Kamu boleh pilih ___ nasi ___ roti" - kata hubung?', options: ['dan, dan', 'atau, atau', 'tetapi, tetapi'], answer: 1 },
      { problem: '"Mereka berlari cepat ___ takut tertinggal" - kata hubung?', options: ['dan', 'kerana', 'walaupun'], answer: 1 },
      { problem: '"Saya tidur awal ___ besok ada ujian" - kata hubung?', options: ['kerana', 'tetapi', 'atau'], answer: 0 },
      { problem: '"Dia kaya ___ dia tidak boros" - kata hubung?', options: ['tetapi', 'kerana', 'dan'], answer: 0 },
      { problem: '"Saya ingin bermain ___ saya perlu siapkan kerja rumah dahulu" - kata hubung?', options: ['tetapi', 'kerana', 'atau'], answer: 0 },
      { problem: '"Ibu memasak nasi ___ sayur ___ ikan" - kata hubung?', options: ['dan, dan', 'tetapi, tetapi', 'atau, atau'], answer: 0 },
      { problem: '"Kami akan datang ___ tidak ada halangan" - kata hubung?', options: ['selagi', 'kerana', 'walaupun'], answer: 0 },
      { problem: '"Saya suka membaca buku ___ menonton wayang" - kata hubung?', options: ['dan', 'atau', 'tetapi'], answer: 1 },
      { problem: '"Dia sakit ___ dia masih datang ke sekolah" - kata hubung?', options: ['tetapi', 'kerana', 'dan'], answer: 0 },
      { problem: '"Kita harus belajar ___ kita ingin berjaya" - kata hubung?', options: ['dan', 'kerana', 'selagi'], answer: 1 },
      { problem: '"Dia tidak hadir ___ sakit perut" - kata hubung?', options: ['kerana', 'tetapi', 'atau'], answer: 0 },
      { problem: '"Saya akan tunggu ___ kamu datang" - kata hubung?', options: ['selagi', 'kerana', 'walaupun'], answer: 0 },
      { problem: '"Mereka kesal ___ mereka tetap tersenyum" - kata hubung?', options: ['kerana', 'walaupun', 'dan'], answer: 1 },
      { problem: '"Saya harus berangkat sekarang ___ tidak terlambat" - kata hubung?', options: ['supaya', 'kerana', 'tetapi'], answer: 0 },
      { problem: '"Dia pandai bernyanyi ___ menari" - kata hubung?', options: ['dan', 'atau', 'tetapi'], answer: 0 },
      { problem: '"Kamu boleh pergi ___ datang balik tepat waktu" - kata hubung?', options: ['selagi', 'tetapi', 'kerana'], answer: 0 },
      { problem: '"Buku ini menarik ___ berkualiti" - kata hubung?', options: ['dan', 'tetapi', 'kerana'], answer: 0 },
    ]}
  },
  {
    title: 'Pembacaan Pemahaman - Cerita Pendek',
    type: 'reading',
    emoji: '📖',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: 'Cerita: "Seorang budak bernama Ahmad sangat malas. Dia tidak suka belajar. Setiap hari dia bermain saja. Ibunya sering menolong dia belajar tetapi Ahmad tidak malu." - Sifat Ahmad apa?', options: ['rajin', 'malas', 'budiman'], answer: 1 },
      { problem: 'Apa yang Ahmad lakukan setiap hari?', options: ['belajar', 'bermain', 'bekerja'], answer: 1 },
      { problem: 'Siapa yang menolong Ahmad belajar?', options: ['ayah', 'ibu', 'guru'], answer: 1 },
      { problem: 'Cerita ini mengajar apa?', options: ['bermain itu bagus', 'kemalasan buruk', 'ibu itu jahat'], answer: 1 },
      { problem: 'Berapa banyak orang dalam cerita?', options: ['1', '2', '3'], answer: 1 },
      { problem: 'Ahmad rasa malu atau tidak?', options: ['ya', 'tidak', 'kadang'], answer: 1 },
      { problem: 'Cerita ini tentang apa?', options: ['keluarga bahagia', 'budak yang malas', 'ibu yang sabar'], answer: 1 },
      { problem: 'Apa yang sepatutnya Ahmad lakukan?', options: ['bermain lebih', 'belajar rajin', 'tidak dengar ibu'], answer: 1 },
      { problem: 'Sifat ibu Ahmad apa?', options: ['penyabar', 'pemalas', 'kejam'], answer: 0 },
      { problem: 'Pelajaran dari cerita ini apa?', options: ['bermain penting', 'belajar sangat penting', 'ibu bodoh'], answer: 1 },
      { problem: 'Cerita di atas menunjukkan apa?', options: ['kasih sayang ibu', 'kebinaasan anak', 'kemalasan diri'], answer: 0 },
      { problem: 'Yang benar tentang Ahmad apa?', options: ['dia rajin', 'dia malas belajar', 'dia suka buku'], answer: 1 },
      { problem: 'Ibu Ahmad membuat apa?', options: ['marah', 'usaha bantu Ahmad', 'tidak peduli'], answer: 1 },
      { problem: 'Masalah dalam cerita apa?', options: ['ibu sakit', 'Ahmad malas', 'sekolah jauh'], answer: 1 },
      { problem: 'Perasaan ibu Ahmad apa?', options: ['gembira', 'kecewa', 'marah'], answer: 1 },
      { problem: 'Pengajaran untuk anak apa?', options: ['ikut kata ibu', 'bermain banyak', 'tidak belajar'], answer: 0 },
      { problem: 'Ahmad hendak berubah atau tidak?', options: ['ya', 'tidak tunjuk', 'mungkin'], answer: 1 },
      { problem: 'Masa depan Ahmad akan jadi apa jika terus malas?', options: ['berjaya', 'gagal', 'tak tahu'], answer: 1 },
      { problem: 'Ibu Ahmad cinta pada dia atau tidak?', options: ['ya', 'tidak', 'masa bodoh'], answer: 0 },
      { problem: 'Cerita itu memberi teladan apa?', options: ['bermain saja', 'rajin belajar', 'tidak dengar'], answer: 1 },
    ]}
  },
  {
    title: 'Struktur Ayat - Pola Dasar',
    type: 'multiple_choice',
    emoji: '📝',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'Ayat dasar dalam BM apa pola?', options: ['Subjek-Predikat-Objek', 'Objek-Subjek', 'Predikat saja'], answer: 0 },
      { problem: '"Adik minum susu" - struktur ayat?', options: ['SPO', 'OS', 'PS'], answer: 0 },
      { problem: '"Ibu memasak nasi" - predikat ayat apa?', options: ['ibu', 'memasak', 'nasi'], answer: 1 },
      { problem: '"Anak laki suka bermain" - subjek ayat apa?', options: ['anak laki', 'suka', 'bermain'], answer: 0 },
      { problem: '"Kucing putih tidur di sofa" - objek apa?', options: ['kucing', 'tidur', 'sofa'], answer: 2 },
      { problem: 'Predikat dalam ayat paling penting apa?', options: ['menunjuk tindakan', 'nama barang', 'tempat'], answer: 0 },
      { problem: '"Guru mengajar pelajaran" - objek ayat?', options: ['guru', 'mengajar', 'pelajaran'], answer: 2 },
      { problem: 'Subjek dalam ayat biasanya apa?', options: ['tindakan', 'pengambil tindakan', 'alat'], answer: 1 },
      { problem: '"Saya membaca buku cerita" - SPO mana?', options: ['saya, membaca, buku cerita', 'membaca, saya, buku', 'buku, saya, membaca'], answer: 0 },
      { problem: 'Ayat yang lengkap mesti ada berapa unsur?', options: ['1', '2', '3'], answer: 1 },
      { problem: '"Dia berlari ke sekolah" - predikat?', options: ['dia', 'berlari', 'sekolah'], answer: 1 },
      { problem: '"Ayah membeli buku" - jenis predikat?', options: ['nominal', 'verbal', 'preposisional'], answer: 1 },
      { problem: 'Struktur ayat nominal contohnya apa?', options: ['"dia makan"', '"dia cerdas"', '"dia datang"'], answer: 1 },
      { problem: '"Bunga itu cantik" - predikat nominal atau verbal?', options: ['nominal', 'verbal', 'tidak tahu'], answer: 0 },
      { problem: 'Keterangan dalam ayat apa kegunaan?', options: ['memberi info tambahan', 'tindakan', 'nama barang'], answer: 0 },
      { problem: '"Mereka pergi ke taman kemarin" - keterangan apa?', options: ['tempat dan waktu', 'subjek', 'predikat'], answer: 0 },
      { problem: 'Ayat dengan lebih dari 3 unsur biasa disebut?', options: ['ayat ringkas', 'ayat lengkap', 'ayat panjang'], answer: 2 },
      { problem: '"Dia tidur" - ayat ini struktur apa?', options: ['SP', 'SPO', 'SPOK'], answer: 0 },
      { problem: 'Mana ayat yang benar struktur?', options: ['Memasak ibu nasi', 'Ibu memasak nasi', 'Nasi ibu memasak'], answer: 1 },
      { problem: 'Kelengkapan ayat apakah paling penting?', options: ['keterangan', 'subjek dan predikat', 'objek saja'], answer: 1 },
    ]}
  },
  {
    title: 'Kamus dan Gaya Bahasa',
    type: 'multiple_choice',
    emoji: '📚',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: '"Metafora" dalam gaya bahasa apa maksud?', options: ['perbandingan', 'mengatakan sesuatu dengan kiasan', 'penceritaan'], answer: 1 },
      { problem: 'Contoh metafora mana yang betul?', options: ['"dia seperti bunga"', '"dia adalah bunga"', '"dia mirip bunga"'], answer: 1 },
      { problem: '"Simile" dalam BM disebut apa?', options: ['andaian', 'perumpamaan', 'perbandingan'], answer: 1 },
      { problem: '"Dia kuat seperti harimau" - gaya bahasa apa?', options: ['metafora', 'simile', 'hiperbola'], answer: 1 },
      { problem: '"Matahari terbit di timur setiap hari" - gaya bahasa apa?', options: ['kiasan', 'makna sebenarnya', 'pujian'], answer: 1 },
      { problem: 'Sinonim "besar" dalam bahasa apa?', options: ['kecil', 'membesar', 'raya'], answer: 2 },
      { problem: 'Antonim "rajin" dalam bahasa apa?', options: ['sangat rajin', 'malas', 'bekerja'], answer: 1 },
      { problem: 'Kata "mencuri" sinonim dengan?', options: ['membeli', 'mengambil tanpa izin', 'memberikan'], answer: 1 },
      { problem: 'Makna kamus untuk "budiman" apa?', options: ['buruk', 'tinggi', 'berbudi baik'], answer: 2 },
      { problem: '"Hiperbola" dalam gaya bahasa apa?', options: ['perbandingan sebenar', 'pembesaran sifat', 'kiasan halus'], answer: 1 },
      { problem: '"Saya sudah bilang seribu kali" - gaya bahasa?', options: ['metafora', 'simile', 'hiperbola'], answer: 2 },
      { problem: 'Idiom dalam bahasa apa arti?', options: ['perkataan tunggal', 'kelompok kata dengan makna khusus', 'ayat panjang'], answer: 1 },
      { problem: 'Contoh idiom yang betul apa?', options: ['"makan nasi"', '"mencuri pandang"', '"tidur nyenyak"'], answer: 1 },
      { problem: 'Makna "alusi" dalam bahasa apa?', options: ['pujian', 'acuan tidak langsung', 'ejekan'], answer: 1 },
      { problem: 'Gaya bahasa "pun" dalam bahasa apa?', options: ['biasa', 'perendahan diri', 'tinggi hati'], answer: 1 },
      { problem: 'Kata luar yang sering dipakai dalam BM contohnya?', options: ['"jam" dari bahasa Arab', '"meja" dari bahasa Belanda', 'semua betul'], answer: 2 },
      { problem: 'Eufemisme dalam bahasa apa maksud?', options: ['perkataan pedas', 'perkataan lembut menggantikan yang kasar', 'perkataan aneh'], answer: 1 },
      { problem: 'Contoh eufemisme yang betul apa?', options: ['"wafat" ganti "mati"', '"bodoh" ganti "kurang cerdas"', 'dua-dua betul'], answer: 2 },
      { problem: 'Majas dalam karya sastera apa guna?', options: ['membelakangi fakta', 'memberi keindahan bahasa', 'mengaburkan maksud'], answer: 1 },
      { problem: 'Bahasa yang lebih dalam sastra dipakai apa?', options: ['bahasa mudah', 'bahasa indah dan bermakna', 'bahasa kasar'], answer: 1 },
    ]}
  },
  {
    title: 'Ejaan dan Tanda Baca - Penggunaan',
    type: 'multiple_choice',
    emoji: '✏️',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'Tanda titik (.) digunakan apabila?', options: ['pertanyaan', 'akhir ayat', 'senarai'], answer: 1 },
      { problem: 'Koma (,) dipakai untuk apa?', options: ['akhir ayat', 'pemisah kata atau ungkapan', 'pertanyaan'], answer: 1 },
      { problem: 'Tanda tanya (?) digunakan apabila?', options: ['pernyataan', 'pertanyaan', 'perintah'], answer: 1 },
      { problem: 'Tanda seru (!) dipakai apabila?', options: ['pertanyaan', 'pernyataan emosi kuat', 'senarai'], answer: 1 },
      { problem: 'Huruf besar digunakan untuk?', options: ['semua kata', 'awal ayat dan nama khas', 'akhir ayat'], answer: 1 },
      { problem: '"Kuala Lumpur" - mengapa huruf besar?', options: ['nama khas', 'kata penting', 'awal ayat'], answer: 0 },
      { problem: 'Kata "negara" sepatutnya eja apa?', options: ['negera', 'negara', 'negoro'], answer: 1 },
      { problem: '"Mereka _____ ke sekolah" - kata yang betul?', options: ['pergi', 'pegi', 'pergi'], answer: 0 },
      { problem: 'Bunyi "kh" dalam BM eja apa?', options: ['kh', 'kl', 'kj'], answer: 0 },
      { problem: '"Khutbah" bagaimanakah ejaannya?', options: ['khutbah', 'kutbah', 'qutbah'], answer: 0 },
      { problem: 'Tanda hubung (-) digunakan untuk?', options: ['akhir ayat', 'menyambung kata', 'pertanyaan'], answer: 1 },
      { problem: 'Tanda petik ("") dipakai untuk?', options: ['nama khas', 'petikan kata', 'senarai'], answer: 1 },
      { problem: 'Titik dua (:) biasanya dipakai?', options: ['pemisah', 'sebelum senarai', 'akhir ayat'], answer: 1 },
      { problem: 'Tanda garis miring (/) apa kegunaan?', options: ['pemisah', 'akhir ayat', 'huruf besar'], answer: 0 },
      { problem: '"Buku-buku" - tanda garis apa?', options: ['penghubung', 'pemisah', 'pemberi tanda'], answer: 0 },
      { problem: 'Ejaan "berapa" yang betul apa?', options: ['brapa', 'berapa', 'berapah'], answer: 1 },
      { problem: 'Kata "jangan" sepatutnya eja apa?', options: ['jangan', 'jgan', 'jngn'], answer: 0 },
      { problem: 'Huruf "z" biasanya bunyi apa?', options: ['z seperti Inggeris', 'j seperti BM', 'dua-duanya'], answer: 2 },
      { problem: 'Kata "mengapa" bagaimanakah ejaannya?', options: ['mengapa', 'mengapa', 'mgapa'], answer: 0 },
      { problem: 'Tanda koma dalam senarai apa guna?', options: ['pemisah item', 'akhir senarai', 'permulaan'], answer: 0 },
    ]}
  },
  {
    title: 'Penulisan Cerita Pendek',
    type: 'multiple_choice',
    emoji: '🖊️',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Cerita pendek mesti ada berapa elemen utama?', options: ['2', '3', '5'], answer: 2 },
      { problem: 'Lima elemen cerita pendek apa saja?', options: ['watak, latar, plot, konflik, resolusi', 'mula, tengah, akhir, watak, latar', 'pengarang, tema, dialog, deskripsi, watak'], answer: 0 },
      { problem: 'Pendahuluan dalam cerita biasanya untuk apa?', options: ['memperkenalkan watak', 'menjelaskan masalah', 'menyelesaikan kisah'], answer: 0 },
      { problem: 'Konflik dalam cerita apa maksudnya?', options: ['masalah atau pertentangan', 'ending cerita', 'watak cerita'], answer: 0 },
      { problem: 'Resolusi dalam cerita apa guna?', options: ['masalah timbul', 'masalah selesai', 'watak diperkenalkan'], answer: 1 },
      { problem: 'Latar dalam cerita apa maksud?', options: ['watak cerita', 'tempat dan masa cerita', 'tindakan watak'], answer: 1 },
      { problem: 'Watak dinamis dalam cerita apa maksud?', options: ['tidak berubah', 'berubah sepanjang cerita', 'diam saja'], answer: 1 },
      { problem: 'Dialog dalam cerita apa kegunaan?', options: ['menghias cerita', 'membuat cerita jelas dan hidup', 'memanjangkan cerita'], answer: 1 },
      { problem: 'Tema dalam cerita apa maksud?', options: ['nama cerita', 'idea utama cerita', 'akhir cerita'], answer: 1 },
      { problem: 'Deskripsi dalam cerita untuk apa?', options: ['cepat dapat cerita', 'gambarkan suasana dengan detail', 'pendekkan cerita'], answer: 1 },
      { problem: 'Puncak cerita (climax) apa maksud?', options: ['mula cerita', 'titik tegang paling tinggi', 'akhir cerita'], answer: 1 },
      { problem: 'Gaya bahasa dalam cerita apa guna?', options: ['memuat cerita', 'memberi keindahan dalam cerita', 'memperendah cerita'], answer: 1 },
      { problem: 'Narator dalam cerita apa maksud?', options: ['watak cerita', 'pencerita', 'pembaca cerita'], answer: 1 },
      { problem: 'Cerita dari sudut pandang orang pertama maksud apa?', options: ['watak lain cerita', 'watak sendiri bercerita', 'penulis bercerita'], answer: 1 },
      { problem: 'Paragraf pembuka cerita harus apa?', options: ['panjang', 'pendek tetapi menarik', 'membosankan'], answer: 1 },
      { problem: 'Akhir cerita yang baik apa ciri?', options: ['panjang', 'meninggalkan kesan', 'cerita belum selesai'], answer: 1 },
      { problem: 'Cerita pendek panjang ideal berapa perkataan?', options: ['100', '1000-3000', 'tidak ada batasan'], answer: 1 },
      { problem: 'Alur cerita linier apa maksud?', options: ['cerita berbelok', 'cerita maju lurus dari awal ke akhir', 'cerita melompat waktu'], answer: 1 },
      { problem: 'Karakter watak jahat dalam cerita maksud apa?', options: ['pemberi konflik', 'penyelamat', 'pembantu'], answer: 0 },
      { problem: 'Flashback dalam cerita apa maksud?', options: ['cerita masa hadapan', 'cerita masa lalu', 'cerita masa kini'], answer: 1 },
    ]}
  },
  {
    title: 'Karya Sastera - Jenis dan Ciri',
    type: 'multiple_choice',
    emoji: '📕',
    difficulty: 'medium',
    darjah: 5,
    gameData: { questions: [
      { problem: 'Puisi dalam sastera apa maksud?', options: ['cerpen panjang', 'karya dengan irama dan ritma', 'drama', 'esei'], answer: 1 },
      { problem: 'Drama dalam sastera apa ciri utama?', options: ['naratif panjang', 'dialog dan tindakan', 'cerita ringkas'], answer: 1 },
      { problem: 'Novel berbeda dengan cerpen bagaimana?', options: ['novel lebih pendek', 'novel lebih panjang dan kompleks', 'sama panjang'], answer: 1 },
      { problem: 'Esei dalam sastera apa maksud?', options: ['cerita rekaan', 'tulisan pendek berupa pendapat', 'puisi'], answer: 1 },
      { problem: 'Pantun dalam puisi apa ciri?', options: ['baris satu rima', 'empat baris, persamaan akhir', 'tanpa rima'], answer: 1 },
      { problem: 'Syair dalam puisi apa maksud?', options: ['puisi pendek', 'puisi dengan cerita panjang', 'puisi tanpa cerita'], answer: 1 },
      { problem: 'Gurindam dalam puisi apa ciri?', options: ['banyak baris', 'dua baris dengan makna lengkap', 'tanpa rima'], answer: 1 },
      { problem: 'Soneta dalam puisi apa ciri?', options: ['4 baris', '8 baris', '14 baris'], answer: 2 },
      { problem: 'Fiksi dalam sastera apa maksud?', options: ['cerita benar', 'cerita rekaan', 'biografi'], answer: 1 },
      { problem: 'Non-fiksi dalam sastera apa maksud?', options: ['cerita rekaan', 'cerita benar dan nyata', 'fantasi'], answer: 1 },
      { problem: 'Legenda dalam sastera apa ciri?', options: ['cerita pendek', 'cerita rakyat yang diyakini benar', 'cerita fiksi jelas'], answer: 1 },
      { problem: 'Mitos dalam sastera apa maksud?', options: ['cerita benar', 'cerita keagamaan atau penjelas alam', 'cerita modern'], answer: 1 },
      { problem: 'Autobiografi apa maksud?', options: ['cerita orang lain', 'sejarah diri sendiri oleh penulis', 'cerita rekaan'], answer: 1 },
      { problem: 'Biografi apa berbeda dari autobiografi?', options: ['sama saja', 'biografi ditulis orang lain', 'biografi lebih pendek'], answer: 1 },
      { problem: 'Satra modern apa ciri utama?', options: ['cerita lama', 'menggunakan gaya bahasa baru dan tema masa kini', 'sama dengan klasik'], answer: 1 },
      { problem: 'Sastra klasik dalam BM apa contohnya?', options: ['"Hikayat Hang Tuah"', '"Kain Batik"', '"Tiga Putra Mariam"'], answer: 0 },
      { problem: 'Teks dramatik dalam sastera apa ciri?', options: ['naratif saja', 'dialog dan penggambaran adegan', 'puisi saja'], answer: 1 },
      { problem: 'Metafora dalam sastera apa guna?', options: ['jelaskan', 'memberi keindahan', 'memendekkan'], answer: 1 },
      { problem: 'Hiperbola dalam sastera apa maksud?', options: ['perbandingan wajar', 'pembesaran emosi atau kejadian', 'pengurangan'], answer: 1 },
      { problem: 'Alusi dalam sastera untuk apa?', options: ['jelaskan langsung', 'memberi rujukan tidak langsung', 'memudahkan cerita'], answer: 1 },
    ]}
  },
  {
    title: 'Pidato dan Ceramah - Teknik',
    type: 'multiple_choice',
    emoji: '🎤',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'Pidato yang baik mesti ada berapa bahagian?', options: ['2', '3', '5'], answer: 1 },
      { problem: 'Tiga bahagian pidato apa saja?', options: ['pembukaan, isi, penutup', 'awal, tengah, akhir', 'berapa aja boleh'], answer: 0 },
      { problem: 'Pembukaan pidato apa tujuan utama?', options: ['jelaskan isi', 'tarik perhatian pendengar', 'samaikan'], answer: 1 },
      { problem: 'Isi pidato apa maksud?', options: ['salam pembuka', 'perkara utama pidato', 'terima kasih'], answer: 1 },
      { problem: 'Penutup pidato apa kegunaan?', options: ['mula pidato', 'ringkas dan tamatkan pidato', 'jelaskan detail'], answer: 1 },
      { problem: 'Nada dalam pidato apa penting?', options: ['tidak penting', 'sangat penting untuk kesan', 'cadangan saja'], answer: 1 },
      { problem: 'Gerak tubuh dalam pidato (gesture) apa guna?', options: ['tidak perlu', 'menghidupkan pidato', 'mengacaukan'], answer: 1 },
      { problem: 'Kontak mata dengan pendengar apa guna?', options: ['tidak penting', 'membina hubungan dengan pendengar', 'menakutkan'], answer: 1 },
      { problem: 'Kecepatan berbicara dalam pidato apa ideal?', options: ['cepat', 'sederhana dan jelas', 'tak tentu'], answer: 1 },
      { problem: 'Jeda dalam pidato apa kegunaan?', options: ['membuang waktu', 'memberi ruang pemahaman', 'mengganggu'], answer: 1 },
      { problem: 'Persiapan pidato apa langkah pertama?', options: ['asal bicara', 'kumpul bahan dan buat nota', 'hapal kata demi kata'], answer: 1 },
      { problem: 'Nota pidato apa maksud?', options: ['kata untuk hapal', 'garis besar untuk panduan', 'tulisan panjang'], answer: 1 },
      { problem: 'Bahasa pidato apa jenis terbaik?', options: ['bahasa pasar', 'bahasa baku dan jelas', 'bahasa slang'], answer: 1 },
      { problem: 'Ceramah berbeda dari pidato bagaimana?', options: ['sama saja', 'ceramah lebih santai dan mengajar', 'pidato sama ceramah'], answer: 1 },
      { problem: 'Slide dalam pidato apa guna?', options: ['hiburan', 'membantu jelaskan isi', 'tidak perlu'], answer: 1 },
      { problem: 'Audiens dalam pidato siapa maksud?', options: ['penulis pidato', 'pendengar pidato', 'pengajar pidato'], answer: 1 },
      { problem: 'Kesimpulan pidato apa ciri?', options: ['baru info baru', 'ringkas ide utama', 'cerita baru'], answer: 1 },
      { problem: 'Tema pidato apa penting?', options: ['tidak penting', 'sangat penting sebagai fokus', 'cadangan'], answer: 1 },
      { problem: 'Senyuman dalam pidato apa kegunaan?', options: ['tidak penting', 'memberi kesan positif', 'tidak perlu'], answer: 1 },
      { problem: 'Pertanyaan dalam pidato apa tujuan?', options: ['mengganggu', 'melibatkan pendengar', 'membuang waktu'], answer: 1 },
    ]}
  },
  {
    title: 'Terjemahan - Teknik Dasar',
    type: 'multiple_choice',
    emoji: '🌐',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Terjemahan harfiah apa maksud?', options: ['terjemah arti', 'terjemah kata demi kata', 'terjemah ringkas'], answer: 1 },
      { problem: 'Terjemahan makna apa maksud?', options: ['terjemah kata', 'terjemah arti dan makna keseluruhan', 'terjemah pendek'], answer: 1 },
      { problem: 'Kesulitan terjemahan utama apa?', options: ['waktu', 'perbezaan budaya dan bahasa', 'alat'], answer: 1 },
      { problem: '"He is blue" bagaimana terjemah yang tepat?', options: ['"Dia adalah biru"', '"Dia sedih"', '"Dia dalam laut"'], answer: 1 },
      { problem: 'Idiom dalam terjemahan bagaimana cara terbaik?', options: ['terjemah kata demi kata', 'cari idiom setara dalam bahasa tujuan', 'tambah penjelasan'], answer: 1 },
      { problem: 'Budaya dalam terjemahan apa maksud?', options: ['bahasa saja', 'cara hidup dan nilai masyarakat', 'kata-kata'], answer: 1 },
      { problem: 'Sinonim dalam terjemahan apa guna?', options: ['tidak penting', 'temukan kata yang sama maknanya', 'ganti sesuka'], answer: 1 },
      { problem: 'Konteks dalam terjemahan apa penting?', options: ['tidak penting', 'sangat penting untuk keakuratan', 'cadangan saja'], answer: 1 },
      { problem: 'Terjemah istilah teknis bagaimana terbaik?', options: ['asal terjemah', 'cari istilah setara dalam bahasa tujuan', 'tidak perlu'], answer: 1 },
      { problem: 'Pelafalan dalam terjemahan apa masalah?', options: ['tidak ada', 'dapat mengubah makna', 'tidak penting'], answer: 1 },
      { problem: '"Broken English" dalam terjemahan apa maksud?', options: ['bahasa Inggeris cacat', 'bahasa tidak lancar', 'dua-dua betul'], answer: 2 },
      { problem: 'Penerjemah profesional apa syarat utama?', options: ['hanya hafal kamus', 'kuasai kedua bahasa dan budaya', 'baca banyak'], answer: 1 },
      { problem: 'Bacaan berulang dalam terjemahan apa guna?', options: ['membuang waktu', 'memahami makna lebih baik', 'tidak perlu'], answer: 1 },
      { problem: 'Sumber dan bahasa tujuan dalam terjemahan apa?', options: ['bahasa asal dan tujuan terjemahan', 'sama saja', 'tidak penting'], answer: 0 },
      { problem: 'Ekuivalen dinamis dalam terjemahan apa maksud?', options: ['arti yang sama tetapi gaya berbeza', 'arti sama persis', 'arti berbeza'], answer: 0 },
      { problem: 'Daftar istilah dalam terjemahan apa guna?', options: ['hiasan', 'konsistensi istilah yang sama', 'tidak perlu'], answer: 1 },
      { problem: '"Mistranslation" apa maksud?', options: ['terjemahan baik', 'terjemahan salah', 'terjemahan panjang'], answer: 1 },
      { problem: 'Gaya penulis dalam terjemahan apa peranan?', options: ['tidak penting', 'harus dipertahankan dalam terjemahan', 'ubah saja'], answer: 1 },
      { problem: 'Catatan kaki dalam terjemahan apa guna?', options: ['dekorasi', 'beri penjelasan tambahan bila perlu', 'tidak perlu'], answer: 1 },
      { problem: 'Revisi dalam terjemahan apa pentingnya?', options: ['tidak penting', 'sangat penting untuk hasil berkualiti', 'cadangan'], answer: 1 },
    ]}
  },
  {
    title: 'Penulisan Email dan Surat Rasmi',
    type: 'multiple_choice',
    emoji: '✉️',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'Email rasmi kepada siapa bagaimana salam?', options: ['Halo kawan', 'Yang Hormat', 'Hei'], answer: 1 },
      { problem: 'Surat rasmi mesti ada berapa bahagian?', options: ['2', '5', '10'], answer: 1 },
      { problem: 'Lima bahagian surat rasmi apa saja?', options: ['kepala surat, tarikh, penerima, isi, penutup', 'awal, tengah, akhir, nama, alamat', 'bebas berapa'], answer: 0 },
      { problem: 'Kepala surat (letterhead) apa guna?', options: ['hiasan', 'menunjukkan organisasi pengirim', 'tidak penting'], answer: 1 },
      { problem: 'Tarikh dalam surat rasmi di mana letak?', options: ['akhir', 'di bawah kepala surat', 'permulaan isi'], answer: 1 },
      { problem: 'Tajuk surat rasmi apa fungsi?', options: ['hiasan', 'jelaskan pokok surat', 'tidak perlu'], answer: 1 },
      { problem: 'Tujuan utama surat rasmi apa?', options: ['cerita panjang', 'menyampaikan maklumat formal', 'ngobrol'], answer: 1 },
      { problem: 'Isi surat rasmi bagaimana struktur?', options: ['sesuka hati', 'pendahuluan, isi, penutup', 'panjang saja'], answer: 1 },
      { problem: 'Penutup surat rasmi apa jenis salam?', options: ['sampai jumpa', 'Salam Hormat / Sehidmat Menegara', 'bye bye'], answer: 1 },
      { problem: 'Tanda tangan dalam surat rasmi penting atau tidak?', options: ['tidak penting', 'sangat penting', 'guna nama saja'], answer: 1 },
      { problem: 'Bahasa surat rasmi apa jenis?', options: ['bahasa santai', 'bahasa baku dan formal', 'bahasa slang'], answer: 1 },
      { problem: 'Email rasmi berbeda dari surat bagaimana?', options: ['sama saja', 'email lebih cepat tapi tetap formal', 'email bebas'], answer: 1 },
      { problem: 'CC dalam email rasmi apa maksud?', options: ['tidak ada guna', 'salinan kepada orang lain', 'rahsia'], answer: 1 },
      { problem: 'BCC dalam email apa maksud?', options: ['salinan terlihat', 'salinan tersembunyi', 'kopian'], answer: 1 },
      { problem: 'Lampiran dalam surat rasmi apa fungsi?', options: ['tidak perlu', 'sertakan dokumen pendukung', 'hiasan'], answer: 1 },
      { problem: 'Alamat penerima dalam surat di mana?', options: ['bawah salam', 'atas, di bawah tarikh', 'akhir surat'], answer: 1 },
      { problem: 'Rujukan dalam surat rasmi apa guna?', options: ['tidak perlu', 'untuk pengenalan dan rekod', 'hiasan'], answer: 1 },
      { problem: 'Kejelasan dalam surat rasmi apa penting?', options: ['tidak penting', 'sangat penting untuk fahami maksud', 'cadangan'], answer: 1 },
      { problem: 'Kesingkatan dalam surat rasmi apa sebab?', options: ['pemalas', 'hormat masa penerima', 'tidak perlu'], answer: 1 },
      { problem: 'Profesional dalam penulisan surat rasmi apa maksud?', options: ['sulit', 'ringkas dan jelas dengan bahasa baik', 'panjang'], answer: 1 },
    ]}
  },
  {
    title: 'Percakapan Sehari-hari - Situasi',
    type: 'multiple_choice',
    emoji: '💬',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'Di warung kopi, bagaimana pesanan?', options: ['"Saya mahu minuman"', '"Boleh saya pesan kopi dan roti?"', '"Kopi saja"'], answer: 1 },
      { problem: 'Di hospital, bagaimana cakap kepada doktor?', options: ['"Saya sakit"', '"Saya rasa tidak sihat, boleh check?"', '"Tolong saya"'], answer: 1 },
      { problem: 'Di bank, bagaimana tanya?', options: ['"Mana pejabat?"', '"Boleh saya tanya tentang pembukaan akaun?"', '"Saya perlu duit"'], answer: 1 },
      { problem: 'Di sekolah, bagaimana minta izin?', options: ['"Saya pergi"', '"Boleh saya minta izin ke tandas?"', '"Izinkan"'], answer: 1 },
      { problem: 'Bertemu guru, bagaimana sapa?', options: ['"Halo cikgu"', '"Pagi cikgu"', '"Apa kaba cikgu"'], answer: 1 },
      { problem: 'Terima bantuan, apa yang dikatakan?', options: ['"Terima"', '"Terima kasih atas bantuan anda"', '"OK"'], answer: 1 },
      { problem: 'Mohon maaf kepada guru, apa ucapan?', options: ['"Sorry"', '"Saya minta maaf kerana telah..."', '"Tidak sengaja"'], answer: 1 },
      { problem: 'Di telefon, bagaimana buka percakapan?', options: ['"Halo"', '"Assalamu alaikum, siapa nama anda?"', '"Ada siapa?"'], answer: 0 },
      { problem: 'Bertanya waktu kepada orang asing?', options: ['"Berapa jam?"', '"Boleh saya tahu pukul berapa?"', '"Jam berapa?"'], answer: 1 },
      { problem: 'Bertanya arah kepada orang, bagaimana?', options: ['"Mana jalan?"', '"Maaf, boleh tanya di mana stesen bas?"', '"Di situ"'], answer: 1 },
      { problem: 'Jumpa kenalan lama, bagaimana cakap?', options: ['"Salam"', '"Lama tidak berjumpa, apa kabar?"', '"Apa kaba"'], answer: 1 },
      { problem: 'Menjemput tamu ke rumah, apa kata?', options: ['"Masuk saja"', '"Selamat datang, silakan masuk"', '"Duduk di situ"'], answer: 1 },
      { problem: 'Merapatkan persahabatan, apa cakap?', options: ['"Suka kat kamu"', '"Saya harap kita dapat kekal rapat"', '"OK lah"'], answer: 1 },
      { problem: 'Meminta maaf untuk terlambat, apa kata?', options: ['"Maaf"', '"Saya sangat minta maaf kerana terlambat"', '"Tadi sibuk"'], answer: 1 },
      { problem: 'Memberi compliment, bagaimana kata?', options: ['"Bagus"', '"Saya kagum dengan pencapaian anda"', '"Good job"'], answer: 1 },
      { problem: 'Dalam perhimpunan sosial, perkenalkan diri?', options: ['"Nama saya..."', '"Salam, nama saya adalah... dan saya dari..."', '"Saya siapa"'], answer: 1 },
      { problem: 'Menolak ajakan dengan sopan, bagaimana?', options: ['"Tidak"', '"Terima kasih tawarannya tetapi saya tidak boleh"', '"Tak nak"'], answer: 1 },
      { problem: 'Menyetujui ajakan, apa kata?', options: ['"OK"', '"Ya, saya dengan senang hati setuju"', '"Boleh lah"'], answer: 1 },
      { problem: 'Menghubungi orang yang berulang tahun, cakap apa?', options: ['"Happy birthday"', '"Selamat hari jadi, semoga anda berbahagia"', '"Dah tua"'], answer: 1 },
      { problem: 'Ketika berpisah dari teman, bagaimana?', options: ['"Sampai jumpa"', '"Sampai jumpa nanti, jaga kesihatan"', '"Bye"'], answer: 1 },
    ]}
  },
  {
    title: 'Membaca Iklan dan Label Produk',
    type: 'reading',
    emoji: '📢',
    difficulty: 'easy',
    darjah: 3,
    gameData: { questions: [
      { problem: 'Tujuan iklan dalam media apa?', options: ['menghibur saja', 'mempromosi produk atau perkhidmatan', 'cerita saja'], answer: 1 },
      { problem: 'Iklan biasanya mencari siapa?', options: ['semua orang', 'pembeli atau calon pembeli', 'guru'], answer: 1 },
      { problem: 'Label produk apa kegunaan?', options: ['hiasan', 'tunjukkan info produk dan cara guna', 'tidak penting'], answer: 1 },
      { problem: 'Tarikh tamat (expiry date) dalam label apa guna?', options: ['hiasan', 'tunjukkan produk masih baik untuk dimakan', 'tidak penting'], answer: 1 },
      { problem: 'Harga dalam iklan apa tujuan?', options: ['tidak penting', 'tunjukkan berapa kos produk', 'hiasan'], answer: 1 },
      { problem: 'Cara guna dalam label produk apa fungsi?', options: ['tidak perlu', 'tunjukkan cara guna yang betul', 'mencemaskan'], answer: 1 },
      { problem: 'Bahan (ingredients) dalam label apa guna?', options: ['tidak penting', 'tunjukkan apa yang ada dalam produk', 'hiasan'], answer: 1 },
      { problem: 'Jaminan (warranty) dalam iklan apa maksud?', options: ['tidak ada jaminan', 'janji jika produk rosak akan ganti', 'promo'], answer: 1 },
      { problem: 'Diskon dalam iklan apa maksud?', options: ['harga naik', 'harga turun atau potong harga', 'harga sama'], answer: 1 },
      { problem: 'Promo (promotion) dalam iklan apa tujuan?', options: ['menaikkan harga', 'tarik pembeli dengan tawaran istimewa', 'tidak ada guna'], answer: 1 },
      { problem: 'Testimoni dalam iklan siapa?', options: ['pengiklan saja', 'orang yang sudah pakai produk berkomen', 'pengarang'], answer: 1 },
      { problem: 'Warna dan design dalam iklan apa guna?', options: ['tidak penting', 'tarik perhatian dan ingatan pembeli', 'mengacau'], answer: 1 },
      { problem: 'Slogan dalam iklan apa maksud?', options: ['kata-kata panjang', 'kata-kata pendek mudah ingat untuk produk', 'tidak penting'], answer: 1 },
      { problem: 'Gambar dalam iklan apa fungsi?', options: ['hiasan saja', 'tunjukkan produk dan cara gunaannya', 'tidak perlu'], answer: 1 },
      { problem: 'Keputusan pembeli berdasarkan iklan dipengaruhi apa?', options: ['hanya harga', 'teks, gambar, warna, testimonial, etc', 'tidak ada'], answer: 1 },
      { problem: 'Letak produk dalam iklan penting atau tidak?', options: ['tidak penting', 'sangat penting untuk tarik perhatian', 'cadangan'], answer: 1 },
      { problem: 'Perbandingan dengan produk lain dalam iklan apa tujuan?', options: ['tidak ada guna', 'tunjukkan produk lebih baik', 'mengelirukan'], answer: 1 },
      { problem: 'Petua dalam label produk apa maksud?', options: ['cerita', 'saran cara guna terbaik', 'kenyataan saja'], answer: 1 },
      { problem: 'Kod bar (barcode) dalam label apa guna?', options: ['hiasan', 'identifikasi produk dan harga', 'tidak perlu'], answer: 1 },
      { problem: 'Nombor hubungan dalam iklan apa fungsi?', options: ['hiasan', 'hubungi pengiklan jika ada soalan', 'tidak penting'], answer: 1 },
    ]}
  },
];