export const prasekolah_bahasa_tamil_expansion = [
  { title: 'உயிர் எழுத்துக்கள் - விரிவாக்கம்', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'அ', options: ['அ', 'ஆ', 'இ', 'ஈ'], answer: 0 },
    { letter: 'ஆ', options: ['அ', 'ஆ', 'இ', 'ஈ'], answer: 1 },
    { letter: 'இ', options: ['உ', 'ஊ', 'இ', 'ஏ'], answer: 2 },
    { letter: 'ஈ', options: ['அ', 'ஆ', 'இ', 'ஈ'], answer: 3 },
    { letter: 'உ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 0 },
    { letter: 'ஊ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 1 },
    { letter: 'எ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 2 },
    { letter: 'ஏ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 3 },
    { letter: 'ஐ', options: ['ஐ', 'ஒ', 'ஓ', 'ஔ'], answer: 0 },
    { letter: 'ஒ', options: ['ஐ', 'ஒ', 'ஓ', 'ஔ'], answer: 1 },
    { letter: 'ஓ', options: ['ஐ', 'ஒ', 'ஓ', 'ஔ'], answer: 2 },
    { letter: 'ஔ', options: ['ஐ', 'ஒ', 'ஓ', 'ஔ'], answer: 3 },
    { letter: 'அ', options: ['இ', 'அ', 'உ', 'எ'], answer: 1 },
    { letter: 'இ', options: ['அ', 'ஆ', 'இ', 'உ'], answer: 2 },
    { letter: 'உ', options: ['எ', 'ஏ', 'உ', 'ஒ'], answer: 2 },
    { letter: 'எ', options: ['எ', 'ஏ', 'ஐ', 'ஒ'], answer: 0 },
    { letter: 'ஏ', options: ['எ', 'ஏ', 'ஐ', 'ஒ'], answer: 1 },
    { letter: 'ஐ', options: ['எ', 'ஏ', 'ஐ', 'ஒ'], answer: 2 },
    { letter: 'ஒ', options: ['ஐ', 'ஒ', 'ஓ', 'ஔ'], answer: 1 },
    { letter: 'ஓ', options: ['ஐ', 'ஒ', 'ஓ', 'ஔ'], answer: 2 },
  ]}},
  { title: 'விலங்கு சொற்கள் - விரிவாக்கம்', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐘', options: ['யானை', 'ஒட்டகம்', 'நீர்யானை'], answer: 0 },
    { image: '🦁', options: ['சிங்கம்', 'புலி', 'கரடி'], answer: 0 },
    { image: '🐯', options: ['சிங்கம்', 'புலி', 'நரி'], answer: 1 },
    { image: '🐻', options: ['கரடி', 'ஓநாய்', 'நரி'], answer: 0 },
    { image: '🐸', options: ['தவளை', 'ஆமை', 'கோழி'], answer: 0 },
    { image: '🦊', options: ['நாய்', 'நரி', 'ஓநாய்'], answer: 1 },
    { image: '🦓', options: ['குதிரை', 'வரிக்குதிரை', 'கழுதை'], answer: 1 },
    { image: '🐊', options: ['ஆமை', 'முதலை', 'பாம்பு'], answer: 1 },
    { image: '🦒', options: ['ஒட்டகம்', 'ஒட்டகச்சிவிங்கி', 'குதிரை'], answer: 1 },
    { image: '🐋', options: ['திமிங்கலம்', 'சுறாமீன்', 'டாஃல்பின்'], answer: 0 },
    { image: '🦈', options: ['சுறாமீன்', 'திமிங்கலம்', 'மீன்'], answer: 0 },
    { image: '🐧', options: ['பென்குயின்', 'கோழி', 'வாத்து'], answer: 0 },
    { image: '🦅', options: ['காகம்', 'கழுகு', 'குருவி'], answer: 1 },
    { image: '🐝', options: ['ஈ', 'தேனீ', 'வண்ணத்துப்பூச்சி'], answer: 1 },
    { image: '🦋', options: ['ஈ', 'தேனீ', 'வண்ணத்துப்பூச்சி'], answer: 2 },
    { image: '🐢', options: ['ஆமை', 'முதலை', 'பாம்பு'], answer: 0 },
    { image: '🐍', options: ['ஆமை', 'முதலை', 'பாம்பு'], answer: 2 },
    { image: '🦔', options: ['எலி', 'கவரி', 'முள்ளம்பன்றி'], answer: 2 },
    { image: '🦚', options: ['மயில்', 'கோழி', 'வாத்து'], answer: 0 },
    { image: '🦜', options: ['காகம்', 'கிளி', 'குருவி'], answer: 1 },
  ]}},
  { title: 'எண்கள் - ஒன்று முதல் பத்து', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐', options: ['ஒன்று', 'இரண்டு', 'மூன்று'], answer: 0 },
    { problem: '⭐⭐', options: ['ஒன்று', 'இரண்டு', 'மூன்று'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['இரண்டு', 'மூன்று', 'நான்கு'], answer: 1 },
    { problem: '⭐⭐⭐⭐', options: ['மூன்று', 'நான்கு', 'ஐந்து'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['நான்கு', 'ஐந்து', 'ஆறு'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['ஐந்து', 'ஆறு', 'ஏழு'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['ஆறு', 'ஏழு', 'எட்டு'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['ஏழு', 'எட்டு', 'ஒன்பது'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['எட்டு', 'ஒன்பது', 'பத்து'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['ஒன்பது', 'பத்து', 'பதினொன்று'], answer: 1 },
    { problem: 'ஒன்று = ?', options: ['1', '2', '3'], answer: 0 },
    { problem: 'இரண்டு = ?', options: ['1', '2', '3'], answer: 1 },
    { problem: 'மூன்று = ?', options: ['2', '3', '4'], answer: 1 },
    { problem: 'நான்கு = ?', options: ['3', '4', '5'], answer: 1 },
    { problem: 'ஐந்து = ?', options: ['4', '5', '6'], answer: 1 },
    { problem: 'ஆறு = ?', options: ['5', '6', '7'], answer: 1 },
    { problem: 'ஏழு = ?', options: ['6', '7', '8'], answer: 1 },
    { problem: 'எட்டு = ?', options: ['7', '8', '9'], answer: 1 },
    { problem: 'ஒன்பது = ?', options: ['8', '9', '10'], answer: 1 },
    { problem: 'பத்து = ?', options: ['9', '10', '11'], answer: 1 },
  ]}},
  { title: 'வண்ணங்கள் - Tamil PS', type: 'picture_quiz', emoji: '🎨', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['சிவப்பு', 'நீலம்', 'பச்சை'], answer: 0 },
    { image: '🔵', options: ['சிவப்பு', 'நீலம்', 'மஞ்சள்'], answer: 1 },
    { image: '🟢', options: ['ஊதா', 'பச்சை', 'ஆரஞ்சு'], answer: 1 },
    { image: '🟡', options: ['மஞ்சள்', 'ஆரஞ்சு', 'வெள்ளை'], answer: 0 },
    { image: '🟠', options: ['மஞ்சள்', 'ஆரஞ்சு', 'சிவப்பு'], answer: 1 },
    { image: '💜', options: ['ஊதா', 'பிங்க்', 'நீலம்'], answer: 0 },
    { image: '🤎', options: ['கறுப்பு', 'பழுப்பு', 'சாம்பல்'], answer: 1 },
    { image: '⚪', options: ['வெள்ளை', 'கறுப்பு', 'சாம்பல்'], answer: 0 },
    { image: '⚫', options: ['வெள்ளை', 'கறுப்பு', 'பழுப்பு'], answer: 1 },
    { image: '💚', options: ['நீலம்', 'பச்சை', 'மஞ்சள்'], answer: 1 },
    { image: '💙', options: ['நீலம்', 'பச்சை', 'ஊதா'], answer: 0 },
    { image: '❤️', options: ['மஞ்சள்', 'சிவப்பு', 'பச்சை'], answer: 1 },
    { image: '💛', options: ['மஞ்சள்', 'ஆரஞ்சு', 'வெள்ளை'], answer: 0 },
    { image: '🌈', options: ['வெள்ளை', 'வானவில்', 'கறுப்பு'], answer: 1 },
    { image: '☀️', options: ['சிவப்பு', 'மஞ்சள்', 'நீலம்'], answer: 1 },
    { image: '🌿', options: ['பழுப்பு', 'பச்சை', 'மஞ்சள்'], answer: 1 },
    { image: '🌊', options: ['பழுப்பு', 'பச்சை', 'நீலம்'], answer: 2 },
    { image: '🍎', options: ['மஞ்சள்', 'சிவப்பு', 'நீலம்'], answer: 1 },
    { image: '🍌', options: ['மஞ்சள்', 'சிவப்பு', 'பச்சை'], answer: 0 },
    { image: '🍇', options: ['சிவப்பு', 'ஊதா', 'பழுப்பு'], answer: 1 },
  ]}},
  { title: 'பழங்கள் மற்றும் காய்கறிகள்', type: 'picture_quiz', emoji: '🍎', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['ஆப்பிள்', 'ஆரஞ்சு', 'வாழைப்பழம்'], answer: 0 },
    { image: '🍊', options: ['ஆப்பிள்', 'ஆரஞ்சு', 'மாம்பழம்'], answer: 1 },
    { image: '🍌', options: ['வாழைப்பழம்', 'பப்பாளி', 'மாம்பழம்'], answer: 0 },
    { image: '🍇', options: ['திராட்சை', 'ஸ்ட்ராபெர்ரி', 'கொய்யா'], answer: 0 },
    { image: '🍓', options: ['திராட்சை', 'ஸ்ட்ராபெர்ரி', 'ஆப்பிள்'], answer: 1 },
    { image: '🍉', options: ['தர்பூசணி', 'பப்பாளி', 'மாம்பழம்'], answer: 0 },
    { image: '🥭', options: ['பப்பாளி', 'மாம்பழம்', 'துரியன்'], answer: 1 },
    { image: '🥕', options: ['கேரட்', 'தக்காளி', 'வெங்காயம்'], answer: 0 },
    { image: '🍅', options: ['கேரட்', 'தக்காளி', 'பப்பாளி'], answer: 1 },
    { image: '🥦', options: ['ப்ரோக்கோலி', 'முட்டைக்கோஸ்', 'கீரை'], answer: 0 },
    { image: '🌽', options: ['சோளம்', 'வெள்ளரி', 'சுரைக்காய்'], answer: 0 },
    { image: '🥒', options: ['வெள்ளரி', 'கேரட்', 'சுரைக்காய்'], answer: 0 },
    { image: '🧅', options: ['வெங்காயம்', 'உருளைக்கிழங்கு', 'இஞ்சி'], answer: 0 },
    { image: '🥔', options: ['சர்க்கரைவள்ளி', 'உருளைக்கிழங்கு', 'கேரட்'], answer: 1 },
    { image: '🌶️', options: ['மிளகாய்', 'தக்காளி', 'கேரட்'], answer: 0 },
    { image: '🍋', options: ['எலுமிச்சை', 'ஆரஞ்சு', 'ஆப்பிள்'], answer: 0 },
    { image: '🍑', options: ['மாம்பழம்', 'பீச்', 'ஆரஞ்சு'], answer: 1 },
    { image: '🍍', options: ['அன்னாசி', 'மாம்பழம்', 'வாழைப்பழம்'], answer: 0 },
    { image: '🥝', options: ['கிவி', 'ஆப்பிள்', 'திராட்சை'], answer: 0 },
    { image: '🍒', options: ['சேரி', 'திராட்சை', 'ஸ்ட்ராபெர்ரி'], answer: 0 },
  ]}},
  { title: 'உடல் பாகங்கள் - விரிவாக்கம்', type: 'picture_quiz', emoji: '🧒', difficulty: 'easy', gameData: { questions: [
    { image: '👁️', options: ['கண்', 'மூக்கு', 'காது'], answer: 0 },
    { image: '👃', options: ['கண்', 'மூக்கு', 'வாய்'], answer: 1 },
    { image: '👂', options: ['கண்', 'மூக்கு', 'காது'], answer: 2 },
    { image: '👄', options: ['வாய்', 'மூக்கு', 'கண்'], answer: 0 },
    { image: '✋', options: ['கால்', 'கை', 'தோள்'], answer: 1 },
    { image: '🦶', options: ['கால்', 'கை', 'முழங்கால்'], answer: 0 },
    { image: '🦵', options: ['கை', 'கால்', 'தொடை'], answer: 2 },
    { image: '💇', options: ['தலை', 'உடல்', 'வயிறு'], answer: 0 },
    { image: '🦷', options: ['தாடை', 'பல்', 'நாக்கு'], answer: 1 },
    { image: '👅', options: ['பல்', 'நாக்கு', 'உதடு'], answer: 1 },
    { image: '🫀', options: ['நுரையீரல்', 'இதயம்', 'கல்லீரல்'], answer: 1 },
    { image: '🫁', options: ['இதயம்', 'நுரையீரல்', 'வயிறு'], answer: 1 },
    { image: '🧠', options: ['இதயம்', 'மூளை', 'நுரையீரல்'], answer: 1 },
    { image: '🦴', options: ['தசை', 'எலும்பு', 'நரம்பு'], answer: 1 },
    { image: '👃', options: ['கண்', 'மூக்கு', 'காது'], answer: 1 },
    { image: '💪', options: ['கால்', 'கை (தசை)', 'தொடை'], answer: 1 },
    { image: '🦱', options: ['கண்', 'தலைமுடி', 'பல்'], answer: 1 },
    { image: '👂', options: ['காது', 'கண்', 'மூக்கு'], answer: 0 },
    { image: '🫀', options: ['இதயம்', 'வயிறு', 'மூளை'], answer: 0 },
    { image: '🦷', options: ['நாக்கு', 'உதடு', 'பல்'], answer: 2 },
  ]}},
  { title: 'குடும்பம் மற்றும் உறவுகள்', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['அப்பா', 'அம்மா', 'அண்ணன்'], answer: 0 },
    { image: '👩', options: ['அப்பா', 'அம்மா', 'அக்கா'], answer: 1 },
    { image: '👦', options: ['அண்ணன்', 'தம்பி', 'தாத்தா'], answer: 1 },
    { image: '👧', options: ['அக்கா', 'அம்மா', 'பாட்டி'], answer: 0 },
    { image: '👴', options: ['அப்பா', 'தாத்தா', 'அண்ணன்'], answer: 1 },
    { image: '👵', options: ['அம்மா', 'பாட்டி', 'அக்கா'], answer: 1 },
    { image: '👶', options: ['குழந்தை', 'சிறுவன்', 'பெரியவர்'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['நண்பர்கள்', 'குடும்பம்', 'வகுப்பு'], answer: 1 },
    { image: '👫', options: ['நண்பர்கள்', 'குடும்பம்', 'திருமண ஜோடி'], answer: 0 },
    { image: '👨‍👧', options: ['அப்பா மகள்', 'அண்ணன் சகோதரி', 'பாட்டி மகன்'], answer: 0 },
    { image: '👩‍👦', options: ['அம்மா மகன்', 'அப்பா மகன்', 'நண்பர்கள்'], answer: 0 },
    { image: '👴', options: ['அப்பா', 'தாத்தா', 'மாமா'], answer: 1 },
    { image: '👵', options: ['அம்மா', 'பாட்டி', 'அத்தை'], answer: 1 },
    { image: '👶', options: ['தம்பி', 'அண்ணன்', 'குழந்தை'], answer: 2 },
    { image: '👩', options: ['அம்மா', 'அத்தை', 'இரண்டும் சாத்தியம்'], answer: 2 },
    { image: '👨', options: ['அப்பா', 'மாமா', 'இரண்டும் சாத்தியம்'], answer: 2 },
    { image: '👦', options: ['மகன்', 'சிறுவன்', 'இரண்டும்'], answer: 2 },
    { image: '👧', options: ['மகள்', 'சிறுமி', 'இரண்டும்'], answer: 2 },
    { image: '👨‍👩‍👧‍👦', options: ['பள்ளி', 'குடும்பம்', 'கும்பல்'], answer: 1 },
    { image: '👫', options: ['குடும்பம்', 'நண்பர்கள்', 'திருமணம்'], answer: 1 },
  ]}},
  { title: 'வீட்டு பொருட்கள் - Tamil PS', type: 'picture_quiz', emoji: '🏠', difficulty: 'easy', gameData: { questions: [
    { image: '🛋️', options: ['படுக்கை', 'சோபா', 'மேசை'], answer: 1 },
    { image: '🛁', options: ['குளியல் அறை', 'படுக்கை அறை', 'சமையலறை'], answer: 0 },
    { image: '🍳', options: ['கடாய்', 'வாணலி', 'தட்டு'], answer: 1 },
    { image: '🛏️', options: ['படுக்கை', 'சோபா', 'மேசை'], answer: 0 },
    { image: '🪑', options: ['மேசை', 'நாற்காலி', 'படுக்கை'], answer: 1 },
    { image: '📺', options: ['ரேடியோ', 'தொலைக்காட்சி', 'தொலைபேசி'], answer: 1 },
    { image: '🚪', options: ['ஜன்னல்', 'கதவு', 'சுவர்'], answer: 1 },
    { image: '🪟', options: ['கதவு', 'ஜன்னல்', 'சுவர்'], answer: 1 },
    { image: '💡', options: ['மோம்பழுது', 'விளக்கு', 'நெருப்பு'], answer: 1 },
    { image: '🧹', options: ['துடைக்கல்', 'கூட்டு', 'அடுப்பு'], answer: 1 },
    { image: '🪣', options: ['வாளி', 'பாத்திரம்', 'கடாய்'], answer: 0 },
    { image: '🧴', options: ['சோப்பு', 'ஷாம்பூ', 'மாய்ஸ்சர்'], answer: 1 },
    { image: '🧻', options: ['டவல்', 'டிஷ்யூ', 'துணி'], answer: 1 },
    { image: '🥄', options: ['கரண்டி', 'முள்கரண்டி', 'கத்தி'], answer: 0 },
    { image: '🔪', options: ['கரண்டி', 'கத்தி', 'முள்கரண்டி'], answer: 1 },
    { image: '🍽️', options: ['தட்டு', 'கிண்ணம்', 'கோப்பை'], answer: 0 },
    { image: '🫖', options: ['கப்', 'தேயிலை பாத்திரம்', 'பாட்டில்'], answer: 1 },
    { image: '🥤', options: ['பாட்டில்', 'கப்', 'கோப்பை'], answer: 2 },
    { image: '🪴', options: ['மரம்', 'வீட்டுத் தாவரம்', 'புல்'], answer: 1 },
    { image: '🖼️', options: ['கண்ணாடி', 'படம்', 'சித்திரம்'], answer: 1 },
  ]}},
  { title: 'வானம் மற்றும் பருவநிலை - Tamil PS', type: 'picture_quiz', emoji: '⛅', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['சூரியன்', 'நிலவு', 'நட்சத்திரம்'], answer: 0 },
    { image: '🌙', options: ['சூரியன்', 'நிலவு', 'நட்சத்திரம்'], answer: 1 },
    { image: '⭐', options: ['சூரியன்', 'நிலவு', 'நட்சத்திரம்'], answer: 2 },
    { image: '☁️', options: ['மேகம்', 'மழை', 'வெயில்'], answer: 0 },
    { image: '🌧️', options: ['வெயில்', 'மழை', 'காற்று'], answer: 1 },
    { image: '❄️', options: ['மழை', 'பனி', 'காற்று'], answer: 1 },
    { image: '💨', options: ['மழை', 'வெயில்', 'காற்று'], answer: 2 },
    { image: '⛈️', options: ['இடியுடன் மழை', 'காற்று', 'வெயில்'], answer: 0 },
    { image: '🌈', options: ['மழை', 'வானவில்', 'வெயில்'], answer: 1 },
    { image: '🌫️', options: ['புகை', 'மூடுபனி', 'மேகம்'], answer: 1 },
    { image: '☀️', options: ['சூடான நாள்', 'குளிர் நாள்', 'மழை நாள்'], answer: 0 },
    { image: '🌧️', options: ['சூடான நாள்', 'மழை நாள்', 'வெயில் நாள்'], answer: 1 },
    { image: '❄️', options: ['சூடான', 'குளிர்ந்த', 'சீரான'], answer: 1 },
    { image: '☁️', options: ['தெளிவான வானம்', 'மேகமூட்டம்', 'மழை'], answer: 1 },
    { image: '⭐', options: ['பகல்', 'இரவு', 'மாலை'], answer: 1 },
    { image: '☀️', options: ['காலை', 'மாலை', 'இரவு'], answer: 0 },
    { image: '🌅', options: ['சூரியோதயம்', 'சூரிய அஸ்தமனம்', 'பட்டப்பகல்'], answer: 0 },
    { image: '🌇', options: ['சூரியோதயம்', 'சூரிய அஸ்தமனம்', 'நள்ளிரவு'], answer: 1 },
    { image: '🌃', options: ['பகல்', 'இரவு', 'காலை'], answer: 1 },
    { image: '💧', options: ['மழைத்துளி', 'வியர்வை', 'இரண்டும்'], answer: 2 },
  ]}},
  { title: 'அடிப்படை இலக்கணம் - Tamil PS', type: 'multiple_choice', emoji: '📝', difficulty: 'easy', gameData: { questions: [
    { problem: 'பெயர்ச்சொல் என்பது?', options: ['செயல்', 'பெயர்', 'வினை'], answer: 1 },
    { problem: '"மரம்" என்பது?', options: ['வினைச்சொல்', 'பெயர்ச்சொல்', 'உரிச்சொல்'], answer: 1 },
    { problem: '"ஓடுகிறான்" என்பது?', options: ['பெயர்ச்சொல்', 'வினைச்சொல்', 'உரிச்சொல்'], answer: 1 },
    { problem: '"அழகான" என்பது?', options: ['வினைச்சொல்', 'பெயர்ச்சொல்', 'உரிச்சொல்'], answer: 2 },
    { problem: 'வாக்கியம் என்பது?', options: ['ஒரு சொல்', 'சொற்களின் தொகுப்பு', 'எழுத்து'], answer: 1 },
    { problem: '"நான் படிக்கிறேன்" - செயல் என்ன?', options: ['நான்', 'படிக்கிறேன்', 'படிப்பு'], answer: 1 },
    { problem: '"அவள் பாடுகிறாள்" - யார் பாடுகிறார்?', options: ['அவன்', 'அவள்', 'யாரும் இல்லை'], answer: 1 },
    { problem: 'கேள்வி வாக்கியம் எதை கொண்டு முடியும்?', options: ['.', '?', '!'], answer: 1 },
    { problem: 'ஆச்சரிய வாக்கியம் எதை கொண்டு முடியும்?', options: ['.', '?', '!'], answer: 2 },
    { problem: 'தகவல் வாக்கியம் எதை கொண்டு முடியும்?', options: ['.', '?', '!'], answer: 0 },
    { problem: '"குழந்தை அழுகிறது" - பெயர்ச்சொல் எது?', options: ['அழுகிறது', 'குழந்தை', 'இரண்டும்'], answer: 1 },
    { problem: 'ஒருமை என்பது?', options: ['ஒன்று', 'இரண்டு', 'பல'], answer: 0 },
    { problem: 'பன்மை என்பது?', options: ['ஒன்று', 'இரண்டு', 'பல'], answer: 2 },
    { problem: '"மரங்கள்" என்பது?', options: ['ஒருமை', 'பன்மை', 'வேறு'], answer: 1 },
    { problem: '"பூனை" என்பது?', options: ['ஒருமை', 'பன்மை', 'வேறு'], answer: 0 },
    { problem: 'ஆண்பால் என்பது?', options: ['ஆண்', 'பெண்', 'இரண்டும்'], answer: 0 },
    { problem: 'பெண்பால் என்பது?', options: ['ஆண்', 'பெண்', 'இரண்டும்'], answer: 1 },
    { problem: '"அவள்" என்பது எந்த பால்?', options: ['ஆண்பால்', 'பெண்பால்', 'அலிங்கம்'], answer: 1 },
    { problem: '"அவன்" என்பது எந்த பால்?', options: ['ஆண்பால்', 'பெண்பால்', 'அலிங்கம்'], answer: 0 },
    { problem: '"அது" என்பது எந்த பால்?', options: ['ஆண்பால்', 'பெண்பால்', 'அலிங்கம்'], answer: 2 },
  ]}},
  { title: 'அன்றாட வாழ்க்கை - Tamil PS', type: 'picture_quiz', emoji: '⏰', difficulty: 'easy', gameData: { questions: [
    { image: '😴', options: ['தூக்கம்', 'குளியல்', 'சாப்பிடுவது'], answer: 0 },
    { image: '🍳', options: ['குளியல்', 'சாப்பிடுவது', 'விளையாட்டு'], answer: 1 },
    { image: '🚿', options: ['குளியல்', 'தூக்கம்', 'சாப்பிடுவது'], answer: 0 },
    { image: '🎒', options: ['பள்ளி', 'தூக்கம்', 'விளையாட்டு'], answer: 0 },
    { image: '✏️', options: ['விளையாட்டு', 'படிப்பு', 'சாப்பிடுவது'], answer: 1 },
    { image: '🏃', options: ['விளையாட்டு', 'தூக்கம்', 'படிப்பு'], answer: 0 },
    { image: '📚', options: ['தூக்கம்', 'படிப்பு', 'விளையாட்டு'], answer: 1 },
    { image: '🛏️', options: ['குளியல்', 'விளையாட்டு', 'தூக்கம்'], answer: 2 },
    { image: '🧼', options: ['சாப்பிடுவதற்கு முன்', 'தூக்கத்திற்கு முன்', 'பள்ளிக்கு முன்'], answer: 0 },
    { image: '🪥', options: ['காலை', 'இரவு', 'இரண்டும்'], answer: 2 },
    { image: '🍚', options: ['சோறு', 'இட்லி', 'தோசை'], answer: 0 },
    { image: '☕', options: ['தேநீர்', 'காபி', 'பால்'], answer: 1 },
    { image: '📖', options: ['விளையாட்டு', 'படிப்பு', 'சாப்பிடுவது'], answer: 1 },
    { image: '🎮', options: ['விளையாட்டு', 'படிப்பு', 'தூக்கம்'], answer: 0 },
    { image: '🚌', options: ['பள்ளிக்கு செல்வது', 'வீட்டுக்கு திரும்புவது', 'இரண்டும்'], answer: 2 },
    { image: '👗', options: ['குளியல்', 'ஆடை அணிவது', 'சாப்பிடுவது'], answer: 1 },
    { image: '🌙', options: ['காலை', 'மாலை', 'இரவு'], answer: 2 },
    { image: '☀️', options: ['காலை', 'மாலை', 'இரவு'], answer: 0 },
    { image: '🌆', options: ['காலை', 'மாலை', 'இரவு'], answer: 1 },
    { image: '🙏', options: ['சண்டை', 'வணக்கம்', 'ஆட்டம்'], answer: 1 },
  ]}},
];