// Sekolah Rendah - Tamil EXPANSION (20+ soalan per game)
// Tier 1 CRITICAL FIX

export const sekolah_bahasa_tamil_expansion_full = [
  { title: 'Tamil Alphabets Extended', type: 'letter_match', emoji: '🔤', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { letter: 'அ', word: 'Ayyunam', options: ['அ','ஆ','இ','ஈ'], answer: 0 },
    { letter: 'ஆ', word: 'Aakaram', options: ['அ','ஆ','இ','ஈ'], answer: 1 },
    { letter: 'இ', word: 'Ikaram', options: ['அ','ஆ','இ','ஈ'], answer: 2 },
    { letter: 'ஈ', word: 'Eekaram', options: ['அ','ஆ','இ','ஈ'], answer: 3 },
    { letter: 'உ', word: 'Ukaram', options: ['உ','ஊ','எ','ஏ'], answer: 0 },
    { letter: 'ஊ', word: 'Uukaram', options: ['உ','ஊ','எ','ஏ'], answer: 1 },
    { letter: 'எ', word: 'Ekaram', options: ['உ','ஊ','எ','ஏ'], answer: 2 },
    { letter: 'ஏ', word: 'Ekaram', options: ['உ','ஊ','எ','ஏ'], answer: 3 },
    { letter: 'க', word: 'Ka', options: ['க','ச','ட','த'], answer: 0 },
    { letter: 'ச', word: 'Cha', options: ['க','ச','ட','த'], answer: 1 },
    { letter: 'ட', word: 'Ta', options: ['க','ச','ட','த'], answer: 2 },
    { letter: 'த', word: 'Tha', options: ['க','ச','ட','த'], answer: 3 },
    { letter: 'ப', word: 'Pa', options: ['ப','ம','ய','ர'], answer: 0 },
    { letter: 'ம', word: 'Ma', options: ['ப','ம','ய','ர'], answer: 1 },
    { letter: 'ய', word: 'Ya', options: ['ப','ம','ய','ர'], answer: 2 },
    { letter: 'ர', word: 'Ra', options: ['ப','ம','ய','ர'], answer: 3 },
    { letter: 'ல', word: 'La', options: ['ல','வ','ழ','ள'], answer: 0 },
    { letter: 'வ', word: 'Va', options: ['ல','வ','ழ','ள'], answer: 1 },
    { letter: 'ழ', word: 'Zha', options: ['ல','வ','ழ','ள'], answer: 2 },
    { letter: 'ள', word: 'Lha', options: ['ல','வ','ழ','ள'], answer: 3 },
  ]}},
  { title: 'Tamil Numbers Extended', type: 'number_match', emoji: '🔢', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: '௧', options: ['Onru','Irandu','Munu'], answer: 0 },
    { problem: '௨', options: ['Onru','Irandu','Munu'], answer: 1 },
    { problem: '௩', options: ['Irandu','Munu','Nalu'], answer: 1 },
    { problem: '௪', options: ['Munu','Nalu','Ainu'], answer: 1 },
    { problem: '௫', options: ['Nalu','Ainu','Aaru'], answer: 1 },
    { problem: '௬', options: ['Ainu','Aaru','Eelu'], answer: 1 },
    { problem: '௭', options: ['Aaru','Eelu','Ettu'], answer: 1 },
    { problem: '௮', options: ['Eelu','Ettu','Onbathu'], answer: 1 },
    { problem: '௯', options: ['Ettu','Onbathu','Pattu'], answer: 1 },
    { problem: '௰', options: ['Onbathu','Pattu','Nuppattu'], answer: 1 },
    { problem: '௧௦', options: ['Pattu','Nuppattu','Iruppatu'], answer: 1 },
    { problem: '௨௦', options: ['Nuppattu','Iruppatu','Muppatu'], answer: 1 },
    { problem: '௩௦', options: ['Iruppatu','Muppatu','Naarpatu'], answer: 1 },
    { problem: '௪௦', options: ['Muppatu','Naarpatu','Ambattu'], answer: 1 },
    { problem: '௫௦', options: ['Naarpatu','Ambattu','Aimpatu'], answer: 1 },
    { problem: '௭௦', options: ['Ambattu','Aimpatu','Ezhupatu'], answer: 1 },
    { problem: '௯௦', options: ['Aimpatu','Ezhupatu','Tonnuttu'], answer: 1 },
    { problem: '௧௦௰', options: ['Ezhupatu','Tonnuttu','Nooru'], answer: 1 },
    { problem: '൦', options: ['Tonnuttu','Nooru','Aayiram'], answer: 1 },
    { problem: '୧୦୦୦', options: ['Nooru','Aayiram','Pathaayiram'], answer: 1 },
  ]}},
  { title: 'Tamil Family Words Extended', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '👨', options: ['Appa','Amma','Magan'], answer: 0 },
    { image: '👩', options: ['Appa','Amma','Magal'], answer: 1 },
    { image: '👦', options: ['Magan','Magal','Periyappan'], answer: 0 },
    { image: '👧', options: ['Magan','Magal','Akka'], answer: 1 },
    { image: '👴', options: ['Tatha','Patti','Periyappan'], answer: 0 },
    { image: '👵', options: ['Tatha','Patti','Periyamma'], answer: 1 },
    { image: '👶', options: ['Kutty','Payan','Kuzhanthai'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['Kudumbam','Katavar','Katavai'], answer: 0 },
    { image: '🤝', options: ['Annan','Akka','Thozhi'], answer: 2 },
    { image: '💑', options: ['Annan','Akka','Katavar'], answer: 2 },
    { image: '👨‍🦱', options: ['Chinna','Periya','Neeya'], answer: 1 },
    { image: '👩‍🦱', options: ['Chinna','Periya','Neeya'], answer: 2 },
    { image: '🧒', options: ['Kutty','Boodhavan','Ulukuthiyai'], answer: 0 },
    { image: '👨‍🦳', options: ['Tatha','Patti','Periyappan'], answer: 0 },
    { image: '👵', options: ['Patti','Tatha','Ayya'], answer: 0 },
    { image: '🤵', options: ['Katavar','Katavai','Magan'], answer: 0 },
    { image: '👰', options: ['Katavai','Katavar','Magal'], answer: 0 },
    { image: '👨‍👦', options: ['Appa','Amma','Magan'], answer: 0 },
    { image: '👩‍👧', options: ['Amma','Appa','Magal'], answer: 0 },
    { image: '👨‍👩‍👧‍👦', options: ['Kudumbam','Katavar','Katavai'], answer: 0 },
  ]}},
];