export const prasekolah_bahasa_mandarin = [
  {
    title: '数字 1-10 (Nombor 1-10)',
    type: 'number_match',
    emoji: '🔢',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '⭐', options: ['一', '二', '三'], answer: 0 },
      { problem: '⭐⭐', options: ['一', '二', '三'], answer: 1 },
      { problem: '⭐⭐⭐', options: ['二', '三', '四'], answer: 1 },
      { problem: '⭐⭐⭐⭐', options: ['三', '四', '五'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐', options: ['四', '五', '六'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐', options: ['五', '六', '七'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['六', '七', '八'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['七', '八', '九'], answer: 1 },
    ]}
  },
  {
    title: '动物名字 (Nama Haiwan)',
    type: 'picture_quiz',
    emoji: '🐾',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🐱', options: ['猫', '狗', '兔子'], answer: 0 },
      { image: '🐶', options: ['猫', '狗', '鸟'], answer: 1 },
      { image: '🐘', options: ['大象', '马', '斑马'], answer: 0 },
      { image: '🦁', options: ['老虎', '狮子', '熊'], answer: 1 },
      { image: '🐄', options: ['牛', '羊', '猪'], answer: 0 },
      { image: '🐟', options: ['鱼', '螃蟹', '乌龟'], answer: 0 },
      { image: '🦋', options: ['蜻蜓', '蝴蝶', '蜜蜂'], answer: 1 },
      { image: '🐦', options: ['鸡', '鸟', '鸭'], answer: 1 },
    ]}
  },
  {
    title: '颜色 (Warna)',
    type: 'picture_quiz',
    emoji: '🌈',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🔴', options: ['红色', '蓝色', '绿色'], answer: 0 },
      { image: '🔵', options: ['红色', '蓝色', '黄色'], answer: 1 },
      { image: '🟢', options: ['紫色', '绿色', '橙色'], answer: 1 },
      { image: '🟡', options: ['黄色', '橙色', '白色'], answer: 0 },
      { image: '🟠', options: ['黄色', '橙色', '红色'], answer: 1 },
      { image: '💜', options: ['紫色', '粉红色', '蓝色'], answer: 0 },
      { image: '⚫', options: ['棕色', '黑色', '灰色'], answer: 1 },
      { image: '⚪', options: ['白色', '黑色', '灰色'], answer: 0 },
    ]}
  },
  {
    title: '水果名字 (Nama Buah)',
    type: 'picture_quiz',
    emoji: '🍎',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🍎', options: ['苹果', '橙子', '香蕉'], answer: 0 },
      { image: '🍌', options: ['苹果', '香蕉', '芒果'], answer: 1 },
      { image: '🍊', options: ['橙子', '柠檬', '葡萄'], answer: 0 },
      { image: '🍇', options: ['葡萄', '草莓', '樱桃'], answer: 0 },
      { image: '🍓', options: ['葡萄', '草莓', '苹果'], answer: 1 },
      { image: '🥭', options: ['木瓜', '芒果', '榴莲'], answer: 1 },
      { image: '🍉', options: ['西瓜', '木瓜', '芒果'], answer: 0 },
      { image: '🍋', options: ['柠檬', '橙子', '葡萄'], answer: 0 },
    ]}
  },
  {
    title: '家庭成员 (Keluarga)',
    type: 'picture_quiz',
    emoji: '👨‍👩‍👧‍👦',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👨', options: ['爸爸', '妈妈', '哥哥'], answer: 0 },
      { image: '👩', options: ['爸爸', '妈妈', '姐姐'], answer: 1 },
      { image: '👴', options: ['爸爸', '爷爷', '哥哥'], answer: 1 },
      { image: '👵', options: ['妈妈', '奶奶', '姐姐'], answer: 1 },
      { image: '👦', options: ['哥哥', '弟弟', '爷爷'], answer: 0 },
      { image: '👧', options: ['姐姐', '妹妹', '奶奶'], answer: 0 },
      { image: '👶', options: ['宝宝', '弟弟', '小孩'], answer: 0 },
      { image: '👨‍👩‍👧', options: ['家庭', '朋友', '邻居'], answer: 0 },
    ]}
  },
  {
    title: '身体部位 (Anggota Badan)',
    type: 'picture_quiz',
    emoji: '🧒',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👁️', options: ['眼睛', '鼻子', '耳朵'], answer: 0 },
      { image: '👃', options: ['眼睛', '鼻子', '嘴巴'], answer: 1 },
      { image: '👂', options: ['眼睛', '鼻子', '耳朵'], answer: 2 },
      { image: '👄', options: ['嘴巴', '鼻子', '嘴唇'], answer: 0 },
      { image: '✋', options: ['脚', '手', '肩膀'], answer: 1 },
      { image: '🦶', options: ['脚', '手', '手臂'], answer: 0 },
      { image: '💇', options: ['头', '身体', '肚子'], answer: 0 },
      { image: '🧠', options: ['心脏', '大脑', '肺'], answer: 1 },
    ]}
  },
  {
    title: '蔬菜名字 (Sayur-Sayuran)',
    type: 'picture_quiz',
    emoji: '🥦',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🥕', options: ['胡萝卜', '番茄', '洋葱'], answer: 0 },
      { image: '🍅', options: ['胡萝卜', '番茄', '木瓜'], answer: 1 },
      { image: '🥦', options: ['西兰花', '卷心菜', '菠菜'], answer: 0 },
      { image: '🌽', options: ['玉米', '黄瓜', '南瓜'], answer: 0 },
      { image: '🥒', options: ['黄瓜', '胡萝卜', '南瓜'], answer: 0 },
      { image: '🧅', options: ['洋葱', '马铃薯', '生姜'], answer: 0 },
      { image: '🥔', options: ['红薯', '马铃薯', '胡萝卜'], answer: 1 },
      { image: '🌶️', options: ['辣椒', '番茄', '胡萝卜'], answer: 0 },
    ]}
  },
  {
    title: '汉字笔画 (Huruf Cina Mudah)',
    type: 'letter_match',
    emoji: '📝',
    difficulty: 'easy',
    gameData: { questions: [
      { letter: '一', options: ['一', '二', '三', '四'], answer: 0 },
      { letter: '二', options: ['一', '二', '三', '四'], answer: 1 },
      { letter: '三', options: ['一', '二', '三', '四'], answer: 2 },
      { letter: '四', options: ['一', '二', '三', '四'], answer: 3 },
      { letter: '五', options: ['五', '六', '七', '八'], answer: 0 },
      { letter: '六', options: ['五', '六', '七', '八'], answer: 1 },
      { letter: '七', options: ['五', '六', '七', '八'], answer: 2 },
      { letter: '八', options: ['五', '六', '七', '八'], answer: 3 },
    ]}
  },
  {
    title: '问候语 (Ucapan Salam)',
    type: 'multiple_choice',
    emoji: '👋',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '早上打招呼用什么?', options: ['晚安', '早上好', '再见'], answer: 1 },
      { problem: '下午打招呼?', options: ['早上好', '下午好', '晚安'], answer: 1 },
      { problem: '晚上打招呼?', options: ['早上好', '下午好', '晚安'], answer: 2 },
      { problem: '"谢谢"的回答?', options: ['对不起', '不客气', '再见'], answer: 1 },
      { problem: '离别时说?', options: ['你好', '再见', '谢谢'], answer: 1 },
      { problem: '"你好"是什么意思?', options: ['再见', '你好', '谢谢'], answer: 1 },
      { problem: '道歉时说?', options: ['谢谢', '对不起', '再见'], answer: 1 },
      { problem: '请人帮忙时说?', options: ['对不起', '谢谢', '请'], answer: 2 },
    ]}
  },
  {
    title: '食物名字 (Makanan)',
    type: 'picture_quiz',
    emoji: '🍜',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🍚', options: ['米饭', '面包', '面条'], answer: 0 },
      { image: '🍞', options: ['米饭', '面包', '饼干'], answer: 1 },
      { image: '🍜', options: ['米粉', '面条', '意大利面'], answer: 1 },
      { image: '🥛', options: ['牛奶', '水', '果汁'], answer: 0 },
      { image: '🍰', options: ['蛋糕', '糕点', '甜甜圈'], answer: 0 },
      { image: '🍳', options: ['煮鸡蛋', '煎鸡蛋', '炒鸡蛋'], answer: 1 },
      { image: '🥘', options: ['汤', '咖喱', '炖菜'], answer: 1 },
      { image: '🥪', options: ['三明治', '汉堡', '吐司'], answer: 0 },
    ]}
  },
  {
    title: '交通工具 (Kenderaan)',
    type: 'picture_quiz',
    emoji: '🚗',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🚗', options: ['汽车', '公共汽车', '卡车'], answer: 0 },
      { image: '🚌', options: ['汽车', '公共汽车', '面包车'], answer: 1 },
      { image: '✈️', options: ['飞机', '直升机', '轮船'], answer: 0 },
      { image: '🚂', options: ['地铁', '火车', '电车'], answer: 1 },
      { image: '🚲', options: ['自行车', '摩托车', '推车'], answer: 0 },
      { image: '🚁', options: ['飞机', '直升机', '无人机'], answer: 1 },
      { image: '🚢', options: ['船', '渡轮', '轮船'], answer: 2 },
      { image: '🏍️', options: ['自行车', '摩托车', '汽车'], answer: 1 },
    ]}
  },
  {
    title: '情绪表达 (Perasaan)',
    type: 'picture_quiz',
    emoji: '😊',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '😊', options: ['高兴', '难过', '生气'], answer: 0 },
      { image: '😢', options: ['高兴', '难过', '害怕'], answer: 1 },
      { image: '😠', options: ['高兴', '累了', '生气'], answer: 2 },
      { image: '😨', options: ['害怕', '生气', '高兴'], answer: 0 },
      { image: '😴', options: ['难过', '累了', '无聊'], answer: 1 },
      { image: '😂', options: ['笑', '哭', '微笑'], answer: 0 },
      { image: '🤗', options: ['拥抱', '爱', '高兴'], answer: 0 },
      { image: '😍', options: ['惊喜', '爱', '高兴'], answer: 1 },
    ]}
  },
  {
    title: '房间名字 (Nama Bilik)',
    type: 'picture_quiz',
    emoji: '🏠',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🛋️', options: ['卧室', '客厅', '厨房'], answer: 1 },
      { image: '🛁', options: ['浴室', '卧室', '厨房'], answer: 0 },
      { image: '🍳', options: ['饭厅', '厨房', '储藏室'], answer: 1 },
      { image: '🛏️', options: ['卧室', '客厅', '浴室'], answer: 0 },
      { image: '📺', options: ['卧室', '客厅', '厨房'], answer: 1 },
      { image: '📚', options: ['书房', '卧室', '客厅'], answer: 0 },
      { image: '🚪', options: ['窗户', '门', '围栏'], answer: 1 },
      { image: '🏠', options: ['房子', '学校', '商店'], answer: 0 },
    ]}
  },
  {
    title: '学校用品 (Peralatan Sekolah)',
    type: 'picture_quiz',
    emoji: '✏️',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '✏️', options: ['铅笔', '钢笔', '蜡笔'], answer: 0 },
      { image: '📏', options: ['尺子', '剪刀', '橡皮擦'], answer: 0 },
      { image: '📚', options: ['书', '杂志', '笔记'], answer: 0 },
      { image: '🎒', options: ['书包', '手提包', '运动包'], answer: 0 },
      { image: '🖊️', options: ['铅笔', '钢笔', '马克笔'], answer: 1 },
      { image: '📐', options: ['三角尺', '尺子', '圆规'], answer: 0 },
      { image: '🖍️', options: ['彩色铅笔', '蜡笔', '钢笔'], answer: 1 },
      { image: '📓', options: ['练习本', '教科书', '日记'], answer: 0 },
    ]}
  },
  {
    title: '星期 (Hari Dalam Seminggu)',
    type: 'multiple_choice',
    emoji: '📅',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '一周的第一天?', options: ['星期一', '星期日', '星期六'], answer: 1 },
      { problem: '星期一之后是?', options: ['星期日', '星期三', '星期二'], answer: 2 },
      { problem: '一周中间是?', options: ['星期二', '星期三', '星期四'], answer: 1 },
      { problem: '一周有几天?', options: ['5', '6', '7'], answer: 2 },
      { problem: '周末是哪几天?', options: ['星期一星期二', '星期六星期日', '星期三星期四'], answer: 1 },
      { problem: '学校上课是哪几天?', options: ['周末', '星期一到星期五', '每天'], answer: 1 },
      { problem: '星期五之后是?', options: ['星期四', '星期六', '星期日'], answer: 1 },
      { problem: '星期三之前是?', options: ['星期四', '星期二', '星期一'], answer: 1 },
    ]}
  },
  {
    title: '反义词 (Lawan Kata)',
    type: 'multiple_choice',
    emoji: '↔️',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '"大"的反义词?', options: ['小', '长', '高'], answer: 0 },
      { problem: '"热"的反义词?', options: ['温暖', '冷', '湿'], answer: 1 },
      { problem: '"白天"的反义词?', options: ['傍晚', '黑夜', '早晨'], answer: 1 },
      { problem: '"上"的反义词?', options: ['走', '下', '去'], answer: 1 },
      { problem: '"老"的反义词?', options: ['年轻', '小', '矮'], answer: 0 },
      { problem: '"硬"的反义词?', options: ['粗糙', '软', '细'], answer: 1 },
      { problem: '"亮"的反义词?', options: ['暗淡', '黑暗', '昏暗'], answer: 1 },
      { problem: '"胖"的反义词?', options: ['瘦', '小', '矮'], answer: 0 },
    ]}
  },
  {
    title: '月份 (Bulan Dalam Setahun)',
    type: 'multiple_choice',
    emoji: '📆',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '一年的第一个月?', options: ['二月', '一月', '三月'], answer: 1 },
      { problem: '一年有几个月?', options: ['10', '11', '12'], answer: 2 },
      { problem: '一年的最后一个月?', options: ['十一月', '十月', '十二月'], answer: 2 },
      { problem: '四月之后是?', options: ['三月', '五月', '六月'], answer: 1 },
      { problem: '第六个月是?', options: ['五月', '六月', '七月'], answer: 1 },
      { problem: '十二月之前是?', options: ['十月', '十一月', '九月'], answer: 1 },
      { problem: '情人节是哪个月?', options: ['一月', '二月', '三月'], answer: 1 },
      { problem: '第二个月是?', options: ['一月', '二月', '三月'], answer: 1 },
    ]}
  },
  {
    title: '自然界 (Alam Semula Jadi)',
    type: 'picture_quiz',
    emoji: '🌿',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🌳', options: ['树', '草', '花'], answer: 0 },
      { image: '🌸', options: ['树', '花', '叶子'], answer: 1 },
      { image: '🌊', options: ['河流', '海洋', '湖泊'], answer: 1 },
      { image: '☀️', options: ['太阳', '月亮', '星星'], answer: 0 },
      { image: '🌙', options: ['太阳', '月亮', '星星'], answer: 1 },
      { image: '🌧️', options: ['晴天', '下雨', '刮风'], answer: 1 },
      { image: '🌈', options: ['雨后彩虹', '白天', '晚上'], answer: 0 },
      { image: '⛰️', options: ['山丘', '山', '平原'], answer: 1 },
    ]}
  },
  {
    title: '健康生活 (Gaya Hidup Sihat)',
    type: 'multiple_choice',
    emoji: '💪',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '保持健康需要什么?', options: ['多吃甜食', '吃蔬菜水果', '吃炸食'], answer: 1 },
      { problem: '儿童每天需要几小时睡眠?', options: ['4小时', '8小时', '10-12小时'], answer: 2 },
      { problem: '每天要喝多少水?', options: ['很少', '足够多', '每年一次'], answer: 1 },
      { problem: '游泳是什么?', options: ['玩耍', '休息', '运动'], answer: 2 },
      { problem: '吃饭前要做什么?', options: ['学习', '睡觉', '洗手'], answer: 2 },
      { problem: '刷牙几次?', options: ['只早上', '早晚各一次', '每周一次'], answer: 1 },
      { problem: '运动对我们有什么好处?', options: ['生病', '保持健康', '疲劳'], answer: 1 },
      { problem: '骑自行车是什么?', options: ['玩耍', '运动', '工作'], answer: 1 },
    ]}
  },
  {
    title: '汉字认识 - 基础 (Huruf Cina Asas)',
    type: 'letter_match',
    emoji: '🔤',
    difficulty: 'easy',
    gameData: { questions: [
      { letter: '人', options: ['人', '大', '小', '山'], answer: 0 },
      { letter: '大', options: ['人', '大', '小', '山'], answer: 1 },
      { letter: '小', options: ['人', '大', '小', '山'], answer: 2 },
      { letter: '山', options: ['人', '大', '小', '山'], answer: 3 },
      { letter: '水', options: ['水', '火', '土', '木'], answer: 0 },
      { letter: '火', options: ['水', '火', '土', '木'], answer: 1 },
      { letter: '土', options: ['水', '火', '土', '木'], answer: 2 },
      { letter: '木', options: ['水', '火', '土', '木'], answer: 3 },
    ]}
  },
  {
    title: '小故事 - 小猫和小狗',
    type: 'multiple_choice',
    emoji: '📖',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '故事: "小猫和小狗是好朋友。他们在公园里玩。" - 谁是好朋友?', options: ['小猫和小鸟', '小猫和小狗', '小狗和小鸟'], answer: 1 },
      { problem: '他们在哪里玩?', options: ['学校', '公园', '家里'], answer: 1 },
      { problem: '故事里有几只动物?', options: ['1', '2', '3'], answer: 1 },
      { problem: '他们的关系是?', options: ['敌人', '好朋友', '陌生人'], answer: 1 },
      { problem: '故事教给我们什么?', options: ['打架', '交朋友', '跑步'], answer: 1 },
      { problem: '小猫在哪里?', options: ['学校', '公园', '家里'], answer: 1 },
      { problem: '小狗做了什么?', options: ['睡觉', '玩耍', '吃东西'], answer: 1 },
      { problem: '故事是关于什么的?', options: ['食物', '友谊', '学习'], answer: 1 },
    ]}
  },
  {
    title: '好习惯 (Adab Baik)',
    type: 'multiple_choice',
    emoji: '🙏',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '吃饭前要做什么?', options: ['玩耍', '洗手', '跑步'], answer: 1 },
      { problem: '见到老师要说什么?', options: ['嗨!', '老师好!', '随便'], answer: 1 },
      { problem: '别人帮助你后要说什么?', options: ['没关系', '谢谢!', '走开'], answer: 1 },
      { problem: '做错事要说什么?', options: ['不管', '对不起', '不知道'], answer: 1 },
      { problem: '垃圾应该放在哪里?', options: ['地上', '垃圾桶', '任何地方'], answer: 1 },
      { problem: '在教室里应该做什么?', options: ['大声喊叫', '认真听课', '睡觉'], answer: 1 },
      { problem: '帮助朋友是?', options: ['不好的', '好的', '不对的'], answer: 1 },
      { problem: '要排队等待是?', options: ['浪费时间', '礼貌的行为', '不必要的'], answer: 1 },
    ]}
  },
  {
    title: '植物认识 (Tumbuhan)',
    type: 'picture_quiz',
    emoji: '🌱',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🌹', options: ['玫瑰', '向日葵', '郁金香'], answer: 0 },
      { image: '🌻', options: ['玫瑰', '向日葵', '百合'], answer: 1 },
      { image: '🌺', options: ['芙蓉花', '兰花', '玫瑰'], answer: 0 },
      { image: '🌴', options: ['椰子树', '酸豆树', '榴莲树'], answer: 0 },
      { image: '🍃', options: ['叶子', '根', '茎'], answer: 0 },
      { image: '🌾', options: ['稻米', '玉米', '椰子树'], answer: 0 },
      { image: '🌵', options: ['仙人掌', '玫瑰', '稻米'], answer: 0 },
      { image: '🍄', options: ['蘑菇', '花', '树'], answer: 0 },
    ]}
  },
  {
    title: '天气认识 (Cuaca)',
    type: 'picture_quiz',
    emoji: '⛅',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '☀️', options: ['下雨', '晴天', '寒冷'], answer: 1 },
      { image: '🌧️', options: ['晴天', '下雨', '刮风'], answer: 1 },
      { image: '🌈', options: ['雨后', '白天', '夜晚'], answer: 0 },
      { image: '⛈️', options: ['暴风雨', '晴天', '刮风'], answer: 0 },
      { image: '☁️', options: ['云', '下雨', '晴天'], answer: 0 },
      { image: '❄️', options: ['晴天', '寒冷', '下雨'], answer: 1 },
      { image: '💨', options: ['下雨', '晴天', '刮风'], answer: 2 },
      { image: '🌤️', options: ['局部多云', '晴天', '下雨'], answer: 0 },
    ]}
  },
  {
    title: '职业认识 (Kerjaya)',
    type: 'picture_quiz',
    emoji: '👔',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👨‍⚕️', options: ['医生', '老师', '工程师'], answer: 0 },
      { image: '👩‍🏫', options: ['医生', '老师', '护士'], answer: 1 },
      { image: '👮', options: ['消防员', '警察', '医生'], answer: 1 },
      { image: '🧑‍🍳', options: ['厨师', '老师', '医生'], answer: 0 },
      { image: '🧑‍🌾', options: ['医生', '农民', '木匠'], answer: 1 },
      { image: '✈️', options: ['飞行员', '医生', '船长'], answer: 0 },
      { image: '🚒', options: ['警察', '消防员', '医生'], answer: 1 },
      { image: '📚', options: ['老师', '医生', '工程师'], answer: 0 },
    ]}
  },
  {
    title: '数字 11-20 (Nombor 11-20)',
    type: 'number_match',
    emoji: '🔢',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '11', options: ['十一', '十二', '十三'], answer: 0 },
      { problem: '12', options: ['十一', '十二', '十三'], answer: 1 },
      { problem: '15', options: ['十四', '十五', '十六'], answer: 1 },
      { problem: '17', options: ['十六', '十七', '十八'], answer: 1 },
      { problem: '20', options: ['十九', '二十', '二十一'], answer: 1 },
      { problem: '十五 = ?', options: ['14', '15', '16'], answer: 1 },
      { problem: '十二 = ?', options: ['11', '12', '13'], answer: 1 },
      { problem: '二十 = ?', options: ['19', '20', '21'], answer: 1 },
    ]}
  },
  {
    title: '形状认识 (Bentuk)',
    type: 'picture_quiz',
    emoji: '🔵',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '⭕', options: ['圆形', '正方形', '三角形'], answer: 0 },
      { image: '⬜', options: ['圆形', '正方形', '三角形'], answer: 1 },
      { image: '△', options: ['圆形', '正方形', '三角形'], answer: 2 },
      { image: '▭', options: ['长方形', '正方形', '椭圆形'], answer: 0 },
      { image: '⭐', options: ['星形', '圆形', '三角形'], answer: 0 },
      { image: '🔶', options: ['菱形', '六边形', '正方形'], answer: 0 },
      { image: '🔷', options: ['菱形', '椭圆形', '三角形'], answer: 0 },
      { image: '🟣', options: ['球', '圆形', '椭圆形'], answer: 1 },
    ]}
  },
];