// Sekolah Rendah - English EXPANSION (20+ soalan per game)
// Tier 1 CRITICAL FIX

export const sekolah_english_expansion_full = [
  { title: 'Alphabet A-Z Extended', type: 'letter_match', emoji: '🔤', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Apple', options: ['A','B','C','D'], answer: 0 },
    { letter: 'B', emoji: '🐦', word: 'Bird', options: ['A','B','C','D'], answer: 1 },
    { letter: 'C', emoji: '🐱', word: 'Cat', options: ['A','B','C','D'], answer: 2 },
    { letter: 'D', emoji: '🐕', word: 'Dog', options: ['A','B','C','D'], answer: 3 },
    { letter: 'E', emoji: '🐘', word: 'Elephant', options: ['D','E','F','G'], answer: 1 },
    { letter: 'F', emoji: '🐟', word: 'Fish', options: ['D','E','F','G'], answer: 2 },
    { letter: 'G', emoji: '🍇', word: 'Grapes', options: ['E','F','G','H'], answer: 2 },
    { letter: 'H', emoji: '🏠', word: 'House', options: ['F','G','H','I'], answer: 2 },
    { letter: 'I', emoji: '🕷️', word: 'Ice cream', options: ['H','I','J','K'], answer: 1 },
    { letter: 'J', emoji: '🤹', word: 'Jelly', options: ['H','I','J','K'], answer: 2 },
    { letter: 'K', emoji: '🔑', word: 'Key', options: ['J','K','L','M'], answer: 1 },
    { letter: 'L', emoji: '🦁', word: 'Lion', options: ['K','L','M','N'], answer: 1 },
    { letter: 'M', emoji: '🍌', word: 'Mango', options: ['L','M','N','O'], answer: 1 },
    { letter: 'N', emoji: '📰', word: 'Newspaper', options: ['M','N','O','P'], answer: 1 },
    { letter: 'O', emoji: '🍊', word: 'Orange', options: ['N','O','P','Q'], answer: 1 },
    { letter: 'P', emoji: '🐧', word: 'Penguin', options: ['O','P','Q','R'], answer: 1 },
    { letter: 'Q', emoji: '👑', word: 'Queen', options: ['P','Q','R','S'], answer: 1 },
    { letter: 'R', emoji: '🌹', word: 'Rose', options: ['Q','R','S','T'], answer: 1 },
    { letter: 'S', emoji: '🌞', word: 'Sun', options: ['R','S','T','U'], answer: 1 },
    { letter: 'T', emoji: '🐯', word: 'Tiger', options: ['S','T','U','V'], answer: 1 },
  ]}},
  { title: 'Animal Names Extended', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '🐱', options: ['Cat','Dog','Rabbit'], answer: 0 },
    { image: '🐶', options: ['Cat','Dog','Bird'], answer: 1 },
    { image: '🐟', options: ['Fish','Bird','Snake'], answer: 0 },
    { image: '🐓', options: ['Fish','Chicken','Duck'], answer: 1 },
    { image: '🐘', options: ['Elephant','Horse','Rhino'], answer: 0 },
    { image: '🦁', options: ['Lion','Tiger','Bear'], answer: 0 },
    { image: '🐧', options: ['Penguin','Chicken','Duck'], answer: 0 },
    { image: '🐰', options: ['Rabbit','Squirrel','Mouse'], answer: 0 },
    { image: '🐄', options: ['Cow','Buffalo','Sheep'], answer: 0 },
    { image: '🦒', options: ['Giraffe','Horse','Deer'], answer: 0 },
    { image: '🐢', options: ['Turtle','Crocodile','Snake'], answer: 0 },
    { image: '🦋', options: ['Butterfly','Bee','Beetle'], answer: 0 },
    { image: '🐝', options: ['Butterfly','Bee','Bug'], answer: 1 },
    { image: '🦜', options: ['Eagle','Parrot','Raven'], answer: 1 },
    { image: '🦅', options: ['Eagle','Parrot','Sparrow'], answer: 0 },
    { image: '🐸', options: ['Frog','Snake','Turtle'], answer: 0 },
    { image: '🦔', options: ['Hedgehog','Mouse','Rabbit'], answer: 0 },
    { image: '🦓', options: ['Horse','Zebra','Donkey'], answer: 1 },
    { image: '🐉', options: ['Dragon','Lizard','Crocodile'], answer: 0 },
    { image: '🦒', options: ['Giraffe','Zebra','Antelope'], answer: 0 },
  ]}},
  { title: 'Simple Verbs Extended', type: 'multiple_choice', emoji: '⚡', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: 'What is an action word?', options: ['jump','happy','blue'], answer: 0 },
    { problem: 'Which is a verb?', options: ['table','run','big'], answer: 1 },
    { problem: 'Which shows action?', options: ['eat','book','red'], answer: 0 },
    { problem: 'Which is a verb?', options: ['sit','chair','small'], answer: 0 },
    { problem: 'Which shows movement?', options: ['dance','yellow','fast'], answer: 0 },
    { problem: 'Which verb means to move quickly?', options: ['walk','run','sit'], answer: 1 },
    { problem: 'Which verb means to eat?', options: ['drink','eat','sleep'], answer: 1 },
    { problem: 'Which verb means to close eyes?', options: ['open','sleep','write'], answer: 1 },
    { problem: 'Which verb means to listen?', options: ['see','hear','smell'], answer: 1 },
    { problem: 'Which verb means to look at?', options: ['see','hear','taste'], answer: 0 },
    { problem: 'Which verb means to hold?', options: ['catch','drop','throw'], answer: 0 },
    { problem: 'Which verb means to throw?', options: ['catch','drop','throw'], answer: 2 },
    { problem: 'Which verb means to play?', options: ['study','work','play'], answer: 2 },
    { problem: 'Which verb means to write?', options: ['read','write','draw'], answer: 1 },
    { problem: 'Which verb means to paint?', options: ['draw','paint','sing'], answer: 1 },
    { problem: 'Which verb means to sing?', options: ['dance','sing','laugh'], answer: 1 },
    { problem: 'Which verb means to swim?', options: ['run','swim','jump'], answer: 1 },
    { problem: 'Which verb means to build?', options: ['make','build','create'], answer: 1 },
    { problem: 'Which verb means to help?', options: ['aid','help','assist'], answer: 1 },
    { problem: 'Which verb means to clean?', options: ['wash','clean','wipe'], answer: 1 },
  ]}},
];