export const prasekolah_bahasa_melayu = [
  { title: 'Huruf ABC - A hingga F', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Epal', options: ['A','B','C','D'], answer: 0 },
    { letter: 'B', emoji: '🐦', word: 'Burung', options: ['A','B','C','D'], answer: 1 },
    { letter: 'C', emoji: '🐱', word: 'Kucing', options: ['A','B','C','D'], answer: 2 },
    { letter: 'D', emoji: '🐕', word: 'Anjing', options: ['A','B','C','D'], answer: 3 },
    { letter: 'E', emoji: '🐘', word: 'Gajah', options: ['D','E','F','G'], answer: 1 },
    { letter: 'F', emoji: '🐟', word: 'Ikan', options: ['D','E','F','G'], answer: 2 },
    { letter: 'G', emoji: '🍇', word: 'Anggur', options: ['E','F','G','H'], answer: 2 },
    { letter: 'H', emoji: '🏠', word: 'Rumah', options: ['F','G','H','I'], answer: 2 },
  ]}},
  { title: 'Huruf Vokal A, E, I, O, U', type: 'letter_match', emoji: '🅰️', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Epal', options: ['A','E','I','O'], answer: 0 },
    { letter: 'E', emoji: '🥚', word: 'Telur', options: ['A','E','I','O'], answer: 1 },
    { letter: 'I', emoji: '🍦', word: 'Ais Krim', options: ['A','E','I','O'], answer: 2 },
    { letter: 'O', emoji: '🍊', word: 'Oren', options: ['A','E','I','O'], answer: 3 },
    { letter: 'U', emoji: '☂️', word: 'Payung', options: ['I','U','E','O'], answer: 1 },
    { letter: 'A', emoji: '🐊', word: 'Buaya', options: ['U','A','I','O'], answer: 1 },
    { letter: 'E', emoji: '🦅', word: 'Helang', options: ['A','E','U','I'], answer: 1 },
    { letter: 'I', emoji: '🐟', word: 'Ikan', options: ['U','O','I','A'], answer: 2 },
  ]}},
  { title: 'Nama Haiwan', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Kucing','Anjing','Kelinci'], answer: 0 },
    { image: '🐶', options: ['Kucing','Anjing','Burung'], answer: 1 },
    { image: '🦁', options: ['Singa','Harimau','Beruang'], answer: 0 },
    { image: '🐘', options: ['Gajah','Kuda','Zebra'], answer: 0 },
    { image: '🐧', options: ['Penguin','Ayam','Itik'], answer: 0 },
    { image: '🦒', options: ['Jerapah','Rusa','Kuda'], answer: 0 },
    { image: '🐻', options: ['Beruang','Serigala','Singa'], answer: 0 },
    { image: '🦓', options: ['Zebra','Kuda','Kijang'], answer: 0 },
  ]}},
  { title: 'Suara Haiwan', type: 'sound_match', emoji: '🔊', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Meow','Woof','Moo','Baa'], answer: 0 },
    { image: '🐶', options: ['Meow','Woof','Moo','Baa'], answer: 1 },
    { image: '🐄', options: ['Meow','Woof','Moo','Baa'], answer: 2 },
    { image: '🐑', options: ['Meow','Woof','Moo','Baa'], answer: 3 },
    { image: '🦆', options: ['Quack','Hiss','Chirp','Roar'], answer: 0 },
    { image: '🐍', options: ['Quack','Hiss','Chirp','Roar'], answer: 1 },
    { image: '🐦', options: ['Quack','Hiss','Chirp','Roar'], answer: 2 },
    { image: '🦁', options: ['Quack','Hiss','Chirp','Roar'], answer: 3 },
  ]}},
  { title: 'Nama Buah-Buahan', type: 'picture_quiz', emoji: '🍓', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['Epal','Oren','Pisang'], answer: 0 },
    { image: '🍊', options: ['Epal','Oren','Mangga'], answer: 1 },
    { image: '🍌', options: ['Pisang','Betik','Ciku'], answer: 0 },
    { image: '🍇', options: ['Anggur','Strawberi','Ceri'], answer: 0 },
    { image: '🍓', options: ['Anggur','Strawberi','Epal'], answer: 1 },
    { image: '🍉', options: ['Tembikai','Betik','Mangga'], answer: 0 },
    { image: '🥭', options: ['Betik','Mangga','Durian'], answer: 1 },
    { image: '🍋', options: ['Limau','Oren','Lemon'], answer: 2 },
  ]}},
  { title: 'Nama Warna', type: 'picture_quiz', emoji: '🎨', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Merah','Biru','Hijau'], answer: 0 },
    { image: '🔵', options: ['Merah','Biru','Kuning'], answer: 1 },
    { image: '🟢', options: ['Ungu','Hijau','Oren'], answer: 1 },
    { image: '🟡', options: ['Kuning','Oren','Putih'], answer: 0 },
    { image: '🟠', options: ['Kuning','Oren','Merah'], answer: 1 },
    { image: '💜', options: ['Ungu','Merah Jambu','Biru'], answer: 0 },
    { image: '🤎', options: ['Hitam','Coklat','Kelabu'], answer: 1 },
    { image: '⚪', options: ['Putih','Hitam','Kelabu'], answer: 0 },
  ]}},
  { title: 'Nama Sayur-Sayuran', type: 'picture_quiz', emoji: '🥦', difficulty: 'easy', gameData: { questions: [
    { image: '🥕', options: ['Lobak Merah','Tomato','Bawang'], answer: 0 },
    { image: '🍅', options: ['Lobak','Tomato','Betik'], answer: 1 },
    { image: '🥦', options: ['Brokoli','Kobis','Bayam'], answer: 0 },
    { image: '🌽', options: ['Jagung','Timun','Labu'], answer: 0 },
    { image: '🥒', options: ['Timun','Lobak','Labu'], answer: 0 },
    { image: '🧅', options: ['Bawang','Kentang','Halia'], answer: 0 },
    { image: '🥔', options: ['Ubi','Kentang','Lobak'], answer: 1 },
    { image: '🌶️', options: ['Cili','Tomato','Lobak'], answer: 0 },
  ]}},
  { title: 'Anggota Keluarga', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['Ayah','Ibu','Abang'], answer: 0 },
    { image: '👩', options: ['Ayah','Ibu','Kakak'], answer: 1 },
    { image: '👦', options: ['Abang','Adik Lelaki','Datuk'], answer: 1 },
    { image: '👧', options: ['Kakak','Nenek','Ibu'], answer: 0 },
    { image: '👴', options: ['Ayah','Datuk','Abang'], answer: 1 },
    { image: '👵', options: ['Ibu','Nenek','Kakak'], answer: 1 },
    { image: '👶', options: ['Bayi','Adik','Budak'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['Keluarga','Kawan','Jiran'], answer: 0 },
  ]}},
  { title: 'Huruf I hingga N', type: 'letter_match', emoji: '🔡', difficulty: 'easy', gameData: { questions: [
    { letter: 'I', emoji: '🐟', word: 'Ikan', options: ['I','J','K','L'], answer: 0 },
    { letter: 'J', emoji: '🌉', word: 'Jambatan', options: ['I','J','K','L'], answer: 1 },
    { letter: 'K', emoji: '🐴', word: 'Kuda', options: ['I','J','K','L'], answer: 2 },
    { letter: 'L', emoji: '🌊', word: 'Laut', options: ['I','J','K','L'], answer: 3 },
    { letter: 'M', emoji: '🌙', word: 'Malam', options: ['M','N','O','P'], answer: 0 },
    { letter: 'N', emoji: '🌰', word: 'Nangka', options: ['M','N','O','P'], answer: 1 },
    { letter: 'O', emoji: '🐙', word: 'Sotong', options: ['M','N','O','P'], answer: 2 },
    { letter: 'P', emoji: '🦚', word: 'Merak', options: ['M','N','O','P'], answer: 3 },
  ]}},
  { title: 'Perkataan Pertama Saya', type: 'picture_quiz', emoji: '💬', difficulty: 'easy', gameData: { questions: [
    { image: '🏠', options: ['Rumah','Sekolah','Kedai'], answer: 0 },
    { image: '🚗', options: ['Bas','Kereta','Lori'], answer: 1 },
    { image: '📚', options: ['Buku','Pensil','Kertas'], answer: 0 },
    { image: '🎒', options: ['Beg','Buku','Kotak'], answer: 0 },
    { image: '✏️', options: ['Pen','Pensil','Pensel'], answer: 1 },
    { image: '🍽️', options: ['Pinggan','Mangkuk','Cawan'], answer: 0 },
    { image: '🛏️', options: ['Katil','Kerusi','Meja'], answer: 0 },
    { image: '🪑', options: ['Meja','Kerusi','Almari'], answer: 1 },
  ]}},
  { title: 'Huruf O hingga S', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'O', emoji: '🐙', word: 'Sotong', options: ['O','P','Q','R'], answer: 0 },
    { letter: 'P', emoji: '🦚', word: 'Merak', options: ['O','P','Q','R'], answer: 1 },
    { letter: 'Q', emoji: '👑', word: 'Mahkota', options: ['O','P','Q','R'], answer: 2 },
    { letter: 'R', emoji: '🌹', word: 'Ros', options: ['O','P','Q','R'], answer: 3 },
    { letter: 'S', emoji: '⭐', word: 'Bintang', options: ['R','S','T','U'], answer: 1 },
    { letter: 'T', emoji: '🐯', word: 'Harimau', options: ['R','S','T','U'], answer: 2 },
    { letter: 'U', emoji: '☂️', word: 'Payung', options: ['R','S','T','U'], answer: 3 },
    { letter: 'V', emoji: '🎻', word: 'Biola', options: ['S','T','U','V'], answer: 3 },
  ]}},
  { title: 'Nama Pakaian', type: 'picture_quiz', emoji: '👕', difficulty: 'easy', gameData: { questions: [
    { image: '👕', options: ['Baju','Seluar','Kasut'], answer: 0 },
    { image: '👖', options: ['Baju','Seluar','Topi'], answer: 1 },
    { image: '👟', options: ['Sandal','Kasut','Stokin'], answer: 1 },
    { image: '🧦', options: ['Stokin','Kasut','Sarung'], answer: 0 },
    { image: '🧢', options: ['Topi','Tudung','Skaf'], answer: 0 },
    { image: '👗', options: ['Baju','Gaun','Seluar'], answer: 1 },
    { image: '🧥', options: ['Jaket','Baju','Seluar'], answer: 0 },
    { image: '👔', options: ['Tali Leher','T-shirt','Baju Melayu'], answer: 0 },
  ]}},
  { title: 'Nama Pengangkutan', type: 'picture_quiz', emoji: '🚗', difficulty: 'easy', gameData: { questions: [
    { image: '🚗', options: ['Kereta','Bas','Lori'], answer: 0 },
    { image: '🚌', options: ['Kereta','Bas','Van'], answer: 1 },
    { image: '✈️', options: ['Kapal Terbang','Helikopter','Kapal'], answer: 0 },
    { image: '🚢', options: ['Bot','Feri','Kapal'], answer: 2 },
    { image: '🚂', options: ['LRT','Kereta Api','Tram'], answer: 1 },
    { image: '🏍️', options: ['Basikal','Motosikal','Kereta'], answer: 1 },
    { image: '🚲', options: ['Basikal','Motosikal','Troli'], answer: 0 },
    { image: '🚁', options: ['Kapal Terbang','Helikopter','Dron'], answer: 1 },
  ]}},
  { title: 'Nama Bilik di Rumah', type: 'picture_quiz', emoji: '🏠', difficulty: 'easy', gameData: { questions: [
    { image: '🛋️', options: ['Bilik Tidur','Ruang Tamu','Dapur'], answer: 1 },
    { image: '🛁', options: ['Bilik Air','Bilik Tidur','Dapur'], answer: 0 },
    { image: '🍳', options: ['Ruang Makan','Dapur','Stor'], answer: 1 },
    { image: '🛏️', options: ['Bilik Tidur','Ruang Tamu','Bilik Air'], answer: 0 },
    { image: '🍽️', options: ['Dapur','Ruang Makan','Ruang Tamu'], answer: 1 },
    { image: '📺', options: ['Bilik Tidur','Ruang Tamu','Dapur'], answer: 1 },
    { image: '📚', options: ['Bilik Belajar','Bilik Tidur','Ruang Tamu'], answer: 0 },
    { image: '🚪', options: ['Tingkap','Pintu','Pagar'], answer: 1 },
  ]}},
  { title: 'Nama Jenis Makanan', type: 'picture_quiz', emoji: '🍜', difficulty: 'easy', gameData: { questions: [
    { image: '🍚', options: ['Nasi','Roti','Mee'], answer: 0 },
    { image: '🍞', options: ['Nasi','Roti','Biskut'], answer: 1 },
    { image: '🍜', options: ['Mihun','Mee','Spaghetti'], answer: 1 },
    { image: '🍳', options: ['Telur Goreng','Telur Rebus','Telur Dadar'], answer: 0 },
    { image: '🥘', options: ['Sup','Kari','Gulai'], answer: 1 },
    { image: '🍰', options: ['Kek','Kuih','Donat'], answer: 0 },
    { image: '🍱', options: ['Bento','Nasi Lemak','Nasi Kotak'], answer: 0 },
    { image: '🥞', options: ['Waffle','Pancake','Crepe'], answer: 1 },
  ]}},
  { title: 'Penjodoh Bilangan Mudah', type: 'multiple_choice', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: 'Seekor ___ (satu haiwan)', options: ['kereta','kucing','rumah'], answer: 1 },
    { problem: 'Sebuah ___ (satu benda besar)', options: ['burung','rumah','pensel'], answer: 1 },
    { problem: 'Sebatang ___ (satu barang panjang)', options: ['pensil','buku','kasut'], answer: 0 },
    { problem: 'Sehelai ___ (satu benda tipis)', options: ['kertas','batu','botol'], answer: 0 },
    { problem: 'Sepasang ___ (dua yang sama)', options: ['kasut','buku','mata'], answer: 0 },
    { problem: 'Sekawan ___ (banyak)', options: ['itik','kucing','pokok'], answer: 0 },
    { problem: 'Sebiji ___ (satu buah)', options: ['epal','kertas','kasut'], answer: 0 },
    { problem: 'Seorang ___ (satu orang)', options: ['budak','kucing','kereta'], answer: 0 },
  ]}},
  { title: 'Kata Ganti Nama', type: 'multiple_choice', emoji: '👤', difficulty: 'easy', gameData: { questions: [
    { problem: 'Kata ganti nama diri pertama?', options: ['Dia','Saya','Mereka'], answer: 1 },
    { problem: 'Kata ganti nama diri kedua?', options: ['Saya','Kamu','Mereka'], answer: 1 },
    { problem: 'Kata ganti nama diri ketiga?', options: ['Saya','Kamu','Dia'], answer: 2 },
    { problem: '"___ pergi ke sekolah" (diri sendiri)', options: ['Dia','Saya','Kamu'], answer: 1 },
    { problem: '"___ suka bermain" (kawan)', options: ['Saya','Dia','Kami'], answer: 1 },
    { problem: '"___ semua bersama" (ramai)', options: ['Saya','Kamu','Kami'], answer: 2 },
    { problem: '"___ buku saya" (kepunyaan)', options: ['Ini','Di sini','Itu'], answer: 0 },
    { problem: '"___ rumah kamu?" (bertanya)', options: ['Mana','Di mana','Bagaimana'], answer: 1 },
  ]}},
  { title: 'Pantun Mudah - Lengkapkan', type: 'multiple_choice', emoji: '📜', difficulty: 'easy', gameData: { questions: [
    { problem: 'Hujan emas di negeri orang, hujan ___ di negeri sendiri', options: ['emas','perak','batu'], answer: 1 },
    { problem: 'Buat baik, baik ___ dibalas', options: ['buruk','baik','jahat'], answer: 1 },
    { problem: 'Rajin belajar, ___ pandai', options: ['mesti','jadi','akan'], answer: 1 },
    { problem: 'Kasih sayang ___ keluarga', options: ['untuk','dari','bersama'], answer: 0 },
    { problem: 'Bangun pagi, ___ muka cuci', options: ['basuh','gosok','lap'], answer: 0 },
    { problem: 'Tolong-menolong ___ mulia', options: ['adalah','ialah','jadi'], answer: 0 },
    { problem: 'Makan nasi ___ perut kenyang', options: ['jadi','sampai','sampai'], answer: 0 },
    { problem: 'Ibu ___ kita sayang', options: ['ayah','bapa','papa'], answer: 1 },
  ]}},
  { title: 'Huruf T hingga Z', type: 'letter_match', emoji: '🔠', difficulty: 'easy', gameData: { questions: [
    { letter: 'T', emoji: '🐯', word: 'Harimau', options: ['T','U','V','W'], answer: 0 },
    { letter: 'U', emoji: '☂️', word: 'Payung', options: ['T','U','V','W'], answer: 1 },
    { letter: 'V', emoji: '🎻', word: 'Biola', options: ['T','U','V','W'], answer: 2 },
    { letter: 'W', emoji: '🐋', word: 'Ikan Paus', options: ['T','U','V','W'], answer: 3 },
    { letter: 'X', emoji: '🎮', word: 'Xbox', options: ['W','X','Y','Z'], answer: 1 },
    { letter: 'Y', emoji: '🪀', word: 'Yo-yo', options: ['W','X','Y','Z'], answer: 2 },
    { letter: 'Z', emoji: '🦓', word: 'Zebra', options: ['W','X','Y','Z'], answer: 3 },
    { letter: 'A', emoji: '🐊', word: 'Buaya', options: ['A','B','C','D'], answer: 0 },
  ]}},
  { title: 'Nama Peralatan Sekolah', type: 'picture_quiz', emoji: '✏️', difficulty: 'easy', gameData: { questions: [
    { image: '✏️', options: ['Pensil','Pen','Krayon'], answer: 0 },
    { image: '📏', options: ['Pembaris','Gunting','Pemadam'], answer: 0 },
    { image: '🖊️', options: ['Pensil','Pen','Marker'], answer: 1 },
    { image: '📐', options: ['Jangka','Pembaris Sudut','Penggaris'], answer: 1 },
    { image: '📚', options: ['Buku','Majalah','Nota'], answer: 0 },
    { image: '🎒', options: ['Beg Sekolah','Beg Tangan','Beg Sukan'], answer: 0 },
    { image: '🗂️', options: ['Fail','Buku','Kotak'], answer: 0 },
    { image: '🖍️', options: ['Pensil Warna','Krayon','Pen'], answer: 1 },
  ]}},
  { title: 'Nama Badan Manusia', type: 'picture_quiz', emoji: '🧒', difficulty: 'easy', gameData: { questions: [
    { image: '👁️', options: ['Mata','Hidung','Telinga'], answer: 0 },
    { image: '👃', options: ['Mata','Hidung','Mulut'], answer: 1 },
    { image: '👂', options: ['Mata','Hidung','Telinga'], answer: 2 },
    { image: '👄', options: ['Mulut','Hidung','Bibir'], answer: 0 },
    { image: '✋', options: ['Kaki','Tangan','Bahu'], answer: 1 },
    { image: '🦶', options: ['Kaki','Tangan','Lengan'], answer: 0 },
    { image: '🦵', options: ['Lengan','Betis','Paha'], answer: 2 },
    { image: '💇', options: ['Kepala','Badan','Perut'], answer: 0 },
  ]}},
  { title: 'Perasaan Saya', type: 'picture_quiz', emoji: '😊', difficulty: 'easy', gameData: { questions: [
    { image: '😊', options: ['Gembira','Sedih','Marah'], answer: 0 },
    { image: '😢', options: ['Gembira','Sedih','Takut'], answer: 1 },
    { image: '😠', options: ['Gembira','Penat','Marah'], answer: 2 },
    { image: '😨', options: ['Takut','Marah','Gembira'], answer: 0 },
    { image: '😴', options: ['Sedih','Penat','Bosan'], answer: 1 },
    { image: '😂', options: ['Ketawa','Menangis','Senyum'], answer: 0 },
    { image: '🤗', options: ['Peluk','Sayang','Gembira'], answer: 0 },
    { image: '😍', options: ['Terkejut','Suka/Cinta','Gembira'], answer: 1 },
  ]}},
  { title: 'Hari dalam Seminggu', type: 'multiple_choice', emoji: '📅', difficulty: 'easy', gameData: { questions: [
    { problem: 'Hari pertama dalam seminggu?', options: ['Isnin','Ahad','Sabtu'], answer: 1 },
    { problem: 'Hari selepas Isnin?', options: ['Ahad','Rabu','Selasa'], answer: 2 },
    { problem: 'Hari tengah seminggu?', options: ['Selasa','Rabu','Khamis'], answer: 1 },
    { problem: 'Hari sebelum Sabtu?', options: ['Khamis','Jumaat','Ahad'], answer: 1 },
    { problem: 'Hari akhir dalam seminggu?', options: ['Sabtu','Ahad','Jumaat'], answer: 1 },
    { problem: 'Hari sekolah dari?', options: ['Sabtu-Ahad','Isnin-Jumaat','Rabu-Sabtu'], answer: 1 },
    { problem: 'Hari cuti sekolah?', options: ['Isnin-Selasa','Sabtu-Ahad','Rabu-Khamis'], answer: 1 },
    { problem: 'Berapa hari dalam seminggu?', options: ['5','6','7'], answer: 2 },
  ]}},
  { title: 'Kata Tanya Mudah', type: 'multiple_choice', emoji: '❓', difficulty: 'easy', gameData: { questions: [
    { problem: 'Tanya nama orang? "___ nama kamu?"', options: ['Siapa','Di mana','Berapa'], answer: 0 },
    { problem: 'Tanya tempat? "___ rumah kamu?"', options: ['Di mana','Siapa','Apa'], answer: 0 },
    { problem: 'Tanya waktu? "___ kamu pergi?"', options: ['Bila','Siapa','Apa'], answer: 0 },
    { problem: 'Tanya benda? "___ kamu suka?"', options: ['Apa','Siapa','Bila'], answer: 0 },
    { problem: 'Tanya sebab? "___ kamu menangis?"', options: ['Mengapa','Siapa','Berapa'], answer: 0 },
    { problem: 'Tanya jumlah? "___ banyak epal?"', options: ['Berapa','Apa','Bila'], answer: 0 },
    { problem: 'Tanya cara? "___ kamu datang ke sekolah?"', options: ['Bagaimana','Siapa','Berapa'], answer: 0 },
    { problem: 'Tanya orang? "___ itu?"', options: ['Siapa','Apa','Di mana'], answer: 0 },
  ]}},
  { title: 'Bulan dalam Setahun', type: 'multiple_choice', emoji: '📆', difficulty: 'easy', gameData: { questions: [
    { problem: 'Bulan pertama tahun?', options: ['Februari','Januari','Mac'], answer: 1 },
    { problem: 'Bulan kedua tahun?', options: ['Januari','Februari','Mac'], answer: 1 },
    { problem: 'Berapa bulan dalam setahun?', options: ['10','11','12'], answer: 2 },
    { problem: 'Bulan terakhir tahun?', options: ['November','Oktober','Disember'], answer: 2 },
    { problem: 'Bulan Hari Kemerdekaan Malaysia?', options: ['Ogos','Julai','September'], answer: 0 },
    { problem: 'Bulan selepas April?', options: ['Mac','Mei','Jun'], answer: 1 },
    { problem: 'Bulan ke-6?', options: ['Mei','Jun','Julai'], answer: 1 },
    { problem: 'Bulan sebelum Disember?', options: ['Oktober','November','September'], answer: 1 },
  ]}},
  { title: 'Kata Sifat - Ciri Benda', type: 'multiple_choice', emoji: '✨', difficulty: 'easy', gameData: { questions: [
    { problem: 'Batu itu ___', options: ['Lembut','Keras','Ringan'], answer: 1 },
    { problem: 'Air itu ___', options: ['Kering','Keras','Basah'], answer: 2 },
    { problem: 'Kapas itu ___', options: ['Berat','Ringan','Keras'], answer: 1 },
    { problem: 'Gula itu ___', options: ['Masin','Manis','Masam'], answer: 1 },
    { problem: 'Garam itu ___', options: ['Manis','Masin','Pahit'], answer: 1 },
    { problem: 'Ais itu ___', options: ['Panas','Suam','Sejuk'], answer: 2 },
    { problem: 'Lemon itu ___', options: ['Manis','Masam','Pahit'], answer: 1 },
    { problem: 'Bulu ayam itu ___', options: ['Kasar','Keras','Lembut'], answer: 2 },
  ]}},
  { title: 'Ayat Mudah - Subjek dan Predikat', type: 'multiple_choice', emoji: '📝', difficulty: 'easy', gameData: { questions: [
    { problem: 'Siapakah yang berlari? "Ali berlari."', options: ['berlari','Ali','cepat'], answer: 1 },
    { problem: 'Apakah yang dilakukan? "Ibu memasak."', options: ['Ibu','memasak','dapur'], answer: 1 },
    { problem: 'Lengkapkan: "Kucing itu ___"', options: ['buku','berlari','meja'], answer: 1 },
    { problem: 'Lengkapkan: "___ minum susu"', options: ['Berlari','Adik','Sekolah'], answer: 1 },
    { problem: 'Ayat lengkap?', options: ['Berlari cepat','Ali berlari','Sangat cepat'], answer: 1 },
    { problem: 'Tanda baca ayat penyata?', options: ['?','!','.'], answer: 2 },
    { problem: 'Tanda baca ayat tanya?', options: ['?','!','.'], answer: 0 },
    { problem: 'Tanda baca ayat seruan?', options: ['?','!','.'], answer: 1 },
  ]}},
  { title: 'Nama Alatan Rumah', type: 'picture_quiz', emoji: '🏠', difficulty: 'easy', gameData: { questions: [
    { image: '🍳', options: ['Kuali','Periuk','Besen'], answer: 0 },
    { image: '🥄', options: ['Sudu','Garfu','Penyepit'], answer: 0 },
    { image: '🔪', options: ['Sudu','Pisau','Garfu'], answer: 1 },
    { image: '🧹', options: ['Penyapu','Mop','Penyidai'], answer: 0 },
    { image: '🧺', options: ['Baldi','Bakul','Tong'], answer: 1 },
    { image: '🧴', options: ['Sabun','Syampoo','Pelembap'], answer: 1 },
    { image: '🪣', options: ['Baldi','Periuk','Mangkuk'], answer: 0 },
    { image: '🧻', options: ['Tuala','Kertas Tandas','Serbet'], answer: 1 },
  ]}},
  { title: 'Lawan Kata Mudah', type: 'multiple_choice', emoji: '↔️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Lawan "besar"?', options: ['kecil','panjang','tinggi'], answer: 0 },
    { problem: 'Lawan "panas"?', options: ['suam','sejuk','lembap'], answer: 1 },
    { problem: 'Lawan "siang"?', options: ['petang','malam','pagi'], answer: 1 },
    { problem: 'Lawan "naik"?', options: ['pergi','turun','jalan'], answer: 1 },
    { problem: 'Lawan "tua"?', options: ['muda','kecil','pendek'], answer: 0 },
    { problem: 'Lawan "keras"?', options: ['kasar','lembut','halus'], answer: 1 },
    { problem: 'Lawan "terang"?', options: ['redup','gelap','malap'], answer: 1 },
    { problem: 'Lawan "gemuk"?', options: ['kurus','kecil','rendah'], answer: 0 },
  ]}},
  { title: 'Nama Pokok dan Bunga', type: 'picture_quiz', emoji: '🌳', difficulty: 'easy', gameData: { questions: [
    { image: '🌹', options: ['Ros','Bunga Matahari','Tulip'], answer: 0 },
    { image: '🌻', options: ['Ros','Bunga Matahari','Bunga Lili'], answer: 1 },
    { image: '🌲', options: ['Pokok Kelapa','Pokok Pinus','Pokok Getah'], answer: 1 },
    { image: '🌴', options: ['Pokok Kelapa','Pokok Asam','Pokok Durian'], answer: 0 },
    { image: '🌺', options: ['Bunga Raya','Orkid','Bunga Mawar'], answer: 0 },
    { image: '🌸', options: ['Bunga Sakura','Orkid','Ros'], answer: 0 },
    { image: '🍃', options: ['Daun','Akar','Batang'], answer: 0 },
    { image: '🌾', options: ['Padi','Jagung','Pokok Kelapa'], answer: 0 },
  ]}},
  { title: 'Nama Bulan Setahun', type: 'multiple_choice', emoji: '📅', difficulty: 'easy', gameData: { questions: [
    { problem: 'Bulan pertama setahun?', options: ['Februari','Januari','Mac'], answer: 1 },
    { problem: 'Bulan Hari Kemerdekaan?', options: ['Julai','Ogos','September'], answer: 1 },
    { problem: 'Bulan Tahun Baru Cina?', options: ['Januari','Februari','Mac'], answer: 1 },
    { problem: 'Bulan Ramadan biasanya?', options: ['Disember','Ramadan sahaja','Bergantung Lunar'], answer: 2 },
    { problem: 'Bulan terakhir setahun?', options: ['November','Disember','Oktober'], answer: 1 },
    { problem: 'Berapa bulan dalam setahun?', options: ['10','11','12'], answer: 2 },
    { problem: 'Bulan Jun - berapa bulan dalam tahun?', options: ['5','6','7'], answer: 1 },
    { problem: 'Selepas Desember datang?', options: ['Januari','November','Oktober'], answer: 0 },
  ]}},
  { title: 'Aktiviti Harian Saya', type: 'picture_quiz', emoji: '⏰', difficulty: 'easy', gameData: { questions: [
    { image: '😴', options: ['Tidur','Mandi','Makan'], answer: 0 },
    { image: '🍳', options: ['Mandi','Makan','Bermain'], answer: 1 },
    { image: '🚿', options: ['Mandi','Tidur','Makan'], answer: 0 },
    { image: '🎒', options: ['Sekolah','Tidur','Bermain'], answer: 0 },
    { image: '✏️', options: ['Bermain','Menulis/Belajar','Makan'], answer: 1 },
    { image: '🏃', options: ['Bermain','Tidur','Belajar'], answer: 0 },
    { image: '📚', options: ['Tidur','Belajar','Bermain'], answer: 1 },
    { image: '🛏️', options: ['Mandi','Bermain','Tidur'], answer: 2 },
  ]}},
  { title: 'Cuaca dan Musim', type: 'picture_quiz', emoji: '⛅', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['Hujan','Panas','Sejuk'], answer: 1 },
    { image: '🌧️', options: ['Panas','Hujan','Angin'], answer: 1 },
    { image: '🌈', options: ['Selepas Hujan','Siang Hari','Malam'], answer: 0 },
    { image: '⛈️', options: ['Ribut','Angin Kuat','Hujan Lebat'], answer: 0 },
    { image: '☁️', options: ['Awan','Hujan','Panas'], answer: 0 },
    { image: '🌤️', options: ['Cerah Sebahagian','Panas','Hujan'], answer: 0 },
    { image: '❄️', options: ['Panas','Sejuk/Beku','Hujan'], answer: 1 },
    { image: '💨', options: ['Hujan','Panas','Angin'], answer: 2 },
  ]}},
  { title: 'Tempat-Tempat di Bandar', type: 'picture_quiz', emoji: '🏙️', difficulty: 'easy', gameData: { questions: [
    { image: '🏫', options: ['Hospital','Sekolah','Masjid'], answer: 1 },
    { image: '🏥', options: ['Sekolah','Hospital','Kedai'], answer: 1 },
    { image: '🛒', options: ['Pasar','Pasaraya','Kedai'], answer: 2 },
    { image: '🕌', options: ['Masjid','Gereja','Sekolah'], answer: 0 },
    { image: '🏠', options: ['Rumah','Sekolah','Hospital'], answer: 0 },
    { image: '🚉', options: ['Stesen Kereta Api','Lapangan Terbang','Stesen Bas'], answer: 0 },
    { image: '🎡', options: ['Taman','Kota Permainan','Pantai'], answer: 1 },
    { image: '📚', options: ['Sekolah','Perpustakaan','Rumah'], answer: 1 },
  ]}},
  { title: 'Gaya Hidup Sihat', type: 'multiple_choice', emoji: '💪', difficulty: 'easy', gameData: { questions: [
    { problem: 'Untuk sihat, apa yang perlu?', options: ['Makan Manis','Makan Sayur Buah','Makan Makanan Bergoreng'], answer: 1 },
    { problem: 'Berapa jam tidur kanak-kanak?', options: ['4 jam','8 jam','10-12 jam'], answer: 2 },
    { problem: 'Olahraga kegemaran?', options: ['Main Permainan Aktif','Bermain Komputer','Menonton TV'], answer: 0 },
    { problem: 'Minum air putih sehari?', options: ['Jarang','Cukup banyak','Setahun sekali'], answer: 1 },
    { problem: 'Basikal adalah?', options: ['Bermain','Olahraga','Berjalan'], answer: 1 },
    { problem: 'Berenang adalah?', options: ['Bermain','Istirahat','Olahraga'], answer: 2 },
    { problem: 'Basuh tangan sebelum?', options: ['Belajar','Tidur','Makan'], answer: 2 },
    { problem: 'Gosok gigi?', options: ['Pagi Saja','Pagi dan Malam','Seminggu Sekali'], answer: 1 },
  ]}},
  { title: 'Alat Mainan dan Permainan', type: 'picture_quiz', emoji: '🎮', difficulty: 'easy', gameData: { questions: [
    { image: '⚽', options: ['Bola Sepak','Bola Keranjang','Bola Tenis'], answer: 0 },
    { image: '🏀', options: ['Bola Sepak','Bola Keranjang','Bola Voli'], answer: 1 },
    { image: '🪀', options: ['Yo-yo','Gancu','Bola'], answer: 0 },
    { image: '🎲', options: ['Dadu','Congkak','Permainan Papan'], answer: 0 },
    { image: '🧩', options: ['Teka-Teki','Permainan Bongkar Pasang','Lego'], answer: 2 },
    { image: '🎨', options: ['Warna','Melukis','Berus'], answer: 1 },
    { image: '🎸', options: ['Gitar','Asli','Alat Muzik'], answer: 0 },
    { image: '🪁', options: ['Wau','Layang-Layang','Mainan'], answer: 1 },
  ]}},
  { title: 'Mendengar Cerita - Mak Cik Punya Kucing', type: 'multiple_choice', emoji: '👂', difficulty: 'easy', gameData: { questions: [
    { problem: 'Cerita: "Mak Cik ada seekor kucing putih. Kucing itu bernama Putih. Putih suka bermain." - Siapa punya kucing?', options: ['Anak','Mak Cik','Pak Cik'], answer: 1 },
    { problem: 'Apa warna kucing itu?', options: ['Hitam','Putih','Kuning'], answer: 1 },
    { problem: 'Nama kucing itu siapa?', options: ['Abu','Putih','Tompok'], answer: 1 },
    { problem: 'Kucing itu suka apa?', options: ['Mandi','Bermain','Tidur'], answer: 1 },
    { problem: 'Cerita tentang apa?', options: ['Anjing','Burung','Kucing'], answer: 2 },
    { problem: 'Berapa kucing yang ada?', options: ['2','1','3'], answer: 1 },
    { problem: 'Kucing itu milik siapa?', options: ['Ibu','Mak Cik','Cikgu'], answer: 1 },
    { problem: 'Warna kucing dalam cerita?', options: ['Coklat','Putih','Oren'], answer: 1 },
  ]}},
  { title: 'Adab Bermasyarakat - Kata Sopan', type: 'picture_quiz', emoji: '🙏', difficulty: 'easy', gameData: { questions: [
    { image: '🤝', options: ['Pukul','Bersalaman','Tendang'], answer: 1 },
    { image: '👋', options: ['Berlari','Melambai','Menepuk'], answer: 1 },
    { image: '🙏', options: ['Tidur','Berdoa/Berterima kasih','Memukul'], answer: 1 },
    { image: '🤐', options: ['Bercerita','Berbual','Berdiam diri'], answer: 2 },
    { image: '👂', options: ['Ketawa','Mendengarkan','Menari'], answer: 1 },
    { image: '😊', options: ['Marah','Menyenyum Sopan','Menangis'], answer: 1 },
    { image: '🚪', options: ['Menolak','Membuka Dengan Sopan','Memukul'], answer: 1 },
    { image: '🍴', options: ['Membuang','Makan Dengan Sopan','Bermain'], answer: 1 },
  ]}},
  { title: 'Tolong-Menolong di Rumah', type: 'multiple_choice', emoji: '👨‍👩‍👧', difficulty: 'easy', gameData: { questions: [
    { problem: 'Apa yang perlu kita lakukan untuk membantu ibu?', options: ['Bermain saja','Sapu lantai, cuci pinggan','Tidur saja'], answer: 1 },
    { problem: 'Ketika adik menangis, apa yang patut kita buat?', options: ['Tinggalkan','Hibur dan tanya masalah','Marah'], answer: 1 },
    { problem: 'Ibu memasak - kamu boleh?', options: ['Lari keluar','Dekat dan tanya nak bantu','Jauh-jauh'], answer: 1 },
    { problem: 'Ayah balik lelah - kamu boleh?', options: ['Hanya main','Ambil kasut dan tanya khabar','Nyotor'], answer: 1 },
    { problem: 'Nenek duduk sendiri - apa yang elok?', options: ['Tinggalkan','Duduk dengannya dan cerita','Lari'], answer: 1 },
    { problem: 'Rumah kotor - siapa bertanggung jawab?', options: ['Hanya ayah','Semua anggota keluarga','Pembantu saja'], answer: 1 },
    { problem: 'Adik lupa kasut - apa yang patut?', options: ['Biarkan','Bantu cari kasut adik','Ketawa'], answer: 1 },
    { problem: 'Keluarga adalah?', options: ['Kumpulan orang','Orang-orang yang saling bantu','Hanya ibu bapa'], answer: 1 },
  ]}},
  { title: 'Cerita Pendek - Ali Bantu Nenek', type: 'multiple_choice', emoji: '📖', difficulty: 'medium', gameData: { questions: [
    { problem: 'Cerita: "Ali dengar nenek panggil. Nenek jatuh di dapur. Ali cepat-cepat angkat nenek." - Apa yang berlaku?', options: ['Ali tidur','Nenek jatuh','Nenek berlari'], answer: 1 },
    { problem: 'Siapa yang terjatuh?', options: ['Ali','Ibu','Nenek'], answer: 2 },
    { problem: 'Ali buat apa?', options: ['Tertawa','Angkat nenek','Lari'], answer: 1 },
    { problem: 'Cerita berlaku di?', options: ['Taman','Sekolah','Dapur'], answer: 2 },
    { problem: 'Ali adalah orang yang?', options: ['Jahat','Baik hati','Malas'], answer: 1 },
    { problem: 'Apa yang perlu kita buat seperti Ali?', options: ['Lari','Bantu orang tua','Tertawa'], answer: 1 },
    { problem: 'Nenek senang kepada?', options: ['Orang jahat','Ali yang membantu','Orang yang jauh'], answer: 1 },
    { problem: 'Pelajaran cerita ialah?', options: ['Jangan bantu','Selalulah bantu orang','Hanya bermain'], answer: 1 },
  ]}},
  { title: 'Bersih dan Rapi - Kebiasaan Baik', type: 'picture_quiz', emoji: '🧹', difficulty: 'easy', gameData: { questions: [
    { image: '🛏️', options: ['Buat berantakan','Selak kasur dan kerapikan','Tidur terus'], answer: 1 },
    { image: '🧻', options: ['Buang sembarangan','Basuh tangan selepas','Tidak basuh'], answer: 1 },
    { image: '🪥', options: ['Tidur dengan gigi kotor','Gosok gigi pagi dan malam','Tidak gosok'], answer: 1 },
    { image: '👕', options: ['Buang merata','Lipat dan masuk almari','Tergantung'], answer: 1 },
    { image: '🍽️', options: ['Tinggalkan','Cuci dan keringkan','Biarkan sepanjang hari'], answer: 1 },
    { image: '🧤', options: ['Buat kotor','Cuci basah dan keringkan','Abaikan'], answer: 1 },
    { image: '🚿', options: ['Mandi baju lengkap','Mandi tanpa baju','Tidak mandi'], answer: 0 },
    { image: '🧹', options: ['Biar kotor','Sapu lantai sendiri','Hanya orang tua'], answer: 1 },
  ]}},
  { title: 'Adab Makan Makanan Berkati', type: 'multiple_choice', emoji: '🥘', difficulty: 'easy', gameData: { questions: [
    { problem: 'Sebelum makan, kita patut?', options: ['Main dulu','Berdoa/Basmalah','Lari'], answer: 1 },
    { problem: 'Makan dengan tangan apa yang baik?', options: ['Tangan kiri','Tangan kanan','Kedua-dua'], answer: 1 },
    { problem: 'Ketika mulut penuh - apa yang elok?', options: ['Bercerita','Diam dan telan','Minum terus'], answer: 1 },
    { problem: 'Makanan yang jatuh - kita patut?', options: ['Biarkan jatuh','Ambil dan buang','Makan juga'], answer: 1 },
    { problem: 'Selepas makan selesai, kita patut?', options: ['Berlari','Berdoa/Ucap terima kasih','Tidur'], answer: 1 },
    { problem: 'Makan dengan rakus itu?', options: ['Baik','Tidak baik adab','Sempurna'], answer: 1 },
    { problem: 'Jika ada orang tua di meja - siapa makan dahulu?', options: ['Anak','Orang tua','Semua sama'], answer: 1 },
    { problem: 'Makan mesti dengan?', options: ['Cepat','Perlahan dan sopan','Sambil main'], answer: 1 },
  ]}},
  ];