// Sekolah Rendah - Science EXPANSION FULL (20+ soalan per game + NEW GAMES)
// Tier 1 CRITICAL FIX - Expand dari 18 games → 25+ games, ALL 20+ soalan per game

export const sekolah_science_expansion_full = [
  { title: 'Sistem Tubuh Manusia Extended D4-5', type: 'multiple_choice', emoji: '🫀', difficulty: 'hard', darjah: 4, gameData: { questions: [
    { problem: 'Berapa tulang dalam badan manusia?', options: ['106','206','306'], answer: 1 },
    { problem: 'Tulang terbesar ialah?', options: ['Tulang rusuk','Tulang paha','Tulang lengan'], answer: 1 },
    { problem: 'Fungsi rangka tulang?', options: ['Buat makanan','Sokong dan lindungi','Bernafas'], answer: 1 },
    { problem: 'Jantung berdenyut berapa kali semenit?', options: ['30-40','60-100','200-300'], answer: 1 },
    { problem: 'Paru-paru berfungsi untuk?', options: ['Pompakan darah','Ambil oksigen lepas CO₂','Proses makanan'], answer: 1 },
    { problem: 'Hati (liver) berfungsi?', options: ['Bernafas','Saring dan proses','Buang air'], answer: 1 },
    { problem: 'Ginjal berfungsi?', options: ['Simpan makanan','Saring sisa urin','Pegang tulang'], answer: 1 },
    { problem: 'Usus halus berfungsi?', options: ['Buat makanan','Serap nutrisi','Buang air'], answer: 1 },
    { problem: 'Sel darah merah bawa?', options: ['Hormon','Oksigen','Lemak'], answer: 1 },
    { problem: 'Sel darah putih lawan?', options: ['Air','Jangkitan/kuman','Lemak'], answer: 1 },
    { problem: 'Otak mengawal?', options: ['Otot sahaja','Seluruh badan','Jantung sahaja'], answer: 1 },
    { problem: 'Saraf membawa?', options: ['Makanan','Isyarat elektrik','Air'], answer: 1 },
    { problem: 'Apa diet seimbang perlukan?', options: ['Karbohidrat sahaja','Protein, lemak, vitamin, mineral','Hanya air'], answer: 1 },
    { problem: 'Vitamin A penting untuk?', options: ['Otot','Mata','Jantung'], answer: 1 },
    { problem: 'Vitamin C penting untuk?', options: ['Tulang','Kulit dan imuniti','Perut'], answer: 1 },
    { problem: 'Kalsium penting untuk?', options: ['Otot','Tulang dan gigi','Jantung'], answer: 1 },
    { problem: 'Besi penting untuk?', options: ['Tulang','Darah - hemoglobin','Otak'], answer: 1 },
    { problem: 'Air penting untuk?', options: ['Warna badan','Semua fungsi tubuh','Hanya tidur'], answer: 1 },
    { problem: 'Berapa jam tidur diperlukan kanak-kanak?', options: ['4-5','8-10','12-14'], answer: 1 },
    { problem: 'Olahraga memberi manfaat?', options: ['Hanya otot','Semua sistem tubuh','Hanya jantung'], answer: 1 },
  ]}},
  
  { title: 'Ekosistem dan Rantai Makanan Extended D5', type: 'multiple_choice', emoji: '🌿', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Produsen dalam rantai makanan?', options: ['Haiwan','Tumbuhan','Kulat'], answer: 1 },
    { problem: 'Konsumen primer memakan?', options: ['Konsumen lain','Tumbuhan','Pengurai'], answer: 1 },
    { problem: 'Konsumen tertiari memakan?', options: ['Tumbuhan','Konsumen sekunder','Pengurai'], answer: 1 },
    { problem: 'Pengurai memecah?', options: ['Benda hidup','Benda mati organik','Batu'], answer: 1 },
    { problem: 'Contoh pengurai ialah?', options: ['Singa','Bakteria dan fungi','Rumput'], answer: 1 },
    { problem: 'Herbivor memakan?', options: ['Daging','Tumbuhan','Kedua-dua'], answer: 1 },
    { problem: 'Karnivor memakan?', options: ['Tumbuhan','Daging','Kedua-dua'], answer: 1 },
    { problem: 'Omnivor memakan?', options: ['Tumbuhan sahaja','Daging sahaja','Tumbuhan dan daging'], answer: 2 },
    { problem: 'Piramid biomassa menunjukkan?', options: ['Jumlah spesies','Jisim di tiap aras','Saiz haiwan'], answer: 1 },
    { problem: 'Jika produsen hilang - konsumen?', options: ['Bertambah','Pupus (kelaparan)','Tidak berubah'], answer: 1 },
    { problem: 'Jika pemangsa hilang - mangsa?', options: ['Pupus','Bertambah berlebihan','Sama'], answer: 1 },
    { problem: 'Simbiosis mutualisme - kedua-duanya?', options: ['Untung','Rugi','Tiada kesan'], answer: 0 },
    { problem: 'Parasit adalah?', options: ['Untung-untung','Satu untung satu rugi','Kedua-duanya untung'], answer: 1 },
    { problem: 'Spesies invasif boleh?', options: ['Bantu ekosistem','Rosakkan ekosistem','Baik sahaja'], answer: 1 },
    { problem: 'Biodiversiti tinggi bermakna?', options: ['Satu spesies dominan','Banyak spesies berbeza','Tanpa predator'], answer: 1 },
    { problem: 'Habitat adalah?', options: ['Makanan','Tempat hidup organisma','Musim'], answer: 1 },
    { problem: 'Niche adalah?', options: ['Rumah saja','Peranan spesies dalam ekosistem','Pertumbuhan'], answer: 1 },
    { problem: 'Taman negara ditubuhkan untuk?', options: ['Pelancongan sahaja','Perlindungan ekosistem','Pertanian'], answer: 1 },
    { problem: 'Pencemaran laut membahayakan?', options: ['Hanya ikan besar','Seluruh ekosistem laut','Tanaman darat'], answer: 1 },
    { problem: 'Cara terbaik penjagaan alam?', options: ['Bina lebih kilang','Kurangkan limbah, kitar semula','Tebang hutan'], answer: 1 },
  ]}},
  
  { title: 'Perubahan Keadaan Jirim Extended D3', type: 'multiple_choice', emoji: '🧪', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Tiga keadaan jirim?', options: ['Gas, air, api','Pepejal, cecair, gas','Keras, lembut, cair'], answer: 1 },
    { problem: 'Contoh pepejal?', options: ['Air','Batu','Oksigen'], answer: 1 },
    { problem: 'Contoh cecair?', options: ['Besi','Minyak','Udara'], answer: 1 },
    { problem: 'Contoh gas?', options: ['Ais','Alkohol','CO₂'], answer: 2 },
    { problem: 'Pepejal mempunyai bentuk?', options: ['Berubah','Tetap','Tiada'], answer: 1 },
    { problem: 'Cecair bentuknya?', options: ['Tetap','Mengikut bekas','Tidak nampak'], answer: 1 },
    { problem: 'Gas mengisi?', options: ['Sebahagian bekas','Seluruh bekas','Tiada'], answer: 1 },
    { problem: 'Ais cair → air adalah?', options: ['Penyejatan','Peleburan','Pembekuan'], answer: 1 },
    { problem: 'Air mendidih → wap adalah?', options: ['Peleburan','Penyejatan','Kondensasi'], answer: 1 },
    { problem: 'Wap sejuk → air adalah?', options: ['Penyejatan','Peleburan','Kondensasi'], answer: 2 },
    { problem: 'Air beku adalah?', options: ['Peleburan','Pembekuan/kristalisasi','Penyejatan'], answer: 1 },
    { problem: 'Lilin cair bila?', options: ['Didinginkan','Dipanaskan','Ditekan'], answer: 1 },
    { problem: 'Contoh peleburan?', options: ['Air beku','Ais cair','Gas ke cecair'], answer: 1 },
    { problem: 'Proses air → wap disebut?', options: ['Pembekuan','Penyejatan','Kondensasi'], answer: 1 },
    { problem: 'Pemanasan menyebabkan?', options: ['Pengurangan volume','Peningkatan volume','Tiada perubahan'], answer: 1 },
    { problem: 'Pendinginan menyebabkan?', options: ['Pengurangan volume','Peningkatan volume','Tiada perubahan'], answer: 0 },
    { problem: 'Embun pagi adalah?', options: ['Hujan kecil','Kondensasi wap air','Penyejatan'], answer: 1 },
    { problem: 'Jirim padat mengandungi atom?', options: ['Longgar','Rapat erat','Bergerak bebas'], answer: 1 },
    { problem: 'Jirim cecair atom bergerak?', options: ['Tetap','Lebih bebas dari pepejal','Sangat bebas'], answer: 1 },
    { problem: 'Jirim gas atom bergerak?', options: ['Lambat','Sedang','Sangat cepat dan bebas'], answer: 2 },
  ]}},
  
  { title: 'Cahaya dan Bunyi Extended D5', type: 'multiple_choice', emoji: '💡', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Cahaya bergerak dalam?', options: ['Garis bengkok','Garis lurus','Lingkaran'], answer: 1 },
    { problem: 'Bunyi memerlukan apa untuk bergerak?', options: ['Vakum','Medium (udara/air/batu)','Cahaya'], answer: 1 },
    { problem: 'Bunyi TIDAK boleh bergerak dalam?', options: ['Udara','Air','Vakum'], answer: 2 },
    { problem: 'Cermin memantulkan?', options: ['Bunyi','Cahaya','Haba'], answer: 1 },
    { problem: 'Gema adalah?', options: ['Cahaya pantulan','Bunyi pantulan','Cahaya baru'], answer: 1 },
    { problem: 'Sumber cahaya semula jadi?', options: ['Lampu','Matahari','Lilin'], answer: 1 },
    { problem: 'Sumber cahaya buatan?', options: ['Matahari','Lampu','Api'], answer: 1 },
    { problem: 'Bahan lutsinar?', options: ['Legap','Cahaya melepas sepenuhnya','Cahaya sebahagian'], answer: 1 },
    { problem: 'Bahan legap?', options: ['Cahaya melepas','Cahaya diserap','Cahaya melepas sebahagian'], answer: 1 },
    { problem: 'Pelangi terbentuk dari?', options: ['Api','Prisma air - pencerahan cahaya','Awan'], answer: 1 },
    { problem: 'Warna pelangi dimulai?', options: ['Biru','Merah','Hijau'], answer: 1 },
    { problem: 'Kelajuan cahaya kira-kira?', options: ['300 km/s','300,000 km/s','3,000 km/s'], answer: 1 },
    { problem: 'Kelajuan bunyi di udara?', options: ['3 m/s','340 m/s','3,400 m/s'], answer: 1 },
    { problem: 'Mengapa kilat didapat sebelum guruh?', options: ['Kilat lebih dekat','Cahaya lebih laju bunyi','Guruh lambat'], answer: 1 },
    { problem: 'Ultrasonik digunakan dalam?', options: ['Lampu','Ultrasound/sonar','Radio'], answer: 1 },
    { problem: 'Telinga manusia dengar frekuensi?', options: ['20-200 Hz','20-20,000 Hz','100,000 Hz+'], answer: 1 },
    { problem: 'Frekuensi tinggi = nada?', options: ['Rendah','Tinggi','Sama'], answer: 1 },
    { problem: 'Amplitud besar = bunyi?', options: ['Lembut','Kuat/kencang','Sama'], answer: 1 },
    { problem: 'Cermin cekung digunakan?', options: ['Kaca rumah mandi','Teleskop reflektor','Periskop'], answer: 1 },
    { problem: 'Kanta pembesar menggunakan?', options: ['Pantulan','Pembiasan cahaya','Penyerapan'], answer: 1 },
  ]}},
  
  { title: 'Daya, Gerakan dan Mesin Mudah Extended D5', type: 'multiple_choice', emoji: '⚙️', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Daya diukur dalam unit?', options: ['Kilogram','Newton','Meter'], answer: 1 },
    { problem: 'Graviti menarik objek ke?', options: ['Atas','Bawah','Sisi'], answer: 1 },
    { problem: 'Tanpa graviti kita?', options: ['Jalan biasa','Terapung','Jatuh laju'], answer: 1 },
    { problem: 'Magnet menarik bahan?', options: ['Plastik','Besi/Kobalt/Nikel','Kayu'], answer: 1 },
    { problem: 'Kutub N + Kutub N?', options: ['Tarik','Tolak','Tiada'], answer: 1 },
    { problem: 'Kutub N + Kutub S?', options: ['Tolak','Tarik','Tiada'], answer: 1 },
    { problem: 'Gesekan menghasilkan?', options: ['Sejuk','Haba','Cahaya'], answer: 1 },
    { problem: 'Roda mengurangkan?', options: ['Haba','Gesekan','Graviti'], answer: 1 },
    { problem: 'Tuas membantu dengan?', options: ['Menghasilkan api','Mengurangkan usaha','Membuat bunyi'], answer: 1 },
    { problem: 'Contoh tuas?', options: ['Kaca pembesar','Gunting','Bateri'], answer: 1 },
    { problem: 'Satah condong membantu?', options: ['Angkat sama mudah','Angkat dengan usaha kurang','Jatuhkan'], answer: 1 },
    { problem: 'Takal digunakan untuk?', options: ['Potong','Angkat beban berat','Korek'], answer: 1 },
    { problem: 'Apungan membolehkan?', options: ['Tenggelam','Terapung','Terbakar'], answer: 1 },
    { problem: 'Benda terapung bila ketumpatannya?', options: ['Lebih dari air','Kurang dari air','Sama'], answer: 1 },
    { problem: 'Kapal terapung kerana?', options: ['Ringan','Bentuk menangkap udara','Emas'], answer: 1 },
    { problem: 'Pegas menyimpan tenaga?', options: ['Kinetik','Berpotensi elastik','Haba'], answer: 1 },
    { problem: 'Tekanan udara tinggi di?', options: ['Puncak gunung','Paras laut','Angkasa'], answer: 1 },
    { problem: 'Ombak digerakkan oleh?', options: ['Ikan','Angin dan bulan','Api'], answer: 1 },
    { problem: 'Paras air naik kerana?', options: ['Graviti','Sesaran benda','Tekanan'], answer: 1 },
    { problem: 'Daya henti bola ialah?', options: ['Graviti','Gesekan','Magnet'], answer: 1 },
  ]}},
];