// Prasekolah - Bahasa Melayu - Expansion (10 games)
export const prasekolah_bahasa_melayu_expansion = [
  { title: 'Nosi & Tanda Baca Mudah', type: 'multiple_choice', emoji: '📝', difficulty: 'easy', gameData: { questions: [
    { problem: 'Tanda baca di hujung ayat — "Saya suka bermain"?', options: ['!','?','.'], answer: 2 },
    { problem: 'Tanda baca ayat tanya — "Siapa namamu?"?', options: ['!','?','.'], answer: 1 },
    { problem: 'Tanda baca ayat seruan — "Wah cantiknya!"?', options: ['!','?','.'], answer: 0 },
    { problem: 'Huruf mula ayat mesti?', options: ['Kecil','Besar','Sama'], answer: 1 },
    { problem: 'Pemisah perkataan dalam senarai?', options: ['Titik','Koma','Garis'], answer: 1 },
    { problem: 'Tanda untuk dialog — "Saya ada kucing"?', options: ['Kurung','Petik','Garis'], answer: 1 },
    { problem: 'Tanda (...) menunjuk?', options: ['Akhir','Sambungan','Soalan'], answer: 1 },
    { problem: 'Ayat yang betul — "dia makan nasi"?', options: ['Dia makan nasi.','dia makan nasi','Dia makan Nasi'], answer: 0 },
  ]}},
  { title: 'Sinonim Mudah - Perkataan Sama Maksud', type: 'multiple_choice', emoji: '🔄', difficulty: 'easy', gameData: { questions: [
    { problem: 'Perkataan sama dengan "cantik"?', options: ['Hodoh','Indah','Besar'], answer: 1 },
    { problem: 'Perkataan sama dengan "gembira"?', options: ['Sedih','Suka','Marah'], answer: 1 },
    { problem: 'Perkataan sama dengan "cepat"?', options: ['Lambat','Laju','Perlahan'], answer: 1 },
    { problem: 'Perkataan sama dengan "besar"?', options: ['Kecil','Berat','Besar-besar'], answer: 2 },
    { problem: 'Perkataan sama dengan "sejuk"?', options: ['Panas','Sejuknya','Dingin'], answer: 2 },
    { problem: 'Perkataan sama dengan "pandai"?', options: ['Pintar','Bodoh','Taraf'], answer: 0 },
    { problem: 'Perkataan sama dengan "jauh"?', options: ['Dekat','Terpencil','Jauhan'], answer: 1 },
    { problem: 'Perkataan sama dengan "mudah"?', options: ['Susah','Ringkas','Kompleks'], answer: 1 },
  ]}},
  { title: 'Ungkapan & Makna Mudah', type: 'multiple_choice', emoji: '💬', difficulty: 'medium', gameData: { questions: [
    { problem: '"Mata kucing" bermaksud?', options: ['Mata nyata kucing','Mata yang tajam','Kucing bermata'], answer: 1 },
    { problem: '"Hati batu" bermaksud?', options: ['Batu di hati','Hati yang keras/tidak belas kasihan','Hati kotor'], answer: 1 },
    { problem: '"Mulut manis" bermaksud?', options: ['Mulut bercebok','Suka berjanji','Orang yang pandai cakap'], answer: 2 },
    { problem: '"Tangan dingin" bermaksud?', options: ['Tangan benar-benar sejuk','Pandai mencuri','Tangan cedera'], answer: 1 },
    { problem: '"Telinga panjang" bermaksud?', options: ['Telinga besar','Mudah percaya desas-desus','Dengar dengan baik'], answer: 1 },
    { problem: '"Kepala panas" bermaksud?', options: ['Kepala benar panas','Mudah marah','Berpikir keras'], answer: 1 },
    { problem: '"Kaki lembut" bermaksud?', options: ['Kaki betul lembut','Tidak berani/takut ambil tindakan','Berjalan lembut'], answer: 1 },
    { problem: '"Lidah panjang" bermaksud?', options: ['Lidah besar','Suka mengumpat/fitnah','Berbicara jelas'], answer: 1 },
  ]}},
  { title: 'Abjad & Susunan Abjad', type: 'multiple_choice', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { problem: 'Huruf selepas M dalam abjad?', options: ['L','N','O'], answer: 1 },
    { problem: 'Huruf sebelum G dalam abjad?', options: ['F','H','E'], answer: 0 },
    { problem: 'Huruf ke-5 dalam abjad?', options: ['C','D','E'], answer: 2 },
    { problem: 'Susun perkataan mengikut abjad: Apel, Buku, Anak?', options: ['Anak, Apel, Buku','Apel, Anak, Buku','Buku, Anak, Apel'], answer: 0 },
    { problem: 'Manakah perkataan pertama mengikut abjad?', options: ['Rumah','Kereta','Anjing'], answer: 2 },
    { problem: 'Susun: Kucing, Kuda, Kereta — abjad?', options: ['Kereta, Kuda, Kucing','Kucing, Kuda, Kereta','Kuda, Kereta, Kucing'], answer: 1 },
    { problem: 'Mana perkataan terakhir abjad: Meja, Matahari, Mulut?', options: ['Meja','Mulut','Matahari'], answer: 2 },
    { problem: 'Abjad ada berapa huruf?', options: ['24','26','28'], answer: 1 },
  ]}},
  { title: 'Kosa Kata Tempat & Lokasi', type: 'picture_quiz', emoji: '🏘️', difficulty: 'easy', gameData: { questions: [
    { image: '🏪', options: ['Rumah','Kedai','Sekolah'], answer: 1 },
    { image: '⛪', options: ['Gereja','Masjid','Sekolah'], answer: 0 },
    { image: '🏥', options: ['Klinik','Hospital','Farmasi'], answer: 1 },
    { image: '🏨', options: ['Hotel','Rumah','Kedai'], answer: 0 },
    { image: '🏦', options: ['Bank','Pejabat','Kedai'], answer: 0 },
    { image: '🏭', options: ['Kilang','Rumah','Sekolah'], answer: 0 },
    { image: '🏬', options: ['Pasaraya','Pasar','Kedai'], answer: 0 },
    { image: '🚏', options: ['Stesen Bas','Terminal','Perhentian'], answer: 0 },
  ]}},
  { title: 'Soalan Mudah - Apa, Siapa, Mana', type: 'multiple_choice', emoji: '❓', difficulty: 'easy', gameData: { questions: [
    { problem: '"___ itu bunga?" — Jawab dengan Apa/Siapa/Mana?', options: ['Apa','Siapa','Mana'], answer: 0 },
    { problem: '"___ nama kamu?" — Jawab dengan Apa/Siapa/Mana?', options: ['Apa','Siapa','Mana'], answer: 1 },
    { problem: '"___ rumah kamu?" — Jawab dengan Apa/Siapa/Mana?', options: ['Apa','Siapa','Mana'], answer: 2 },
    { problem: 'Soalan "Apa itu?" cari?', options: ['Nama orang','Nama benda','Tempat'], answer: 1 },
    { problem: 'Soalan "Siapa nama kamu?" cari?', options: ['Benda','Orang','Tempat'], answer: 1 },
    { problem: 'Soalan "Di mana sekolah?" cari?', options: ['Benda','Orang','Tempat'], answer: 2 },
    { problem: '"Apakah warna langit?" — Jawab warna apa?', options: ['Biru','Merah','Kuning'], answer: 0 },
    { problem: '"Siapakah guru kamu?" — Tanya tentang?', options: ['Orang','Benda','Tempat'], answer: 0 },
  ]}},
  { title: 'Situasi Sosial - Adab Bertutur', type: 'multiple_choice', emoji: '🙏', difficulty: 'easy', gameData: { questions: [
    { problem: 'Bertemu guru, ucapan yang tepat?', options: ['Apa hal?','Assalamualaikum cikgu','Hei!'], answer: 1 },
    { problem: 'Minta bantuan — perkataan sopan?', options: ['Tolong!','Boleh saya minta bantuan?','Buat!'], answer: 1 },
    { problem: 'Dipinjami barang — ucapan?', options: ['Biasa saja','Terima kasih!','Lepas!'], answer: 1 },
    { problem: 'Buat kesalahan — perkataan?', options: ['Tidak peduli','Maafkan saya','Cari masalah'], answer: 1 },
    { problem: 'Hendak pergi — salam yang baik?', options: ['Daa!','Assalamualaikum','Sampai jumpa'], answer: 1 },
    { problem: 'Orang tua datang — sambutan?', options: ['Apa hal?','Selamat datang!','Siapa kamu?'], answer: 1 },
    { problem: 'Terpaksa tidak hadir — perkataan?', options: ['Tak apa','Maaf tidak dapat hadir','Sibuk'], answer: 1 },
    { problem: 'Makan bersama — adab?', options: ['Makan rakus','Makan perlahan dan sopan','Buang makanan'], answer: 1 },
  ]}},
  { title: 'Kata Ganda & Pengulangan', type: 'multiple_choice', emoji: '🔂', difficulty: 'medium', gameData: { questions: [
    { problem: '"Kucing-kucing" bermaksud?', options: ['Satu kucing','Banyak kucing','Besar kucing'], answer: 1 },
    { problem: '"Anak-anak" bermaksud?', options: ['Satu anak','Banyak anak','Anak besar'], answer: 1 },
    { problem: '"Bunga-bunga" bermaksud?', options: ['Satu bunga','Dua bunga','Banyak bunga'], answer: 2 },
    { problem: '"Rumah-rumah" bermaksud?', options: ['Satu rumah','Rumah besar','Banyak rumah'], answer: 2 },
    { problem: '"Pokok-pokok" bermaksud?', options: ['Pokok besar','Banyak pokok','Satu pokok'], answer: 1 },
    { problem: '"Batu-batu" bermaksud?', options: ['Satu batu','Dua batu','Banyak batu'], answer: 2 },
    { problem: 'Kata ganda dibuat untuk?', options: ['Nyatakan tunggal','Nyatakan jamak/banyak','Nyatakan besar'], answer: 1 },
    { problem: '"Sayur-sayuran" bermaksud?', options: ['Satu sayur','Macam-macam sayur','Sayur besar'], answer: 1 },
  ]}},
  { title: 'Sebutan & Ejaan Betul', type: 'multiple_choice', emoji: '🗣️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Ejaan betul "tmn" adalah?', options: ['taman','temen','temam'], answer: 0 },
    { problem: 'Ejaan betul "krta" adalah?', options: ['kereta','kareta','krete'], answer: 0 },
    { problem: 'Ejaan betul "skola" adalah?', options: ['sekolah','sekola','skolah'], answer: 0 },
    { problem: 'Ejaan betul "pgi" adalah?', options: ['pagi','pegi','pogi'], answer: 0 },
    { problem: 'Ejaan betul "mlm" adalah?', options: ['malam','milam','melam'], answer: 0 },
    { problem: 'Sebutan "bunga" — suku kata?', options: ['Bu-nga','Bun-ga','B-u-n-g-a'], answer: 0 },
    { problem: 'Sebutan "kucing" — suku kata?', options: ['Ku-cing','Kuc-ing','K-u-c-i-n-g'], answer: 0 },
    { problem: 'Huruf pertama "Sekolah" besar atau kecil?', options: ['Kecil','Besar','Sama'], answer: 1 },
  ]}},
  { title: 'Cerita Pendek - Tini dan Mainannya', type: 'multiple_choice', emoji: '🎀', difficulty: 'easy', gameData: { questions: [
    { problem: 'Cerita: "Tini ada boneka merah. Tini sayang boneka itu." — Tini punya apa?', options: ['Kereta','Boneka','Buku'], answer: 1 },
    { problem: 'Warna boneka Tini?', options: ['Biru','Merah','Kuning'], answer: 1 },
    { problem: 'Perasaan Tini kepada boneka?', options: ['Benci','Sayang','Takut'], answer: 1 },
    { problem: 'Boneka adalah?', options: ['Binatang','Mainan','Orang'], answer: 1 },
    { problem: 'Apa yang Tini lakukan dengan boneka?', options: ['Cuci','Main','Baca'], answer: 1 },
    { problem: 'Cerita ini mengajar kita?', options: ['Sayang mainan','Jual mainan','Buang mainan'], answer: 0 },
    { problem: 'Dari cerita, Tini adalah anak yang?', options: ['Jahat','Baik hati','Malas'], answer: 1 },
    { problem: 'Pelajaran dari cerita ialah?', options: ['Beli banyak mainan','Sayang mainan kita','Hanya main'], answer: 1 },
  ]}},
];