// Sekolah Rendah - Jawi EXPANSION (20+ soalan per game)
// Tier 1 CRITICAL FIX

export const sekolah_jawi_expansion_full = [
  { title: 'Alif hingga Dal Extended', type: 'letter_match', emoji: '🕌', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { letter: 'ا', emoji: '🍎', word: 'Alif', options: ['ا','ب','ت','ث'], answer: 0 },
    { letter: 'ب', emoji: '🐦', word: 'Ba', options: ['ا','ب','ت','ث'], answer: 1 },
    { letter: 'ت', emoji: '🐯', word: 'Ta', options: ['ا','ب','ت','ث'], answer: 2 },
    { letter: 'ث', emoji: '🧊', word: 'Tha', options: ['ا','ب','ت','ث'], answer: 3 },
    { letter: 'ج', emoji: '🦒', word: 'Jim', options: ['ج','ح','خ','د'], answer: 0 },
    { letter: 'ح', emoji: '🌸', word: 'Ha', options: ['ج','ح','خ','د'], answer: 1 },
    { letter: 'خ', emoji: '🌾', word: 'Kha', options: ['ج','ح','خ','د'], answer: 2 },
    { letter: 'د', emoji: '💎', word: 'Dal', options: ['ج','ح','خ','د'], answer: 3 },
    { letter: 'ذ', emoji: '🦌', word: 'Dzal', options: ['ذ','ر','ز','س'], answer: 0 },
    { letter: 'ر', emoji: '🌹', word: 'Ra', options: ['ذ','ر','ز','س'], answer: 1 },
    { letter: 'ز', emoji: '🌺', word: 'Zain', options: ['ذ','ر','ز','س'], answer: 2 },
    { letter: 'س', emoji: '⭐', word: 'Sin', options: ['ذ','ر','ز','س'], answer: 3 },
    { letter: 'ش', emoji: '☀️', word: 'Shin', options: ['ش','ص','ض','ط'], answer: 0 },
    { letter: 'ص', emoji: '🦅', word: 'Sad', options: ['ش','ص','ض','ط'], answer: 1 },
    { letter: 'ض', emoji: '🐊', word: 'Dad', options: ['ش','ص','ض','ط'], answer: 2 },
    { letter: 'ط', emoji: '🦚', word: 'Ta', options: ['ش','ص','ض','ط'], answer: 3 },
    { letter: 'ظ', emoji: '🦁', word: 'Zha', options: ['ظ','ع','غ','ف'], answer: 0 },
    { letter: 'ع', emoji: '🍇', word: 'Ain', options: ['ظ','ع','غ','ف'], answer: 1 },
    { letter: 'غ', emoji: '🦜', word: 'Ghain', options: ['ظ','ع','غ','ف'], answer: 2 },
    { letter: 'ف', emoji: '🦋', word: 'Fa', options: ['ظ','ع','غ','ف'], answer: 3 },
  ]}},
  { title: 'Sebutan Huruf Jawi Extended', type: 'sound_match', emoji: '🔊', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: 'ا', word: 'Alif', options: ['Alif','Ba','Ta'], answer: 0 },
    { image: 'ب', word: 'Ba', options: ['Alif','Ba','Ta'], answer: 1 },
    { image: 'ت', word: 'Ta', options: ['Ba','Ta','Jim'], answer: 1 },
    { image: 'ج', word: 'Jim', options: ['Ta','Jim','Kha'], answer: 1 },
    { image: 'ر', word: 'Ra', options: ['Za','Ra','Sin'], answer: 1 },
    { image: 'ك', word: 'Kaf', options: ['Qaf','Kaf','Lam'], answer: 1 },
    { image: 'م', word: 'Mim', options: ['Lam','Mim','Nun'], answer: 1 },
    { image: 'ن', word: 'Nun', options: ['Mim','Nun','Wau'], answer: 1 },
    { image: 'ع', word: 'Ain', options: ['Ghain','Ain','Fa'], answer: 1 },
    { image: 'ش', word: 'Shin', options: ['Sad','Shin','Dad'], answer: 1 },
    { image: 'و', word: 'Wau', options: ['Nun','Wau','Ha'], answer: 1 },
    { image: 'ي', word: 'Ya', options: ['Wau','Ya','Ha'], answer: 1 },
    { image: 'ق', word: 'Qaf', options: ['Kaf','Qaf','Lam'], answer: 1 },
    { image: 'ل', word: 'Lam', options: ['Kaf','Lam','Mim'], answer: 1 },
    { image: 'ه', word: 'Ha', options: ['Nun','Ha','Ya'], answer: 1 },
    { image: 'ز', word: 'Zain', options: ['Ra','Zain','Sin'], answer: 1 },
    { image: 'س', word: 'Sin', options: ['Zain','Sin','Shin'], answer: 1 },
    { image: 'د', word: 'Dal', options: ['Dzal','Dal','Ra'], answer: 1 },
    { image: 'ث', word: 'Tha', options: ['Ta','Tha','Jim'], answer: 1 },
    { image: 'خ', word: 'Kha', options: ['Ha','Kha','Jim'], answer: 1 },
  ]}},
  { title: 'Jawi - Nama Haiwan Extended', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '🐱', options: ['كوچيڠ','انجيڠ','ايام'], answer: 0 },
    { image: '🐶', options: ['كوچيڠ','انجيڠ','برونو'], answer: 1 },
    { image: '🐟', options: ['ايكن','بوروڠ','اولر'], answer: 0 },
    { image: '🐦', options: ['ايكن','بوروڠ','اولر'], answer: 1 },
    { image: '☀️', options: ['ماتاهاري','بولن','بيماكيڠ'], answer: 0 },
    { image: '🌙', options: ['ماتاهاري','بولن','بيماكيڠ'], answer: 1 },
    { image: '🍎', options: ['ايڤل','اورين','پيساڠ'], answer: 0 },
    { image: '🍌', options: ['ايڤل','اورين','پيساڠ'], answer: 2 },
    { image: '🐘', options: ['جاجه','كودا','بادق'], answer: 0 },
    { image: '🦁', options: ['سيڠا','هاريماو','بروانڠ'], answer: 0 },
    { image: '🐄', options: ['لمبو','كيربو','بيري-بيري'], answer: 0 },
    { image: '🐰', options: ['ارناب','توڤاي','تيكوس'], answer: 0 },
    { image: '🦒', options: ['جيراڤه','كودا','روسا'], answer: 0 },
    { image: '🐢', options: ['پينيو','بواياه','اولر'], answer: 0 },
    { image: '🐸', options: ['كاتق','اولر','پينيو'], answer: 0 },
    { image: '🦋', options: ['راما-راما','لباه','كومبڠ'], answer: 0 },
    { image: '🦜', options: ['ايلڠ','بوروڠ بيو','ڬاڬق'], answer: 1 },
    { image: '🦅', options: ['ايلڠ','بوروڠ بيو','پيڤيت'], answer: 0 },
    { image: '🐝', options: ['راما-راما','لباه','كومبڠ'], answer: 1 },
    { image: '🦔', options: ['لندق','تيكوس','ارناب'], answer: 0 },
  ]}},
];