// Prasekolah - Science - Expansion (10 games)
export const prasekolah_science_expansion = [
  { title: 'Makhluk Hidup vs Benda Mati', type: 'multiple_choice', emoji: '♻️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Burung adalah makhluk?', options: ['Hidup','Mati','Barang'], answer: 0 },
    { problem: 'Batu adalah benda?', options: ['Hidup','Mati','Hidup-mati'], answer: 1 },
    { problem: 'Pohon adalah makhluk?', options: ['Hidup','Mati','Barang'], answer: 0 },
    { problem: 'Gelas adalah benda?', options: ['Hidup','Mati','Barang'], answer: 2 },
    { problem: 'Kucing adalah makhluk?', options: ['Hidup','Mati','Barang'], answer: 0 },
    { problem: 'Air adalah benda?', options: ['Hidup','Mati','Cair/Barang'], answer: 2 },
    { problem: 'Ikan adalah makhluk?', options: ['Hidup','Mati','Barang'], answer: 0 },
    { problem: 'Meja adalah benda?', options: ['Hidup','Mati','Barang'], answer: 2 },
  ]}},
  { title: 'Organ Penting Manusia', type: 'picture_quiz', emoji: '❤️', difficulty: 'easy', gameData: { questions: [
    { image: '🧠', options: ['Paru','Otak','Hati'], answer: 1 },
    { image: '❤️', options: ['Otak','Jantung','Hati'], answer: 1 },
    { image: '💪', options: ['Otot','Tulang','Jantung'], answer: 0 },
    { image: '🫁', options: ['Paru-paru','Perut','Hati'], answer: 0 },
    { image: '👃', options: ['Hidung','Telinga','Mulut'], answer: 0 },
    { image: '👂', options: ['Mata','Telinga','Hidung'], answer: 1 },
    { image: '👁️', options: ['Hidung','Mata','Telinga'], answer: 1 },
    { image: '👅', options: ['Lidah','Bibir','Mulut'], answer: 0 },
  ]}},
  { title: 'Makanan Sihat dan Tidak Sihat', type: 'multiple_choice', emoji: '🥗', difficulty: 'easy', gameData: { questions: [
    { problem: 'Sayur adalah makanan?', options: ['Tidak sihat','Sihat','Tidak baik'], answer: 1 },
    { problem: 'Nasi adalah makanan?', options: ['Tidak sihat','Sihat','Campuran'], answer: 1 },
    { problem: 'Gula berlebihan baik?', options: ['Ya','Tidak','Mungkin'], answer: 1 },
    { problem: 'Makanan bergoreng boleh setiap hari?', options: ['Ya','Tidak','Boleh'], answer: 1 },
    { problem: 'Buah-buahan adalah makanan?', options: ['Tidak sihat','Sihat','Biasa'], answer: 1 },
    { problem: 'Air putih penting untuk?', options: ['Bermain','Kesihatan','Tidur'], answer: 1 },
    { problem: 'Susu baik untuk?', options: ['Gigi dan tulang','Perut','Kepala'], answer: 0 },
    { problem: 'Makanan sihat membantu?', options: ['Sakit','Tumbuh sihat','Main saja'], answer: 1 },
  ]}},
  { title: 'Siklus Air Mudah', type: 'multiple_choice', emoji: '💧', difficulty: 'easy', gameData: { questions: [
    { problem: 'Air dari laut pergi kemana?', options: ['Tetap','Naik ke udara','Turun ke tanah'], answer: 1 },
    { problem: 'Awan terbentuk dari?', options: ['Tanah','Udara/Uap air','Laut'], answer: 1 },
    { problem: 'Hujan berasal dari?', options: ['Laut','Awan','Matahari'], answer: 1 },
    { problem: 'Air hujan jatuh kemana?', options: ['Ke atas','Ke tanah','Ke matahari'], answer: 1 },
    { problem: 'Proses penguapan terjadi kerana?', options: ['Dingin','Panas matahari','Angin'], answer: 1 },
    { problem: 'Air laut menjadi air tawar bagaimana?', options: ['Menguap saja','Dimasak','Dibasuh'], answer: 0 },
    { problem: 'Siklus air penting untuk?', options: ['Bermain','Kehidupan makhluk','Warna'], answer: 1 },
    { problem: 'Kolam air berkurang sebab?', options: ['Diminum','Menguap','Buang'], answer: 1 },
  ]}},
  { title: 'Cahaya dan Bayangan', type: 'picture_quiz', emoji: '💡', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['Bintang','Cahaya','Panas'], answer: 1 },
    { image: '💡', options: ['Cahaya','Panas','Listrik'], answer: 0 },
    { image: '🕯️', options: ['Api','Cahaya','Panas'], answer: 1 },
    { image: '🌙', options: ['Cahaya sendiri','Cahaya pantul','Panas'], answer: 1 },
    { image: '⭐', options: ['Cahaya bulan','Cahaya sendiri','Pantulan'], answer: 1 },
    { image: '🔦', options: ['Cahaya matahari','Cahaya listrik','Cahaya api'], answer: 1 },
    { problem: 'Bayangan terbentuk kerana?', options: ['Cahaya di belakang','Cahaya di depan','Tidak ada cahaya'], answer: 0 },
    { problem: 'Bayangan panjang ketika?', options: ['Siang','Pagi/Sore','Malam'], answer: 1 },
  ]}},
  { title: 'Tiga Keadaan Benda - Padat Cair Gas', type: 'multiple_choice', emoji: '⚗️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Batu adalah benda?', options: ['Cair','Padat','Gas'], answer: 1 },
    { problem: 'Air adalah benda?', options: ['Padat','Cair','Gas'], answer: 1 },
    { problem: 'Udara adalah benda?', options: ['Padat','Cair','Gas'], answer: 2 },
    { problem: 'Es adalah benda?', options: ['Cair','Padat','Gas'], answer: 1 },
    { problem: 'Asap adalah benda?', options: ['Padat','Cair','Gas'], answer: 2 },
    { problem: 'Kayu adalah benda?', options: ['Cair','Padat','Gas'], answer: 1 },
    { problem: 'Uap adalah benda?', options: ['Padat','Cair','Gas'], answer: 2 },
    { problem: 'Minyak adalah benda?', options: ['Padat','Cair','Gas'], answer: 1 },
  ]}},
  { title: 'Habitat Haiwan', type: 'picture_quiz', emoji: '🏠', difficulty: 'easy', gameData: { questions: [
    { image: '🐠', options: ['Darat','Air','Udara'], answer: 1 },
    { image: '🦅', options: ['Laut','Darat','Udara'], answer: 2 },
    { image: '🦁', options: ['Darat','Air','Pohon'], answer: 0 },
    { image: '🦆', options: ['Air','Darat','Udara'], answer: 1 },
    { image: '🐍', options: ['Air','Pohon','Darat'], answer: 2 },
    { image: '🦝', options: ['Pohon','Bawah tanah','Gua'], answer: 1 },
    { image: '🐢', options: ['Darat','Air','Darat & Air'], answer: 2 },
    { image: '🐝', options: ['Darat','Pohon','Udara'], answer: 1 },
  ]}},
  { title: 'Perubahan Musim', type: 'multiple_choice', emoji: '🌍', difficulty: 'easy', gameData: { questions: [
    { problem: 'Malaysia ada berapa musim utama?', options: ['2','3','4'], answer: 0 },
    { problem: 'Musim panas ciri-cirinya?', options: ['Panas, cerah','Hujan, sejuk','Angin kuat'], answer: 0 },
    { problem: 'Musim hujan berlaku ketika?', options: ['Panas','Cerah','Banyak awan & hujan'], answer: 2 },
    { problem: 'Tanaman tumbuh baik ketika?', options: ['Panas','Hujan','Angin'], answer: 1 },
    { problem: 'Kami paling banyak air ketika?', options: ['Panas','Musim hujan','Kemarau'], answer: 1 },
    { problem: 'Matahari terletak dekat ketika?', options: ['Pagi','Siang','Malam'], answer: 1 },
    { problem: 'Suhu terendah ketika?', options: ['Siang','Petang','Malam'], answer: 2 },
    { problem: 'Apa penyebab perubahan musim?', options: ['Bumi','Bulan','Matahari'], answer: 2 },
  ]}},
  { title: 'Bintang dan Planet', type: 'picture_quiz', emoji: '🌟', difficulty: 'easy', gameData: { questions: [
    { image: '⭐', options: ['Planet','Bintang','Satelit'], answer: 1 },
    { image: '🌍', options: ['Bintang','Planet','Bulan'], answer: 1 },
    { image: '🌙', options: ['Bintang','Planet','Satelit'], answer: 2 },
    { image: '☀️', options: ['Planet','Bintang','Bulan'], answer: 1 },
    { image: '🪐', options: ['Satelit','Planet','Bintang'], answer: 1 },
    { image: '🔴', options: ['Bintang','Planet Marikh','Bulan'], answer: 1 },
    { problem: 'Bintang muncul ketika?', options: ['Pagi','Siang','Malam'], answer: 2 },
    { problem: 'Planet beredar mengelilingi?', options: ['Bulan','Bintang','Matahari'], answer: 2 },
  ]}},
  { title: 'Rantai Makanan Sederhana', type: 'multiple_choice', emoji: '🔗', difficulty: 'easy', gameData: { questions: [
    { problem: 'Rumput dimakan oleh?', options: ['Singa','Arnab','Manusia'], answer: 1 },
    { problem: 'Arnab dimakan oleh?', options: ['Burung','Singa','Tikus'], answer: 1 },
    { problem: 'Dalam rantai makanan, tumbuhan adalah?', options: ['Pemakan','Pembuat makanan','Pengurai'], answer: 1 },
    { problem: 'Haiwan karnivore makan?', options: ['Tumbuhan','Daging','Keduanya'], answer: 1 },
    { problem: 'Haiwan herbivore makan?', options: ['Daging','Tumbuhan','Keduanya'], answer: 1 },
    { problem: 'Manusia adalah?', options: ['Herbivore','Karnivore','Omnivore'], answer: 2 },
    { problem: 'Rantai makanan bermula dari?', options: ['Haiwan','Tumbuhan','Matahari'], answer: 1 },
    { problem: 'Siapa di akhir rantai makanan?', options: ['Tumbuhan','Haiwan kecil','Haiwan besar'], answer: 2 },
  ]}},
];