export const sekolah_english = [
  { title: 'Consonants G-N', type: 'letter_match', emoji: '🔤', difficulty: 'medium', gameData: { questions: [
    { letter: 'G', emoji: '🍇', word: 'Grapes', options: ['G','H','I','J'], answer: 0 },
    { letter: 'H', emoji: '🏠', word: 'House', options: ['G','H','I','J'], answer: 1 },
    { letter: 'I', emoji: '🍦', word: 'Ice Cream', options: ['G','H','I','J'], answer: 2 },
    { letter: 'J', emoji: '🤹', word: 'Juggler', options: ['G','H','I','J'], answer: 3 },
    { letter: 'K', emoji: '🪀', word: 'Kite', options: ['J','K','L','M'], answer: 1 },
    { letter: 'L', emoji: '🦁', word: 'Lion', options: ['J','K','L','M'], answer: 2 },
    { letter: 'M', emoji: '🌙', word: 'Moon', options: ['J','K','L','M'], answer: 3 },
    { letter: 'N', emoji: '🥜', word: 'Nut', options: ['M','N','O','P'], answer: 1 },
  ]}},
  { title: 'Simple Sentences - Reading', type: 'reading', emoji: '📖', difficulty: 'medium', gameData: { questions: [
    { problem: 'I like to play.', options: ['Play','Sleep','Eat'], answer: 0 },
    { problem: 'The cat is cute.', options: ['Cute','Big','Small'], answer: 0 },
    { problem: 'Mom cooks rice.', options: ['Rice','Bread','Noodle'], answer: 0 },
    { problem: 'Dad fixes the car.', options: ['Car','Bike','Bus'], answer: 0 },
    { problem: 'Sister plays with doll.', options: ['Doll','Ball','Toy'], answer: 0 },
    { problem: 'School is closed today.', options: ['Today','Tomorrow','Next week'], answer: 0 },
    { problem: 'We play in the park.', options: ['Park','Home','School'], answer: 0 },
    { problem: 'Brother drinks hot milk.', options: ['Milk','Water','Juice'], answer: 0 },
  ]}},
  { title: 'Daily Vocabulary', type: 'word_builder', emoji: '🔠', difficulty: 'medium', gameData: { questions: [
    { problem: 'h-u-s-', options: ['house','horse','haste'], answer: 0 },
    { problem: 's-h-o-l', options: ['school','shall','shoal'], answer: 0 },
    { problem: 'f-m-l-', options: ['family','female','formal'], answer: 0 },
    { problem: 'f-o-', options: ['food','fool','foot'], answer: 0 },
    { problem: 't-y', options: ['toy','try','tray'], answer: 0 },
    { problem: 'b-o-k', options: ['book','brook','break'], answer: 0 },
    { problem: 'p-n-i-', options: ['pencil','penal','panel'], answer: 0 },
    { problem: 't-b-l-', options: ['table','tablet','taboo'], answer: 0 },
  ]}},
  { title: 'Grammar - Nouns', type: 'multiple_choice', emoji: '📝', difficulty: 'medium', gameData: { questions: [
    { problem: 'Which is a noun?', options: ['run','book','happy'], answer: 1 },
    { problem: 'Which is a noun?', options: ['table','sleep','red'], answer: 0 },
    { problem: 'Which is a noun?', options: ['jump','school','big'], answer: 1 },
    { problem: 'Which is a noun?', options: ['green','cry','flower'], answer: 2 },
    { problem: 'Which is a noun?', options: ['tree','run','strong'], answer: 0 },
    { problem: 'Which is a noun?', options: ['small','drink','car'], answer: 2 },
    { problem: 'Which is a noun?', options: ['fly','bird','tall'], answer: 1 },
    { problem: 'Which is a noun?', options: ['river','swim','cold'], answer: 0 },
  ]}},
  { title: 'Grammar - Verbs', type: 'multiple_choice', emoji: '⚡', difficulty: 'medium', gameData: { questions: [
    { problem: 'Which is a verb?', options: ['run','book','happy'], answer: 0 },
    { problem: 'Which is a verb?', options: ['table','sleep','red'], answer: 1 },
    { problem: 'Which is a verb?', options: ['jump','school','big'], answer: 0 },
    { problem: 'Which is a verb?', options: ['green','cry','flower'], answer: 1 },
    { problem: 'Which is a verb?', options: ['tree','run','strong'], answer: 1 },
    { problem: 'Which is a verb?', options: ['small','drink','car'], answer: 1 },
    { problem: 'Which is a verb?', options: ['fly','bird','tall'], answer: 0 },
    { problem: 'Which is a verb?', options: ['river','swim','cold'], answer: 1 },
  ]}},
  { title: 'Antonyms (Opposite Words)', type: 'multiple_choice', emoji: '↔️', difficulty: 'medium', gameData: { questions: [
    { problem: 'Opposite of "big"?', options: ['small','medium','long'], answer: 0 },
    { problem: 'Opposite of "hot"?', options: ['warm','cold','cool'], answer: 1 },
    { problem: 'Opposite of "dark"?', options: ['dim','bright','dull'], answer: 1 },
    { problem: 'Opposite of "old"?', options: ['young','adult','teen'], answer: 0 },
    { problem: 'Opposite of "up"?', options: ['go','down','fall'], answer: 1 },
    { problem: 'Opposite of "day"?', options: ['evening','night','dawn'], answer: 1 },
    { problem: 'Opposite of "hard"?', options: ['soft','fine','smooth'], answer: 0 },
    { problem: 'Opposite of "fast"?', options: ['late','slow','quick'], answer: 1 },
  ]}},
  { title: 'Spelling Practice', type: 'spelling', emoji: '🔡', difficulty: 'medium', gameData: { questions: [
    { problem: 'Correct spelling of "frend"?', options: ['friend','frend','friand'], answer: 0 },
    { problem: 'Correct spelling of "lern"?', options: ['lerne','learn','leern'], answer: 1 },
    { problem: 'Correct spelling of "teecher"?', options: ['teacher','teecher','techer'], answer: 0 },
    { problem: 'Correct spelling of "moter"?', options: ['motor','moter','motir'], answer: 0 },
    { problem: 'Correct spelling of "wether"?', options: ['weather','wether','wethar'], answer: 0 },
    { problem: 'Correct spelling of "bycycle"?', options: ['bicycle','bycycle','bicycal'], answer: 0 },
    { problem: 'Correct spelling of "intresting"?', options: ['intresting','interesting','intersting'], answer: 1 },
    { problem: 'Correct spelling of "libary"?', options: ['library','libary','librery'], answer: 0 },
  ]}},
  { title: 'Tenses - Past & Present', type: 'multiple_choice', emoji: '⏰', difficulty: 'medium', gameData: { questions: [
    { problem: 'Past tense of "run"?', options: ['runned','ran','runs'], answer: 1 },
    { problem: 'Past tense of "eat"?', options: ['eated','ate','eats'], answer: 1 },
    { problem: 'Past tense of "play"?', options: ['played','play','plays'], answer: 0 },
    { problem: 'Past tense of "go"?', options: ['goed','went','goes'], answer: 1 },
    { problem: 'Past tense of "see"?', options: ['seed','saw','sees'], answer: 1 },
    { problem: 'Past tense of "drink"?', options: ['drinked','drank','drinks'], answer: 1 },
    { problem: 'Present tense: "She ___ to school"', options: ['go','goes','went'], answer: 1 },
    { problem: 'Present tense: "They ___ football"', options: ['plays','play','played'], answer: 1 },
  ]}},
  { title: 'Phonics - Letter Sounds', type: 'phonics', emoji: '🔊', difficulty: 'medium', gameData: { questions: [
    { problem: 'What sound does "ch" make in "chair"?', options: ['k','sh','ch'], answer: 2 },
    { problem: 'What sound does "th" make in "the"?', options: ['t','th','d'], answer: 1 },
    { problem: 'Word with "oo" sound?', options: ['moon','man','men'], answer: 0 },
    { problem: 'Word with "ai" sound?', options: ['rain','run','Ron'], answer: 0 },
    { problem: 'What sound does "ph" make?', options: ['p','f','ph'], answer: 1 },
    { problem: 'Word that rhymes with "cat"?', options: ['cup','bat','bit'], answer: 1 },
    { problem: 'Word that rhymes with "dog"?', options: ['fog','dug','dig'], answer: 0 },
    { problem: 'Word that rhymes with "ball"?', options: ['bill','bell','tall'], answer: 2 },
  ]}},
  { title: 'Comprehension - Short Paragraphs', type: 'reading', emoji: '📚', difficulty: 'hard', gameData: { questions: [
    { problem: 'Ali has a dog. The dog is brown. What colour is the dog?', options: ['Black','White','Brown'], answer: 2 },
    { problem: 'Siti eats an apple every day. What does Siti eat?', options: ['Orange','Apple','Banana'], answer: 1 },
    { problem: 'The sun rises in the morning. When does the sun rise?', options: ['Evening','Morning','Night'], answer: 1 },
    { problem: 'Tom reads books at the library. Where does Tom read?', options: ['Home','School','Library'], answer: 2 },
    { problem: 'Birds fly in the sky. Where do birds fly?', options: ['In the sea','In the sky','On the ground'], answer: 1 },
    { problem: 'She has two cats and one dog. How many pets does she have?', options: ['Two','Three','One'], answer: 1 },
    { problem: 'The children play after school. When do they play?', options: ['Before school','After school','During school'], answer: 1 },
    { problem: 'John is taller than Ali. Who is taller?', options: ['Ali','John','Both'], answer: 1 },
  ]}},
  { title: 'Grammar - Adjectives', type: 'multiple_choice', emoji: '🎨', difficulty: 'medium', gameData: { questions: [
    { problem: 'Which is an adjective?', options: ['run','book','happy'], answer: 2 },
    { problem: 'Which is an adjective?', options: ['table','sleep','red'], answer: 2 },
    { problem: 'Which is an adjective?', options: ['jump','school','big'], answer: 2 },
    { problem: 'Which is an adjective?', options: ['green','cry','flower'], answer: 0 },
    { problem: 'Which is an adjective?', options: ['tree','run','strong'], answer: 2 },
    { problem: 'Which is an adjective?', options: ['small','drink','car'], answer: 0 },
    { problem: 'Which is an adjective?', options: ['fly','bird','tall'], answer: 2 },
    { problem: 'Which is an adjective?', options: ['river','swim','cold'], answer: 2 },
  ]}},
  { title: 'Prepositions', type: 'multiple_choice', emoji: '📌', difficulty: 'medium', gameData: { questions: [
    { problem: 'The book is ___ the table.', options: ['in','on','under'], answer: 1 },
    { problem: 'The cat is hiding ___ the chair.', options: ['on','above','under'], answer: 2 },
    { problem: 'She lives ___ Kuala Lumpur.', options: ['at','in','on'], answer: 1 },
    { problem: 'He put the bag ___ the door.', options: ['near','in','on'], answer: 0 },
    { problem: 'The bird flew ___ the house.', options: ['under','over','between'], answer: 1 },
    { problem: 'She sat ___ her friends.', options: ['between','above','under'], answer: 0 },
    { problem: 'He arrived ___ 8 oclock.', options: ['in','at','on'], answer: 1 },
    { problem: 'We go to school ___ Monday.', options: ['in','at','on'], answer: 2 },
  ]}},
  { title: 'Synonyms - Similar Words', type: 'multiple_choice', emoji: '🔄', difficulty: 'medium', gameData: { questions: [
    { problem: 'Synonym of "happy"?', options: ['sad','joyful','angry'], answer: 1 },
    { problem: 'Synonym of "big"?', options: ['small','large','tiny'], answer: 1 },
    { problem: 'Synonym of "fast"?', options: ['slow','quick','lazy'], answer: 1 },
    { problem: 'Synonym of "beautiful"?', options: ['ugly','pretty','plain'], answer: 1 },
    { problem: 'Synonym of "smart"?', options: ['dumb','clever','silly'], answer: 1 },
    { problem: 'Synonym of "angry"?', options: ['calm','happy','furious'], answer: 2 },
    { problem: 'Synonym of "start"?', options: ['end','begin','stop'], answer: 1 },
    { problem: 'Synonym of "tired"?', options: ['energetic','exhausted','awake'], answer: 1 },
  ]}},
  { title: 'Future Tense - Will', type: 'multiple_choice', emoji: '🔮', difficulty: 'medium', gameData: { questions: [
    { problem: 'Tomorrow I ___ go to school.', options: ['went','will','going'], answer: 1 },
    { problem: 'She ___ cook dinner tonight.', options: ['cooked','will','is'], answer: 1 },
    { problem: 'They ___ play football next week.', options: ['played','will','are'], answer: 1 },
    { problem: 'He ___ finish his homework soon.', options: ['finished','will','has'], answer: 1 },
    { problem: '"Will" is used for?', options: ['Past','Future','Present'], answer: 1 },
    { problem: 'Correct sentence?', options: ['I will went home','I will go home','I will goes home'], answer: 1 },
    { problem: 'She will ___ (eat)?', options: ['eating','ate','eat'], answer: 2 },
    { problem: 'They will ___ (play)?', options: ['playing','played','play'], answer: 2 },
  ]}},
  { title: 'Singular and Plural', type: 'multiple_choice', emoji: '🔢', difficulty: 'medium', gameData: { questions: [
    { problem: 'Plural of "cat"?', options: ['cats','cates','cates'], answer: 0 },
    { problem: 'Plural of "box"?', options: ['boxs','boxes','boxies'], answer: 1 },
    { problem: 'Plural of "child"?', options: ['childs','childes','children'], answer: 2 },
    { problem: 'Plural of "mouse"?', options: ['mouses','mice','mouse'], answer: 1 },
    { problem: 'Plural of "tooth"?', options: ['tooths','teeths','teeth'], answer: 2 },
    { problem: 'Plural of "foot"?', options: ['foots','feet','feets'], answer: 1 },
    { problem: 'Plural of "sheep"?', options: ['sheeps','sheep','sheepes'], answer: 1 },
    { problem: 'Plural of "man"?', options: ['mans','men','manes'], answer: 1 },
  ]}},
  { title: 'Compound Words', type: 'word_builder', emoji: '🔗', difficulty: 'medium', gameData: { questions: [
    { problem: 'sun + flower = ?', options: ['sunflower','flowerun','sunfly'], answer: 0 },
    { problem: 'rain + bow = ?', options: ['bowrain','rainbow','rainbow'], answer: 1 },
    { problem: 'foot + ball = ?', options: ['ballfoot','football','footbal'], answer: 1 },
    { problem: 'tooth + brush = ?', options: ['brushooth','toothbrush','toothrush'], answer: 1 },
    { problem: 'book + shelf = ?', options: ['bookshelf','shelfbook','bookshef'], answer: 0 },
    { problem: 'air + port = ?', options: ['portair','airport','airpot'], answer: 1 },
    { problem: 'fire + work = ?', options: ['firework','workfire','firement'], answer: 0 },
    { problem: 'butter + fly = ?', options: ['flybutter','butterfli','butterfly'], answer: 2 },
  ]}},
  { title: 'Pronouns', type: 'multiple_choice', emoji: '👤', difficulty: 'medium', gameData: { questions: [
    { problem: 'Replace "Ali": "___ is tall."', options: ['She','He','They'], answer: 1 },
    { problem: 'Replace "Siti": "___ is clever."', options: ['He','She','They'], answer: 1 },
    { problem: 'Replace "the children": "___ are playing."', options: ['He','She','They'], answer: 2 },
    { problem: 'I told ___ (Ali) about it.', options: ['he','him','his'], answer: 1 },
    { problem: 'This is ___ (Siti\'s) book.', options: ['she','her','hers'], answer: 1 },
    { problem: 'We play with ___ (the children).', options: ['they','them','their'], answer: 1 },
    { problem: 'The dog wagged ___ tail.', options: ['it','its','it\'s'], answer: 1 },
    { problem: '"We" refers to?', options: ['One person','Two or more','Three only'], answer: 1 },
  ]}},
  { title: 'Questions Words - 5W1H', type: 'multiple_choice', emoji: '❓', difficulty: 'medium', gameData: { questions: [
    { problem: '"___ is your name?" — asking about person', options: ['Where','What','Who'], answer: 2 },
    { problem: '"___ do you live?" — asking about place', options: ['When','Where','Why'], answer: 1 },
    { problem: '"___ do you go to school?" — asking about time', options: ['Where','Who','When'], answer: 2 },
    { problem: '"___ are you late?" — asking for reason', options: ['How','Why','Where'], answer: 1 },
    { problem: '"___ is your favourite colour?" — asking about thing', options: ['What','Who','When'], answer: 0 },
    { problem: '"___ did you come to school?" — asking about manner', options: ['Why','Where','How'], answer: 2 },
    { problem: '"___ books do you have?" — asking about number', options: ['How many','How much','How far'], answer: 0 },
    { problem: '"___ is your teacher?" — asking about person', options: ['What','Who','Which'], answer: 1 },
  ]}},
  { title: 'Paragraph Writing - Fill in Blanks', type: 'reading', emoji: '✍️', difficulty: 'hard', gameData: { questions: [
    { problem: 'My name ___ Ali.', options: ['are','is','am'], answer: 1 },
    { problem: 'I ___ a student at SK Jaya.', options: ['are','is','am'], answer: 2 },
    { problem: 'My school ___ very big.', options: ['are','is','am'], answer: 1 },
    { problem: 'My friends ___ always kind.', options: ['are','is','am'], answer: 0 },
    { problem: 'We ___ learning English together.', options: ['are','is','am'], answer: 0 },
    { problem: 'Our teacher ___ very patient.', options: ['are','is','am'], answer: 1 },
    { problem: 'I ___ happy to be at school.', options: ['are','is','am'], answer: 2 },
    { problem: 'School ___ fun and exciting.', options: ['are','is','am'], answer: 1 },
  ]}},
  { title: 'Adverbs of Time', type: 'multiple_choice', emoji: '⏰', difficulty: 'medium', gameData: { questions: [
    { problem: 'I brush my teeth ___ (before sleeping).', options: ['yesterday','at night','tomorrow'], answer: 1 },
    { problem: 'She ___ goes to school on time.', options: ['never','always','yesterday'], answer: 1 },
    { problem: 'He was late ___.', options: ['today','tomorrow','yesterday'], answer: 2 },
    { problem: 'We will go ___ (the next day).', options: ['yesterday','today','tomorrow'], answer: 2 },
    { problem: 'She ___ eats vegetables (not at all).', options: ['always','often','never'], answer: 2 },
    { problem: 'He goes swimming ___ (from time to time).', options: ['never','sometimes','always'], answer: 1 },
    { problem: 'They ___ win the game (most of the time).', options: ['never','sometimes','usually'], answer: 2 },
    { problem: 'I eat breakfast ___ (each morning).', options: ['never','every day','sometimes'], answer: 1 },
  ]}},
];