export const prasekolah_mathematics = [
  { title: 'Kira 1 hingga 5', type: 'counting', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['1','2','3'], answer: 0 },
    { image: '🍎🍎', options: ['1','2','3'], answer: 1 },
    { image: '🍎🍎🍎', options: ['2','3','4'], answer: 1 },
    { image: '🍎🍎🍎🍎', options: ['3','4','5'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎', options: ['4','5','6'], answer: 1 },
    { image: '🌟🌟', options: ['1','2','3'], answer: 1 },
    { image: '🌟🌟🌟', options: ['2','3','4'], answer: 1 },
    { image: '🌟🌟🌟🌟', options: ['3','4','5'], answer: 1 },
  ]}},
  { title: 'Kira 6 hingga 10', type: 'counting', emoji: '🔟', difficulty: 'easy', gameData: { questions: [
    { image: '🍎🍎🍎🍎🍎🍎', options: ['5','6','7'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎', options: ['6','7','8'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎', options: ['7','8','9'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['8','9','10'], answer: 1 },
    { image: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['9','10','11'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { image: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
  ]}},
  { title: 'Nombor 1 hingga 10', type: 'number_match', emoji: '1️⃣', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐', options: ['1','2','3'], answer: 0 },
    { problem: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['1','2','3'], answer: 2 },
    { problem: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['4','5','6'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
  ]}},
  { title: 'Tambah 1+1 hingga 5+5', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '1+1', options: ['3','2','4','1'], answer: 1 },
    { problem: '2+1', options: ['4','3','5','2'], answer: 1 },
    { problem: '1+2', options: ['4','3','5','2'], answer: 1 },
    { problem: '2+2', options: ['6','4','5','3'], answer: 1 },
    { problem: '3+1', options: ['6','4','5','2'], answer: 1 },
    { problem: '2+3', options: ['7','5','6','4'], answer: 1 },
    { problem: '4+1', options: ['7','5','6','4'], answer: 1 },
    { problem: '3+3', options: ['7','6','8','5'], answer: 1 },
  ]}},
  { title: 'Bentuk Geometri Mudah', type: 'shape_sort', emoji: '🔵', difficulty: 'easy', gameData: { questions: [
    { image: '⭕', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 0 },
    { image: '⬜', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 2 },
    { image: '▭', options: ['Segiempat Tepat','Segi Empat','Bujur'], answer: 0 },
    { image: '⭐', options: ['Bintang','Bulatan','Segi Tiga'], answer: 0 },
    { image: '🔶', options: ['Berlian','Heksagon','Segi Empat'], answer: 0 },
    { image: '🔷', options: ['Berlian','Bujur','Segi Tiga'], answer: 0 },
    { image: '🔴', options: ['Bola','Bulatan','Cakera'], answer: 1 },
  ]}},
  { title: 'Lebih Besar atau Lebih Kecil', type: 'math_puzzle', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: '3 atau 5?', options: ['3 lebih besar','5 lebih besar','Sama'], answer: 1 },
    { problem: '7 atau 4?', options: ['7 lebih besar','4 lebih besar','Sama'], answer: 0 },
    { problem: '2 atau 2?', options: ['2 lebih besar','2 lebih kecil','Sama'], answer: 2 },
    { problem: '1 atau 9?', options: ['1 lebih besar','9 lebih besar','Sama'], answer: 1 },
    { problem: '6 atau 3?', options: ['6 lebih besar','3 lebih besar','Sama'], answer: 0 },
    { problem: '5 atau 8?', options: ['5 lebih besar','8 lebih besar','Sama'], answer: 1 },
    { problem: '4 atau 4?', options: ['4 lebih besar','4 lebih kecil','Sama'], answer: 2 },
    { problem: '10 atau 7?', options: ['10 lebih besar','7 lebih besar','Sama'], answer: 0 },
  ]}},
  { title: 'Tolak Mudah', type: 'math_puzzle', emoji: '➖', difficulty: 'easy', gameData: { questions: [
    { problem: '3-1', options: ['1','2','3','4'], answer: 1 },
    { problem: '5-2', options: ['2','3','4','5'], answer: 1 },
    { problem: '4-1', options: ['2','3','4','5'], answer: 1 },
    { problem: '6-3', options: ['2','3','4','5'], answer: 1 },
    { problem: '7-2', options: ['4','5','6','7'], answer: 1 },
    { problem: '8-4', options: ['3','4','5','6'], answer: 1 },
    { problem: '9-3', options: ['5','6','7','8'], answer: 1 },
    { problem: '10-5', options: ['4','5','6','7'], answer: 1 },
  ]}},
  { title: 'Susunan Nombor', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: 'Selepas 3 ialah?', options: ['2','4','5','3'], answer: 1 },
    { problem: 'Selepas 6 ialah?', options: ['5','7','8','6'], answer: 1 },
    { problem: 'Sebelum 5 ialah?', options: ['6','4','3','5'], answer: 1 },
    { problem: 'Sebelum 9 ialah?', options: ['10','8','7','9'], answer: 1 },
    { problem: 'Antara 4 dan 6?', options: ['3','5','7','4'], answer: 1 },
    { problem: 'Antara 1 dan 3?', options: ['0','2','4','1'], answer: 1 },
    { problem: 'Selepas 8 ialah?', options: ['7','9','10','8'], answer: 1 },
    { problem: 'Sebelum 2 ialah?', options: ['3','1','0','2'], answer: 1 },
  ]}},
  { title: 'Wang Syiling Kecil', type: 'counting', emoji: '💰', difficulty: 'medium', gameData: { questions: [
    { image: '🪙', options: ['10 sen','20 sen','50 sen'], answer: 0 },
    { image: '🪙🪙', options: ['10 sen','20 sen','30 sen'], answer: 1 },
    { image: '🪙🪙🪙', options: ['20 sen','30 sen','40 sen'], answer: 1 },
    { image: '🪙🪙🪙🪙🪙', options: ['40 sen','50 sen','60 sen'], answer: 1 },
    { image: '💵', options: ['RM 1','RM 2','RM 5'], answer: 0 },
    { image: '💵💵', options: ['RM 1','RM 2','RM 3'], answer: 1 },
    { image: '💵💵💵', options: ['RM 2','RM 3','RM 4'], answer: 1 },
    { image: '💵💵💵💵💵', options: ['RM 4','RM 5','RM 6'], answer: 1 },
  ]}},
  { title: 'Corak dan Urutan', type: 'pattern_fill', emoji: '🔷', difficulty: 'medium', gameData: { questions: [
    { problem: '🔴🔵🔴🔵?', options: ['🔴','🔵','🟢'], answer: 0 },
    { problem: '⭐🌙⭐🌙?', options: ['⭐','🌙','☀️'], answer: 0 },
    { problem: '1, 2, 3, ?', options: ['3','4','5'], answer: 1 },
    { problem: '2, 4, 6, ?', options: ['7','8','9'], answer: 1 },
    { problem: '🔺🔺🔵🔺🔺?', options: ['🔺','🔵','🔷'], answer: 1 },
    { problem: '5, 10, 15, ?', options: ['18','20','25'], answer: 1 },
    { problem: '🟡🟡🔴🟡🟡?', options: ['🟡','🔴','🔵'], answer: 1 },
    { problem: '1, 3, 5, ?', options: ['6','7','8'], answer: 1 },
  ]}},
  { title: 'Nombor 11 hingga 20', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '11 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 0 },
    { problem: '12 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 1 },
    { problem: '15 biji epal', options: ['Empat Belas','Lima Belas','Enam Belas'], answer: 1 },
    { problem: '17 biji epal', options: ['Enam Belas','Tujuh Belas','Lapan Belas'], answer: 1 },
    { problem: '20 biji epal', options: ['Sembilan Belas','Dua Puluh','Dua Puluh Satu'], answer: 1 },
    { problem: 'Lima belas = ?', options: ['14','15','16'], answer: 1 },
    { problem: 'Dua belas = ?', options: ['11','12','13'], answer: 1 },
    { problem: 'Dua puluh = ?', options: ['19','20','21'], answer: 1 },
  ]}},
  { title: 'Tambah hingga 10', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', gameData: { questions: [
    { problem: '4+5', options: ['7','9','8','10'], answer: 1 },
    { problem: '3+6', options: ['7','9','8','10'], answer: 1 },
    { problem: '5+4', options: ['7','9','8','10'], answer: 1 },
    { problem: '6+4', options: ['9','10','11','8'], answer: 1 },
    { problem: '7+3', options: ['9','10','11','8'], answer: 1 },
    { problem: '8+2', options: ['9','10','11','8'], answer: 1 },
    { problem: '5+5', options: ['9','10','11','8'], answer: 1 },
    { problem: '3+7', options: ['9','10','11','8'], answer: 1 },
  ]}},
  { title: 'Pasangan Nombor Sama', type: 'number_match', emoji: '🎯', difficulty: 'easy', gameData: { questions: [
    { problem: 'Lima = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'Tiga = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'Lapan = ?', options: ['7','8','9'], answer: 1 },
    { problem: 'Satu = ?', options: ['1','2','3'], answer: 0 },
    { problem: 'Sepuluh = ?', options: ['8','9','10'], answer: 2 },
    { problem: 'Dua = ?', options: ['1','2','3'], answer: 1 },
    { problem: 'Tujuh = ?', options: ['6','7','8'], answer: 1 },
    { problem: 'Sembilan = ?', options: ['8','9','10'], answer: 1 },
  ]}},
  { title: 'Bahagi Mudah', type: 'math_puzzle', emoji: '➗', difficulty: 'medium', gameData: { questions: [
    { problem: '4÷2', options: ['1','2','3'], answer: 1 },
    { problem: '6÷2', options: ['2','3','4'], answer: 1 },
    { problem: '6÷3', options: ['1','2','3'], answer: 2 },
    { problem: '8÷2', options: ['3','4','5'], answer: 1 },
    { problem: '10÷2', options: ['4','5','6'], answer: 1 },
    { problem: '9÷3', options: ['2','3','4'], answer: 1 },
    { problem: '4÷4', options: ['1','2','3'], answer: 0 },
    { problem: '10÷5', options: ['1','2','3'], answer: 1 },
  ]}},
  { title: 'Masa - Jam', type: 'multiple_choice', emoji: '⏰', difficulty: 'easy', gameData: { questions: [
    { problem: '1 jam = berapa minit?', options: ['30','60','100'], answer: 1 },
    { problem: 'Pagi bermula pada?', options: ['12 malam','12 tengahari','6 pagi'], answer: 2 },
    { problem: 'Tengahari pada pukul?', options: ['10 pagi','12 tengahari','2 petang'], answer: 1 },
    { problem: 'Malam bermula selepas?', options: ['Pagi','Tengahari','Petang'], answer: 2 },
    { problem: 'Separuh jam = berapa minit?', options: ['15','30','45'], answer: 1 },
    { problem: '1 hari = berapa jam?', options: ['12','24','48'], answer: 1 },
    { problem: 'Pukul 3 petang - 2 jam kemudian?', options: ['Pukul 4','Pukul 5','Pukul 6'], answer: 1 },
    { problem: 'Subuh adalah waktu?', options: ['Malam','Awal pagi','Petang'], answer: 1 },
  ]}},
  { title: 'Darab Mudah ×2 dan ×5', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', gameData: { questions: [
    { problem: '2×2', options: ['2','4','6'], answer: 1 },
    { problem: '2×3', options: ['4','6','8'], answer: 1 },
    { problem: '2×4', options: ['6','8','10'], answer: 1 },
    { problem: '2×5', options: ['8','10','12'], answer: 1 },
    { problem: '5×1', options: ['4','5','6'], answer: 1 },
    { problem: '5×2', options: ['8','10','12'], answer: 1 },
    { problem: '5×3', options: ['13','15','17'], answer: 1 },
    { problem: '5×4', options: ['18','20','22'], answer: 1 },
  ]}},
  { title: 'Ukuran - Panjang Pendek', type: 'multiple_choice', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: 'Mana lebih panjang?', options: ['Pensel','Pembaris','Sama'], answer: 1 },
    { problem: 'Mana lebih pendek?', options: ['Jari','Tangan','Sama'], answer: 0 },
    { problem: 'Mana lebih tinggi?', options: ['Kerusi','Meja','Sama'], answer: 1 },
    { problem: 'Mana lebih rendah?', options: ['Semut','Gajah','Sama'], answer: 0 },
    { problem: 'Mana lebih besar?', options: ['Kucing','Singa','Sama'], answer: 1 },
    { problem: 'Mana lebih kecil?', options: ['Gajah','Tikus','Sama'], answer: 1 },
    { problem: 'Mana lebih berat?', options: ['Buku','Pensel','Sama'], answer: 0 },
    { problem: 'Mana lebih ringan?', options: ['Batu','Bulu','Sama'], answer: 1 },
  ]}},
  { title: 'Nombor Ganjil dan Genap', type: 'multiple_choice', emoji: '🔢', difficulty: 'medium', gameData: { questions: [
    { problem: '2 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '3 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '4 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '7 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '10 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '5 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
    { problem: '8 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 1 },
    { problem: '1 adalah nombor?', options: ['Ganjil','Genap','Tiada'], answer: 0 },
  ]}},
  { title: 'Tolak hingga 20', type: 'math_puzzle', emoji: '➖', difficulty: 'medium', gameData: { questions: [
    { problem: '10-6', options: ['3','4','5'], answer: 1 },
    { problem: '12-5', options: ['6','7','8'], answer: 1 },
    { problem: '15-8', options: ['6','7','8'], answer: 1 },
    { problem: '18-9', options: ['8','9','10'], answer: 1 },
    { problem: '20-10', options: ['9','10','11'], answer: 1 },
    { problem: '14-7', options: ['6','7','8'], answer: 1 },
    { problem: '16-8', options: ['7','8','9'], answer: 1 },
    { problem: '11-4', options: ['6','7','8'], answer: 1 },
  ]}},
  { title: 'Berat - Ringan Berat', type: 'multiple_choice', emoji: '⚖️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Gajah atau semut — mana lebih berat?', options: ['Semut','Gajah','Sama'], answer: 1 },
    { problem: 'Batu atau kapas — mana lebih ringan?', options: ['Batu','Kapas','Sama'], answer: 1 },
    { problem: '1 kg atau 2 kg — mana lebih berat?', options: ['1 kg','2 kg','Sama'], answer: 1 },
    { problem: 'Kereta atau basikal — mana lebih berat?', options: ['Kereta','Basikal','Sama'], answer: 0 },
    { problem: 'Buku atau pensel — mana lebih berat?', options: ['Pensel','Buku','Sama'], answer: 1 },
    { problem: '500g atau 1kg — mana lebih ringan?', options: ['500g','1kg','Sama'], answer: 0 },
    { problem: 'Kamus atau buku cerita — mana lebih berat?', options: ['Buku cerita','Kamus','Sama'], answer: 1 },
    { problem: 'Cikgu atau murid — mana lebih berat biasanya?', options: ['Murid','Cikgu','Sama'], answer: 1 },
  ]}},
  { title: 'Tambah hingga 20', type: 'math_puzzle', emoji: '➕', difficulty: 'medium', gameData: { questions: [
    { problem: '8+5', options: ['11','13','12'], answer: 1 },
    { problem: '9+6', options: ['14','15','16'], answer: 1 },
    { problem: '7+8', options: ['14','15','16'], answer: 1 },
    { problem: '6+7', options: ['12','13','14'], answer: 1 },
    { problem: '9+9', options: ['17','18','19'], answer: 1 },
    { problem: '8+8', options: ['15','16','17'], answer: 1 },
    { problem: '7+7', options: ['13','14','15'], answer: 1 },
    { problem: '9+8', options: ['16','17','18'], answer: 1 },
  ]}},
  { title: 'Darab ×3 dan ×4', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', gameData: { questions: [
    { problem: '3×2', options: ['4','6','8'], answer: 1 },
    { problem: '3×3', options: ['6','9','12'], answer: 1 },
    { problem: '3×4', options: ['10','12','14'], answer: 1 },
    { problem: '3×5', options: ['13','15','17'], answer: 1 },
    { problem: '4×2', options: ['6','8','10'], answer: 1 },
    { problem: '4×3', options: ['10','12','14'], answer: 1 },
    { problem: '4×4', options: ['14','16','18'], answer: 1 },
    { problem: '4×5', options: ['18','20','22'], answer: 1 },
  ]}},
  { title: 'Nombor 21 hingga 50', type: 'number_match', emoji: '🔢', difficulty: 'medium', gameData: { questions: [
    { problem: '21 = ?', options: ['Dua Puluh','Dua Puluh Satu','Dua Puluh Dua'], answer: 1 },
    { problem: '30 = ?', options: ['Dua Puluh','Tiga Puluh','Empat Puluh'], answer: 1 },
    { problem: '35 = ?', options: ['Tiga Puluh Lima','Empat Puluh Lima','Lima Puluh'], answer: 0 },
    { problem: '40 = ?', options: ['Tiga Puluh','Empat Puluh','Lima Puluh'], answer: 1 },
    { problem: '45 = ?', options: ['Empat Puluh','Empat Puluh Lima','Lima Puluh'], answer: 1 },
    { problem: '50 = ?', options: ['Empat Puluh','Lima Puluh','Enam Puluh'], answer: 1 },
    { problem: 'Tiga puluh satu = ?', options: ['30','31','32'], answer: 1 },
    { problem: 'Empat puluh dua = ?', options: ['41','42','43'], answer: 1 },
  ]}},
  { title: 'Pecahan Mudah', type: 'math_puzzle', emoji: '🍕', difficulty: 'medium', gameData: { questions: [
    { problem: '1/2 bermaksud?', options: ['1 bahagian dari 3','Separuh','Satu pertiga'], answer: 1 },
    { problem: '1/4 bermaksud?', options: ['Separuh','Satu pertiga','Satu perempat'], answer: 2 },
    { problem: 'Pizza dibahagi 2 sama — tiap bahagian?', options: ['1/3','1/2','1/4'], answer: 1 },
    { problem: 'Kek dibahagi 4 — tiap bahagian?', options: ['1/2','1/3','1/4'], answer: 2 },
    { problem: '1/2 + 1/2 = ?', options: ['1/2','1','2'], answer: 1 },
    { problem: 'Mana lebih besar?', options: ['1/4','1/2','Sama'], answer: 1 },
    { problem: '3/4 bermaksud berapa bahagian dari 4?', options: ['2','3','4'], answer: 1 },
    { problem: 'Satu penuh = berapa separuh?', options: ['1','2','3'], answer: 1 },
  ]}},
  { title: 'Isipadu — Penuh dan Kosong', type: 'multiple_choice', emoji: '🥛', difficulty: 'easy', gameData: { questions: [
    { problem: 'Botol penuh — ada lebih atau kurang air?', options: ['Kurang','Lebih','Tiada'], answer: 1 },
    { problem: 'Botol kosong — ada berapa air?', options: ['Banyak','Sedikit','Tiada'], answer: 2 },
    { problem: 'Mana yang boleh tampung lebih air?', options: ['Sudu','Baldi','Cawan'], answer: 1 },
    { problem: '1 liter = berapa mililiter (ml)?', options: ['100','500','1000'], answer: 2 },
    { problem: 'Kurang dari separuh penuh bermaksud?', options: ['Hampir penuh','Hampir kosong','Penuh'], answer: 1 },
    { problem: 'Mana muat lebih banyak?', options: ['Cawan kecil','Tong besar','Sama'], answer: 1 },
    { problem: 'Jika tuang air dari baldi besar ke baldi kecil?', options: ['Muat semua','Melimpah','Tiada perubahan'], answer: 1 },
    { problem: 'Cara ukur isipadu cecair?', options: ['Timbang','Ukur panjang','Guna cawan ukur'], answer: 2 },
  ]}},
  { title: 'Tolak hingga 50', type: 'math_puzzle', emoji: '➖', difficulty: 'medium', gameData: { questions: [
    { problem: '20-8', options: ['10','12','14'], answer: 1 },
    { problem: '25-10', options: ['13','15','17'], answer: 1 },
    { problem: '30-15', options: ['13','15','17'], answer: 1 },
    { problem: '40-20', options: ['18','20','22'], answer: 1 },
    { problem: '35-15', options: ['18','20','22'], answer: 1 },
    { problem: '50-25', options: ['23','25','27'], answer: 1 },
    { problem: '28-14', options: ['12','14','16'], answer: 1 },
    { problem: '45-30', options: ['13','15','17'], answer: 1 },
  ]}},
  { title: 'Jadual Waktu', type: 'multiple_choice', emoji: '⏰', difficulty: 'medium', gameData: { questions: [
    { problem: 'Kamu bangun pagi pukul 6. 1 jam kemudian?', options: ['Pukul 6','Pukul 7','Pukul 8'], answer: 1 },
    { problem: 'Sekolah bermula pukul 7:30. 30 minit sebelum?', options: ['Pukul 6:30','Pukul 7:00','Pukul 7:30'], answer: 1 },
    { problem: 'Rehat pukul 10:00. 15 minit kemudian?', options: ['Pukul 10:05','Pukul 10:15','Pukul 10:30'], answer: 1 },
    { problem: '1 minit = berapa saat?', options: ['30','60','100'], answer: 1 },
    { problem: '1 jam = berapa saat?', options: ['600','3600','600'], answer: 1 },
    { problem: 'Tengahari ke petang = berapa jam?', options: ['2','3','4'], answer: 1 },
    { problem: 'Pagi ke malam = berapa jam kira-kira?', options: ['6','12','8'], answer: 1 },
    { problem: '1 minggu = berapa hari?', options: ['5','6','7'], answer: 2 },
  ]}},
  { title: 'Wang — Duit Syiling dan Nota', type: 'counting', emoji: '💰', difficulty: 'medium', gameData: { questions: [
    { image: '🪙🪙🪙🪙🪙', options: ['40 sen','50 sen','60 sen'], answer: 1 },
    { image: '💵', options: ['RM 1','RM 2','RM 5'], answer: 0 },
    { image: '💵💵', options: ['RM 2','RM 3','RM 4'], answer: 0 },
    { image: '💵💵💵💵💵', options: ['RM 4','RM 5','RM 6'], answer: 1 },
    { image: '🪙×10', options: ['RM 1','RM 2','RM 3'], answer: 0 },
    { image: '💵+🪙🪙', options: ['RM 1.10','RM 1.20','RM 2.10'], answer: 1 },
    { image: '💵💵+🪙🪙🪙', options: ['RM 2.20','RM 2.30','RM 3.30'], answer: 1 },
    { image: '💵💵💵+🪙×5', options: ['RM 3.40','RM 3.50','RM 4.50'], answer: 1 },
  ]}},
  { title: 'Geometri — Sisi dan Bucu', type: 'shape_sort', emoji: '📐', difficulty: 'medium', gameData: { questions: [
    { image: '△', options: ['2 sisi','3 sisi','4 sisi'], answer: 1 },
    { image: '⬜', options: ['3 sisi','4 sisi','5 sisi'], answer: 1 },
    { image: '⭕', options: ['0 sisi','1 sisi','2 sisi'], answer: 0 },
    { image: '▭', options: ['3 sisi','4 sisi','5 sisi'], answer: 1 },
    { image: '⭐', options: ['4 mata','5 mata','6 mata'], answer: 1 },
    { problem: 'Segi enam mempunyai berapa sisi?', options: ['5','6','7'], answer: 1 },
    { problem: 'Segi tiga mempunyai berapa bucu?', options: ['2','3','4'], answer: 1 },
    { problem: 'Segi empat sama mempunyai berapa sisi sama panjang?', options: ['2','3','4'], answer: 2 },
  ]}},
  { title: 'Nombor 51 hingga 100', type: 'number_match', emoji: '💯', difficulty: 'medium', gameData: { questions: [
    { problem: '60 = ?', options: ['Lima Puluh','Enam Puluh','Tujuh Puluh'], answer: 1 },
    { problem: '75 = ?', options: ['Tujuh Puluh Lima','Lapan Puluh Lima','Sembilan Puluh Lima'], answer: 0 },
    { problem: '80 = ?', options: ['Tujuh Puluh','Lapan Puluh','Sembilan Puluh'], answer: 1 },
    { problem: '100 = ?', options: ['Sembilan Puluh','Seratus','Satu Ratus Satu'], answer: 1 },
    { problem: 'Lima puluh = ?', options: ['40','50','60'], answer: 1 },
    { problem: 'Sembilan puluh = ?', options: ['80','90','100'], answer: 1 },
    { problem: 'Tujuh puluh lima = ?', options: ['65','75','85'], answer: 1 },
    { problem: 'Enam puluh enam = ?', options: ['56','66','76'], answer: 1 },
  ]}},
  { title: 'Tambah Tiga Digit Mudah', type: 'math_puzzle', emoji: '➕', difficulty: 'medium', gameData: { questions: [
    { problem: '50+30', options: ['70','80','90'], answer: 0 },
    { problem: '40+40', options: ['70','80','90'], answer: 1 },
    { problem: '60+20', options: ['70','80','90'], answer: 1 },
    { problem: '30+50', options: ['70','80','90'], answer: 1 },
    { problem: '25+25', options: ['40','50','60'], answer: 1 },
    { problem: '45+5', options: ['50','60','70'], answer: 0 },
    { problem: '35+15', options: ['45','50','55'], answer: 1 },
    { problem: '20+20+20', options: ['50','60','70'], answer: 1 },
  ]}},
  { title: 'Tolak Tiga Digit Mudah', type: 'math_puzzle', emoji: '➖', difficulty: 'medium', gameData: { questions: [
    { problem: '50-20', options: ['20','30','40'], answer: 1 },
    { problem: '80-30', options: ['40','50','60'], answer: 1 },
    { problem: '100-50', options: ['40','50','60'], answer: 1 },
    { problem: '70-40', options: ['20','30','40'], answer: 1 },
    { problem: '60-15', options: ['35','40','45'], answer: 2 },
    { problem: '90-30', options: ['50','60','70'], answer: 1 },
    { problem: '55-5', options: ['40','50','60'], answer: 1 },
    { problem: '75-25', options: ['40','50','60'], answer: 1 },
  ]}},
  { title: 'Darab ×6 dan ×7', type: 'math_puzzle', emoji: '✖️', difficulty: 'hard', gameData: { questions: [
    { problem: '6×2', options: ['10','12','14'], answer: 1 },
    { problem: '6×3', options: ['15','18','21'], answer: 1 },
    { problem: '6×4', options: ['20','24','28'], answer: 1 },
    { problem: '6×5', options: ['28','30','35'], answer: 1 },
    { problem: '7×2', options: ['12','14','16'], answer: 1 },
    { problem: '7×3', options: ['18','21','24'], answer: 1 },
    { problem: '7×4', options: ['24','28','32'], answer: 1 },
    { problem: '7×5', options: ['30','35','40'], answer: 1 },
  ]}},
  { title: 'Pecahan - Separuh dan Satu Perempat', type: 'math_puzzle', emoji: '🍕', difficulty: 'hard', gameData: { questions: [
    { problem: 'Pizza dibahagi 2 - tiap bahagian?', options: ['1/3','1/2','1/4'], answer: 1 },
    { problem: '1/2 sama dengan?', options: ['25%','50%','75%'], answer: 1 },
    { problem: 'Separuh dari 10?', options: ['3','5','7'], answer: 1 },
    { problem: 'Satu perempat dari 20?', options: ['3','5','7'], answer: 1 },
    { problem: '1/2 + 1/2 = ?', options: ['1/2','1','2'], answer: 1 },
    { problem: 'Kek dibahagi 4 - tiap bahagian?', options: ['1/2','1/3','1/4'], answer: 2 },
    { problem: 'Mana lebih besar - 1/2 atau 1/4?', options: ['1/4','1/2','Sama'], answer: 1 },
    { problem: '3/4 bermaksud berapa bahagian dari 4?', options: ['2','3','4'], answer: 1 },
  ]}},
  { title: 'Perbandingan - Lebih Berat Lebih Ringan', type: 'multiple_choice', emoji: '⚖️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Gajah atau semut - siapa lebih berat?', options: ['Semut','Gajah','Sama'], answer: 1 },
    { problem: 'Kapas atau besi - siapa lebih ringan?', options: ['Besi','Kapas','Sama'], answer: 1 },
    { problem: '1 kg atau 500g - mana lebih berat?', options: ['500g','1 kg','Sama'], answer: 1 },
    { problem: 'Buku atau pensel - mana lebih berat?', options: ['Pensel','Buku','Sama'], answer: 1 },
    { problem: 'Baldi air penuh atau kosong - mana lebih berat?', options: ['Kosong','Penuh','Sama'], answer: 1 },
    { problem: 'Bulu ayam atau batu - siapa lebih ringan?', options: ['Batu','Bulu','Sama'], answer: 1 },
    { problem: 'Kamus tebal atau buku nipis - mana lebih berat?', options: ['Buku Nipis','Kamus','Sama'], answer: 1 },
    { problem: 'Kapal atau mainan kapal - mana lebih berat?', options: ['Mainan','Kapal Sebenar','Sama'], answer: 1 },
  ]}},
  { title: 'Ukuran Panjang Pendek Tinggi Rendah', type: 'multiple_choice', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: 'Pensel atau pembaris - mana lebih panjang?', options: ['Pensel','Pembaris','Sama'], answer: 1 },
    { problem: 'Jari atau tangan - mana lebih panjang?', options: ['Jari','Tangan','Sama'], answer: 1 },
    { problem: 'Kerusi atau meja - mana lebih tinggi?', options: ['Kerusi','Meja','Sama'], answer: 1 },
    { problem: 'Semut atau gajah - mana lebih tinggi?', options: ['Semut','Gajah','Sama'], answer: 1 },
    { problem: 'Kucing atau singa - mana lebih besar?', options: ['Kucing','Singa','Sama'], answer: 1 },
    { problem: 'Gajah atau tikus - mana lebih besar?', options: ['Tikus','Gajah','Sama'], answer: 1 },
    { problem: 'Kayu atau benang - mana lebih keras?', options: ['Benang','Kayu','Sama'], answer: 1 },
    { problem: 'Kapas atau batu - mana lebih lembut?', options: ['Batu','Kapas','Sama'], answer: 1 },
  ]}},
  { title: 'Bentuk 3D - Kubus Sfera Silinder', type: 'shape_sort', emoji: '3️⃣', difficulty: 'hard', gameData: { questions: [
    { image: '⬜', options: ['Kubus','Sfera','Silinder'], answer: 0 },
    { image: '🔵', options: ['Kubus','Sfera','Silinder'], answer: 1 },
    { image: '🥫', options: ['Kubus','Sfera','Silinder'], answer: 2 },
    { image: '🎁', options: ['Kubus','Sfera','Piramid'], answer: 0 },
    { image: '🏀', options: ['Kubus','Sfera','Silinder'], answer: 1 },
    { image: '🍌', options: ['Silinder Bengkok','Silinder','Sfera'], answer: 0 },
    { image: '📦', options: ['Kubus','Sfera','Piramid'], answer: 0 },
    { image: '🎯', options: ['Sfera','Kubus','Silinder'], answer: 0 },
  ]}},
  { title: 'Waktu - Pagi Siang Malam', type: 'multiple_choice', emoji: '🕐', difficulty: 'easy', gameData: { questions: [
    { problem: 'Pagi adalah waktu?', options: ['6 pagi - 12 tengahari','12 tengahari - 6 petang','6 petang - 6 pagi'], answer: 0 },
    { problem: 'Siang adalah waktu?', options: ['Pagi Awal','Tengah Hari','Petang Akhir'], answer: 1 },
    { problem: 'Malam adalah waktu?', options: ['Awal Pagi','Petang Akhir - Pagi','Tengah Hari'], answer: 1 },
    { problem: 'Sekolah bermula pagi - jam berapa?', options: ['7:30','12:30','19:30'], answer: 0 },
    { problem: 'Makan tengahari pada?', options: ['Pagi','Tengah Hari','Malam'], answer: 1 },
    { problem: 'Tidur malam pada?', options: ['9 pagi','9 malam','9 petang'], answer: 1 },
    { problem: 'Berapa jam dari pagi ke malam?', options: ['8','12','24'], answer: 1 },
    { problem: 'Satu hari = ?', options: ['12 jam','24 jam','36 jam'], answer: 1 },
  ]}},
  ];