// Additional questions untuk Prasekolah BM games (20+ questions per game)

export const prasekolah_bahasa_melayu_expansion_full = [
  { title: 'Abjad A-H Lengkap', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', options: ['A', 'B', 'C', 'D'], answer: 0 },
    { letter: 'B', options: ['A', 'B', 'C', 'D'], answer: 1 },
    { letter: 'C', options: ['A', 'B', 'C', 'D'], answer: 2 },
    { letter: 'D', options: ['A', 'B', 'C', 'D'], answer: 3 },
    { letter: 'E', options: ['D', 'E', 'F', 'G'], answer: 1 },
    { letter: 'F', options: ['D', 'E', 'F', 'G'], answer: 2 },
    { letter: 'G', options: ['D', 'E', 'F', 'G'], answer: 3 },
    { letter: 'H', options: ['F', 'G', 'H', 'I'], answer: 2 },
    { letter: 'A', options: ['A', 'a', 'B', 'b'], answer: 0 },
    { letter: 'C', options: ['C', 'c', 'D', 'd'], answer: 0 },
    { letter: 'E', options: ['E', 'e', 'F', 'f'], answer: 0 },
    { letter: 'G', options: ['G', 'g', 'H', 'h'], answer: 0 },
    { letter: 'B', options: ['B', 'b', 'C', 'c'], answer: 0 },
    { letter: 'D', options: ['D', 'd', 'E', 'e'], answer: 0 },
    { letter: 'F', options: ['F', 'f', 'G', 'g'], answer: 0 },
    { letter: 'H', options: ['H', 'h', 'I', 'i'], answer: 0 },
    { letter: 'A', options: ['A', 'X', 'Y', 'Z'], answer: 0 },
    { letter: 'B', options: ['B', 'X', 'Y', 'Z'], answer: 0 },
    { letter: 'C', options: ['C', 'X', 'Y', 'Z'], answer: 0 },
    { letter: 'D', options: ['D', 'X', 'Y', 'Z'], answer: 0 },
  ]}},
  { title: 'Binatang Peliharaan Lengkap', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Kucing', 'Anjing', 'Kelinci'], answer: 0 },
    { image: '🐶', options: ['Kucing', 'Anjing', 'Burung'], answer: 1 },
    { image: '🐰', options: ['Kelinci', 'Tupai', 'Tikus'], answer: 0 },
    { image: '🐹', options: ['Hamster', 'Tupai', 'Tikus'], answer: 0 },
    { image: '🐦', options: ['Ayam', 'Itik', 'Burung'], answer: 2 },
    { image: '🐠', options: ['Ikan', 'Udang', 'Ketam'], answer: 0 },
    { image: '🐢', options: ['Penyu', 'Buaya', 'Ular'], answer: 0 },
    { image: '🦜', options: ['Kakak Tua', 'Burung Hantu', 'Elang'], answer: 0 },
    { image: '🐹', options: ['Hamster', 'Tikus', 'Kelinci'], answer: 0 },
    { image: '🐠', options: ['Ikan Hias', 'Ikan Lele', 'Udang'], answer: 0 },
    { image: '🐢', options: ['Penyu', 'Katak', 'Buaya'], answer: 0 },
    { image: '🐤', options: ['Anak Ayam', 'Anak Itik', 'Anak Angsa'], answer: 0 },
    { image: '🦗', options: ['Jangkrik', 'Lebah', 'Semut'], answer: 0 },
    { image: '🐛', options: ['Ulat', 'Cacing', 'Lipan'], answer: 0 },
    { image: '🦗', options: ['Belalang', 'Jangkrik', 'Sembab'], answer: 1 },
    { image: '🐁', options: ['Tikus', 'Tupai', 'Kelinci'], answer: 0 },
    { image: '🐁', options: ['Tikus', 'Hamster', 'Marmut'], answer: 0 },
    { image: '🦝', options: ['Rakun', 'Tupai', 'Musang'], answer: 0 },
    { image: '🐿️', options: ['Tupai', 'Kelinci', 'Tikus'], answer: 0 },
    { image: '🦕', options: ['Iguana', 'Buaya', 'Ular'], answer: 0 },
  ]}},
  { title: 'Buah-Buahan Lengkap', type: 'picture_quiz', emoji: '🍎', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['Epal', 'Oren', 'Pisang'], answer: 0 },
    { image: '🍌', options: ['Epal', 'Pisang', 'Mangga'], answer: 1 },
    { image: '🍊', options: ['Oren', 'Lemon', 'Anggur'], answer: 0 },
    { image: '🍋', options: ['Oren', 'Lemon', 'Jeruk'], answer: 1 },
    { image: '🍇', options: ['Anggur', 'Strawberi', 'Ceri'], answer: 0 },
    { image: '🍓', options: ['Anggur', 'Strawberi', 'Epal'], answer: 1 },
    { image: '🥝', options: ['Kiwi', 'Anggur', 'Lemon'], answer: 0 },
    { image: '🍑', options: ['Pic', 'Pear', 'Plum'], answer: 0 },
    { image: '🍒', options: ['Ceri', 'Strawberi', 'Anggur'], answer: 0 },
    { image: '🥭', options: ['Mangga', 'Paw-paw', 'Nanas'], answer: 0 },
    { image: '🍍', options: ['Nanas', 'Mangga', 'Paw-paw'], answer: 0 },
    { image: '🍉', options: ['Tembikai', 'Cantaloup', 'Susu Melon'], answer: 0 },
    { image: '🫐', options: ['Blueberi', 'Blackberi', 'Gooseberi'], answer: 0 },
    { image: '🍓', options: ['Strawberi', 'Rasberry', 'Blueberi'], answer: 0 },
    { image: '🥝', options: ['Kiwi', 'Starfruit', 'Dragon Fruit'], answer: 0 },
    { image: '🍑', options: ['Pic', 'Apricot', 'Nectarine'], answer: 0 },
    { image: '🍒', options: ['Ceri', 'Gooseberi', 'Currant'], answer: 0 },
    { image: '🥭', options: ['Mangga', 'Harimau Mangga', 'Mangga India'], answer: 0 },
    { image: '🍍', options: ['Nanas', 'Nanas Liar', 'Nanas Manis'], answer: 0 },
    { image: '🍈', options: ['Melon', 'Cantaloup', 'Honeydew'], answer: 0 },
  ]}},
  { title: 'Warna Lengkap', type: 'picture_quiz', emoji: '🌈', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Merah', 'Biru', 'Hijau'], answer: 0 },
    { image: '🔵', options: ['Merah', 'Biru', 'Kuning'], answer: 1 },
    { image: '🟢', options: ['Ungu', 'Hijau', 'Jingga'], answer: 1 },
    { image: '🟡', options: ['Kuning', 'Jingga', 'Putih'], answer: 0 },
    { image: '🟠', options: ['Kuning', 'Jingga', 'Merah'], answer: 1 },
    { image: '💜', options: ['Ungu', 'Merah Jambu', 'Biru'], answer: 0 },
    { image: '⚫', options: ['Coklat', 'Hitam', 'Kelabu'], answer: 1 },
    { image: '⚪', options: ['Putih', 'Hitam', 'Kelabu'], answer: 0 },
    { image: '🟤', options: ['Coklat', 'Kelabu', 'Hitam'], answer: 0 },
    { image: '🔴', options: ['Merah', 'Merah Jambu', 'Merah Tua'], answer: 0 },
    { image: '🔵', options: ['Biru', 'Biru Tua', 'Biru Muda'], answer: 0 },
    { image: '🟢', options: ['Hijau', 'Hijau Tua', 'Hijau Muda'], answer: 0 },
    { image: '🟡', options: ['Kuning', 'Kuning Pucat', 'Kuning Cerah'], answer: 0 },
    { image: '🟠', options: ['Jingga', 'Jingga Tua', 'Jingga Muda'], answer: 0 },
    { image: '💜', options: ['Ungu', 'Ungu Tua', 'Ungu Muda'], answer: 0 },
    { image: '🖤', options: ['Hitam', 'Kelabu', 'Coklat'], answer: 0 },
    { image: '🤍', options: ['Putih', 'Abu Putih', 'Pucat'], answer: 0 },
    { image: '🤎', options: ['Coklat', 'Coklat Tua', 'Coklat Muda'], answer: 0 },
    { image: '🩵', options: ['Biru Muda', 'Biru Langit', 'Turquoise'], answer: 0 },
    { image: '🩶', options: ['Kelabu', 'Kelabu Gelap', 'Kelabu Terang'], answer: 0 },
  ]}},
  { title: 'Keluarga Lengkap', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['Ayah', 'Ibu', 'Abang'], answer: 0 },
    { image: '👩', options: ['Ayah', 'Ibu', 'Kakak'], answer: 1 },
    { image: '👴', options: ['Ayah', 'Datuk', 'Abang'], answer: 1 },
    { image: '👵', options: ['Ibu', 'Nenek', 'Kakak'], answer: 1 },
    { image: '👦', options: ['Abang', 'Adik Lelaki', 'Datuk'], answer: 0 },
    { image: '👧', options: ['Kakak', 'Adik Perempuan', 'Nenek'], answer: 0 },
    { image: '👶', options: ['Bayi', 'Adik', 'Kanak-kanak'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['Keluarga', 'Kawan', 'Jiran'], answer: 0 },
    { image: '👪', options: ['Keluarga', 'Sekolah', 'Rumah'], answer: 0 },
    { image: '👨‍👩‍👦', options: ['Keluarga', 'Kawan', 'Jiran'], answer: 0 },
    { image: '👨‍👩‍👧‍👦', options: ['Keluarga Besar', 'Keluarga Kecil', 'Jiran'], answer: 0 },
    { image: '👨‍👨‍👧', options: ['Ayah Ayah', 'Abang Abang', 'Kawan'], answer: 0 },
    { image: '👩‍👩‍👦', options: ['Ibu Ibu', 'Kakak Kakak', 'Kawan'], answer: 0 },
    { image: '👨‍👧', options: ['Ayah Anak Perempuan', 'Ayah Anak Lelaki', 'Abang Adik'], answer: 0 },
    { image: '👩‍👦', options: ['Ibu Anak Lelaki', 'Ibu Anak Perempuan', 'Kakak Adik'], answer: 0 },
    { image: '👨‍👦', options: ['Ayah Anak Lelaki', 'Ayah Anak Perempuan', 'Abang Adik'], answer: 0 },
    { image: '👩‍👧', options: ['Ibu Anak Perempuan', 'Ibu Anak Lelaki', 'Kakak Adik'], answer: 0 },
    { image: '❤️', options: ['Cinta', 'Kecewa', 'Marah'], answer: 0 },
    { image: '💕', options: ['Cinta', 'Hati', 'Sayang'], answer: 0 },
    { image: '🏠', options: ['Rumah', 'Sekolah', 'Taman'], answer: 0 },
  ]}},
];