// Additional questions untuk Prasekolah English games (20+ questions per game)

export const prasekolah_english_expansion_full = [
  { title: 'Alphabet A-H Complete', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', options: ['A', 'B', 'C', 'D'], answer: 0 },
    { letter: 'B', options: ['A', 'B', 'C', 'D'], answer: 1 },
    { letter: 'C', options: ['A', 'B', 'C', 'D'], answer: 2 },
    { letter: 'D', options: ['A', 'B', 'C', 'D'], answer: 3 },
    { letter: 'E', options: ['D', 'E', 'F', 'G'], answer: 1 },
    { letter: 'F', options: ['D', 'E', 'F', 'G'], answer: 2 },
    { letter: 'G', options: ['D', 'E', 'F', 'G'], answer: 3 },
    { letter: 'H', options: ['F', 'G', 'H', 'I'], answer: 2 },
    { letter: 'A', options: ['A', 'a', 'B', 'b'], answer: 0 },
    { letter: 'C', options: ['C', 'c', 'D', 'd'], answer: 0 },
    { letter: 'E', options: ['E', 'e', 'F', 'f'], answer: 0 },
    { letter: 'G', options: ['G', 'g', 'H', 'h'], answer: 0 },
    { letter: 'B', options: ['B', 'b', 'C', 'c'], answer: 0 },
    { letter: 'D', options: ['D', 'd', 'E', 'e'], answer: 0 },
    { letter: 'F', options: ['F', 'f', 'G', 'g'], answer: 0 },
    { letter: 'H', options: ['H', 'h', 'I', 'i'], answer: 0 },
    { letter: 'A', options: ['A', 'X', 'Y', 'Z'], answer: 0 },
    { letter: 'B', options: ['B', 'X', 'Y', 'Z'], answer: 0 },
    { letter: 'C', options: ['C', 'X', 'Y', 'Z'], answer: 0 },
    { letter: 'D', options: ['D', 'X', 'Y', 'Z'], answer: 0 },
  ]}},
  { title: 'Animals Complete', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Cat', 'Dog', 'Rabbit'], answer: 0 },
    { image: '🐶', options: ['Cat', 'Dog', 'Bird'], answer: 1 },
    { image: '🐰', options: ['Rabbit', 'Squirrel', 'Mouse'], answer: 0 },
    { image: '🐹', options: ['Hamster', 'Squirrel', 'Mouse'], answer: 0 },
    { image: '🐦', options: ['Chicken', 'Duck', 'Bird'], answer: 2 },
    { image: '🐠', options: ['Fish', 'Shrimp', 'Crab'], answer: 0 },
    { image: '🐢', options: ['Turtle', 'Crocodile', 'Snake'], answer: 0 },
    { image: '🦜', options: ['Parrot', 'Owl', 'Eagle'], answer: 0 },
    { image: '🐹', options: ['Hamster', 'Mouse', 'Rabbit'], answer: 0 },
    { image: '🐠', options: ['Goldfish', 'Catfish', 'Shrimp'], answer: 0 },
    { image: '🐢', options: ['Turtle', 'Frog', 'Crocodile'], answer: 0 },
    { image: '🐤', options: ['Chick', 'Duckling', 'Gosling'], answer: 0 },
    { image: '🦗', options: ['Cricket', 'Bee', 'Ant'], answer: 0 },
    { image: '🐛', options: ['Worm', 'Earthworm', 'Millipede'], answer: 0 },
    { image: '🦗', options: ['Grasshopper', 'Cricket', 'Moth'], answer: 1 },
    { image: '🐁', options: ['Mouse', 'Squirrel', 'Rabbit'], answer: 0 },
    { image: '🐁', options: ['Mouse', 'Hamster', 'Guinea Pig'], answer: 0 },
    { image: '🦝', options: ['Raccoon', 'Squirrel', 'Civet'], answer: 0 },
    { image: '🐿️', options: ['Squirrel', 'Rabbit', 'Mouse'], answer: 0 },
    { image: '🦕', options: ['Iguana', 'Crocodile', 'Snake'], answer: 0 },
  ]}},
  { title: 'Fruits Complete', type: 'picture_quiz', emoji: '🍎', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['Apple', 'Orange', 'Banana'], answer: 0 },
    { image: '🍌', options: ['Apple', 'Banana', 'Mango'], answer: 1 },
    { image: '🍊', options: ['Orange', 'Lemon', 'Grape'], answer: 0 },
    { image: '🍋', options: ['Orange', 'Lemon', 'Lime'], answer: 1 },
    { image: '🍇', options: ['Grape', 'Strawberry', 'Cherry'], answer: 0 },
    { image: '🍓', options: ['Grape', 'Strawberry', 'Apple'], answer: 1 },
    { image: '🥝', options: ['Kiwi', 'Grape', 'Lemon'], answer: 0 },
    { image: '🍑', options: ['Peach', 'Pear', 'Plum'], answer: 0 },
    { image: '🍒', options: ['Cherry', 'Strawberry', 'Grape'], answer: 0 },
    { image: '🥭', options: ['Mango', 'Papaya', 'Pineapple'], answer: 0 },
    { image: '🍍', options: ['Pineapple', 'Mango', 'Papaya'], answer: 0 },
    { image: '🍉', options: ['Watermelon', 'Cantaloupe', 'Honeydew'], answer: 0 },
    { image: '🫐', options: ['Blueberry', 'Blackberry', 'Gooseberry'], answer: 0 },
    { image: '🍓', options: ['Strawberry', 'Raspberry', 'Blueberry'], answer: 0 },
    { image: '🥝', options: ['Kiwi', 'Starfruit', 'Dragon Fruit'], answer: 0 },
    { image: '🍑', options: ['Peach', 'Apricot', 'Nectarine'], answer: 0 },
    { image: '🍒', options: ['Cherry', 'Gooseberry', 'Currant'], answer: 0 },
    { image: '🥭', options: ['Mango', 'Mango King', 'Indian Mango'], answer: 0 },
    { image: '🍍', options: ['Pineapple', 'Wild Pineapple', 'Sweet Pineapple'], answer: 0 },
    { image: '🍈', options: ['Melon', 'Cantaloupe', 'Honeydew'], answer: 0 },
  ]}},
  { title: 'Colors Complete', type: 'picture_quiz', emoji: '🌈', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Red', 'Blue', 'Green'], answer: 0 },
    { image: '🔵', options: ['Red', 'Blue', 'Yellow'], answer: 1 },
    { image: '🟢', options: ['Purple', 'Green', 'Orange'], answer: 1 },
    { image: '🟡', options: ['Yellow', 'Orange', 'White'], answer: 0 },
    { image: '🟠', options: ['Yellow', 'Orange', 'Red'], answer: 1 },
    { image: '💜', options: ['Purple', 'Pink', 'Blue'], answer: 0 },
    { image: '⚫', options: ['Brown', 'Black', 'Gray'], answer: 1 },
    { image: '⚪', options: ['White', 'Black', 'Gray'], answer: 0 },
    { image: '🟤', options: ['Brown', 'Gray', 'Black'], answer: 0 },
    { image: '🔴', options: ['Red', 'Dark Red', 'Light Red'], answer: 0 },
    { image: '🔵', options: ['Blue', 'Dark Blue', 'Light Blue'], answer: 0 },
    { image: '🟢', options: ['Green', 'Dark Green', 'Light Green'], answer: 0 },
    { image: '🟡', options: ['Yellow', 'Light Yellow', 'Bright Yellow'], answer: 0 },
    { image: '🟠', options: ['Orange', 'Dark Orange', 'Light Orange'], answer: 0 },
    { image: '💜', options: ['Purple', 'Dark Purple', 'Light Purple'], answer: 0 },
    { image: '🖤', options: ['Black', 'Gray', 'Brown'], answer: 0 },
    { image: '🤍', options: ['White', 'Off-White', 'Pale'], answer: 0 },
    { image: '🤎', options: ['Brown', 'Dark Brown', 'Light Brown'], answer: 0 },
    { image: '🩵', options: ['Light Blue', 'Sky Blue', 'Turquoise'], answer: 0 },
    { image: '🩶', options: ['Gray', 'Dark Gray', 'Light Gray'], answer: 0 },
  ]}},
  { title: 'Family Complete', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['Father', 'Mother', 'Brother'], answer: 0 },
    { image: '👩', options: ['Father', 'Mother', 'Sister'], answer: 1 },
    { image: '👴', options: ['Father', 'Grandfather', 'Brother'], answer: 1 },
    { image: '👵', options: ['Mother', 'Grandmother', 'Sister'], answer: 1 },
    { image: '👦', options: ['Brother', 'Little Brother', 'Grandfather'], answer: 0 },
    { image: '👧', options: ['Sister', 'Little Sister', 'Grandmother'], answer: 0 },
    { image: '👶', options: ['Baby', 'Brother', 'Child'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['Family', 'Friends', 'Neighbors'], answer: 0 },
    { image: '👪', options: ['Family', 'School', 'Home'], answer: 0 },
    { image: '👨‍👩‍👦', options: ['Family', 'Friends', 'Neighbors'], answer: 0 },
    { image: '👨‍👩‍👧‍👦', options: ['Big Family', 'Small Family', 'Neighbors'], answer: 0 },
    { image: '👨‍👨‍👧', options: ['Two Fathers', 'Two Brothers', 'Friends'], answer: 0 },
    { image: '👩‍👩‍👦', options: ['Two Mothers', 'Two Sisters', 'Friends'], answer: 0 },
    { image: '👨‍👧', options: ['Father Daughter', 'Father Son', 'Brother Sister'], answer: 0 },
    { image: '👩‍👦', options: ['Mother Son', 'Mother Daughter', 'Sister Brother'], answer: 0 },
    { image: '👨‍👦', options: ['Father Son', 'Father Daughter', 'Brother Sister'], answer: 0 },
    { image: '👩‍👧', options: ['Mother Daughter', 'Mother Son', 'Sister Brother'], answer: 0 },
    { image: '❤️', options: ['Love', 'Sad', 'Angry'], answer: 0 },
    { image: '💕', options: ['Love', 'Heart', 'Care'], answer: 0 },
    { image: '🏠', options: ['House', 'School', 'Park'], answer: 0 },
  ]}},
];