export const sekolah_bahasa_mandarin_expansion = [
  {
    title: '阅读理解 - 短故事',
    type: 'reading',
    emoji: '📖',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '故事："一个叫阿默德的男孩很懒惰。他不喜欢学习。每天只玩。他的母亲经常帮他学习，但阿默德不感到羞愧。" - 阿默德的性格是什么？', options: ['勤劳', '懒惰', '勇敢'], answer: 1 },
      { problem: '阿默德每天做什么？', options: ['学习', '玩耍', '工作'], answer: 1 },
      { problem: '谁帮助阿默德学习？', options: ['父亲', '母亲', '老师'], answer: 1 },
      { problem: '这个故事教给我们什么？', options: ['玩耍很好', '懒惰是坏的', '学校很无聊'], answer: 1 },
      { problem: '故事中有多少人？', options: ['1', '2', '3'], answer: 1 },
      { problem: '阿默德感到羞愧吗？', options: ['是', '不是', '也许'], answer: 1 },
      { problem: '故事讲的是什么？', options: ['幸福的家庭', '懒惰的男孩', '学校的工作'], answer: 1 },
      { problem: '阿默德应该做什么？', options: ['玩得更多', '努力学习', '睡觉'], answer: 1 },
      { problem: '阿默德母亲的性格是什么？', options: ['严格', '耐心', '懒惰'], answer: 1 },
      { problem: '这个故事的教训是什么？', options: ['玩很重要', '学习非常重要', '母亲很烦'], answer: 1 },
      { problem: '故事表明什么？', options: ['母亲的爱', '男孩的懒惰', '学校的困难'], answer: 0 },
      { problem: '关于阿默德什么是对的？', options: ['他学习努力', '他对学习很懒', '他喜欢书'], answer: 1 },
      { problem: '如果阿默德继续懒惰？', options: ['成功', '失败', '不确定'], answer: 1 },
      { problem: '母亲的行为表现什么？', options: ['愤怒', '帮助的努力', '放弃'], answer: 1 },
      { problem: '故事的主要问题？', options: ['贫困', '学习的懒惰', '生病'], answer: 1 },
      { problem: '故事的背景在哪里？', options: ['学校', '家里', '公园'], answer: 1 },
      { problem: '故事的时间是什么时候？', options: ['过去', '现在', '将来'], answer: 0 },
      { problem: '阿默德需要什么来改变？', options: ['惩罚', '努力和纪律', '新学校'], answer: 1 },
      { problem: '母亲爱阿默德吗？', options: ['是', '不是', '不确定'], answer: 0 },
      { problem: '故事的信息是关于什么？', options: ['家庭问题', '努力工作的重要性', '学校规则'], answer: 1 },
    ]}
  },
  {
    title: '汉字 - 基础认识',
    type: 'letter_match',
    emoji: '🔤',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { letter: '一', options: ['一', '二', '三', '四'], answer: 0 },
      { letter: '二', options: ['一', '二', '三', '四'], answer: 1 },
      { letter: '三', options: ['一', '二', '三', '四'], answer: 2 },
      { letter: '四', options: ['一', '二', '三', '四'], answer: 3 },
      { letter: '五', options: ['五', '六', '七', '八'], answer: 0 },
      { letter: '六', options: ['五', '六', '七', '八'], answer: 1 },
      { letter: '七', options: ['五', '六', '七', '八'], answer: 2 },
      { letter: '八', options: ['五', '六', '七', '八'], answer: 3 },
      { letter: '九', options: ['九', '十', '十一', '十二'], answer: 0 },
      { letter: '十', options: ['九', '十', '十一', '十二'], answer: 1 },
      { letter: '人', options: ['人', '大', '小', '山'], answer: 0 },
      { letter: '大', options: ['人', '大', '小', '山'], answer: 1 },
      { letter: '小', options: ['人', '大', '小', '山'], answer: 2 },
      { letter: '山', options: ['人', '大', '小', '山'], answer: 3 },
      { letter: '水', options: ['水', '火', '土', '木'], answer: 0 },
      { letter: '火', options: ['水', '火', '土', '木'], answer: 1 },
      { letter: '土', options: ['水', '火', '土', '木'], answer: 2 },
      { letter: '木', options: ['水', '火', '土', '木'], answer: 3 },
      { letter: '日', options: ['日', '月', '星', '天'], answer: 0 },
      { letter: '月', options: ['日', '月', '星', '天'], answer: 1 },
    ]}
  },
  {
    title: '词汇 - 常见单词',
    type: 'picture_quiz',
    emoji: '📚',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { image: '🏠', options: ['学校', '房子', '市场'], answer: 1 },
      { image: '📚', options: ['笔', '书', '桌子'], answer: 1 },
      { image: '✏️', options: ['铅笔', '纸', '橡皮'], answer: 0 },
      { image: '🚗', options: ['公共汽车', '汽车', '卡车'], answer: 1 },
      { image: '🍎', options: ['香蕉', '苹果', '橙子'], answer: 1 },
      { image: '🌳', options: ['花', '树', '草'], answer: 1 },
      { image: '👨', options: ['女人', '男人', '孩子'], answer: 1 },
      { image: '👨‍👩‍👧‍👦', options: ['朋友', '家庭', '团队'], answer: 1 },
      { image: '🎒', options: ['包', '背包', '行李箱'], answer: 1 },
      { image: '🏫', options: ['医院', '学校', '图书馆'], answer: 1 },
      { image: '⚽', options: ['球', '足球', '运动球'], answer: 2 },
      { image: '🍕', options: ['披萨', '面包', '蛋糕'], answer: 0 },
      { image: '☕', options: ['水', '咖啡', '果汁'], answer: 1 },
      { image: '🎨', options: ['油漆', '艺术', '颜色'], answer: 1 },
      { image: '🎵', options: ['歌曲', '音乐', '声音'], answer: 1 },
      { image: '💻', options: ['计算机', '电话', '平板'], answer: 0 },
      { image: '📱', options: ['计算机', '电话', '照相机'], answer: 1 },
      { image: '🕐', options: ['时钟', '手表', '时间'], answer: 1 },
      { image: '📺', options: ['收音机', '电视', '电话'], answer: 1 },
      { image: '🌟', options: ['月亮', '星星', '太阳'], answer: 1 },
    ]}
  },
  {
    title: '语法 - 主语和动词',
    type: 'multiple_choice',
    emoji: '📝',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '"The cat ___ milk"的动词是？', options: ['drink', 'drinks', 'drinking'], answer: 1 },
      { problem: '"The dogs ___ in the park"的动词是？', options: ['play', 'plays', 'playing'], answer: 0 },
      { problem: '"She ___ very smart"的动词是？', options: ['are', 'is', 'am'], answer: 1 },
      { problem: '"They ___ friends"的动词是？', options: ['is', 'are', 'am'], answer: 1 },
      { problem: '"I ___ a student"的动词是？', options: ['is', 'are', 'am'], answer: 2 },
      { problem: '"He ___ to school every day"的动词是？', options: ['go', 'goes', 'going'], answer: 1 },
      { problem: '"The children ___ happy"的动词是？', options: ['is', 'are', 'am'], answer: 1 },
      { problem: '"My mother ___ cooking"的动词是？', options: ['is', 'are', 'be'], answer: 0 },
      { problem: '"This book ___ interesting"的动词是？', options: ['are', 'is', 'am'], answer: 1 },
      { problem: '"These shoes ___ expensive"的动词是？', options: ['is', 'are', 'am'], answer: 1 },
      { problem: '"My friend ___ a teacher"的动词是？', options: ['are', 'is', 'am'], answer: 1 },
      { problem: '"The students ___ their homework"的动词是？', options: ['do', 'does', 'doing'], answer: 0 },
      { problem: '"She ___ ice cream"的动词是？', options: ['like', 'likes', 'liking'], answer: 1 },
      { problem: '"We ___ English"的动词是？', options: ['speaks', 'speak', 'speaking'], answer: 1 },
      { problem: '"The bird ___ in the sky"的动词是？', options: ['fly', 'flies', 'flying'], answer: 1 },
      { problem: '复数主语需要什么动词？', options: ['单数', '复数', '不变'], answer: 0 },
      { problem: '单数主语需要什么动词？', options: ['复数', '单数', '不变'], answer: 1 },
      { problem: '"I"主语使用什么动词形式？', options: ['is', 'are', 'am'], answer: 2 },
      { problem: '"you"主语使用什么动词形式？', options: ['is', 'are', 'am'], answer: 1 },
      { problem: '在第三人称单数，动词加什么？', options: ['-ing', '-ed', '-s or -es'], answer: 2 },
    ]}
  },
  {
    title: '对话和交谈',
    type: 'multiple_choice',
    emoji: '💬',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: '早上问好说什么？', options: ['"Good night"', '"Good morning"', '"Good evening"'], answer: 1 },
      { problem: '感谢某人说什么？', options: ['"Sorry"', '"Thank you"', '"Hello"'], answer: 1 },
      { problem: '道歉说什么？', options: ['"Thank you"', '"I\'m sorry"', '"Goodbye"'], answer: 1 },
      { problem: '说再见说什么？', options: ['"Hello"', '"See you later"', '"Good night" only'], answer: 1 },
      { problem: '在课堂上问老师怎么说？', options: ['"Oi teacher"', '"Excuse me, can you explain?"', '"Teach me"'], answer: 1 },
      { problem: '请求离开怎么问？', options: ['"I\'m going"', '"May I leave?"', '"Let me go"'], answer: 1 },
      { problem: '问别人的名字怎么问？', options: ['"What is your name?"', '"You?"', '"Name?"'], answer: 0 },
      { problem: '问别人怎么样怎么问？', options: ['"How are you?"', '"You good?"', '"How you?"'], answer: 0 },
      { problem: '对"How are you?"的回答？', options: ['"How are you?"', '"I\'m fine, thank you"', '"Fine?"'], answer: 1 },
      { problem: '要求指路怎么说？', options: ['"Where is the bathroom?"', '"Bathroom?"', '"Show me bathroom"'], answer: 0 },
      { problem: '礼貌的请求用什么？', options: ['"Give me"', '"Please give me"', '"Want"'], answer: 1 },
      { problem: '提供帮助怎么说？', options: ['"Help?"', '"Can I help you?"', '"Need help?"'], answer: 1 },
      { problem: '同意某人怎么说？', options: ['"No"', '"Yes, I agree"', '"Maybe"'], answer: 1 },
      { problem: '礼貌地不同意怎么说？', options: ['"You\'re wrong"', '"I think differently"', '"No way"'], answer: 1 },
      { problem: '问时间怎么说？', options: ['"Time?"', '"What time is it?"', '"Tell time"'], answer: 1 },
      { problem: '邀请某人怎么说？', options: ['"Come"', '"Would you like to join me?"', '"Join"'], answer: 1 },
      { problem: '祝贺某人怎么说？', options: ['"You did it!"', '"Congratulations!"', '"Well done" or "Congratulations"'], answer: 2 },
      { problem: '表示惊讶怎么说？', options: ['"Wow!" or "Really?"', '"Okay"', '"I know"'], answer: 0 },
      { problem: '与陌生人开始谈话？', options: ['"Hi, how are you?"', '"Introduce"', '"Hello, my name is..."'], answer: 0 },
      { problem: '礼貌地结束谈话说什么？', options: ['"Bye"', '"It was nice talking to you"', '"Goodbye" or "See you"'], answer: 1 },
    ]}
  },
  {
    title: '形容词 - 描述词',
    type: 'multiple_choice',
    emoji: '✨',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '"Beautiful"描述什么？', options: ['行动', '品质/外观', '人'], answer: 1 },
      { problem: '"Smart"是形容词用来？', options: ['智力', '运动', '声音'], answer: 0 },
      { problem: '形容词通常在？', options: ['名词后', '名词前', '任何地方'], answer: 1 },
      { problem: '"A big house" - 形容词在哪里？', options: ['在house后', '在house前', '在末尾'], answer: 1 },
      { problem: '"cold"的反义词是？', options: ['ice', 'hot', 'warm'], answer: 1 },
      { problem: '"big"的反义词是？', options: ['large', 'small', 'large'], answer: 1 },
      { problem: '"happy"的反义词是？', options: ['sad', 'angry', 'tired'], answer: 0 },
      { problem: '"tall"的比较级？', options: ['taller', 'tallest', 'more tall'], answer: 0 },
      { problem: '"fast"的最高级？', options: ['faster', 'fastest', 'more fast'], answer: 1 },
      { problem: '用"more"对于形容词？', options: ['所有', '短的', '长的'], answer: 2 },
      { problem: '"Beautiful"变成？', options: ['more beautiful', 'beautifuler', 'beautifullest'], answer: 0 },
      { problem: '形容词加"er"用于？', options: ['最高级', '比较级', '无'], answer: 1 },
      { problem: '形容词加"est"用于？', options: ['比较级', '最高级', '无'], answer: 1 },
      { problem: '"Good"的比较级是？', options: ['gooder', 'better', 'more good'], answer: 1 },
      { problem: '"Bad"的最高级是？', options: ['baddest', 'worse', 'worst'], answer: 2 },
      { problem: '形容词修饰？', options: ['动词', '名词', '形容词'], answer: 1 },
      { problem: '颜色词如"red"是？', options: ['动词', '形容词', '名词'], answer: 1 },
      { problem: '数词如"five"是？', options: ['形容词', '名词', '动词'], answer: 0 },
      { problem: '形容词能独立存在吗？', options: ['是', '不是', '有时候'], answer: 2 },
      { problem: '"The tall, dark stranger" - 有多少形容词？', options: ['1', '2', '3'], answer: 2 },
    ]}
  },
  {
    title: '前置词 - 位置和时间',
    type: 'multiple_choice',
    emoji: '📍',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'The book is ___ the table（前置词）？', options: ['in', 'on', 'at'], answer: 1 },
      { problem: 'The pen is ___ the bag（前置词）？', options: ['on', 'in', 'at'], answer: 1 },
      { problem: 'I am ___ school（前置词）？', options: ['in', 'on', 'at'], answer: 2 },
      { problem: 'Meet me ___ 3 o\'clock（前置词）？', options: ['in', 'on', 'at'], answer: 2 },
      { problem: 'The picture is ___ the wall（前置词）？', options: ['in', 'on', 'at'], answer: 1 },
      { problem: 'I live ___ Malaysia（前置词）？', options: ['in', 'on', 'at'], answer: 0 },
      { problem: 'The cat is ___ the chair（前置词）？', options: ['under', 'on', 'in'], answer: 0 },
      { problem: 'The ball is ___ the box（前置词）？', options: ['under', 'in', 'on'], answer: 1 },
      { problem: 'The lamp is ___ the desk（前置词）？', options: ['on', 'under', 'in'], answer: 0 },
      { problem: 'The garden is ___ the house（前置词）？', options: ['in', 'behind', 'above'], answer: 1 },
      { problem: 'I go ___ my friend\'s house（前置词）？', options: ['in', 'to', 'at'], answer: 1 },
      { problem: 'We come ___ school ___ 7 am（前置词）？', options: ['to, in', 'at, on', 'to, at'], answer: 2 },
      { problem: 'The fly is ___ my head（前置词）？', options: ['above', 'on', 'in'], answer: 0 },
      { problem: 'I work ___ a hospital（前置词）？', options: ['in', 'on', 'at'], answer: 0 },
      { problem: 'The child sits ___ his mother（前置词）？', options: ['near', 'beside', 'next to'], answer: 1 },
      { problem: 'We meet ___ 5pm（前置词）？', options: ['in', 'on', 'at'], answer: 2 },
      { problem: 'The stars are ___ the sky（前置词）？', options: ['in', 'above', 'below'], answer: 0 },
      { problem: 'I go to bed ___ night（前置词）？', options: ['in', 'on', 'at'], answer: 0 },
      { problem: 'Classes start ___ Monday（前置词）？', options: ['in', 'on', 'at'], answer: 1 },
      { problem: '前置词显示什么关系？', options: ['词', '名词/代词和其他词', '动词'], answer: 1 },
    ]}
  },
  {
    title: '代词 - 主宾格',
    type: 'multiple_choice',
    emoji: '👤',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '主格代词"he"指的是？', options: ['女性', '男性', '物体'], answer: 1 },
      { problem: '主格代词"she"指的是？', options: ['男性', '女性', '东西'], answer: 1 },
      { problem: '"John"的宾格代词是？', options: ['he', 'him', 'his'], answer: 1 },
      { problem: '"Mary"的宾格代词是？', options: ['she', 'her', 'hers'], answer: 1 },
      { problem: '"I"是什么类型？', options: ['宾格', '主格', '所有格'], answer: 1 },
      { problem: '"Me"是什么类型？', options: ['主格', '宾格', '所有格'], answer: 1 },
      { problem: '正确："Him and I go" 还是 "He and I go"？', options: ['Him and I', 'He and I', '都对'], answer: 1 },
      { problem: '正确："She gave it to me" - 哪个代词？', options: ['主格', '宾格', '都对'], answer: 1 },
      { problem: '"We"是复数形式？', options: ['I', 'you', 'he'], answer: 0 },
      { problem: '"They"指的是？', options: ['一个东西', '一个人', '一个以上'], answer: 2 },
      { problem: '所有格代词"his"？', options: ['是宾格', '表示所有权', '是主格'], answer: 1 },
      { problem: '所有格代词"her"？', options: ['是主格', '表示所有权', '是宾格'], answer: 1 },
      { problem: '"My"是？', options: ['宾格代词', '主格代词', '所有格代词'], answer: 2 },
      { problem: '自反代词"himself"？', options: ['指代他人', '指代主语', '宾格'], answer: 1 },
      { problem: '"Herself"是？', options: ['宾格', '自反代词', '主格'], answer: 1 },
      { problem: '"This" 和 "that"是？', options: ['代词', '指示词', '形容词'], answer: 1 },
      { problem: '"Who"用于？', options: ['物体', '人们', '东西'], answer: 1 },
      { problem: '"Whom"用于？', options: ['主语', '宾语人称', '东西'], answer: 1 },
      { problem: '相对代词"which"用于？', options: ['人', '东西', '动词'], answer: 1 },
      { problem: '相对代词"who"用于？', options: ['东西', '人', '地点'], answer: 1 },
    ]}
  },
  {
    title: '动词 - 行动词',
    type: 'multiple_choice',
    emoji: '⚡',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '"Run"意思是？', options: ['缓慢', '用腿快速移动', '行走'], answer: 1 },
      { problem: '"Sleep"意思是？', options: ['吃', '休息夜晚', '工作'], answer: 1 },
      { problem: '"Eat"意思是？', options: ['喝', '睡觉', '消费食物'], answer: 2 },
      { problem: '"Write"意思是？', options: ['读', '在纸上写字', '说话'], answer: 1 },
      { problem: '"Listen"意思是？', options: ['听声音', '说话', '看'], answer: 0 },
      { problem: '"Watch"意思是？', options: ['听', '看', '触摸'], answer: 1 },
      { problem: '"Play"意思是？', options: ['工作', '享受活动的乐趣', '睡觉'], answer: 1 },
      { problem: '"Study"意思是？', options: ['教', '通过阅读学习', '想'], answer: 1 },
      { problem: '"Help"意思是？', options: ['伤害', '协助', '忽视'], answer: 1 },
      { problem: '"Break"意思是？', options: ['修复', '损坏', '制造'], answer: 1 },
      { problem: '"Cook"意思是？', options: ['吃', '用热准备食物', '服务'], answer: 1 },
      { problem: '"Jump"意思是？', options: ['跑', '在空中跳跃', '摔'], answer: 1 },
      { problem: '"Swim"意思是？', options: ['走路', '穿过水移动', '漂浮'], answer: 1 },
      { problem: '"Climb"意思是？', options: ['摔', '往上走', '向下'], answer: 1 },
      { problem: '"Teach"意思是？', options: ['学', '传递知识', '学习'], answer: 1 },
      { problem: '"Sing"意思是？', options: ['说话', '用嗓音发出音乐', '窃窃私语'], answer: 1 },
      { problem: '"Dance"意思是？', options: ['走路', '有节奏地移动', '站立'], answer: 1 },
      { problem: '规则动词加什么？', options: ['-ing', '-ed', '-s'], answer: 1 },
      { problem: '"go"的不规则动词形式？', options: ['goed', 'gooed', 'went'], answer: 2 },
      { problem: '"eat"的不规则动词形式？', options: ['eated', 'ate', 'eating'], answer: 1 },
    ]}
  },
  {
    title: '问题 - 提问和回答',
    type: 'multiple_choice',
    emoji: '❓',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '要问"what"，问题词是？', options: ['which', 'what', 'why'], answer: 1 },
      { problem: '要问"reason"，问题词是？', options: ['why', 'where', 'when'], answer: 0 },
      { problem: '要问"place"，问题词是？', options: ['when', 'where', 'who'], answer: 1 },
      { problem: '要问"person"，问题词是？', options: ['what', 'where', 'who'], answer: 2 },
      { problem: '要问"time"，问题词是？', options: ['why', 'when', 'how'], answer: 1 },
      { problem: '问题"Do you like..."是？', options: ['是-否问题', '信息问题', '命令'], answer: 0 },
      { problem: '"What color..."是？', options: ['是-否', '信息问题', '感叹'], answer: 1 },
      { problem: '问题使用什么？', options: ['陈述句', '问号', '句号'], answer: 1 },
      { problem: '在问题中，动词来？', options: ['在主语前', '在主语后', '无处'], answer: 0 },
      { problem: '"Does she like coffee?" - 回答？', options: ['"Yes, she does"', '"She does"', '是/否回答'], answer: 0 },
      { problem: '"Where do you live?" - 回答类型？', options: ['是/否', '信息', '命令'], answer: 1 },
      { problem: '"How are you?" - 回答？', options: ['"Yes"', '"I am fine"', '"No"'], answer: 1 },
      { problem: '标签问题如"isn\'t it?"是？', options: ['陈述句', '是/否问题', '命令'], answer: 1 },
      { problem: '要形成是/否问题，使用？', options: ['-ing', 'do/does/did', '无'], answer: 1 },
      { problem: '"Will you help me?" - 是这个问题吗？', options: ['不是', '是', '也许'], answer: 1 },
      { problem: '礼貌问题使用？', options: ['"Can you"', '"You can"', '"Can I"'], answer: 0 },
      { problem: '"How many"问什么？', options: ['品质', '数量', '原因'], answer: 1 },
      { problem: '"How much"问什么？', options: ['数字', '金额/价格', '大小'], answer: 1 },
      { problem: '问题"Could you help?"显示？', options: ['命令', '礼貌请求', '陈述'], answer: 1 },
      { problem: '"What time is it?"的回答是？', options: ['"It\'s 3 pm"', '"Yes, it is"', '"No"'], answer: 0 },
    ]}
  },
  {
    title: '模态动词 - Can, Could, Should, Must',
    type: 'multiple_choice',
    emoji: '🔒',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '"Can"意思是？', options: ['必须', '有能力', '应该'], answer: 1 },
      { problem: '"Must"意思是？', options: ['也许', '必要的', '可能的'], answer: 1 },
      { problem: '"Should"意思是？', options: ['必须', '推荐/建议', '可以'], answer: 1 },
      { problem: '"Could"是？', options: ['can的现在式', 'can的过去式', '必须'], answer: 1 },
      { problem: '"I can swim"意思是？', options: ['我必须', '我能够', '我应该'], answer: 1 },
      { problem: '"You must study"意思是？', options: ['可选', '这是必要的', '也许'], answer: 1 },
      { problem: '"Should I go?"意思是？', options: ['我必须', '这被建议', '我能'], answer: 1 },
      { problem: '"May I ask?"使用模态？', options: ['可以', '可能', '可能'], answer: 1 },
      { problem: '"Might"显示？', options: ['能力', '可能性', '必要性'], answer: 1 },
      { problem: '"Would you help?"是？', options: ['能力', '礼貌请求', '必要性'], answer: 1 },
      { problem: '模态动词+什么？', options: ['-ed', '基础动词', '-ing'], answer: 1 },
      { problem: '"He can speak English" - 正确吗？', options: ['不是', '是', '也许'], answer: 1 },
      { problem: '"She must goes" - 正确吗？', options: ['是', '否', '都对'], answer: 1 },
      { problem: '正确："You should study"？', options: ['否', '是', '不清楚'], answer: 1 },
      { problem: '"Can\'t"意思是？', options: ['不应该', '不能够', '可能'], answer: 1 },
      { problem: '"Shouldn\'t"意思是？', options: ['必须', '不推荐', '可以'], answer: 1 },
      { problem: '"Mustn\'t"意思是？', options: ['不必要', '你不能', '也许'], answer: 1 },
      { problem: '"Don\'t have to" vs "Must not"？', options: ['相同', '不同的意思', '不清楚'], answer: 1 },
      { problem: '"I may leave"显示？', options: ['许可', '可能性', '都对'], answer: 2 },
      { problem: '"Could you pass salt?"是？', options: ['过去能力', '礼貌请求', '命令'], answer: 1 },
    ]}
  },
  {
    title: '写作 - 段落结构',
    type: 'multiple_choice',
    emoji: '✍️',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '好段落有？', options: ['无结构', '主题句和支持细节', '随机想法'], answer: 1 },
      { problem: '主题句通常在？', options: ['末尾', '开头', '中间'], answer: 1 },
      { problem: '主题句告诉？', options: ['随机信息', '主要想法', '结论'], answer: 1 },
      { problem: '支持句提供？', options: ['标题', '细节/例子', '结尾'], answer: 1 },
      { problem: '结论句？', options: ['开始段落', '结束和总结', '在中间'], answer: 1 },
      { problem: '段落统一性意味着？', options: ['不同话题', '都关于一个想法', '无连接'], answer: 1 },
      { problem: '好段落长度？', options: ['1个句子', '通常3-8个句子', '整页'], answer: 1 },
      { problem: '写作中的连贯性意味着？', options: ['句子不连接', '逻辑流畅', '随机顺序'], answer: 1 },
      { problem: '过渡词如"because"？', options: ['混淆', '连接想法', '分离'], answer: 1 },
      { problem: '"Furthermore"和"However"例子是？', options: ['主语', '过渡词', '动词'], answer: 1 },
      { problem: '好写作使用？', options: ['所有简单句', '各种句子', '所有长句'], answer: 1 },
      { problem: '支持细节例子是？', options: ['主要想法', '证明/具体事实', '结论'], answer: 1 },
      { problem: '段落开始的缩进？', options: ['不需要', '显示新段落', '错误'], answer: 1 },
      { problem: '每个段落是关于？', options: ['同一话题', '不同主要想法', '没有'], answer: 1 },
      { problem: '文章最少需要几个段落？', options: ['1', '3-5', '10'], answer: 1 },
      { problem: '引言段落显示？', options: ['结论', '主要话题', '结尾'], answer: 1 },
      { problem: '正文段落包含？', options: ['结尾', '支持细节', '标题'], answer: 1 },
      { problem: '结论段落做什么？', options: ['开始文章', '总结主要观点', '添加新想法'], answer: 1 },
      { problem: '段落标题放在？', options: ['中间', '顶部', '底部'], answer: 1 },
    ]}
  },
];