// Prasekolah - English - Expansion (10 games)
export const prasekolah_english_expansion = [
  { title: 'Alphabet Song - A to Z', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Apple', options: ['A','B','C','D'], answer: 0 },
    { letter: 'B', emoji: '🚲', word: 'Bicycle', options: ['A','B','C','D'], answer: 1 },
    { letter: 'C', emoji: '🐱', word: 'Cat', options: ['A','B','C','D'], answer: 2 },
    { letter: 'D', emoji: '🐕', word: 'Dog', options: ['A','B','C','D'], answer: 3 },
    { letter: 'E', emoji: '🦅', word: 'Eagle', options: ['D','E','F','G'], answer: 1 },
    { letter: 'F', emoji: '🐟', word: 'Fish', options: ['D','E','F','G'], answer: 2 },
    { letter: 'G', emoji: '🍇', word: 'Grape', options: ['E','F','G','H'], answer: 2 },
    { letter: 'H', emoji: '🏠', word: 'House', options: ['F','G','H','I'], answer: 2 },
  ]}},
  { title: 'Greetings and Polite Words', type: 'multiple_choice', emoji: '👋', difficulty: 'easy', gameData: { questions: [
    { problem: 'How to say goodbye?', options: ['Hello','Goodbye','Thank you'], answer: 1 },
    { problem: 'How to greet morning?', options: ['Good evening','Good morning','Good night'], answer: 1 },
    { problem: 'How to say thank you?', options: ['Sorry','Please','Thank you'], answer: 2 },
    { problem: 'How to ask politely?', options: ['Please','Sorry','Hello'], answer: 0 },
    { problem: 'How to apologize?', options: ['Thank you','Please','Sorry'], answer: 2 },
    { problem: 'How to start conversation?', options: ['Goodbye','Hello','Thank you'], answer: 1 },
    { problem: 'Good night means?', options: ['Morning','Evening','Bedtime'], answer: 2 },
    { problem: 'See you later means?', options: ['Right now','Soon','Tomorrow'], answer: 1 },
  ]}},
  { title: 'Body Parts - Head to Toe', type: 'picture_quiz', emoji: '👤', difficulty: 'easy', gameData: { questions: [
    { image: '👁️', options: ['Ear','Eye','Nose'], answer: 1 },
    { image: '👃', options: ['Eye','Nose','Mouth'], answer: 1 },
    { image: '👂', options: ['Eye','Ear','Nose'], answer: 1 },
    { image: '👄', options: ['Mouth','Lip','Tongue'], answer: 0 },
    { image: '✋', options: ['Foot','Hand','Arm'], answer: 1 },
    { image: '🦶', options: ['Arm','Hand','Foot'], answer: 2 },
    { image: '💇', options: ['Hair','Head','Face'], answer: 0 },
    { image: '❤️', options: ['Brain','Heart','Lung'], answer: 1 },
  ]}},
  { title: 'Colors & Shapes', type: 'picture_quiz', emoji: '🎨', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Red','Blue','Green'], answer: 0 },
    { image: '🔵', options: ['Red','Blue','Yellow'], answer: 1 },
    { image: '🟢', options: ['Yellow','Green','Orange'], answer: 1 },
    { image: '⭕', options: ['Circle','Square','Triangle'], answer: 0 },
    { image: '⬜', options: ['Circle','Square','Triangle'], answer: 1 },
    { image: '△', options: ['Circle','Square','Triangle'], answer: 2 },
    { image: '🟡', options: ['Yellow','Orange','Pink'], answer: 0 },
    { image: '🟠', options: ['Yellow','Orange','Red'], answer: 1 },
  ]}},
  { title: 'Simple Sentences - Present Tense', type: 'multiple_choice', emoji: '📝', difficulty: 'easy', gameData: { questions: [
    { problem: '"I am happy" — correct?', options: ['Wrong','Correct','Maybe'], answer: 1 },
    { problem: '"He are tall" — correct?', options: ['Wrong','Correct','Maybe'], answer: 0 },
    { problem: '"She is a girl" — correct?', options: ['Wrong','Correct','Maybe'], answer: 1 },
    { problem: '"They is happy" — correct?', options: ['Wrong','Correct','Maybe'], answer: 0 },
    { problem: '"You are smart" — correct?', options: ['Wrong','Correct','Maybe'], answer: 1 },
    { problem: '"It are big" — correct?', options: ['Wrong','Correct','Maybe'], answer: 0 },
    { problem: '"We is friends" — correct?', options: ['Wrong','Correct','Maybe'], answer: 0 },
    { problem: '"The cat are cute" — correct?', options: ['Wrong','Correct','Maybe'], answer: 0 },
  ]}},
  { title: 'Questions and Answers', type: 'multiple_choice', emoji: '❓', difficulty: 'easy', gameData: { questions: [
    { problem: '"What is your name?" — What to answer?', options: ['Yes','My name is...','OK'], answer: 1 },
    { problem: '"How are you?" — Good answer?', options: ['Goodbye','I am fine','I am sorry'], answer: 1 },
    { problem: '"Do you like cats?" — Should answer?', options: ['Yes/No','My name','Thank you'], answer: 0 },
    { problem: '"Where is the school?" — Should answer?', options: ['It is big','It is there','Thank you'], answer: 1 },
    { problem: '"How old are you?" — Should answer?', options: ['I am happy','I am 5 years old','I am fine'], answer: 1 },
    { problem: '"Can you help me?" — Yes answer?', options: ['No problem','Sure/Yes','Goodbye'], answer: 1 },
    { problem: '"What color is this?" — Should answer?', options: ['It is big','It is red','It is nice'], answer: 1 },
    { problem: '"Who is your friend?" — Answer?', options: ['His name is Ali','I am happy','It is big'], answer: 0 },
  ]}},
  { title: 'Numbers 1-10 English', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '1 in English?', options: ['One','Two','Three'], answer: 0 },
    { problem: '2 in English?', options: ['One','Two','Three'], answer: 1 },
    { problem: '3 in English?', options: ['Two','Three','Four'], answer: 1 },
    { problem: '5 in English?', options: ['Four','Five','Six'], answer: 1 },
    { problem: '7 in English?', options: ['Six','Seven','Eight'], answer: 1 },
    { problem: '10 in English?', options: ['Nine','Ten','Eleven'], answer: 1 },
    { problem: '4 in English?', options: ['Three','Four','Five'], answer: 1 },
    { problem: '6 in English?', options: ['Five','Six','Seven'], answer: 1 },
  ]}},
  { title: 'Family Members', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['Mother','Father','Sister'], answer: 1 },
    { image: '👩', options: ['Father','Mother','Brother'], answer: 1 },
    { image: '👦', options: ['Brother','Sister','Father'], answer: 0 },
    { image: '👧', options: ['Brother','Sister','Father'], answer: 1 },
    { image: '👴', options: ['Father','Grandfather','Grandmother'], answer: 1 },
    { image: '👵', options: ['Mother','Grandfather','Grandmother'], answer: 2 },
    { image: '👶', options: ['Baby','Boy','Girl'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['Family','Friends','Group'], answer: 0 },
  ]}},
  { title: 'Daily Activities - Action Verbs', type: 'picture_quiz', emoji: '⚡', difficulty: 'easy', gameData: { questions: [
    { image: '🏃', options: ['Jump','Run','Walk'], answer: 1 },
    { image: '🤸', options: ['Run','Jump','Sit'], answer: 1 },
    { image: '😴', options: ['Sleep','Wake','Rest'], answer: 0 },
    { image: '🍴', options: ['Drink','Cook','Eat'], answer: 2 },
    { image: '🚶', options: ['Run','Walk','Jump'], answer: 1 },
    { image: '🙋', options: ['Sit','Stand','Raise hand'], answer: 2 },
    { image: '📚', options: ['Play','Read','Sit'], answer: 1 },
    { image: '✍️', options: ['Draw','Write','Read'], answer: 1 },
  ]}},
  { title: 'Opposites - Antonyms', type: 'multiple_choice', emoji: '↔️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Opposite of "big"?', options: ['Small','Tall','Wide'], answer: 0 },
    { problem: 'Opposite of "hot"?', options: ['Warm','Cold','Cool'], answer: 1 },
    { problem: 'Opposite of "happy"?', options: ['Sad','Angry','Tired'], answer: 0 },
    { problem: 'Opposite of "fast"?', options: ['Slow','Quick','Speed'], answer: 0 },
    { problem: 'Opposite of "tall"?', options: ['Short','Long','Wide'], answer: 0 },
    { problem: 'Opposite of "clean"?', options: ['Dirty','Wet','Dry'], answer: 0 },
    { problem: 'Opposite of "night"?', options: ['Evening','Day','Morning'], answer: 1 },
    { problem: 'Opposite of "young"?', options: ['Old','New','Adult'], answer: 0 },
  ]}},
];