export const sekolah_science_expansion = [
  // ===== DARJAH 1 =====
  {
    title: 'Deria Lima - Lanjutan D1',
    type: 'multiple_choice',
    emoji: '👁️',
    difficulty: 'easy',
    darjah: 1,
    gameData: { questions: [
      { problem: 'Kita guna apa untuk melihat?', options: ['Hidung','Mata','Telinga'], answer: 1 },
      { problem: 'Kita guna apa untuk mendengar?', options: ['Mata','Telinga','Tangan'], answer: 1 },
      { problem: 'Kita guna apa untuk menghidu?', options: ['Hidung','Mata','Mulut'], answer: 0 },
      { problem: 'Kita guna apa untuk merasa?', options: ['Tangan','Kaki','Lidah'], answer: 2 },
      { problem: 'Kita guna apa untuk menyentuh?', options: ['Hidung','Tangan','Mata'], answer: 1 },
      { problem: 'Berapa deria yang ada pada manusia?', options: ['3','4','5'], answer: 2 },
      { problem: 'Bau bunga kita hidu dengan?', options: ['Mata','Hidung','Telinga'], answer: 1 },
      { problem: 'Muzik kita dengar dengan?', options: ['Mata','Tangan','Telinga'], answer: 2 },
      { problem: 'Rasa manis gula kita kesan dengan?', options: ['Hidung','Lidah','Mata'], answer: 1 },
      { problem: 'Rasa panas api kita kesan dengan?', options: ['Tangan/Kulit','Mata','Hidung'], answer: 0 },
      { problem: 'Gambar kita lihat dengan?', options: ['Telinga','Hidung','Mata'], answer: 2 },
      { problem: 'Suara ibu kita dengar dengan?', options: ['Mata','Hidung','Telinga'], answer: 2 },
      { problem: 'Kulit adalah organ deria apa?', options: ['Penglihatan','Pendengaran','Sentuhan'], answer: 2 },
      { problem: 'Deria yang membantu kita membaca?', options: ['Pendengaran','Penglihatan','Sentuhan'], answer: 1 },
      { problem: 'Deria yang membantu kita memasak?', options: ['Rasa dan Bau','Penglihatan sahaja','Sentuhan sahaja'], answer: 0 },
      { problem: 'Orang buta menggunakan deria apa lebih?', options: ['Penglihatan','Sentuhan dan Pendengaran','Rasa'], answer: 1 },
      { problem: 'Kacamata membantu deria?', options: ['Pendengaran','Penglihatan','Sentuhan'], answer: 1 },
      { problem: 'Alat bantu dengar membantu deria?', options: ['Penglihatan','Pendengaran','Rasa'], answer: 1 },
      { problem: 'Bau asap api kita hidu dengan?', options: ['Mata','Hidung','Telinga'], answer: 1 },
      { problem: 'Deria paling penting untuk keselamatan jalan?', options: ['Rasa','Bau','Penglihatan dan Pendengaran'], answer: 2 },
    ]}
  },
  {
    title: 'Haiwan dan Tumbuhan - Lanjutan D1',
    type: 'picture_quiz',
    emoji: '🌱',
    difficulty: 'easy',
    darjah: 1,
    gameData: { questions: [
      { image: '🌻', options: ['Haiwan','Tumbuhan','Batu'], answer: 1 },
      { image: '🐘', options: ['Haiwan','Tumbuhan','Batu'], answer: 0 },
      { image: '🍌', options: ['Dari haiwan','Dari tumbuhan','Dari batu'], answer: 1 },
      { image: '🥚', options: ['Dari haiwan','Dari tumbuhan','Dari batu'], answer: 0 },
      { image: '🌴', options: ['Haiwan','Tumbuhan','Mineral'], answer: 1 },
      { image: '🦁', options: ['Haiwan','Tumbuhan','Mineral'], answer: 0 },
      { image: '🌾', options: ['Haiwan','Tumbuhan','Batu'], answer: 1 },
      { image: '🐟', options: ['Haiwan','Tumbuhan','Air'], answer: 0 },
      { image: '🍎', options: ['Dari haiwan','Dari tumbuhan','Dari batu'], answer: 1 },
      { image: '🥛', options: ['Dari haiwan','Dari tumbuhan','Dari batu'], answer: 0 },
      { image: '🌵', options: ['Haiwan','Tumbuhan','Mineral'], answer: 1 },
      { image: '🐔', options: ['Haiwan','Tumbuhan','Batu'], answer: 0 },
      { image: '🌹', options: ['Haiwan','Tumbuhan','Mineral'], answer: 1 },
      { image: '🐋', options: ['Haiwan','Tumbuhan','Air'], answer: 0 },
      { image: '🍄', options: ['Haiwan','Tumbuhan/Kulat','Batu'], answer: 1 },
      { image: '🐝', options: ['Haiwan','Tumbuhan','Mineral'], answer: 0 },
      { image: '🌿', options: ['Haiwan','Tumbuhan','Batu'], answer: 1 },
      { image: '🦊', options: ['Haiwan','Tumbuhan','Mineral'], answer: 0 },
      { image: '🌊🌿', options: ['Tumbuhan darat','Tumbuhan air','Batu'], answer: 1 },
      { image: '🐛', options: ['Haiwan','Tumbuhan','Mineral'], answer: 0 },
    ]}
  },
  {
    title: 'Cuaca dan Alam Sekitar D1',
    type: 'multiple_choice',
    emoji: '☀️',
    difficulty: 'easy',
    darjah: 1,
    gameData: { questions: [
      { problem: 'Matahari memberi kita?', options: ['Hujan','Cahaya dan haba','Angin'], answer: 1 },
      { problem: 'Semasa hujan kita perlu?', options: ['Topi','Payung','Kasut'], answer: 1 },
      { problem: 'Pelangi muncul selepas?', options: ['Panas','Angin','Hujan'], answer: 2 },
      { problem: 'Cuaca panas - kita buat apa?', options: ['Pakai jaket','Minum air lebih','Tidur'], answer: 1 },
      { problem: 'Salji turun bila cuaca?', options: ['Panas','Sejuk sekali','Hujan'], answer: 1 },
      { problem: 'Ribut petir berlaku bila?', options: ['Cuaca cerah','Cuaca hujan lebat','Cuaca sejuk'], answer: 1 },
      { problem: 'Angin meniup karena?', options: ['Perbezaan suhu udara','Hujan','Matahari padam'], answer: 0 },
      { problem: 'Malaysia cuaca biasanya?', options: ['Sejuk bersalji','Panas dan hujan','Kering sahaja'], answer: 1 },
      { problem: 'Pokok melengkung bermakna ada?', options: ['Hujan','Angin kuat','Panas'], answer: 1 },
      { problem: 'Awan hitam tanda akan?', options: ['Cerah','Hujan','Sejuk sahaja'], answer: 1 },
      { problem: 'Pancaindera untuk rasa hawa sejuk?', options: ['Mata','Hidung','Kulit'], answer: 2 },
      { problem: 'Waktu pagi cuaca biasanya?', options: ['Sangat panas','Lebih sejuk','Ribut'], answer: 1 },
      { problem: 'Kilat berlaku semasa?', options: ['Panas terik','Ribut petir','Angin sepoi'], answer: 1 },
      { problem: 'Pakaian yang sesuai cuaca panas?', options: ['Tebal dan gelap','Nipis dan cerah','Jaket tebal'], answer: 1 },
      { problem: 'Banjir berlaku bila?', options: ['Terlalu panas','Hujan sangat lebat','Angin kencang'], answer: 1 },
      { problem: 'Waktu yang paling panas?', options: ['Pagi','Tengah hari','Malam'], answer: 1 },
      { problem: 'Embun pada daun berlaku pada waktu?', options: ['Tengah hari','Pagi awal','Malam lewat'], answer: 1 },
      { problem: 'Cuaca boleh berubah dalam?', options: ['Hanya setahun','Satu hari','Tidak pernah'], answer: 1 },
      { problem: 'Alat untuk ukur suhu?', options: ['Pembaris','Termometer','Jam'], answer: 1 },
      { problem: 'Musim hujan di Malaysia biasanya bila?', options: ['Januari-Mac','Oktober-Mac','Jun-Ogos'], answer: 1 },
    ]}
  },

  // ===== DARJAH 2 =====
  {
    title: 'Bahan dan Sifatnya D2',
    type: 'multiple_choice',
    emoji: '🧱',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'Besi adalah bahan yang?', options: ['Lembut','Keras dan berat','Ringan'], answer: 1 },
      { problem: 'Kayu boleh?', options: ['Terapung di air','Tenggelam','Cair'], answer: 0 },
      { problem: 'Getah sifatnya?', options: ['Keras','Kenyal/Elastik','Pecah'], answer: 1 },
      { problem: 'Kaca sifatnya?', options: ['Legap','Lutsinar','Kenyal'], answer: 1 },
      { problem: 'Plastik boleh dibentuk bila?', options: ['Dibekukan','Dipanaskan','Dibasahkan'], answer: 1 },
      { problem: 'Batu adalah bahan yang?', options: ['Lembut','Keras','Kenyal'], answer: 1 },
      { problem: 'Kapas sifatnya?', options: ['Keras','Lembut dan ringan','Berat'], answer: 1 },
      { problem: 'Bahan manakah yang boleh berkarat?', options: ['Plastik','Besi','Kayu'], answer: 1 },
      { problem: 'Bahan yang terbaik buat jambatan?', options: ['Kertas','Kayu tipis','Besi/Konkrit'], answer: 2 },
      { problem: 'Bahan yang tidak boleh dibakar?', options: ['Kayu','Kertas','Besi'], answer: 2 },
      { problem: 'Dawai elektrik dibuat dari?', options: ['Plastik sahaja','Kuprum/Logam','Kayu'], answer: 1 },
      { problem: 'Baju dibuat dari?', options: ['Besi','Kain/Tekstil','Kayu'], answer: 1 },
      { problem: 'Bahan paling baik simpan makanan sejuk?', options: ['Kertas','Plastik/Aluminium foil','Kain'], answer: 1 },
      { problem: 'Tayar kereta dibuat dari?', options: ['Plastik keras','Getah','Besi'], answer: 1 },
      { problem: 'Cermin diperbuat dari?', options: ['Besi','Kaca','Plastik'], answer: 1 },
      { problem: 'Bahan yang tidak terapung?', options: ['Kayu','Batu besar','Plastik'], answer: 1 },
      { problem: 'Bahan yang baik untuk payung?', options: ['Kertas','Kain kalis air','Kayu'], answer: 1 },
      { problem: 'Belon diperbuat dari?', options: ['Besi','Getah nipis','Kaca'], answer: 1 },
      { problem: 'Bahan yang baik penghantar elektrik?', options: ['Kayu','Plastik','Logam'], answer: 2 },
      { problem: 'Sifat magnet - menarik bahan?', options: ['Kayu','Plastik','Besi'], answer: 2 },
    ]}
  },
  {
    title: 'Air dan Alam Sekitar D2',
    type: 'multiple_choice',
    emoji: '💧',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'Air terdapat dalam berapa keadaan?', options: ['1','2','3'], answer: 2 },
      { problem: 'Air cair disebut?', options: ['Ais','Air biasa/cecair','Wap'], answer: 1 },
      { problem: 'Air beku disebut?', options: ['Ais','Wap','Embun'], answer: 0 },
      { problem: 'Air dipanaskan jadi?', options: ['Ais','Wap air','Salji'], answer: 1 },
      { problem: 'Air didinginkan jadi?', options: ['Wap','Ais','Gas'], answer: 1 },
      { problem: 'Proses air cair jadi wap dipanggil?', options: ['Pembekuan','Penyejatan','Kondensasi'], answer: 1 },
      { problem: 'Proses wap air jadi titisan air dipanggil?', options: ['Penyejatan','Kondensasi','Pembekuan'], answer: 1 },
      { problem: 'Kitaran air bermula dari?', options: ['Awan','Laut/tasik','Sungai'], answer: 1 },
      { problem: 'Hujan terbentuk dari?', options: ['Awan yang berat dengan titisan air','Angin','Matahari'], answer: 0 },
      { problem: 'Air hujan mengalir ke?', options: ['Awan','Sungai dan laut','Tanah sahaja'], answer: 1 },
      { problem: 'Tumbuhan perlukan air untuk?', options: ['Tidur','Fotosintesis/membesar','Bernafas sahaja'], answer: 1 },
      { problem: 'Manusia perlu minum air berapa banyak sehari?', options: ['Sedikit','Banyak (8 gelas)','Tidak perlu'], answer: 1 },
      { problem: 'Pencemaran air boleh menyebabkan?', options: ['Sihat','Penyakit','Cuaca baik'], answer: 1 },
      { problem: 'Cara jimat air di rumah?', options: ['Buka paip lama','Tutup paip bila tidak guna','Mandi lama'], answer: 1 },
      { problem: 'Air bersih perlu?', options: ['Kotor','Disaring dan dirawat','Berbau'], answer: 1 },
      { problem: 'Sumber air bersih?', options: ['Air sungai kotor','Air paip yang dirawat','Air longkang'], answer: 1 },
      { problem: 'Mengapa air laut tidak boleh diminum?', options: ['Terlalu sejuk','Masin - ada garam','Terlalu bersih'], answer: 1 },
      { problem: 'Banjir berlaku bila air?', options: ['Terlalu sedikit','Terlalu banyak','Beku'], answer: 1 },
      { problem: 'Embun pada daun pagi hari adalah?', options: ['Hujan kecil','Kondensasi wap air','Salji'], answer: 1 },
      { problem: 'Air berperanan dalam kehidupan - penting atau tidak?', options: ['Tidak penting','Sangat penting','Biasa sahaja'], answer: 1 },
    ]}
  },

  // ===== DARJAH 3 =====
  {
    title: 'Haiwan - Pengkelasan dan Ciri D3',
    type: 'multiple_choice',
    emoji: '🦁',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: 'Mamalia dicirikan oleh?', options: ['Bersisik','Bertelur sahaja','Menyusukan anak'], answer: 2 },
      { problem: 'Ikan bernafas menggunakan?', options: ['Paru-paru','Insang','Kulit'], answer: 1 },
      { problem: 'Amfibia boleh hidup di?', options: ['Darat sahaja','Air sahaja','Darat dan air'], answer: 2 },
      { problem: 'Reptilia bersisik dan?', options: ['Berdarah panas','Berdarah sejuk','Berbulu'], answer: 1 },
      { problem: 'Burung mempunyai?', options: ['Sisik','Bulu pelepah','Rambut'], answer: 1 },
      { problem: 'Serangga mempunyai berapa kaki?', options: ['4','6','8'], answer: 1 },
      { problem: 'Labah-labah mempunyai berapa kaki?', options: ['6','8','10'], answer: 1 },
      { problem: 'Ular tergolong dalam?', options: ['Mamalia','Amfibia','Reptilia'], answer: 2 },
      { problem: 'Katak tergolong dalam?', options: ['Reptilia','Amfibia','Ikan'], answer: 1 },
      { problem: 'Paus tergolong dalam?', options: ['Ikan','Mamalia laut','Reptilia'], answer: 1 },
      { problem: 'Kelawar tergolong dalam?', options: ['Burung','Mamalia','Serangga'], answer: 1 },
      { problem: 'Penyu tergolong dalam?', options: ['Amfibia','Mamalia','Reptilia'], answer: 2 },
      { problem: 'Karnivor memakan?', options: ['Tumbuhan','Daging','Kedua-duanya'], answer: 1 },
      { problem: 'Herbivor memakan?', options: ['Tumbuhan','Daging','Serangga'], answer: 0 },
      { problem: 'Omnivor memakan?', options: ['Tumbuhan sahaja','Daging sahaja','Tumbuhan dan daging'], answer: 2 },
      { problem: 'Harimau adalah?', options: ['Herbivor','Karnivor','Omnivor'], answer: 1 },
      { problem: 'Lembu adalah?', options: ['Herbivor','Karnivor','Omnivor'], answer: 0 },
      { problem: 'Manusia adalah?', options: ['Herbivor','Karnivor','Omnivor'], answer: 2 },
      { problem: 'Haiwan yang bertelur dan bersisik?', options: ['Arnab','Buaya','Katak'], answer: 1 },
      { problem: 'Ciri utama mamalia selain menyusu?', options: ['Bersisik','Berambut/berbulu','Bersayap'], answer: 1 },
    ]}
  },
  {
    title: 'Jirim dan Keadaannya D3',
    type: 'multiple_choice',
    emoji: '🧪',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: 'Tiga keadaan jirim ialah?', options: ['Gas, air, api','Pepejal, cecair, gas','Keras, lembut, cair'], answer: 1 },
      { problem: 'Contoh pepejal?', options: ['Air','Batu','Oksigen'], answer: 1 },
      { problem: 'Contoh cecair?', options: ['Besi','Minyak','Nitrogen gas'], answer: 1 },
      { problem: 'Contoh gas?', options: ['Ais','Air','Karbon dioksida'], answer: 2 },
      { problem: 'Pepejal mempunyai bentuk yang?', options: ['Berubah-ubah','Tetap','Tiada bentuk'], answer: 1 },
      { problem: 'Cecair mengalir mengikut bentuk?', options: ['Sendiri','Bekas yang mengisinya','Tidak mengalir'], answer: 1 },
      { problem: 'Gas mengembang mengisi?', options: ['Sebahagian bekas','Seluruh bekas','Tidak boleh bergerak'], answer: 1 },
      { problem: 'Ais cair bila?', options: ['Dibekukan','Dipanaskan','Ditekan'], answer: 1 },
      { problem: 'Air mendidih menghasilkan?', options: ['Ais','Wap','Gas lain'], answer: 1 },
      { problem: 'Proses pepejal jadi cecair dipanggil?', options: ['Pembekuan','Peleburan','Penyejatan'], answer: 1 },
      { problem: 'Proses cecair jadi pepejal dipanggil?', options: ['Pembekuan','Peleburan','Penyejatan'], answer: 0 },
      { problem: 'Lilin cair bila?', options: ['Didinginkan','Dipanaskan','Dibasahkan'], answer: 1 },
      { problem: 'Contoh perubahan pepejal ke cecair?', options: ['Ais ke air','Air ke wap','Gas ke cecair'], answer: 0 },
      { problem: 'Contoh perubahan cecair ke gas?', options: ['Air beku','Air mendidih','Ais cair'], answer: 1 },
      { problem: 'Udara yang kita sedut adalah?', options: ['Cecair','Gas','Pepejal'], answer: 1 },
      { problem: 'Susu adalah?', options: ['Gas','Pepejal','Cecair'], answer: 2 },
      { problem: 'Besi panas boleh cair menjadi?', options: ['Gas','Cecair','Pepejal lain'], answer: 1 },
      { problem: 'Jirim boleh berubah keadaan dengan?', options: ['Warna','Perubahan suhu','Tekanan sahaja'], answer: 1 },
      { problem: 'Pepejal yang keras seperti?', options: ['Minyak','Granit/Batu','Oksigen'], answer: 1 },
      { problem: 'Jirim yang tidak nampak tetapi boleh dirasa?', options: ['Pepejal','Cecair','Gas'], answer: 2 },
    ]}
  },
  {
    title: 'Tumbuhan - Struktur dan Fungsi D3',
    type: 'multiple_choice',
    emoji: '🌿',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: 'Fungsi akar tumbuhan?', options: ['Membuat makanan','Serap air dan mineral dari tanah','Buat bunga'], answer: 1 },
      { problem: 'Fungsi batang?', options: ['Serap air','Sokong tumbuhan dan hantar air','Membuat biji'], answer: 1 },
      { problem: 'Fungsi daun?', options: ['Serap air','Membuat makanan (fotosintesis)','Sokong tumbuhan'], answer: 1 },
      { problem: 'Fungsi bunga?', options: ['Membuat makanan','Penyerbukan dan membuat biji','Serap air'], answer: 1 },
      { problem: 'Fungsi buah?', options: ['Membuat makanan','Melindungi dan sebarkan biji','Serap air'], answer: 1 },
      { problem: 'Fotosintesis memerlukan?', options: ['Hanya air','Cahaya, air, CO₂','Tanah sahaja'], answer: 1 },
      { problem: 'Hasil fotosintesis ialah?', options: ['Oksigen dan glukosa','Air dan CO₂','Nitrogen'], answer: 0 },
      { problem: 'Klorofil memberi warna apa pada daun?', options: ['Merah','Hijau','Kuning'], answer: 1 },
      { problem: 'Tumbuhan yang tidak ada klorofil?', options: ['Pokok mango','Kulat (fungi)','Padi'], answer: 1 },
      { problem: 'Akar serabut dimiliki oleh?', options: ['Pokok kayu besar','Tumbuhan rumpai/herba','Kaktus'], answer: 1 },
      { problem: 'Pokok yang simpan air di batang?', options: ['Padi','Kaktus','Pisang'], answer: 1 },
      { problem: 'Tumbuhan perlukan tanah untuk?', options: ['Bernafas','Sokongan dan nutrisi','Cahaya'], answer: 1 },
      { problem: 'Penyerbukan dibuat oleh?', options: ['Angin dan serangga','Hujan sahaja','Manusia sahaja'], answer: 0 },
      { problem: 'Biji benih bercambah memerlukan?', options: ['Cahaya terik','Air, udara dan suhu sesuai','Tanah hitam sahaja'], answer: 1 },
      { problem: 'Tumbuhan bernafas mengeluarkan?', options: ['Oksigen sahaja','CO₂ pada waktu malam','Nitrogen'], answer: 1 },
      { problem: 'Daun gugur pada tumbuhan bermakna?', options: ['Mati','Kitaran musim','Sakit'], answer: 1 },
      { problem: 'Pokok yang hidup lama dipanggil?', options: ['Herba','Pokok kayu/berkayu','Rumput'], answer: 1 },
      { problem: 'Manfaat tumbuhan kepada manusia?', options: ['Hanya hiasan','Makanan, ubat, oksigen','Bunyi sahaja'], answer: 1 },
      { problem: 'Tumbuhan yang boleh makan serangga?', options: ['Ros','Pokok Periuk Kera','Kaktus'], answer: 1 },
      { problem: 'Bahan hijau dalam daun dipanggil?', options: ['Amilase','Klorofil','Glukosa'], answer: 1 },
    ]}
  },

  // ===== DARJAH 4 =====
  {
    title: 'Sistem Tubuh Manusia - Lanjutan D4',
    type: 'multiple_choice',
    emoji: '🏃',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'Berapa tulang dalam badan manusia dewasa?', options: ['106','206','306'], answer: 1 },
      { problem: 'Tulang terbesar manusia?', options: ['Tulang rusuk','Tulang paha (femur)','Tulang lengan'], answer: 1 },
      { problem: 'Fungsi rangka tulang?', options: ['Buat makanan','Sokong dan lindungi organ','Bernafas'], answer: 1 },
      { problem: 'Otot berfungsi untuk?', options: ['Simpan makanan','Gerakkan anggota badan','Saring darah'], answer: 1 },
      { problem: 'Jantung memam darah ke seluruh badan melalui?', options: ['Saraf','Salur darah','Tulang'], answer: 1 },
      { problem: 'Fungsi sel darah merah?', options: ['Lawan jangkitan','Bawa oksigen','Bekukan darah'], answer: 1 },
      { problem: 'Fungsi sel darah putih?', options: ['Bawa oksigen','Lawan jangkitan/kuman','Bekukan darah'], answer: 1 },
      { problem: 'Paru-paru kanan manusia mempunyai berapa lobus?', options: ['2','3','4'], answer: 1 },
      { problem: 'Berapa kali jantung berdenyut seminit?', options: ['30-40','60-100','200-300'], answer: 1 },
      { problem: 'Otak manusia bahagi kepada berapa bahagian utama?', options: ['2','3','4'], answer: 1 },
      { problem: 'Sistem penghadaman bermula dari?', options: ['Perut','Mulut','Usus'], answer: 1 },
      { problem: 'Enzim dalam air liur memecah?', options: ['Lemak','Protein','Kanji/Karbohidrat'], answer: 2 },
      { problem: 'Ginjal berfungsi?', options: ['Pam darah','Saring sisa dari darah','Buat hormon'], answer: 1 },
      { problem: 'Hati (liver) menghasilkan?', options: ['Darah','Hempedu untuk hadam lemak','Oksigen'], answer: 1 },
      { problem: 'Saraf pusat terdiri dari?', options: ['Jantung dan paru-paru','Otak dan saraf tunjang','Otot dan tulang'], answer: 1 },
      { problem: 'Vitamin C penting untuk?', options: ['Tulang sahaja','Kulit dan imuniti','Mata sahaja'], answer: 1 },
      { problem: 'Kalsium penting untuk?', options: ['Mata','Tulang dan gigi','Jantung'], answer: 1 },
      { problem: 'Badan kekurangan air menyebabkan?', options: ['Lebih kuat','Dehidrasi','Lebih tenaga'], answer: 1 },
      { problem: 'Bersenam memberi manfaat kepada?', options: ['Hanya otot','Seluruh sistem badan','Hanya jantung'], answer: 1 },
      { problem: 'Berapa jam tidur yang cukup untuk kanak-kanak?', options: ['4-5 jam','8-10 jam','12-14 jam'], answer: 1 },
    ]}
  },
  {
    title: 'Tenaga - Pelbagai Bentuk D4',
    type: 'multiple_choice',
    emoji: '⚡',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'Tenaga cahaya dihasilkan oleh?', options: ['Angin','Lampu dan matahari','Air'], answer: 1 },
      { problem: 'Tenaga bunyi dihasilkan oleh?', options: ['Getaran','Cahaya','Haba'], answer: 0 },
      { problem: 'Tenaga haba dihasilkan oleh?', options: ['Cahaya sahaja','Api, matahari, geseran','Bunyi'], answer: 1 },
      { problem: 'Tenaga kinetik adalah tenaga?', options: ['Tersimpan','Pergerakan','Cahaya'], answer: 1 },
      { problem: 'Tenaga berpotensi adalah tenaga yang?', options: ['Bergerak','Tersimpan','Hilang'], answer: 1 },
      { problem: 'Batu di atas bukit mempunyai tenaga?', options: ['Kinetik','Berpotensi graviti','Bunyi'], answer: 1 },
      { problem: 'Batu bergolek ke bawah mempunyai tenaga?', options: ['Berpotensi','Kinetik','Haba'], answer: 1 },
      { problem: 'Sumber tenaga yang boleh dibaharui?', options: ['Arang','Minyak petroleum','Matahari'], answer: 2 },
      { problem: 'Sumber tenaga tidak boleh dibaharui?', options: ['Angin','Gas asli','Air'], answer: 1 },
      { problem: 'Cara jimat tenaga elektrik?', options: ['Biarkan semua lampu hidup','Padam bila tidak guna','Guna lebih alatan'], answer: 1 },
      { problem: 'Penjana elektrik menggunakan tenaga?', options: ['Cahaya','Mekanikal untuk hasilkan elektrik','Bunyi'], answer: 1 },
      { problem: 'Kereta elektrik menggunakan tenaga dari?', options: ['Petrol','Bateri elektrik','Gas'], answer: 1 },
      { problem: 'Bahan bakar fossil terbentuk dari?', options: ['Tumbuhan hidup','Sisa organisma purba','Batu biasa'], answer: 1 },
      { problem: 'Penggunaan tenaga fossil menyebabkan?', options: ['Udara bersih','Pencemaran udara','Lebih oksigen'], answer: 1 },
      { problem: 'Tenaga angin digunakan untuk penjana?', options: ['Gas','Elektrik melalui turbine','Air'], answer: 1 },
      { problem: 'Tenaga hidro menggunakan?', options: ['Angin','Aliran air','Matahari'], answer: 1 },
      { problem: 'Nuklear menghasilkan tenaga yang?', options: ['Sedikit','Sangat besar','Tidak berbahaya'], answer: 1 },
      { problem: 'Seluruh tenaga di bumi datang dari?', options: ['Bumi','Matahari','Bulan'], answer: 1 },
      { problem: 'Manusia mendapat tenaga dari?', options: ['Cahaya matahari terus','Makanan','Udara'], answer: 1 },
      { problem: 'Tenaga tidak boleh dicipta atau dimusnahkan, hanya?', options: ['Hilang','Bertukar bentuk','Bertambah'], answer: 1 },
    ]}
  },

  // ===== DARJAH 5 =====
  {
    title: 'Daya Fizik dan Mekanikal D5',
    type: 'multiple_choice',
    emoji: '⚙️',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: 'Daya diukur dalam unit?', options: ['Kilogram','Newton','Meter'], answer: 1 },
      { problem: 'Graviti menarik semua objek ke?', options: ['Atas','Bawah','Sisi'], answer: 1 },
      { problem: 'Tanpa graviti kita akan?', options: ['Jalan biasa','Terapung di udara','Jatuh lagi laju'], answer: 1 },
      { problem: 'Magnet menarik bahan yang mengandungi?', options: ['Plastik','Besi/Kobalt/Nikel','Kayu'], answer: 1 },
      { problem: 'Kutub utara (N) magnet dan kutub utara (N) lain akan?', options: ['Tarik menarik','Tolak menolak','Tiada kesan'], answer: 1 },
      { problem: 'Kutub utara (N) dan kutub selatan (S) magnet akan?', options: ['Tolak menolak','Tarik menarik','Tiada kesan'], answer: 1 },
      { problem: 'Geseran menghasilkan?', options: ['Sejuk','Haba','Cahaya'], answer: 1 },
      { problem: 'Roda membantu mengurangkan?', options: ['Haba','Geseran','Graviti'], answer: 1 },
      { problem: 'Tuas (lever) adalah mesin mudah yang?', options: ['Menghasilkan api','Mengurangkan usaha','Membuat bunyi'], answer: 1 },
      { problem: 'Contoh tuas dalam kehidupan?', options: ['Kaca pembesar','Gunting','Lampu'], answer: 1 },
      { problem: 'Satah condong membantu?', options: ['Angkat lebih berat','Angkat benda berat dengan usaha kurang','Jatuhkan benda'], answer: 1 },
      { problem: 'Takal (pulley) digunakan untuk?', options: ['Potong','Angkat beban berat','Korek'], answer: 1 },
      { problem: 'Daya apungan (buoyancy) membolehkan benda?', options: ['Tenggelam','Terapung','Terbakar'], answer: 1 },
      { problem: 'Benda terapung bila ketumpatannya?', options: ['Lebih dari air','Kurang dari air','Sama dengan air'], answer: 1 },
      { problem: 'Kapal besar terapung kerana?', options: ['Ringan','Bentuk menangkap udara','Dibuat emas'], answer: 1 },
      { problem: 'Pegas (spring) menyimpan tenaga?', options: ['Kinetik','Berpotensi elastik','Haba'], answer: 1 },
      { problem: 'Tekanan udara tinggi berada di?', options: ['Puncak gunung','Paras laut','Angkasa'], answer: 1 },
      { problem: 'Ombak laut digerakkan oleh?', options: ['Ikan','Angin dan bulan','Api'], answer: 1 },
      { problem: 'Paras air naik bila objek dimasukkan kerana?', options: ['Graviti','Sesaran air','Tekanan'], answer: 1 },
      { problem: 'Daya yang menyebabkan bola berhenti bergolek ialah?', options: ['Graviti','Geseran','Magnet'], answer: 1 },
    ]}
  },
  {
    title: 'Cahaya, Bunyi dan Gelombang D5',
    type: 'multiple_choice',
    emoji: '💡',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: 'Kelajuan cahaya ialah kira-kira?', options: ['300 km/s','300,000 km/s','3000 km/s'], answer: 1 },
      { problem: 'Cahaya boleh melewati bahan?', options: ['Legap sahaja','Lutsinar sahaja','Lutsinar dan lut sinar'], answer: 2 },
      { problem: 'Bayang-bayang terbentuk apabila cahaya?', options: ['Melangkau semua','Disekat oleh objek legap','Dipantulkan'], answer: 1 },
      { problem: 'Prisma memisahkan cahaya putih kepada?', options: ['2 warna','7 warna pelangi','1 warna'], answer: 1 },
      { problem: 'Warna pelangi bermula dari?', options: ['Biru','Merah','Hijau'], answer: 1 },
      { problem: 'Cermin cekung digunakan dalam?', options: ['Kaca cermin bilik mandi','Teleskop reflektor','Periskop'], answer: 1 },
      { problem: 'Cermin cembung digunakan dalam?', options: ['Kanta kamera','Spion kenderaan','Kanta mata'], answer: 1 },
      { problem: 'Bunyi adalah gelombang yang memerlukan?', options: ['Vakum','Medium (pepejal/cecair/gas)','Cahaya'], answer: 1 },
      { problem: 'Bunyi paling laju dalam?', options: ['Gas','Cecair','Pepejal'], answer: 2 },
      { problem: 'Bunyi tidak boleh bergerak dalam?', options: ['Udara','Air','Vakum/ruang hampa'], answer: 2 },
      { problem: 'Gema adalah bunyi yang?', options: ['Hilang','Dipantulkan semula','Diserap'], answer: 1 },
      { problem: 'Ultrasonik digunakan dalam?', options: ['Lampu','Ultrasound/sonar','Radio'], answer: 1 },
      { problem: 'Kelajuan bunyi di udara kira-kira?', options: ['3 m/s','340 m/s','3400 m/s'], answer: 1 },
      { problem: 'Kilat dan guruh sama masa tetapi kita lihat kilat dahulu kerana?', options: ['Kilat lebih dekat','Cahaya lebih laju dari bunyi','Guruh lambat'], answer: 1 },
      { problem: 'Frekuensi bunyi tinggi menghasilkan nada?', options: ['Rendah','Tinggi','Sama'], answer: 1 },
      { problem: 'Amplitud gelombang bunyi besar = bunyi?', options: ['Perlahan','Kuat/Kencang','Tinggi'], answer: 1 },
      { problem: 'Telinga manusia boleh dengar frekuensi?', options: ['20-20,000 Hz','1-100 Hz','100,000 Hz ke atas'], answer: 0 },
      { problem: 'Periskop menggunakan prinsip?', options: ['Pembiasan cahaya','Pantulan cahaya','Penyerapan cahaya'], answer: 1 },
      { problem: 'Kanta pembesar menggunakan prinsip?', options: ['Pantulan','Pembiasan (refraksi)','Penyerapan'], answer: 1 },
      { problem: 'Warna hitam menyerap haba lebih dari warna?', options: ['Gelap','Putih','Merah'], answer: 1 },
    ]}
  },
  {
    title: 'Rantai Makanan dan Ekosistem D5',
    type: 'multiple_choice',
    emoji: '🌿',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: 'Pengeluar dalam rantai makanan ialah?', options: ['Haiwan','Tumbuhan hijau','Kulat'], answer: 1 },
      { problem: 'Pengguna primer (pertama) memakan?', options: ['Pengguna lain','Tumbuhan','Pengurai'], answer: 1 },
      { problem: 'Pengguna tertiari memakan?', options: ['Tumbuhan','Pengguna sekunder','Pengurai'], answer: 1 },
      { problem: 'Pengurai memecah?', options: ['Bahan hidup','Bahan organik mati','Batu'], answer: 1 },
      { problem: 'Contoh pengurai?', options: ['Singa','Bakteria dan kulat','Rumpai'], answer: 1 },
      { problem: 'Jika semua tumbuhan musnah, haiwan akan?', options: ['Hidup sihat','Pupus kerana tiada makanan','Lebih banyak'], answer: 1 },
      { problem: 'Jika predator pupus, mangsa akan?', options: ['Pupus juga','Bertambah berlebihan','Tidak berubah'], answer: 1 },
      { problem: 'Tumbuhan → Ulat → Katak → Ular. Siapa pengguna ke-2?', options: ['Ulat','Katak','Ular'], answer: 1 },
      { problem: 'Piramid biomassa menunjukkan?', options: ['Jumlah spesies','Jisim organisma di tiap aras','Saiz haiwan'], answer: 1 },
      { problem: 'Ekosistem stabil apabila?', options: ['Satu spesies dominan','Ada kepelbagaian spesies','Tiada predator'], answer: 1 },
      { problem: 'Simbiosis mutualisme bermakna?', options: ['Satu untung, satu rugi','Kedua-dua untung','Kedua-dua rugi'], answer: 1 },
      { problem: 'Parasit ialah?', options: ['Simbiosis mutualisme','Satu untung, satu rugi/host','Kedua-dua pupus'], answer: 1 },
      { problem: 'Hutan hujan tropika mempunyai biodiversiti?', options: ['Rendah','Sangat tinggi','Tiada'], answer: 1 },
      { problem: 'Spesies invasif boleh?', options: ['Bantu ekosistem','Rosakkan ekosistem asal','Tidak beri kesan'], answer: 1 },
      { problem: 'Kepupusan spesies berlaku bila?', options: ['Populasi bertambah','Semua individu spesies mati','Spesies berpindah'], answer: 1 },
      { problem: 'Taman negara ditubuhkan untuk?', options: ['Pelancongan sahaja','Perlindungan ekosistem','Pertanian'], answer: 1 },
      { problem: 'Pencemaran laut membahayakan?', options: ['Hanya ikan','Seluruh ekosistem laut','Tumbuhan darat'], answer: 1 },
      { problem: 'Hujan asid disebabkan oleh?', options: ['Air bersih','Gas SO₂ dan NOₓ dari industri','Angin'], answer: 1 },
      { problem: 'Punca utama kepupusan spesies masa kini?', options: ['Bencana alam','Aktiviti manusia','Usia tua'], answer: 1 },
      { problem: 'Cara terbaik pemuliharaan alam?', options: ['Bina lebih kilang','Kurangkan pembaziran, kitar semula','Tebang hutan'], answer: 1 },
    ]}
  },

  // ===== DARJAH 6 =====
  {
    title: 'Alam Sekitar dan Pemuliharaan - Lanjutan D6',
    type: 'multiple_choice',
    emoji: '🌍',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Gas utama penyebab kesan rumah hijau?', options: ['Oksigen','Karbon dioksida (CO₂)','Nitrogen'], answer: 1 },
      { problem: 'Kesan rumah hijau menyebabkan suhu bumi?', options: ['Turun','Naik (pemanasan global)','Tidak berubah'], answer: 1 },
      { problem: 'Pencairan ais kutub menyebabkan?', options: ['Paras laut turun','Paras laut naik','Cuaca sejuk'], answer: 1 },
      { problem: '3R bermaksud?', options: ['Run, Rest, Relax','Reduce, Reuse, Recycle','Read, Run, Rest'], answer: 1 },
      { problem: 'Mengurangkan penggunaan plastik adalah contoh?', options: ['Recycle','Reduce','Reuse'], answer: 1 },
      { problem: 'Menggunakan semula botol air adalah?', options: ['Reduce','Recycle','Reuse'], answer: 2 },
      { problem: 'Menghantar kertas ke pusat kitar semula adalah?', options: ['Reduce','Reuse','Recycle'], answer: 2 },
      { problem: 'Pencemaran tanah boleh disebabkan?', options: ['Hujan bersih','Sisa toksik industri','Angin'], answer: 1 },
      { problem: 'Ozon di atmosfera melindungi dari?', options: ['Hujan','Sinaran UV berbahaya','Angin'], answer: 1 },
      { problem: 'CFC (klorofluorokarbon) merosakkan?', options: ['Tanah','Lapisan ozon','Air laut'], answer: 1 },
      { problem: 'Pembangunan lestari bermaksud?', options: ['Binakan lebih bangunan','Gunakan sumber dengan bijak untuk masa depan','Hentikan semua industri'], answer: 1 },
      { problem: 'Tenaga boleh diperbaharui adalah lebih baik kerana?', options: ['Lebih murah sahaja','Tidak habis dan lebih bersih','Lebih mudah'], answer: 1 },
      { problem: 'Impak penebangan hutan?', options: ['Lebih oksigen','Kehilangan habitat, banjir, hakisan','Cuaca baik'], answer: 1 },
      { problem: 'Cara mengurangkan pencemaran udara?', options: ['Bakar lebih sampah','Guna kenderaan awam','Buka lebih kilang'], answer: 1 },
      { problem: 'Biojisim (biomass) adalah sumber tenaga dari?', options: ['Batu','Bahan organik tumbuhan/haiwan','Gas'], answer: 1 },
      { problem: 'Jejak karbon bermaksud?', options: ['Kesan kaki di tanah','Jumlah CO₂ dihasilkan aktiviti seseorang','Jenis batuan'], answer: 1 },
      { problem: 'Kitar semula membantu?', options: ['Hasilkan lebih sampah','Jimat sumber dan kurang sampah','Tambah pencemaran'], answer: 1 },
      { problem: 'Tanam pokok membantu?', options: ['Tambah CO₂','Serap CO₂ dan hasilkan O₂','Panaskan bumi'], answer: 1 },
      { problem: 'Bahan biodegradable bermaksud?', options: ['Tidak boleh hancur','Boleh terurai secara semula jadi','Beracun'], answer: 1 },
      { problem: 'Cara terbaik tangani perubahan iklim?', options: ['Abaikan','Kerjasama global kurangkan pelepasan gas','Tunggu saja'], answer: 1 },
    ]}
  },
  {
    title: 'Teknologi dan Inovasi Sains D6',
    type: 'multiple_choice',
    emoji: '🔬',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Bioteknologi bermaksud?', options: ['Kajian batu','Penggunaan organisma hidup untuk produk','Kajian planet'], answer: 1 },
      { problem: 'Vaksin berfungsi untuk?', options: ['Bunuh bakteria terus','Latih sistem imun','Bersihkan darah'], answer: 1 },
      { problem: 'Antibiotik digunakan untuk rawat?', options: ['Jangkitan virus','Jangkitan bakteria','Kanser'], answer: 1 },
      { problem: 'Pengklonan adalah proses?', options: ['Membiak secara seksual','Hasilkan salinan genetik sama','Ubah gen'], answer: 1 },
      { problem: 'DNA bermaksud?', options: ['Deoxyribonucleic Acid','Dynamic Nuclear Array','Digital Network Analysis'], answer: 0 },
      { problem: 'Nanotek beroperasi pada skala?', options: ['Meter','Sentimeter','Nanometer'], answer: 2 },
      { problem: 'Robot digunakan dalam industri untuk?', options: ['Bermain','Tugas berulang yang tepat','Tidur'], answer: 1 },
      { problem: 'Internet of Things (IoT) bermaksud?', options: ['Benda-benda disambung internet','Internet untuk haiwan','Kajian web'], answer: 0 },
      { problem: 'Kecerdasan buatan (AI) meniru?', options: ['Tumbuhan','Kecerdasan manusia','Haiwan'], answer: 1 },
      { problem: 'Panel solar adalah teknologi?', options: ['Tenaga fosil','Tenaga solar boleh diperbaharui','Tenaga nuklear'], answer: 1 },
      { problem: 'Teknologi GPS menggunakan?', options: ['Radar','Satelit','Kabel bawah laut'], answer: 1 },
      { problem: 'Perubatan nanoteknologi boleh?', options: ['Bina robot besar','Hantar ubat ke sel sakit','Gantikan doktor'], answer: 1 },
      { problem: 'Kenderaan elektrik berbeza kereta biasa kerana?', options: ['Lebih besar','Gunakan motor elektrik, bukan enjin petrol','Lebih laju'], answer: 1 },
      { problem: 'Pencetakan 3D boleh menghasilkan?', options: ['Hanya kertas','Objek 3D dari pelbagai bahan','Gambar sahaja'], answer: 1 },
      { problem: 'Teknologi hijau bertujuan untuk?', options: ['Tingkatkan pencemaran','Kurangkan kesan alam sekitar','Tingkatkan kos'], answer: 1 },
      { problem: 'Teleskop James Webb dilancarkan untuk?', options: ['Tengok bumi','Kaji alam semesta jauh','Pantau cuaca'], answer: 1 },
      { problem: 'CRISPR adalah teknologi untuk?', options: ['Penyuntingan gen','Buat ubat biasa','Kaji planet'], answer: 0 },
      { problem: 'Komputer kuantum lebih laju dari komputer biasa kerana?', options: ['Lebih besar','Guna qubit - boleh proses selari','Lebih mahal'], answer: 1 },
      { problem: 'Biomimicry adalah?', options: ['Klon haiwan','Tiru reka bentuk alam untuk teknologi','Buat robot haiwan'], answer: 1 },
      { problem: 'Masa depan tenaga yang paling bersih?', options: ['Arang','Tenaga fusion nuklear','Minyak'], answer: 1 },
    ]}
  },
  {
    title: 'Kaedah Saintifik dan Eksperimen D6',
    type: 'multiple_choice',
    emoji: '⚗️',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Langkah pertama kaedah saintifik?', options: ['Eksperimen','Kenal pasti masalah/soalan','Hipotesis'], answer: 1 },
      { problem: 'Hipotesis adalah?', options: ['Keputusan eksperimen','Jangkaan yang boleh diuji','Peralatan'], answer: 1 },
      { problem: 'Pembolehubah dimanipulasi adalah yang?', options: ['Dikekalkan sama','Diubah','Diukur'], answer: 1 },
      { problem: 'Pembolehubah bergerakbalas adalah yang?', options: ['Diubah','Diukur/diperhatikan','Dikekalkan'], answer: 1 },
      { problem: 'Pembolehubah kawalan adalah yang?', options: ['Diubah','Diukur','Dikekalkan sama'], answer: 2 },
      { problem: 'Replikasi dalam eksperimen bermakna?', options: ['Ulang sekali sahaja','Ulang beberapa kali untuk kepastian','Tidak perlu ulang'], answer: 1 },
      { problem: 'Data kuantitatif adalah data?', options: ['Berupa perkataan','Berupa nombor/ukuran','Berupa gambar'], answer: 1 },
      { problem: 'Data kualitatif adalah data?', options: ['Berupa nombor','Berupa deskripsi/perkataan','Berupa graf'], answer: 1 },
      { problem: 'Graf bar sesuai untuk data?', options: ['Berterusan','Berkategori','Masa'], answer: 1 },
      { problem: 'Graf garis sesuai untuk data?', options: ['Kategori','Perubahan mengikut masa','Perbandingan'], answer: 1 },
      { problem: 'Kesimpulan harus merujuk kepada?', options: ['Hipotesis dan keputusan','Hanya hipotesis','Hanya keputusan'], answer: 0 },
      { problem: 'Ralat dalam eksperimen boleh dikurangkan dengan?', options: ['Melakukan sekali sahaja','Mengukur berkali-kali','Abaikan ralat'], answer: 1 },
      { problem: 'Eksperimen kawalan berfungsi untuk?', options: ['Jimat masa','Perbandingan tanpa pembolehubah','Permudah kerja'], answer: 1 },
      { problem: 'Alat ukur yang tepat untuk isipadu cecair?', options: ['Sudu','Silinder penyukat','Bikar'], answer: 1 },
      { problem: 'Nilai min dikira dengan?', options: ['Jumlah sahaja','Jumlah ÷ bilangan','Nilai tengah'], answer: 1 },
      { problem: 'Pemerhatian yang baik mestilah?', options: ['Berdasarkan perasaan','Objektif dan tepat','Ringkas sahaja'], answer: 1 },
      { problem: 'Laporan eksperimen perlu mengandungi?', options: ['Pendapat sahaja','Tujuan, kaedah, keputusan, kesimpulan','Gambar sahaja'], answer: 1 },
      { problem: 'Kesimpulan yang baik menyatakan?', options: ['Soalan baru','Sama ada hipotesis disokong/tidak','Perasaan'], answer: 1 },
      { problem: 'Keselamatan makmal penting untuk?', options: ['Jimat wang','Elakkan kecederaan dan kemalangan','Lakukan kerja lebih laju'], answer: 1 },
      { problem: 'Simbol bahaya dalam makmal bermaksud?', options: ['Biasa sahaja','Ada risiko berbahaya','Bahan mahal'], answer: 1 },
    ]}
  },
  {
    title: 'Matahari, Bumi dan Bulan - Lanjutan D5/D6',
    type: 'multiple_choice',
    emoji: '🌍',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: 'Bumi mengambil berapa lama melingkar matahari?', options: ['1 bulan','365 hari (1 tahun)','24 jam'], answer: 1 },
      { problem: 'Bulan mengambil berapa lama melingkar bumi?', options: ['29.5 hari','365 hari','1 jam'], answer: 0 },
      { problem: 'Siang terjadi kerana?', options: ['Matahari bergerak','Bumi berputar - bahagian menghadap matahari','Tiada awanDalam kurun'], answer: 1 },
      { problem: 'Musim berubah kerana?', options: ['Jarak bumi ke matahari','Cerun paksi bumi','Bulan','Angin'], answer: 1 },
      { problem: 'Hemisphere utara musim panas ketika?', options: ['Juni-Ogos','Disember-Februari','September-November'], answer: 0 },
      { problem: 'Graviti matahari membuat bumi?', options: ['Terapung', 'Mengorbit','Bergolek'], answer: 1 },
      { problem: 'Fasa bulan berlaku kerana?', options: ['Bulan berubah besar','Posisi bulan-bumi-matahari','Cahaya bulan melemah'], answer: 1 },
      { problem: 'Bulan baru terjadi apabila?', options: ['Bulan antara bumi dan matahari','Bumi antara bulan dan matahari','Bulan jauh dari bumi'], answer: 0 },
      { problem: 'Bulan purnama terjadi apabila??', options: ['Bumi antara bulan dan matahari','Bulan sisi bumi','Bulan jauh'], answer: 0 },
      { problem: 'Pasang surut disebabkan??', options: ['Angin laut','Graviti bulan menarik air laut','Cuaca panas'], answer: 1 },
      { problem: 'Gerhana bulan terjadi apabila?', options: ['Bulan antara bumi-matahari','Bumi antara bulan-matahari','Bulan menyentuh matahari'], answer: 1 },
      { problem: 'Gerhana matahari terjadi apabila?', options: ['Bumi antara bulan-matahari','Bulan antara bumi-matahari','Bulan di belakang bumi'], answer: 1 },
      { problem: 'Kutub bumi condong kerana?', options: ['Tokin purba','Cerun paksi bumi','Graviti'], answer: 1 },
      { problem: 'Panjang hari berbeza mengikut?', options: ['Longitud','Latitud','Bulan'], answer: 1 },
      { problem: 'Di kutub utara, musim panas hari sangat?', options: ['Pendek','Panjang','Tidak ada'], answer: 1 },
      { problem: 'Lintasan bumi mengelilingi matahari disebut?', options: ['Putaran','Orbita','Revolusi'], answer: 2 },
      { problem: 'Putaran bumi menghasilkan?', options: ['Musim','Siang dan malam','Tahun'], answer: 1 },
      { problem: 'Satelit tiruan mengorbit bumi seperti?', options: ['Bulan','Matahari','Planet'], answer: 0 },
      { problem: 'Cahaya matahari sampai bumi dalam berapa minit?', options: ['1 minit','8 minit','30 minit'], answer: 1 },
      { problem: 'Energi bumi datang terutama dari?', options: ['Bulan','Matahari','Bintang lain'], answer: 1 },
    ]}
  },
  {
    title: 'Fosil dan Sejarah Bumi - Lanjutan D5/D6',
    type: 'multiple_choice',
    emoji: '🦖',
    difficulty: 'hard',
    darjah: 5,
    gameData: { questions: [
      { problem: 'Fosil terbentuk dari?', options: ['Batu sahaja','Sisa organisma purba terkubur','Tanah hitam'], answer: 1 },
      { problem: 'Contoh fosil?', options: ['Daun pokok hidup','Kerangka dinosaur terpetri','Tanah'], answer: 1 },
      { problem: 'Fosil jejakMakanan terbentuk dari?', options: ['Badan organisma','Jejak kaki atau tahi','Gua'], answer: 1 },
      { problem: 'Batu kapur terbentuk dari?', options: ['Batuan vulkanik','Cangkang organism laut','Pasir'], answer: 1 },
      { problem: 'Minyak bumi datang dari?', options: ['Pokok','Organisma laut purba terkompres','Batu'], answer: 1 },
      { problem: 'Arang batu terbentuk dari?', options: ['Batu keras','Pokok purba terkompres','Tanah'], answer: 1 },
      { problem: 'Dinosaur hidup pada??', options: ['Era Hadal','Era Mesozoik','Era Kaenozoik'], answer: 1 },
      { problem: 'Dinosaur pupus kira-kira??', options: ['100 tahun lepas','Masa mudah sekarang','65 juta tahun lepas'], answer: 2 },
      { problem: 'Teori punah dinosaur??', options: ['Makanan habis','Meteorit besar hentam bumi','Suhu tinggi'], answer: 1 },
      { problem: 'Usia bumi kira-kira berapa juta tahun??', options: ['100','1000','4600'], answer: 2 },
      { problem: 'Lapisan bumi paling dalam disebut??', options: ['Kerak','Mantel','Teras'], answer: 2 },
      { problem: 'Ketebalan kerak bumi??', options: ['100 km','10 km','1000 km'], answer: 0 },
      { problem: 'Plat tektonik bumi bergerak kerana??', options: ['Angin','Arus mantel panas','Rotasi'], answer: 1 },
      { problem: 'Gempa bumi berlaku apabila plat??', options: ['Bergerak lambat','Bergerak cepat tiba-tiba','Tidak bergerak'], answer: 1 },
      { problem: 'Gunung api terbentuk dari??', options: ['Batu terangkat','Magma keluar dari bumi','Erosi'], answer: 1 },
      { problem: 'Usia fosil boleh ditentukan dengan??', options: ['Warna','Kadar radioisotop, tarikh karbon','Besar'], answer: 1 },
      { problem: 'Pokok dan tumbuhan pertama hidup pada??', options: ['Era Hadal','Era Paleozoik','Era Mesozoik'], answer: 1 },
      { problem: 'Manusia purba hidup pada??', options: ['Era Paleozoik','Era Mesozoik','Era Kaenozoik'], answer: 2 },
      { problem: 'Es zaman pertama terjadi pada??', options: ['Era Paleozoik','Era Mesozoik','Era Kaenozoik'], answer: 2 },
      { problem: 'Tektonikal bumi lebih aktif di??', options: ['Tengah benua','Sempadan plat','Kawasan rata'], answer: 1 },
    ]}
  },
  {
    title: 'Tenaga Nuklear dan Keselamatan - Lanjutan D6',
    type: 'multiple_choice',
    emoji: '☢️',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Tenaga nuklear dihasilkan dari??', options: ['Api','Pemecahan nukleus atom (fisi)','Matahari terus'], answer: 1 },
      { problem: 'Tenaga fusi nuklear adalah??', options: ['Bergabung dua nukleus','Belah nukleus','Leburan'], answer: 0 },
      { problem: 'Sumber tenaga untuk matahari adalah??', options: ['Pembakaran','Fusi nuklear','Batu'], answer: 1 },
      { problem: 'Nuklear fisi lepaskan berapa tenaga??', options: ['Sedikit','Sangat besar','Tiada'], answer: 1 },
      { problem: 'Reaktor nuklear digunakan untuk??', options: ['Mainan','Jana elektrik','Cuaca'], answer: 1 },
      { problem: 'Bahan bakar nuklear yang umum??', options: ['Plutonium','Uranium-235','Tungsten'], answer: 1 },
      { problem: 'Sisa radioaktif nuklear berbahaya kerana??', options: ['Warna merah','Memancar tenaga berbahaya','Berat'], answer: 1 },
      { problem: 'Masa separuh uranium-235 adalah??', options: ['1 tahun','700 juta tahun','10 tahun'], answer: 1 },
      { problem: 'Keselamatan plumbum (lead) dalam nuklear??', options: ['Penghantar','Pelindung radiasi','Pendingin'], answer: 1 },
      { problem: 'Reflektor dalam reaktor fungsinya??', options: ['Hangatkan','Pantulan neutron kembali','Sejukkan'], answer: 1 },
      { problem: 'Bahan pendingin reaktor nuklear selalunya??', options: ['Udara','Air atau helium','Pasir'], answer: 1 },
      { problem: 'Kemalangan Chernobyl berlaku kerana??', options: ['Api','Ledakan reaktor','Angin'], answer: 1 },
      { problem: 'Radiasi alpha adalah??', options: ['Cahaya','Zarah heliun (inti helium)','Gelombang'], answer: 1 },
      { problem: 'Radiasi beta adalah??', options: ['Elektron','Foton','Proton'], answer: 0 },
      { problem: 'Radiasi gamma adalah??', options: ['Zarah','Foton tenaga tinggi','Neutron'], answer: 1 },
      { problem: 'Kegunaan radiasi dalam perubatan??', options: ['Ganti batu ginjal','Rawat kanser, sterilisasi alat','Ubah air'], answer: 1 },
      { problem: 'Dosis radiasi selamat untuk manusia??', options: ['100 sievert','Semua dosis aman','Kurang dari 0.1 sievert'], answer: 2 },
      { problem: 'Kurikulum nukleus atom mengandungi??', options: ['Neuton sahaja','Proton dan neutron','Elektron'], answer: 1 },
      { problem: 'Negara yang paling banyak guna tenaga nuklear??', options: ['Australia','Perancis','Indonesia'], answer: 1 },
      { problem: 'Penjualan sisa nuklear?', options: ['Ambil terus','Simpan di lokasi khusus berabad-abad','Buang ke laut'], answer: 1 },
    ]}
  },
  {
    title: 'Sistem Saraf dan Hormon Manusia - Lanjutan D6',
    type: 'multiple_choice',
    emoji: '🧠',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Saraf membawa isyarat dalam berapa arah?', options: ['1','2','3'], answer: 1 },
      { problem: 'Saraf sensorik membawa??', options: ['Perintah ke otot','Maklumat ke otak','Darah'], answer: 1 },
      { problem: 'Saraf motor membawa??', options: ['Maklumat masuk','Perintah keluar ke otot','Hormon'], answer: 1 },
      { problem: 'Neuron terdiri dari??', options: ['Badan sel dan akson','Badan sel dan dendrit','Akson dan dendrit'], answer: 2 },
      { problem: 'Sinap adalah??', options: ['Bahagian neuron','Jurang antara dua neuron','Sel saraf'], answer: 1 },
      { problem: 'Refleks arcsin melibatkan??', options: ['Otak sahaja','Saraf tunjang tanpa otak','Otot'], answer: 1 },
      { problem: 'Hormon adalah??', options: ['Bahagian saraf','Cecair kimia untuk keseimbangan badan','Sel darah'], answer: 1 },
      { problem: 'Anak gondok berlaku kerana kekurangan??', options: ['Kalsium','Iodine','Besi'], answer: 1 },
      { problem: 'Pankreas mengeluarkan??', options: ['Hable','Insulin untuk kawal gula darah','Adrenalin'], answer: 1 },
      { problem: 'Diabetes berlaku akibat??', options: ['Kekurangan insulin atau rintangan insulin','Kekurangan air','Tekanan rendah'], answer: 0 },
      { problem: 'Kelenjar adrenal mengeluarkan??', options: ['Tiroksin','Adrenalin untuk tindakan cepat','Insulin'], answer: 1 },
      { problem: 'Pubertas disebabkan oleh??', options: ['Makanan','Hormon seks dari gonad','Sinar matahari'], answer: 1 },
      { problem: 'Otak terdiri dari??', options: ['Sel darah','Sel saraf dan sel glial','Otot'], answer: 1 },
      { problem: 'Cere bellum mengawal??', options: ['Emosi','Keseimbangan dan koordinasi','Ingatan'], answer: 1 },
      { problem: 'Hipotalamus mengawal??', options: ['Gerakan','Suhu badan dan hormon hipofisis','Penglihatan'], answer: 1 },
      { problem: 'Saraf bahagian simpatetik bertindak??', options: ['Santai','Lawan atau lari','Tidur'], answer: 1 },
      { problem: 'Saraf parasimpatetik membuat badan??', options: ['Tegang','Santai dan pemulihan','Cepat'], answer: 1 },
      { problem: 'Ubat psikotropik mempengaruhi??', options: ['Otot','Proses mental dan emosi','Darah'], answer: 1 },
      { problem: 'Plastisiti otak bermakna??', options: ['Keras','Boleh berubah fungsi lain','Rapuh'], answer: 1 },
      { problem: 'Dorming (tidur siaga) dalam otak ialah??', options: ['Tidur lena','Aktiviti otak saat istirahat','Bermimpi'], answer: 1 },
    ]}
  },
  {
    title: 'Biomekanik dan Anggota Gerak - Lanjutan D6',
    type: 'multiple_choice',
    emoji: '🦴',
    difficulty: 'hard',
    darjah: 6,
    gameData: { questions: [
      { problem: 'Sendi (joint) membolehkan??', options: ['Warna berubah','Gerakan badan','Otot bertambah'], answer: 1 },
      { problem: 'Sendi peluru (ball dan socket) contohnya??', options: ['Siku','Bahu','Lutut'], answer: 1 },
      { problem: 'Sendi engsel (hinge) contohnya??', options: ['Lutut','Bahu','Pinggul'], answer: 0 },
      { problem: 'Ligamen menghubungkan??', options: ['Otot ke tulang','Tulang ke tulang','Saraf ke otot'], answer: 1 },
      { problem: 'Tendon menghubungkan??', options: ['Tulang ke tulang','Otot ke tulang','Saraf ke saraf'], answer: 1 },
      { problem: 'Tulang rawan (cartilage) melindungi dengan??', options: ['Keras','Lembut di hujung sendi','Berdarah'], answer: 1 },
      { problem: 'Cairan sinovial dalam sendi berfungsi??', options: ['Bekalan nutrisi','Pelincir untuk gerakan lancar','Perlindungan'], answer: 1 },
      { problem: 'Otot antagonis adalah??', options: ['Bekerja sama','Bekerja berlawanan arah','Satu jenis'], answer: 1 },
      { problem: 'Otot biseps membengkok siku dengan??', options: ['Otot lain bertambah','Kontraksi biseps','Relaksasi total'], answer: 1 },
      { problem: 'Otot triseps meluruskan siku dengan??', options: ['Relaksasi biseps','Kontraksi triseps','Kedua-duanya'], answer: 2 },
      { problem: 'Miosin dan aktin adalah??', options: ['Hormon','Protein penghasil gerak otot','Sel saraf'], answer: 1 },
      { problem: 'ATP diperlukan untuk??', options: ['Memberi warna','Tenaga otot untuk kontraksi','Transmisi saraf'], answer: 1 },
      { problem: 'Keram otot terjadi kerana??', options: ['Istirahat lama','Penumpukan asid laktat','Panas berlebihan'], answer: 1 },
      { problem: 'Osteoporosis berlaku akibat??', options: ['Makan terlalu banyak','Kekurangan kalsium dan aktiviti','Tidur banyak'], answer: 1 },
      { problem: 'Arthritis adalah??', options: ['Peradangan otot','Peradangan sendi','Kelemahan tulang'], answer: 1 },
      { problem: 'Postur yang baik??', options: ['Membungkuk','Tegak, bahagian tubuh selaras','Bersandar'], answer: 1 },
      { problem: 'Ergonomi mempelajari??', options: ['Otot saja','Keadaan kerja dan gerakan efisien','Tulang sahaja'], answer: 1 },
      { problem: 'Cedera ACL adalah??', options: ['Otot kecil','Robekan ligamen kritikal lutut','Patah tulang'], answer: 1 },
      { problem: 'Fraktur kompaun adalah??', options: ['Patah tanpa luka','Patah dengan luka terbuka','Patah bersudu'], answer: 1 },
      { problem: 'Penyembuhan tulang patah memerlukan??', options: ['Hanya ubat','Istirahat, imobilisasi, nutrisi kalsium','Olahraga intensif'], answer: 1 },
    ]}
  },
  ];