export const prasekolah_science_expansion = [
  { title: 'Haiwan & Tempat Tinggal', type: 'picture_quiz', emoji: '🦁', difficulty: 'easy', gameData: { questions: [
    { image: '🐠', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🐦', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐿️', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦈', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦅', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐜', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🐢', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦆', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐬', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦉', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐘', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦋', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐙', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🐌', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦜', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🦞', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦎', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🕊️', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🦑', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🐛', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦗', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🐓', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦀', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦭', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦩', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐊', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦔', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🐝', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🦚', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🐟', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦁', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🐸', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦇', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐍', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦧', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🐳', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦢', options: ['Air','Udara','Tanah'], answer: 1 },
    { image: '🐠', options: ['Air','Udara','Tanah'], answer: 0 },
    { image: '🦮', options: ['Air','Udara','Tanah'], answer: 2 },
    { image: '🦦', options: ['Air','Udara','Tanah'], answer: 0 },
  ]}},
  { title: 'Warna-Warni di Alam', type: 'color_match', emoji: '🌈', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Merah','Biru','Hijau'], answer: 0 },
    { image: '🔵', options: ['Merah','Biru','Hijau'], answer: 1 },
    { image: '🟢', options: ['Merah','Biru','Hijau'], answer: 2 },
    { image: '🟡', options: ['Kuning','Oren','Merah'], answer: 0 },
    { image: '🟠', options: ['Kuning','Oren','Merah'], answer: 1 },
    { image: '💜', options: ['Ungu','Merah Jambu','Biru'], answer: 0 },
    { image: '🤎', options: ['Coklat','Hitam','Kelabu'], answer: 0 },
    { image: '⚫', options: ['Coklat','Hitam','Kelabu'], answer: 1 },
    { image: '⚪', options: ['Putih','Kelabu','Kuning'], answer: 0 },
    { image: '🟤', options: ['Coklat','Hitam','Merah'], answer: 0 },
    { problem: 'Warna langit cerah?', options: ['Merah','Biru','Hijau'], answer: 1 },
    { problem: 'Warna daun pokok?', options: ['Merah','Kuning','Hijau'], answer: 2 },
    { problem: 'Warna matahari?', options: ['Kuning/Oren','Biru','Hijau'], answer: 0 },
    { problem: 'Warna awan?', options: ['Kelabu/Putih','Merah','Hijau'], answer: 0 },
    { problem: 'Warna tanah?', options: ['Biru','Coklat','Ungu'], answer: 1 },
    { problem: 'Warna pisang masak?', options: ['Hijau','Kuning','Merah'], answer: 1 },
    { problem: 'Warna epal merah?', options: ['Biru','Merah','Kuning'], answer: 1 },
    { problem: 'Campuran merah + biru = ?', options: ['Hijau','Ungu','Oren'], answer: 1 },
    { problem: 'Campuran merah + kuning = ?', options: ['Oren','Ungu','Hijau'], answer: 0 },
    { problem: 'Campuran biru + kuning = ?', options: ['Ungu','Oren','Hijau'], answer: 2 },
    { problem: 'Pelangi mempunyai berapa warna?', options: ['5','6','7'], answer: 2 },
    { problem: 'Warna lampu isyarat berhenti?', options: ['Hijau','Merah','Kuning'], answer: 1 },
    { problem: 'Warna lampu isyarat boleh jalan?', options: ['Merah','Kuning','Hijau'], answer: 2 },
    { problem: 'Warna salji?', options: ['Putih','Biru','Kelabu'], answer: 0 },
    { problem: 'Warna api?', options: ['Biru','Merah/Oren','Ungu'], answer: 1 },
    { problem: 'Warna oren (buah)?', options: ['Oren','Merah','Kuning'], answer: 0 },
    { problem: 'Warna anggur?', options: ['Ungu/Hijau','Merah','Kuning'], answer: 0 },
    { problem: 'Warna tembikai?', options: ['Kuning','Hijau (luar) Merah (dalam)','Biru'], answer: 1 },
    { problem: 'Warna susu?', options: ['Kuning','Putih','Kelabu'], answer: 1 },
    { problem: 'Warna hati (liver)?', options: ['Merah','Coklat kemerahan','Hijau'], answer: 1 },
    { problem: 'Warna gajah?', options: ['Hitam','Kelabu','Coklat'], answer: 1 },
    { problem: 'Warna lumba-lumba?', options: ['Biru','Kelabu','Hitam'], answer: 1 },
    { problem: 'Warna flamingo?', options: ['Merah','Merah Jambu','Ungu'], answer: 1 },
    { problem: 'Warna kuda zebra?', options: ['Hitam & Putih','Coklat','Kelabu'], answer: 0 },
    { problem: 'Warna harimau?', options: ['Hijau','Oren dengan jalur hitam','Merah'], answer: 1 },
    { problem: 'Warna dedaunan kering?', options: ['Hijau','Coklat/Kuning','Biru'], answer: 1 },
    { problem: 'Warna emas?', options: ['Kuning keemasan','Perak','Coklat'], answer: 0 },
    { problem: 'Warna perak?', options: ['Kuning','Kelabu perak','Putih'], answer: 1 },
    { problem: 'Warna besi yang berkarat?', options: ['Putih','Merah kecoklatan','Hitam'], answer: 1 },
    { problem: 'Warna bumi (planet)?', options: ['Merah','Biru dan Hijau','Kuning'], answer: 1 },
  ]}},
  { title: 'Makanan Sihat', type: 'picture_quiz', emoji: '🥗', difficulty: 'easy', gameData: { questions: [
    { image: '🥦', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍕', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥕', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍩', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🍎', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍔', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥛', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍬', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥚', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍟', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🍇', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🧁', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥩', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍫', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥝', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍦', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🌽', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🍰', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { image: '🥑', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 0 },
    { image: '🥤', options: ['Sihat','Tidak Sihat','Sederhana'], answer: 1 },
    { problem: 'Sayur-sayuran mengandungi?', options: ['Vitamin & mineral','Hanya gula','Lemak banyak'], answer: 0 },
    { problem: 'Minuman paling sihat?', options: ['Air kosong','Jus berkotak','Minuman bergas'], answer: 0 },
    { problem: 'Protein terdapat dalam?', options: ['Gula','Daging & telur','Garam'], answer: 1 },
    { problem: 'Kalsium baik untuk?', options: ['Kulit','Tulang & gigi','Mata'], answer: 1 },
    { problem: 'Vitamin C banyak dalam?', options: ['Daging','Oren & lemon','Nasi'], answer: 1 },
    { problem: 'Makan terlalu banyak gula boleh?', options: ['Sihat','Sakit gigi & gemuk','Tinggi'], answer: 1 },
    { problem: 'Serat terdapat dalam?', options: ['Daging','Sayur & buah','Gula'], answer: 1 },
    { problem: 'Berapa kali sehari kita perlu makan?', options: ['1','2','3'], answer: 2 },
    { problem: 'Karbohidrat terdapat dalam?', options: ['Nasi & roti','Minyak','Daging'], answer: 0 },
    { problem: 'Ikan baik untuk?', options: ['Protein & omega 3','Hanya rasa','Tiada kebaikan'], answer: 0 },
    { problem: 'Minum air berapa gelas sehari?', options: ['2-3','4-5','6-8'], answer: 2 },
    { problem: 'Cara masak paling sihat?', options: ['Goreng deep-fry','Kukus/rebus','Goreng dalam minyak banyak'], answer: 1 },
    { problem: 'Susu mengandungi banyak?', options: ['Vitamin C','Kalsium','Serat'], answer: 1 },
    { problem: 'Makanan pelangi bermaksud?', options: ['Makanan berwarna-warni sihat','Makanan manis','Makanan masam'], answer: 0 },
    { problem: 'Sarapan pagi penting kerana?', options: ['Membazir masa','Beri tenaga untuk aktiviti pagi','Tidak penting'], answer: 1 },
    { problem: 'Lemak baik terdapat dalam?', options: ['Gorengan','Alpukat & ikan','Gula'], answer: 1 },
    { problem: 'Makanan seimbang bermaksud?', options: ['Makan banyak-banyak','Makan semua jenis makanan berkhasiat','Makan sekali sehari'], answer: 1 },
    { problem: 'Zink penting untuk?', options: ['Sistem imun','Warna rambut','Ketinggian'], answer: 0 },
    { problem: 'Buah-buahan mengandungi banyak?', options: ['Lemak','Vitamin','Garam'], answer: 1 },
    { problem: 'Makanan yang banyak lemak tidak sihat?', options: ['Salad','Goreng-gorengan','Buah'], answer: 1 },
  ]}},
  { title: 'Siang dan Malam', type: 'picture_quiz', emoji: '🌙', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['Siang','Malam','Petang'], answer: 0 },
    { image: '🌙', options: ['Siang','Malam','Pagi'], answer: 1 },
    { image: '🌅', options: ['Pagi','Tengahari','Malam'], answer: 0 },
    { image: '🌇', options: ['Pagi','Petang','Malam'], answer: 1 },
    { image: '⭐', options: ['Siang','Malam','Pagi'], answer: 1 },
    { image: '🌄', options: ['Pagi','Malam','Petang'], answer: 0 },
    { image: '🌤️', options: ['Siang','Malam','Subuh'], answer: 0 },
    { image: '🌃', options: ['Siang','Malam','Pagi'], answer: 1 },
    { image: '🌞', options: ['Siang','Malam','Petang'], answer: 0 },
    { image: '🌉', options: ['Siang','Malam','Pagi'], answer: 1 },
    { image: '🌌', options: ['Siang','Malam Berbintang','Petang'], answer: 1 },
    { image: '🌠', options: ['Siang','Malam (bintang jatuh)','Petang'], answer: 1 },
    { problem: 'Matahari terbit di waktu?', options: ['Malam','Pagi','Petang'], answer: 1 },
    { problem: 'Matahari terbenam di waktu?', options: ['Pagi','Tengahari','Petang/Senja'], answer: 2 },
    { problem: 'Bintang dapat dilihat pada?', options: ['Siang','Malam','Tengahari'], answer: 1 },
    { problem: 'Bulan dapat dilihat pada?', options: ['Siang sahaja','Malam','Tidak pernah'], answer: 1 },
    { problem: 'Cahaya di siang hari datang dari?', options: ['Bulan','Matahari','Bintang'], answer: 1 },
    { problem: 'Bayang pendek terbentuk pada?', options: ['Pagi','Tengahari','Petang'], answer: 1 },
    { problem: 'Berapa jam sehari?', options: ['12','24','48'], answer: 1 },
    { problem: 'Subuh adalah waktu?', options: ['Awal pagi sebelum matahari terbit','Tengahari','Malam'], answer: 0 },
    { problem: 'Haiwan yang aktif pada malam hari?', options: ['Ayam','Burung Hantu','Kupu-kupu'], answer: 1 },
    { problem: 'Tumbuhan buat makanan pada waktu?', options: ['Malam','Siang (ada cahaya)','Bila-bila masa'], answer: 1 },
    { problem: 'Warna langit senja?', options: ['Biru','Oren/Merah','Hitam'], answer: 1 },
    { problem: 'Kelawar keluar pada?', options: ['Pagi','Siang','Malam'], answer: 2 },
    { problem: 'Bumi mengambil berapa hari mengelilingi matahari?', options: ['30 hari','365 hari','7 hari'], answer: 1 },
    { problem: 'Bulan mengambil berapa hari mengelilingi bumi?', options: ['7 hari','28-30 hari','365 hari'], answer: 1 },
    { problem: 'Waktu tengahari paling panas kerana?', options: ['Matahari paling rendah','Matahari paling tinggi di langit','Tiada sebab'], answer: 1 },
    { problem: 'Senja terjadi apabila?', options: ['Matahari terbit','Matahari terbenam','Tengah malam'], answer: 1 },
    { problem: 'Fajar terjadi apabila?', options: ['Matahari terbit','Matahari terbenam','Tengah malam'], answer: 0 },
    { problem: 'Bunga matahari menghadap ke?', options: ['Bulan','Matahari','Tanah'], answer: 1 },
    { problem: 'Waktu pagi paling dingin pada?', options: ['Tengahari','Subuh/Awal pagi','Petang'], answer: 1 },
    { problem: 'Sehari semalam = berapa jam?', options: ['12','24','36'], answer: 1 },
    { problem: 'Jam 12 tengahari bermaksud?', options: ['Tengah malam','Tengah hari','Awal pagi'], answer: 1 },
    { problem: 'Jam 12 malam bermaksud?', options: ['Tengah hari','Tengah malam','Petang'], answer: 1 },
    { problem: 'Pada waktu malam, kita perlu?', options: ['Bermain di luar','Tidur & berehat','Makan banyak'], answer: 1 },
    { problem: 'Aktiviti yang sesuai pada siang hari?', options: ['Tidur','Bersekolah & bermain','Menonton gelap'], answer: 1 },
    { problem: 'Bintang yang paling hampir dengan bumi?', options: ['Sirius','Matahari','Polaris'], answer: 1 },
    { problem: 'Kenapa ada siang dan malam?', options: ['Bumi berputar','Matahari bergerak','Bulan bergerak'], answer: 0 },
    { problem: 'Bentuk bulan penuh?', options: ['Separuh bulatan','Bulatan penuh','Sabit'], answer: 1 },
  ]}},
  { title: 'Pancaindera', type: 'picture_quiz', emoji: '👁️', difficulty: 'easy', gameData: { questions: [
    { image: '👁️', options: ['Lihat','Dengar','Rasa'], answer: 0 },
    { image: '👂', options: ['Lihat','Dengar','Bau'], answer: 1 },
    { image: '👃', options: ['Lihat','Rasa','Bau'], answer: 2 },
    { image: '👅', options: ['Bau','Rasa','Dengar'], answer: 1 },
    { image: '✋', options: ['Lihat','Dengar','Sentuh'], answer: 2 },
    { image: '🌹', options: ['Harum','Berbunyi','Pahit'], answer: 0 },
    { image: '🍋', options: ['Manis','Masam','Masin'], answer: 1 },
    { image: '🥁', options: ['Berbunyi','Harum','Rasa'], answer: 0 },
    { image: '🎶', options: ['Lihat','Dengar','Rasa'], answer: 1 },
    { image: '🌶️', options: ['Pedas-Rasa','Harum-Bau','Keras-Sentuh'], answer: 0 },
    { image: '🧊', options: ['Bau','Rasa','Sentuh (sejuk)'], answer: 2 },
    { image: '🕯️', options: ['Lihat & Panas','Rasa','Dengar'], answer: 0 },
    { problem: 'Deria mana untuk lihat warna?', options: ['Mata','Hidung','Telinga'], answer: 0 },
    { problem: 'Deria mana untuk hidu bunga?', options: ['Mulut','Hidung','Mata'], answer: 1 },
    { problem: 'Deria mana untuk dengar muzik?', options: ['Mata','Telinga','Tangan'], answer: 1 },
    { problem: 'Deria mana untuk rasa manis?', options: ['Hidung','Lidah','Tangan'], answer: 1 },
    { problem: 'Deria mana untuk rasa panas/sejuk?', options: ['Mata','Hidung','Kulit'], answer: 2 },
    { problem: 'Berapa deria yang kita ada?', options: ['3','4','5'], answer: 2 },
    { problem: 'Garam rasanya?', options: ['Manis','Masam','Masin'], answer: 2 },
    { problem: 'Lemon rasanya?', options: ['Manis','Masam','Pahit'], answer: 1 },
    { problem: 'Gula rasanya?', options: ['Masam','Masin','Manis'], answer: 2 },
    { problem: 'Bunga ros baunya?', options: ['Busuk','Harum','Tiada bau'], answer: 1 },
    { problem: 'Api terasa?', options: ['Sejuk','Panas','Lembut'], answer: 1 },
    { problem: 'Ais terasa?', options: ['Panas','Sejuk','Lembut'], answer: 1 },
    { problem: 'Bulu terasa?', options: ['Keras','Kasar','Lembut'], answer: 2 },
    { problem: 'Batu terasa?', options: ['Lembut','Keras','Licin'], answer: 1 },
    { problem: 'Kita boleh rasa makanan menggunakan?', options: ['Hidung sahaja','Lidah','Mata'], answer: 1 },
    { problem: 'Deria sentuh terdapat di seluruh?', options: ['Hati','Kulit','Tulang'], answer: 1 },
    { problem: 'Orang buta menggunakan deria?', options: ['Mata lebih','Sentuh, dengar, bau & rasa','Hanya mata'], answer: 1 },
    { problem: 'Orang pekak tidak boleh?', options: ['Melihat','Mendengar','Merasa'], answer: 1 },
    { problem: 'Cermin mata membantu deria?', options: ['Pendengaran','Penglihatan','Bau'], answer: 1 },
    { problem: 'Hidung berfungsi untuk?', options: ['Melihat','Menghidu','Merasa'], answer: 1 },
    { problem: 'Muzik kuat terdengar?', options: ['Kuat/Bising','Sunyi','Perlahan'], answer: 0 },
    { problem: 'Kita perlu jaga deria kita dengan?', options: ['Abaikan','Menjaga kebersihan & kesihatan','Hanya tidur'], answer: 1 },
    { problem: 'Kopi pahit rasanya?', options: ['Manis','Pahit','Masam'], answer: 1 },
    { problem: 'Sampah baunya?', options: ['Harum','Busuk/Tidak Enak','Tiada bau'], answer: 1 },
    { problem: 'Bulu ayam terasa?', options: ['Keras','Lembut','Kasar'], answer: 1 },
    { problem: 'Kulit kita boleh rasa?', options: ['Hanya panas','Panas, sejuk, sakit, tekanan','Hanya sejuk'], answer: 1 },
    { problem: 'Apakah fungsi lidah selain rasa?', options: ['Menghidu','Membantu bercakap & menelan','Melihat'], answer: 1 },
    { problem: 'Apakah nama saintifik pancaindera kita?', options: ['Sistem Deria','Sistem Saraf','Sistem Tulang'], answer: 0 },
  ]}},
  { title: 'Tumbuhan di Sekeliling Kita', type: 'picture_quiz', emoji: '🌱', difficulty: 'easy', gameData: { questions: [
    { image: '🌳', options: ['Pokok','Bunga','Rumput'], answer: 0 },
    { image: '🌸', options: ['Pokok','Bunga','Daun'], answer: 1 },
    { image: '🍀', options: ['Bunga','Daun','Biji'], answer: 1 },
    { image: '🌵', options: ['Kaktus','Pokok Epal','Pokok Kelapa'], answer: 0 },
    { image: '🌻', options: ['Ros','Bunga Matahari','Orkid'], answer: 1 },
    { image: '🍄', options: ['Cendawan','Bunga','Pokok'], answer: 0 },
    { image: '🌿', options: ['Rumput','Daun','Akar'], answer: 1 },
    { image: '🌾', options: ['Padi','Rumput','Gandum'], answer: 0 },
    { image: '🌴', options: ['Pokok Kelapa','Pokok Pisang','Pokok Pinang'], answer: 0 },
    { image: '🌺', options: ['Bunga Ros','Bunga Raya','Bunga Matahari'], answer: 1 },
    { image: '🎋', options: ['Buluh','Pokok Getah','Pokok Kayu'], answer: 0 },
    { image: '🌹', options: ['Bunga Ros','Bunga Raya','Bunga Orkid'], answer: 0 },
    { problem: 'Bahagian tumbuhan yang menerima cahaya matahari?', options: ['Akar','Daun','Biji'], answer: 1 },
    { problem: 'Bahagian tumbuhan yang memindahkan air?', options: ['Daun','Batang','Bunga'], answer: 1 },
    { problem: 'Biji benih tumbuh menjadi?', options: ['Bunga','Anak pokok','Buah'], answer: 1 },
    { problem: 'Pokok kelapa tumbuh di?', options: ['Gurun','Pantai/Tropika','Kutub'], answer: 1 },
    { problem: 'Kaktus tumbuh di?', options: ['Padang Pasir','Laut','Hutan hujan'], answer: 0 },
    { problem: 'Tumbuhan memerlukan apa untuk tumbuh?', options: ['Air, cahaya, tanah','Hanya air','Hanya cahaya'], answer: 0 },
    { problem: 'Contoh tumbuhan buah?', options: ['Pokok Paku','Pokok Mangga','Pokok Bakau'], answer: 1 },
    { problem: 'Tumbuhan berklorofil berwarna?', options: ['Merah','Hijau','Biru'], answer: 1 },
    { problem: 'Manfaat pokok kepada manusia?', options: ['Tiada manfaat','Oksigen, makanan, teduhan','Hanya cantik'], answer: 1 },
    { problem: 'Akar tumbuhan berfungsi untuk?', options: ['Buat makanan','Serap air & mineral dari tanah','Tangkap cahaya'], answer: 1 },
    { problem: 'Bunga berfungsi untuk?', options: ['Fotosintesis','Pembiakan tumbuhan','Serap air'], answer: 1 },
    { problem: 'Tumbuhan yang boleh makan serangga?', options: ['Kaktus','Pokok Periuk Kera','Ros'], answer: 1 },
    { problem: 'Lumut biasa tumbuh di tempat?', options: ['Kering','Panas','Lembap/Teduh'], answer: 2 },
    { problem: 'Tumbuhan yang tumbuh dalam air?', options: ['Kaktus','Teratai','Pokok getah'], answer: 1 },
    { problem: 'Padi ditanam di?', options: ['Sawah','Gurun','Hutan'], answer: 0 },
    { problem: 'Berapa bahagian utama tumbuhan?', options: ['3','4','5'], answer: 2 },
    { problem: 'Bahagian tumbuhan yang boleh kita makan?', options: ['Semua bahagian','Buah, daun, akar, biji','Hanya buah'], answer: 1 },
    { problem: 'Pokok yang menghasilkan getah?', options: ['Pokok Pisang','Pokok Getah/Hevea','Pokok Kelapa'], answer: 1 },
    { problem: 'Tumbuhan yang tidak perlu cahaya matahari?', options: ['Semua perlukan cahaya','Cendawan','Pokok mangga'], answer: 1 },
    { problem: 'Daun gugur banyak berlaku pada musim?', options: ['Bunga','Luruh (autumn)','Hujan'], answer: 1 },
    { problem: 'Warna daun yang sihat biasanya?', options: ['Kuning','Hijau','Coklat'], answer: 1 },
    { problem: 'Cara tumbuhan bernafas?', options: ['Melalui akar','Melalui daun (stoma)','Melalui batang'], answer: 1 },
    { problem: 'Contoh tumbuhan yang menjalar?', options: ['Pokok getah','Timun','Pokok kelapa'], answer: 1 },
    { problem: 'Bau bunga bertujuan untuk?', options: ['Sedapkan udara','Menarik serangga untuk pendebungaan','Tidak ada tujuan'], answer: 1 },
    { problem: 'Tumbuhan berduri contohnya?', options: ['Teratai','Kaktus & mawar','Padi'], answer: 1 },
    { problem: 'Bahagian pokok yang paling keras?', options: ['Daun','Batang/Kayu','Akar kecil'], answer: 1 },
    { problem: 'Kenapa daun berubah warna pada musim luruh?', options: ['Kotor','Klorofil berkurang','Kena angin'], answer: 1 },
    { problem: 'Peranan pokok dalam alam sekitar?', options: ['Mengeluarkan CO2','Menghasilkan oksigen','Menyerap oksigen'], answer: 1 },
  ]}},
  { title: 'Langit dan Cuaca', type: 'picture_quiz', emoji: '⛅', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['Panas','Sejuk','Hujan'], answer: 0 },
    { image: '🌧️', options: ['Panas','Sejuk','Hujan'], answer: 2 },
    { image: '⛅', options: ['Awan','Panas','Gelap'], answer: 0 },
    { image: '🌈', options: ['Pelangi','Kilat','Hujan'], answer: 0 },
    { image: '💨', options: ['Angin','Hujan','Panas'], answer: 0 },
    { image: '🌩️', options: ['Kilat','Pelangi','Awan'], answer: 0 },
    { image: '❄️', options: ['Ais','Hujan','Salji'], answer: 2 },
    { image: '🌫️', options: ['Kabus','Asap','Awan'], answer: 0 },
    { image: '🌪️', options: ['Ribut Taufan','Hari Cerah','Gerimis'], answer: 0 },
    { image: '☃️', options: ['Bersalji','Hujan','Hari Panas'], answer: 0 },
    { image: '🌤️', options: ['Cerah Sedikit Awan','Hujan','Gelap'], answer: 0 },
    { image: '⛈️', options: ['Ribut Petir','Hari Cerah','Hari Berangin'], answer: 0 },
    { problem: 'Cuaca Malaysia biasanya?', options: ['Sejuk seperti Eropah','Panas dan lembap/hujan','Bersalji'], answer: 1 },
    { problem: 'Apa yang digunakan masa hujan?', options: ['Cermin mata hitam','Payung','Topi panas'], answer: 1 },
    { problem: 'Kilat adalah?', options: ['Bunyi','Cahaya elektrik di awan','Angin'], answer: 1 },
    { problem: 'Guruh adalah?', options: ['Cahaya','Bunyi dari kilat','Hujan'], answer: 1 },
    { problem: 'Alat ukur suhu?', options: ['Pembaris','Termometer','Jam'], answer: 1 },
    { problem: 'Banjir berlaku akibat?', options: ['Hujan ringan','Hujan lebat berterusan','Hari panas'], answer: 1 },
    { problem: 'Awan putih membawa?', options: ['Hujan lebat','Cuaca cerah/baik','Ribut'], answer: 1 },
    { problem: 'Awan gelap/hitam membawa?', options: ['Cuaca cerah','Hujan atau ribut','Panas terik'], answer: 1 },
    { problem: 'Pelangi muncul bila?', options: ['Sebelum hujan','Selepas hujan bila ada matahari','Waktu malam'], answer: 1 },
    { problem: 'Salji terbentuk apabila?', options: ['Terlalu panas','Sangat sejuk (di bawah 0°C)','Musim bunga'], answer: 1 },
    { problem: 'Kemarau bermaksud?', options: ['Hujan lebat','Tiada atau kurang hujan lama','Sejuk'], answer: 1 },
    { problem: 'Suhu diukur dalam unit?', options: ['Meter','Darjah Celsius (°C)','Kilogram'], answer: 1 },
    { problem: 'Jika suhu 35°C, cuaca?', options: ['Sejuk','Panas','Bersalji'], answer: 1 },
    { problem: 'Kabus terbentuk dari?', options: ['Asap','Titisan air halus di udara','Api'], answer: 1 },
    { problem: 'Ribut Taufan adalah?', options: ['Hujan biasa','Ribut angin kencang & hujan','Cerah'], answer: 1 },
    { problem: 'Musim hujan di Malaysia biasanya?', options: ['Jun-Julai','Oktober-Mac','Februari-Mac'], answer: 1 },
    { problem: 'Cuaca panas menyebabkan?', options: ['Sejuk','Peluh & haus','Hujan'], answer: 1 },
    { problem: 'Angin bertiup dari?', options: ['Tempat panas ke sejuk','Tempat sejuk ke panas','Bertentangan'], answer: 0 },
    { problem: 'Cara kenal cuaca hari ini?', options: ['Tengok TV/aplikasi cuaca','Tengok jam','Tanya rakan'], answer: 0 },
    { problem: 'Musim di Malaysia?', options: ['4 musim','2 musim (hujan & panas)','1 musim'], answer: 1 },
    { problem: 'Salji ada di Malaysia?', options: ['Ya, selalu','Tidak','Kadang-kadang'], answer: 1 },
    { problem: 'Hujan penting untuk?', options: ['Membanjiri','Memberi air kepada tumbuhan & manusia','Tiada kepentingan'], answer: 1 },
    { problem: 'Pakaian yang sesuai cuaca panas?', options: ['Jaket tebal','Baju nipis & cerah','Baju bulu'], answer: 1 },
    { problem: 'Pakaian yang sesuai cuaca hujan?', options: ['Baju pendek','Baju hujan/anorak','Baju nipis'], answer: 1 },
    { problem: 'Apa yang berlaku semasa hujan lebat dan petir?', options: ['Selamat main di luar','Lebih selamat di dalam rumah','Pergi mandi hujan'], answer: 1 },
    { problem: 'Kenapa cuaca berubah-ubah?', options: ['Kerana kita mahu','Pergerakan angin, awan & suhu','Tiada sebab'], answer: 1 },
    { problem: 'Embun pagi terbentuk kerana?', options: ['Hujan kecil','Pengewapan pada waktu malam','Angin'], answer: 1 },
    { problem: 'Warna pelangi ada berapa?', options: ['5','6','7'], answer: 2 },
  ]}},
  { title: 'Haiwan Peliharaan', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🐶', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🐰', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🦁', options: ['Peliharaan','Liar','Ternakan'], answer: 1 },
    { image: '🐄', options: ['Peliharaan','Liar','Ternakan'], answer: 2 },
    { image: '🐍', options: ['Peliharaan','Liar','Bahaya'], answer: 1 },
    { image: '🐠', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🐔', options: ['Peliharaan','Liar','Ternakan'], answer: 2 },
    { image: '🐹', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🦜', options: ['Peliharaan','Liar','Ternakan'], answer: 0 },
    { image: '🐑', options: ['Peliharaan','Liar','Ternakan'], answer: 2 },
    { image: '🐐', options: ['Peliharaan','Liar','Ternakan'], answer: 2 },
    { problem: 'Haiwan peliharaan perlu?', options: ['Makanan dan penjagaan','Dibiarkan sahaja','Dikurung selalu'], answer: 0 },
    { problem: 'Kucing memakan?', options: ['Rumput','Daging/makanan kucing','Biji-bijian'], answer: 1 },
    { problem: 'Arnab suka makan?', options: ['Daging','Sayur & wortel','Ikan'], answer: 1 },
    { problem: 'Ikan peliharaan perlu?', options: ['Udara','Air bersih & makanan ikan','Tanah'], answer: 1 },
    { problem: 'Haiwan peliharaan perlu pergi ke?', options: ['Sekolah','Doktor haiwan','Pejabat pos'], answer: 1 },
    { problem: 'Burung peliharaan tinggal dalam?', options: ['Sangkar','Baldi','Rumah manusia'], answer: 0 },
    { problem: 'Haiwan ternakan memberi manfaat?', options: ['Susu, daging, telur','Tiada manfaat','Hanya hiburan'], answer: 0 },
    { problem: 'Anjing membantu manusia dengan?', options: ['Memasak','Menjaga rumah/keselamatan','Memandu'], answer: 1 },
    { problem: 'Hamster adalah haiwan?', options: ['Liar','Peliharaan kecil','Ternakan'], answer: 1 },
    { problem: 'Kucing mengeluarkan suara?', options: ['Woof','Meow','Moo'], answer: 1 },
    { problem: 'Anjing mengeluarkan suara?', options: ['Meow','Woof/Bark','Moo'], answer: 1 },
    { problem: 'Lembu mengeluarkan suara?', options: ['Meow','Woof','Moo'], answer: 2 },
    { problem: 'Kambing mengeluarkan suara?', options: ['Moo','Baa/Meh','Woof'], answer: 1 },
    { problem: 'Vaksin untuk haiwan penting untuk?', options: ['Membuat cantik','Cegah penyakit','Buat gemuk'], answer: 1 },
    { problem: 'Ikan koi biasanya dipelihara dalam?', options: ['Sangkar','Kolam','Bakul'], answer: 1 },
    { problem: 'Cara jaga haiwan peliharaan?', options: ['Biarkan kelaparan','Beri makan, air & vaksin','Pukul bila nakal'], answer: 1 },
    { problem: 'Haiwan yang paling popular dipelihara?', options: ['Harimau','Kucing & anjing','Buaya'], answer: 1 },
    { problem: 'Anjing polis digunakan untuk?', options: ['Bermain','Mencari & mengesan','Menari'], answer: 1 },
    { problem: 'Haiwan ternakan yang menghasilkan susu?', options: ['Ayam','Lembu & kambing','Arnab'], answer: 1 },
    { problem: 'Haiwan ternakan yang menghasilkan telur?', options: ['Lembu','Ayam & itik','Arnab'], answer: 1 },
    { problem: 'Kuda digunakan untuk?', options: ['Terbang','Menunggang & kerja','Berenang'], answer: 1 },
    { problem: 'Haiwan yang hidup dalam sangkar?', options: ['Ikan','Burung peliharaan','Arnab'], answer: 1 },
    { problem: 'Anjing boleh dengar suara yang?', options: ['Lebih tinggi dari manusia','Sama dengan manusia','Lebih rendah dari manusia'], answer: 0 },
    { problem: 'Kucing boleh melihat dalam?', options: ['Siang sahaja','Gelap/malam','Tidak boleh lihat'], answer: 1 },
    { problem: 'Haiwan peliharaan perlu dibersihkan?', options: ['Tidak perlu','Ya, supaya sihat','Hanya masa sakit'], answer: 1 },
    { problem: 'Ikan boleh hidup di?', options: ['Darat','Air (laut/tawar)','Udara'], answer: 1 },
    { problem: 'Pokok juga boleh dijadikan?', options: ['Haiwan peliharaan','Teman/hiasan dirumah','Jiran'], answer: 1 },
    { problem: 'Haiwan liar berbeza dari peliharaan kerana?', options: ['Lebih besar','Hidup bebas di alam','Lebih cantik'], answer: 1 },
  ]}},
  { title: 'Benda Hidup dan Benda Mati', type: 'picture_quiz', emoji: '🌿', difficulty: 'easy', gameData: { questions: [
    { image: '🌳', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🪑', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🐶', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '📚', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🐟', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🪨', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🌸', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🚗', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🌹', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🖊️', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🦋', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '💻', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🐜', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🧲', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { image: '🌻', options: ['Hidup','Mati','Tidak Pasti'], answer: 0 },
    { image: '🏠', options: ['Hidup','Mati','Tidak Pasti'], answer: 1 },
    { problem: 'Ciri-ciri benda hidup?', options: ['Tidak bergerak, tidak makan','Bernafas, membesar, makan','Tidak berubah'], answer: 1 },
    { problem: 'Ciri-ciri benda mati?', options: ['Memerlukan makanan','Tidak bernafas, tidak membesar','Membesar'], answer: 1 },
    { problem: 'Manusia adalah benda?', options: ['Mati','Hidup','Tidak pasti'], answer: 1 },
    { problem: 'Batu adalah benda?', options: ['Hidup','Mati','Tidak pasti'], answer: 1 },
    { problem: 'Pokok adalah benda?', options: ['Mati','Hidup','Tidak pasti'], answer: 1 },
    { problem: 'Air adalah benda?', options: ['Hidup','Mati','Tidak pasti'], answer: 1 },
    { problem: 'Adakah cendawan benda hidup?', options: ['Tidak','Ya, ia tumbuh','Tidak pasti'], answer: 1 },
    { problem: 'Adakah api benda hidup?', options: ['Ya','Tidak (tiada sel)','Tidak pasti'], answer: 1 },
    { problem: 'Benda hidup memerlukan?', options: ['Hanya air','Makanan, air & udara','Hanya udara'], answer: 1 },
    { problem: 'Contoh benda hidup di laut?', options: ['Kapal','Ikan & tumbuhan laut','Batu karang mati'], answer: 1 },
    { problem: 'Bakteri adalah?', options: ['Benda mati','Benda hidup (sangat kecil)','Bukan apa-apa'], answer: 1 },
    { problem: 'Benda hidup boleh berkembang biak bermaksud?', options: ['Melawat','Menghasilkan anak/keturunan','Membesar sahaja'], answer: 1 },
    { problem: 'Biji benih yang ditanam akan?', options: ['Tidak berubah','Tumbuh menjadi pokok','Menjadi batu'], answer: 1 },
    { problem: 'Haiwan yang telah mati adalah?', options: ['Masih hidup','Benda mati','Tidak pasti'], answer: 1 },
    { problem: 'Kayu dari pokok yang dipotong adalah?', options: ['Hidup','Mati','Tidak pasti'], answer: 1 },
    { problem: 'Semua benda hidup akan?', options: ['Kekal selama-lamanya','Mati pada akhirnya','Tidak berubah'], answer: 1 },
    { problem: 'Contoh benda mati di alam semula jadi?', options: ['Burung','Batu, tanah, air','Cacing'], answer: 1 },
    { problem: 'Pokok boleh bergerak apabila?', options: ['Tidak boleh bergerak langsung','Angin bertiup','Dipanaskan'], answer: 1 },
    { problem: 'Makhluk hidup terkecil yang dapat dilihat mata?', options: ['Semut','Hama (mite)','Tiada'], answer: 0 },
    { problem: 'Ciri benda hidup: ia boleh?', options: ['Bergerak, makan, membesar, membiak','Hanya bergerak','Hanya makan'], answer: 0 },
    { problem: 'Adakah tanah benda hidup?', options: ['Ya','Tidak (tetapi mengandungi benda hidup)','Tidak pasti'], answer: 1 },
    { problem: 'Robot adalah benda?', options: ['Hidup','Mati (buatan manusia)','Tidak pasti'], answer: 1 },
    { problem: 'Virus adalah benda hidup atau mati?', options: ['Hidup sepenuhnya','Di antara hidup dan mati','Mati sepenuhnya'], answer: 1 },
  ]}},
];