export const sekolah_english_expansion = [
  {
    title: 'Reading Comprehension - Short Stories',
    type: 'reading',
    emoji: '📖',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: 'Story: "A boy named Ahmed was very lazy. He did not like studying. Every day he played only. His mother often helped him study but Ahmed felt no shame." - What is Ahmed\'s character?', options: ['hardworking', 'lazy', 'brave'], answer: 1 },
      { problem: 'What did Ahmed do every day?', options: ['studied', 'played', 'worked'], answer: 1 },
      { problem: 'Who helped Ahmed study?', options: ['father', 'mother', 'teacher'], answer: 1 },
      { problem: 'What does this story teach?', options: ['playing is good', 'laziness is bad', 'studying is boring'], answer: 1 },
      { problem: 'How many people in the story?', options: ['1', '2', '3'], answer: 1 },
      { problem: 'Did Ahmed feel embarrassed?', options: ['yes', 'no', 'maybe'], answer: 1 },
      { problem: 'What is the story about?', options: ['happy family', 'a lazy boy', 'school work'], answer: 1 },
      { problem: 'What should Ahmed do?', options: ['play more', 'study hard', 'sleep'], answer: 1 },
      { problem: 'What is Ahmed\'s mother\'s character?', options: ['strict', 'patient', 'lazy'], answer: 1 },
      { problem: 'The lesson from this story is?', options: ['playing is important', 'studying is very important', 'mothers are annoying'], answer: 1 },
      { problem: 'The story shows what?', options: ['mother\'s love', 'boy\'s laziness', 'school difficulty'], answer: 0 },
      { problem: 'What is correct about Ahmed?', options: ['he studies hard', 'he is lazy about learning', 'he loves books'], answer: 1 },
      { problem: 'Ahmed\'s future if he continues lazy?', options: ['success', 'failure', 'uncertain'], answer: 1 },
      { problem: 'Mother Ahmed behavior shows?', options: ['anger', 'effort to help', 'giving up'], answer: 1 },
      { problem: 'The main character problem what?', options: ['poverty', 'laziness in studying', 'sickness'], answer: 1 },
      { problem: 'Setting of story where?', options: ['school', 'at home', 'park'], answer: 1 },
      { problem: 'Time of story when?', options: ['past', 'present', 'future'], answer: 0 },
      { problem: 'Ahmed needs what to change?', options: ['punishment', 'effort and discipline', 'new school'], answer: 1 },
      { problem: 'Mother loves Ahmed or not?', options: ['yes', 'no', 'unsure'], answer: 0 },
      { problem: 'Story message is about?', options: ['family problems', 'importance of hard work', 'school rules'], answer: 1 },
    ]}
  },
  {
    title: 'Tenses - Past, Present, Future',
    type: 'multiple_choice',
    emoji: '⏰',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'Present tense example is?', options: ['she played', 'she plays', 'she will play'], answer: 1 },
      { problem: 'Past tense example is?', options: ['I write', 'I wrote', 'I will write'], answer: 1 },
      { problem: 'Future tense example is?', options: ['we study', 'we studied', 'we will study'], answer: 2 },
      { problem: 'She ___ to school every day (verb)?', options: ['go', 'goes', 'went'], answer: 1 },
      { problem: 'Yesterday, I ___ my homework (verb)?', options: ['do', 'does', 'did'], answer: 2 },
      { problem: 'Tomorrow, they ___ to the cinema (verb)?', options: ['go', 'goes', 'will go'], answer: 2 },
      { problem: 'Simple present tense for habit or routine?', options: ['no', 'yes', 'maybe'], answer: 1 },
      { problem: 'Simple past tense for finished action?', options: ['no', 'yes', 'sometimes'], answer: 1 },
      { problem: 'Simple future tense for planned action?', options: ['yes', 'no', 'rarely'], answer: 0 },
      { problem: '"I am eating" is which tense?', options: ['simple present', 'present continuous', 'simple past'], answer: 1 },
      { problem: '"She was reading" is which tense?', options: ['simple past', 'past continuous', 'simple present'], answer: 1 },
      { problem: '"They will be playing" is which tense?', options: ['simple future', 'future continuous', 'present'], answer: 1 },
      { problem: 'He ___ football when it rained (verb)?', options: ['plays', 'played', 'was playing'], answer: 2 },
      { problem: 'By tomorrow, I ___ this book (verb)?', options: ['finish', 'will finish', 'finished'], answer: 1 },
      { problem: '"Has she gone?" is which tense?', options: ['simple present', 'present perfect', 'past continuous'], answer: 1 },
      { problem: 'Present perfect shows?', options: ['finished action', 'recent completed action', 'future action'], answer: 1 },
      { problem: '"They had eaten" is which tense?', options: ['simple past', 'past perfect', 'present perfect'], answer: 1 },
      { problem: 'Which is correct: "I go" or "I goes"?', options: ['I goes', 'I go', 'both correct'], answer: 1 },
      { problem: 'Which is correct: "She went" or "She goes went"?', options: ['She goes went', 'She went', 'both correct'], answer: 1 },
      { problem: 'Modal verbs like "can, must, should" use which form?', options: ['past', 'present', 'base verb'], answer: 2 },
    ]}
  },
  {
    title: 'Vocabulary - Common Words',
    type: 'picture_quiz',
    emoji: '📚',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { image: '🏠', options: ['school', 'house', 'market'], answer: 1 },
      { image: '📚', options: ['pen', 'book', 'desk'], answer: 1 },
      { image: '✏️', options: ['pencil', 'paper', 'eraser'], answer: 0 },
      { image: '🚗', options: ['bus', 'car', 'truck'], answer: 1 },
      { image: '🍎', options: ['banana', 'apple', 'orange'], answer: 1 },
      { image: '🌳', options: ['flower', 'tree', 'grass'], answer: 1 },
      { image: '👨', options: ['woman', 'man', 'child'], answer: 1 },
      { image: '👨‍👩‍👧‍👦', options: ['friends', 'family', 'team'], answer: 1 },
      { image: '🎒', options: ['bag', 'backpack', 'suitcase'], answer: 1 },
      { image: '🏫', options: ['hospital', 'school', 'library'], answer: 1 },
      { image: '⚽', options: ['ball', 'football', 'soccer ball'], answer: 2 },
      { image: '🍕', options: ['pizza', 'bread', 'cake'], answer: 0 },
      { image: '☕', options: ['water', 'coffee', 'juice'], answer: 1 },
      { image: '🎨', options: ['paint', 'art', 'color'], answer: 1 },
      { image: '🎵', options: ['song', 'music', 'sound'], answer: 1 },
      { image: '💻', options: ['computer', 'phone', 'tablet'], answer: 0 },
      { image: '📱', options: ['computer', 'phone', 'camera'], answer: 1 },
      { image: '🕐', options: ['clock', 'watch', 'time'], answer: 1 },
      { image: '📺', options: ['radio', 'television', 'phone'], answer: 1 },
      { image: '🌟', options: ['moon', 'star', 'sun'], answer: 1 },
    ]}
  },
  {
    title: 'Grammar - Subject and Verb Agreement',
    type: 'multiple_choice',
    emoji: '📝',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: 'The cat ___ milk (verb)?', options: ['drink', 'drinks', 'drinking'], answer: 1 },
      { problem: 'The dogs ___ in the park (verb)?', options: ['play', 'plays', 'playing'], answer: 0 },
      { problem: 'She ___ very smart (verb)?', options: ['are', 'is', 'am'], answer: 1 },
      { problem: 'They ___ friends (verb)?', options: ['is', 'are', 'am'], answer: 1 },
      { problem: 'I ___ a student (verb)?', options: ['is', 'are', 'am'], answer: 2 },
      { problem: 'He ___ to school every day (verb)?', options: ['go', 'goes', 'going'], answer: 1 },
      { problem: 'The children ___ happy (verb)?', options: ['is', 'are', 'am'], answer: 1 },
      { problem: 'My mother ___ cooking (verb)?', options: ['is', 'are', 'be'], answer: 0 },
      { problem: 'This book ___ interesting (verb)?', options: ['are', 'is', 'am'], answer: 1 },
      { problem: 'These shoes ___ expensive (verb)?', options: ['is', 'are', 'am'], answer: 1 },
      { problem: 'My friend ___ a teacher (verb)?', options: ['are', 'is', 'am'], answer: 1 },
      { problem: 'The students ___ their homework (verb)?', options: ['do', 'does', 'doing'], answer: 0 },
      { problem: 'She ___ ice cream (verb)?', options: ['like', 'likes', 'liking'], answer: 1 },
      { problem: 'We ___ English (verb)?', options: ['speaks', 'speak', 'speaking'], answer: 1 },
      { problem: 'The bird ___ in the sky (verb)?', options: ['fly', 'flies', 'flying'], answer: 1 },
      { problem: 'Plural subject needs?', options: ['singular verb', 'plural verb', 'no change'], answer: 0 },
      { problem: 'Singular subject needs?', options: ['plural verb', 'singular verb', 'no change'], answer: 1 },
      { problem: 'Subject "I" uses which verb form?', options: ['is', 'are', 'am'], answer: 2 },
      { problem: 'Subject "you" uses which verb form?', options: ['is', 'are', 'am'], answer: 1 },
      { problem: 'In third person singular, add ___ to verb?', options: ['nothing', '-s or -es', '-ed'], answer: 1 },
    ]}
  },
  {
    title: 'Sentence Structure - Word Order',
    type: 'multiple_choice',
    emoji: '🔤',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'Correct sentence order is?', options: ['"go school I to"', '"I go to school"', '"go I to school"'], answer: 1 },
      { problem: '"likes pizza she" correct order?', options: ['yes', 'no', 'maybe'], answer: 1 },
      { problem: 'Basic sentence pattern (SVO)?', options: ['Verb-Subject-Object', 'Subject-Verb-Object', 'Object-Subject-Verb'], answer: 1 },
      { problem: '"The cat drinks milk" - Subject is?', options: ['cat', 'drinks', 'milk'], answer: 0 },
      { problem: '"The cat drinks milk" - Verb is?', options: ['cat', 'drinks', 'milk'], answer: 1 },
      { problem: '"The cat drinks milk" - Object is?', options: ['cat', 'drinks', 'milk'], answer: 2 },
      { problem: 'Question word order starts with?', options: ['Subject', 'Verb', 'Question word'], answer: 2 },
      { problem: 'Negative sentence structure uses?', options: ['no change', 'not/don\'t between subject and verb', 'only negative words'], answer: 1 },
      { problem: '"He does not like coffee" - is this correct?', options: ['no', 'yes', 'maybe'], answer: 1 },
      { problem: 'Adjective usually comes?', options: ['after noun', 'before noun', 'at end'], answer: 1 },
      { problem: '"beautiful girl" - adjective position?', options: ['wrong', 'correct', 'neutral'], answer: 1 },
      { problem: 'Adverb usually comes?', options: ['before subject', 'after verb or end', 'nowhere'], answer: 1 },
      { problem: '"She carefully reads" - correct?', options: ['no', 'yes', 'depends'], answer: 1 },
      { problem: 'Time expression usually goes?', options: ['beginning or end', 'middle', 'nowhere'], answer: 0 },
      { problem: 'Prepositional phrase position?', options: ['anywhere', 'usually end of sentence', 'never'], answer: 1 },
      { problem: '"In the park children play" - correct?', options: ['yes', 'no', 'maybe'], answer: 1 },
      { problem: 'Correct: "Children in the park play"?', options: ['yes', 'no', 'both ok'], answer: 1 },
      { problem: 'When making questions, we use?', options: ['same order', 'invert subject-verb', 'add word'], answer: 1 },
      { problem: '"Do you like chocolate?" - is this correct?', options: ['no', 'yes', 'maybe'], answer: 1 },
      { problem: 'Sentence must have at least?', options: ['subject', 'subject and verb', 'three words'], answer: 1 },
    ]}
  },
  {
    title: 'Dialogue and Conversation',
    type: 'multiple_choice',
    emoji: '💬',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'When greeting someone in morning, say?', options: ['"Good night"', '"Good morning"', '"Good evening"'], answer: 1 },
      { problem: 'When thanking someone, say?', options: ['"Sorry"', '"Thank you"', '"Hello"'], answer: 1 },
      { problem: 'When apologizing, say?', options: ['"Thank you"', '"I\'m sorry"', '"Goodbye"'], answer: 1 },
      { problem: 'When saying goodbye, say?', options: ['"Hello"', '"See you later"', '"Good night" only'], answer: 1 },
      { problem: 'In class, ask teacher, how?', options: ['"Oi teacher"', '"Excuse me, can you explain?"', '"Teach me"'], answer: 1 },
      { problem: 'Ask permission to go out?', options: ['"I\'m going"', '"May I leave?"', '"Let me go"'], answer: 1 },
      { problem: 'Ask for someone\'s name?', options: ['"What is your name?"', '"You?"', '"Name?"'], answer: 0 },
      { problem: 'Ask how someone is?', options: ['"How are you?"', '"You good?"', '"How you?"'], answer: 0 },
      { problem: 'Respond to "How are you?"?', options: ['"How are you?"', '"I\'m fine, thank you"', '"Fine?"'], answer: 1 },
      { problem: 'Ask for directions, how?', options: ['"Where is the bathroom?"', '"Bathroom?"', '"Show me bathroom"'], answer: 0 },
      { problem: 'Polite request uses?', options: ['"Give me"', '"Please give me"', '"Want"'], answer: 1 },
      { problem: 'Offer help by saying?', options: ['"Help?"', '"Can I help you?"', '"Need help?"'], answer: 1 },
      { problem: 'Agree with someone say?', options: ['"No"', '"Yes, I agree"', '"Maybe"'], answer: 1 },
      { problem: 'Disagree politely say?', options: ['"You\'re wrong"', '"I think differently"', '"No way"'], answer: 1 },
      { problem: 'Ask about time, say?', options: ['"Time?"', '"What time is it?"', '"Tell time"'], answer: 1 },
      { problem: 'Invite someone say?', options: ['"Come"', '"Would you like to join me?"', '"Join"'], answer: 1 },
      { problem: 'Congratulate someone say?', options: ['"You did it!"', '"Congratulations!"', '"Well done" or "Congratulations"'], answer: 2 },
      { problem: 'Express surprise say?', options: ['"Wow!" or "Really?"', '"Okay"', '"I know"'], answer: 0 },
      { problem: 'Start conversation with stranger?', options: ['"Hi, how are you?"', '"Introduce"', '"Hello, my name is..."'], answer: 0 },
      { problem: 'End conversation politely say?', options: ['"Bye"', '"It was nice talking to you"', '"Goodbye" or "See you"'], answer: 1 },
    ]}
  },
  {
    title: 'Adjectives and Descriptive Words',
    type: 'multiple_choice',
    emoji: '✨',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '"Beautiful" describes what?', options: ['action', 'quality/appearance', 'person'], answer: 1 },
      { problem: '"Smart" is adjective for?', options: ['intelligence', 'movement', 'sound'], answer: 0 },
      { problem: 'Adjectives come usually?', options: ['after noun', 'before noun', 'anywhere'], answer: 1 },
      { problem: '"A big house" - where is adjective?', options: ['after house', 'before house', 'at end'], answer: 1 },
      { problem: 'Opposite of "cold" is?', options: ['ice', 'hot', 'warm'], answer: 1 },
      { problem: 'Opposite of "big" is?', options: ['large', 'small', 'large'], answer: 1 },
      { problem: 'Opposite of "happy" is?', options: ['sad', 'angry', 'tired'], answer: 0 },
      { problem: 'Comparative form of "tall"?', options: ['taller', 'tallest', 'more tall'], answer: 0 },
      { problem: 'Superlative form of "fast"?', options: ['faster', 'fastest', 'more fast'], answer: 1 },
      { problem: 'Use "more" for adjectives?', options: ['all', 'short ones', 'long ones'], answer: 2 },
      { problem: '"Beautiful" becomes?', options: ['more beautiful', 'beautifuler', 'beautifullest'], answer: 0 },
      { problem: 'Adjective +"er" for?', options: ['superlative', 'comparative', 'none'], answer: 1 },
      { problem: 'Adjective +"est" for?', options: ['comparative', 'superlative', 'none'], answer: 1 },
      { problem: '"Good" comparative is?', options: ['gooder', 'better', 'more good'], answer: 1 },
      { problem: '"Bad" superlative is?', options: ['baddest', 'worse', 'worst'], answer: 2 },
      { problem: 'Adjectives modify?', options: ['verbs', 'nouns', 'adjectives'], answer: 1 },
      { problem: 'Color words like "red" are?', options: ['verbs', 'adjectives', 'nouns'], answer: 1 },
      { problem: 'Number words like "five" are?', options: ['adjectives', 'nouns', 'verbs'], answer: 0 },
      { problem: 'Can adjective stand alone?', options: ['yes', 'no', 'sometimes'], answer: 2 },
      { problem: '"The tall, dark stranger" - how many adjectives?', options: ['1', '2', '3'], answer: 2 },
    ]}
  },
  {
    title: 'Prepositions - Location and Time',
    type: 'multiple_choice',
    emoji: '📍',
    difficulty: 'easy',
    darjah: 2,
    gameData: { questions: [
      { problem: 'The book is ___ the table (preposition)?', options: ['in', 'on', 'at'], answer: 1 },
      { problem: 'The pen is ___ the bag (preposition)?', options: ['on', 'in', 'at'], answer: 1 },
      { problem: 'I am ___ school (preposition)?', options: ['in', 'on', 'at'], answer: 2 },
      { problem: 'Meet me ___ 3 o\'clock (preposition)?', options: ['in', 'on', 'at'], answer: 2 },
      { problem: 'The picture is ___ the wall (preposition)?', options: ['in', 'on', 'at'], answer: 1 },
      { problem: 'I live ___ Malaysia (preposition)?', options: ['in', 'on', 'at'], answer: 0 },
      { problem: 'The cat is ___ the chair (preposition)?', options: ['under', 'on', 'in'], answer: 0 },
      { problem: 'The ball is ___ the box (preposition)?', options: ['under', 'in', 'on'], answer: 1 },
      { problem: 'The lamp is ___ the desk (preposition)?', options: ['on', 'under', 'in'], answer: 0 },
      { problem: 'The garden is ___ the house (preposition)?', options: ['in', 'behind', 'above'], answer: 1 },
      { problem: 'I go ___ my friend\'s house (preposition)?', options: ['in', 'to', 'at'], answer: 1 },
      { problem: 'We come ___ school ___ 7 am (prepositions)?', options: ['to, in', 'at, on', 'to, at'], answer: 2 },
      { problem: 'The fly is ___ my head (preposition)?', options: ['above', 'on', 'in'], answer: 0 },
      { problem: 'I work ___ a hospital (preposition)?', options: ['in', 'on', 'at'], answer: 0 },
      { problem: 'The child sits ___ his mother (preposition)?', options: ['near', 'beside', 'next to'], answer: 1 },
      { problem: 'We meet ___ 5pm (preposition)?', options: ['in', 'on', 'at'], answer: 2 },
      { problem: 'The stars are ___ the sky (preposition)?', options: ['in', 'above', 'below'], answer: 0 },
      { problem: 'I go to bed ___ night (preposition)?', options: ['in', 'on', 'at'], answer: 0 },
      { problem: 'Classes start ___ Monday (preposition)?', options: ['in', 'on', 'at'], answer: 1 },
      { problem: 'Preposition shows relationship between?', options: ['words', 'nouns/pronouns and other words', 'verbs'], answer: 1 },
    ]}
  },
  {
    title: 'Pronouns - Subject and Object',
    type: 'multiple_choice',
    emoji: '👤',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: 'Subject pronoun "he" refers to?', options: ['female', 'male', 'object'], answer: 1 },
      { problem: 'Subject pronoun "she" refers to?', options: ['male', 'female', 'thing'], answer: 1 },
      { problem: 'Object pronoun for "John" is?', options: ['he', 'him', 'his'], answer: 1 },
      { problem: 'Object pronoun for "Mary" is?', options: ['she', 'her', 'hers'], answer: 1 },
      { problem: '"I" is which type?', options: ['object', 'subject', 'possessive'], answer: 1 },
      { problem: '"Me" is which type?', options: ['subject', 'object', 'possessive'], answer: 1 },
      { problem: 'Correct: "Him and I go" or "He and I go"?', options: ['Him and I', 'He and I', 'both'], answer: 1 },
      { problem: 'Correct: "She gave it to me" - which pronoun?', options: ['subject', 'object', 'both'], answer: 1 },
      { problem: '"We" is plural form of?', options: ['I', 'you', 'he'], answer: 0 },
      { problem: '"They" refers to?', options: ['one thing', 'one person', 'more than one'], answer: 2 },
      { problem: 'Possessive pronoun "his"?', options: ['is object', 'shows ownership', 'is subject'], answer: 1 },
      { problem: 'Possessive pronoun "her"?', options: ['is subject', 'shows ownership', 'is object'], answer: 1 },
      { problem: '"My" is?', options: ['object pronoun', 'subject pronoun', 'possessive pronoun'], answer: 2 },
      { problem: 'Reflexive pronoun "himself"?', options: ['refers to others', 'refers back to subject', 'object'], answer: 1 },
      { problem: '"Herself" is?', options: ['object', 'reflexive', 'subject'], answer: 1 },
      { problem: '"This" and "that" are?', options: ['pronouns', 'demonstrative words', 'adjectives'], answer: 1 },
      { problem: '"Who" is used for?', options: ['objects', 'people', 'things'], answer: 1 },
      { problem: '"Whom" is used for?', options: ['subject', 'object person', 'things'], answer: 1 },
      { problem: 'Relative pronoun "which" for?', options: ['people', 'things', 'verbs'], answer: 1 },
      { problem: 'Relative pronoun "who" for?', options: ['things', 'people', 'places'], answer: 1 },
    ]}
  },
  {
    title: 'Verbs - Action Words',
    type: 'multiple_choice',
    emoji: '⚡',
    difficulty: 'medium',
    darjah: 3,
    gameData: { questions: [
      { problem: '"Run" means?', options: ['slow', 'fast movement with legs', 'walking'], answer: 1 },
      { problem: '"Sleep" means?', options: ['eat', 'rest at night', 'work'], answer: 1 },
      { problem: '"Eat" means?', options: ['drink', 'sleep', 'consume food'], answer: 2 },
      { problem: '"Write" means?', options: ['read', 'put words on paper', 'speak'], answer: 1 },
      { problem: '"Listen" means?', options: ['hear sounds', 'speak', 'look'], answer: 0 },
      { problem: '"Watch" means?', options: ['listen', 'look at', 'touch'], answer: 1 },
      { problem: '"Play" means?', options: ['work', 'have fun with activity', 'sleep'], answer: 1 },
      { problem: '"Study" means?', options: ['teach', 'learn by reading', 'think'], answer: 1 },
      { problem: '"Help" means?', options: ['hurt', 'assist', 'ignore'], answer: 1 },
      { problem: '"Break" means?', options: ['fix', 'damage', 'make'], answer: 1 },
      { problem: '"Cook" means?', options: ['eat', 'prepare food by heat', 'serve'], answer: 1 },
      { problem: '"Jump" means?', options: ['run', 'leap in air', 'fall'], answer: 1 },
      { problem: '"Swim" means?', options: ['walk', 'move through water', 'float'], answer: 1 },
      { problem: '"Climb" means?', options: ['fall', 'go up', 'descend'], answer: 1 },
      { problem: '"Teach" means?', options: ['learn', 'give knowledge', 'study'], answer: 1 },
      { problem: '"Sing" means?', options: ['speak', 'make music with voice', 'whisper'], answer: 1 },
      { problem: '"Dance" means?', options: ['walk', 'move rhythmically', 'stand'], answer: 1 },
      { problem: 'Regular verb adds?', options: ['-ing', '-ed', '-s'], answer: 1 },
      { problem: 'Irregular verb form of "go"?', options: ['goed', 'gooed', 'went'], answer: 2 },
      { problem: 'Irregular verb form of "eat"?', options: ['eated', 'ate', 'eating'], answer: 1 },
    ]}
  },
  {
    title: 'Questions - Forming and Answering',
    type: 'multiple_choice',
    emoji: '❓',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'To ask "what", question word?', options: ['which', 'what', 'why'], answer: 1 },
      { problem: 'To ask "reason", question word?', options: ['why', 'where', 'when'], answer: 0 },
      { problem: 'To ask "place", question word?', options: ['when', 'where', 'who'], answer: 1 },
      { problem: 'To ask "person", question word?', options: ['what', 'where', 'who'], answer: 2 },
      { problem: 'To ask "time", question word?', options: ['why', 'when', 'how'], answer: 1 },
      { problem: 'Question "Do you like..." is?', options: ['yes-no question', 'information question', 'command'], answer: 0 },
      { problem: '"What color..." is?', options: ['yes-no', 'information question', 'exclamation'], answer: 1 },
      { problem: 'Question uses?', options: ['statement', 'question mark', 'period'], answer: 1 },
      { problem: 'In question, verb comes?', options: ['before subject', 'after subject', 'nowhere'], answer: 0 },
      { problem: '"Does she like coffee?" - answer?', options: ['"Yes, she does"', '"She does"', 'yes/no answer'], answer: 0 },
      { problem: '"Where do you live?" - answer type?', options: ['yes/no', 'information', 'command'], answer: 1 },
      { problem: '"How are you?" - answer?', options: ['"Yes"', '"I am fine"', '"No"'], answer: 1 },
      { problem: 'Tag question like "isn\'t it?" is?', options: ['statement', 'yes-no question', 'command'], answer: 1 },
      { problem: 'To form yes-no question, use?', options: ['-ing', 'do/does/did', 'nothing'], answer: 1 },
      { problem: '"Will you help me?" - is this question?', options: ['no', 'yes', 'maybe'], answer: 1 },
      { problem: 'Polite question uses?', options: ['"Can you"', '"You can"', '"Can I"'], answer: 0 },
      { problem: '"How many" asks about?', options: ['quality', 'quantity', 'reason'], answer: 1 },
      { problem: '"How much" asks about?', options: ['number', 'amount/price', 'size'], answer: 1 },
      { problem: 'Question "Could you help?" shows?', options: ['command', 'polite request', 'statement'], answer: 1 },
      { problem: 'Answer to "What time is it?" is?', options: ['"It\'s 3 pm"', '"Yes, it is"', '"No"'], answer: 0 },
    ]}
  },
  {
    title: 'Modals - Can, Could, Should, Must',
    type: 'multiple_choice',
    emoji: '🔒',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: '"Can" means?', options: ['must', 'have ability', 'should'], answer: 1 },
      { problem: '"Must" means?', options: ['maybe', 'necessary', 'possible'], answer: 1 },
      { problem: '"Should" means?', options: ['must', 'recommend/advice', 'can'], answer: 1 },
      { problem: '"Could" is?', options: ['present of can', 'past of can', 'must'], answer: 1 },
      { problem: '"I can swim" means?', options: ['I must', 'I am able to', 'I should'], answer: 1 },
      { problem: '"You must study" means?', options: ['optional', 'it is necessary', 'maybe'], answer: 1 },
      { problem: '"Should I go?" means?', options: ['must I', 'is it advised', 'can I'], answer: 1 },
      { problem: '"May I ask?" uses modal?', options: ['can', 'may', 'might'], answer: 1 },
      { problem: '"Might" shows?', options: ['ability', 'possibility', 'necessity'], answer: 1 },
      { problem: '"Would you help?" is?', options: ['ability', 'polite request', 'necessity'], answer: 1 },
      { problem: 'Modal verb + what?', options: ['-ed', 'base verb', '-ing'], answer: 1 },
      { problem: '"He can speak English" - correct?', options: ['no', 'yes', 'maybe'], answer: 1 },
      { problem: '"She must goes" - correct?', options: ['yes', 'no', 'both'], answer: 1 },
      { problem: 'Correct: "You should study"?', options: ['no', 'yes', 'unclear'], answer: 1 },
      { problem: '"Can\'t" means?', options: ['must not', 'not able to', 'possible'], answer: 1 },
      { problem: '"Shouldn\'t" means?', options: ['must', 'not recommended', 'can'], answer: 1 },
      { problem: '"Mustn\'t" means?', options: ['don\'t have to', 'you must not', 'maybe'], answer: 1 },
      { problem: '"Don\'t have to" vs "Must not"?', options: ['same', 'different meanings', 'unclear'], answer: 1 },
      { problem: '"I may leave" shows?', options: ['permission', 'possibility', 'both'], answer: 2 },
      { problem: '"Could you pass salt?" is?', options: ['past ability', 'polite request', 'command'], answer: 1 },
    ]}
  },
  {
    title: 'Writing - Paragraph Structure',
    type: 'multiple_choice',
    emoji: '✍️',
    difficulty: 'medium',
    darjah: 4,
    gameData: { questions: [
      { problem: 'Good paragraph has?', options: ['no structure', 'topic sentence and supporting details', 'random ideas'], answer: 1 },
      { problem: 'Topic sentence usually at?', options: ['end', 'beginning', 'middle'], answer: 1 },
      { problem: 'Topic sentence tells?', options: ['random info', 'main idea', 'conclusion'], answer: 1 },
      { problem: 'Supporting sentences provide?', options: ['heading', 'details/examples', 'ending'], answer: 1 },
      { problem: 'Concluding sentence?', options: ['starts paragraph', 'ends and sums up', 'in middle'], answer: 1 },
      { problem: 'Paragraph unity means?', options: ['different topics', 'all about one idea', 'no connection'], answer: 1 },
      { problem: 'Good paragraph length?', options: ['1 sentence', '3-8 sentences typically', 'page long'], answer: 1 },
      { problem: 'Coherence in writing means?', options: ['sentences don\'t connect', 'ideas flow logically', 'random order'], answer: 1 },
      { problem: 'Transition words like "because"?', options: ['confuse', 'connect ideas', 'separate'], answer: 1 },
      { problem: 'Examples "Furthermore" and "However"?', options: ['subjects', 'transition words', 'verbs'], answer: 1 },
      { problem: 'Topic sentence "I like sports"?', options: ['too specific', 'too general', 'perfect'], answer: 1 },
      { problem: 'Good writing uses?', options: ['all simple sentences', 'variety of sentences', 'all long'], answer: 1 },
      { problem: 'Supporting detail example?', options: ['main idea', 'proof/specific fact', 'conclusion'], answer: 1 },
      { problem: 'Indentation at paragraph start?', options: ['not needed', 'shows new paragraph', 'wrong'], answer: 1 },
      { problem: 'Each paragraph is about?', options: ['same topic', 'different main idea', 'nothing'], answer: 1 },
      { problem: 'Essay needs how many paragraphs minimum?', options: ['1', '3-5', '10'], answer: 1 },
      { problem: 'Introduction paragraph shows?', options: ['conclusion', 'main topic', 'ending'], answer: 1 },
      { problem: 'Body paragraphs contain?', options: ['ending', 'supporting details', 'heading'], answer: 1 },
      { problem: 'Conclusion paragraph does?', options: ['starts essay', 'sums up main points', 'adds new idea'], answer: 1 },
      { problem: 'Title of paragraph placed?', options: ['middle', 'top', 'bottom'], answer: 1 },
    ]}
  },
];