export const prasekolah_english = [
  { title: 'ABC Letters - A to H', type: 'letter_match', emoji: '🔤', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Apple', options: ['A','B','C','D'], answer: 0 },
    { letter: 'B', emoji: '🐦', word: 'Bird', options: ['A','B','C','D'], answer: 1 },
    { letter: 'C', emoji: '🐱', word: 'Cat', options: ['A','B','C','D'], answer: 2 },
    { letter: 'D', emoji: '🐕', word: 'Dog', options: ['A','B','C','D'], answer: 3 },
    { letter: 'E', emoji: '🐘', word: 'Elephant', options: ['D','E','F','G'], answer: 1 },
    { letter: 'F', emoji: '🐟', word: 'Fish', options: ['D','E','F','G'], answer: 2 },
    { letter: 'G', emoji: '🦒', word: 'Giraffe', options: ['E','F','G','H'], answer: 2 },
    { letter: 'H', emoji: '🐎', word: 'Horse', options: ['F','G','H','I'], answer: 2 },
  ]}},
  { title: 'Vowels A, E, I, O, U', type: 'letter_match', emoji: '🅰️', difficulty: 'easy', gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Apple', options: ['A','E','I','O'], answer: 0 },
    { letter: 'E', emoji: '🥚', word: 'Egg', options: ['A','E','I','O'], answer: 1 },
    { letter: 'I', emoji: '🍦', word: 'Ice Cream', options: ['A','E','I','O'], answer: 2 },
    { letter: 'O', emoji: '🍊', word: 'Orange', options: ['A','E','I','O'], answer: 3 },
    { letter: 'U', emoji: '☂️', word: 'Umbrella', options: ['I','U','E','O'], answer: 1 },
    { letter: 'A', emoji: '🐊', word: 'Alligator', options: ['U','A','I','O'], answer: 1 },
    { letter: 'E', emoji: '🦅', word: 'Eagle', options: ['A','E','U','I'], answer: 1 },
    { letter: 'I', emoji: '🐛', word: 'Insect', options: ['U','O','I','A'], answer: 2 },
  ]}},
  { title: 'Animal Names', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', gameData: { questions: [
    { image: '🐱', options: ['Cat','Dog','Rabbit'], answer: 0 },
    { image: '🐶', options: ['Cat','Dog','Bird'], answer: 1 },
    { image: '🦁', options: ['Lion','Tiger','Bear'], answer: 0 },
    { image: '🐘', options: ['Elephant','Horse','Zebra'], answer: 0 },
    { image: '🐧', options: ['Penguin','Chicken','Duck'], answer: 0 },
    { image: '🦒', options: ['Giraffe','Deer','Horse'], answer: 0 },
    { image: '🐻', options: ['Bear','Wolf','Lion'], answer: 0 },
    { image: '🦓', options: ['Zebra','Horse','Donkey'], answer: 0 },
  ]}},
  { title: 'Fruit Names', type: 'picture_quiz', emoji: '🍓', difficulty: 'easy', gameData: { questions: [
    { image: '🍎', options: ['Apple','Orange','Banana'], answer: 0 },
    { image: '🍊', options: ['Apple','Orange','Mango'], answer: 1 },
    { image: '🍌', options: ['Banana','Papaya','Mango'], answer: 0 },
    { image: '🍇', options: ['Grapes','Strawberry','Cherry'], answer: 0 },
    { image: '🍓', options: ['Grapes','Strawberry','Apple'], answer: 1 },
    { image: '🍉', options: ['Watermelon','Papaya','Mango'], answer: 0 },
    { image: '🥭', options: ['Papaya','Mango','Durian'], answer: 1 },
    { image: '🍋', options: ['Lime','Orange','Lemon'], answer: 2 },
  ]}},
  { title: 'Color Names', type: 'picture_quiz', emoji: '🌈', difficulty: 'easy', gameData: { questions: [
    { image: '🔴', options: ['Red','Blue','Green'], answer: 0 },
    { image: '🔵', options: ['Red','Blue','Yellow'], answer: 1 },
    { image: '🟢', options: ['Purple','Green','Orange'], answer: 1 },
    { image: '🟡', options: ['Yellow','Orange','White'], answer: 0 },
    { image: '🟠', options: ['Yellow','Orange','Red'], answer: 1 },
    { image: '💜', options: ['Purple','Pink','Blue'], answer: 0 },
    { image: '🤎', options: ['Black','Brown','Grey'], answer: 1 },
    { image: '⚪', options: ['White','Black','Grey'], answer: 0 },
  ]}},
  { title: 'Body Parts', type: 'picture_quiz', emoji: '🧒', difficulty: 'easy', gameData: { questions: [
    { image: '👁️', options: ['Eye','Nose','Ear'], answer: 0 },
    { image: '👃', options: ['Eye','Nose','Mouth'], answer: 1 },
    { image: '👂', options: ['Eye','Nose','Ear'], answer: 2 },
    { image: '👄', options: ['Mouth','Nose','Lip'], answer: 0 },
    { image: '✋', options: ['Foot','Hand','Leg'], answer: 1 },
    { image: '🦶', options: ['Foot','Hand','Arm'], answer: 0 },
    { image: '🦵', options: ['Arm','Leg','Hand'], answer: 1 },
    { image: '🧠', options: ['Heart','Brain','Lung'], answer: 1 },
  ]}},
  { title: 'Letters I to P', type: 'letter_match', emoji: '🔡', difficulty: 'easy', gameData: { questions: [
    { letter: 'I', emoji: '🐛', word: 'Insect', options: ['I','J','K','L'], answer: 0 },
    { letter: 'J', emoji: '🤹', word: 'Juggler', options: ['I','J','K','L'], answer: 1 },
    { letter: 'K', emoji: '🪀', word: 'Kite', options: ['I','J','K','L'], answer: 2 },
    { letter: 'L', emoji: '🦁', word: 'Lion', options: ['I','J','K','L'], answer: 3 },
    { letter: 'M', emoji: '🌙', word: 'Moon', options: ['M','N','O','P'], answer: 0 },
    { letter: 'N', emoji: '🥜', word: 'Nut', options: ['M','N','O','P'], answer: 1 },
    { letter: 'O', emoji: '🦉', word: 'Owl', options: ['M','N','O','P'], answer: 2 },
    { letter: 'P', emoji: '🐼', word: 'Panda', options: ['M','N','O','P'], answer: 3 },
  ]}},
  { title: 'Letters Q to Z', type: 'letter_match', emoji: '🔠', difficulty: 'easy', gameData: { questions: [
    { letter: 'Q', emoji: '👸', word: 'Queen', options: ['Q','R','S','T'], answer: 0 },
    { letter: 'R', emoji: '🌹', word: 'Rose', options: ['Q','R','S','T'], answer: 1 },
    { letter: 'S', emoji: '⭐', word: 'Star', options: ['Q','R','S','T'], answer: 2 },
    { letter: 'T', emoji: '🐯', word: 'Tiger', options: ['Q','R','S','T'], answer: 3 },
    { letter: 'U', emoji: '☂️', word: 'Umbrella', options: ['U','V','W','X'], answer: 0 },
    { letter: 'V', emoji: '🎻', word: 'Violin', options: ['U','V','W','X'], answer: 1 },
    { letter: 'W', emoji: '🐋', word: 'Whale', options: ['U','V','W','X'], answer: 2 },
    { letter: 'Y', emoji: '🪀', word: 'Yo-yo', options: ['W','X','Y','Z'], answer: 2 },
  ]}},
  { title: 'Simple Words - Things', type: 'picture_quiz', emoji: '🧸', difficulty: 'easy', gameData: { questions: [
    { image: '🏠', options: ['House','School','Shop'], answer: 0 },
    { image: '🚗', options: ['Bus','Car','Truck'], answer: 1 },
    { image: '📚', options: ['Book','Pencil','Paper'], answer: 0 },
    { image: '🎒', options: ['Bag','Book','Box'], answer: 0 },
    { image: '✏️', options: ['Pen','Pencil','Ruler'], answer: 1 },
    { image: '🍽️', options: ['Plate','Bowl','Cup'], answer: 0 },
    { image: '🛏️', options: ['Bed','Chair','Table'], answer: 0 },
    { image: '🪑', options: ['Table','Chair','Cupboard'], answer: 1 },
  ]}},
  { title: 'Numbers 1-10 in English', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐', options: ['One','Two','Three'], answer: 0 },
    { problem: '⭐⭐', options: ['One','Two','Three'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['Two','Three','Four'], answer: 1 },
    { problem: '⭐⭐⭐⭐', options: ['Three','Four','Five'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['Four','Five','Six'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['Five','Six','Seven'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['Six','Seven','Eight'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['Seven','Eight','Nine'], answer: 1 },
  ]}},
  { title: 'Clothing Names', type: 'picture_quiz', emoji: '👕', difficulty: 'easy', gameData: { questions: [
    { image: '👕', options: ['Shirt','Pants','Shoes'], answer: 0 },
    { image: '👖', options: ['Shirt','Pants','Hat'], answer: 1 },
    { image: '👟', options: ['Sandal','Shoes','Socks'], answer: 1 },
    { image: '🧦', options: ['Socks','Shoes','Gloves'], answer: 0 },
    { image: '🧢', options: ['Hat','Scarf','Hood'], answer: 0 },
    { image: '👗', options: ['Shirt','Dress','Pants'], answer: 1 },
    { image: '🧥', options: ['Jacket','Shirt','Pants'], answer: 0 },
    { image: '👔', options: ['T-shirt','Shirt','Blouse'], answer: 1 },
  ]}},
  { title: 'Transport Names', type: 'picture_quiz', emoji: '🚗', difficulty: 'easy', gameData: { questions: [
    { image: '🚗', options: ['Car','Bus','Truck'], answer: 0 },
    { image: '🚌', options: ['Car','Bus','Van'], answer: 1 },
    { image: '✈️', options: ['Airplane','Helicopter','Ship'], answer: 0 },
    { image: '🚢', options: ['Boat','Ferry','Ship'], answer: 2 },
    { image: '🚂', options: ['LRT','Train','Tram'], answer: 1 },
    { image: '🏍️', options: ['Bicycle','Motorcycle','Car'], answer: 1 },
    { image: '🚲', options: ['Bicycle','Motorcycle','Trolley'], answer: 0 },
    { image: '🚁', options: ['Airplane','Helicopter','Drone'], answer: 1 },
  ]}},
  { title: 'Rooms in a House', type: 'picture_quiz', emoji: '🏠', difficulty: 'easy', gameData: { questions: [
    { image: '🛋️', options: ['Bedroom','Living Room','Kitchen'], answer: 1 },
    { image: '🛁', options: ['Bathroom','Bedroom','Kitchen'], answer: 0 },
    { image: '🍳', options: ['Dining Room','Kitchen','Store'], answer: 1 },
    { image: '🛏️', options: ['Bedroom','Living Room','Bathroom'], answer: 0 },
    { image: '🍽️', options: ['Kitchen','Dining Room','Living Room'], answer: 1 },
    { image: '📺', options: ['Bedroom','Living Room','Kitchen'], answer: 1 },
    { image: '📚', options: ['Study Room','Bedroom','Living Room'], answer: 0 },
    { image: '🚪', options: ['Window','Door','Gate'], answer: 1 },
  ]}},
  { title: 'Food Names', type: 'picture_quiz', emoji: '🍜', difficulty: 'easy', gameData: { questions: [
    { image: '🍚', options: ['Rice','Bread','Noodle'], answer: 0 },
    { image: '🍞', options: ['Rice','Bread','Biscuit'], answer: 1 },
    { image: '🍜', options: ['Vermicelli','Noodle','Spaghetti'], answer: 1 },
    { image: '🍳', options: ['Fried Egg','Boiled Egg','Scrambled Egg'], answer: 0 },
    { image: '🥘', options: ['Soup','Curry','Stew'], answer: 1 },
    { image: '🍰', options: ['Cake','Kuih','Donut'], answer: 0 },
    { image: '🧇', options: ['Waffle','Pancake','Crepe'], answer: 0 },
    { image: '🥪', options: ['Sandwich','Burger','Toast'], answer: 0 },
  ]}},
  { title: 'School Supplies', type: 'picture_quiz', emoji: '✏️', difficulty: 'easy', gameData: { questions: [
    { image: '✏️', options: ['Pencil','Pen','Crayon'], answer: 0 },
    { image: '📏', options: ['Ruler','Scissors','Eraser'], answer: 0 },
    { image: '🖊️', options: ['Pencil','Pen','Marker'], answer: 1 },
    { image: '📚', options: ['Book','Magazine','Note'], answer: 0 },
    { image: '🎒', options: ['School Bag','Handbag','Sports Bag'], answer: 0 },
    { image: '🖍️', options: ['Coloured Pencil','Crayon','Pen'], answer: 1 },
    { image: '📐', options: ['Set Square','Ruler','Compass'], answer: 0 },
    { image: '📓', options: ['Exercise Book','Textbook','Diary'], answer: 0 },
  ]}},
  { title: 'Feelings & Emotions', type: 'picture_quiz', emoji: '😊', difficulty: 'easy', gameData: { questions: [
    { image: '😊', options: ['Happy','Sad','Angry'], answer: 0 },
    { image: '😢', options: ['Happy','Sad','Scared'], answer: 1 },
    { image: '😠', options: ['Happy','Tired','Angry'], answer: 2 },
    { image: '😨', options: ['Scared','Angry','Happy'], answer: 0 },
    { image: '😴', options: ['Sad','Tired','Bored'], answer: 1 },
    { image: '😂', options: ['Laughing','Crying','Smiling'], answer: 0 },
    { image: '🤗', options: ['Hugging','Loving','Happy'], answer: 0 },
    { image: '😍', options: ['Surprised','Loving','Happy'], answer: 1 },
  ]}},
  { title: 'Opposites in English', type: 'multiple_choice', emoji: '↔️', difficulty: 'easy', gameData: { questions: [
    { problem: 'Opposite of "big"?', options: ['small','large','tall'], answer: 0 },
    { problem: 'Opposite of "hot"?', options: ['warm','cold','cool'], answer: 1 },
    { problem: 'Opposite of "happy"?', options: ['glad','sad','angry'], answer: 1 },
    { problem: 'Opposite of "day"?', options: ['evening','night','morning'], answer: 1 },
    { problem: 'Opposite of "fast"?', options: ['quick','slow','stop'], answer: 1 },
    { problem: 'Opposite of "up"?', options: ['away','down','side'], answer: 1 },
    { problem: 'Opposite of "open"?', options: ['shut','close','closed'], answer: 2 },
    { problem: 'Opposite of "clean"?', options: ['wet','dirty','messy'], answer: 1 },
  ]}},
  { title: 'Simple Sentences - Fill in Blank', type: 'multiple_choice', emoji: '📝', difficulty: 'easy', gameData: { questions: [
    { problem: 'I ___ to school every day.', options: ['goes','go','gone'], answer: 1 },
    { problem: 'She ___ a cat.', options: ['have','has','had'], answer: 1 },
    { problem: 'They ___ playing football.', options: ['is','am','are'], answer: 2 },
    { problem: 'The dog ___ very fast.', options: ['run','runs','ran'], answer: 1 },
    { problem: 'I ___ rice for lunch.', options: ['eats','eating','eat'], answer: 2 },
    { problem: 'We ___ friends.', options: ['is','am','are'], answer: 2 },
    { problem: 'He ___ a book.', options: ['read','reads','reading'], answer: 1 },
    { problem: 'The bird ___ in the sky.', options: ['fly','flying','flies'], answer: 2 },
  ]}},
  { title: 'Days of the Week', type: 'multiple_choice', emoji: '📅', difficulty: 'easy', gameData: { questions: [
    { problem: 'First day of the week?', options: ['Monday','Sunday','Saturday'], answer: 1 },
    { problem: 'Day after Monday?', options: ['Sunday','Wednesday','Tuesday'], answer: 2 },
    { problem: 'Middle of the week?', options: ['Tuesday','Wednesday','Thursday'], answer: 1 },
    { problem: 'Day before Saturday?', options: ['Thursday','Friday','Sunday'], answer: 1 },
    { problem: 'Last day of the week?', options: ['Saturday','Sunday','Friday'], answer: 1 },
    { problem: 'School days are?', options: ['Sat & Sun','Mon to Fri','Wed & Thu'], answer: 1 },
    { problem: 'Weekend days?', options: ['Mon & Tue','Sat & Sun','Fri & Sat'], answer: 1 },
    { problem: 'Day after Wednesday?', options: ['Tuesday','Thursday','Friday'], answer: 1 },
  ]}},
  { title: 'Numbers 11-20', type: 'number_match', emoji: '🔢', difficulty: 'easy', gameData: { questions: [
    { problem: '⭐×11', options: ['Ten','Eleven','Twelve'], answer: 1 },
    { problem: '⭐×12', options: ['Eleven','Twelve','Thirteen'], answer: 1 },
    { problem: '⭐×13', options: ['Twelve','Thirteen','Fourteen'], answer: 1 },
    { problem: '⭐×15', options: ['Fourteen','Fifteen','Sixteen'], answer: 1 },
    { problem: '⭐×16', options: ['Fifteen','Sixteen','Seventeen'], answer: 1 },
    { problem: '⭐×18', options: ['Seventeen','Eighteen','Nineteen'], answer: 1 },
    { problem: '⭐×19', options: ['Eighteen','Nineteen','Twenty'], answer: 1 },
    { problem: '⭐×20', options: ['Nineteen','Twenty','Twenty-one'], answer: 1 },
  ]}},
  { title: 'Vegetables & Plants', type: 'picture_quiz', emoji: '🥦', difficulty: 'easy', gameData: { questions: [
    { image: '🥕', options: ['Carrot','Tomato','Onion'], answer: 0 },
    { image: '🍅', options: ['Carrot','Tomato','Papaya'], answer: 1 },
    { image: '🥦', options: ['Broccoli','Cabbage','Spinach'], answer: 0 },
    { image: '🌽', options: ['Corn','Cucumber','Pumpkin'], answer: 0 },
    { image: '🥒', options: ['Cucumber','Carrot','Pumpkin'], answer: 0 },
    { image: '🧅', options: ['Onion','Potato','Ginger'], answer: 0 },
    { image: '🥔', options: ['Sweet Potato','Potato','Carrot'], answer: 1 },
    { image: '🌶️', options: ['Chili','Tomato','Carrot'], answer: 0 },
  ]}},
  { title: 'Months of the Year', type: 'multiple_choice', emoji: '📆', difficulty: 'easy', gameData: { questions: [
    { problem: 'First month of the year?', options: ['February','January','March'], answer: 1 },
    { problem: 'Second month of the year?', options: ['January','February','March'], answer: 1 },
    { problem: 'How many months in a year?', options: ['10','11','12'], answer: 2 },
    { problem: 'Last month of the year?', options: ['November','October','December'], answer: 2 },
    { problem: 'Month after April?', options: ['March','May','June'], answer: 1 },
    { problem: '6th month?', options: ['May','June','July'], answer: 1 },
    { problem: 'Month before December?', options: ['October','November','September'], answer: 1 },
    { problem: 'Month with Valentine\'s Day?', options: ['January','February','March'], answer: 1 },
  ]}},
  { title: 'Family Members', type: 'picture_quiz', emoji: '👨‍👩‍👧‍👦', difficulty: 'easy', gameData: { questions: [
    { image: '👨', options: ['Father','Mother','Brother'], answer: 0 },
    { image: '👩', options: ['Father','Mother','Sister'], answer: 1 },
    { image: '👦', options: ['Brother','Boy','Grandfather'], answer: 0 },
    { image: '👧', options: ['Sister','Grandmother','Mother'], answer: 0 },
    { image: '👴', options: ['Father','Grandfather','Uncle'], answer: 1 },
    { image: '👵', options: ['Mother','Grandmother','Aunt'], answer: 1 },
    { image: '👶', options: ['Baby','Child','Toddler'], answer: 0 },
    { image: '👨‍👩‍👧', options: ['Family','Friends','Neighbours'], answer: 0 },
  ]}},
  { title: 'Action Words (Verbs)', type: 'picture_quiz', emoji: '🏃', difficulty: 'easy', gameData: { questions: [
    { image: '🏃', options: ['Run','Jump','Swim'], answer: 0 },
    { image: '🦘', options: ['Run','Jump','Fly'], answer: 1 },
    { image: '🏊', options: ['Run','Walk','Swim'], answer: 2 },
    { image: '✈️', options: ['Swim','Fly','Jump'], answer: 1 },
    { image: '📖', options: ['Write','Read','Draw'], answer: 1 },
    { image: '✍️', options: ['Write','Read','Draw'], answer: 0 },
    { image: '🎨', options: ['Write','Colour','Read'], answer: 1 },
    { image: '😴', options: ['Sleep','Eat','Play'], answer: 0 },
  ]}},
  { title: 'Shapes & Patterns', type: 'shape_sort', emoji: '🔵', difficulty: 'easy', gameData: { questions: [
    { image: '⭕', options: ['Circle','Square','Triangle'], answer: 0 },
    { image: '⬜', options: ['Circle','Square','Triangle'], answer: 1 },
    { image: '△', options: ['Circle','Square','Triangle'], answer: 2 },
    { image: '▭', options: ['Rectangle','Square','Oval'], answer: 0 },
    { image: '⭐', options: ['Star','Circle','Diamond'], answer: 0 },
    { image: '🔶', options: ['Diamond','Hexagon','Square'], answer: 0 },
    { image: '🔷', options: ['Diamond','Oval','Triangle'], answer: 0 },
    { image: '🟣', options: ['Ball','Circle','Sphere'], answer: 1 },
  ]}},
  { title: 'Weather & Seasons', type: 'picture_quiz', emoji: '⛅', difficulty: 'easy', gameData: { questions: [
    { image: '☀️', options: ['Hot & Sunny','Cold & Rainy','Windy'], answer: 0 },
    { image: '🌧️', options: ['Hot & Sunny','Cold & Rainy','Windy'], answer: 1 },
    { image: '🌬️', options: ['Hot','Rainy','Windy'], answer: 2 },
    { image: '⛅', options: ['Sunny','Cloudy','Rainy'], answer: 1 },
    { image: '❄️', options: ['Hot','Cold','Windy'], answer: 1 },
    { image: '🌩️', options: ['Storm','Sunny','Windy'], answer: 0 },
    { image: '🌈', options: ['After rain','During heat','Before rain'], answer: 0 },
    { image: '🌊', options: ['Flood','Sea','Wave'], answer: 0 },
  ]}},
  { title: 'In, On, Under — Prepositions', type: 'multiple_choice', emoji: '📌', difficulty: 'easy', gameData: { questions: [
    { problem: 'The cat is ___ the box.', options: ['on','in','under'], answer: 1 },
    { problem: 'The book is ___ the table.', options: ['in','on','under'], answer: 1 },
    { problem: 'The ball is ___ the chair.', options: ['on','in','under'], answer: 2 },
    { problem: 'The bird is ___ the tree.', options: ['under','in','on'], answer: 2 },
    { problem: 'The fish is ___ the water.', options: ['on','in','under'], answer: 1 },
    { problem: 'The hat is ___ his head.', options: ['in','under','on'], answer: 2 },
    { problem: 'The dog is ___ the sofa.', options: ['in','on','under'], answer: 2 },
    { problem: 'The apple is ___ the basket.', options: ['under','in','on'], answer: 1 },
  ]}},
  { title: 'Big and Small — Comparisons', type: 'multiple_choice', emoji: '📏', difficulty: 'easy', gameData: { questions: [
    { problem: 'Elephant or cat — which is bigger?', options: ['Cat','Elephant','Same'], answer: 1 },
    { problem: 'Ant or dog — which is smaller?', options: ['Ant','Dog','Same'], answer: 0 },
    { problem: 'Sun or moon — which is bigger?', options: ['Moon','Sun','Same'], answer: 1 },
    { problem: '5 or 3 — which is more?', options: ['3','5','Same'], answer: 1 },
    { problem: 'Tree or flower — which is taller?', options: ['Flower','Tree','Same'], answer: 1 },
    { problem: 'Pencil or ruler — which is longer?', options: ['Pencil','Ruler','Same'], answer: 1 },
    { problem: 'Stone or feather — which is heavier?', options: ['Stone','Feather','Same'], answer: 0 },
    { problem: 'Whale or fish — which is larger?', options: ['Fish','Whale','Same'], answer: 1 },
  ]}},
  { title: 'Phonics — Short Vowel Sounds', type: 'phonics', emoji: '🔊', difficulty: 'easy', gameData: { questions: [
    { problem: '"cat" — what vowel sound?', options: ['a','e','i'], answer: 0 },
    { problem: '"bed" — what vowel sound?', options: ['a','e','o'], answer: 1 },
    { problem: '"pig" — what vowel sound?', options: ['a','i','u'], answer: 1 },
    { problem: '"dog" — what vowel sound?', options: ['e','o','u'], answer: 1 },
    { problem: '"sun" — what vowel sound?', options: ['a','o','u'], answer: 2 },
    { problem: 'Word with short "a" sound?', options: ['eat','hat','ice'], answer: 1 },
    { problem: 'Word with short "i" sound?', options: ['bit','boat','beat'], answer: 0 },
    { problem: 'Word rhyming with "hat"?', options: ['hot','bat','bit'], answer: 1 },
  ]}},
  { title: 'Greetings Around the Day', type: 'multiple_choice', emoji: '👋', difficulty: 'easy', gameData: { questions: [
    { problem: 'Morning greeting?', options: ['Good night','Good morning','Good evening'], answer: 1 },
    { problem: 'Afternoon greeting?', options: ['Good morning','Good afternoon','Good night'], answer: 1 },
    { problem: 'Evening greeting?', options: ['Good afternoon','Good evening','Good morning'], answer: 1 },
    { problem: 'Bedtime greeting?', options: ['Good night','Good morning','Goodbye'], answer: 0 },
    { problem: 'When leaving someone?', options: ['Hello','Goodbye','Please'], answer: 1 },
    { problem: '"Thank you" reply?', options: ['Sorry','Welcome','Excuse me'], answer: 1 },
    { problem: 'When bumping into someone?', options: ['Thank you','Excuse me','Please'], answer: 1 },
    { problem: 'Asking for something politely?', options: ['Give me','Please','Take it'], answer: 1 },
  ]}},
];