// Sekolah Rendah - Mandarin EXPANSION (20+ soalan per game)
// Tier 1 CRITICAL FIX

export const sekolah_bahasa_mandarin_expansion_full = [
  { title: 'Chinese Characters Extended', type: 'letter_match', emoji: '🔤', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { letter: '一', word: 'Yi (One)', options: ['一','二','三','四'], answer: 0 },
    { letter: '二', word: 'Er (Two)', options: ['一','二','三','四'], answer: 1 },
    { letter: '三', word: 'San (Three)', options: ['一','二','三','四'], answer: 2 },
    { letter: '四', word: 'Si (Four)', options: ['一','二','三','四'], answer: 3 },
    { letter: '五', word: 'Wu (Five)', options: ['五','六','七','八'], answer: 0 },
    { letter: '六', word: 'Liu (Six)', options: ['五','六','七','八'], answer: 1 },
    { letter: '七', word: 'Qi (Seven)', options: ['五','六','七','八'], answer: 2 },
    { letter: '八', word: 'Ba (Eight)', options: ['五','六','七','八'], answer: 3 },
    { letter: '九', word: 'Jiu (Nine)', options: ['九','十','百','千'], answer: 0 },
    { letter: '十', word: 'Shi (Ten)', options: ['九','十','百','千'], answer: 1 },
    { letter: '人', word: 'Ren (Person)', options: ['人','木','火','水'], answer: 0 },
    { letter: '木', word: 'Mu (Wood)', options: ['人','木','火','水'], answer: 1 },
    { letter: '火', word: 'Huo (Fire)', options: ['人','木','火','水'], answer: 2 },
    { letter: '水', word: 'Shui (Water)', options: ['人','木','火','水'], answer: 3 },
    { letter: '金', word: 'Jin (Metal)', options: ['金','土','风','云'], answer: 0 },
    { letter: '土', word: 'Tu (Earth)', options: ['金','土','风','云'], answer: 1 },
    { letter: '风', word: 'Feng (Wind)', options: ['金','土','风','云'], answer: 2 },
    { letter: '云', word: 'Yun (Cloud)', options: ['金','土','风','云'], answer: 3 },
    { letter: '日', word: 'Ri (Sun)', options: ['日','月','星','雨'], answer: 0 },
    { letter: '月', word: 'Yue (Moon)', options: ['日','月','星','雨'], answer: 1 },
  ]}},
  { title: 'Chinese Numbers Extended', type: 'number_match', emoji: '🔢', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: '一', options: ['One','Two','Three'], answer: 0 },
    { problem: '二', options: ['One','Two','Three'], answer: 1 },
    { problem: '三', options: ['Two','Three','Four'], answer: 1 },
    { problem: '四', options: ['Three','Four','Five'], answer: 1 },
    { problem: '五', options: ['Four','Five','Six'], answer: 1 },
    { problem: '六', options: ['Five','Six','Seven'], answer: 1 },
    { problem: '七', options: ['Six','Seven','Eight'], answer: 1 },
    { problem: '八', options: ['Seven','Eight','Nine'], answer: 1 },
    { problem: '九', options: ['Eight','Nine','Ten'], answer: 1 },
    { problem: '十', options: ['Nine','Ten','Eleven'], answer: 1 },
    { problem: '十一', options: ['Ten','Eleven','Twelve'], answer: 1 },
    { problem: '十二', options: ['Eleven','Twelve','Thirteen'], answer: 1 },
    { problem: '二十', options: ['Nineteen','Twenty','Twenty-one'], answer: 1 },
    { problem: '三十', options: ['Twenty','Thirty','Forty'], answer: 1 },
    { problem: '四十', options: ['Thirty','Forty','Fifty'], answer: 1 },
    { problem: '五十', options: ['Forty','Fifty','Sixty'], answer: 1 },
    { problem: '百', options: ['Fifty','Hundred','Thousand'], answer: 1 },
    { problem: '千', options: ['Hundred','Thousand','Ten Thousand'], answer: 1 },
    { problem: '万', options: ['Thousand','Ten Thousand','Hundred Thousand'], answer: 1 },
    { problem: '百万', options: ['Hundred Thousand','Million','Billion'], answer: 1 },
  ]}},
  { title: 'Chinese Colors Extended', type: 'picture_quiz', emoji: '🎨', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '🔴', options: ['红 (Hong)','蓝 (Lan)','绿 (Lü)'], answer: 0 },
    { image: '🔵', options: ['红 (Hong)','蓝 (Lan)','黄 (Huang)'], answer: 1 },
    { image: '🟢', options: ['红 (Hong)','绿 (Lü)','黄 (Huang)'], answer: 1 },
    { image: '🟡', options: ['蓝 (Lan)','黄 (Huang)','绿 (Lü)'], answer: 1 },
    { image: '⚫', options: ['黑 (Hei)','白 (Bai)','灰 (Hui)'], answer: 0 },
    { image: '⚪', options: ['黑 (Hei)','白 (Bai)','灰 (Hui)'], answer: 1 },
    { image: '🟣', options: ['橙 (Cheng)','紫 (Zi)','粉 (Fen)'], answer: 1 },
    { image: '🟠', options: ['橙 (Cheng)','紫 (Zi)','棕 (Zong)'], answer: 0 },
    { image: '💛', options: ['黄 (Huang)','金 (Jin)','亮 (Liang)'], answer: 0 },
    { image: '💚', options: ['绿 (Lü)','青 (Qing)','墨 (Mo)'], answer: 0 },
    { image: '💙', options: ['蓝 (Lan)','靛 (Dian)','青 (Qing)'], answer: 0 },
    { image: '🩶', options: ['灰 (Hui)','黑 (Hei)','墨 (Mo)'], answer: 0 },
    { image: '🩷', options: ['粉 (Fen)','红 (Hong)','玫 (Mei)'], answer: 0 },
    { image: '🤎', options: ['棕 (Zong)','褐 (He)','土 (Tu)'], answer: 1 },
    { image: '🤍', options: ['白 (Bai)','银 (Yin)','奶 (Nai)'], answer: 0 },
    { image: '🩵', options: ['蓝 (Lan)','靛 (Dian)','青 (Qing)'], answer: 0 },
    { image: '🧡', options: ['橙 (Cheng)','黄 (Huang)','金 (Jin)'], answer: 0 },
    { image: '🖤', options: ['黑 (Hei)','墨 (Mo)','暗 (An)'], answer: 0 },
    { image: '🤐', options: ['银 (Yin)','白 (Bai)','金 (Jin)'], answer: 1 },
    { image: '💜', options: ['紫 (Zi)','蓝 (Lan)','靛 (Dian)'], answer: 0 },
  ]}},
];