// Sekolah Rendah - Bahasa Melayu EXPANSION (20+ soalan per game)
// Tier 1 CRITICAL FIX - Expand semua 20 games dari 8 → 20+ soalan

export const sekolah_bahasa_melayu_expansion_full = [
  // DARJAH 1 Expansion
  { title: 'Huruf Besar A-Z Extended', type: 'letter_match', emoji: '🔤', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { letter: 'A', emoji: '🍎', word: 'Epal', options: ['A','B','C','D'], answer: 0 },
    { letter: 'B', emoji: '🐦', word: 'Burung', options: ['A','B','C','D'], answer: 1 },
    { letter: 'C', emoji: '🐱', word: 'Kucing', options: ['A','B','C','D'], answer: 2 },
    { letter: 'D', emoji: '🐕', word: 'Anjing', options: ['A','B','C','D'], answer: 3 },
    { letter: 'E', emoji: '🐘', word: 'Gajah', options: ['D','E','F','G'], answer: 1 },
    { letter: 'F', emoji: '🐟', word: 'Ikan', options: ['D','E','F','G'], answer: 2 },
    { letter: 'G', emoji: '🍇', word: 'Anggur', options: ['E','F','G','H'], answer: 2 },
    { letter: 'H', emoji: '🏠', word: 'Rumah', options: ['F','G','H','I'], answer: 2 },
    { letter: 'I', emoji: '🕷️', word: 'Lipas', options: ['H','I','J','K'], answer: 1 },
    { letter: 'J', emoji: '🤹', word: 'Jalan', options: ['H','I','J','K'], answer: 2 },
    { letter: 'K', emoji: '🔑', word: 'Kunci', options: ['J','K','L','M'], answer: 1 },
    { letter: 'L', emoji: '🦁', word: 'Singa', options: ['K','L','M','N'], answer: 1 },
    { letter: 'M', emoji: '🧊', word: 'Manisan', options: ['L','M','N','O'], answer: 1 },
    { letter: 'N', emoji: '📰', word: 'Akhbar', options: ['M','N','O','P'], answer: 1 },
    { letter: 'O', emoji: '🍊', word: 'Oren', options: ['N','O','P','Q'], answer: 1 },
    { letter: 'P', emoji: '🐧', word: 'Pinguin', options: ['O','P','Q','R'], answer: 1 },
    { letter: 'Q', emoji: '👑', word: 'Raja', options: ['P','Q','R','S'], answer: 1 },
    { letter: 'R', emoji: '🌹', word: 'Ros', options: ['Q','R','S','T'], answer: 1 },
    { letter: 'S', emoji: '🌞', word: 'Siang', options: ['R','S','T','U'], answer: 1 },
    { letter: 'T', emoji: '🐯', word: 'Harimau', options: ['S','T','U','V'], answer: 1 },
  ]}},
  { title: 'Suku Kata KV Extended', type: 'word_builder', emoji: '🔡', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: 'Bunyi: ka + ki = ?', options: ['kaki','kuku','keke'], answer: 0 },
    { problem: 'Bunyi: bu + ku = ?', options: ['buku','baka','boke'], answer: 0 },
    { problem: 'Bunyi: ma + ta = ?', options: ['mata','mota','muta'], answer: 0 },
    { problem: 'Bunyi: su + su = ?', options: ['sosi','susu','sisu'], answer: 1 },
    { problem: 'Bunyi: pi + pi = ?', options: ['popi','pipi','pupu'], answer: 1 },
    { problem: 'Bunyi: da + da = ?', options: ['dada','didi','dudu'], answer: 0 },
    { problem: 'Bunyi: ku + da = ?', options: ['koda','kuda','kada'], answer: 1 },
    { problem: 'Bunyi: sa + ya = ?', options: ['siyu','saya','suyu'], answer: 1 },
    { problem: 'Bunyi: li + ma = ?', options: ['lima','lama','lima'], answer: 0 },
    { problem: 'Bunyi: pa + nah = ?', options: ['pana','panah','puna'], answer: 1 },
    { problem: 'Bunyi: ba + tu = ?', options: ['batu','butu','bitu'], answer: 0 },
    { problem: 'Bunyi: ga + wai = ?', options: ['gawai','gawei','guwai'], answer: 0 },
    { problem: 'Bunyi: ke + pala = ?', options: ['kepala','kipala','kopala'], answer: 0 },
    { problem: 'Bunyi: je + lita = ?', options: ['jelita','jilita','julita'], answer: 0 },
    { problem: 'Bunyi: mo + tor = ?', options: ['motar','motor','mutor'], answer: 1 },
    { problem: 'Bunyi: so + fa = ?', options: ['sofa','sufa','sifa'], answer: 0 },
    { problem: 'Bunyi: per + i = ?', options: ['peri','piri','puri'], answer: 0 },
    { problem: 'Bunyi: si + cap = ?', options: ['sicap','siap','scap'], answer: 1 },
    { problem: 'Bunyi: ha + ri = ?', options: ['hari','hiri','huri'], answer: 0 },
    { problem: 'Bunyi: wa + ri = ?', options: ['wari','wiri','wuri'], answer: 0 },
  ]}},
  { title: 'Nama Haiwan Mudah Extended', type: 'picture_quiz', emoji: '🐾', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '🐱', options: ['Kucing','Anjing','Arnab'], answer: 0 },
    { image: '🐶', options: ['Kucing','Anjing','Burung'], answer: 1 },
    { image: '🐟', options: ['Ikan','Sotong','Ketam'], answer: 0 },
    { image: '🐓', options: ['Itik','Ayam','Angsa'], answer: 1 },
    { image: '🐘', options: ['Gajah','Kuda','Badak'], answer: 0 },
    { image: '🦁', options: ['Singa','Harimau','Beruang'], answer: 0 },
    { image: '🐧', options: ['Penguin','Ayam','Itik'], answer: 0 },
    { image: '🐰', options: ['Arnab','Tupai','Tikus'], answer: 0 },
    { image: '🐄', options: ['Lembu','Kerbau','Biri-biri'], answer: 0 },
    { image: '🦒', options: ['Jerapah','Kuda','Rusa'], answer: 0 },
    { image: '🐘', options: ['Gajah','Badak','Kerbau'], answer: 0 },
    { image: '🦓', options: ['Kuda','Zebra','Keledai'], answer: 1 },
    { image: '🐢', options: ['Penyu','Buaya','Ular'], answer: 0 },
    { image: '🦋', options: ['Rama-rama','Lebah','Semut'], answer: 0 },
    { image: '🐝', options: ['Rama-rama','Lebah','Kumbang'], answer: 1 },
    { image: '🐸', options: ['Katak','Ular','Penyu'], answer: 0 },
    { image: '🦜', options: ['Elang','Burung beo','Gagak'], answer: 1 },
    { image: '🦅', options: ['Elang','Burung beo','Pipit'], answer: 0 },
    { image: '🐢', options: ['Penyu','Kura-kura','Kelawar'], answer: 1 },
    { image: '🦔', options: ['Landak','Tikus','Arnab'], answer: 0 },
  ]}},

  // DARJAH 2 Expansion
  { title: 'Perkataan Dua Suku Kata Extended', type: 'word_builder', emoji: '📖', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'r-m-h', options: ['rumah','ramah','rimah'], answer: 0 },
    { problem: 'b-k-', options: ['buku','baka','boke'], answer: 0 },
    { problem: 'p-g-', options: ['pagi','pige','poagi'], answer: 0 },
    { problem: 'm-l-m', options: ['malam','malim','milam'], answer: 0 },
    { problem: 'k-d-', options: ['kedai','kuda','kodak'], answer: 0 },
    { problem: 's-k-l', options: ['sekolah','seket','sokol'], answer: 0 },
    { problem: 'k-r-t', options: ['kereta','karata','korat'], answer: 0 },
    { problem: 'j-l-n', options: ['jalan','jilon','julan'], answer: 0 },
    { problem: 'l-m-r', options: ['lamar','lemur','limur'], answer: 1 },
    { problem: 't-l-ng', options: ['telung','telinga','tulang'], answer: 1 },
    { problem: 'p-s-r', options: ['pasar','peser','posar'], answer: 0 },
    { problem: 'k-d-i', options: ['kedai','kidai','kodai'], answer: 0 },
    { problem: 'b-l-j-r', options: ['belajar','belaja','bilajor'], answer: 0 },
    { problem: 'k-m-j-', options: ['kemaji','kemeja','kamaja'], answer: 1 },
    { problem: 'p-t-ng', options: ['petang','pitang','potang'], answer: 0 },
    { problem: 'm-k-n-n', options: ['makanan','mekanan','mokonan'], answer: 0 },
    { problem: 'm-j-h', options: ['majah','mejah','mijah'], answer: 1 },
    { problem: 'k-r-j-', options: ['keraja','kiraja','koraja'], answer: 0 },
    { problem: 'b-r-ng', options: ['barang','bereng','borang'], answer: 1 },
    { problem: 'l-mp-', options: ['lampu','limpu','lumpu'], answer: 0 },
  ]}},
  { title: 'Kata Nama Am - Benda Extended', type: 'multiple_choice', emoji: '📝', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'Manakah kata nama?', options: ['berlari','buku','cantik'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['meja','tidur','merah'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['melompat','sekolah','besar'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['hijau','menangis','bunga'], answer: 2 },
    { problem: 'Manakah kata nama?', options: ['pokok','berlari','kuat'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['kecil','minum','kereta'], answer: 2 },
    { problem: 'Manakah kata nama?', options: ['terbang','burung','tinggi'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['sungai','berenang','sejuk'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['membaca','rumah','lambat'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['manis','gula','cepat'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['mentega','leleh','keras'], answer: 0 },
    { problem: 'Manakah kata nama?', options: ['tidur','pelajar','comel'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['membuat','alat','tajam'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['memberi','hadiah','istimewa'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['mandi','pakaian','bersih'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['makan','nasi','lezat'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['berlari','kasut','cepat'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['meletak','sepotong','berat'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['bersuara','lagu','indah'], answer: 1 },
    { problem: 'Manakah kata nama?', options: ['bermain','permainan','suka'], answer: 1 },
  ]}},
  { title: 'Ejaan Mudah Darjah 2 Extended', type: 'spelling', emoji: '🔡', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: 'Ejaan betul "rmah"?', options: ['rumah','ramah','rimah'], answer: 0 },
    { problem: 'Ejaan betul "bljar"?', options: ['belajar','beljar','blakar'], answer: 0 },
    { problem: 'Ejaan betul "kreta"?', options: ['kereta','kareta','kretas'], answer: 0 },
    { problem: 'Ejaan betul "ptang"?', options: ['patang','petang','poteng'], answer: 1 },
    { problem: 'Ejaan betul "mlm"?', options: ['malam','malim','milam'], answer: 0 },
    { problem: 'Ejaan betul "pgi"?', options: ['pagi','pige','poagi'], answer: 0 },
    { problem: 'Ejaan betul "skola"?', options: ['sekolah','sekola','skolar'], answer: 0 },
    { problem: 'Ejaan betul "mkan"?', options: ['makanan','makan','mekkan'], answer: 1 },
    { problem: 'Ejaan betul "bku"?', options: ['buku','bukku','bako'], answer: 0 },
    { problem: 'Ejaan betul "kdr"?', options: ['kadir','kader','kidur'], answer: 1 },
    { problem: 'Ejaan betul "jln"?', options: ['jalan','julun','jelan'], answer: 0 },
    { problem: 'Ejaan betul "brang"?', options: ['barang','bereng','borang'], answer: 0 },
    { problem: 'Ejaan betul "lmpu"?', options: ['lampu','limpu','lumpu'], answer: 0 },
    { problem: 'Ejaan betul "tng"?', options: ['tang','teng','tung'], answer: 1 },
    { problem: 'Ejaan betul "mndi"?', options: ['mandi','mindi','mundu'], answer: 0 },
    { problem: 'Ejaan betul "ksut"?', options: ['kasut','kesut','kosut'], answer: 0 },
    { problem: 'Ejaan betul "pjbt"?', options: ['pejabat','pijabat','pojabat'], answer: 0 },
    { problem: 'Ejaan betul "bsin"?', options: ['besi','besun','bisen'], answer: 2 },
    { problem: 'Ejaan betul "mrh"?', options: ['merah','mirah','morah'], answer: 0 },
    { problem: 'Ejaan betul "hjau"?', options: ['hijau','hijau','hejau'], answer: 0 },
  ]}},
];