// Sekolah Rendah - Matematik
// Silibus mengikut KSSR (Darjah 1-6)

export const sekolah_mathematics = [
  // ===== DARJAH 1 =====
  { title: 'Nombor 1-10 Darjah 1', type: 'number_match', emoji: '1️⃣', difficulty: 'easy', darjah: 1, totalQuestions: 10, gameData: { questions: [
    { problem: '⭐', options: ['1','2','3'], answer: 0 },
    { problem: '⭐⭐', options: ['1','2','3'], answer: 1 },
    { problem: '⭐⭐⭐', options: ['1','2','3'], answer: 2 },
    { problem: '⭐⭐⭐⭐', options: ['3','4','5'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐', options: ['4','5','6'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐', options: ['5','6','7'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['6','7','8'], answer: 1 },
    { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7','8','9'], answer: 1 },
  ]}},
  { title: 'Tambah Mudah 1+1 Darjah 1', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { problem: '1+1', options: ['3','2','4','1'], answer: 1 },
    { problem: '2+1', options: ['4','3','5','2'], answer: 1 },
    { problem: '1+2', options: ['4','3','5','2'], answer: 1 },
    { problem: '2+2', options: ['6','4','5','3'], answer: 1 },
    { problem: '3+1', options: ['6','4','5','2'], answer: 1 },
    { problem: '2+3', options: ['7','5','6','4'], answer: 1 },
    { problem: '4+1', options: ['7','5','6','4'], answer: 1 },
    { problem: '3+2', options: ['6','5','4','7'], answer: 1 },
  ]}},
  { title: 'Bentuk Mudah Darjah 1', type: 'shape_sort', emoji: '🔵', difficulty: 'easy', darjah: 1, gameData: { questions: [
    { image: '⭕', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 0 },
    { image: '⬜', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 1 },
    { image: '△', options: ['Bulatan','Segi Empat','Segi Tiga'], answer: 2 },
    { image: '▭', options: ['Segiempat Tepat','Segi Empat','Bujur'], answer: 0 },
    { image: '⭐', options: ['Bintang','Bulatan','Segi Tiga'], answer: 0 },
    { image: '🔶', options: ['Berlian','Heksagon','Segi Empat'], answer: 0 },
    { image: '🟡', options: ['Bulatan','Segi Empat','Bintang'], answer: 0 },
    { image: '🔷', options: ['Berlian','Bujur','Segi Tiga'], answer: 0 },
  ]}},

  // ===== DARJAH 2 =====
  { title: 'Tambah hingga 20 Darjah 2', type: 'math_puzzle', emoji: '➕', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: '5+3', options: ['6','8','9','7'], answer: 1 },
    { problem: '7+4', options: ['9','11','12','10'], answer: 1 },
    { problem: '10+5', options: ['13','15','16','14'], answer: 1 },
    { problem: '6+7', options: ['11','13','14','12'], answer: 1 },
    { problem: '8+5', options: ['11','13','14','12'], answer: 1 },
    { problem: '9+6', options: ['13','15','16','14'], answer: 1 },
    { problem: '7+8', options: ['13','15','16','14'], answer: 1 },
    { problem: '11+4', options: ['13','15','16','14'], answer: 1 },
  ]}},
  { title: 'Tolak hingga 20 Darjah 2', type: 'math_puzzle', emoji: '➖', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: '10-3', options: ['5','7','8','6'], answer: 1 },
    { problem: '15-5', options: ['8','10','11','9'], answer: 1 },
    { problem: '20-8', options: ['10','12','13','11'], answer: 1 },
    { problem: '18-7', options: ['9','11','12','10'], answer: 1 },
    { problem: '16-4', options: ['10','12','13','11'], answer: 1 },
    { problem: '14-6', options: ['6','8','9','7'], answer: 1 },
    { problem: '19-9', options: ['8','10','11','9'], answer: 1 },
    { problem: '17-5', options: ['10','12','13','11'], answer: 1 },
  ]}},
  { title: 'Nombor 11-50 Darjah 2', type: 'number_match', emoji: '🔢', difficulty: 'easy', darjah: 2, gameData: { questions: [
    { problem: '11 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 0 },
    { problem: '12 biji epal', options: ['Sebelas','Dua Belas','Tiga Belas'], answer: 1 },
    { problem: '15 biji epal', options: ['Empat Belas','Lima Belas','Enam Belas'], answer: 1 },
    { problem: '20 = ?', options: ['Sembilan Belas','Dua Puluh','Dua Puluh Satu'], answer: 1 },
    { problem: '30 = ?', options: ['Dua Puluh','Tiga Puluh','Empat Puluh'], answer: 1 },
    { problem: '40 = ?', options: ['Tiga Puluh','Empat Puluh','Lima Puluh'], answer: 1 },
    { problem: '50 = ?', options: ['Empat Puluh','Lima Puluh','Enam Puluh'], answer: 1 },
    { problem: '25 = ?', options: ['Dua Puluh','Dua Puluh Lima','Tiga Puluh'], answer: 1 },
  ]}},

  // ===== DARJAH 3 =====
  { title: 'Darab 2 & 5 Darjah 3', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: '2×3', options: ['4','6','8','5'], answer: 1 },
    { problem: '2×5', options: ['8','10','12','9'], answer: 1 },
    { problem: '5×2', options: ['8','10','12','9'], answer: 1 },
    { problem: '5×3', options: ['13','15','17','14'], answer: 1 },
    { problem: '2×7', options: ['12','14','16','10'], answer: 1 },
    { problem: '5×4', options: ['18','20','22','16'], answer: 1 },
    { problem: '2×9', options: ['16','18','20','14'], answer: 1 },
    { problem: '5×6', options: ['28','30','32','26'], answer: 1 },
  ]}},
  { title: 'Bahagi Mudah Darjah 3', type: 'math_puzzle', emoji: '➗', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: '6÷2', options: ['2','3','4','5'], answer: 1 },
    { problem: '10÷2', options: ['4','5','6','7'], answer: 1 },
    { problem: '9÷3', options: ['2','3','4','5'], answer: 1 },
    { problem: '15÷5', options: ['2','3','4','5'], answer: 1 },
    { problem: '12÷4', options: ['2','3','4','5'], answer: 1 },
    { problem: '20÷5', options: ['3','4','5','6'], answer: 1 },
    { problem: '16÷2', options: ['7','8','9','10'], answer: 1 },
    { problem: '25÷5', options: ['4','5','6','7'], answer: 1 },
  ]}},
  { title: 'Pecahan Mudah Darjah 3', type: 'multiple_choice', emoji: '🍕', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: '1/2 bermaksud?', options: ['Satu dari tiga','Satu dari dua','Dua dari satu'], answer: 1 },
    { problem: '1/4 pizza — berapa bahagian?', options: ['Satu dari empat','Empat dari satu','Dua dari empat'], answer: 0 },
    { problem: '1/2 + 1/2 = ?', options: ['1/4','1','2'], answer: 1 },
    { problem: 'Pecahan manakah lebih besar?', options: ['1/4','1/2','Sama'], answer: 1 },
    { problem: '3/4 bermaksud berapa bahagian?', options: ['Tiga dari empat','Empat dari tiga','Tiga sahaja'], answer: 0 },
    { problem: 'Pizza dibahagi 4, ambil 2. Berapa pecahan?', options: ['1/4','2/4','3/4'], answer: 1 },
    { problem: 'Manakah bersamaan dengan 1/2?', options: ['2/4','1/3','3/4'], answer: 0 },
    { problem: '1/3 + 1/3 = ?', options: ['1/3','2/3','3/3'], answer: 1 },
  ]}},

  // ===== DARJAH 4 =====
  { title: 'Darab 3,4,6 Darjah 4', type: 'math_puzzle', emoji: '✖️', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: '3×4', options: ['10','12','14','11'], answer: 1 },
    { problem: '4×4', options: ['14','16','18','15'], answer: 1 },
    { problem: '6×3', options: ['16','18','20','15'], answer: 1 },
    { problem: '3×7', options: ['19','21','23','18'], answer: 1 },
    { problem: '4×6', options: ['22','24','26','20'], answer: 1 },
    { problem: '6×5', options: ['28','30','32','26'], answer: 1 },
    { problem: '3×9', options: ['25','27','29','24'], answer: 1 },
    { problem: '4×8', options: ['30','32','34','28'], answer: 1 },
  ]}},
  { title: 'Wang Malaysia Darjah 4', type: 'counting', emoji: '💰', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: '💵💵💵 — berapa ringgit?', options: ['RM 2','RM 3','RM 4'], answer: 1 },
    { problem: '🪙🪙🪙🪙🪙 (10sen each) — berapa?', options: ['40 sen','50 sen','60 sen'], answer: 1 },
    { problem: '💵💵💵💵💵 — berapa ringgit?', options: ['RM 4','RM 5','RM 6'], answer: 1 },
    { problem: 'Beli RM 5. Bayar RM 10. Baki?', options: ['RM 3','RM 5','RM 7'], answer: 1 },
    { problem: 'Beli roti RM 2.50. Bayar RM 5. Baki?', options: ['RM 2','RM 2.50','RM 3'], answer: 1 },
    { problem: '3 buku × RM 2 = ?', options: ['RM 4','RM 6','RM 8'], answer: 1 },
    { problem: 'RM 10 - RM 3.50 = ?', options: ['RM 5.50','RM 6.50','RM 7.50'], answer: 1 },
    { problem: '2 pen × RM 1.50 = ?', options: ['RM 2.50','RM 3.00','RM 3.50'], answer: 1 },
  ]}},
  { title: 'Masa dan Waktu Darjah 4', type: 'multiple_choice', emoji: '⏰', difficulty: 'medium', darjah: 4, gameData: { questions: [
    { problem: '1 jam = berapa minit?', options: ['30 minit','60 minit','100 minit'], answer: 1 },
    { problem: '1 minit = berapa saat?', options: ['60 saat','30 saat','100 saat'], answer: 0 },
    { problem: '1 hari = berapa jam?', options: ['12 jam','24 jam','48 jam'], answer: 1 },
    { problem: '1 minggu = berapa hari?', options: ['5 hari','6 hari','7 hari'], answer: 2 },
    { problem: '1 bulan = lebih kurang berapa hari?', options: ['20 hari','30 hari','40 hari'], answer: 1 },
    { problem: '1 tahun = berapa bulan?', options: ['10 bulan','12 bulan','14 bulan'], answer: 1 },
    { problem: 'Setengah jam = berapa minit?', options: ['20 minit','30 minit','45 minit'], answer: 1 },
    { problem: 'Pukul 8:30 + 30 minit = ?', options: ['8:00','9:00','9:30'], answer: 1 },
  ]}},

  // ===== DARJAH 5 =====
  { title: 'Darab 7,8,9 Darjah 5', type: 'math_puzzle', emoji: '✖️', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '7×4', options: ['26','28','30','24'], answer: 1 },
    { problem: '8×3', options: ['22','24','26','20'], answer: 1 },
    { problem: '9×2', options: ['16','18','20','14'], answer: 1 },
    { problem: '7×7', options: ['47','49','51','45'], answer: 1 },
    { problem: '8×8', options: ['62','64','66','60'], answer: 1 },
    { problem: '9×9', options: ['79','81','83','77'], answer: 1 },
    { problem: '7×9', options: ['61','63','65','59'], answer: 1 },
    { problem: '8×6', options: ['46','48','50','44'], answer: 1 },
  ]}},
  { title: 'Nombor Dua Digit - Tambah & Tolak Darjah 5', type: 'math_puzzle', emoji: '➕', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '23+45', options: ['66','68','70','64'], answer: 1 },
    { problem: '36+27', options: ['61','63','65','59'], answer: 1 },
    { problem: '54+38', options: ['90','92','94','88'], answer: 1 },
    { problem: '50-23', options: ['25','27','29','23'], answer: 1 },
    { problem: '68-34', options: ['32','34','36','30'], answer: 1 },
    { problem: '75-48', options: ['25','27','29','23'], answer: 1 },
    { problem: '83-26', options: ['55','57','59','53'], answer: 1 },
    { problem: '90-55', options: ['33','35','37','31'], answer: 1 },
  ]}},
  { title: 'Perpuluhan Darjah 5', type: 'math_puzzle', emoji: '🔢', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '0.5 + 0.3 = ?', options: ['0.7','0.8','0.9'], answer: 1 },
    { problem: '1.2 + 0.8 = ?', options: ['1.8','2.0','2.2'], answer: 1 },
    { problem: '2.5 - 1.2 = ?', options: ['1.1','1.3','1.5'], answer: 1 },
    { problem: '0.75 + 0.25 = ?', options: ['0.90','1.00','1.10'], answer: 1 },
    { problem: '3.0 - 1.5 = ?', options: ['1.0','1.5','2.0'], answer: 1 },
    { problem: '0.4 × 2 = ?', options: ['0.6','0.8','1.0'], answer: 1 },
    { problem: '1.6 ÷ 2 = ?', options: ['0.6','0.8','1.0'], answer: 1 },
    { problem: '2.5 × 4 = ?', options: ['8','10','12'], answer: 1 },
  ]}},

  // ===== DARJAH 5 — TAMBAHAN =====
  { title: 'Pecahan Tak Wajar & Nombor Bercampur D5', type: 'math_puzzle', emoji: '🍕', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '7/4 sebagai nombor bercampur?', options: ['1¾','2¼','1½'], answer: 0 },
    { problem: '2½ sebagai pecahan tak wajar?', options: ['3/2','5/2','4/2'], answer: 1 },
    { problem: '1¾ + 2¼ = ?', options: ['3','4','3½'], answer: 1 },
    { problem: '3½ - 1¼ = ?', options: ['2¼','2½','2¾'], answer: 0 },
    { problem: '9/4 sebagai nombor bercampur?', options: ['2¼','2½','2¾'], answer: 0 },
    { problem: '3¾ sebagai pecahan tak wajar?', options: ['13/4','15/4','11/4'], answer: 0 },
    { problem: '2⅓ + 1⅔ = ?', options: ['3','4','3⅓'], answer: 1 },
    { problem: '5/3 sebagai nombor bercampur?', options: ['1⅓','1⅔','2⅓'], answer: 1 },
  ]}},
  { title: 'Nisbah dan Kadar Darjah 5', type: 'math_puzzle', emoji: '📊', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: 'Nisbah 2:4 dalam bentuk paling mudah?', options: ['1:2','2:4','1:3'], answer: 0 },
    { problem: 'Nisbah merah:biru = 3:5. Ada 8 bola, berapa merah?', options: ['2','3','5'], answer: 1 },
    { problem: '6:9 = 2:?', options: ['2','3','4'], answer: 1 },
    { problem: 'Harga 3 buku = RM15. Harga 1 buku?', options: ['RM3','RM5','RM6'], answer: 1 },
    { problem: '5 pen = RM10. 8 pen = ?', options: ['RM14','RM16','RM20'], answer: 1 },
    { problem: 'Nisbah pelajar lelaki:perempuan = 2:3. 20 lelaki, berapa perempuan?', options: ['25','30','15'], answer: 1 },
    { problem: '10:15 = ?:3', options: ['1','2','4'], answer: 1 },
    { problem: 'Harga 4 epal = RM8. Harga 6 epal?', options: ['RM10','RM12','RM14'], answer: 1 },
  ]}},

  // ===== DARJAH 6 =====
  { title: 'Perimeter dan Luas Darjah 6', type: 'multiple_choice', emoji: '📐', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Perimeter segi empat 4cm × 4cm?', options: ['12cm','16cm','8cm'], answer: 1 },
    { problem: 'Luas segi empat 5cm × 3cm?', options: ['8cm²','15cm²','16cm²'], answer: 1 },
    { problem: 'Perimeter segi empat tepat 6cm × 4cm?', options: ['20cm','24cm','10cm'], answer: 0 },
    { problem: 'Luas segi empat 4cm × 4cm?', options: ['8cm²','16cm²','20cm²'], answer: 1 },
    { problem: 'Perimeter = ?', options: ['Panjang × Lebar','Jumlah semua sisi','Panjang + Lebar'], answer: 1 },
    { problem: 'Luas = ?', options: ['Jumlah semua sisi','Panjang × Lebar','Panjang + Lebar'], answer: 1 },
    { problem: 'Segi tiga 3cm, 4cm, 5cm. Perimeter?', options: ['10cm','12cm','14cm'], answer: 1 },
    { problem: 'Luas segi empat 7cm × 2cm?', options: ['9cm²','14cm²','18cm²'], answer: 1 },
  ]}},
  { title: 'Statistik & Graf Darjah 6', type: 'multiple_choice', emoji: '📊', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Graf palang digunakan untuk?', options: ['Tunjukkan arah','Bandingkan data','Ukur sudut'], answer: 1 },
    { problem: 'Paksi x pada graf palang ialah?', options: ['Nilai','Kategori','Nombor'], answer: 1 },
    { problem: 'Paksi y pada graf palang ialah?', options: ['Nilai/Kekerapan','Kategori','Nama'], answer: 0 },
    { problem: '5 murid suka epal, 8 suka oren. Lebih berapa?', options: ['2','3','4'], answer: 1 },
    { problem: 'Jumlah 3 + 5 + 7 + 2 = ?', options: ['15','17','19'], answer: 1 },
    { problem: 'Nilai terbesar dari: 12, 8, 15, 10?', options: ['12','8','15'], answer: 2 },
    { problem: 'Nilai terkecil dari: 12, 8, 15, 10?', options: ['12','8','15'], answer: 1 },
    { problem: 'Min (purata) dari 2, 4, 6 ialah?', options: ['3','4','5'], answer: 1 },
  ]}},
  { title: 'Pecahan Lanjutan & Peratus Darjah 6', type: 'math_puzzle', emoji: '🍕', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: '1/4 + 2/4 = ?', options: ['1/4','3/4','4/4'], answer: 1 },
    { problem: '3/5 - 1/5 = ?', options: ['1/5','2/5','3/5'], answer: 1 },
    { problem: 'Tukar 3/4 ke perpuluhan?', options: ['0.25','0.50','0.75'], answer: 2 },
    { problem: 'Tukar 1/2 ke peratus?', options: ['25%','50%','75%'], answer: 1 },
    { problem: '1/4 dalam peratus?', options: ['10%','25%','50%'], answer: 1 },
    { problem: '3/4 dalam peratus?', options: ['50%','75%','80%'], answer: 1 },
    { problem: '50% daripada 80 = ?', options: ['30','40','50'], answer: 1 },
    { problem: '25% daripada 100 = ?', options: ['20','25','30'], answer: 1 },
  ]}},
  // ===== DARJAH 6 — TAMBAHAN =====
  { title: 'Nombor Negatif Darjah 6', type: 'math_puzzle', emoji: '➖', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: '-3 + 5 = ?', options: ['1','2','3'], answer: 1 },
    { problem: '-4 + (-2) = ?', options: ['-5','-6','-7'], answer: 1 },
    { problem: '7 - 10 = ?', options: ['-2','-3','-4'], answer: 1 },
    { problem: '-5 × 2 = ?', options: ['-8','-10','-12'], answer: 1 },
    { problem: '-6 ÷ 2 = ?', options: ['-2','-3','-4'], answer: 1 },
    { problem: 'Mana lebih besar: -3 atau -7?', options: ['-7','-3','Sama'], answer: 1 },
    { problem: '-2 + 2 = ?', options: ['-1','0','1'], answer: 1 },
    { problem: '(-4) × (-3) = ?', options: ['10','12','14'], answer: 1 },
  ]}},
  { title: 'Algebra Asas Darjah 6', type: 'math_puzzle', emoji: '🔢', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'x + 5 = 9, x = ?', options: ['3','4','5'], answer: 1 },
    { problem: '2x = 10, x = ?', options: ['4','5','6'], answer: 1 },
    { problem: 'x - 3 = 7, x = ?', options: ['9','10','11'], answer: 1 },
    { problem: '3x + 2 = 11, x = ?', options: ['2','3','4'], answer: 1 },
    { problem: 'x/4 = 3, x = ?', options: ['10','12','14'], answer: 1 },
    { problem: '2x - 4 = 8, x = ?', options: ['5','6','7'], answer: 1 },
    { problem: 'Nilai 3x jika x = 4?', options: ['10','12','14'], answer: 1 },
    { problem: 'Nilai x² jika x = 5?', options: ['20','25','30'], answer: 1 },
  ]}},
  { title: 'Statistik - Graf & Data Darjah 6', type: 'multiple_choice', emoji: '📊', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Graf yang tunjuk perubahan masa ialah?', options: ['Carta Pai','Graf Garis','Carta Bar'], answer: 1 },
    { problem: 'Carta pai tunjuk?', options: ['Perubahan masa','Perbandingan bahagian dari keseluruhan','Frekuensi'], answer: 1 },
    { problem: 'Mod ialah?', options: ['Nilai tengah','Nilai paling kerap','Nilai terbesar'], answer: 1 },
    { problem: 'Median ialah?', options: ['Nilai tengah data tersusun','Nilai terbesar','Nilai paling kerap'], answer: 0 },
    { problem: 'Min = jumlah data ÷ ?', options: ['nilai terbesar','bilangan data','nilai tengah'], answer: 1 },
    { problem: 'Julat = nilai terbesar ___?', options: ['+ nilai terkecil','- nilai terkecil','× nilai terkecil'], answer: 1 },
    { problem: 'Data: 2,3,3,5,7. Modnya?', options: ['2','3','5'], answer: 1 },
    { problem: 'Data: 1,2,3,4,5. Min = ?', options: ['2','3','4'], answer: 1 },
  ]}},
  { title: 'Perimeter, Luas & Isipadu D6', type: 'math_puzzle', emoji: '📐', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Perimeter segi empat 5cm × 3cm?', options: ['15cm','16cm','8cm'], answer: 1 },
    { problem: 'Luas segi tiga tapak=6, tinggi=4?', options: ['10cm²','12cm²','24cm²'], answer: 1 },
    { problem: 'Isipadu kiub sisi 3cm?', options: ['9cm³','27cm³','18cm³'], answer: 1 },
    { problem: 'Luas bulatan (π=3.14, r=7)?', options: ['43.96cm²','153.86cm²','21.98cm²'], answer: 1 },
    { problem: 'Isipadu kuboid 4×3×2?', options: ['20cm³','24cm³','28cm³'], answer: 1 },
    { problem: 'Perimeter segi tiga 3+4+5?', options: ['10cm','12cm','14cm'], answer: 1 },
    { problem: 'Luas segiempat tepat 8×5?', options: ['35cm²','40cm²','45cm²'], answer: 1 },
    { problem: 'Keliling bulatan = 2πr. Jika r=7, π=22/7, keliling = ?', options: ['22cm','44cm','66cm'], answer: 1 },
  ]}},
];