export const prasekolah_bahasa_tamil = [
  {
    title: 'எழுத்துக்கள் அ முதல் ஈ வரை',
    type: 'letter_match',
    emoji: '🔤',
    difficulty: 'easy',
    gameData: { questions: [
      { letter: 'அ', options: ['அ', 'ஆ', 'இ', 'ஈ'], answer: 0 },
      { letter: 'ஆ', options: ['அ', 'ஆ', 'இ', 'ஈ'], answer: 1 },
      { letter: 'இ', options: ['அ', 'ஆ', 'இ', 'ஈ'], answer: 2 },
      { letter: 'ஈ', options: ['அ', 'ஆ', 'இ', 'ஈ'], answer: 3 },
      { letter: 'உ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 0 },
      { letter: 'ஊ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 1 },
      { letter: 'எ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 2 },
      { letter: 'ஏ', options: ['உ', 'ஊ', 'எ', 'ஏ'], answer: 3 },
    ]}
  },
  {
    title: 'விலங்குகள் பெயர்கள்',
    type: 'picture_quiz',
    emoji: '🐾',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🐱', options: ['பூனை', 'நாய்', 'மாடு'], answer: 0 },
      { image: '🐶', options: ['பூனை', 'நாய்', 'குதிரை'], answer: 1 },
      { image: '🐘', options: ['யானை', 'குதிரை', 'கரடி'], answer: 0 },
      { image: '🦁', options: ['புலி', 'சிங்கம்', 'கரடி'], answer: 1 },
      { image: '🐄', options: ['மாடு', 'ஆடு', 'பன்றி'], answer: 0 },
      { image: '🐟', options: ['மீன்', 'நண்டு', 'ஆமை'], answer: 0 },
      { image: '🦋', options: ['தும்பி', 'வண்ணத்துப்பூச்சி', 'தேனீ'], answer: 1 },
      { image: '🐦', options: ['கோழி', 'பறவை', 'வாத்து'], answer: 1 },
    ]}
  },
  {
    title: 'பழங்கள் பெயர்கள்',
    type: 'picture_quiz',
    emoji: '🍎',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🍎', options: ['ஆப்பிள்', 'ஆரஞ்சு', 'வாழை'], answer: 0 },
      { image: '🍌', options: ['ஆப்பிள்', 'வாழை', 'மாம்பழம்'], answer: 1 },
      { image: '🍊', options: ['ஆரஞ்சு', 'எலுமிச்சை', 'திராட்சை'], answer: 0 },
      { image: '🍇', options: ['திராட்சை', 'ஸ்ட்ராபெரி', 'செர்ரி'], answer: 0 },
      { image: '🍓', options: ['திராட்சை', 'ஸ்ட்ராபெரி', 'ஆப்பிள்'], answer: 1 },
      { image: '🥭', options: ['பப்பாளி', 'மாம்பழம்', 'பலாப்பழம்'], answer: 1 },
      { image: '🍉', options: ['தர்பூசணி', 'பப்பாளி', 'மாம்பழம்'], answer: 0 },
      { image: '🍋', options: ['எலுமிச்சை', 'ஆரஞ்சு', 'திராட்சை'], answer: 0 },
    ]}
  },
  {
    title: 'நிறங்கள் கற்போம்',
    type: 'picture_quiz',
    emoji: '🌈',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🔴', options: ['சிவப்பு', 'நீலம்', 'பச்சை'], answer: 0 },
      { image: '🔵', options: ['சிவப்பு', 'நீலம்', 'மஞ்சள்'], answer: 1 },
      { image: '🟢', options: ['ஊதா', 'பச்சை', 'ஆரஞ்சு'], answer: 1 },
      { image: '🟡', options: ['மஞ்சள்', 'ஆரஞ்சு', 'வெள்ளை'], answer: 0 },
      { image: '🟠', options: ['மஞ்சள்', 'ஆரஞ்சு', 'சிவப்பு'], answer: 1 },
      { image: '💜', options: ['ஊதா', 'இளஞ்சிவப்பு', 'நீலம்'], answer: 0 },
      { image: '⚫', options: ['கழுப்பு', 'கறுப்பு', 'சாம்பல்'], answer: 1 },
      { image: '⚪', options: ['வெள்ளை', 'கறுப்பு', 'சாம்பல்'], answer: 0 },
    ]}
  },
  {
    title: 'உடல் உறுப்புகள்',
    type: 'picture_quiz',
    emoji: '🧒',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👁️', options: ['கண்', 'மூக்கு', 'காது'], answer: 0 },
      { image: '👃', options: ['கண்', 'மூக்கு', 'வாய்'], answer: 1 },
      { image: '👂', options: ['கண்', 'மூக்கு', 'காது'], answer: 2 },
      { image: '👄', options: ['வாய்', 'மூக்கு', 'உதடு'], answer: 0 },
      { image: '✋', options: ['கால்', 'கை', 'தோள்'], answer: 1 },
      { image: '🦶', options: ['கால்', 'கை', 'கைகள்'], answer: 0 },
      { image: '💇', options: ['தலை', 'உடல்', 'வயிறு'], answer: 0 },
      { image: '🧠', options: ['இதயம்', 'மூளை', 'நுரையீரல்'], answer: 1 },
    ]}
  },
  {
    title: 'எண்கள் 1 முதல் 10',
    type: 'number_match',
    emoji: '🔢',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '⭐', options: ['ஒன்று', 'இரண்டு', 'மூன்று'], answer: 0 },
      { problem: '⭐⭐', options: ['ஒன்று', 'இரண்டு', 'மூன்று'], answer: 1 },
      { problem: '⭐⭐⭐', options: ['இரண்டு', 'மூன்று', 'நான்கு'], answer: 1 },
      { problem: '⭐⭐⭐⭐', options: ['மூன்று', 'நான்கு', 'ஐந்து'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐', options: ['நான்கு', 'ஐந்து', 'ஆறு'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐', options: ['ஐந்து', 'ஆறு', 'ஏழு'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐', options: ['ஆறு', 'ஏழு', 'எட்டு'], answer: 1 },
      { problem: '⭐⭐⭐⭐⭐⭐⭐⭐', options: ['ஏழு', 'எட்டு', 'ஒன்பது'], answer: 1 },
    ]}
  },
  {
    title: 'எழுத்துக்கள் ஓ முதல் ஔ வரை',
    type: 'letter_match',
    emoji: '🔡',
    difficulty: 'easy',
    gameData: { questions: [
      { letter: 'ஒ', options: ['ஒ', 'ஓ', 'ஔ', 'அ'], answer: 0 },
      { letter: 'ஓ', options: ['ஒ', 'ஓ', 'ஔ', 'அ'], answer: 1 },
      { letter: 'ஔ', options: ['ஒ', 'ஓ', 'ஔ', 'இ'], answer: 2 },
      { letter: 'க', options: ['க', 'ங', 'ச', 'ஞ'], answer: 0 },
      { letter: 'ங', options: ['க', 'ங', 'ச', 'ஞ'], answer: 1 },
      { letter: 'ச', options: ['க', 'ங', 'ச', 'ஞ'], answer: 2 },
      { letter: 'ஞ', options: ['க', 'ங', 'ச', 'ஞ'], answer: 3 },
      { letter: 'ட', options: ['ட', 'ண', 'த', 'ந'], answer: 0 },
    ]}
  },
  {
    title: 'குடும்ப உறுப்பினர்கள்',
    type: 'picture_quiz',
    emoji: '👨‍👩‍👧‍👦',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👨', options: ['அப்பா', 'அம்மா', 'அண்ணன்'], answer: 0 },
      { image: '👩', options: ['அப்பா', 'அம்மா', 'அக்கா'], answer: 1 },
      { image: '👴', options: ['அப்பா', 'தாத்தா', 'அண்ணன்'], answer: 1 },
      { image: '👵', options: ['அம்மா', 'பாட்டி', 'அக்கா'], answer: 1 },
      { image: '👦', options: ['அண்ணன்', 'தம்பி', 'தாத்தா'], answer: 0 },
      { image: '👧', options: ['அக்கா', 'தங்கை', 'பாட்டி'], answer: 0 },
      { image: '👶', options: ['குழந்தை', 'தம்பி', 'சிறுவன்'], answer: 0 },
      { image: '👨‍👩‍👧', options: ['குடும்பம்', 'நண்பர்கள்', 'அண்டை வீட்டார்'], answer: 0 },
    ]}
  },
  {
    title: 'காய்கறிகள் பெயர்கள்',
    type: 'picture_quiz',
    emoji: '🥦',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🥕', options: ['கேரட்', 'தக்காளி', 'வெங்காயம்'], answer: 0 },
      { image: '🍅', options: ['கேரட்', 'தக்காளி', 'பப்பாளி'], answer: 1 },
      { image: '🥦', options: ['ப்ரொக்கோலி', 'முட்டைக்கோஸ்', 'கீரை'], answer: 0 },
      { image: '🌽', options: ['சோளம்', 'வெள்ளரி', 'பூசணி'], answer: 0 },
      { image: '🥒', options: ['வெள்ளரி', 'கேரட்', 'பூசணி'], answer: 0 },
      { image: '🧅', options: ['வெங்காயம்', 'உருளைக்கிழங்கு', 'இஞ்சி'], answer: 0 },
      { image: '🥔', options: ['சர்க்கரைவள்ளி', 'உருளைக்கிழங்கு', 'கேரட்'], answer: 1 },
      { image: '🌶️', options: ['மிளகாய்', 'தக்காளி', 'கேரட்'], answer: 0 },
    ]}
  },
  {
    title: 'வீட்டு அறைகள்',
    type: 'picture_quiz',
    emoji: '🏠',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🛋️', options: ['படுக்கையறை', 'வரவேற்பறை', 'சமையலறை'], answer: 1 },
      { image: '🛁', options: ['குளியலறை', 'படுக்கையறை', 'சமையலறை'], answer: 0 },
      { image: '🍳', options: ['சாப்பாட்டு அறை', 'சமையலறை', 'கடை அறை'], answer: 1 },
      { image: '🛏️', options: ['படுக்கையறை', 'வரவேற்பறை', 'குளியலறை'], answer: 0 },
      { image: '📺', options: ['படுக்கையறை', 'வரவேற்பறை', 'சமையலறை'], answer: 1 },
      { image: '📚', options: ['படிக்கும் அறை', 'படுக்கையறை', 'வரவேற்பறை'], answer: 0 },
      { image: '🚪', options: ['ஜன்னல்', 'கதவு', 'வேலி'], answer: 1 },
      { image: '🏠', options: ['வீடு', 'பள்ளி', 'கடை'], answer: 0 },
    ]}
  },
  {
    title: 'போக்குவரத்து வாகனங்கள்',
    type: 'picture_quiz',
    emoji: '🚗',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🚗', options: ['கார்', 'பேருந்து', 'லாரி'], answer: 0 },
      { image: '🚌', options: ['கார்', 'பேருந்து', 'வேன்'], answer: 1 },
      { image: '✈️', options: ['விமானம்', 'ஹெலிகாப்டர்', 'கப்பல்'], answer: 0 },
      { image: '🚢', options: ['படகு', 'படகு', 'கப்பல்'], answer: 2 },
      { image: '🚂', options: ['ரயில்', 'மெட்ரோ', 'டிராம்'], answer: 0 },
      { image: '🏍️', options: ['மிதிவண்டி', 'மோட்டார் சைக்கிள்', 'கார்'], answer: 1 },
      { image: '🚲', options: ['மிதிவண்டி', 'மோட்டார் சைக்கிள்', 'ட்ரோலி'], answer: 0 },
      { image: '🚁', options: ['விமானம்', 'ஹெலிகாப்டர்', 'ட்ரோன்'], answer: 1 },
    ]}
  },
  {
    title: 'பள்ளி பொருட்கள்',
    type: 'picture_quiz',
    emoji: '✏️',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '✏️', options: ['பென்சில்', 'பேனா', 'கிரயான்'], answer: 0 },
      { image: '📏', options: ['அளவுகோல்', 'கத்தரிக்கோல்', 'அழிப்பான்'], answer: 0 },
      { image: '📚', options: ['புத்தகம்', 'பத்திரிகை', 'குறிப்பு'], answer: 0 },
      { image: '🎒', options: ['பள்ளிப் பை', 'கை பை', 'விளையாட்டு பை'], answer: 0 },
      { image: '🖊️', options: ['பென்சில்', 'பேனா', 'மார்க்கர்'], answer: 1 },
      { image: '📐', options: ['செட் ஸ்கொயர்', 'அளவுகோல்', 'கம்பஸ்'], answer: 0 },
      { image: '🗂️', options: ['கோப்பு', 'புத்தகம்', 'பெட்டி'], answer: 0 },
      { image: '🖍️', options: ['வண்ண பென்சில்', 'கிரயான்', 'பேனா'], answer: 1 },
    ]}
  },
  {
    title: 'உணவு வகைகள்',
    type: 'picture_quiz',
    emoji: '🍜',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🍚', options: ['சோறு', 'ரொட்டி', 'நூடுல்ஸ்'], answer: 0 },
      { image: '🍞', options: ['சோறு', 'ரொட்டி', 'பிஸ்கட்'], answer: 1 },
      { image: '🍜', options: ['நூடுல்ஸ்', 'இட்லி', 'தோசை'], answer: 0 },
      { image: '🥘', options: ['சூப்', 'கறி', 'குழம்பு'], answer: 1 },
      { image: '🍰', options: ['கேக்', 'குழி பணியாரம்', 'டோனட்'], answer: 0 },
      { image: '🍳', options: ['வேகவைத்த முட்டை', 'பொரித்த முட்டை', 'ஸ்க்ராம்பிள்ட் எக்'], answer: 1 },
      { image: '🥞', options: ['வாஃபிள்', 'பான்கேக்', 'க்ரேப்'], answer: 1 },
      { image: '🥛', options: ['பால்', 'தண்ணீர்', 'ஜூஸ்'], answer: 0 },
    ]}
  },
  {
    title: 'உணர்வுகள் கற்போம்',
    type: 'picture_quiz',
    emoji: '😊',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '😊', options: ['மகிழ்ச்சி', 'சோகம்', 'கோபம்'], answer: 0 },
      { image: '😢', options: ['மகிழ்ச்சி', 'சோகம்', 'பயம்'], answer: 1 },
      { image: '😠', options: ['மகிழ்ச்சி', 'சோர்வு', 'கோபம்'], answer: 2 },
      { image: '😨', options: ['பயம்', 'கோபம்', 'மகிழ்ச்சி'], answer: 0 },
      { image: '😴', options: ['சோகம்', 'சோர்வு', 'சலிப்பு'], answer: 1 },
      { image: '😂', options: ['சிரிப்பு', 'அழுகை', 'புன்னகை'], answer: 0 },
      { image: '🤗', options: ['அணைப்பு', 'அன்பு', 'மகிழ்ச்சி'], answer: 0 },
      { image: '😍', options: ['ஆச்சரியம்', 'அன்பு', 'மகிழ்ச்சி'], answer: 1 },
    ]}
  },
  {
    title: 'வாரத்தின் நாட்கள்',
    type: 'multiple_choice',
    emoji: '📅',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: 'வாரத்தில் முதல் நாள்?', options: ['திங்கள்', 'ஞாயிறு', 'சனி'], answer: 1 },
      { problem: 'திங்களுக்கு பிறகு வரும் நாள்?', options: ['ஞாயிறு', 'புதன்', 'செவ்வாய்'], answer: 2 },
      { problem: 'வாரத்தின் நடுவிலுள்ள நாள்?', options: ['செவ்வாய்', 'புதன்', 'வியாழன்'], answer: 1 },
      { problem: 'சனிக்கு முன்பு உள்ள நாள்?', options: ['வியாழன்', 'வெள்ளி', 'ஞாயிறு'], answer: 1 },
      { problem: 'வாரத்தில் கடைசி நாள்?', options: ['சனி', 'ஞாயிறு', 'வெள்ளி'], answer: 1 },
      { problem: 'பள்ளி நாட்கள் எத்தனை?', options: ['5', '6', '7'], answer: 0 },
      { problem: 'விடுமுறை நாட்கள்?', options: ['திங்கள்-செவ்வாய்', 'சனி-ஞாயிறு', 'புதன்-வியாழன்'], answer: 1 },
      { problem: 'வாரத்தில் எத்தனை நாட்கள்?', options: ['5', '6', '7'], answer: 2 },
    ]}
  },
  {
    title: 'எதிர்ச்சொற்கள்',
    type: 'multiple_choice',
    emoji: '↔️',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '"பெரிய" என்பதின் எதிர்ச்சொல்?', options: ['சிறிய', 'நீண்ட', 'உயரமான'], answer: 0 },
      { problem: '"சூடான" என்பதின் எதிர்ச்சொல்?', options: ['வெதுவெதுப்பான', 'குளிர்ந்த', 'ஈரமான'], answer: 1 },
      { problem: '"பகல்" என்பதின் எதிர்ச்சொல்?', options: ['மாலை', 'இரவு', 'காலை'], answer: 1 },
      { problem: '"மேலே" என்பதின் எதிர்ச்சொல்?', options: ['போ', 'கீழே', 'நட'], answer: 1 },
      { problem: '"வயதான" என்பதின் எதிர்ச்சொல்?', options: ['இளமையான', 'சிறிய', 'குட்டையான'], answer: 0 },
      { problem: '"கடினமான" என்பதின் எதிர்ச்சொல்?', options: ['கரடுமுரடான', 'மென்மையான', 'மிருதுவான'], answer: 1 },
      { problem: '"ஒளிமயமான" என்பதின் எதிர்ச்சொல்?', options: ['மங்கலான', 'இருண்ட', 'மங்கிய'], answer: 1 },
      { problem: '"கொழுத்த" என்பதின் எதிர்ச்சொல்?', options: ['மெலிந்த', 'சிறிய', 'குட்டையான'], answer: 0 },
    ]}
  },
  {
    title: 'ஆரோக்கியமான வாழ்க்கை',
    type: 'multiple_choice',
    emoji: '💪',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: 'ஆரோக்கியமாக இருக்க என்ன வேண்டும்?', options: ['இனிப்பு சாப்பிடுங்கள்', 'காய்கறி பழம் சாப்பிடுங்கள்', 'பொரித்த உணவு சாப்பிடுங்கள்'], answer: 1 },
      { problem: 'குழந்தைகளுக்கு எத்தனை மணி நேரம் தூக்கம்?', options: ['4 மணி நேரம்', '8 மணி நேரம்', '10-12 மணி நேரம்'], answer: 2 },
      { problem: 'தினமும் தண்ணீர் குடிக்க வேண்டுமா?', options: ['அரிதாக', 'நிறைய', 'வருடம் ஒரு முறை'], answer: 1 },
      { problem: 'நீந்துவது என்ன?', options: ['விளையாட்டு', 'ஓய்வு', 'உடற்பயிற்சி'], answer: 2 },
      { problem: 'சாப்பிடுவதற்கு முன் என்ன செய்ய வேண்டும்?', options: ['படிக்க வேண்டும்', 'தூங்க வேண்டும்', 'கைகளை கழுவ வேண்டும்'], answer: 2 },
      { problem: 'பல் துலக்க வேண்டும்?', options: ['காலை மட்டும்', 'காலை மற்றும் இரவு', 'வாரம் ஒரு முறை'], answer: 1 },
      { problem: 'மைதான விளையாட்டு விளையாடுவது?', options: ['தீங்கானது', 'நல்லது', 'சரியில்லை'], answer: 1 },
      { problem: 'உடற்பயிற்சி நமக்கு என்ன செய்யும்?', options: ['நோய்வாய்படுத்தும்', 'ஆரோக்கியமாக வைக்கும்', 'தூக்கம் வராது'], answer: 1 },
    ]}
  },
  {
    title: 'இயற்கை மற்றும் சூழல்',
    type: 'picture_quiz',
    emoji: '🌿',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🌳', options: ['மரம்', 'புல்', 'பூ'], answer: 0 },
      { image: '🌸', options: ['மரம்', 'பூ', 'இலை'], answer: 1 },
      { image: '🌊', options: ['ஆறு', 'கடல்', 'ஏரி'], answer: 1 },
      { image: '☀️', options: ['சூரியன்', 'நிலவு', 'விண்மீன்'], answer: 0 },
      { image: '🌙', options: ['சூரியன்', 'நிலவு', 'விண்மீன்'], answer: 1 },
      { image: '🌧️', options: ['சூடு', 'மழை', 'காற்று'], answer: 1 },
      { image: '🌈', options: ['மழைக்கு பிறகு', 'பகல் நேரம்', 'இரவு'], answer: 0 },
      { image: '🌲', options: ['தேங்காய் மரம்', 'பைன் மரம்', 'இறப்பர் மரம்'], answer: 1 },
    ]}
  },
  {
    title: 'வீட்டுப் பொருட்கள்',
    type: 'picture_quiz',
    emoji: '🏠',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🍳', options: ['வாணலி', 'பாத்திரம்', 'பேசின்'], answer: 0 },
      { image: '🥄', options: ['கரண்டி', 'முள்கரண்டி', 'பிடிப்பு'], answer: 0 },
      { image: '🔪', options: ['கரண்டி', 'கத்தி', 'முள்கரண்டி'], answer: 1 },
      { image: '🧹', options: ['துடைப்பம்', 'மாப்', 'உலர்த்தி'], answer: 0 },
      { image: '🪣', options: ['வாளி', 'பாத்திரம்', 'கிண்ணம்'], answer: 0 },
      { image: '🛁', options: ['குளியல் தொட்டி', 'படுக்கை', 'சோபா'], answer: 0 },
      { image: '🪑', options: ['மேசை', 'நாற்காலி', 'அலமாரி'], answer: 1 },
      { image: '🛏️', options: ['மேசை', 'படுக்கை', 'நாற்காலி'], answer: 1 },
    ]}
  },
  {
    title: 'விலங்குகளின் ஒலிகள்',
    type: 'multiple_choice',
    emoji: '🔊',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: 'பூனை என்ன சொல்லும்?', options: ['மியாவ்', 'வூஃப்', 'மூ'], answer: 0 },
      { problem: 'நாய் என்ன சொல்லும்?', options: ['மியாவ்', 'வூஃப்', 'மூ'], answer: 1 },
      { problem: 'மாடு என்ன சொல்லும்?', options: ['மியாவ்', 'வூஃப்', 'மூ'], answer: 2 },
      { problem: 'சிங்கம் என்ன சொல்லும்?', options: ['குவாக்', 'கர்ஜனை', 'ட்வீட்'], answer: 1 },
      { problem: 'வாத்து என்ன சொல்லும்?', options: ['குவாக்', 'கர்ஜனை', 'ஹிஸ்'], answer: 0 },
      { problem: 'பறவை என்ன சொல்லும்?', options: ['குவாக்', 'ஹிஸ்', 'ட்வீட்'], answer: 2 },
      { problem: 'ஆட்டுக்குட்டி என்ன சொல்லும்?', options: ['மியாவ்', 'வூஃப்', 'பா'], answer: 2 },
      { problem: 'பாம்பு என்ன சொல்லும்?', options: ['குவாக்', 'ஹிஸ்', 'ட்வீட்'], answer: 1 },
    ]}
  },
  {
    title: 'எண்கள் 11 முதல் 20',
    type: 'number_match',
    emoji: '🔢',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '11 ⭐', options: ['பதினொரு', 'பன்னிரண்டு', 'பதின்மூன்று'], answer: 0 },
      { problem: '12 ⭐', options: ['பதினொரு', 'பன்னிரண்டு', 'பதின்மூன்று'], answer: 1 },
      { problem: '15 ⭐', options: ['பதினான்கு', 'பதினைந்து', 'பதினாறு'], answer: 1 },
      { problem: '17 ⭐', options: ['பதினாறு', 'பதினேழு', 'பதினெட்டு'], answer: 1 },
      { problem: '20 ⭐', options: ['பத்தொன்பது', 'இருபது', 'இருபத்தொன்று'], answer: 1 },
      { problem: 'பதினைந்து = ?', options: ['14', '15', '16'], answer: 1 },
      { problem: 'பன்னிரண்டு = ?', options: ['11', '12', '13'], answer: 1 },
      { problem: 'இருபது = ?', options: ['19', '20', '21'], answer: 1 },
    ]}
  },
  {
    title: 'மாதங்கள் கற்போம்',
    type: 'multiple_choice',
    emoji: '📆',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: 'ஆண்டின் முதல் மாதம்?', options: ['பிப்ரவரி', 'ஜனவரி', 'மார்ச்'], answer: 1 },
      { problem: 'ஒரு வருடத்தில் எத்தனை மாதங்கள்?', options: ['10', '11', '12'], answer: 2 },
      { problem: 'ஆண்டின் கடைசி மாதம்?', options: ['நவம்பர்', 'அக்டோபர்', 'டிசம்பர்'], answer: 2 },
      { problem: 'ஏப்ரலுக்கு பிறகு வரும் மாதம்?', options: ['மார்ச்', 'மே', 'ஜூன்'], answer: 1 },
      { problem: 'ஆண்டின் ஆறாவது மாதம்?', options: ['மே', 'ஜூன்', 'ஜூலை'], answer: 1 },
      { problem: 'டிசம்பருக்கு முன்பு வரும் மாதம்?', options: ['அக்டோபர்', 'நவம்பர்', 'செப்டம்பர்'], answer: 1 },
      { problem: 'வேலன்டைன் தினம் எந்த மாதம்?', options: ['ஜனவரி', 'பிப்ரவரி', 'மார்ச்'], answer: 1 },
      { problem: 'இரண்டாவது மாதம்?', options: ['ஜனவரி', 'பிப்ரவரி', 'மார்ச்'], answer: 1 },
    ]}
  },
  {
    title: 'நேரம் கற்போம்',
    type: 'multiple_choice',
    emoji: '⏰',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: '1 மணி நேரம் = எத்தனை நிமிடங்கள்?', options: ['30', '60', '100'], answer: 1 },
      { problem: 'காலை சுறுசுறுப்பு எந்த நேரத்தில்?', options: ['12 நள்ளிரவு', '12 நண்பகல்', '6 காலை'], answer: 2 },
      { problem: 'நாளில் எத்தனை மணி நேரங்கள்?', options: ['12', '24', '48'], answer: 1 },
      { problem: 'அரை மணி நேரம் = எத்தனை நிமிடங்கள்?', options: ['15', '30', '45'], answer: 1 },
      { problem: 'பள்ளி எந்த நேரத்தில் தொடங்கும்?', options: ['7:30', '12:30', '19:30'], answer: 0 },
      { problem: 'இரவு என்றால் என்ன நேரம்?', options: ['காலை', 'நண்பகல்', 'இரவு'], answer: 2 },
      { problem: '1 வாரம் = எத்தனை நாட்கள்?', options: ['5', '6', '7'], answer: 2 },
      { problem: 'சூரியன் எப்போது உதிக்கும்?', options: ['மாலை', 'காலை', 'இரவு'], answer: 1 },
    ]}
  },
  {
    title: 'சிறு கதை - பூனையும் நாயும்',
    type: 'multiple_choice',
    emoji: '📖',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: 'கதை: "ஒரு வீட்டில் பூனையும் நாயும் இருந்தன. அவை சேர்ந்து விளையாடின." - யார் விளையாடினார்கள்?', options: ['பூனை மட்டும்', 'நாய் மட்டும்', 'பூனையும் நாயும்'], answer: 2 },
      { problem: 'அவை எங்கு இருந்தன?', options: ['பள்ளியில்', 'வீட்டில்', 'கடலில்'], answer: 1 },
      { problem: 'அவை என்ன செய்தன?', options: ['சாப்பிட்டன', 'விளையாடின', 'தூங்கின'], answer: 1 },
      { problem: 'கதையில் எத்தனை விலங்குகள்?', options: ['1', '2', '3'], answer: 1 },
      { problem: 'கதை எதைப் பற்றியது?', options: ['மீன்கள்', 'பறவைகள்', 'விலங்குகள்'], answer: 2 },
      { problem: 'கதையின் பாடம் என்ன?', options: ['சண்டை போடு', 'சேர்ந்து விளையாடு', 'ஒளிந்துகொள்'], answer: 1 },
      { problem: 'பூனை எங்கு இருந்தது?', options: ['வீட்டில்', 'கடலில்', 'பள்ளியில்'], answer: 0 },
      { problem: 'நாய் என்ன செய்தது?', options: ['தூங்கியது', 'விளையாடியது', 'ஓடியது'], answer: 1 },
    ]}
  },
  {
    title: 'நல்ல பழக்கங்கள்',
    type: 'multiple_choice',
    emoji: '🙏',
    difficulty: 'easy',
    gameData: { questions: [
      { problem: 'சாப்பிடுவதற்கு முன் என்ன செய்ய வேண்டும்?', options: ['விளையாடுங்கள்', 'கைகளை கழுவுங்கள்', 'ஓடுங்கள்'], answer: 1 },
      { problem: 'ஆசிரியரை சந்திக்கும்போது என்ன சொல்ல வேண்டும்?', options: ['ஏய்!', 'வணக்கம் ஆசிரியரே', 'ஹாய்!'], answer: 1 },
      { problem: 'பொருள் கொடுத்தால் என்ன சொல்ல வேண்டும்?', options: ['சரியில்லை', 'நன்றி!', 'விடுங்கள்!'], answer: 1 },
      { problem: 'தவறு செய்தால் என்ன சொல்ல வேண்டும்?', options: ['கவலை இல்லை', 'மன்னிக்கவும்', 'தெரியாது'], answer: 1 },
      { problem: 'பெரியவர்கள் முன்னால் எப்படி பேச வேண்டும்?', options: ['சத்தமாக', 'மரியாதையாக', 'தாழ்வாக'], answer: 1 },
      { problem: 'நண்பருக்கு உதவுவது?', options: ['தீங்கானது', 'நல்லது', 'சரியில்லை'], answer: 1 },
      { problem: 'வகுப்பில் என்ன செய்ய வேண்டும்?', options: ['கத்துவது', 'கவனித்துக் கேட்பது', 'தூங்குவது'], answer: 1 },
      { problem: 'குப்பையை எங்கே போட வேண்டும்?', options: ['தரையில்', 'குப்பை தொட்டியில்', 'எங்கும்'], answer: 1 },
    ]}
  },
  {
    title: 'தாவரங்கள் கற்போம்',
    type: 'picture_quiz',
    emoji: '🌱',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '🌹', options: ['ரோஜா', 'சூரியகாந்தி', 'டூலிப்'], answer: 0 },
      { image: '🌻', options: ['ரோஜா', 'சூரியகாந்தி', 'லில்லி'], answer: 1 },
      { image: '🌺', options: ['செம்பருத்தி', 'ஆர்கிட்', 'ரோஜா'], answer: 0 },
      { image: '🌴', options: ['தேங்காய் மரம்', 'புளிய மரம்', 'பலா மரம்'], answer: 0 },
      { image: '🍃', options: ['இலை', 'வேர்', 'தண்டு'], answer: 0 },
      { image: '🌾', options: ['நெல்', 'சோளம்', 'தேங்காய் மரம்'], answer: 0 },
      { image: '🌵', options: ['கள்ளிச்செடி', 'ரோஜா', 'நெல்'], answer: 0 },
      { image: '🍄', options: ['காளான்', 'பூ', 'மரம்'], answer: 0 },
    ]}
  },
  {
    title: 'வானிலை கற்போம்',
    type: 'picture_quiz',
    emoji: '⛅',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '☀️', options: ['மழை', 'வெயில்', 'குளிர்'], answer: 1 },
      { image: '🌧️', options: ['வெயில்', 'மழை', 'காற்று'], answer: 1 },
      { image: '🌈', options: ['மழைக்கு பிறகு', 'பகல் நேரம்', 'இரவு'], answer: 0 },
      { image: '⛈️', options: ['புயல்', 'காற்று', 'கனமழை'], answer: 0 },
      { image: '☁️', options: ['மேகம்', 'மழை', 'வெயில்'], answer: 0 },
      { image: '❄️', options: ['வெயில்', 'குளிர்/பனி', 'மழை'], answer: 1 },
      { image: '💨', options: ['மழை', 'வெயில்', 'காற்று'], answer: 2 },
      { image: '🌤️', options: ['பகுதியளவு மேகம்', 'வெயில்', 'மழை'], answer: 0 },
    ]}
  },
  {
    title: 'தொழில்கள் கற்போம்',
    type: 'picture_quiz',
    emoji: '👔',
    difficulty: 'easy',
    gameData: { questions: [
      { image: '👨‍⚕️', options: ['மருத்துவர்', 'ஆசிரியர்', 'பொறியாளர்'], answer: 0 },
      { image: '👩‍🏫', options: ['மருத்துவர்', 'ஆசிரியர்', 'நர்ஸ்'], answer: 1 },
      { image: '👮', options: ['தீயணைப்பு வீரர்', 'காவல்காரர்', 'மருத்துவர்'], answer: 1 },
      { image: '🧑‍🍳', options: ['சமையல்காரர்', 'ஆசிரியர்', 'மருத்துவர்'], answer: 0 },
      { image: '🧑‍🌾', options: ['மருத்துவர்', 'விவசாயி', 'தச்சர்'], answer: 1 },
      { image: '✈️', options: ['விமான ஓட்டுநர்', 'மருத்துவர்', 'கப்பிட்டான்'], answer: 0 },
      { image: '🚒', options: ['காவல்காரர்', 'தீயணைப்பு வீரர்', 'மருத்துவர்'], answer: 1 },
      { image: '📚', options: ['ஆசிரியர்', 'மருத்துவர்', 'பொறியாளர்'], answer: 0 },
    ]}
  },
];