// Sekolah Rendah - Bahasa Melayu EXPANSION FULL PART 2 (Darjah 3-6, 20+ soalan per game)

export const sekolah_bahasa_melayu_expansion_full_part2 = [
  // DARJAH 3
  { title: 'Perkataan Tiga Suku Kata Extended D3', type: 'word_builder', emoji: '📖', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Bunyi: ke-ma-di', options: ['kemadi','kimdi','komdi'], answer: 0 },
    { problem: 'Bunyi: te-la-ga', options: ['telaga','taluga','tilaga'], answer: 0 },
    { problem: 'Bunyi: pe-nu-lis', options: ['penulis','penalis','pinalis'], answer: 0 },
    { problem: 'Bunyi: ba-ti-k', options: ['batik','butik','betik'], answer: 0 },
    { problem: 'Bunyi: ku-li-t', options: ['kulit','kalat','kilat'], answer: 0 },
    { problem: 'Bunyi: ta-li-n', options: ['talin','taliun','talian'], answer: 2 },
    { problem: 'Bunyi: ha-ri-m', options: ['harim','harum','hiriam'], answer: 1 },
    { problem: 'Bunyi: ba-rang', options: ['barang','bereng','borang'], answer: 0 },
    { problem: 'Bunyi: ma-ta-h', options: ['matah','matah','matahi'], answer: 0 },
    { problem: 'Bunyi: sa-tu-l', options: ['satul','setul','sitol'], answer: 0 },
    { problem: 'Bunyi: pe-ja-bat', options: ['pejabat','pijabat','pojabat'], answer: 0 },
    { problem: 'Bunyi: ke-lu-ar', options: ['keluar','kaliur','kiluar'], answer: 0 },
    { problem: 'Bunyi: pu-la-u', options: ['pulau','palau','pilau'], answer: 0 },
    { problem: 'Bunyi: gam-bar', options: ['gambar','gambir','gimbar'], answer: 0 },
    { problem: 'Bunyi: tem-pat', options: ['tempat','timpit','timpat'], answer: 0 },
    { problem: 'Bunyi: du-nia', options: ['dunia','diunya','deniya'], answer: 0 },
    { problem: 'Bunyi: pin-tu', options: ['pintu','pantau','pintu'], answer: 0 },
    { problem: 'Bunyi: tin-jau', options: ['tinjau','tanjau','tinjaw'], answer: 0 },
    { problem: 'Bunyi: tam-pan', options: ['tampan','timpan','tempun'], answer: 0 },
    { problem: 'Bunyi: bu-mi', options: ['bumi','bami','bomi'], answer: 0 },
  ]}},
  
  { title: 'Sinonim dan Antonim Mudah D3', type: 'multiple_choice', emoji: '🔀', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Sinonim "besar" ialah?', options: ['kecil','raksasa','sedang'], answer: 1 },
    { problem: 'Antonim "panas" ialah?', options: ['gerah','sejuk','hangat'], answer: 1 },
    { problem: 'Sinonim "cantik" ialah?', options: ['jelek','indah','hodoh'], answer: 1 },
    { problem: 'Antonim "naik" ialah?', options: ['terbang','turun','berlari'], answer: 1 },
    { problem: 'Sinonim "cepat" ialah?', options: ['lambat','pantas','perlahan'], answer: 1 },
    { problem: 'Antonim "panjang" ialah?', options: ['pendek','jarak','jauh'], answer: 0 },
    { problem: 'Sinonim "suka" ialah?', options: ['benci','minat','malas'], answer: 1 },
    { problem: 'Antonim "bersih" ialah?', options: ['kotor','putih','cerah'], answer: 0 },
    { problem: 'Sinonim "kuat" ialah?', options: ['lemah','hebat','ringan'], answer: 1 },
    { problem: 'Antonim "depan" ialah?', options: ['hadapan','belakang','tepi'], answer: 1 },
    { problem: 'Sinonim "ramai" ialah?', options: ['senyap','meriah','sunyi'], answer: 1 },
    { problem: 'Antonim "ada" ialah?', options: ['hilang','tiada','hadir'], answer: 1 },
    { problem: 'Sinonim "marah" ialah?', options: ['senang','geram','ceria'], answer: 1 },
    { problem: 'Antonim "membuka" ialah?', options: ['menutup','mengambil','memberi'], answer: 0 },
    { problem: 'Sinonim "gelap" ialah?', options: ['cerah','kelam','terang'], answer: 1 },
    { problem: 'Antonim "kaya" ialah?', options: ['miskin','mapan','sejahtera'], answer: 0 },
    { problem: 'Sinonim "takut" ialah?', options: ['berani','ketakutan','cemerlan'], answer: 1 },
    { problem: 'Antonim "memberi" ialah?', options: ['menerima','mengambil','membawa'], answer: 1 },
    { problem: 'Sinonim "pandai" ialah?', options: ['bodoh','cerdas','naif'], answer: 1 },
    { problem: 'Antonim "membeli" ialah?', options: ['menjual','mengambil','membawa'], answer: 0 },
  ]}},
  
  { title: 'Kalimat Mudah - Tanya Jawab D3', type: 'reading', emoji: '❓', difficulty: 'medium', darjah: 3, gameData: { questions: [
    { problem: 'Soalan: Siapa nama awak? Jawapan yang tepat?', options: ['Nama saya Adik','Rumah saya di sini','Saya bermain'], answer: 0 },
    { problem: 'Soalan: Di mana rumah kamu? Jawapan yang tepat?', options: ['Rumah saya di jalan utama','Saya suka rumah','Rumah besar'], answer: 0 },
    { problem: 'Soalan: Berapa umur kamu? Jawapan yang tepat?', options: ['Umur saya 9 tahun','Sekolah saya besar','Saya anak baik'], answer: 0 },
    { problem: 'Soalan: Apa nama ibu bapa kamu? Jawapan yang tepat?', options: ['Ibu saya Cik Lina dan ayah Encik Ali','Saya ada 2 adik','Rumah saya bagus'], answer: 0 },
    { problem: 'Soalan: Sekolah mana kamu pergi? Jawapan yang tepat?', options: ['Saya pergi ke Sekolah Kebangsaan Seri Jaya','Sekolah itu bagus','Saya suka belajar'], answer: 0 },
    { problem: 'Soalan: Apa subjek kegemaran kamu? Jawapan yang tepat?', options: ['Saya gemar Bahasa Melayu','Guru kami baik','Kelas kami ramai'], answer: 0 },
    { problem: 'Soalan: Apa hobi kamu? Jawapan yang tepat?', options: ['Hobi saya membaca buku','Saya rajin belajar','Saya anak yang baik'], answer: 0 },
    { problem: 'Soalan: Siapa sahabat karib kamu? Jawapan yang tepat?', options: ['Sahabat karib saya ialah Ali','Saya suka bermain','Ali sangat nakal'], answer: 0 },
    { problem: 'Soalan: Apa makanan kegemaran kamu? Jawapan yang tepat?', options: ['Makanan kegemaran saya nasi goreng','Makanan itu enak','Saya selalu makan'], answer: 0 },
    { problem: 'Soalan: Berapa adik-beradik kamu? Jawapan yang tepat?', options: ['Saya ada 2 adik lelaki','Keluarga saya baik','Rumah kami kecil'], answer: 0 },
    { problem: 'Soalan: Apa pekerjaan bapa kamu? Jawapan yang tepat?', options: ['Bapa saya seorang guru','Bapa bekerja setiap hari','Bapa baik hati'], answer: 0 },
    { problem: 'Soalan: Di mana kamu bermain? Jawapan yang tepat?', options: ['Saya bermain di taman','Taman itu luas','Saya suka bermain'], answer: 0 },
    { problem: 'Soalan: Kapan kamu lahir? Jawapan yang tepat?', options: ['Saya lahir pada 15 Januari 2015','Usia saya 9 tahun','Saya lahir di hospital'], answer: 0 },
    { problem: 'Soalan: Apa warna kegemaran kamu? Jawapan yang tepat?', options: ['Warna kegemaran saya biru','Biru warna langit','Saya suka warna cerah'], answer: 0 },
    { problem: 'Soalan: Kemana kamu pergi cuti? Jawapan yang tepat?', options: ['Saya pergi ke Langkawi','Langkawi indah dan sejuk','Saya suka pantai'], answer: 0 },
    { problem: 'Soalan: Apa mimpi kamu? Jawapan yang tepat?', options: ['Mimpi saya menjadi doktor','Saya suka kerja susah','Doktor membantu orang'], answer: 0 },
    { problem: 'Soalan: Siapa guru kegemaran kamu? Jawapan yang tepat?', options: ['Guru kegemaran saya Cik Nur','Guru kami rajin','Cik Nur mengajar dengan baik'], answer: 0 },
    { problem: 'Soalan: Apa olahraga yang kamu mainkan? Jawapan yang tepat?', options: ['Saya bermain bola sepak','Bola sepak suka saya','Bermain itu sehat'], answer: 0 },
    { problem: 'Soalan: Adakah kamu ada keluarga besar? Jawapan yang tepat?', options: ['Ya, saya ada nenek dan atuk','Nenek saya baik','Atuk saya tinggal di kampung'], answer: 0 },
    { problem: 'Soalan: Bagaimana cuaca di rumah kamu? Jawapan yang tepat?', options: ['Cuaca rumah saya panas dan hujan','Hujan itu sejuk','Rumah saya sejuk'], answer: 0 },
  ]}},
  
  // DARJAH 4
  { title: 'Peribahasa dan Simpulan Bahasa D4', type: 'multiple_choice', emoji: '💡', difficulty: 'hard', darjah: 4, gameData: { questions: [
    { problem: '"Seperti kayu api yang sudah mati" bermakna?', options: ['Orang yang patah semangat','Kayu benar-benar mati','Api sudah padam'], answer: 0 },
    { problem: '"Telinga panjang" bermakna?', options: ['Telinga benar-benar panjang','Suka mendengar gosip','Telinga pendek'], answer: 1 },
    { problem: '"Mata seribu" bermakna?', options: ['Mata memang seribu','Orang yang memperhatikan segalanya','Mata besar'], answer: 1 },
    { problem: '"Lidah bercabang" bermakna?', options: ['Lidah benar-benar cabang','Seorang yang suka berdusta','Lidah lurus'], answer: 1 },
    { problem: '"Hati baja" bermakna?', options: ['Hati dari baja','Orang yang tidak mudah tersinggung/kuat','Hati halus'], answer: 1 },
    { problem: '"Mulut manis" bermakna?', options: ['Mulut benar-benar manis','Orang yang pandai bujuk rayu','Mulut pahit'], answer: 1 },
    { problem: '"Tangan ringan" bermakna?', options: ['Tangan benar-benar ringan','Orang yang cepat dan tangkas bekerja','Tangan berat'], answer: 1 },
    { problem: '"Lutut lemah" bermakna?', options: ['Lutut benar-benar lemah','Orang yang takut dan mudah menyerah','Lutut kuat'], answer: 1 },
    { problem: '"Kepala dingin" bermakna?', options: ['Kepala benar-benar sejuk','Orang yang tabah dan tenang','Kepala panas'], answer: 1 },
    { problem: '"Muka masam" bermakna?', options: ['Muka benar-benar masam','Orang yang bersikap tidak senang','Muka ceria'], answer: 1 },
    { problem: '"Akal bulus" bermakna?', options: ['Akal jenis bulus','Orang yang bijaksana dan licik','Akal tunggal'], answer: 1 },
    { problem: '"Bibir kelu" bermakna?', options: ['Bibir benar-benar kelu','Orang yang tertutup mulut/rahasia','Bibir lancar'], answer: 1 },
    { problem: '"Leher besi" bermakna?', options: ['Leher dari besi','Orang yang keras kepala','Leher lembut'], answer: 1 },
    { problem: '"Taring terbuka" bermakna?', options: ['Taring nampak','Orang yang menunjukkan kejahatan','Taring tersembunyi'], answer: 1 },
    { problem: '"Hati busuk" bermakna?', options: ['Hati benar-benar busuk','Orang yang jahat dan kejam','Hati bersih'], answer: 1 },
    { problem: '"Perut buncit" bermakna?', options: ['Perut benar-benar buncit','Orang yang tamak dan serakah','Perut datar'], answer: 1 },
    { problem: '"Bulu kudis" bermakna?', options: ['Bulu benar-benar kudis','Orang yang mudah marah','Bulu halus'], answer: 1 },
    { problem: '"Tulang keras" bermakna?', options: ['Tulang benar-benar keras','Orang yang tidak mudah dipengaruhi','Tulang lemah'], answer: 1 },
    { problem: '"Darah panas" bermakna?', options: ['Darah benar-benar panas','Orang yang mudah marah dan impulsif','Darah sejuk'], answer: 1 },
    { problem: '"Air wajah" bermakna?', options: ['Air dari wajah','Kehormatan dan reputasi seseorang','Air tenang'], answer: 1 },
  ]}},
  
  // DARJAH 5
  { title: 'Ayat Kompleks dan Penulisan D5', type: 'reading', emoji: '📝', difficulty: 'hard', darjah: 5, gameData: { questions: [
    { problem: '"Dia belajar dengan rajin supaya mendapat keputusan terbaik" - tujuannya?', options: ['Dia rajin','Mendapat keputusan terbaik','Dia rajin belajar'], answer: 1 },
    { problem: '"Walaupun hujan lebat, dia tetap pergi ke sekolah" - maknanya?', options: ['Hujan lebat','Dia tidak pergi','Dia tetap pergi meskipun hujan lebat'], answer: 2 },
    { problem: '"Ketika kami sampai di taman, semua telah berkumpul" - urutannya?', options: ['Berkumpul dulu','Kami sampai dulu','Sama waktu'], answer: 1 },
    { problem: '"Ikan yang berenang di sungai itu milik nenek" - penerangnya?', options: ['Di sungai','Berenang','Milik nenek'], answer: 0 },
    { problem: '"Seorang lelaki yang tinggi itu guru kami" - penerangnya?', options: ['Seorang lelaki','Yang tinggi','Guru kami'], answer: 1 },
    { problem: '"Jika kamu belajar dengan sungguh-sungguh, kamu akan berjaya" - syaratnya?', options: ['Kamu berjaya','Belajar dengan sungguh-sungguh','Kamu akan jaya'], answer: 1 },
    { problem: '"Dia berlari cepat ke rumah karena takut ketinggalan makan" - sebabnya?', options: ['Berlari cepat','Takut ketinggalan makan','Ke rumah'], answer: 1 },
    { problem: '"Kami pergi ke pantai dan bermain pasir bersama-sama" - dua hal yang dilakukan?', options: ['Pergi ke pantai & Bermain pasir','Pergi & Bermain','Pantai & Pasir'], answer: 0 },
    { problem: '"Sementara kakak belajar, adik bermain mainan" - dua kegiatan berlaku?', options: ['Bersamaan','Berturut-turut','Satu dulu'], answer: 0 },
    { problem: '"Manakala matahari terbenam, burung-burung pulang ke sarangnya" - waktu?', options: ['Pagi','Siang','Petang/Malam'], answer: 2 },
    { problem: '"Lebih-lebih lagi ketika musim perayaan" - penekannya?', options: ['Perayaan','Lebih-lebih lagi menunjukkan penekanan','Musim'], answer: 1 },
    { problem: '"Di samping itu, dia juga rajin membantu orang tua" - sambungannya?', options: ['Samping','Menambahkan maklumat baru','Bantuan'], answer: 1 },
    { problem: '"Dengan demikian, kita dapat memahami pentingnya pendidikan" - kesimpulannya?', options: ['Dengan','Membuat kesimpulan','Demikian'], answer: 1 },
    { problem: '"Sebab itu, kami berkomitmen untuk belajar dengan lebih baik" - akibatnya?', options: ['Belajar lebih baik','Akibat dari penyebab sebelumnya','Komitmen'], answer: 1 },
    { problem: '"Akan tetapi, masih banyak yang perlu dipelajari" - pertentangannya?', options: ['Akan','Bertentangan dengan pernyataan sebelumnya','Tetapi'], answer: 1 },
    { problem: '"Maka, setiap orang harus berusaha keras" - kesimpulannya?', options: ['Orang','Kesimpulan dari argumen','Keras'], answer: 1 },
    { problem: '"Oleh karena itu, mari kita bersama-sama membangun negara" - sebabnya?', options: ['Membangun','Akibat dari penyebab sebelumnya','Negara'], answer: 1 },
    { problem: '"Apalagi sekarang zaman sudah modern" - penekannya?', options: ['Modern','Lebih menekankan lagi','Sekarang'], answer: 1 },
    { problem: '"Sungguh pun demikian, kami tetap bersyukur" - konsesinya?', options: ['Bersyukur','Memberi konsesi - walaupun begitu','Sungguh'], answer: 1 },
    { problem: '"Biarpun sukar, kita harus teruskan" - penyerahan dirinya?', options: ['Teruskan','Walaupun kesukaran, tetap melakukan','Sukar'], answer: 1 },
  ]}},
  
  // DARJAH 6
  { title: 'Karangan Pendek dan Struktur D6', type: 'multiple_choice', emoji: '✍️', difficulty: 'hard', darjah: 6, gameData: { questions: [
    { problem: 'Bahagian pengenalan karangan berfungsi untuk?', options: ['Menutup cerita','Memperkenalkan tema/latar belakang','Memberi contoh'], answer: 1 },
    { problem: 'Bahagian isi karangan berfungsi untuk?', options: ['Memulai cerita','Menerangkan dan mengembangkan tema','Menutup cerita'], answer: 1 },
    { problem: 'Bahagian penutup karangan berfungsi untuk?', options: ['Menerangkan tema','Menutup dengan kesimpulan/nasihat','Membuka tema'], answer: 1 },
    { problem: 'Karangan deskriptif bertujuan?', options: ['Menceritakan peristiwa','Menggambarkan sesuatu dengan jelas','Mengemukakan pendapat'], answer: 1 },
    { problem: 'Karangan naratif bertujuan?', options: ['Menggambarkan','Menceritakan peristiwa atau kisah','Membujuk'], answer: 1 },
    { problem: 'Karangan eksposisi bertujuan?', options: ['Menceritakan kisah','Menjelaskan dan memberikan maklumat','Menghibur'], answer: 1 },
    { problem: 'Karangan persuasi bertujuan?', options: ['Menggambarkan','Memujuk pembaca untuk setuju','Memberi informasi'], answer: 1 },
    { problem: 'Karangan berbentuk surat resmilah yang..?', options: ['Santai dan dekat','Formal dan terikat peraturan','Pendek dan ringkas'], answer: 1 },
    { problem: 'Tanda baca yang benar dalam dialog?', options: ['"Bagaimana kabarmu ?" dia tanya.','\"Bagaimana kabarmu?\" dia tanya.','\"Bagaimana kabarmu ?\".'], answer: 1 },
    { problem: 'Penggunaan huruf besar yang betul?', options: ['saya tinggal di Kuala Lumpur','Saya tinggal di Kuala Lumpur','SAYA TINGGAL DI KUALA LUMPUR'], answer: 1 },
    { problem: 'Penggunaan huruf besar untuk nama orang yang betul?', options: ['ali pergi ke sekolah','Ali pergi ke sekolah','ALI PERGI KE SEKOLAH'], answer: 1 },
    { problem: 'Penggunaan tanda koma yang betul?', options: ['Dia makan nasi goreng sambil, minum air.','Dia makan nasi goreng, sambil minum air.','Dia makan nasi goreng sambil minum air.'], answer: 2 },
    { problem: 'Penggunaan tanda seru yang betul?', options: ['Berapa umurmu.','Berapa umurmu?','Betapa indahnya pemandangan itu!'], answer: 2 },
    { problem: 'Penggunaan tanda elipsis (...) untuk?', options: ['Akhir ayat','Menunjukkan pemutus atau kelanjutan','Pemisah'], answer: 1 },
    { problem: 'Ayat yang mempunyai subjek dan predikat dipanggil?', options: ['Frasa','Ayat','Perenggan'], answer: 1 },
    { problem: 'Perenggan yang baik mengandungi?', options: ['Banyak ayat','Ayat utama dan ayat sokongan','Sekadar ayat'], answer: 1 },
    { problem: 'Ayat aktif dalam "Dia menulis buku" menunjukkan?', options: ['Dia menerima tindakan','Dia melakukan tindakan','Tindakan pasif'], answer: 1 },
    { problem: 'Ayat pasif dalam "Buku ditulis oleh dia" menunjukkan?', options: ['Dia melakukan','Buku menerima tindakan','Tindakan aktif'], answer: 1 },
    { problem: 'Karangan yang baik harus mengandungi?', options: ['Banyak perenggan','Idea jelas, berkoherensi, dan menarik','Ayat panjang'], answer: 1 },
    { problem: 'Gaya bahasa yang menarik dalam karangan?', options: ['Ayat yang sama terus','Penggunaan kiasan dan perumpamaan','Ayat pendek sahaja'], answer: 1 },
  ]}},
];