// 🔢 MATEMATIK — PRASEKOLAH
// KSSR Prasekolah: Bilangan 0-10, kira, tambah/tolak mudah, bentuk asas.

export const prasekolahMathGames = [
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-kira-1-5',
    title: 'Kira 1 hingga 5',
    emoji: '🔢',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Membilang 1-5',
    order: 1,
    questions: [
      { problem: 'Berapa? 🍎', options: ['1', '2', '3', '4'], answer: 0, emoji: '🍎' },
      { problem: 'Berapa? 🍎🍎', options: ['1', '2', '3', '4'], answer: 1, emoji: '🍎' },
      { problem: 'Berapa? 🍎🍎🍎', options: ['1', '2', '3', '4'], answer: 2, emoji: '🍎' },
      { problem: 'Berapa? 🍎🍎🍎🍎', options: ['2', '3', '4', '5'], answer: 2, emoji: '🍎' },
      { problem: 'Berapa? 🍎🍎🍎🍎🍎', options: ['3', '4', '5', '6'], answer: 2, emoji: '🍎' },
      { problem: 'Berapa? ⭐⭐', options: ['1', '2', '3', '4'], answer: 1, emoji: '⭐' },
      { problem: 'Berapa? 🐱🐱🐱', options: ['2', '3', '4', '5'], answer: 1, emoji: '🐱' },
      { problem: 'Selepas 2 ialah...', options: ['1', '3', '4', '5'], answer: 1, emoji: '🔢' },
      { problem: 'Selepas 4 ialah...', options: ['3', '4', '5', '6'], answer: 2, emoji: '🔢' },
      { problem: 'Sebelum 3 ialah...', options: ['1', '2', '4', '5'], answer: 1, emoji: '🔢' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-kira-6-10',
    title: 'Kira 6 hingga 10',
    emoji: '🔟',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Membilang 6-10',
    order: 2,
    questions: [
      { problem: 'Berapa? ⭐⭐⭐⭐⭐⭐', options: ['5', '6', '7', '8'], answer: 1, emoji: '⭐' },
      { problem: 'Berapa? ⭐⭐⭐⭐⭐⭐⭐', options: ['6', '7', '8', '9'], answer: 1, emoji: '⭐' },
      { problem: 'Berapa? ⭐⭐⭐⭐⭐⭐⭐⭐', options: ['7', '8', '9', '10'], answer: 1, emoji: '⭐' },
      { problem: 'Berapa? ⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['8', '9', '10', '11'], answer: 1, emoji: '⭐' },
      { problem: 'Berapa? ⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', options: ['9', '10', '11', '12'], answer: 1, emoji: '⭐' },
      { problem: 'Selepas 6 ialah...', options: ['5', '7', '8', '9'], answer: 1, emoji: '🔢' },
      { problem: 'Selepas 9 ialah...', options: ['8', '11', '10', '12'], answer: 2, emoji: '🔢' },
      { problem: 'Sebelum 8 ialah...', options: ['6', '7', '9', '10'], answer: 1, emoji: '🔢' },
      { problem: '5, 6, 7, __, 9. Yang hilang ialah...', options: ['6', '7', '8', '10'], answer: 2, emoji: '❓' },
      { problem: '6, __, 8, 9, 10. Yang hilang ialah...', options: ['5', '6', '7', '11'], answer: 2, emoji: '❓' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-tambah-mudah',
    title: 'Tambah Mudah (Jumlah ≤ 10)',
    emoji: '➕',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Tambah Asas',
    order: 3,
    questions: [
      { problem: '1 + 1 = ?', options: ['1', '2', '3', '4'], answer: 1, emoji: '➕' },
      { problem: '2 + 1 = ?', options: ['2', '3', '4', '5'], answer: 1, emoji: '➕' },
      { problem: '2 + 2 = ?', options: ['3', '4', '5', '6'], answer: 1, emoji: '➕' },
      { problem: '3 + 2 = ?', options: ['4', '5', '6', '7'], answer: 1, emoji: '➕' },
      { problem: '4 + 1 = ?', options: ['4', '5', '6', '7'], answer: 1, emoji: '➕' },
      { problem: '3 + 3 = ?', options: ['5', '6', '7', '8'], answer: 1, emoji: '➕' },
      { problem: '4 + 3 = ?', options: ['6', '7', '8', '9'], answer: 1, emoji: '➕' },
      { problem: '5 + 2 = ?', options: ['6', '7', '8', '9'], answer: 1, emoji: '➕' },
      { problem: '5 + 5 = ?', options: ['8', '9', '10', '11'], answer: 2, emoji: '➕' },
      { problem: '6 + 3 = ?', options: ['7', '8', '9', '10'], answer: 2, emoji: '➕' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-tolak-mudah',
    title: 'Tolak Mudah (Hasil ≥ 0)',
    emoji: '➖',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Tolak Asas',
    order: 4,
    questions: [
      { problem: '2 - 1 = ?', options: ['0', '1', '2', '3'], answer: 1, emoji: '➖' },
      { problem: '3 - 1 = ?', options: ['1', '2', '3', '4'], answer: 1, emoji: '➖' },
      { problem: '3 - 2 = ?', options: ['0', '1', '2', '3'], answer: 1, emoji: '➖' },
      { problem: '4 - 2 = ?', options: ['1', '2', '3', '4'], answer: 1, emoji: '➖' },
      { problem: '5 - 3 = ?', options: ['1', '2', '3', '4'], answer: 1, emoji: '➖' },
      { problem: '5 - 5 = ?', options: ['0', '1', '5', '10'], answer: 0, emoji: '➖' },
      { problem: '6 - 4 = ?', options: ['1', '2', '3', '4'], answer: 1, emoji: '➖' },
      { problem: '7 - 3 = ?', options: ['3', '4', '5', '6'], answer: 1, emoji: '➖' },
      { problem: '8 - 6 = ?', options: ['1', '2', '3', '4'], answer: 1, emoji: '➖' },
      { problem: '10 - 5 = ?', options: ['3', '4', '5', '6'], answer: 2, emoji: '➖' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-bentuk',
    title: 'Bentuk Asas',
    emoji: '🔷',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Bentuk 2D',
    order: 5,
    questions: [
      { problem: 'Bentuk apakah ini? ⚪', options: ['Bulatan', 'Segi Empat', 'Segi Tiga', 'Bintang'], answer: 0, emoji: '⚪' },
      { problem: 'Bentuk apakah ini? 🔺', options: ['Bulatan', 'Segi Empat', 'Segi Tiga', 'Bintang'], answer: 2, emoji: '🔺' },
      { problem: 'Bentuk apakah ini? ⬜', options: ['Bulatan', 'Segi Empat Sama', 'Segi Tiga', 'Bintang'], answer: 1, emoji: '⬜' },
      { problem: 'Bentuk apakah ini? ⭐', options: ['Bulatan', 'Segi Empat', 'Segi Tiga', 'Bintang'], answer: 3, emoji: '⭐' },
      { problem: 'Bentuk apakah ini? ❤️', options: ['Hati', 'Bulatan', 'Bintang', 'Bulan'], answer: 0, emoji: '❤️' },
      { problem: 'Roda kereta berbentuk...', options: ['Segi Empat', 'Bulatan', 'Segi Tiga', 'Bintang'], answer: 1, emoji: '🚗' },
      { problem: 'Berapa sisi pada segi tiga?', options: ['2', '3', '4', '5'], answer: 1, emoji: '🔺' },
      { problem: 'Berapa sisi pada segi empat sama?', options: ['3', '4', '5', '6'], answer: 1, emoji: '⬜' },
      { problem: 'Berapa sisi pada bulatan?', options: ['Tiada sisi', '1', '4', '8'], answer: 0, emoji: '⚪' },
      { problem: 'Atap rumah biasanya berbentuk...', options: ['Bulatan', 'Bintang', 'Segi Tiga', 'Hati'], answer: 2, emoji: '🏠' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-banding-saiz',
    title: 'Banding Saiz (Besar/Kecil)',
    emoji: '📏',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Banding & Ukur',
    order: 6,
    questions: [
      { problem: 'Yang mana LEBIH BESAR?', options: ['🐘', '🐭', 'Sama besar', 'Tidak tahu'], answer: 0, emoji: '⚖️' },
      { problem: 'Yang mana LEBIH KECIL?', options: ['🐘', '🐭', 'Sama kecil', 'Tidak tahu'], answer: 1, emoji: '⚖️' },
      { problem: 'Yang mana LEBIH TINGGI?', options: ['🦒', '🐱', 'Sama tinggi', 'Tidak boleh banding'], answer: 0, emoji: '📏' },
      { problem: 'Yang mana LEBIH RENDAH?', options: ['🦒', '🐢', 'Sama tinggi', 'Tidak tahu'], answer: 1, emoji: '📏' },
      { problem: 'Yang mana LEBIH PANJANG?', options: ['🐍 (ular besar)', '🐛 (ulat kecil)', 'Sama panjang', 'Tidak tahu'], answer: 0, emoji: '📏' },
      { problem: 'Yang mana LEBIH BERAT?', options: ['🪶 (bulu)', '🪨 (batu)', 'Sama berat', 'Tidak tahu'], answer: 1, emoji: '⚖️' },
      { problem: 'Yang mana LEBIH RINGAN?', options: ['🪨 (batu)', '🎈 (belon)', 'Sama berat', 'Tidak tahu'], answer: 1, emoji: '⚖️' },
      { problem: 'Antara nombor ini, mana PALING BESAR?', options: ['1', '5', '3', '2'], answer: 1, emoji: '🔢' },
      { problem: 'Antara nombor ini, mana PALING KECIL?', options: ['7', '4', '2', '9'], answer: 2, emoji: '🔢' },
      { problem: '10 adalah lebih __ daripada 5.', options: ['kecil', 'besar', 'sama', 'rendah'], answer: 1, emoji: '🔢' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-corak',
    title: 'Corak & Urutan',
    emoji: '🎨',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'medium',
    topic: 'Corak',
    order: 7,
    questions: [
      { problem: '🔴🔵🔴🔵🔴__. Selepasnya?', options: ['🔴', '🔵', '🟢', '🟡'], answer: 1, emoji: '🎨' },
      { problem: '⭐🌙⭐🌙⭐__. Selepasnya?', options: ['⭐', '🌙', '☀️', '🌟'], answer: 1, emoji: '🎨' },
      { problem: '🍎🍌🍎🍌__. Selepasnya?', options: ['🍓', '🍇', '🍎', '🍊'], answer: 2, emoji: '🎨' },
      { problem: '1, 2, 3, __, 5. Yang hilang?', options: ['2', '4', '6', '7'], answer: 1, emoji: '🔢' },
      { problem: '2, 4, 6, __, 10. Yang hilang?', options: ['7', '8', '9', '12'], answer: 1, emoji: '🔢' },
      { problem: '10, 9, 8, __, 6. Yang hilang?', options: ['5', '7', '11', '4'], answer: 1, emoji: '🔢' },
      { problem: '🔺🔺🔵🔺🔺🔵__. Selepasnya?', options: ['🔺', '🔵', '🟢', '⭐'], answer: 0, emoji: '🎨' },
      { problem: 'A, B, C, __, E. Yang hilang?', options: ['A', 'D', 'F', 'G'], answer: 1, emoji: '🔤' },
      { problem: '5, 10, 15, __, 25. Yang hilang?', options: ['18', '20', '22', '24'], answer: 1, emoji: '🔢' },
      { problem: '🐱🐶🐱🐶🐱__. Selepasnya?', options: ['🐱', '🐶', '🐭', '🐰'], answer: 1, emoji: '🎨' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-mat-cerita-tambah-tolak',
    title: 'Cerita Tambah & Tolak',
    emoji: '📖',
    subject: 'mathematics',
    ageGroup: 'prasekolah',
    difficulty: 'medium',
    topic: 'Penyelesaian Masalah',
    order: 8,
    questions: [
      { problem: 'Ali ada 2 epal. Mak beri 1 lagi. Berapa epal Ali sekarang?', options: ['1', '2', '3', '4'], answer: 2, emoji: '🍎' },
      { problem: 'Aini ada 5 belon. 2 belon meletup. Berapa belon tinggal?', options: ['2', '3', '4', '7'], answer: 1, emoji: '🎈' },
      { problem: 'Ada 3 ekor kucing di taman. 2 ekor datang. Berapa semua?', options: ['3', '4', '5', '6'], answer: 2, emoji: '🐱' },
      { problem: 'Saya ada 4 gula-gula. Saya beri 1 pada adik. Berapa tinggal?', options: ['1', '2', '3', '5'], answer: 2, emoji: '🍬' },
      { problem: 'Ada 6 burung di pokok. 3 burung terbang. Berapa tinggal?', options: ['2', '3', '4', '9'], answer: 1, emoji: '🐦' },
      { problem: 'Mama beli 4 oren. Papa beli 4 oren lagi. Berapa semua?', options: ['6', '7', '8', '10'], answer: 2, emoji: '🍊' },
      { problem: 'Saya ada 10 pensel. Saya hilang 3. Berapa tinggal?', options: ['5', '6', '7', '13'], answer: 2, emoji: '✏️' },
      { problem: 'Ada 2 keping kek. Setiap kek ada 2 ceri. Berapa ceri semua?', options: ['2', '3', '4', '5'], answer: 2, emoji: '🍰' },
      { problem: 'Ada 5 buah pisang. Ali makan 2. Berapa tinggal?', options: ['2', '3', '4', '7'], answer: 1, emoji: '🍌' },
      { problem: 'Saya ada 3 mainan. Datuk beri 4 lagi. Berapa semua?', options: ['5', '6', '7', '8'], answer: 2, emoji: '🧸' },
    ],
  },
];