// 🇲🇾 BAHASA MELAYU — PRASEKOLAH
// Hand-crafted, KSSR Prasekolah-aligned, semua jawapan disahkan.
// Topik: Huruf, suku kata, perkataan asas, ayat ringkas.

export const prasekolahBMGames = [
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-huruf-vokal',
    title: 'Huruf Vokal A E I O U',
    emoji: '🔤',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Huruf Vokal',
    order: 1,
    questions: [
      { problem: 'Yang manakah huruf VOKAL?', options: ['B', 'A', 'C', 'D'], answer: 1, emoji: '🅰️' },
      { problem: 'Pilih huruf vokal:', options: ['M', 'N', 'E', 'P'], answer: 2, emoji: '🅴' },
      { problem: 'Yang manakah huruf vokal?', options: ['I', 'J', 'K', 'L'], answer: 0, emoji: '🅸' },
      { problem: 'Pilih huruf vokal:', options: ['R', 'S', 'T', 'O'], answer: 3, emoji: '🅾️' },
      { problem: 'Yang manakah huruf vokal?', options: ['V', 'U', 'W', 'X'], answer: 1, emoji: '🆄' },
      { problem: "Huruf 'B' adalah huruf...", options: ['Vokal', 'Konsonan', 'Nombor', 'Simbol'], answer: 1, emoji: '🔡' },
      { problem: 'Berapa huruf vokal dalam Bahasa Melayu?', options: ['3', '4', '5', '6'], answer: 2, emoji: '🔢' },
      { problem: "Perkataan 'IBU' bermula dengan huruf...", options: ['Konsonan', 'Vokal', 'Nombor', 'Simbol'], answer: 1, emoji: '👩' },
      { problem: "Huruf vokal dalam 'API' ialah...", options: ['A dan P', 'A dan I', 'P dan I', 'Tiada'], answer: 1, emoji: '🔥' },
      { problem: 'Pilih huruf yang BUKAN vokal:', options: ['A', 'E', 'B', 'I'], answer: 2, emoji: '❌' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-suku-kata-kv',
    title: 'Suku Kata KV (Ba, Bi, Bu)',
    emoji: '📖',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Suku Kata KV',
    order: 2,
    questions: [
      { problem: 'BA + TU = ?', options: ['BATU', 'BUTA', 'BITA', 'BETA'], answer: 0, emoji: '🪨' },
      { problem: 'BU + KU = ?', options: ['BAKU', 'BUKU', 'BIKU', 'BOKU'], answer: 1, emoji: '📚' },
      { problem: 'KU + DA = ?', options: ['KEDA', 'KUDA', 'KIDA', 'KODA'], answer: 1, emoji: '🐴' },
      { problem: 'BU + LU = ?', options: ['BALU', 'BILU', 'BULU', 'BELU'], answer: 2, emoji: '🪶' },
      { problem: 'BA + JU = ?', options: ['BAJU', 'BUJU', 'BIJU', 'BEJU'], answer: 0, emoji: '👕' },
      { problem: 'PI + SU = ?', options: ['PASU', 'PISU', 'POSU', 'PUSU'], answer: 1, emoji: '🔪' },
      { problem: 'BO + LA = ?', options: ['BELA', 'BILA', 'BOLA', 'BULA'], answer: 2, emoji: '⚽' },
      { problem: 'GI + GI = ?', options: ['GAGA', 'GIGI', 'GUGU', 'GEGE'], answer: 1, emoji: '🦷' },
      { problem: 'MA + TA = ?', options: ['MATA', 'MITA', 'MUTA', 'META'], answer: 0, emoji: '👁️' },
      { problem: 'KA + KI = ?', options: ['KEKI', 'KIKI', 'KAKI', 'KUKI'], answer: 2, emoji: '🦵' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-nama-haiwan',
    title: 'Nama Haiwan',
    emoji: '🐾',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Perbendaharaan Kata — Haiwan',
    order: 3,
    questions: [
      { problem: 'Haiwan apakah ini? 🐱', options: ['Kucing', 'Anjing', 'Tikus', 'Arnab'], answer: 0, emoji: '🐱' },
      { problem: 'Haiwan apakah ini? 🐶', options: ['Kucing', 'Anjing', 'Lembu', 'Ayam'], answer: 1, emoji: '🐶' },
      { problem: 'Haiwan apakah ini? 🐘', options: ['Harimau', 'Singa', 'Gajah', 'Kuda'], answer: 2, emoji: '🐘' },
      { problem: 'Haiwan apakah ini? 🐯', options: ['Kucing', 'Singa', 'Beruang', 'Harimau'], answer: 3, emoji: '🐯' },
      { problem: 'Haiwan apakah ini? 🐔', options: ['Ayam', 'Itik', 'Burung', 'Angsa'], answer: 0, emoji: '🐔' },
      { problem: 'Haiwan apakah ini? 🐟', options: ['Udang', 'Ikan', 'Ketam', 'Sotong'], answer: 1, emoji: '🐟' },
      { problem: 'Haiwan apakah ini? 🦋', options: ['Lebah', 'Lalat', 'Rama-rama', 'Nyamuk'], answer: 2, emoji: '🦋' },
      { problem: 'Haiwan apakah ini? 🐰', options: ['Tikus', 'Tupai', 'Hamster', 'Arnab'], answer: 3, emoji: '🐰' },
      { problem: 'Haiwan apakah ini? 🐄', options: ['Lembu', 'Kambing', 'Kerbau', 'Kuda'], answer: 0, emoji: '🐄' },
      { problem: 'Haiwan apakah ini? 🐍', options: ['Cacing', 'Ular', 'Belut', 'Lintah'], answer: 1, emoji: '🐍' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-warna',
    title: 'Nama Warna',
    emoji: '🌈',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Perbendaharaan Kata — Warna',
    order: 4,
    questions: [
      { problem: 'Apakah warna ini? 🔴', options: ['Merah', 'Biru', 'Kuning', 'Hijau'], answer: 0, emoji: '🔴' },
      { problem: 'Apakah warna ini? 🔵', options: ['Merah', 'Biru', 'Hijau', 'Ungu'], answer: 1, emoji: '🔵' },
      { problem: 'Apakah warna ini? 🟢', options: ['Merah', 'Biru', 'Hijau', 'Kuning'], answer: 2, emoji: '🟢' },
      { problem: 'Apakah warna ini? 🟡', options: ['Merah', 'Biru', 'Hijau', 'Kuning'], answer: 3, emoji: '🟡' },
      { problem: 'Apakah warna ini? 🟣', options: ['Ungu', 'Merah', 'Hijau', 'Biru'], answer: 0, emoji: '🟣' },
      { problem: 'Apakah warna ini? 🟠', options: ['Hijau', 'Jingga', 'Kuning', 'Merah'], answer: 1, emoji: '🟠' },
      { problem: 'Apakah warna ini? ⚫', options: ['Putih', 'Kelabu', 'Hitam', 'Coklat'], answer: 2, emoji: '⚫' },
      { problem: 'Apakah warna ini? ⚪', options: ['Hitam', 'Kelabu', 'Krim', 'Putih'], answer: 3, emoji: '⚪' },
      { problem: 'Apakah warna ini? 🟤', options: ['Coklat', 'Hitam', 'Merah', 'Kelabu'], answer: 0, emoji: '🟤' },
      { problem: 'Apakah warna ini? 🩷', options: ['Merah', 'Merah Jambu', 'Ungu', 'Jingga'], answer: 1, emoji: '🩷' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-nama-buah',
    title: 'Nama Buah-Buahan',
    emoji: '🍎',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Perbendaharaan Kata — Buah',
    order: 5,
    questions: [
      { problem: 'Buah apakah ini? 🍎', options: ['Epal', 'Pisang', 'Oren', 'Mangga'], answer: 0, emoji: '🍎' },
      { problem: 'Buah apakah ini? 🍌', options: ['Epal', 'Pisang', 'Oren', 'Mangga'], answer: 1, emoji: '🍌' },
      { problem: 'Buah apakah ini? 🍊', options: ['Epal', 'Pisang', 'Oren', 'Tembikai'], answer: 2, emoji: '🍊' },
      { problem: 'Buah apakah ini? 🥭', options: ['Epal', 'Oren', 'Pisang', 'Mangga'], answer: 3, emoji: '🥭' },
      { problem: 'Buah apakah ini? 🍇', options: ['Anggur', 'Strawberi', 'Ceri', 'Plum'], answer: 0, emoji: '🍇' },
      { problem: 'Buah apakah ini? 🍓', options: ['Anggur', 'Strawberi', 'Ceri', 'Raspberi'], answer: 1, emoji: '🍓' },
      { problem: 'Buah apakah ini? 🍉', options: ['Limau', 'Oren', 'Tembikai', 'Belimbing'], answer: 2, emoji: '🍉' },
      { problem: 'Buah apakah ini? 🍍', options: ['Pisang', 'Oren', 'Mangga', 'Nanas'], answer: 3, emoji: '🍍' },
      { problem: 'Buah apakah ini? 🥥', options: ['Kelapa', 'Durian', 'Manggis', 'Rambutan'], answer: 0, emoji: '🥥' },
      { problem: 'Buah apakah ini? 🫐', options: ['Anggur', 'Bluberi', 'Ceri', 'Plum'], answer: 1, emoji: '🫐' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-anggota-badan',
    title: 'Anggota Badan',
    emoji: '👤',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Perbendaharaan Kata — Badan',
    order: 6,
    questions: [
      { problem: 'Yang mana digunakan untuk MELIHAT?', options: ['Telinga', 'Mata', 'Hidung', 'Mulut'], answer: 1, emoji: '👁️' },
      { problem: 'Yang mana digunakan untuk MENDENGAR?', options: ['Telinga', 'Mata', 'Mulut', 'Tangan'], answer: 0, emoji: '👂' },
      { problem: 'Yang mana digunakan untuk MENCIUM bau?', options: ['Mulut', 'Mata', 'Hidung', 'Telinga'], answer: 2, emoji: '👃' },
      { problem: 'Yang mana digunakan untuk MAKAN?', options: ['Hidung', 'Mata', 'Telinga', 'Mulut'], answer: 3, emoji: '👄' },
      { problem: 'Yang mana digunakan untuk BERJALAN?', options: ['Kaki', 'Tangan', 'Mata', 'Telinga'], answer: 0, emoji: '🦵' },
      { problem: 'Yang mana digunakan untuk MEMEGANG?', options: ['Kaki', 'Tangan', 'Hidung', 'Mata'], answer: 1, emoji: '✋' },
      { problem: 'Berapa MATA yang kita ada?', options: ['1', '2', '3', '4'], answer: 1, emoji: '👀' },
      { problem: 'Berapa HIDUNG yang kita ada?', options: ['2', '3', '1', '4'], answer: 2, emoji: '👃' },
      { problem: 'Bahagian badan untuk berfikir ialah...', options: ['Perut', 'Hati', 'Otak', 'Tangan'], answer: 2, emoji: '🧠' },
      { problem: 'Yang membantu kita BERNAFAS ialah...', options: ['Paru-paru', 'Hati', 'Jantung', 'Perut'], answer: 0, emoji: '🫁' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-keluarga',
    title: 'Ahli Keluarga',
    emoji: '👨‍👩‍👧‍👦',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'easy',
    topic: 'Keluarga',
    order: 7,
    questions: [
      { problem: 'Ibu kepada ibu saya ialah...', options: ['Nenek', 'Mak Cik', 'Kakak', 'Adik'], answer: 0, emoji: '👵' },
      { problem: 'Bapa kepada bapa saya ialah...', options: ['Pak Cik', 'Datuk', 'Abang', 'Bapa Saudara'], answer: 1, emoji: '👴' },
      { problem: 'Anak lelaki kepada ibu bapa saya ialah...', options: ['Bapa', 'Datuk', 'Abang atau adik lelaki', 'Pak Cik'], answer: 2, emoji: '👦' },
      { problem: 'Adik perempuan kepada ibu saya ialah...', options: ['Nenek', 'Kakak', 'Datuk', 'Mak Cik'], answer: 3, emoji: '👩' },
      { problem: 'Adik lelaki kepada bapa saya ialah...', options: ['Bapa Saudara / Pak Cik', 'Datuk', 'Abang', 'Sepupu'], answer: 0, emoji: '👨' },
      { problem: 'Anak kepada Pak Cik saya ialah...', options: ['Adik', 'Sepupu', 'Datuk', 'Ibu'], answer: 1, emoji: '🧒' },
      { problem: 'Yang melahirkan saya ialah...', options: ['Bapa', 'Nenek', 'Ibu', 'Kakak'], answer: 2, emoji: '🤱' },
      { problem: 'Yang menjaga rumah dan bekerja untuk keluarga ialah...', options: ['Saya', 'Adik', 'Nenek', 'Ibu Bapa'], answer: 3, emoji: '👨‍👩‍👧' },
      { problem: 'Saya panggil ibu kepada bapa saya...', options: ['Nenek', 'Mak Cik', 'Ibu', 'Sepupu'], answer: 0, emoji: '👵' },
      { problem: 'Berapa orang ahli keluarga teras (ibu, bapa, anak)?', options: ['1', '3 atau lebih', '2', '0'], answer: 1, emoji: '👨‍👩‍👧‍👦' },
    ],
  },
  // ─────────────────────────────────────────────────────────
  {
    id: 'pra-bm-perkataan-mudah',
    title: 'Eja Perkataan Mudah',
    emoji: '✏️',
    subject: 'bahasa_melayu',
    ageGroup: 'prasekolah',
    difficulty: 'medium',
    topic: 'Ejaan Asas',
    order: 8,
    questions: [
      { problem: "Eja yang betul untuk 🐱:", options: ['Kucing', 'Kuching', 'Cucing', 'Kucink'], answer: 0, emoji: '🐱' },
      { problem: "Eja yang betul untuk 🏠:", options: ['Rumeh', 'Rumah', 'Romah', 'Rumaa'], answer: 1, emoji: '🏠' },
      { problem: "Eja yang betul untuk 🚗:", options: ['Karita', 'Kerita', 'Kereta', 'Kerete'], answer: 2, emoji: '🚗' },
      { problem: "Eja yang betul untuk 📚:", options: ['Beku', 'Boko', 'Bukoh', 'Buku'], answer: 3, emoji: '📚' },
      { problem: "Eja yang betul untuk 🍎:", options: ['Epal', 'Epel', 'Apel', 'Epol'], answer: 0, emoji: '🍎' },
      { problem: "Eja yang betul untuk 👁️:", options: ['Meta', 'Mata', 'Muta', 'Mete'], answer: 1, emoji: '👁️' },
      { problem: "Eja yang betul untuk ☀️:", options: ['Matahri', 'Mtahari', 'Matahari', 'Mataharee'], answer: 2, emoji: '☀️' },
      { problem: "Eja yang betul untuk 🌧️:", options: ['Hojan', 'Hujen', 'Hugen', 'Hujan'], answer: 3, emoji: '🌧️' },
      { problem: "Eja yang betul untuk 🐟:", options: ['Ikan', 'Ekan', 'Ican', 'Ikon'], answer: 0, emoji: '🐟' },
      { problem: "Eja yang betul untuk 👨‍👩‍👧:", options: ['Kluarga', 'Keluarga', 'Keluwarga', 'Keloarga'], answer: 1, emoji: '👨‍👩‍👧' },
    ],
  },
];