// 🏆 BRAIN TRAINING — 10 games × 10 rounds. Tema campuran (kognitif, ingatan, fokus).
import { makeRounds } from './_helpers.js';

export const brainTrainingGames = [
  {
    id: 'brain-padan-bentuk-nama',
    title: 'Padan Bentuk dengan Nama',
    emoji: '🔷',
    mode: 'memory',
    objective: 'Padankan bentuk dengan namanya.',
    reward: 'Shape star',
    rounds: makeRounds([
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang'],['❤️','Hati']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang'],['❤️','Hati'],['💎','Berlian']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang'],['❤️','Hati'],['💎','Berlian'],['🟪','Heksagon']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang'],['❤️','Hati'],['💎','Berlian'],['🟪','Heksagon'],['🟢','Bujur']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang'],['❤️','Hati'],['💎','Berlian'],['🟪','Heksagon'],['🟢','Bujur'],['🔶','Rombus']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang'],['❤️','Hati'],['💎','Berlian'],['🟪','Heksagon'],['🟢','Bujur'],['🔶','Rombus'],['➕','Salib']] },
      { pairs: [['⚪','Bulat'],['🔺','Tiga Segi'],['🟥','Empat Segi'],['⭐','Bintang'],['❤️','Hati'],['💎','Berlian'],['🟪','Heksagon'],['🟢','Bujur'],['🔶','Rombus'],['➕','Salib'],['🟦','Empat Sama'],['🔷','Berlian Biru']] },
    ]),
  },
  {
    id: 'brain-bezakan-kategori',
    title: 'Bezakan Hidup dan Mati',
    emoji: '🌱',
    mode: 'swipe_select',
    objective: 'Bezakan benda hidup dan mati.',
    reward: 'Sort smart',
    rounds: makeRounds([
      { groups: ['Hidup','Mati'], items: [{text:'Pokok',group:'Hidup'},{text:'Batu',group:'Mati'}] },
      { groups: ['Hidup','Mati'], items: [{text:'Manusia',group:'Hidup'},{text:'Kerusi',group:'Mati'},{text:'Kucing',group:'Hidup'}] },
      { groups: ['Hidup','Mati'], items: [{text:'Bunga',group:'Hidup'},{text:'Kereta',group:'Mati'},{text:'Burung',group:'Hidup'},{text:'Meja',group:'Mati'}] },
      { groups: ['Hidup','Mati'], items: [{text:'Ikan',group:'Hidup'},{text:'Komputer',group:'Mati'},{text:'Pokok',group:'Hidup'},{text:'Buku',group:'Mati'},{text:'Manusia',group:'Hidup'}] },
      { groups: ['Bernafas','Tidak Bernafas'], items: [{text:'Manusia',group:'Bernafas'},{text:'Robot',group:'Tidak Bernafas'},{text:'Anjing',group:'Bernafas'},{text:'Patung',group:'Tidak Bernafas'},{text:'Ikan',group:'Bernafas'}] },
      { groups: ['Boleh Bergerak','Tak Bergerak'], items: [{text:'Burung',group:'Boleh Bergerak'},{text:'Batu',group:'Tak Bergerak'},{text:'Kucing',group:'Boleh Bergerak'},{text:'Pokok',group:'Tak Bergerak'},{text:'Ikan',group:'Boleh Bergerak'},{text:'Meja',group:'Tak Bergerak'}] },
      { groups: ['Tumbuhan','Haiwan','Bukan Hidup'], items: [{text:'Pokok',group:'Tumbuhan'},{text:'Kucing',group:'Haiwan'},{text:'Batu',group:'Bukan Hidup'},{text:'Bunga',group:'Tumbuhan'},{text:'Burung',group:'Haiwan'},{text:'Kereta',group:'Bukan Hidup'},{text:'Lalang',group:'Tumbuhan'}] },
      { groups: ['Tumbuhan','Haiwan','Bukan Hidup','Manusia'], items: [{text:'Pokok',group:'Tumbuhan'},{text:'Kucing',group:'Haiwan'},{text:'Batu',group:'Bukan Hidup'},{text:'Murid',group:'Manusia'},{text:'Bunga',group:'Tumbuhan'},{text:'Burung',group:'Haiwan'},{text:'Doktor',group:'Manusia'},{text:'Meja',group:'Bukan Hidup'}] },
      { groups: ['Asli','Buatan'], items: [{text:'Pokok',group:'Asli'},{text:'Kereta',group:'Buatan'},{text:'Burung',group:'Asli'},{text:'Robot',group:'Buatan'},{text:'Air',group:'Asli'},{text:'Plastik',group:'Buatan'},{text:'Matahari',group:'Asli'},{text:'Komputer',group:'Buatan'}] },
      { groups: ['Tumbuhan','Haiwan','Manusia','Buatan','Mineral'], items: [{text:'Pokok',group:'Tumbuhan'},{text:'Kucing',group:'Haiwan'},{text:'Murid',group:'Manusia'},{text:'Robot',group:'Buatan'},{text:'Emas',group:'Mineral'},{text:'Bunga',group:'Tumbuhan'},{text:'Burung',group:'Haiwan'},{text:'Tembaga',group:'Mineral'},{text:'Doktor',group:'Manusia'},{text:'Komputer',group:'Buatan'}] },
    ]),
  },
  {
    id: 'brain-rima-suku-kata',
    title: 'Padan Perkataan Berbunyi',
    emoji: '🎵',
    mode: 'tilematch',
    objective: 'Padankan perkataan yang berima.',
    reward: 'Rhyme smart',
    rounds: makeRounds([
      { tiles: ['lari','hari','batu','satu'] },
      { tiles: ['kucing','pusing','jari','hari'] },
      { tiles: ['malam','dalam','mata','kata','kepala','semula'] },
      { tiles: ['ibu','susu','ayah','rumah','adik','baik'] },
      { tiles: ['besar','segar','muda','duka','tinggi','pergi','jatuh','rebah'] },
      { tiles: ['cantik','adik','bijak','rajin','letih','kacak','manis','tangis'] },
      { tiles: ['gunung','burung','sayang','renang','tidur','dapur','pintu','tentu'] },
      { tiles: ['hujan','minum','jalan','dakapan','rumah','sudah','mendah','tengah'] },
      { tiles: ['kasih','sayang','suka','duka','manis','tangis','pandai','lambai','tinggi','pergi'] },
      { tiles: ['merah','indah','panjang','tenang','lebat','cepat','tinggi','pergi','sangat','dahsyat','baik','periuk'] },
    ]),
  },
  {
    id: 'brain-kira-cabaran',
    title: 'Cabaran Kira',
    emoji: '🧮',
    mode: 'typing_challenge',
    objective: 'Jawab soalan matematik.',
    reward: 'Math whiz',
    rounds: makeRounds([
      { target: '4', prompt: '2 + 2 = ?' },
      { target: '9', prompt: '4 + 5 = ?' },
      { target: '6', prompt: '12 - 6 = ?' },
      { target: '15', prompt: '3 × 5 = ?' },
      { target: '7', prompt: '21 ÷ 3 = ?' },
      { target: '64', prompt: '8 × 8 = ?' },
      { target: '90', prompt: '9 × 10 = ?' },
      { target: '125', prompt: '5 × 25 = ?' },
      { target: '169', prompt: '13 × 13 = ?' },
      { target: '225', prompt: '15 × 15 = ?' },
    ]),
  },
  {
    id: 'brain-ingat-kategori',
    title: 'Ingat Kategori Objek',
    emoji: '🧠',
    mode: 'memory',
    objective: 'Padankan objek dengan kategori.',
    reward: 'Memory wave',
    rounds: makeRounds([
      { pairs: [['🍎','Buah'],['🐯','Haiwan']] },
      { pairs: [['🍎','Buah'],['🐯','Haiwan'],['🚗','Kenderaan']] },
      { pairs: [['🍌','Buah'],['🐘','Haiwan'],['✈️','Kenderaan'],['🌸','Bunga']] },
      { pairs: [['🍇','Buah'],['🦋','Haiwan'],['🚲','Kenderaan'],['⭐','Langit'],['🎨','Seni']] },
      { pairs: [['🥭','Buah'],['🐢','Haiwan'],['🚌','Kenderaan'],['🌙','Langit'],['📚','Buku'],['⚽','Sukan']] },
      { pairs: [['🍍','Buah'],['🦅','Haiwan'],['🚂','Kenderaan'],['☀️','Langit'],['🎵','Muzik'],['🌹','Bunga'],['🏀','Sukan']] },
      { pairs: [['🥥','Buah'],['🐠','Haiwan'],['🛵','Kenderaan'],['🌈','Langit'],['🎸','Muzik'],['🌻','Bunga'],['🏈','Sukan'],['📖','Buku']] },
      { pairs: [['🍓','Buah'],['🦒','Haiwan'],['🚀','Kenderaan'],['☁️','Langit'],['🥁','Muzik'],['🌷','Bunga'],['🎾','Sukan'],['📓','Buku'],['🎨','Seni']] },
      { pairs: [['🍑','Buah'],['🐧','Haiwan'],['🚛','Kenderaan'],['❄️','Langit'],['🎺','Muzik'],['🌺','Bunga'],['⛳','Sukan'],['📕','Buku'],['🖌️','Seni'],['🍕','Makanan']] },
      { pairs: [['🍒','Buah'],['🐬','Haiwan'],['🚁','Kenderaan'],['⚡','Langit'],['🎻','Muzik'],['🪷','Bunga'],['🏐','Sukan'],['📗','Buku'],['🖍️','Seni'],['🍔','Makanan'],['👕','Pakaian'],['⌚','Aksesori']] },
    ]),
  },
  {
    id: 'brain-cari-berbeza',
    title: 'Cari Yang Berbeza',
    emoji: '🔍',
    mode: 'picture_hunt',
    objective: 'Pilih yang BERBEZA dari kumpulan.',
    reward: 'Eagle eye',
    rounds: makeRounds([
      { target: '🐭', items: ['🐱','🐱','🐭'] },
      { target: '🍌', items: ['🍎','🍎','🍌','🍎'] },
      { target: '✈️', items: ['🚗','🚗','🚗','✈️','🚗'] },
      { target: '🌻', items: ['🌸','🌸','🌻','🌸','🌸','🌸'] },
      { target: '🦋', items: ['🐯','🐯','🐯','🐯','🦋','🐯','🐯'] },
      { target: '🎈', items: ['⚽','⚽','⚽','⚽','⚽','🎈','⚽','⚽'] },
      { target: '📚', items: ['✏️','✏️','✏️','✏️','✏️','✏️','📚','✏️','✏️'] },
      { target: '🌊', items: ['🌳','🌳','🌳','🌳','🌳','🌊','🌳','🌳','🌳','🌳'] },
      { target: '⚡', items: ['☁️','☁️','☁️','☁️','☁️','☁️','⚡','☁️','☁️','☁️','☁️'] },
      { target: '🎨', items: ['📖','📖','📖','📖','📖','📖','📖','🎨','📖','📖','📖','📖'] },
    ]),
  },
  {
    id: 'brain-padan-aritmetik',
    title: 'Padan Aritmetik',
    emoji: '➕',
    mode: 'tilematch',
    objective: 'Padankan soalan dengan jawapan.',
    reward: 'Math match',
    rounds: makeRounds([
      { tiles: ['1+1','2','2+2','4'] },
      { tiles: ['1+1','2','2+2','4','3+3','6'] },
      { tiles: ['5+5','10','4+4','8','3+3','6'] },
      { tiles: ['2×2','4','3×3','9','4×4','16'] },
      { tiles: ['10-5','5','20-10','10','15-7','8','30-15','15'] },
      { tiles: ['2×3','6','3×4','12','5×5','25','4×6','24'] },
      { tiles: ['10÷2','5','20÷4','5','15÷3','5','30÷6','5'] },
      { tiles: ['2+3','5','3×3','9','10-4','6','15÷3','5','4×2','8'] },
      { tiles: ['7+8','15','9×9','81','100-25','75','144÷12','12','5×7','35'] },
      { tiles: ['12+8','20','11×11','121','100-37','63','144÷9','16','15×3','45','81÷9','9'] },
    ]),
  },
  {
    id: 'brain-fokus-warna',
    title: 'Fokus Pilih Warna',
    emoji: '🌈',
    mode: 'swipe_select',
    objective: 'Pilih warna ikut sasaran.',
    reward: 'Focus elite',
    rounds: makeRounds([
      { groups: ['Merah','Biru'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'}] },
      { groups: ['Merah','Biru','Hijau'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'}] },
      { groups: ['Merah','Biru','Hijau','Kuning'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'}] },
      { groups: ['Merah','Biru','Hijau','Kuning'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🔴',group:'Merah'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🔵',group:'Biru'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'🟢',group:'Hijau'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'🔴',group:'Merah'},{text:'🟡',group:'Kuning'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga','Hitam'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'⚫',group:'Hitam'},{text:'🟢',group:'Hijau'},{text:'🔴',group:'Merah'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga','Hitam','Putih'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'⚫',group:'Hitam'},{text:'⚪',group:'Putih'},{text:'🟢',group:'Hijau'},{text:'🔴',group:'Merah'}] },
      { groups: ['Panas','Sejuk','Neutral'], items: [{text:'🔴',group:'Panas'},{text:'🔵',group:'Sejuk'},{text:'⚪',group:'Neutral'},{text:'🟠',group:'Panas'},{text:'🟢',group:'Sejuk'},{text:'⚫',group:'Neutral'},{text:'🟡',group:'Panas'},{text:'🟣',group:'Sejuk'},{text:'🟤',group:'Neutral'}] },
    ]),
  },
  {
    id: 'brain-fakta-cepat',
    title: 'Fakta Pantas',
    emoji: '⚡',
    mode: 'true_false',
    objective: 'Jawab pantas — betul atau salah?',
    reward: 'Snap fact',
    rounds: makeRounds([
      { statements: [{text:'5 + 5 = 10.',answer:true},{text:'7 × 7 = 50.',answer:false}] },
      { statements: [{text:'Anjing menyalak.',answer:true},{text:'Ikan berjalan.',answer:false}] },
      { statements: [{text:'Air sejuk = ais.',answer:true},{text:'Api sejuk.',answer:false},{text:'Matahari panas.',answer:true}] },
      { statements: [{text:'Pisang berwarna kuning.',answer:true},{text:'Epal selalu hijau.',answer:false},{text:'Susu putih.',answer:true},{text:'Daun ungu.',answer:false}] },
      { statements: [{text:'2 × 2 = 4.',answer:true},{text:'10 ÷ 2 = 5.',answer:true},{text:'5 - 3 = 1.',answer:false},{text:'9 + 1 = 10.',answer:true},{text:'8 × 0 = 8.',answer:false}] },
      { statements: [{text:'Air mendidih pada 100°C.',answer:true},{text:'Bumi planet ke-3.',answer:true},{text:'Bulan lebih besar dari Bumi.',answer:false},{text:'Manusia ada 2 mata.',answer:true},{text:'Pokok bernafas.',answer:true},{text:'Magnet tarik plastik.',answer:false}] },
      { statements: [{text:'Setahun 12 bulan.',answer:true},{text:'Sehari 24 jam.',answer:true},{text:'Sejam 100 minit.',answer:false},{text:'Seminggu 7 hari.',answer:true},{text:'Setahun 1000 hari.',answer:false},{text:'Bulan Feb ada 28/29 hari.',answer:true},{text:'Bulan Mac ada 31 hari.',answer:true}] },
      { statements: [{text:'Manusia ada hati.',answer:true},{text:'Manusia tak perlu oksigen.',answer:false},{text:'Otak mengawal badan.',answer:true},{text:'Jantung memompa darah.',answer:true},{text:'Paru-paru untuk makan.',answer:false},{text:'Hidung untuk bau.',answer:true},{text:'Lidah untuk lihat.',answer:false},{text:'Telinga untuk dengar.',answer:true}] },
      { statements: [{text:'Pelangi ada 7 warna.',answer:true},{text:'Vokal A E I O U.',answer:true},{text:'Konsonan hanya 3 huruf.',answer:false},{text:'Bumi berputar.',answer:true},{text:'Bulan tidak bersinar sendiri.',answer:true},{text:'Bintang lebih jauh dari bulan.',answer:true},{text:'Cahaya laju dari bunyi.',answer:true},{text:'Hujan turun ke atas.',answer:false},{text:'Salji panas.',answer:false}] },
      { statements: [{text:'1 + 1 = 2.',answer:true},{text:'2 + 2 = 4.',answer:true},{text:'3 × 3 = 9.',answer:true},{text:'10 - 5 = 5.',answer:true},{text:'4 × 4 = 14.',answer:false},{text:'5 × 5 = 25.',answer:true},{text:'6 + 6 = 11.',answer:false},{text:'7 × 7 = 49.',answer:true},{text:'8 × 8 = 64.',answer:true},{text:'9 × 9 = 79.',answer:false}] },
    ]),
  },
  {
    id: 'brain-asingkan-final',
    title: 'Cabaran Final: Asingkan',
    emoji: '🧩',
    mode: 'sorting',
    objective: 'Kelaskan benda ikut konsep.',
    reward: 'Final brain',
    rounds: makeRounds([
      { groups: ['Pagi','Malam'], items: [{text:'Sarapan',group:'Pagi'},{text:'Tidur',group:'Malam'}] },
      { groups: ['Panas','Sejuk'], items: [{text:'Matahari',group:'Panas'},{text:'Ais',group:'Sejuk'},{text:'Api',group:'Panas'}] },
      { groups: ['Boleh Makan','Tak Boleh'], items: [{text:'Nasi',group:'Boleh Makan'},{text:'Batu',group:'Tak Boleh'},{text:'Buah',group:'Boleh Makan'},{text:'Plastik',group:'Tak Boleh'}] },
      { groups: ['Berat','Ringan'], items: [{text:'Gajah',group:'Berat'},{text:'Bulu',group:'Ringan'},{text:'Batu',group:'Berat'},{text:'Belon',group:'Ringan'}] },
      { groups: ['Manusia','Haiwan','Tumbuhan'], items: [{text:'Murid',group:'Manusia'},{text:'Kucing',group:'Haiwan'},{text:'Pokok',group:'Tumbuhan'},{text:'Doktor',group:'Manusia'},{text:'Helang',group:'Haiwan'}] },
      { groups: ['Pagi','Tengah Hari','Malam'], items: [{text:'Sarapan',group:'Pagi'},{text:'Lunch',group:'Tengah Hari'},{text:'Tidur',group:'Malam'},{text:'Bangun',group:'Pagi'},{text:'Snek',group:'Tengah Hari'},{text:'Berdoa',group:'Malam'}] },
      { groups: ['Hidup','Bukan Hidup','Robotik'], items: [{text:'Pokok',group:'Hidup'},{text:'Batu',group:'Bukan Hidup'},{text:'Robot',group:'Robotik'},{text:'Manusia',group:'Hidup'},{text:'Kerusi',group:'Bukan Hidup'},{text:'AI',group:'Robotik'}] },
      { groups: ['Manusia','Haiwan','Tumbuhan','Buatan'], items: [{text:'Murid',group:'Manusia'},{text:'Kucing',group:'Haiwan'},{text:'Pokok',group:'Tumbuhan'},{text:'Robot',group:'Buatan'},{text:'Helang',group:'Haiwan'},{text:'Bunga',group:'Tumbuhan'},{text:'Kereta',group:'Buatan'},{text:'Doktor',group:'Manusia'}] },
      { groups: ['Pagi','Tengah Hari','Petang','Malam'], items: [{text:'Sarapan',group:'Pagi'},{text:'Lunch',group:'Tengah Hari'},{text:'Teh',group:'Petang'},{text:'Tidur',group:'Malam'},{text:'Subuh',group:'Pagi'},{text:'Zohor',group:'Tengah Hari'},{text:'Asar',group:'Petang'},{text:'Isyak',group:'Malam'}] },
      { groups: ['Darat','Air','Udara','Luar Angkasa'], items: [{text:'Kereta',group:'Darat'},{text:'Bot',group:'Air'},{text:'Kapal Terbang',group:'Udara'},{text:'Roket',group:'Luar Angkasa'},{text:'Bas',group:'Darat'},{text:'Kapal',group:'Air'},{text:'Helikopter',group:'Udara'},{text:'Satelit',group:'Luar Angkasa'}] },
    ]),
  },
];