// 🏆 BRAIN TRAINING — 10 games × 10 rounds. Latihan campuran kognitif.
import { makeRounds } from './_helpers.js';

export const brainTrainingGames = [
  {
    id: 'brain-warna-nama',
    title: 'Padan Warna dengan Nama',
    emoji: '🎨',
    mode: 'memory',
    objective: 'Padankan warna dengan namanya.',
    reward: 'Brain streak',
    rounds: makeRounds([
      { pairs: [['🔴','Merah'],['🔵','Biru']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning'],['🟣','Ungu']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning'],['🟣','Ungu'],['🟠','Jingga']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning'],['🟣','Ungu'],['🟠','Jingga'],['⚫','Hitam']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning'],['🟣','Ungu'],['🟠','Jingga'],['⚫','Hitam'],['⚪','Putih']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning'],['🟣','Ungu'],['🟠','Jingga'],['⚫','Hitam'],['⚪','Putih'],['🟤','Coklat']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning'],['🟣','Ungu'],['🟠','Jingga'],['⚫','Hitam'],['⚪','Putih'],['🟤','Coklat'],['🩷','Pink']] },
      { pairs: [['🔴','Merah'],['🔵','Biru'],['🟢','Hijau'],['🟡','Kuning'],['🟣','Ungu'],['🟠','Jingga'],['⚫','Hitam'],['⚪','Putih'],['🟤','Coklat'],['🩷','Pink'],['🩵','Sian'],['🩶','Kelabu']] },
    ]),
  },
  {
    id: 'brain-mainan-belajar',
    title: 'Mainan atau Alat Belajar?',
    emoji: '👆',
    mode: 'swipe_select',
    objective: 'Bezakan mainan dan alat belajar.',
    reward: 'Swipe combo',
    rounds: makeRounds([
      { groups: ['Mainan','Alat Belajar'], items: [{text:'Bola',group:'Mainan'},{text:'Pen',group:'Alat Belajar'}] },
      { groups: ['Mainan','Alat Belajar'], items: [{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Yo-yo',group:'Mainan'}] },
      { groups: ['Mainan','Alat Belajar'], items: [{text:'Bola',group:'Mainan'},{text:'Pen',group:'Alat Belajar'},{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'}] },
      { groups: ['Mainan','Alat Belajar'], items: [{text:'Bola',group:'Mainan'},{text:'Pen',group:'Alat Belajar'},{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Yo-yo',group:'Mainan'}] },
      { groups: ['Mainan','Alat Belajar'], items: [{text:'Bola',group:'Mainan'},{text:'Pen',group:'Alat Belajar'},{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Yo-yo',group:'Mainan'},{text:'Pembaris',group:'Alat Belajar'}] },
      { groups: ['Mainan','Alat Belajar','Sukan'], items: [{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Bola Sepak',group:'Sukan'},{text:'Raket',group:'Sukan'},{text:'Pensel',group:'Alat Belajar'},{text:'Boneka',group:'Mainan'}] },
      { groups: ['Mainan','Alat Belajar','Sukan','Muzik'], items: [{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Bola',group:'Sukan'},{text:'Gitar',group:'Muzik'},{text:'Pensel',group:'Alat Belajar'},{text:'Yo-yo',group:'Mainan'},{text:'Drum',group:'Muzik'}] },
      { groups: ['Mainan','Alat Belajar','Sukan','Muzik'], items: [{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Bola',group:'Sukan'},{text:'Gitar',group:'Muzik'},{text:'Pensel',group:'Alat Belajar'},{text:'Yo-yo',group:'Mainan'},{text:'Drum',group:'Muzik'},{text:'Raket',group:'Sukan'}] },
      { groups: ['Mainan','Alat Belajar','Sukan','Muzik','Seni'], items: [{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Bola',group:'Sukan'},{text:'Gitar',group:'Muzik'},{text:'Berus Cat',group:'Seni'},{text:'Pensel',group:'Alat Belajar'},{text:'Yo-yo',group:'Mainan'},{text:'Drum',group:'Muzik'},{text:'Krayon',group:'Seni'}] },
      { groups: ['Mainan','Alat Belajar','Sukan','Muzik','Seni','Makanan'], items: [{text:'Lego',group:'Mainan'},{text:'Buku',group:'Alat Belajar'},{text:'Bola',group:'Sukan'},{text:'Gitar',group:'Muzik'},{text:'Berus Cat',group:'Seni'},{text:'Pisang',group:'Makanan'},{text:'Pensel',group:'Alat Belajar'},{text:'Yo-yo',group:'Mainan'},{text:'Drum',group:'Muzik'},{text:'Krayon',group:'Seni'}] },
    ]),
  },
  {
    id: 'brain-roda-rima',
    title: 'Padan Perkataan Berima',
    emoji: '🎵',
    mode: 'tilematch',
    objective: 'Padankan perkataan yang berima.',
    reward: 'Rhyme spark',
    rounds: makeRounds([
      { tiles: ['kucing','pusing','hari','jari'] },
      { tiles: ['sayur','tidur','dapur','telur'] },
      { tiles: ['suka','duka','muka','buka','luka','tuka'] },
      { tiles: ['rumah','indah','mudah','susah','sudah','jumlah'] },
      { tiles: ['baju','laju','batu','satu','susu','kuku','buku','palu'] },
      { tiles: ['malam','dalam','salam','siram','kelam','garam','tenggelam','seram'] },
      { tiles: ['cantik','manik','pelik','batik','antik','bilik','adik','dingin'] },
      { tiles: ['gunung','burung','payung','dengung','garing','keliling','helang','batang'] },
      { tiles: ['kasih','manis','tinggi','tangis','sayang','renang','besar','segar','pucat','cepat'] },
      { tiles: ['lautan','daratan','hutan','rakyatan','rumput','sebut','tinggi','pergi','jauh','siapa','apa','tampak'] },
    ]),
  },
  {
    id: 'brain-kira-pantas',
    title: 'Kira Pantas',
    emoji: '🧮',
    mode: 'typing_challenge',
    objective: 'Selesaikan soalan kira pantas.',
    reward: 'Math sprint',
    rounds: makeRounds([
      { target: '3', prompt: '1 + 2 = ?' },
      { target: '5', prompt: '2 + 3 = ?' },
      { target: '7', prompt: '3 + 4 = ?' },
      { target: '12', prompt: '5 + 7 = ?' },
      { target: '20', prompt: '12 + 8 = ?' },
      { target: '35', prompt: '20 + 15 = ?' },
      { target: '50', prompt: '30 + 20 = ?' },
      { target: '81', prompt: '9 × 9 = ?' },
      { target: '144', prompt: '12 × 12 = ?' },
      { target: '256', prompt: '16 × 16 = ?' },
    ]),
  },
  {
    id: 'brain-ingat-emoji',
    title: 'Ingat Emoji & Padan',
    emoji: '🧠',
    mode: 'memory',
    objective: 'Padankan emoji dengan kategorinya.',
    reward: 'Memory wave',
    rounds: makeRounds([
      { pairs: [['🍎','Buah'],['🐯','Haiwan']] },
      { pairs: [['🍎','Buah'],['🐯','Haiwan'],['🚗','Kenderaan']] },
      { pairs: [['🍌','Buah'],['🐘','Haiwan'],['✈️','Kenderaan'],['🌸','Bunga']] },
      { pairs: [['🍇','Buah'],['🦋','Haiwan'],['🚲','Kenderaan'],['⭐','Langit'],['🎨','Seni']] },
      { pairs: [['🥭','Buah'],['🐢','Haiwan'],['🚌','Kenderaan'],['🌙','Langit'],['📚','Buku'],['⚽','Sukan']] },
      { pairs: [['🍍','Buah'],['🦅','Haiwan'],['🚂','Kenderaan'],['☀️','Langit'],['🎵','Muzik'],['🌹','Bunga'],['🏀','Sukan']] },
      { pairs: [['🥥','Buah'],['🐠','Haiwan'],['🛵','Kenderaan'],['🌈','Langit'],['🎸','Muzik'],['🌻','Bunga'],['🏈','Sukan'],['📖','Buku']] },
      { pairs: [['🍓','Buah'],['🦒','Haiwan'],['🚀','Kenderaan'],['☁️','Langit'],['🥁','Muzik'],['🌷','Bunga'],['🎾','Sukan'],['📓','Buku'],['🎨','Seni']] },
      { pairs: [['🍑','Buah'],['🐧','Haiwan'],['🚛','Kenderaan'],['❄️','Langit'],['🎺','Muzik'],['🌺','Bunga'],['⛳','Sukan'],['📕','Buku'],['🖌️','Seni'],['🍕','Makanan']] },
      { pairs: [['🍒','Buah'],['🐬','Haiwan'],['🚁','Kenderaan'],['⚡','Langit'],['🎻','Muzik'],['🪷','Bunga'],['🏐','Sukan'],['📗','Buku'],['🖍️','Seni'],['🍔','Makanan'],['👕','Pakaian'],['⌚','Aksesori']] },
    ]),
  },
  {
    id: 'brain-pilih-ganjil',
    title: 'Cari Yang Ganjil',
    emoji: '🔍',
    mode: 'picture_hunt',
    objective: 'Pilih yang BERBEZA dari kumpulan.',
    reward: 'Odd one out',
    rounds: makeRounds([
      { target: '🐟', items: ['🐯','🐯','🐟'] },
      { target: '🍎', items: ['🐯','🐯','🍎','🐯'] },
      { target: '🚗', items: ['⭐','⭐','⭐','🚗','⭐'] },
      { target: '🌸', items: ['🍎','🍎','🌸','🍎','🍎','🍎'] },
      { target: '🦋', items: ['🐯','🐯','🐯','🐯','🦋','🐯','🐯'] },
      { target: '🎈', items: ['⚽','⚽','⚽','⚽','⚽','🎈','⚽','⚽'] },
      { target: '📚', items: ['✏️','✏️','✏️','✏️','✏️','✏️','📚','✏️','✏️'] },
      { target: '🌊', items: ['🌳','🌳','🌳','🌳','🌳','🌊','🌳','🌳','🌳','🌳'] },
      { target: '⚡', items: ['☁️','☁️','☁️','☁️','☁️','☁️','⚡','☁️','☁️','☁️','☁️'] },
      { target: '🎨', items: ['📖','📖','📖','📖','📖','📖','📖','🎨','📖','📖','📖','📖'] },
    ]),
  },
  {
    id: 'brain-aritmetik',
    title: 'Padan Aritmetik',
    emoji: '➗',
    mode: 'tilematch',
    objective: 'Padankan soalan dengan jawapan.',
    reward: 'Math match',
    rounds: makeRounds([
      { tiles: ['1+1','2','2+2','4'] },
      { tiles: ['1+1','2','2+2','4','3+3','6'] },
      { tiles: ['5+5','10','4+4','8','3+3','6'] },
      { tiles: ['2×2','4','3×3','9','4×4','16'] },
      { tiles: ['10-5','5','20-10','10','15-5','10','30-15','15'] },
      { tiles: ['2×3','6','3×4','12','5×5','25','4×6','24'] },
      { tiles: ['10÷2','5','20÷4','5','15÷3','5','30÷6','5'] },
      { tiles: ['2+3','5','3×3','9','10-4','6','15÷3','5','4×2','8'] },
      { tiles: ['7+8','15','9×9','81','100-25','75','144÷12','12','5×7','35'] },
      { tiles: ['12+8','20','11×11','121','100-37','63','144÷9','16','15×3','45','81÷9','9'] },
    ]),
  },
  {
    id: 'brain-warna-stroop',
    title: 'Pilih Warna Bukan Tulisan',
    emoji: '🌈',
    mode: 'swipe_select',
    objective: 'Pilih warna emoji, bukan perkataan.',
    reward: 'Focus elite',
    rounds: makeRounds([
      { groups: ['Merah','Biru'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'}] },
      { groups: ['Merah','Biru'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🔴',group:'Merah'}] },
      { groups: ['Merah','Biru','Hijau'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'}] },
      { groups: ['Merah','Biru','Hijau','Kuning'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'}] },
      { groups: ['Merah','Biru','Hijau','Kuning'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🔴',group:'Merah'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🔵',group:'Biru'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'🟢',group:'Hijau'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'🔴',group:'Merah'},{text:'🟡',group:'Kuning'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga','Hitam'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'⚫',group:'Hitam'},{text:'🟢',group:'Hijau'},{text:'🔴',group:'Merah'}] },
      { groups: ['Merah','Biru','Hijau','Kuning','Ungu','Jingga','Hitam','Putih'], items: [{text:'🔴',group:'Merah'},{text:'🔵',group:'Biru'},{text:'🟢',group:'Hijau'},{text:'🟡',group:'Kuning'},{text:'🟣',group:'Ungu'},{text:'🟠',group:'Jingga'},{text:'⚫',group:'Hitam'},{text:'⚪',group:'Putih'},{text:'🟢',group:'Hijau'},{text:'🔴',group:'Merah'}] },
    ]),
  },
  {
    id: 'brain-fakta-kilat',
    title: 'Fakta Kilat',
    emoji: '⚡',
    mode: 'true_false',
    objective: 'Jawab pantas — betul atau salah?',
    reward: 'Snap fact',
    rounds: makeRounds([
      { statements: [{text:'Malaysia ada 13 negeri.',answer:true},{text:'KL di Sabah.',answer:false}] },
      { statements: [{text:'Bunga Raya bunga rasmi negara.',answer:true},{text:'Hari Merdeka 31 Disember.',answer:false}] },
      { statements: [{text:'Bahasa rasmi Bahasa Melayu.',answer:true},{text:'Lagu Negaraku ada 5 baris.',answer:false},{text:'Pulau Pinang ada Jambatan Pulau Pinang.',answer:true}] },
      { statements: [{text:'KLCC ada 88 tingkat.',answer:true},{text:'Mount Kinabalu di Sarawak.',answer:false},{text:'Tunku Abdul Rahman PM pertama.',answer:true},{text:'Bandar Hilang dari ASEAN.',answer:false}] },
      { statements: [{text:'5+5=10.',answer:true},{text:'7×8=64.',answer:false},{text:'100-25=75.',answer:true},{text:'144÷12=12.',answer:true},{text:'9×9=99.',answer:false}] },
      { statements: [{text:'Air mendidih pada 100°C.',answer:true},{text:'Bumi planet ke-3.',answer:true},{text:'Bulan lebih besar dari Bumi.',answer:false},{text:'Magnet tarik plastik.',answer:false},{text:'Manusia ada 32 gigi dewasa.',answer:true},{text:'Otot ada di tulang.',answer:true}] },
      { statements: [{text:'Bahasa Inggeris ada 26 huruf.',answer:true},{text:'Bulan November ada 30 hari.',answer:true},{text:'Februari ada 28/29 hari.',answer:true},{text:'Setahun ada 12 bulan.',answer:true},{text:'Sehari ada 25 jam.',answer:false},{text:'Sejam ada 60 minit.',answer:true},{text:'Seminit ada 60 saat.',answer:true}] },
      { statements: [{text:'Petronas Twin Towers di KL.',answer:true},{text:'Langkawi di Selangor.',answer:false},{text:'Cameron di Pahang.',answer:true},{text:'Sabah dan Sarawak di Borneo.',answer:true},{text:'Putrajaya pusat pentadbiran.',answer:true},{text:'KLIA singkatan Kuala Lumpur International Airport.',answer:true},{text:'LRT ialah keretapi bawah tanah.',answer:false},{text:'MRT lebih moden dari LRT.',answer:true}] },
      { statements: [{text:'Bola sepak Malaysia "Harimau Malaya".',answer:true},{text:'Badminton sukan popular Malaysia.',answer:true},{text:'Lee Chong Wei pemain badminton.',answer:true},{text:'Nicol David pemain skuasy.',answer:true},{text:'Datuk pangkat kebangsaan.',answer:true},{text:'Sukan SEA setiap 5 tahun.',answer:false},{text:'Sukan Olimpik setiap 4 tahun.',answer:true},{text:'KL hosted SEA Games 2017.',answer:true},{text:'Sepak takraw guna kepala/kaki.',answer:true}] },
      { statements: [{text:'Bunga Raya simbol negara.',answer:true},{text:'Harimau Malaya simbol negara.',answer:true},{text:'14 jalur biru pada bendera.',answer:false},{text:'Bulan & Bintang pada bendera.',answer:true},{text:'5 prinsip Rukun Negara.',answer:true},{text:'Lagu Negaraku berasal dari Perak.',answer:true},{text:'Sultan ada di setiap negeri.',answer:false},{text:'9 negeri ada Sultan/Raja.',answer:true},{text:'Yang di-Pertuan Agong dipilih.',answer:true},{text:'Tugu Negara ada 7 patung.',answer:true}] },
    ]),
  },
  {
    id: 'brain-mix-mode',
    title: 'Cabaran Campuran',
    emoji: '🧩',
    mode: 'sorting',
    objective: 'Kelaskan benda ikut konsep.',
    reward: 'Final brain',
    rounds: makeRounds([
      { groups: ['Hidup','Bukan Hidup'], items: [{text:'Pokok',group:'Hidup'},{text:'Batu',group:'Bukan Hidup'}] },
      { groups: ['Hidup','Bukan Hidup'], items: [{text:'Pokok',group:'Hidup'},{text:'Batu',group:'Bukan Hidup'},{text:'Manusia',group:'Hidup'}] },
      { groups: ['Hidup','Bukan Hidup'], items: [{text:'Pokok',group:'Hidup'},{text:'Batu',group:'Bukan Hidup'},{text:'Manusia',group:'Hidup'},{text:'Kerusi',group:'Bukan Hidup'}] },
      { groups: ['Boleh Bergerak','Tidak Bergerak'], items: [{text:'Kucing',group:'Boleh Bergerak'},{text:'Batu',group:'Tidak Bergerak'},{text:'Burung',group:'Boleh Bergerak'},{text:'Pokok',group:'Tidak Bergerak'}] },
      { groups: ['Panas','Sejuk'], items: [{text:'Matahari',group:'Panas'},{text:'Ais',group:'Sejuk'},{text:'Api',group:'Panas'},{text:'Salji',group:'Sejuk'},{text:'Lava',group:'Panas'}] },
      { groups: ['Makanan','Bukan Makanan'], items: [{text:'Nasi',group:'Makanan'},{text:'Plastik',group:'Bukan Makanan'},{text:'Roti',group:'Makanan'},{text:'Logam',group:'Bukan Makanan'},{text:'Pisang',group:'Makanan'},{text:'Batu',group:'Bukan Makanan'}] },
      { groups: ['Berat','Ringan'], items: [{text:'Gajah',group:'Berat'},{text:'Bulu',group:'Ringan'},{text:'Batu Besar',group:'Berat'},{text:'Kapas',group:'Ringan'},{text:'Kereta',group:'Berat'},{text:'Daun',group:'Ringan'},{text:'Bulan',group:'Berat'}] },
      { groups: ['Manusia','Haiwan','Tumbuhan'], items: [{text:'Murid',group:'Manusia'},{text:'Kucing',group:'Haiwan'},{text:'Pokok',group:'Tumbuhan'},{text:'Doktor',group:'Manusia'},{text:'Helang',group:'Haiwan'},{text:'Bunga',group:'Tumbuhan'},{text:'Polis',group:'Manusia'}] },
      { groups: ['Manusia','Haiwan','Tumbuhan','Buatan'], items: [{text:'Murid',group:'Manusia'},{text:'Kucing',group:'Haiwan'},{text:'Pokok',group:'Tumbuhan'},{text:'Robot',group:'Buatan'},{text:'Helang',group:'Haiwan'},{text:'Bunga',group:'Tumbuhan'},{text:'Kereta',group:'Buatan'},{text:'Doktor',group:'Manusia'}] },
      { groups: ['Pagi','Tengah Hari','Petang','Malam'], items: [{text:'Sarapan',group:'Pagi'},{text:'Makan Tengah Hari',group:'Tengah Hari'},{text:'Teh Petang',group:'Petang'},{text:'Makan Malam',group:'Malam'},{text:'Solat Subuh',group:'Pagi'},{text:'Solat Zohor',group:'Tengah Hari'},{text:'Solat Asar',group:'Petang'},{text:'Solat Isyak',group:'Malam'}] },
    ]),
  },
];