// 🎨 CREATIVE BUILDER — 10 games × 10 rounds. Kreatif + bina.
import { makeRounds } from './_helpers.js';

export const creativeBuilderGames = [
  {
    id: 'creative-warna-pelangi',
    title: 'Warnakan Bunga',
    emoji: '🌸',
    mode: 'coloring',
    objective: 'Warnakan semua gambar.',
    reward: 'Color sticker',
    rounds: makeRounds([
      { items: ['🌸','🌻'] },
      { items: ['🌸','🌻','🌹'] },
      { items: ['🌸','🌻','🌹','🌷'] },
      { items: ['🌸','🌻','🌹','🌷','🌺'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷','💐'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷','💐','🌾'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷','💐','🌾','🌿','🍀'] },
    ]),
  },
  {
    id: 'creative-bina-menara',
    title: 'Bina Menara KLCC',
    emoji: '🏗️',
    mode: 'stacking',
    objective: 'Susun blok sehingga tinggi sasaran.',
    reward: 'Builder sparkle',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({target:3+i}))),
  },
  {
    id: 'creative-bina-rumah',
    title: 'Bina Rumah Tradisi',
    emoji: '🏠',
    mode: 'dragdrop',
    objective: 'Letak bahagian rumah di tempat betul.',
    reward: 'Heritage build',
    rounds: makeRounds([
      { items: ['Bumbung','Pintu'], targets: ['Atas','Depan'] },
      { items: ['Bumbung','Pintu','Tingkap'], targets: ['Atas','Depan','Sebelah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga'], targets: ['Atas','Depan','Sebelah','Bawah'] },
      { items: ['Bumbung Limas','Pintu','Tingkap','Tangga','Tiang'], targets: ['Atas','Depan','Sisi','Bawah','Sokongan'] },
      { items: ['Bumbung','Pintu','Tingkap Kayu','Tangga','Anjung','Pagar'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan Rumah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan Rumah','Bumbung Atas'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur Luar'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan Rumah','Bumbung Atas','Belakang Rumah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur','Garaj'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan','Bumbung','Belakang','Tepi'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur','Garaj','Bilik Air'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah','Depan','Bumbung Atas','Belakang','Tepi','Dalam Rumah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur','Garaj','Bilik Air','Loteng','Balkoni'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah','Depan','Bumbung','Belakang','Tepi','Dalam','Tingkat Atas','Tingkat Dua'] },
    ]),
  },
  {
    id: 'creative-padan-warna',
    title: 'Padan Warna Sebenar',
    emoji: '🎨',
    mode: 'memory',
    objective: 'Padankan objek dengan warnanya.',
    reward: 'Color match',
    rounds: makeRounds([
      { pairs: [['🍎','Merah'],['🍌','Kuning']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga']] },
      { pairs: [['🍅','Merah'],['🌽','Kuning'],['🥒','Hijau'],['🍇','Ungu'],['🥥','Coklat'],['🥚','Putih']] },
      { pairs: [['🍓','Merah'],['🍍','Kuning'],['🥝','Hijau'],['🫐','Biru'],['🍆','Ungu'],['🥕','Jingga'],['🌶️','Merah Cili']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga'],['🥥','Coklat'],['🥚','Putih']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga'],['🥥','Coklat'],['🥚','Putih'],['🍆','Ungu Tua']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga'],['🥥','Coklat'],['🥚','Putih'],['🍆','Ungu Tua'],['🍓','Merah Manis']] },
    ]),
  },
  {
    id: 'creative-susun-puzzle',
    title: 'Susun Puzzle Bentuk',
    emoji: '🧩',
    mode: 'sorting',
    objective: 'Asingkan bentuk ke kotak yang betul.',
    reward: 'Puzzle solve',
    rounds: makeRounds([
      { groups: ['Bulat','Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'⬛',group:'Sudut'},{text:'🔵',group:'Bulat'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'🔵',group:'Bulat'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'🔵',group:'Bulat'},{text:'🟦',group:'Empat Sudut'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut','Bintang'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'⭐',group:'Bintang'},{text:'🟦',group:'Empat Sudut'}] },
      { groups: ['2D','3D'], items: [{text:'🟦',group:'2D'},{text:'📦',group:'3D'},{text:'⚪',group:'2D'},{text:'⚽',group:'3D'},{text:'🔺',group:'2D'},{text:'🔷',group:'2D'}] },
      { groups: ['Simetri','Tak Simetri'], items: [{text:'🦋',group:'Simetri'},{text:'🍃',group:'Tak Simetri'},{text:'⭐',group:'Simetri'},{text:'🌀',group:'Tak Simetri'},{text:'❄️',group:'Simetri'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut','Banyak Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'⭐',group:'Banyak Sudut'},{text:'🔵',group:'Bulat'},{text:'🟦',group:'Empat Sudut'},{text:'⬢',group:'Banyak Sudut'}] },
      { groups: ['Bulat','Sudut Tajam','Sudut Tumpul'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Sudut Tajam'},{text:'⬛',group:'Sudut Tumpul'},{text:'🔵',group:'Bulat'},{text:'⭐',group:'Sudut Tajam'},{text:'🟦',group:'Sudut Tumpul'},{text:'⬡',group:'Sudut Tumpul'}] },
      { groups: ['Geometri','Organik','Hiasan'], items: [{text:'🟦',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'✨',group:'Hiasan'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'⭐',group:'Hiasan'},{text:'⬛',group:'Geometri'},{text:'🦋',group:'Organik'},{text:'💫',group:'Hiasan'}] },
    ]),
  },
  {
    id: 'creative-bina-perkataan',
    title: 'Bina Perkataan',
    emoji: '📝',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan.',
    reward: 'Word craft',
    rounds: makeRounds([
      { target: 'IBU', letters: ['B','I','U'] },
      { target: 'AYAH', letters: ['A','Y','A','H'] },
      { target: 'BUKU', letters: ['B','U','K','U'] },
      { target: 'SUSU', letters: ['S','U','S','U'] },
      { target: 'RUMAH', letters: ['R','U','M','A','H'] },
      { target: 'KUCING', letters: ['K','U','C','I','N','G'] },
      { target: 'BASIKAL', letters: ['B','A','S','I','K','A','L'] },
      { target: 'SEKOLAH', letters: ['S','E','K','O','L','A','H'] },
      { target: 'MATAHARI', letters: ['M','A','T','A','H','A','R','I'] },
      { target: 'KEMERDEKAAN', letters: ['K','E','M','E','R','D','E','K','A','A','N'] },
    ]),
  },
  {
    id: 'creative-warna-haiwan',
    title: 'Warnakan Haiwan',
    emoji: '🦋',
    mode: 'coloring',
    objective: 'Warnakan setiap haiwan kebun.',
    reward: 'Animal art',
    rounds: makeRounds([
      { items: ['🐢','🦋'] },
      { items: ['🐢','🦋','🐝'] },
      { items: ['🐢','🦋','🐝','🐞'] },
      { items: ['🐢','🦋','🐝','🐞','🐌'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜','🕷️'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜','🕷️','🐍'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜','🕷️','🐍','🦎','🐸'] },
    ]),
  },
  {
    id: 'creative-bina-ayat',
    title: 'Bina Ayat Mudah',
    emoji: '✏️',
    mode: 'sequence',
    objective: 'Susun perkataan jadi ayat.',
    reward: 'Sentence craft',
    rounds: makeRounds([
      { items: ['Saya','makan'], answer: ['Saya','makan'] },
      { items: ['Saya','makan','nasi'], answer: ['Saya','makan','nasi'] },
      { items: ['Ibu','memasak','sup'], answer: ['Ibu','memasak','sup'] },
      { items: ['Ayah','baca','surat','khabar'], answer: ['Ayah','baca','surat','khabar'] },
      { items: ['Adik','bermain','di','taman'], answer: ['Adik','bermain','di','taman'] },
      { items: ['Saya','suka','makan','nasi','lemak'], answer: ['Saya','suka','makan','nasi','lemak'] },
      { items: ['Kakak','membaca','buku','di','perpustakaan'], answer: ['Kakak','membaca','buku','di','perpustakaan'] },
      { items: ['Kami','pergi','ke','sekolah','setiap','hari'], answer: ['Kami','pergi','ke','sekolah','setiap','hari'] },
      { items: ['Pak','Cik','memandu','kereta','ke','pejabat','pagi'], answer: ['Pak','Cik','memandu','kereta','ke','pejabat','pagi'] },
      { items: ['Pada','hari','minggu','keluarga','saya','pergi','ke','pantai'], answer: ['Pada','hari','minggu','keluarga','saya','pergi','ke','pantai'] },
    ]),
  },
  {
    id: 'creative-roda-cerita',
    title: 'Roda Idea Cerita',
    emoji: '🎡',
    mode: 'spin_wheel',
    objective: 'Putar roda untuk dapatkan idea cerita.',
    reward: 'Story spark',
    rounds: makeRounds([
      { items: ['Kucing','Anjing','Burung'] },
      { items: ['Hutan','Pantai','Bandar','Gunung'] },
      { items: ['Wira','Putera','Pengembara','Pencipta','Saintis'] },
      { items: ['Pagi','Tengah Hari','Petang','Malam','Subuh','Tengah Malam'] },
      { items: ['Gembira','Sedih','Berani','Takut','Marah','Kagum','Riang'] },
      { items: ['Buaya','Helang','Harimau','Gajah','Penyu','Monyet','Rusa','Kelawar'] },
      { items: ['Misteri','Petualangan','Persahabatan','Sains','Sukan','Komedi','Sejarah','Fantasi','Cinta'] },
      { items: ['Sekolah','Rumah','Taman','Pasar','Sungai','Tasik','Kapal','Pesawat','Stesen','Pulau'] },
      { items: ['Mengembara','Menyelamat','Mencari Harta','Belajar','Berlawan','Tolong Kawan','Pulang','Membina','Memenangi Perlawanan','Mencipta Sesuatu'] },
      { items: ['Pelajar','Doktor','Guru','Polis','Bomba','Saintis','Penulis','Cef','Jurutera','Petani','Pilot','Pelaut'] },
    ]),
  },
  {
    id: 'creative-bina-pelangi',
    title: 'Susun Warna Pelangi',
    emoji: '🌈',
    mode: 'sequence',
    objective: 'Susun warna pelangi mengikut urutan.',
    reward: 'Rainbow build',
    rounds: makeRounds([
      { items: ['🔴','🟠'], answer: ['🔴','🟠'] },
      { items: ['🔴','🟠','🟡'], answer: ['🔴','🟠','🟡'] },
      { items: ['🔴','🟠','🟡','🟢'], answer: ['🔴','🟠','🟡','🟢'] },
      { items: ['🔴','🟠','🟡','🟢','🔵'], answer: ['🔴','🟠','🟡','🟢','🔵'] },
      { items: ['🔴','🟠','🟡','🟢','🔵','🟣'], answer: ['🔴','🟠','🟡','🟢','🔵','🟣'] },
      { items: ['🔴','🟠','🟡','🟢','🔵','🟣','🟤'], answer: ['🔴','🟠','🟡','🟢','🔵','🟣','🟤'] },
      { items: ['🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫'], answer: ['🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫'] },
      { items: ['🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫','⚪'], answer: ['🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫','⚪'] },
      { items: ['🩷','🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫'], answer: ['🩷','🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫'] },
      { items: ['🩷','🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫','⚪'], answer: ['🩷','🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫','⚪'] },
    ]),
  },
];