// 🎨 CREATIVE BUILDER — 10 games × 10 rounds. Tema campuran (kreatif, bina, susun).
import { makeRounds } from './_helpers.js';

export const creativeBuilderGames = [
  {
    id: 'creative-warna-pokok',
    title: 'Warnakan Pokok',
    emoji: '🌳',
    mode: 'coloring',
    objective: 'Warnakan setiap pokok dan tumbuhan.',
    reward: 'Tree art',
    rounds: makeRounds([
      { items: ['🌳','🌲'] },
      { items: ['🌳','🌲','🌴'] },
      { items: ['🌳','🌲','🌴','🌵'] },
      { items: ['🌳','🌲','🌴','🌵','🌿'] },
      { items: ['🌳','🌲','🌴','🌵','🌿','🍀'] },
      { items: ['🌳','🌲','🌴','🌵','🌿','🍀','🍃'] },
      { items: ['🌳','🌲','🌴','🌵','🌿','🍀','🍃','☘️'] },
      { items: ['🌳','🌲','🌴','🌵','🌿','🍀','🍃','☘️','🌱'] },
      { items: ['🌳','🌲','🌴','🌵','🌿','🍀','🍃','☘️','🌱','🌾'] },
      { items: ['🌳','🌲','🌴','🌵','🌿','🍀','🍃','☘️','🌱','🌾','🪴','🎋'] },
    ]),
  },
  {
    id: 'creative-bina-blok',
    title: 'Susun Blok Tinggi',
    emoji: '📦',
    mode: 'stacking',
    objective: 'Susun blok sehingga capai sasaran.',
    reward: 'Stack master',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({target:3+i}))),
  },
  {
    id: 'creative-bina-bandar',
    title: 'Bina Bandar Aku',
    emoji: '🏙️',
    mode: 'dragdrop',
    objective: 'Letak bangunan di kawasan betul.',
    reward: 'City build',
    rounds: makeRounds([
      { items: ['Rumah','Sekolah'], targets: ['Kawasan Perumahan','Kawasan Pendidikan'] },
      { items: ['Rumah','Sekolah','Hospital'], targets: ['Perumahan','Pendidikan','Kesihatan'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai','Taman'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial','Rekreasi'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai','Taman','Masjid'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial','Rekreasi','Ibadah'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai','Taman','Masjid','Stesen Bomba'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial','Rekreasi','Ibadah','Kecemasan'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai','Taman','Masjid','Bomba','Polis'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial','Rekreasi','Ibadah','Kecemasan','Keselamatan'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai','Taman','Masjid','Bomba','Polis','Bank'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial','Rekreasi','Ibadah','Kecemasan','Keselamatan','Kewangan'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai','Taman','Masjid','Bomba','Polis','Bank','Stesen LRT'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial','Rekreasi','Ibadah','Kecemasan','Keselamatan','Kewangan','Pengangkutan'] },
      { items: ['Rumah','Sekolah','Hospital','Kedai','Taman','Masjid','Bomba','Polis','Bank','LRT','Kilang','Pejabat'], targets: ['Perumahan','Pendidikan','Kesihatan','Komersial','Rekreasi','Ibadah','Kecemasan','Keselamatan','Kewangan','Pengangkutan','Industri','Korporat'] },
    ]),
  },
  {
    id: 'creative-warna-objek',
    title: 'Padan Objek dengan Warna',
    emoji: '🎨',
    mode: 'memory',
    objective: 'Padankan objek dengan warna asalnya.',
    reward: 'Color sense',
    rounds: makeRounds([
      { pairs: [['🌞','Kuning'],['🌊','Biru']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah'],['🍆','Ungu']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah'],['🍆','Ungu'],['🥕','Jingga']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah'],['🍆','Ungu'],['🥕','Jingga'],['🥥','Coklat']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah'],['🍆','Ungu'],['🥕','Jingga'],['🥥','Coklat'],['⚫','Hitam']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah'],['🍆','Ungu'],['🥕','Jingga'],['🥥','Coklat'],['⚫','Hitam'],['⚪','Putih']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah'],['🍆','Ungu'],['🥕','Jingga'],['🥥','Coklat'],['⚫','Hitam'],['⚪','Putih'],['🩷','Pink']] },
      { pairs: [['🌞','Kuning'],['🌊','Biru'],['🌳','Hijau'],['🍓','Merah'],['🍆','Ungu'],['🥕','Jingga'],['🥥','Coklat'],['⚫','Hitam'],['⚪','Putih'],['🩷','Pink'],['🩶','Kelabu']] },
    ]),
  },
  {
    id: 'creative-puzzle-jubin',
    title: 'Susun Jubin Lantai',
    emoji: '🟧',
    mode: 'sorting',
    objective: 'Asingkan jubin ikut bentuk.',
    reward: 'Tile solve',
    rounds: makeRounds([
      { groups: ['Bulat','Segi Empat'], items: [{text:'⚪',group:'Bulat'},{text:'🟧',group:'Segi Empat'},{text:'🔵',group:'Bulat'}] },
      { groups: ['Bulat','Segi Empat','Segi Tiga'], items: [{text:'⚪',group:'Bulat'},{text:'🟧',group:'Segi Empat'},{text:'🔺',group:'Segi Tiga'}] },
      { groups: ['Bulat','Segi Empat','Segi Tiga'], items: [{text:'⚪',group:'Bulat'},{text:'🟧',group:'Segi Empat'},{text:'🔺',group:'Segi Tiga'},{text:'🔵',group:'Bulat'}] },
      { groups: ['Bulat','Segi Empat','Segi Tiga','Bintang'], items: [{text:'⚪',group:'Bulat'},{text:'🟧',group:'Segi Empat'},{text:'🔺',group:'Segi Tiga'},{text:'⭐',group:'Bintang'},{text:'🟦',group:'Segi Empat'}] },
      { groups: ['Kecil','Sederhana','Besar'], items: [{text:'•',group:'Kecil'},{text:'⚪',group:'Sederhana'},{text:'🌕',group:'Besar'},{text:'·',group:'Kecil'},{text:'⭕',group:'Sederhana'}] },
      { groups: ['Bulat','Segi Empat','Segi Tiga','Heksagon'], items: [{text:'⚪',group:'Bulat'},{text:'🟧',group:'Segi Empat'},{text:'🔺',group:'Segi Tiga'},{text:'🟪',group:'Heksagon'},{text:'🔵',group:'Bulat'},{text:'🟦',group:'Segi Empat'}] },
      { groups: ['Bulat','Segi 4','Segi 3','Bintang','Hati'], items: [{text:'⚪',group:'Bulat'},{text:'🟧',group:'Segi 4'},{text:'🔺',group:'Segi 3'},{text:'⭐',group:'Bintang'},{text:'❤️',group:'Hati'},{text:'💙',group:'Hati'},{text:'🔵',group:'Bulat'}] },
      { groups: ['Bulat','Lurus','Bersudut'], items: [{text:'⚪',group:'Bulat'},{text:'➖',group:'Lurus'},{text:'🔺',group:'Bersudut'},{text:'🔵',group:'Bulat'},{text:'➕',group:'Lurus'},{text:'⬛',group:'Bersudut'}] },
      { groups: ['2D','3D'], items: [{text:'🟧',group:'2D'},{text:'📦',group:'3D'},{text:'⚪',group:'2D'},{text:'⚽',group:'3D'},{text:'🔺',group:'2D'},{text:'🎲',group:'3D'},{text:'🟫',group:'2D'}] },
      { groups: ['Bulat','Segi 4','Segi 3','Bintang','Hati','Berlian'], items: [{text:'⚪',group:'Bulat'},{text:'🟧',group:'Segi 4'},{text:'🔺',group:'Segi 3'},{text:'⭐',group:'Bintang'},{text:'❤️',group:'Hati'},{text:'💎',group:'Berlian'},{text:'🔵',group:'Bulat'},{text:'🟦',group:'Segi 4'}] },
    ]),
  },
  {
    id: 'creative-perkataan-haiwan',
    title: 'Bina Perkataan Haiwan',
    emoji: '🐱',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi nama haiwan.',
    reward: 'Animal word',
    rounds: makeRounds([
      { target: 'ITIK', letters: ['I','T','I','K'] },
      { target: 'AYAM', letters: ['A','Y','A','M'] },
      { target: 'IKAN', letters: ['I','K','A','N'] },
      { target: 'LEMBU', letters: ['L','E','M','B','U'] },
      { target: 'KAMBING', letters: ['K','A','M','B','I','N','G'] },
      { target: 'KUCING', letters: ['K','U','C','I','N','G'] },
      { target: 'HARIMAU', letters: ['H','A','R','I','M','A','U'] },
      { target: 'KUPU-KUPU', letters: ['K','U','P','U','-','K','U','P','U'] },
      { target: 'GAJAH', letters: ['G','A','J','A','H'] },
      { target: 'KELIP-KELIP', letters: ['K','E','L','I','P','-','K','E','L','I','P'] },
    ]),
  },
  {
    id: 'creative-warna-kenderaan',
    title: 'Warnakan Kenderaan',
    emoji: '🚗',
    mode: 'coloring',
    objective: 'Warnakan setiap kenderaan.',
    reward: 'Vehicle art',
    rounds: makeRounds([
      { items: ['🚗','🚌'] },
      { items: ['🚗','🚌','🚲'] },
      { items: ['🚗','🚌','🚲','✈️'] },
      { items: ['🚗','🚌','🚲','✈️','🚂'] },
      { items: ['🚗','🚌','🚲','✈️','🚂','🚢'] },
      { items: ['🚗','🚌','🚲','✈️','🚂','🚢','🚁'] },
      { items: ['🚗','🚌','🚲','✈️','🚂','🚢','🚁','🛵'] },
      { items: ['🚗','🚌','🚲','✈️','🚂','🚢','🚁','🛵','🚜'] },
      { items: ['🚗','🚌','🚲','✈️','🚂','🚢','🚁','🛵','🚜','🚀'] },
      { items: ['🚗','🚌','🚲','✈️','🚂','🚢','🚁','🛵','🚜','🚀','⛵','🛸'] },
    ]),
  },
  {
    id: 'creative-perkataan-buah',
    title: 'Bina Nama Buah',
    emoji: '🍇',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi nama buah.',
    reward: 'Fruit word',
    rounds: makeRounds([
      { target: 'EPAL', letters: ['E','P','A','L'] },
      { target: 'OREN', letters: ['O','R','E','N'] },
      { target: 'PISANG', letters: ['P','I','S','A','N','G'] },
      { target: 'MANGGA', letters: ['M','A','N','G','G','A'] },
      { target: 'KELAPA', letters: ['K','E','L','A','P','A'] },
      { target: 'NANAS', letters: ['N','A','N','A','S'] },
      { target: 'DURIAN', letters: ['D','U','R','I','A','N'] },
      { target: 'RAMBUTAN', letters: ['R','A','M','B','U','T','A','N'] },
      { target: 'TEMBIKAI', letters: ['T','E','M','B','I','K','A','I'] },
      { target: 'STRAWBERI', letters: ['S','T','R','A','W','B','E','R','I'] },
    ]),
  },
  {
    id: 'creative-padan-cerita',
    title: 'Padan Watak dengan Cerita',
    emoji: '📖',
    mode: 'memory',
    objective: 'Padankan watak dengan cerita.',
    reward: 'Story match',
    rounds: makeRounds([
      { pairs: [['🐺','Si Tanggang'],['🐅','Bawang Putih']] },
      { pairs: [['🐺','Si Tanggang'],['🐅','Bawang Putih'],['🐢','Sang Kancil']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga'],['🧙','Ahli Sihir']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga'],['🧙','Ahli Sihir'],['🧚','Pari-pari']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga'],['🧙','Ahli Sihir'],['🧚','Pari-pari'],['🦸','Wira']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga'],['🧙','Ahli Sihir'],['🧚','Pari-pari'],['🦸','Wira'],['🧞','Jin']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga'],['🧙','Ahli Sihir'],['🧚','Pari-pari'],['🦸','Wira'],['🧞','Jin'],['🧜','Duyung']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga'],['🧙','Ahli Sihir'],['🧚','Pari-pari'],['🦸','Wira'],['🧞','Jin'],['🧜','Duyung'],['🧛','Pontianak']] },
      { pairs: [['👸','Puteri'],['🤴','Putera'],['🐉','Naga'],['🧙','Ahli Sihir'],['🧚','Pari-pari'],['🦸','Wira'],['🧞','Jin'],['🧜','Duyung'],['🧛','Pontianak'],['🧟','Zombi']] },
    ]),
  },
  {
    id: 'creative-pop-bentuk-bunga',
    title: 'Pop Bunga Warna-warni',
    emoji: '🌷',
    mode: 'balloon_pop',
    objective: 'Pop bunga sasaran sahaja.',
    reward: 'Flower pop',
    rounds: makeRounds([
      { target: '🌸', items: ['🌸','🌻','🌸'] },
      { target: '🌻', items: ['🌻','🌹','🌻','🌷'] },
      { target: '🌹', items: ['🌹','🌷','🌹','🌺','🌹'] },
      { target: '🌷', items: ['🌷','🌺','🌷','🪻','🌷','💐'] },
      { target: '🌺', items: ['🌺','🪻','🌺','💐','🌺','🌼','🌺'] },
      { target: '🪻', items: ['🪻','💐','🪻','🌼','🪻','🪷','🪻','🌾'] },
      { target: '💐', items: ['💐','🌼','💐','🪷','💐','🌾','💐','🌸','💐'] },
      { target: '🌼', items: ['🌼','🪷','🌼','🌾','🌼','🌸','🌼','🌻','🌼','🌹'] },
      { target: '🪷', items: ['🪷','🌾','🪷','🌸','🪷','🌻','🪷','🌹','🪷','🌷','🪷'] },
      { target: '🌾', items: ['🌾','🌸','🌾','🌻','🌾','🌹','🌾','🌷','🌾','🌺','🌾','🪻'] },
    ]),
  },
];