// 🎨 CREATIVE BUILDER — 10 games × 10 rounds. Kreatif + bina.
import { makeRounds } from './_helpers.js';

export const creativeBuilderGames = [
  {
    id: 'creative-warna-pelangi',
    title: 'Warnakan Bunga',
    emoji: '🌸',
    mode: 'coloring',
    objective: 'Warnakan semua gambar.',
    reward: 'Color sticker',
    rounds: makeRounds([
      { items: ['🌸','🌻'] },
      { items: ['🌸','🌻','🌹'] },
      { items: ['🌸','🌻','🌹','🌷'] },
      { items: ['🌸','🌻','🌹','🌷','🌺'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷','💐'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷','💐','🌾'] },
      { items: ['🌸','🌻','🌹','🌷','🌺','🪻','🌼','🪷','💐','🌾','🌿','🍀'] },
    ]),
  },
  {
    id: 'creative-bina-menara',
    title: 'Bina Menara KLCC',
    emoji: '🏗️',
    mode: 'stacking',
    objective: 'Susun blok sehingga tinggi sasaran.',
    reward: 'Builder sparkle',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({target:3+i}))),
  },
  {
    id: 'creative-bina-rumah',
    title: 'Bina Rumah Tradisi',
    emoji: '🏠',
    mode: 'dragdrop',
    objective: 'Letak bahagian rumah di tempat betul.',
    reward: 'Heritage build',
    rounds: makeRounds([
      { items: ['Bumbung','Pintu'], targets: ['Atas','Depan'] },
      { items: ['Bumbung','Pintu','Tingkap'], targets: ['Atas','Depan','Sebelah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga'], targets: ['Atas','Depan','Sebelah','Bawah'] },
      { items: ['Bumbung Limas','Pintu','Tingkap','Tangga','Tiang'], targets: ['Atas','Depan','Sisi','Bawah','Sokongan'] },
      { items: ['Bumbung','Pintu','Tingkap Kayu','Tangga','Anjung','Pagar'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan Rumah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan Rumah','Bumbung Atas'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur Luar'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan Rumah','Bumbung Atas','Belakang Rumah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur','Garaj'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah Pintu','Depan','Bumbung','Belakang','Tepi'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur','Garaj','Bilik Air'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah','Depan','Bumbung Atas','Belakang','Tepi','Dalam Rumah'] },
      { items: ['Bumbung','Pintu','Tingkap','Tangga','Anjung','Pagar','Cerobong','Dapur','Garaj','Bilik Air','Loteng','Balkoni'], targets: ['Atas','Depan','Sisi','Bawah','Sebelah','Depan','Bumbung','Belakang','Tepi','Dalam','Tingkat Atas','Tingkat Dua'] },
    ]),
  },
  {
    id: 'creative-padan-warna',
    title: 'Padan Warna Sebenar',
    emoji: '🎨',
    mode: 'memory',
    objective: 'Padankan objek dengan warnanya.',
    reward: 'Color match',
    rounds: makeRounds([
      { pairs: [['🍎','Merah'],['🍌','Kuning']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga']] },
      { pairs: [['🍅','Merah'],['🌽','Kuning'],['🥒','Hijau'],['🍇','Ungu'],['🥥','Coklat'],['🥚','Putih']] },
      { pairs: [['🍓','Merah'],['🍍','Kuning'],['🥝','Hijau'],['🫐','Biru'],['🍆','Ungu'],['🥕','Jingga'],['🌶️','Merah Cili']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga'],['🥥','Coklat'],['🥚','Putih']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga'],['🥥','Coklat'],['🥚','Putih'],['🍆','Ungu Tua']] },
      { pairs: [['🍎','Merah'],['🍌','Kuning'],['🥬','Hijau'],['🫐','Biru'],['🍇','Ungu'],['🍊','Jingga'],['🥥','Coklat'],['🥚','Putih'],['🍆','Ungu Tua'],['🍓','Merah Manis']] },
    ]),
  },
  {
    id: 'creative-susun-puzzle',
    title: 'Susun Puzzle Bentuk',
    emoji: '🧩',
    mode: 'sorting',
    objective: 'Asingkan bentuk ke kotak yang betul.',
    reward: 'Puzzle solve',
    rounds: makeRounds([
      { groups: ['Bulat','Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'⬛',group:'Sudut'},{text:'🔵',group:'Bulat'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'🔵',group:'Bulat'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'🔵',group:'Bulat'},{text:'🟦',group:'Empat Sudut'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut','Bintang'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'⭐',group:'Bintang'},{text:'🟦',group:'Empat Sudut'}] },
      { groups: ['2D','3D'], items: [{text:'🟦',group:'2D'},{text:'📦',group:'3D'},{text:'⚪',group:'2D'},{text:'⚽',group:'3D'},{text:'🔺',group:'2D'},{text:'🔷',group:'2D'}] },
      { groups: ['Simetri','Tak Simetri'], items: [{text:'🦋',group:'Simetri'},{text:'🍃',group:'Tak Simetri'},{text:'⭐',group:'Simetri'},{text:'🌀',group:'Tak Simetri'},{text:'❄️',group:'Simetri'}] },
      { groups: ['Bulat','Tiga Sudut','Empat Sudut','Banyak Sudut'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Tiga Sudut'},{text:'⬛',group:'Empat Sudut'},{text:'⭐',group:'Banyak Sudut'},{text:'🔵',group:'Bulat'},{text:'🟦',group:'Empat Sudut'},{text:'⬢',group:'Banyak Sudut'}] },
      { groups: ['Bulat','Sudut Tajam','Sudut Tumpul'], items: [{text:'⚪',group:'Bulat'},{text:'🔺',group:'Sudut Tajam'},{text:'⬛',group:'Sudut Tumpul'},{text:'🔵',group:'Bulat'},{text:'⭐',group:'Sudut Tajam'},{text:'🟦',group:'Sudut Tumpul'},{text:'⬡',group:'Sudut Tumpul'}] },
      { groups: ['Geometri','Organik','Hiasan'], items: [{text:'🟦',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'✨',group:'Hiasan'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'⭐',group:'Hiasan'},{text:'⬛',group:'Geometri'},{text:'🦋',group:'Organik'},{text:'💫',group:'Hiasan'}] },
    ]),
  },
  {
    id: 'creative-bina-perkataan',
    title: 'Bina Perkataan',
    emoji: '📝',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan.',
    reward: 'Word craft',
    rounds: makeRounds([
      { target: 'IBU', letters: ['B','I','U'] },
      { target: 'AYAH', letters: ['A','Y','A','H'] },
      { target: 'BUKU', letters: ['B','U','K','U'] },
      { target: 'SUSU', letters: ['S','U','S','U'] },
      { target: 'RUMAH', letters: ['R','U','M','A','H'] },
      { target: 'KUCING', letters: ['K','U','C','I','N','G'] },
      { target: 'BASIKAL', letters: ['B','A','S','I','K','A','L'] },
      { target: 'SEKOLAH', letters: ['S','E','K','O','L','A','H'] },
      { target: 'MATAHARI', letters: ['M','A','T','A','H','A','R','I'] },
      { target: 'KEMERDEKAAN', letters: ['K','E','M','E','R','D','E','K','A','A','N'] },
    ]),
  },
  {
    id: 'creative-warna-haiwan',
    title: 'Warnakan Haiwan',
    emoji: '🦋',
    mode: 'coloring',
    objective: 'Warnakan setiap haiwan kebun.',
    reward: 'Animal art',
    rounds: makeRounds([
      { items: ['🐢','🦋'] },
      { items: ['🐢','🦋','🐝'] },
      { items: ['🐢','🦋','🐝','🐞'] },
      { items: ['🐢','🦋','🐝','🐞','🐌'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜','🕷️'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜','🕷️','🐍'] },
      { items: ['🐢','🦋','🐝','🐞','🐌','🐛','🦗','🐜','🕷️','🐍','🦎','🐸'] },
    ]),
  },
  {
    id: 'creative-bina-ayat',
    title: 'Bina Perkataan dari Huruf',
    emoji: '✏️',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan Bahasa Melayu.',
    reward: 'Word craft',
    rounds: makeRounds([
      { target: 'SAYA', letters: ['S','A','Y','A'] },
      { target: 'NASI', letters: ['N','A','S','I'] },
      { target: 'IBU', letters: ['I','B','U'] },
      { target: 'AYAH', letters: ['A','Y','A','H'] },
      { target: 'ADIK', letters: ['A','D','I','K'] },
      { target: 'KAWAN', letters: ['K','A','W','A','N'] },
      { target: 'TAMAN', letters: ['T','A','M','A','N'] },
      { target: 'SEKOLAH', letters: ['S','E','K','O','L','A','H'] },
      { target: 'BASIKAL', letters: ['B','A','S','I','K','A','L'] },
      { target: 'KELUARGA', letters: ['K','E','L','U','A','R','G','A'] },
    ]),
  },
  {
    id: 'creative-roda-cerita',
    title: 'Padan Watak dengan Tempat',
    emoji: '📖',
    mode: 'memory',
    objective: 'Padankan watak dengan tempat sesuai.',
    reward: 'Story spark',
    rounds: makeRounds([
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran']] },
      { pairs: [['👮','Balai Polis'],['👨‍🚒','Stesen Bomba'],['👨‍⚕️','Hospital']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran'],['👨‍🌾','Sawah']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran'],['👨‍🌾','Sawah'],['👮','Balai Polis']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran'],['👨‍🌾','Sawah'],['👮','Balai Polis'],['👨‍🚒','Stesen Bomba']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran'],['👨‍🌾','Sawah'],['👮','Balai Polis'],['👨‍🚒','Stesen Bomba'],['🧑‍✈️','Lapangan Terbang']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran'],['👨‍🌾','Sawah'],['👮','Balai Polis'],['👨‍🚒','Stesen Bomba'],['🧑‍✈️','Lapangan Terbang'],['🧑‍🔬','Makmal']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran'],['👨‍🌾','Sawah'],['👮','Balai Polis'],['👨‍🚒','Stesen Bomba'],['🧑‍✈️','Lapangan Terbang'],['🧑‍🔬','Makmal'],['👨‍🎨','Studio Seni']] },
      { pairs: [['👨‍⚕️','Hospital'],['👨‍🏫','Sekolah'],['👨‍🍳','Restoran'],['👨‍🌾','Sawah'],['👮','Balai Polis'],['👨‍🚒','Stesen Bomba'],['🧑‍✈️','Lapangan Terbang'],['🧑‍🔬','Makmal'],['👨‍🎨','Studio Seni'],['🧑‍💻','Pejabat']] },
    ]),
  },
  {
    id: 'creative-bina-pelangi',
    title: 'Pop Warna Pelangi',
    emoji: '🌈',
    mode: 'balloon_pop',
    objective: 'Pop warna pelangi yang ditunjukkan.',
    reward: 'Rainbow build',
    rounds: makeRounds([
      { target: '🔴', items: ['🔴','⚫','🔴'] },
      { target: '🟠', items: ['🟠','🔴','🟠','🟡'] },
      { target: '🟡', items: ['🟡','🟠','🟡','🟢','🟡'] },
      { target: '🟢', items: ['🟢','🟡','🟢','🔵','🟢','🟣'] },
      { target: '🔵', items: ['🔵','🟢','🔵','🟣','🔵','⚫','🔵'] },
      { target: '🟣', items: ['🟣','🔵','🟣','🩷','🟣','🟤','🟣','⚫'] },
      { target: '🩷', items: ['🩷','🟣','🩷','🔴','🩷','🟠','🩷','🟡','🩷'] },
      { target: '🔴', items: ['🔴','🟠','🟡','🟢','🔴','🔵','🟣','🩷','🔴','⚫'] },
      { target: '🟢', items: ['🟢','🔴','🟠','🟡','🟢','🔵','🟣','🩷','🟢','⚫','🟢'] },
      { target: '🟣', items: ['🟣','🔴','🟠','🟡','🟢','🔵','🟣','🩷','🟤','⚫','⚪','🟣'] },
    ]),
  },
];