// 🧩 LOGIC PUZZLES — 10 games × 10 rounds. Tema Malaysia.
import { makeRounds } from './_helpers.js';

export const logicPuzzlesGames = [
  {
    id: 'logic-haiwan-tempat',
    title: 'Kelaskan Haiwan',
    emoji: '🦅',
    mode: 'sorting',
    objective: 'Asingkan haiwan ikut tempat tinggal.',
    reward: 'Logic star',
    rounds: makeRounds([
      { groups: ['Darat','Air'], items: [{text:'🐯',group:'Darat'},{text:'🐟',group:'Air'},{text:'🐘',group:'Darat'}] },
      { groups: ['Darat','Udara'], items: [{text:'🐘',group:'Darat'},{text:'🦅',group:'Udara'},{text:'🐅',group:'Darat'}] },
      { groups: ['Darat','Air','Udara'], items: [{text:'🐯',group:'Darat'},{text:'🐟',group:'Air'},{text:'🦅',group:'Udara'},{text:'🦋',group:'Udara'}] },
      { groups: ['Darat','Air','Udara'], items: [{text:'🐘',group:'Darat'},{text:'🐬',group:'Air'},{text:'🦜',group:'Udara'},{text:'🐢',group:'Air'},{text:'🐒',group:'Darat'}] },
      { groups: ['Darat','Air','Udara'], items: [{text:'🦒',group:'Darat'},{text:'🦈',group:'Air'},{text:'🦋',group:'Udara'},{text:'🐊',group:'Air'},{text:'🐅',group:'Darat'},{text:'🦅',group:'Udara'}] },
      { groups: ['Jinak','Liar'], items: [{text:'🐈',group:'Jinak'},{text:'🐅',group:'Liar'},{text:'🐕',group:'Jinak'},{text:'🐺',group:'Liar'},{text:'🐎',group:'Jinak'},{text:'🦁',group:'Liar'}] },
      { groups: ['Mamalia','Reptilia','Burung'], items: [{text:'🐯',group:'Mamalia'},{text:'🐍',group:'Reptilia'},{text:'🦅',group:'Burung'},{text:'🐘',group:'Mamalia'},{text:'🦎',group:'Reptilia'},{text:'🦉',group:'Burung'}] },
      { groups: ['Mamalia','Reptilia','Serangga'], items: [{text:'🦋',group:'Serangga'},{text:'🐢',group:'Reptilia'},{text:'🐒',group:'Mamalia'},{text:'🐝',group:'Serangga'},{text:'🐊',group:'Reptilia'},{text:'🐕',group:'Mamalia'},{text:'🐞',group:'Serangga'}] },
      { groups: ['Darat','Air','Udara'], items: [{text:'🐯',group:'Darat'},{text:'🐟',group:'Air'},{text:'🦅',group:'Udara'},{text:'🐘',group:'Darat'},{text:'🐬',group:'Air'},{text:'🦋',group:'Udara'},{text:'🐅',group:'Darat'},{text:'🦈',group:'Air'}] },
      { groups: ['Darat','Air','Udara','Pokok'], items: [{text:'🐯',group:'Darat'},{text:'🐟',group:'Air'},{text:'🦅',group:'Udara'},{text:'🐒',group:'Pokok'},{text:'🐘',group:'Darat'},{text:'🐬',group:'Air'},{text:'🦋',group:'Udara'},{text:'🦧',group:'Pokok'}] },
    ]),
  },
  {
    id: 'logic-alat-guna',
    title: 'Padan Alat dan Gunanya',
    emoji: '🔑',
    mode: 'tilematch',
    objective: 'Padankan alat dengan kegunaannya.',
    reward: 'Tool combo',
    rounds: makeRounds([
      { tiles: ['Kunci','Pintu','Pensel','Kertas'] },
      { tiles: ['Payung','Hujan','Sudu','Makan'] },
      { tiles: ['Cermin Mata','Mata','Sikat','Rambut','Berus','Gigi'] },
      { tiles: ['Kunci','Pintu','Payung','Hujan','Sudu','Makan'] },
      { tiles: ['Pensel','Kertas','Sikat','Rambut','Berus','Gigi','Sabun','Tangan'] },
      { tiles: ['Tukul','Paku','Gunting','Kertas','Pisau','Sayur','Sudip','Periuk'] },
      { tiles: ['Buku','Membaca','Pen','Menulis','Beg','Mengangkat','Kasut','Memakai'] },
      { tiles: ['Sapu','Sampah','Mop','Lantai','Span','Pinggan','Tuala','Tangan','Sabun','Mandi'] },
      { tiles: ['Pencungkil','Gigi','Selipar','Kaki','Topi','Kepala','Cincin','Jari','Jam','Tangan'] },
      { tiles: ['Periuk','Memasak','Sudu','Makan','Kunci','Pintu','Payung','Hujan','Sikat','Rambut','Berus','Gigi'] },
    ]),
  },
  {
    id: 'logic-objek-tempat',
    title: 'Letak Objek di Tempat',
    emoji: '🎯',
    mode: 'dragdrop',
    objective: 'Letak objek di tempat yang betul dalam rumah.',
    reward: 'Smart solve',
    rounds: makeRounds([
      { items: ['Buku','Pinggan'], targets: ['Rak Buku','Dapur'] },
      { items: ['Kereta','Baju'], targets: ['Garaj','Almari'] },
      { items: ['Buku','Pinggan','Kereta'], targets: ['Rak Buku','Dapur','Garaj'] },
      { items: ['Tilam','Sudu','Tuala'], targets: ['Bilik Tidur','Dapur','Bilik Air'] },
      { items: ['Buku','Pinggan','Kereta','Baju'], targets: ['Rak Buku','Dapur','Garaj','Almari'] },
      { items: ['Sofa','Periuk','Bantal','Sabun'], targets: ['Ruang Tamu','Dapur','Bilik Tidur','Bilik Air'] },
      { items: ['TV','Cawan','Tilam','Berus Gigi','Sapu'], targets: ['Ruang Tamu','Dapur','Bilik Tidur','Bilik Air','Halaman'] },
      { items: ['Sofa','Periuk','Bantal','Sabun','Sapu','Kasut'], targets: ['Ruang Tamu','Dapur','Bilik Tidur','Bilik Air','Halaman','Rak Kasut'] },
      { items: ['TV','Cawan','Tilam','Berus Gigi','Sapu','Kasut','Cermin'], targets: ['Ruang Tamu','Dapur','Bilik Tidur','Bilik Air','Halaman','Rak Kasut','Almari'] },
      { items: ['Buku','Pinggan','Kereta','Baju','Sofa','Periuk','Bantal','Sabun'], targets: ['Rak Buku','Sinki','Garaj','Almari','Ruang Tamu','Dapur','Bilik Tidur','Bilik Air'] },
    ]),
  },
  {
    id: 'logic-ganjil-genap',
    title: 'Pilih Ganjil atau Genap',
    emoji: '🔢',
    mode: 'swipe_select',
    objective: 'Pilih nombor ganjil atau genap.',
    reward: 'Number sense',
    rounds: makeRounds([
      { groups: ['Ganjil','Genap'], items: [{text:'1',group:'Ganjil'},{text:'2',group:'Genap'},{text:'3',group:'Ganjil'}] },
      { groups: ['Ganjil','Genap'], items: [{text:'4',group:'Genap'},{text:'5',group:'Ganjil'},{text:'6',group:'Genap'}] },
      { groups: ['Ganjil','Genap'], items: [{text:'7',group:'Ganjil'},{text:'8',group:'Genap'},{text:'9',group:'Ganjil'},{text:'10',group:'Genap'}] },
      { groups: ['Ganjil','Genap'], items: [{text:'11',group:'Ganjil'},{text:'12',group:'Genap'},{text:'13',group:'Ganjil'},{text:'14',group:'Genap'},{text:'15',group:'Ganjil'}] },
      { groups: ['Ganjil','Genap'], items: [{text:'16',group:'Genap'},{text:'17',group:'Ganjil'},{text:'18',group:'Genap'},{text:'19',group:'Ganjil'},{text:'20',group:'Genap'}] },
      { groups: ['Ganjil','Genap'], items: [{text:'21',group:'Ganjil'},{text:'24',group:'Genap'},{text:'27',group:'Ganjil'},{text:'30',group:'Genap'},{text:'33',group:'Ganjil'},{text:'36',group:'Genap'}] },
      { groups: ['Ganjil','Genap'], items: [{text:'41',group:'Ganjil'},{text:'48',group:'Genap'},{text:'55',group:'Ganjil'},{text:'62',group:'Genap'},{text:'73',group:'Ganjil'},{text:'80',group:'Genap'},{text:'91',group:'Ganjil'}] },
      { groups: ['Ganjil','Genap'], items: [{text:'15',group:'Ganjil'},{text:'28',group:'Genap'},{text:'37',group:'Ganjil'},{text:'44',group:'Genap'},{text:'59',group:'Ganjil'},{text:'66',group:'Genap'},{text:'81',group:'Ganjil'},{text:'94',group:'Genap'}] },
      { groups: ['Ganjil','Genap','Sifar'], items: [{text:'0',group:'Sifar'},{text:'7',group:'Ganjil'},{text:'12',group:'Genap'},{text:'19',group:'Ganjil'},{text:'24',group:'Genap'},{text:'33',group:'Ganjil'},{text:'40',group:'Genap'}] },
      { groups: ['Ganjil','Genap','Sifar'], items: [{text:'0',group:'Sifar'},{text:'11',group:'Ganjil'},{text:'22',group:'Genap'},{text:'33',group:'Ganjil'},{text:'44',group:'Genap'},{text:'55',group:'Ganjil'},{text:'66',group:'Genap'},{text:'77',group:'Ganjil'},{text:'88',group:'Genap'}] },
    ]),
  },
  {
    id: 'logic-pakaian-tempat',
    title: 'Pakaian untuk Acara',
    emoji: '👔',
    mode: 'dragdrop',
    objective: 'Pilih pakaian sesuai untuk acara.',
    reward: 'Style sense',
    rounds: makeRounds([
      { items: ['Baju Sekolah','Baju Tidur'], targets: ['Pergi Sekolah','Masa Tidur'] },
      { items: ['Sukan','Berbaju Melayu'], targets: ['Padang Bola','Hari Raya'] },
      { items: ['Baju Renang','Jaket'], targets: ['Pantai','Musim Sejuk'] },
      { items: ['Baju Sekolah','Sukan','Baju Melayu','Baju Tidur'], targets: ['Sekolah','Padang','Hari Raya','Tidur'] },
      { items: ['Cheongsam','Sari','Baju Kurung'], targets: ['Tahun Baru Cina','Deepavali','Hari Raya'] },
      { items: ['Songkok','Selendang','Topi','Hijab'], targets: ['Lelaki Solat','Wanita Solat','Sukan','Sekolah Agama'] },
      { items: ['Tuxedo','Gaun','Baju T','Seluar Pendek'], targets: ['Majlis Formal','Pesta','Rehat','Berenang'] },
      { items: ['Baju Sekolah','Sukan','Baju Kurung','Baju Tidur','Baju Renang','Jaket'], targets: ['Sekolah','Padang','Hari Raya','Tidur','Pantai','Sejuk'] },
      { items: ['Cheongsam','Sari','Baju Kurung','Songkok','Selendang','Hijab','Topi'], targets: ['CNY','Deepavali','Raya','Solat Lelaki','Solat Wanita','Tudung Harian','Sukan'] },
      { items: ['Tuxedo','Gaun','Baju T','Seluar Pendek','Sukan','Baju Kurung','Baju Tidur','Jaket'], targets: ['Formal','Pesta','Rehat','Berenang','Padang','Hari Raya','Tidur','Sejuk'] },
    ]),
  },
  {
    id: 'logic-musim-buah',
    title: 'Musim dan Buah',
    emoji: '🌧️',
    mode: 'sorting',
    objective: 'Asingkan buah ikut musim.',
    reward: 'Season smart',
    rounds: makeRounds([
      { groups: ['Musim Durian','Sepanjang Tahun'], items: [{text:'Durian',group:'Musim Durian'},{text:'Pisang',group:'Sepanjang Tahun'},{text:'Mangga',group:'Sepanjang Tahun'}] },
      { groups: ['Musim','Sepanjang Tahun'], items: [{text:'Rambutan',group:'Musim'},{text:'Pisang',group:'Sepanjang Tahun'},{text:'Manggis',group:'Musim'}] },
      { groups: ['Musim','Sepanjang Tahun'], items: [{text:'Durian',group:'Musim'},{text:'Rambutan',group:'Musim'},{text:'Pisang',group:'Sepanjang Tahun'},{text:'Kelapa',group:'Sepanjang Tahun'}] },
      { groups: ['Musim','Sepanjang Tahun'], items: [{text:'Manggis',group:'Musim'},{text:'Langsat',group:'Musim'},{text:'Pisang',group:'Sepanjang Tahun'},{text:'Tembikai',group:'Sepanjang Tahun'},{text:'Mangga',group:'Musim'}] },
      { groups: ['Musim','Sepanjang Tahun'], items: [{text:'Durian',group:'Musim'},{text:'Rambutan',group:'Musim'},{text:'Manggis',group:'Musim'},{text:'Pisang',group:'Sepanjang Tahun'},{text:'Kelapa',group:'Sepanjang Tahun'},{text:'Tembikai',group:'Sepanjang Tahun'}] },
      { groups: ['Musim Buah','Musim Tengkujuh'], items: [{text:'Durian',group:'Musim Buah'},{text:'Rambutan',group:'Musim Buah'},{text:'Hujan Lebat',group:'Musim Tengkujuh'},{text:'Banjir',group:'Musim Tengkujuh'}] },
      { groups: ['Kemarau','Tengkujuh','Sederhana'], items: [{text:'Matahari Terik',group:'Kemarau'},{text:'Banjir',group:'Tengkujuh'},{text:'Hujan Renyai',group:'Sederhana'},{text:'Panas Berhabuk',group:'Kemarau'}] },
      { groups: ['Musim Hujan','Musim Kemarau'], items: [{text:'Payung',group:'Musim Hujan'},{text:'Topi',group:'Musim Kemarau'},{text:'Baju Sejuk',group:'Musim Hujan'},{text:'Cermin Mata Hitam',group:'Musim Kemarau'},{text:'Kasut But',group:'Musim Hujan'}] },
      { groups: ['Musim','Sepanjang Tahun','Pesta'], items: [{text:'Durian',group:'Musim'},{text:'Pisang',group:'Sepanjang Tahun'},{text:'Kuih Raya',group:'Pesta'},{text:'Kueh Bulan',group:'Pesta'},{text:'Manggis',group:'Musim'},{text:'Kelapa',group:'Sepanjang Tahun'}] },
      { groups: ['Musim Buah','Musim Tengkujuh','Musim Kemarau','Sepanjang Tahun'], items: [{text:'Durian',group:'Musim Buah'},{text:'Banjir',group:'Musim Tengkujuh'},{text:'Habuk',group:'Musim Kemarau'},{text:'Pisang',group:'Sepanjang Tahun'},{text:'Rambutan',group:'Musim Buah'},{text:'Hujan Lebat',group:'Musim Tengkujuh'},{text:'Matahari Terik',group:'Musim Kemarau'},{text:'Kelapa',group:'Sepanjang Tahun'}] },
    ]),
  },
  {
    id: 'logic-betul-salah-am',
    title: 'Betul atau Salah?',
    emoji: '✅',
    mode: 'true_false',
    objective: 'Nilai fakta umum dengan tepat.',
    reward: 'Truth scout',
    rounds: makeRounds([
      { statements: [{text:'Kuala Lumpur adalah ibu negara Malaysia.',answer:true},{text:'Bulan lebih besar dari Bumi.',answer:false}] },
      { statements: [{text:'Petronas Twin Towers terletak di KL.',answer:true},{text:'Pulau Pinang terletak di Sabah.',answer:false}] },
      { statements: [{text:'Sungai Rajang adalah sungai paling panjang di Malaysia.',answer:true},{text:'Gunung Tahan di Kelantan.',answer:false},{text:'Malaysia ada 13 negeri.',answer:true}] },
      { statements: [{text:'Air laut masin.',answer:true},{text:'Lebah membuat sarang dari batu.',answer:false},{text:'Bulan mengelilingi Bumi.',answer:true}] },
      { statements: [{text:'5 + 5 = 10',answer:true},{text:'10 - 3 = 5',answer:false},{text:'2 × 4 = 8',answer:true},{text:'9 ÷ 3 = 4',answer:false}] },
      { statements: [{text:'Bahasa rasmi Malaysia ialah Bahasa Melayu.',answer:true},{text:'Sabah dan Sarawak adalah negeri di Semenanjung.',answer:false},{text:'Lagu Negaraku adalah lagu kebangsaan.',answer:true},{text:'Hari Kebangsaan jatuh pada 1 Januari.',answer:false}] },
      { statements: [{text:'Matahari terbit di Timur.',answer:true},{text:'Tumbuhan menghasilkan oksigen.',answer:true},{text:'Ais lebih panas dari air.',answer:false},{text:'Magnet menarik kayu.',answer:false},{text:'Manusia bernafas dengan paru-paru.',answer:true}] },
      { statements: [{text:'Sultan Mizan Stadium di Terengganu.',answer:true},{text:'Putrajaya adalah ibu kota Pahang.',answer:false},{text:'Cameron Highlands di Pahang.',answer:true},{text:'Langkawi adalah pulau di Pahang.',answer:false},{text:'Genting Highlands tempat sejuk.',answer:true}] },
      { statements: [{text:'Tulip adalah bunga rasmi Malaysia.',answer:false},{text:'Bunga Raya adalah bunga rasmi Malaysia.',answer:true},{text:'Harimau Malaya pada jata negara.',answer:true},{text:'Lambang negara mempunyai 5 keris.',answer:false},{text:'Rukun Negara ada 5 prinsip.',answer:true}] },
      { statements: [{text:'Malaysia merdeka pada 1957.',answer:true},{text:'Sabah dan Sarawak masuk pada 1963.',answer:true},{text:'Kuala Lumpur di Pulau Pinang.',answer:false},{text:'Tunku Abdul Rahman PM pertama.',answer:true},{text:'Hari Malaysia 16 September.',answer:true},{text:'Bendera Malaysia ada 13 jalur.',answer:false}] },
    ]),
  },
  {
    id: 'logic-zaman-perkara',
    title: 'Padan Perkara dan Zaman',
    emoji: '⏳',
    mode: 'sorting',
    objective: 'Asingkan benda ikut zaman.',
    reward: 'Time logic',
    rounds: makeRounds([
      { groups: ['Lama','Baru'], items: [{text:'Surat',group:'Lama'},{text:'E-mel',group:'Baru'}] },
      { groups: ['Lama','Baru'], items: [{text:'Radio',group:'Lama'},{text:'Spotify',group:'Baru'}] },
      { groups: ['Lama','Baru'], items: [{text:'Surat',group:'Lama'},{text:'E-mel',group:'Baru'},{text:'Telegraf',group:'Lama'}] },
      { groups: ['Lama','Baru'], items: [{text:'Lampu Pelita',group:'Lama'},{text:'LED',group:'Baru'},{text:'Pen Buluh',group:'Lama'},{text:'Tablet',group:'Baru'}] },
      { groups: ['Tradisional','Moden'], items: [{text:'Kuali Besi',group:'Tradisional'},{text:'Periuk Elektrik',group:'Moden'},{text:'Ubat Herba',group:'Tradisional'},{text:'Pil',group:'Moden'},{text:'Kapal Kayu',group:'Tradisional'}] },
      { groups: ['Pra-Merdeka','Pasca-Merdeka'], items: [{text:'Penjajahan Inggeris',group:'Pra-Merdeka'},{text:'PM Pertama',group:'Pasca-Merdeka'},{text:'Era Penjajahan',group:'Pra-Merdeka'},{text:'KLCC',group:'Pasca-Merdeka'},{text:'Komuter KTM',group:'Pasca-Merdeka'}] },
      { groups: ['Tradisional','Moden','Kombinasi'], items: [{text:'Baju Kurung',group:'Tradisional'},{text:'Cheongsam',group:'Tradisional'},{text:'Hoodie',group:'Moden'},{text:'Baju Batik Corporate',group:'Kombinasi'},{text:'T-Shirt Songket',group:'Kombinasi'}] },
      { groups: ['Lama','Baru'], items: [{text:'Kamera Filem',group:'Lama'},{text:'Telefon Bimbit',group:'Baru'},{text:'Buku Cek',group:'Lama'},{text:'E-Wallet',group:'Baru'},{text:'Kaset Tape',group:'Lama'},{text:'YouTube',group:'Baru'}] },
      { groups: ['Tradisional','Moden','Kombinasi'], items: [{text:'Wau Bulan',group:'Tradisional'},{text:'Drone',group:'Moden'},{text:'Sape',group:'Tradisional'},{text:'Synthesizer',group:'Moden'},{text:'Gamelan Elektronik',group:'Kombinasi'},{text:'Batik Cetakan',group:'Kombinasi'}] },
      { groups: ['1900-an','2000-an','2020-an'], items: [{text:'Telegraf',group:'1900-an'},{text:'Internet',group:'2000-an'},{text:'AI Assistant',group:'2020-an'},{text:'Filem Hitam Putih',group:'1900-an'},{text:'Filem 3D',group:'2000-an'},{text:'VR Game',group:'2020-an'},{text:'Mesin Taip',group:'1900-an'}] },
    ]),
  },
  {
    id: 'logic-corak-pilih',
    title: 'Cari Yang Hilang dari Corak',
    emoji: '❓',
    mode: 'picture_hunt',
    objective: 'Pilih item yang lengkapkan corak.',
    reward: 'Pattern brain',
    rounds: makeRounds([
      { target: '🔵', items: ['🔴','🔵','🟢'] },
      { target: '🌙', items: ['⭐','🌙','☀️','🌈'] },
      { target: '🟡', items: ['🔴','🟡','🔵','🟢'] },
      { target: '🍇', items: ['🍎','🍌','🍇','🍊','🍓'] },
      { target: '🟢', items: ['🔵','🔺','🟢','🟥','🟨'] },
      { target: '➡️', items: ['⬆️','⬇️','⬅️','➡️','↗️'] },
      { target: '🌹', items: ['🌸','🌻','🌹','🌷','🌺','🪻'] },
      { target: '6', items: ['2','4','6','8','10','12','14'] },
      { target: 'E', items: ['A','B','C','D','E','F','G','H'] },
      { target: '🌕', items: ['🌑','🌒','🌓','🌔','🌕','🌖','🌗','🌘','🌙','⭐'] },
    ]),
  },
];