// 🧩 LOGIC PUZZLES — 10 games × 10 rounds. Tema campuran (asingkan, klasifikasi, padanan logik).
import { makeRounds } from './_helpers.js';

export const logicPuzzlesGames = [
  {
    id: 'logic-makanan-jenis',
    title: 'Kelaskan Makanan',
    emoji: '🍎',
    mode: 'sorting',
    objective: 'Asingkan makanan ikut jenis.',
    reward: 'Food logic',
    rounds: makeRounds([
      { groups: ['Buah','Sayur'], items: [{text:'🍎',group:'Buah'},{text:'🥕',group:'Sayur'},{text:'🍌',group:'Buah'}] },
      { groups: ['Manis','Masin'], items: [{text:'🍭',group:'Manis'},{text:'🍟',group:'Masin'},{text:'🍰',group:'Manis'}] },
      { groups: ['Buah','Sayur','Daging'], items: [{text:'🍎',group:'Buah'},{text:'🥕',group:'Sayur'},{text:'🍗',group:'Daging'},{text:'🥬',group:'Sayur'}] },
      { groups: ['Manis','Masin','Pedas'], items: [{text:'🍭',group:'Manis'},{text:'🍟',group:'Masin'},{text:'🌶️',group:'Pedas'},{text:'🍰',group:'Manis'},{text:'🥨',group:'Masin'}] },
      { groups: ['Sarapan','Makan Malam','Snek'], items: [{text:'🥞',group:'Sarapan'},{text:'🍝',group:'Makan Malam'},{text:'🍪',group:'Snek'},{text:'🍳',group:'Sarapan'},{text:'🥗',group:'Makan Malam'},{text:'🍿',group:'Snek'}] },
      { groups: ['Buah','Sayur','Bijirin'], items: [{text:'🍎',group:'Buah'},{text:'🥕',group:'Sayur'},{text:'🍞',group:'Bijirin'},{text:'🍌',group:'Buah'},{text:'🥦',group:'Sayur'},{text:'🍚',group:'Bijirin'}] },
      { groups: ['Mentah','Masak'], items: [{text:'🥒',group:'Mentah'},{text:'🍕',group:'Masak'},{text:'🥬',group:'Mentah'},{text:'🍗',group:'Masak'},{text:'🥕',group:'Mentah'},{text:'🍔',group:'Masak'}] },
      { groups: ['Sejuk','Panas'], items: [{text:'🍦',group:'Sejuk'},{text:'🍲',group:'Panas'},{text:'🧊',group:'Sejuk'},{text:'☕',group:'Panas'},{text:'🍧',group:'Sejuk'},{text:'🍜',group:'Panas'},{text:'🥶',group:'Sejuk'}] },
      { groups: ['Buah','Sayur','Daging','Bijirin'], items: [{text:'🍎',group:'Buah'},{text:'🥕',group:'Sayur'},{text:'🍗',group:'Daging'},{text:'🍞',group:'Bijirin'},{text:'🍌',group:'Buah'},{text:'🥦',group:'Sayur'},{text:'🥩',group:'Daging'},{text:'🍚',group:'Bijirin'}] },
      { groups: ['Manis','Masin','Pedas','Masam'], items: [{text:'🍭',group:'Manis'},{text:'🍟',group:'Masin'},{text:'🌶️',group:'Pedas'},{text:'🍋',group:'Masam'},{text:'🍰',group:'Manis'},{text:'🥨',group:'Masin'},{text:'🥒',group:'Masam'},{text:'🫑',group:'Pedas'}] },
    ]),
  },
  {
    id: 'logic-haiwan-makanan',
    title: 'Haiwan Makan Apa?',
    emoji: '🦁',
    mode: 'tilematch',
    objective: 'Padankan haiwan dengan makanan.',
    reward: 'Food chain',
    rounds: makeRounds([
      { tiles: ['Arnab','Lobak','Kucing','Ikan'] },
      { tiles: ['Tikus','Keju','Anjing','Tulang'] },
      { tiles: ['Lebah','Bunga','Burung','Cacing','Monyet','Pisang'] },
      { tiles: ['Arnab','Lobak','Kucing','Ikan','Tikus','Keju'] },
      { tiles: ['Anjing','Tulang','Lebah','Bunga','Burung','Cacing','Monyet','Pisang'] },
      { tiles: ['Singa','Daging','Gajah','Daun','Panda','Buluh','Beruang','Madu'] },
      { tiles: ['Harimau','Daging','Zirafah','Daun','Kuda','Rumput','Ayam','Beras','Itik','Air'] },
      { tiles: ['Arnab','Lobak','Kucing','Ikan','Tikus','Keju','Anjing','Tulang','Lebah','Bunga'] },
      { tiles: ['Singa','Daging','Gajah','Daun','Panda','Buluh','Beruang','Madu','Burung','Cacing'] },
      { tiles: ['Arnab','Lobak','Kucing','Ikan','Tikus','Keju','Anjing','Tulang','Singa','Daging','Gajah','Daun'] },
    ]),
  },
  {
    id: 'logic-objek-bilik',
    title: 'Objek Letak Mana?',
    emoji: '🏠',
    mode: 'dragdrop',
    objective: 'Letak objek di bilik yang sesuai.',
    reward: 'Home smart',
    rounds: makeRounds([
      { items: ['Katil','Periuk'], targets: ['Bilik Tidur','Dapur'] },
      { items: ['TV','Sabun'], targets: ['Ruang Tamu','Bilik Air'] },
      { items: ['Katil','Periuk','TV'], targets: ['Bilik Tidur','Dapur','Ruang Tamu'] },
      { items: ['Bantal','Pinggan','Sofa','Tuala'], targets: ['Bilik Tidur','Dapur','Ruang Tamu','Bilik Air'] },
      { items: ['Almari','Sinki','Karpet','Cermin','Buku'], targets: ['Bilik Tidur','Dapur','Ruang Tamu','Bilik Air','Bilik Belajar'] },
      { items: ['Katil','Periuk','Sofa','Sabun','Meja Belajar'], targets: ['Bilik Tidur','Dapur','Ruang Tamu','Bilik Air','Bilik Belajar'] },
      { items: ['Bantal','Pisau','Bantal Sofa','Berus Gigi','Buku','Kasut'], targets: ['Bilik Tidur','Dapur','Ruang Tamu','Bilik Air','Bilik Belajar','Rak Kasut'] },
      { items: ['Tilam','Sudu','Cushion','Syampu','Pen','Sneakers','Pasu Bunga'], targets: ['Bilik Tidur','Dapur','Ruang Tamu','Bilik Air','Bilik Belajar','Rak Kasut','Halaman'] },
      { items: ['Almari','Mangkuk','TV','Cermin','Beg Sekolah','Selipar','Bunga Mawar','Mesin Basuh'], targets: ['Bilik Tidur','Dapur','Ruang Tamu','Bilik Air','Bilik Belajar','Rak Kasut','Halaman','Bilik Cuci'] },
      { items: ['Selimut','Wajan','Lukisan','Tisu','Buku Cerita','Kasut Sukan','Pasu','Cuci Baju'], targets: ['Bilik Tidur','Dapur','Ruang Tamu','Bilik Air','Bilik Belajar','Rak Kasut','Halaman','Bilik Cuci'] },
    ]),
  },
  {
    id: 'logic-besar-kecil',
    title: 'Susun Besar Kecil',
    emoji: '📏',
    mode: 'sorting',
    objective: 'Asingkan objek ikut saiz.',
    reward: 'Size sense',
    rounds: makeRounds([
      { groups: ['Besar','Kecil'], items: [{text:'🐘',group:'Besar'},{text:'🐜',group:'Kecil'},{text:'🐋',group:'Besar'}] },
      { groups: ['Besar','Kecil'], items: [{text:'🏠',group:'Besar'},{text:'🍎',group:'Kecil'},{text:'🚌',group:'Besar'}] },
      { groups: ['Besar','Kecil','Sederhana'], items: [{text:'🐘',group:'Besar'},{text:'🐜',group:'Kecil'},{text:'🐕',group:'Sederhana'},{text:'🐋',group:'Besar'}] },
      { groups: ['Berat','Ringan'], items: [{text:'🏋️',group:'Berat'},{text:'🪶',group:'Ringan'},{text:'🪨',group:'Berat'},{text:'🎈',group:'Ringan'}] },
      { groups: ['Tinggi','Pendek'], items: [{text:'🦒',group:'Tinggi'},{text:'🐢',group:'Pendek'},{text:'🌳',group:'Tinggi'},{text:'🍄',group:'Pendek'},{text:'🗼',group:'Tinggi'}] },
      { groups: ['Panjang','Pendek'], items: [{text:'🐍',group:'Panjang'},{text:'🐛',group:'Pendek'},{text:'🚂',group:'Panjang'},{text:'🚗',group:'Pendek'},{text:'📏',group:'Panjang'}] },
      { groups: ['Besar','Kecil','Sederhana'], items: [{text:'🐘',group:'Besar'},{text:'🐜',group:'Kecil'},{text:'🐕',group:'Sederhana'},{text:'🐋',group:'Besar'},{text:'🐭',group:'Kecil'},{text:'🐈',group:'Sederhana'}] },
      { groups: ['Berat','Ringan','Sederhana'], items: [{text:'🏋️',group:'Berat'},{text:'🪶',group:'Ringan'},{text:'📦',group:'Sederhana'},{text:'🪨',group:'Berat'},{text:'🎈',group:'Ringan'},{text:'⚽',group:'Sederhana'}] },
      { groups: ['Besar','Kecil','Sederhana','Sangat Besar'], items: [{text:'🐘',group:'Besar'},{text:'🐜',group:'Kecil'},{text:'🐕',group:'Sederhana'},{text:'🐋',group:'Sangat Besar'},{text:'🐭',group:'Kecil'},{text:'🐈',group:'Sederhana'},{text:'🦏',group:'Besar'},{text:'🦕',group:'Sangat Besar'}] },
      { groups: ['Tinggi','Pendek','Panjang','Bulat'], items: [{text:'🦒',group:'Tinggi'},{text:'🐢',group:'Pendek'},{text:'🐍',group:'Panjang'},{text:'⚽',group:'Bulat'},{text:'🌳',group:'Tinggi'},{text:'🍄',group:'Pendek'},{text:'🚂',group:'Panjang'},{text:'🍎',group:'Bulat'}] },
    ]),
  },
  {
    id: 'logic-aktiviti-masa',
    title: 'Aktiviti Bila?',
    emoji: '⏰',
    mode: 'dragdrop',
    objective: 'Padankan aktiviti dengan masa.',
    reward: 'Time sense',
    rounds: makeRounds([
      { items: ['Sarapan','Tidur'], targets: ['Pagi','Malam'] },
      { items: ['Sekolah','Solat Maghrib'], targets: ['Pagi','Petang'] },
      { items: ['Sarapan','Makan Tengah Hari','Makan Malam'], targets: ['Pagi','Tengah Hari','Malam'] },
      { items: ['Bangun','Lunch','Tidur','Subuh'], targets: ['Pagi','Tengah Hari','Malam','Awal Pagi'] },
      { items: ['Sarapan','Sekolah','Snek','Tidur','Mandi'], targets: ['Pagi','Pagi','Petang','Malam','Sebelum Tidur'] },
      { items: ['Bangun','Mandi','Pakai Seragam','Sarapan','Sekolah','Tidur'], targets: ['6 Pagi','6.30 Pagi','7 Pagi','7.30 Pagi','8 Pagi','10 Malam'] },
      { items: ['Subuh','Sarapan','Sekolah','Tengah Hari','Pulang','Makan Malam','Tidur'], targets: ['5 Pagi','7 Pagi','8 Pagi','12 Tgh','2 Petang','7 Malam','10 Malam'] },
      { items: ['Sahur','Sarapan','Solat Asar','Iftar','Terawih','Tidur','Bangun'], targets: ['Awal Pagi','Pagi','Petang','Maghrib','Isyak','Malam','Pagi Esok'] },
      { items: ['Bangun','Mandi','Sarapan','Sekolah','Lunch','Pulang','Petang','Malam'], targets: ['6 Pagi','6.30','7 Pagi','8 Pagi','12 Tgh','2 Ptg','5 Ptg','9 Malam'] },
      { items: ['Subuh','Sarapan','Sekolah','Rehat','Lunch','Pulang','Mandi','Makan Malam','Tidur'], targets: ['5 Pagi','7 Pagi','8 Pagi','10 Pagi','12 Tgh','2 Ptg','5 Ptg','7 Malam','10 Malam'] },
    ]),
  },
  {
    id: 'logic-betul-salah-sains',
    title: 'Fakta Sains Betul Salah',
    emoji: '🔬',
    mode: 'true_false',
    objective: 'Nilai fakta sains.',
    reward: 'Science scout',
    rounds: makeRounds([
      { statements: [{text:'Matahari panas.',answer:true},{text:'Ais tidak sejuk.',answer:false}] },
      { statements: [{text:'Air mendidih pada 100°C.',answer:true},{text:'Bulan bersinar sendiri.',answer:false}] },
      { statements: [{text:'Tumbuhan perlu cahaya matahari.',answer:true},{text:'Ikan boleh hidup di darat.',answer:false},{text:'Manusia ada 2 mata.',answer:true}] },
      { statements: [{text:'Magnet menarik besi.',answer:true},{text:'Plastik boleh ditarik magnet.',answer:false},{text:'Bumi berbentuk bulat.',answer:true},{text:'Salji adalah air panas.',answer:false}] },
      { statements: [{text:'Lebah membuat madu.',answer:true},{text:'Cermin tidak memantulkan cahaya.',answer:false},{text:'Manusia ada 5 deria.',answer:true},{text:'Awan terbuat dari air.',answer:true}] },
      { statements: [{text:'Pelangi ada 7 warna.',answer:true},{text:'Bulan lebih besar dari matahari.',answer:false},{text:'Pokok bernafas guna daun.',answer:true},{text:'Burung tiada tulang.',answer:false},{text:'Manusia perlu air.',answer:true}] },
      { statements: [{text:'Manusia ada 206 tulang.',answer:true},{text:'Otak manusia kecil daripada hati.',answer:false},{text:'Darah berwarna merah.',answer:true},{text:'Hidung untuk melihat.',answer:false},{text:'Telinga untuk dengar.',answer:true}] },
      { statements: [{text:'Air menjadi wap bila panas.',answer:true},{text:'Air membeku menjadi ais.',answer:true},{text:'Api sejuk.',answer:false},{text:'Cahaya laju daripada bunyi.',answer:true},{text:'Bayang muncul di tempat gelap.',answer:false}] },
      { statements: [{text:'Bumi mengelilingi matahari.',answer:true},{text:'Setahun ada 365 hari.',answer:true},{text:'Mars adalah planet biru.',answer:false},{text:'Saturn ada cincin.',answer:true},{text:'Pluto adalah planet besar.',answer:false}] },
      { statements: [{text:'Manusia perlu oksigen.',answer:true},{text:'Pokok hasilkan oksigen.',answer:true},{text:'Karbon dioksida untuk bernafas manusia.',answer:false},{text:'Otak mengawal pergerakan.',answer:true},{text:'Jantung di kepala.',answer:false},{text:'Ginjal menapis darah.',answer:true}] },
    ]),
  },
  {
    id: 'logic-sebab-akibat',
    title: 'Padan Sebab dan Akibat',
    emoji: '🔗',
    mode: 'tilematch',
    objective: 'Padankan sebab dengan akibat.',
    reward: 'Cause star',
    rounds: makeRounds([
      { tiles: ['Hujan','Basah','Matahari','Panas'] },
      { tiles: ['Lapar','Makan','Letih','Tidur'] },
      { tiles: ['Hujan','Basah','Matahari','Panas','Sejuk','Pakai Jaket'] },
      { tiles: ['Lapar','Makan','Letih','Tidur','Dahaga','Minum'] },
      { tiles: ['Belajar','Pandai','Bersukan','Sihat','Tak Mandi','Berbau','Buat Kerja','Penat'] },
      { tiles: ['Berlari','Tercungap','Menangis','Sedih','Ketawa','Gembira','Jatuh','Sakit'] },
      { tiles: ['Lapar','Makan','Dahaga','Minum','Letih','Tidur','Belajar','Pandai','Sukan','Sihat'] },
      { tiles: ['Tak Belajar','Tak Faham','Tak Makan','Lemah','Tak Tidur','Mengantuk','Tak Mandi','Berbau'] },
      { tiles: ['Hujan','Banjir','Panas','Kering','Angin','Sejuk','Gempa','Runtuh','Petir','Cahaya'] },
      { tiles: ['Belajar Banyak','Lulus','Tipu','Kantoi','Tolong','Disayangi','Marah','Dijauhi','Jujur','Dihormati','Curi','Ditangkap'] },
    ]),
  },
  {
    id: 'logic-bilangan-kaki',
    title: 'Berapa Kaki?',
    emoji: '🦵',
    mode: 'sorting',
    objective: 'Asingkan haiwan ikut bilangan kaki.',
    reward: 'Count logic',
    rounds: makeRounds([
      { groups: ['2 Kaki','4 Kaki'], items: [{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🦆',group:'2 Kaki'}] },
      { groups: ['2 Kaki','4 Kaki'], items: [{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🦆',group:'2 Kaki'},{text:'🐈',group:'4 Kaki'}] },
      { groups: ['2 Kaki','4 Kaki','Banyak Kaki'], items: [{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🕷️',group:'Banyak Kaki'},{text:'🦆',group:'2 Kaki'}] },
      { groups: ['Tiada Kaki','2 Kaki','4 Kaki'], items: [{text:'🐍',group:'Tiada Kaki'},{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🐟',group:'Tiada Kaki'},{text:'🦆',group:'2 Kaki'}] },
      { groups: ['Tiada Kaki','2 Kaki','4 Kaki','Banyak'], items: [{text:'🐍',group:'Tiada Kaki'},{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🕷️',group:'Banyak'},{text:'🐟',group:'Tiada Kaki'},{text:'🦆',group:'2 Kaki'}] },
      { groups: ['Tiada Kaki','2 Kaki','4 Kaki','6 Kaki','Lebih'], items: [{text:'🐍',group:'Tiada Kaki'},{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🐝',group:'6 Kaki'},{text:'🦂',group:'Lebih'},{text:'🐟',group:'Tiada Kaki'},{text:'🦅',group:'2 Kaki'}] },
      { groups: ['Tiada Kaki','2 Kaki','4 Kaki','6 Kaki'], items: [{text:'🐍',group:'Tiada Kaki'},{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🐞',group:'6 Kaki'},{text:'🐟',group:'Tiada Kaki'},{text:'🦆',group:'2 Kaki'},{text:'🐎',group:'4 Kaki'},{text:'🦋',group:'6 Kaki'}] },
      { groups: ['2 Kaki','4 Kaki','6 Kaki','8 Kaki'], items: [{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🐝',group:'6 Kaki'},{text:'🕷️',group:'8 Kaki'},{text:'🦅',group:'2 Kaki'},{text:'🐈',group:'4 Kaki'},{text:'🦋',group:'6 Kaki'},{text:'🐙',group:'8 Kaki'}] },
      { groups: ['Tiada','2','4','6','8'], items: [{text:'🐍',group:'Tiada'},{text:'🐔',group:'2'},{text:'🐕',group:'4'},{text:'🐝',group:'6'},{text:'🕷️',group:'8'},{text:'🐟',group:'Tiada'},{text:'🦆',group:'2'},{text:'🐎',group:'4'}] },
      { groups: ['Tiada Kaki','2 Kaki','4 Kaki','6 Kaki','8 Kaki','Banyak'], items: [{text:'🐍',group:'Tiada Kaki'},{text:'🐔',group:'2 Kaki'},{text:'🐕',group:'4 Kaki'},{text:'🐝',group:'6 Kaki'},{text:'🕷️',group:'8 Kaki'},{text:'🐛',group:'Banyak'},{text:'🐟',group:'Tiada Kaki'},{text:'🦆',group:'2 Kaki'}] },
    ]),
  },
  {
    id: 'logic-nombor-bandingkan',
    title: 'Bandingkan Nombor',
    emoji: '⚖️',
    mode: 'true_false',
    objective: 'Nilai persamaan matematik.',
    reward: 'Math judge',
    rounds: makeRounds([
      { statements: [{text:'5 > 3',answer:true},{text:'2 > 7',answer:false}] },
      { statements: [{text:'10 = 10',answer:true},{text:'4 > 9',answer:false}] },
      { statements: [{text:'8 > 3',answer:true},{text:'5 < 2',answer:false},{text:'7 = 7',answer:true}] },
      { statements: [{text:'15 > 10',answer:true},{text:'20 < 5',answer:false},{text:'12 = 12',answer:true},{text:'8 > 8',answer:false}] },
      { statements: [{text:'2+3 = 5',answer:true},{text:'4+1 = 6',answer:false},{text:'7-3 = 4',answer:true},{text:'10-5 = 6',answer:false}] },
      { statements: [{text:'3 × 2 = 6',answer:true},{text:'4 × 3 = 11',answer:false},{text:'5 × 0 = 0',answer:true},{text:'2 × 5 = 10',answer:true},{text:'6 × 2 = 13',answer:false}] },
      { statements: [{text:'10 ÷ 2 = 5',answer:true},{text:'8 ÷ 4 = 3',answer:false},{text:'15 ÷ 3 = 5',answer:true},{text:'20 ÷ 4 = 6',answer:false},{text:'12 ÷ 6 = 2',answer:true}] },
      { statements: [{text:'100 > 99',answer:true},{text:'50 = 50',answer:true},{text:'25 > 30',answer:false},{text:'75 < 60',answer:false},{text:'80 = 80',answer:true},{text:'45 > 50',answer:false}] },
      { statements: [{text:'1 + 1 = 2',answer:true},{text:'2 + 2 = 5',answer:false},{text:'3 × 3 = 9',answer:true},{text:'4 × 4 = 15',answer:false},{text:'5 × 5 = 25',answer:true},{text:'6 + 6 = 11',answer:false},{text:'7 + 7 = 14',answer:true}] },
      { statements: [{text:'1/2 = 0.5',answer:true},{text:'1/4 = 0.25',answer:true},{text:'100% = 1',answer:true},{text:'1/3 = 0.5',answer:false},{text:'50% = 0.5',answer:true},{text:'1 + 0 = 0',answer:false},{text:'0 × 100 = 0',answer:true},{text:'10 ÷ 0 = 10',answer:false}] },
    ]),
  },
  {
    id: 'logic-tempat-kerja',
    title: 'Pekerja Kerja Mana?',
    emoji: '🏥',
    mode: 'sorting',
    objective: 'Asingkan pekerja ikut tempat kerja.',
    reward: 'Career logic',
    rounds: makeRounds([
      { groups: ['Hospital','Sekolah'], items: [{text:'Doktor',group:'Hospital'},{text:'Guru',group:'Sekolah'},{text:'Jururawat',group:'Hospital'}] },
      { groups: ['Hospital','Sekolah','Restoran'], items: [{text:'Doktor',group:'Hospital'},{text:'Guru',group:'Sekolah'},{text:'Tukang Masak',group:'Restoran'},{text:'Pelayan',group:'Restoran'}] },
      { groups: ['Hospital','Sekolah','Restoran','Balai Polis'], items: [{text:'Doktor',group:'Hospital'},{text:'Guru',group:'Sekolah'},{text:'Tukang Masak',group:'Restoran'},{text:'Polis',group:'Balai Polis'}] },
      { groups: ['Bandar','Kampung','Hutan'], items: [{text:'Peniaga',group:'Bandar'},{text:'Petani',group:'Kampung'},{text:'Ranger',group:'Hutan'},{text:'Akauntan',group:'Bandar'}] },
      { groups: ['Hospital','Sekolah','Restoran','Bomba'], items: [{text:'Doktor',group:'Hospital'},{text:'Guru',group:'Sekolah'},{text:'Chef',group:'Restoran'},{text:'Pegawai Bomba',group:'Bomba'},{text:'Jururawat',group:'Hospital'},{text:'Pengetua',group:'Sekolah'}] },
      { groups: ['Darat','Air','Udara'], items: [{text:'Pemandu Bas',group:'Darat'},{text:'Nelayan',group:'Air'},{text:'Juruterbang',group:'Udara'},{text:'Polis Trafik',group:'Darat'},{text:'Penyelam',group:'Air'},{text:'Pramugari',group:'Udara'}] },
      { groups: ['Sekolah','Hospital','Balai Bomba','Pejabat'], items: [{text:'Guru',group:'Sekolah'},{text:'Doktor',group:'Hospital'},{text:'Bomba',group:'Balai Bomba'},{text:'Setiausaha',group:'Pejabat'},{text:'Pengetua',group:'Sekolah'},{text:'Jururawat',group:'Hospital'},{text:'CEO',group:'Pejabat'}] },
      { groups: ['Sains','Seni','Sukan'], items: [{text:'Saintis',group:'Sains'},{text:'Pelukis',group:'Seni'},{text:'Pemain Bola',group:'Sukan'},{text:'Doktor',group:'Sains'},{text:'Penyanyi',group:'Seni'},{text:'Atlet',group:'Sukan'},{text:'Jurutera',group:'Sains'}] },
      { groups: ['Hospital','Sekolah','Restoran','Bomba','Polis','Pejabat'], items: [{text:'Doktor',group:'Hospital'},{text:'Guru',group:'Sekolah'},{text:'Chef',group:'Restoran'},{text:'Bomba',group:'Bomba'},{text:'Polis',group:'Polis'},{text:'CEO',group:'Pejabat'},{text:'Jururawat',group:'Hospital'},{text:'Pelayan',group:'Restoran'}] },
      { groups: ['Darat','Air','Udara','Luar Angkasa'], items: [{text:'Pemandu',group:'Darat'},{text:'Nelayan',group:'Air'},{text:'Juruterbang',group:'Udara'},{text:'Angkasawan',group:'Luar Angkasa'},{text:'Polis',group:'Darat'},{text:'Penyelam',group:'Air'},{text:'Pramugari',group:'Udara'},{text:'Saintis NASA',group:'Luar Angkasa'}] },
    ]),
  },
];