// 🌀 MAZE ADVENTURE — 10 games × 10 rounds. Penerokaan + pilihan.
import { makeRounds } from './_helpers.js';

export const mazeAdventureGames = [
  {
    id: 'maze-arnab-lobak',
    title: 'Bantu Arnab Cari Lobak',
    emoji: '🐰',
    mode: 'maze',
    objective: 'Bawa arnab ke lobak tanpa tersesat.',
    reward: 'Maze clear',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({size:3+Math.min(i,7),goal:'🥕',player:'🐰'}))),
  },
  {
    id: 'maze-cari-harta',
    title: 'Cari Harta Karun',
    emoji: '💎',
    mode: 'hidden_object',
    objective: 'Cari permata tersembunyi.',
    reward: 'Treasure badge',
    rounds: makeRounds([
      { target: '💎', items: [{text:'⭐',value:'bintang'},{text:'💎',value:'permata'},{text:'🚀',value:'roket'}] },
      { target: '👑', items: [{text:'👑',value:'mahkota'},{text:'💎',value:'permata'},{text:'⭐',value:'bintang'},{text:'🎁',value:'hadiah'}] },
      { target: '🏆', items: [{text:'🏆',value:'piala'},{text:'👑',value:'mahkota'},{text:'💎',value:'permata'},{text:'🥇',value:'pingat'},{text:'⭐',value:'bintang'}] },
      { target: '🎁', items: [{text:'🎁',value:'hadiah'},{text:'💎',value:'permata'},{text:'👑',value:'mahkota'},{text:'🏆',value:'piala'},{text:'⭐',value:'bintang'},{text:'🥇',value:'pingat'}] },
      { target: '🥇', items: [{text:'🥇',value:'emas'},{text:'🥈',value:'perak'},{text:'🥉',value:'gangsa'},{text:'🏆',value:'piala'},{text:'👑',value:'mahkota'},{text:'💎',value:'permata'},{text:'⭐',value:'bintang'}] },
      { target: '💍', items: [{text:'💍',value:'cincin'},{text:'👑',value:'mahkota'},{text:'💎',value:'permata'},{text:'🏆',value:'piala'},{text:'🥇',value:'emas'},{text:'🎁',value:'hadiah'},{text:'⭐',value:'bintang'},{text:'🥈',value:'perak'}] },
      { target: '🔱', items: [{text:'🔱',value:'cokmar'},{text:'⚔️',value:'pedang'},{text:'🛡️',value:'perisai'},{text:'💎',value:'permata'},{text:'👑',value:'mahkota'},{text:'🏆',value:'piala'},{text:'🥇',value:'emas'},{text:'🎁',value:'hadiah'},{text:'⭐',value:'bintang'}] },
      { target: '⚔️', items: [{text:'⚔️',value:'pedang'},{text:'🛡️',value:'perisai'},{text:'🔱',value:'cokmar'},{text:'🏹',value:'busur'},{text:'💎',value:'permata'},{text:'👑',value:'mahkota'},{text:'🏆',value:'piala'},{text:'🥇',value:'emas'},{text:'🎁',value:'hadiah'},{text:'⭐',value:'bintang'}] },
      { target: '🛡️', items: [{text:'🛡️',value:'perisai'},{text:'⚔️',value:'pedang'},{text:'🏹',value:'busur'},{text:'🔱',value:'cokmar'},{text:'💎',value:'permata'},{text:'👑',value:'mahkota'},{text:'🏆',value:'piala'},{text:'🥇',value:'emas'},{text:'🎁',value:'hadiah'},{text:'⭐',value:'bintang'},{text:'💍',value:'cincin'}] },
      { target: '🏹', items: [{text:'🏹',value:'busur'},{text:'⚔️',value:'pedang'},{text:'🛡️',value:'perisai'},{text:'🔱',value:'cokmar'},{text:'💎',value:'permata'},{text:'👑',value:'mahkota'},{text:'🏆',value:'piala'},{text:'🥇',value:'emas'},{text:'🥈',value:'perak'},{text:'🥉',value:'gangsa'},{text:'🎁',value:'hadiah'},{text:'⭐',value:'bintang'}] },
    ]),
  },
  {
    id: 'maze-pilih-jalan',
    title: 'Pilih Jalan Bijak',
    emoji: '📖',
    mode: 'story',
    objective: 'Buat keputusan paling baik.',
    reward: 'Wise path',
    rounds: makeRounds([
      { scenes: [{text:'Ali nampak kawan jatuh basikal. Apa Ali patut buat?',choices:['Tolong dia','Ketawa','Lari'],answer:0}] },
      { scenes: [{text:'Hujan turun. Ibu jemur baju di luar. Apa kau buat?',choices:['Bantu angkat','Biar saja','Tidur'],answer:0}] },
      { scenes: [{text:'Jumpa duit di lantai sekolah. Apa kau buat?',choices:['Ambil simpan','Hantar pejabat guru','Bagi kawan'],answer:1}] },
      { scenes: [{text:'Adik nampak takut nak naik basikal. Apa kau buat?',choices:['Ketawa','Galakkan dia','Tolak basikal'],answer:1}] },
      { scenes: [{text:'Nampak nenek tua nak melintas jalan. Apa kau buat?',choices:['Bantu melintas','Buat tak nampak','Tunggu',],answer:0}] },
      { scenes: [{text:'Sampah ada di lantai kelas. Apa kau buat?',choices:['Pungut buang','Tinggalkan','Tendang'],answer:0}] },
      { scenes: [{text:'Kawan baru di kelas tak ada kawan. Apa kau buat?',choices:['Buat tak peduli','Jemput main bersama','Gelakkan'],answer:1}] },
      { scenes: [{text:'Guru beri kerja sekolah susah. Apa kau buat?',choices:['Tinggalkan','Cuba sungguh-sungguh','Salin kawan'],answer:1}] },
      { scenes: [{text:'Nampak kucing kurus lapar. Apa kau buat?',choices:['Tidak peduli','Beri makanan sikit','Tendang'],answer:1}] },
      { scenes: [{text:'Ibu sakit, rumah berselerak. Apa kau buat?',choices:['Main game','Bantu kemas','Pergi keluar'],answer:1}] },
    ]),
  },
  {
    id: 'maze-cari-watak',
    title: 'Cari Watak Dalam Hutan',
    emoji: '🦊',
    mode: 'hidden_object',
    objective: 'Cari watak yang ditunjukkan.',
    reward: 'Forest find',
    rounds: makeRounds([
      { target: '🦊', items: [{text:'🦊',value:'musang'},{text:'🐰',value:'arnab'},{text:'🐻',value:'beruang'}] },
      { target: '🐻', items: [{text:'🐻',value:'beruang'},{text:'🦊',value:'musang'},{text:'🐰',value:'arnab'},{text:'🐺',value:'serigala'}] },
      { target: '🦌', items: [{text:'🦌',value:'rusa'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🐻',value:'beruang'},{text:'🐗',value:'babi hutan'}] },
      { target: '🐗', items: [{text:'🐗',value:'babi hutan'},{text:'🦌',value:'rusa'},{text:'🐻',value:'beruang'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🐰',value:'arnab'}] },
      { target: '🦝', items: [{text:'🦝',value:'rakun'},{text:'🐻',value:'beruang'},{text:'🦌',value:'rusa'},{text:'🐗',value:'babi hutan'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🦔',value:'landak'}] },
      { target: '🦡', items: [{text:'🦡',value:'badger'},{text:'🦝',value:'rakun'},{text:'🦔',value:'landak'},{text:'🐻',value:'beruang'},{text:'🦌',value:'rusa'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🐗',value:'babi hutan'}] },
      { target: '🦔', items: [{text:'🦔',value:'landak'},{text:'🦡',value:'badger'},{text:'🦝',value:'rakun'},{text:'🐻',value:'beruang'},{text:'🦌',value:'rusa'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🐗',value:'babi hutan'},{text:'🐿️',value:'tupai'}] },
      { target: '🐿️', items: [{text:'🐿️',value:'tupai'},{text:'🦔',value:'landak'},{text:'🦡',value:'badger'},{text:'🦝',value:'rakun'},{text:'🐻',value:'beruang'},{text:'🦌',value:'rusa'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🐗',value:'babi hutan'},{text:'🦅',value:'helang'}] },
      { target: '🦅', items: [{text:'🦅',value:'helang'},{text:'🐿️',value:'tupai'},{text:'🦔',value:'landak'},{text:'🦡',value:'badger'},{text:'🦝',value:'rakun'},{text:'🐻',value:'beruang'},{text:'🦌',value:'rusa'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🐗',value:'babi hutan'},{text:'🦉',value:'burung hantu'}] },
      { target: '🦉', items: [{text:'🦉',value:'burung hantu'},{text:'🦅',value:'helang'},{text:'🐿️',value:'tupai'},{text:'🦔',value:'landak'},{text:'🦡',value:'badger'},{text:'🦝',value:'rakun'},{text:'🐻',value:'beruang'},{text:'🦌',value:'rusa'},{text:'🦊',value:'musang'},{text:'🐺',value:'serigala'},{text:'🐗',value:'babi hutan'},{text:'🦇',value:'kelawar'}] },
    ]),
  },
  {
    id: 'maze-laut-dalam',
    title: 'Cari Harta di Laut Dalam',
    emoji: '🐙',
    mode: 'hidden_object',
    objective: 'Cari makhluk laut yang ditunjukkan.',
    reward: 'Deep sea badge',
    rounds: makeRounds([
      { target: '🐙', items: [{text:'🐙',value:'sotong kurita'},{text:'🐠',value:'ikan'},{text:'🦐',value:'udang'}] },
      { target: '🦈', items: [{text:'🦈',value:'yu'},{text:'🐠',value:'ikan'},{text:'🐙',value:'sotong kurita'},{text:'🐢',value:'penyu'}] },
      { target: '🐢', items: [{text:'🐢',value:'penyu'},{text:'🐬',value:'lumba-lumba'},{text:'🐠',value:'ikan'},{text:'🦈',value:'yu'},{text:'🐙',value:'sotong kurita'}] },
      { target: '🐬', items: [{text:'🐬',value:'lumba-lumba'},{text:'🐳',value:'paus'},{text:'🦭',value:'anjing laut'},{text:'🐢',value:'penyu'},{text:'🦈',value:'yu'},{text:'🐠',value:'ikan'}] },
      { target: '🐳', items: [{text:'🐳',value:'paus'},{text:'🐬',value:'lumba-lumba'},{text:'🦈',value:'yu'},{text:'🐢',value:'penyu'},{text:'🦭',value:'anjing laut'},{text:'🐙',value:'sotong kurita'},{text:'🦑',value:'sotong'}] },
      { target: '🦭', items: [{text:'🦭',value:'anjing laut'},{text:'🐳',value:'paus'},{text:'🐬',value:'lumba-lumba'},{text:'🐢',value:'penyu'},{text:'🦈',value:'yu'},{text:'🐠',value:'ikan'},{text:'🐙',value:'sotong kurita'},{text:'🦑',value:'sotong'}] },
      { target: '🦑', items: [{text:'🦑',value:'sotong'},{text:'🐙',value:'sotong kurita'},{text:'🦐',value:'udang'},{text:'🦞',value:'udang karang'},{text:'🦀',value:'ketam'},{text:'🐠',value:'ikan'},{text:'🦈',value:'yu'},{text:'🐢',value:'penyu'},{text:'🐬',value:'lumba-lumba'}] },
      { target: '🦀', items: [{text:'🦀',value:'ketam'},{text:'🦞',value:'udang karang'},{text:'🦐',value:'udang'},{text:'🐙',value:'sotong kurita'},{text:'🦑',value:'sotong'},{text:'🐠',value:'ikan'},{text:'🦈',value:'yu'},{text:'🐢',value:'penyu'},{text:'🐬',value:'lumba-lumba'},{text:'🐳',value:'paus'}] },
      { target: '🦞', items: [{text:'🦞',value:'udang karang'},{text:'🦀',value:'ketam'},{text:'🦐',value:'udang'},{text:'🐙',value:'sotong kurita'},{text:'🦑',value:'sotong'},{text:'🐠',value:'ikan'},{text:'🦈',value:'yu'},{text:'🐢',value:'penyu'},{text:'🐬',value:'lumba-lumba'},{text:'🐳',value:'paus'},{text:'🦭',value:'anjing laut'}] },
      { target: '🐠', items: [{text:'🐠',value:'ikan tropika'},{text:'🐟',value:'ikan kembung'},{text:'🐡',value:'ikan buntal'},{text:'🦈',value:'yu'},{text:'🦞',value:'udang karang'},{text:'🦀',value:'ketam'},{text:'🦐',value:'udang'},{text:'🐙',value:'sotong kurita'},{text:'🦑',value:'sotong'},{text:'🐢',value:'penyu'},{text:'🐬',value:'lumba-lumba'},{text:'🐳',value:'paus'}] },
    ]),
  },
  {
    id: 'maze-pilih-pintu',
    title: 'Pilih Pintu Selamat',
    emoji: '🚪',
    mode: 'story',
    objective: 'Pilih pintu yang membawa kepada hadiah.',
    reward: 'Lucky door',
    rounds: makeRounds([
      { scenes: [{text:'Ada 3 pintu. Pintu mana yang berwarna emas?',choices:['Pintu Kayu','Pintu Emas','Pintu Besi'],answer:1}] },
      { scenes: [{text:'Pintu mana yang ada simbol bintang?',choices:['Pintu Bulan','Pintu Bintang','Pintu Awan'],answer:1}] },
      { scenes: [{text:'Pintu mana paling besar?',choices:['Pintu Kecil','Pintu Sederhana','Pintu Gergasi'],answer:2}] },
      { scenes: [{text:'Mana satu bukan pintu istana?',choices:['Pintu Emas','Pintu Marmar','Pintu Kotak'],answer:2}] },
      { scenes: [{text:'Pintu mana yang ada cahaya keluar?',choices:['Pintu Gelap','Pintu Cahaya','Pintu Tertutup'],answer:1}] },
      { scenes: [{text:'Wira melintasi 3 jambatan. Mana yang paling selamat?',choices:['Jambatan Patah','Jambatan Baru','Jambatan Reput'],answer:1}] },
      { scenes: [{text:'Ada 4 peti. Peti mana berisi harta?',choices:['Peti Berkunci Emas','Peti Berlubang','Peti Patah','Peti Berkarat'],answer:0}] },
      { scenes: [{text:'Pilih cara terbaik untuk seberangi sungai deras.',choices:['Berenang','Naik rakit','Loncat','Terbang'],answer:1}] },
      { scenes: [{text:'Wira nampak 4 laluan ke puncak gunung. Mana paling bijak?',choices:['Laluan licin','Laluan curam','Laluan beranak tangga','Laluan beraga'],answer:2}] },
      { scenes: [{text:'Untuk buka peti harta, mana kunci paling sesuai?',choices:['Kunci besi','Kunci emas','Kunci kayu','Kunci plastik'],answer:1}] },
    ]),
  },
  {
    id: 'maze-jalan-bandar',
    title: 'Cari Jalan ke Bandar',
    emoji: '🏙️',
    mode: 'maze',
    objective: 'Bawa watak ke pusat bandar.',
    reward: 'City clear',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({size:4+Math.min(i,6),goal:'🏙️',player:'🚶'}))),
  },
  {
    id: 'maze-misi-pilih',
    title: 'Misi Wira',
    emoji: '🦸',
    mode: 'story',
    objective: 'Buat keputusan terbaik dalam misi.',
    reward: 'Hero arc',
    rounds: makeRounds([
      { scenes: [{text:'Wira nampak kebakaran kecil. Apa dia patut buat?',choices:['Panggil bomba','Sembunyi','Tonton'],answer:0}] },
      { scenes: [{text:'Wira jumpa beg hilang. Apa nak buat?',choices:['Hantar polis','Buka isi','Lari'],answer:0}] },
      { scenes: [{text:'Wira nampak orang pengsan. Tindakan pertama?',choices:['Hubungi 999','Tolak','Lari'],answer:0}] },
      { scenes: [{text:'Wira nampak budak terkunci dalam kereta panas. Apa nak buat?',choices:['Cari penjaga','Pukul cermin','Tinggalkan'],answer:0}] },
      { scenes: [{text:'Wira melihat kebocoran air paip besar. Apa nak buat?',choices:['Lapor pihak berkuasa','Biarkan','Tutup dengan jari'],answer:0}] },
      { scenes: [{text:'Wira nampak anjing tersesat. Apa langkah pertama?',choices:['Hubungi penjaga haiwan','Tangkap kasar','Pukul'],answer:0}] },
      { scenes: [{text:'Wira lihat lampu isyarat rosak. Apa nak buat?',choices:['Lapor MBSJ/MBPJ','Pandu laju','Berbut isyarat sendiri'],answer:0}] },
      { scenes: [{text:'Banjir melanda kampung. Apa wira buat pertama?',choices:['Bantu mangsa pindah','Tidur','Ambil gambar untuk medsos'],answer:0}] },
      { scenes: [{text:'Ada lubang besar di jalan. Apa nak buat?',choices:['Letak amaran sementara dan lapor','Biarkan','Tutup dengan kerikil'],answer:0}] },
      { scenes: [{text:'Wira nampak gempa kecil di sekolah. Apa langkah pertama?',choices:['Lindungi diri bawah meja','Lari laju ke tingkat atas','Berdiri tengah bilik'],answer:0}] },
    ]),
  },
  {
    id: 'maze-cari-jejak',
    title: 'Ikut Jejak Kaki',
    emoji: '👣',
    mode: 'sequence',
    objective: 'Ikut jejak mengikut urutan.',
    reward: 'Trail combo',
    rounds: makeRounds([
      { items: ['⬆️','➡️'], answer: ['⬆️','➡️'] },
      { items: ['⬆️','➡️','⬇️'], answer: ['⬆️','➡️','⬇️'] },
      { items: ['⬆️','➡️','⬇️','⬅️'], answer: ['⬆️','➡️','⬇️','⬅️'] },
      { items: ['⬆️','⬆️','➡️','⬇️','⬅️'], answer: ['⬆️','⬆️','➡️','⬇️','⬅️'] },
      { items: ['⬆️','➡️','➡️','⬇️','⬅️','⬅️'], answer: ['⬆️','➡️','➡️','⬇️','⬅️','⬅️'] },
      { items: ['⬆️','➡️','⬆️','➡️','⬇️','⬅️','⬇️'], answer: ['⬆️','➡️','⬆️','➡️','⬇️','⬅️','⬇️'] },
      { items: ['↗️','⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️'], answer: ['↗️','⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️'] },
      { items: ['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️','⬆️'], answer: ['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️','⬆️'] },
      { items: ['⬆️','⬆️','➡️','➡️','⬇️','⬇️','⬅️','⬅️','⬆️','➡️'], answer: ['⬆️','⬆️','➡️','➡️','⬇️','⬇️','⬅️','⬅️','⬆️','➡️'] },
      { items: ['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️','⬆️','↗️'], answer: ['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️','⬆️','↗️'] },
    ]),
  },
  {
    id: 'maze-kelaskan-laluan',
    title: 'Kelaskan Tempat',
    emoji: '🗺️',
    mode: 'sorting',
    objective: 'Asingkan tempat ikut kategori.',
    reward: 'Map smart',
    rounds: makeRounds([
      { groups: ['Bandar','Kampung'], items: [{text:'KLCC',group:'Bandar'},{text:'Sawah Padi',group:'Kampung'},{text:'Bangunan Tinggi',group:'Bandar'}] },
      { groups: ['Darat','Laut'], items: [{text:'Gunung',group:'Darat'},{text:'Pulau',group:'Laut'},{text:'Hutan',group:'Darat'}] },
      { groups: ['Bandar','Kampung'], items: [{text:'KLCC',group:'Bandar'},{text:'Sawah Padi',group:'Kampung'},{text:'Bangunan Tinggi',group:'Bandar'},{text:'Pondok',group:'Kampung'}] },
      { groups: ['Darat','Laut','Udara'], items: [{text:'Gunung',group:'Darat'},{text:'Laut China Selatan',group:'Laut'},{text:'Awan',group:'Udara'},{text:'Hutan',group:'Darat'}] },
      { groups: ['Bandar','Kampung','Hutan'], items: [{text:'KLCC',group:'Bandar'},{text:'Sawah Padi',group:'Kampung'},{text:'Taman Negara',group:'Hutan'},{text:'Pasar Tani',group:'Kampung'},{text:'Pavilion',group:'Bandar'}] },
      { groups: ['Pantai','Gunung','Tasik'], items: [{text:'Pantai Cherating',group:'Pantai'},{text:'Gunung Kinabalu',group:'Gunung'},{text:'Tasik Kenyir',group:'Tasik'},{text:'Pantai Tioman',group:'Pantai'},{text:'Gunung Tahan',group:'Gunung'}] },
      { groups: ['Tarikan Pelancongan','Tempat Kerja','Tempat Belajar'], items: [{text:'KLCC',group:'Tarikan Pelancongan'},{text:'Pejabat',group:'Tempat Kerja'},{text:'Sekolah',group:'Tempat Belajar'},{text:'Universiti',group:'Tempat Belajar'},{text:'Kilang',group:'Tempat Kerja'}] },
      { groups: ['Semenanjung','Sabah','Sarawak'], items: [{text:'Perak',group:'Semenanjung'},{text:'Kota Kinabalu',group:'Sabah'},{text:'Kuching',group:'Sarawak'},{text:'Johor',group:'Semenanjung'},{text:'Sandakan',group:'Sabah'},{text:'Miri',group:'Sarawak'}] },
      { groups: ['Sungai','Air Terjun','Tasik'], items: [{text:'Sungai Pahang',group:'Sungai'},{text:'Air Terjun Lata Kinjang',group:'Air Terjun'},{text:'Tasik Kenyir',group:'Tasik'},{text:'Sungai Kelantan',group:'Sungai'},{text:'Air Terjun Telaga Tujuh',group:'Air Terjun'},{text:'Tasik Chini',group:'Tasik'}] },
      { groups: ['Pantai','Gunung','Tasik','Pulau'], items: [{text:'Pantai Cherating',group:'Pantai'},{text:'Gunung Kinabalu',group:'Gunung'},{text:'Tasik Kenyir',group:'Tasik'},{text:'Pulau Langkawi',group:'Pulau'},{text:'Pantai Tioman',group:'Pantai'},{text:'Gunung Tahan',group:'Gunung'},{text:'Tasik Chini',group:'Tasik'},{text:'Pulau Redang',group:'Pulau'}] },
    ]),
  },
];