// 🌀 MAZE ADVENTURE — 10 games × 10 rounds. Tema campuran (pengembaraan + pilihan bijak).
import { makeRounds } from './_helpers.js';

export const mazeAdventureGames = [
  {
    id: 'maze-kucing-susu',
    title: 'Bantu Kucing Cari Susu',
    emoji: '🐱',
    mode: 'maze',
    objective: 'Bawa kucing ke pinggan susu.',
    reward: 'Cat path',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({size:3+Math.min(i,7),goal:'🥛',player:'🐱'}))),
  },
  {
    id: 'maze-cari-bintang',
    title: 'Cari Bintang Hilang',
    emoji: '⭐',
    mode: 'hidden_object',
    objective: 'Cari bintang dalam langit malam.',
    reward: 'Star find',
    rounds: makeRounds([
      { target: '⭐', items: [{text:'⭐',value:'bintang'},{text:'🌙',value:'bulan'},{text:'☁️',value:'awan'}] },
      { target: '🌟', items: [{text:'🌟',value:'bintang besar'},{text:'⭐',value:'bintang'},{text:'🌙',value:'bulan'},{text:'☄️',value:'komet'}] },
      { target: '💫', items: [{text:'💫',value:'bintang pusing'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'🌙',value:'bulan'},{text:'☄️',value:'komet'}] },
      { target: '✨', items: [{text:'✨',value:'cahaya'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'💫',value:'pusing'},{text:'🌙',value:'bulan'},{text:'☁️',value:'awan'}] },
      { target: '☄️', items: [{text:'☄️',value:'komet'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'💫',value:'pusing'},{text:'✨',value:'cahaya'},{text:'🌙',value:'bulan'},{text:'🌌',value:'galaksi'}] },
      { target: '🌌', items: [{text:'🌌',value:'galaksi'},{text:'☄️',value:'komet'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'💫',value:'pusing'},{text:'✨',value:'cahaya'},{text:'🌙',value:'bulan'},{text:'🪐',value:'planet'}] },
      { target: '🪐', items: [{text:'🪐',value:'planet'},{text:'🌌',value:'galaksi'},{text:'☄️',value:'komet'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'💫',value:'pusing'},{text:'✨',value:'cahaya'},{text:'🌙',value:'bulan'},{text:'🌍',value:'bumi'}] },
      { target: '🌍', items: [{text:'🌍',value:'bumi'},{text:'🪐',value:'planet'},{text:'🌌',value:'galaksi'},{text:'☄️',value:'komet'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'💫',value:'pusing'},{text:'✨',value:'cahaya'},{text:'🌙',value:'bulan'},{text:'☀️',value:'matahari'}] },
      { target: '☀️', items: [{text:'☀️',value:'matahari'},{text:'🌍',value:'bumi'},{text:'🪐',value:'planet'},{text:'🌌',value:'galaksi'},{text:'☄️',value:'komet'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'💫',value:'pusing'},{text:'✨',value:'cahaya'},{text:'🌙',value:'bulan'},{text:'🛸',value:'UFO'}] },
      { target: '🛸', items: [{text:'🛸',value:'UFO'},{text:'☀️',value:'matahari'},{text:'🌍',value:'bumi'},{text:'🪐',value:'planet'},{text:'🌌',value:'galaksi'},{text:'☄️',value:'komet'},{text:'⭐',value:'bintang'},{text:'🌟',value:'besar'},{text:'💫',value:'pusing'},{text:'✨',value:'cahaya'},{text:'🌙',value:'bulan'},{text:'🚀',value:'roket'}] },
    ]),
  },
  {
    id: 'maze-pilih-baik',
    title: 'Pilih Tindakan Baik',
    emoji: '👍',
    mode: 'story',
    objective: 'Pilih jawapan yang terbaik.',
    reward: 'Good path',
    rounds: makeRounds([
      { scenes: [{text:'Kawan tertinggal pensel. Apa kau buat?',choices:['Pinjamkan','Buat tak nampak','Sembunyi'],answer:0}] },
      { scenes: [{text:'Adik menangis sebab takut gelap. Apa kau buat?',choices:['Ketawakan','Tenangkan','Tutup pintu'],answer:1}] },
      { scenes: [{text:'Mak suruh tolong angkat barang dapur. Apa kau buat?',choices:['Tolong terus','Pura tak dengar','Tidur'],answer:0}] },
      { scenes: [{text:'Kawan jatuh basikal. Apa kau buat?',choices:['Tolong dia bangun','Ketawa','Lari'],answer:0}] },
      { scenes: [{text:'Nampak sampah dekat kau. Apa kau buat?',choices:['Pungut buang','Tendang','Biarkan'],answer:0}] },
      { scenes: [{text:'Cikgu beri kerja banyak. Apa kau buat?',choices:['Buat satu-satu','Tinggalkan','Salin kawan'],answer:0}] },
      { scenes: [{text:'Kawan baru di kelas. Apa kau buat?',choices:['Sapa dia','Buat tak nampak','Cakap belakang'],answer:0}] },
      { scenes: [{text:'Nampak anak kucing tersesat. Apa kau buat?',choices:['Beritahu mak','Tangkap kasar','Buat tak nampak'],answer:0}] },
      { scenes: [{text:'Mak sakit kepala. Apa kau buat?',choices:['Buat bising','Beri ruang rehat','Buka TV kuat'],answer:1}] },
      { scenes: [{text:'Nampak kawan kena buli. Apa kau buat?',choices:['Bantu dan beritahu cikgu','Buat tak nampak','Sertai membuli'],answer:0}] },
    ]),
  },
  {
    id: 'maze-cari-haiwan-air',
    title: 'Cari Haiwan Air',
    emoji: '🐟',
    mode: 'hidden_object',
    objective: 'Cari haiwan air yang ditunjukkan.',
    reward: 'Sea find',
    rounds: makeRounds([
      { target: '🐟', items: [{text:'🐟',value:'ikan'},{text:'🦐',value:'udang'},{text:'🦀',value:'ketam'}] },
      { target: '🐬', items: [{text:'🐬',value:'lumba-lumba'},{text:'🐟',value:'ikan'},{text:'🦈',value:'yu'},{text:'🐢',value:'penyu'}] },
      { target: '🦈', items: [{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🐟',value:'ikan'},{text:'🐢',value:'penyu'},{text:'🐙',value:'sotong kurita'}] },
      { target: '🐙', items: [{text:'🐙',value:'sotong kurita'},{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🐢',value:'penyu'},{text:'🦑',value:'sotong'},{text:'🐠',value:'ikan tropika'}] },
      { target: '🐡', items: [{text:'🐡',value:'ikan buntal'},{text:'🐙',value:'sotong kurita'},{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🐢',value:'penyu'},{text:'🦑',value:'sotong'},{text:'🐠',value:'ikan tropika'}] },
      { target: '🐳', items: [{text:'🐳',value:'paus'},{text:'🐡',value:'buntal'},{text:'🐙',value:'kurita'},{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🐢',value:'penyu'},{text:'🦑',value:'sotong'},{text:'🐠',value:'tropika'}] },
      { target: '🦭', items: [{text:'🦭',value:'anjing laut'},{text:'🐳',value:'paus'},{text:'🐡',value:'buntal'},{text:'🐙',value:'kurita'},{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🐢',value:'penyu'},{text:'🦑',value:'sotong'},{text:'🐠',value:'tropika'}] },
      { target: '🦀', items: [{text:'🦀',value:'ketam'},{text:'🦭',value:'anjing laut'},{text:'🐳',value:'paus'},{text:'🐡',value:'buntal'},{text:'🐙',value:'kurita'},{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🦞',value:'udang karang'},{text:'🦐',value:'udang'}] },
      { target: '🦞', items: [{text:'🦞',value:'udang karang'},{text:'🦀',value:'ketam'},{text:'🦭',value:'anjing laut'},{text:'🐳',value:'paus'},{text:'🐡',value:'buntal'},{text:'🐙',value:'kurita'},{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🐢',value:'penyu'},{text:'🦑',value:'sotong'}] },
      { target: '🐢', items: [{text:'🐢',value:'penyu'},{text:'🦞',value:'udang karang'},{text:'🦀',value:'ketam'},{text:'🦭',value:'anjing laut'},{text:'🐳',value:'paus'},{text:'🐡',value:'buntal'},{text:'🐙',value:'kurita'},{text:'🦈',value:'yu'},{text:'🐬',value:'lumba-lumba'},{text:'🦑',value:'sotong'},{text:'🐠',value:'tropika'}] },
    ]),
  },
  {
    id: 'maze-jungle-cari',
    title: 'Cari di Hutan',
    emoji: '🌲',
    mode: 'hidden_object',
    objective: 'Cari makhluk hutan yang ditunjukkan.',
    reward: 'Jungle badge',
    rounds: makeRounds([
      { target: '🦒', items: [{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🦁',value:'singa'}] },
      { target: '🦓', items: [{text:'🦓',value:'kuda belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🐘',value:'gajah'}] },
      { target: '🐘', items: [{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🦏',value:'badak'}] },
      { target: '🦏', items: [{text:'🦏',value:'badak'},{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🦛',value:'kuda nil'}] },
      { target: '🦛', items: [{text:'🦛',value:'kuda nil'},{text:'🦏',value:'badak'},{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🦌',value:'rusa'}] },
      { target: '🦌', items: [{text:'🦌',value:'rusa'},{text:'🦛',value:'kuda nil'},{text:'🦏',value:'badak'},{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🐆',value:'harimau bintang'}] },
      { target: '🐆', items: [{text:'🐆',value:'harimau bintang'},{text:'🦌',value:'rusa'},{text:'🦛',value:'kuda nil'},{text:'🦏',value:'badak'},{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🦁',value:'singa'}] },
      { target: '🦁', items: [{text:'🦁',value:'singa'},{text:'🐆',value:'bintang'},{text:'🦌',value:'rusa'},{text:'🦛',value:'kuda nil'},{text:'🦏',value:'badak'},{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🦧',value:'mawas'}] },
      { target: '🦧', items: [{text:'🦧',value:'mawas'},{text:'🦁',value:'singa'},{text:'🐆',value:'bintang'},{text:'🦌',value:'rusa'},{text:'🦛',value:'kuda nil'},{text:'🦏',value:'badak'},{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🐒',value:'monyet'}] },
      { target: '🐒', items: [{text:'🐒',value:'monyet'},{text:'🦧',value:'mawas'},{text:'🦁',value:'singa'},{text:'🐆',value:'bintang'},{text:'🦌',value:'rusa'},{text:'🦛',value:'kuda nil'},{text:'🦏',value:'badak'},{text:'🐘',value:'gajah'},{text:'🦓',value:'belang'},{text:'🦒',value:'zirafah'},{text:'🐅',value:'harimau'},{text:'🦍',value:'gorila'}] },
    ]),
  },
  {
    id: 'maze-pilih-makanan',
    title: 'Pilih Makanan Sihat',
    emoji: '🥗',
    mode: 'story',
    objective: 'Pilih makanan yang lebih sihat.',
    reward: 'Health path',
    rounds: makeRounds([
      { scenes: [{text:'Mana lebih sihat untuk sarapan?',choices:['Oat dengan susu','Kek coklat','Kerepek'],answer:0}] },
      { scenes: [{text:'Snek mana paling sihat?',choices:['Buah epal','Gula-gula','Cip'],answer:0}] },
      { scenes: [{text:'Minuman mana terbaik untuk sukan?',choices:['Air kosong','Air berkarbonat','Kopi'],answer:0}] },
      { scenes: [{text:'Lauk mana paling berkhasiat?',choices:['Sayur dan ikan kukus','Ayam goreng','Mee segera'],answer:0}] },
      { scenes: [{text:'Cara terbaik masak telur untuk anak?',choices:['Telur rebus','Telur goreng minyak banyak','Telur ais'],answer:0}] },
      { scenes: [{text:'Pencuci mulut paling sihat?',choices:['Salad buah','Aiskrim','Donut'],answer:0}] },
      { scenes: [{text:'Berapa kali sepatutnya minum air sehari?',choices:['8 gelas','1 gelas','Tiada'],answer:0}] },
      { scenes: [{text:'Bila masa terbaik makan?',choices:['3 kali sehari','Sekali sahaja','Sepanjang masa'],answer:0}] },
      { scenes: [{text:'Mana protein terbaik?',choices:['Ikan/Ayam/Telur','Hanya gula','Hanya minyak'],answer:0}] },
      { scenes: [{text:'Berapa porsi sayur sehari?',choices:['5 hidangan','Tiada','1 kali sebulan'],answer:0}] },
    ]),
  },
  {
    id: 'maze-jalan-pulang',
    title: 'Cari Jalan Pulang',
    emoji: '🏠',
    mode: 'maze',
    objective: 'Bawa watak pulang ke rumah.',
    reward: 'Home clear',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({size:4+Math.min(i,6),goal:'🏠',player:'🚶'}))),
  },
  {
    id: 'maze-misi-selamatkan',
    title: 'Misi Selamatkan',
    emoji: '🚨',
    mode: 'story',
    objective: 'Pilih tindakan yang menyelamatkan.',
    reward: 'Rescue arc',
    rounds: makeRounds([
      { scenes: [{text:'Nampak api di dapur. Apa langkah pertama?',choices:['Panggil bomba','Cuba padam dengan minyak','Lari sahaja'],answer:0}] },
      { scenes: [{text:'Adik tersangkut di pokok. Apa nak buat?',choices:['Beritahu orang dewasa','Panjat ikut','Tinggalkan'],answer:0}] },
      { scenes: [{text:'Nampak orang lemas di kolam. Apa nak buat?',choices:['Panggil tolong','Loncat masuk sendiri','Tonton'],answer:0}] },
      { scenes: [{text:'Bangunan goyang sebab gempa. Apa nak buat?',choices:['Lindung bawah meja','Lari ke lif','Tunggu di tangga'],answer:0}] },
      { scenes: [{text:'Nampak kemalangan jalan. Apa langkah pertama?',choices:['Hubungi 999','Sentuh mangsa','Buat selfie'],answer:0}] },
      { scenes: [{text:'Banjir besar melanda. Apa nak buat?',choices:['Naik ke tempat tinggi','Berenang masuk arus','Tidur'],answer:0}] },
      { scenes: [{text:'Anak hilang di pasaraya. Apa pertama?',choices:['Lapor pengawal keselamatan','Cari sendiri tanpa lapor','Tunggu lama'],answer:0}] },
      { scenes: [{text:'Termakan ubat secara tak sengaja. Apa nak buat?',choices:['Hubungi hospital','Tidur','Diam'],answer:0}] },
      { scenes: [{text:'Tercedera dan berdarah. Apa langkah pertama?',choices:['Bersihkan dan bebatkan','Lap dengan kain kotor','Pijak luka'],answer:0}] },
      { scenes: [{text:'Nampak pencuri masuk rumah. Apa nak buat?',choices:['Telefon 999 senyap-senyap','Lawan sendiri','Tepuk tangan'],answer:0}] },
    ]),
  },
  {
    id: 'maze-cari-pulau',
    title: 'Cari Pulau Harta',
    emoji: '🏝️',
    mode: 'maze',
    objective: 'Bawa kapal ke pulau harta.',
    reward: 'Treasure trail',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({size:3+Math.min(i,7),goal:'🏝️',player:'⛵'}))),
  },
];