// 🧠 MEMORY MASTER — 10 games × 10 rounds. Tema campuran (haiwan, kenderaan, cuaca, sukan, alam, sekolah).
import { makeRounds } from './_helpers.js';

export const memoryMasterGames = [
  {
    id: 'memory-kenderaan',
    title: 'Padan Kenderaan',
    emoji: '🚗',
    mode: 'memory',
    objective: 'Padankan kenderaan dengan namanya.',
    reward: 'Memory streak',
    rounds: makeRounds([
      { pairs: [['🚗', 'Kereta'], ['🚌', 'Bas'], ['🚲', 'Basikal']] },
      { pairs: [['🚓', 'Polis'], ['🚑', 'Ambulans'], ['🚒', 'Bomba']] },
      { pairs: [['✈️', 'Kapal Terbang'], ['🚂', 'Keretapi'], ['🚢', 'Kapal']] },
      { pairs: [['🚗', 'Kereta'], ['🚌', 'Bas'], ['🚕', 'Teksi'], ['🛵', 'Skuter']] },
      { pairs: [['🚜', 'Traktor'], ['🚛', 'Lori'], ['🚚', 'Trak'], ['🏍️', 'Motosikal']] },
      { pairs: [['🚁', 'Helikopter'], ['🛸', 'UFO'], ['🚀', 'Roket'], ['🛶', 'Sampan']] },
      { pairs: [['🚗', 'Kereta'], ['🚌', 'Bas'], ['🚲', 'Basikal'], ['🛵', 'Skuter'], ['🏍️', 'Motosikal']] },
      { pairs: [['✈️', 'Kapal Terbang'], ['🚁', 'Helikopter'], ['🚂', 'Keretapi'], ['🚇', 'LRT'], ['🚊', 'Tram']] },
      { pairs: [['🚢', 'Kapal'], ['⛵', 'Bot Layar'], ['🛥️', 'Bot Laju'], ['🛶', 'Sampan'], ['🚤', 'Bot Kuasa'], ['⛴️', 'Feri']] },
      { pairs: [['🚗', 'Kereta'], ['🚌', 'Bas'], ['🚲', 'Basikal'], ['🛵', 'Skuter'], ['🏍️', 'Motosikal'], ['🚜', 'Traktor']] },
    ]),
  },
  {
    id: 'memory-cuaca',
    title: 'Cari Lambang Cuaca',
    emoji: '☀️',
    mode: 'hidden_object',
    objective: 'Cari lambang cuaca yang dipilih.',
    reward: 'Weather badge',
    rounds: makeRounds([
      { target: '☀️', items: [{text:'☀️',value:'matahari'},{text:'🌧️',value:'hujan'},{text:'⛅',value:'mendung'}] },
      { target: '🌈', items: [{text:'🌈',value:'pelangi'},{text:'☀️',value:'matahari'},{text:'❄️',value:'salji'}] },
      { target: '⛈️', items: [{text:'⛈️',value:'ribut'},{text:'🌧️',value:'hujan'},{text:'☀️',value:'matahari'},{text:'🌤️',value:'cerah'}] },
      { target: '❄️', items: [{text:'❄️',value:'salji'},{text:'☀️',value:'matahari'},{text:'🌧️',value:'hujan'},{text:'🌈',value:'pelangi'}] },
      { target: '🌪️', items: [{text:'🌪️',value:'puting beliung'},{text:'⛈️',value:'ribut'},{text:'🌧️',value:'hujan'},{text:'☁️',value:'awan'},{text:'☀️',value:'matahari'}] },
      { target: '🌧️', items: [{text:'🌧️',value:'hujan'},{text:'⛈️',value:'ribut'},{text:'☔',value:'payung'},{text:'🌤️',value:'cerah'},{text:'⛅',value:'mendung'}] },
      { target: '🌙', items: [{text:'🌙',value:'bulan'},{text:'⭐',value:'bintang'},{text:'☀️',value:'matahari'},{text:'🌈',value:'pelangi'},{text:'☁️',value:'awan'},{text:'❄️',value:'salji'}] },
      { target: '⚡', items: [{text:'⚡',value:'kilat'},{text:'⛈️',value:'ribut'},{text:'🌧️',value:'hujan'},{text:'🌪️',value:'puting beliung'},{text:'☁️',value:'awan'},{text:'🌫️',value:'kabus'},{text:'☀️',value:'matahari'}] },
      { target: '🌈', items: [{text:'🌈',value:'pelangi'},{text:'☀️',value:'matahari'},{text:'🌧️',value:'hujan'},{text:'⛈️',value:'ribut'},{text:'❄️',value:'salji'},{text:'🌪️',value:'puting beliung'},{text:'☁️',value:'awan'}] },
      { target: '☀️', items: [{text:'☀️',value:'matahari'},{text:'🌧️',value:'hujan'},{text:'❄️',value:'salji'},{text:'🌈',value:'pelangi'},{text:'⛈️',value:'ribut'},{text:'🌪️',value:'puting beliung'},{text:'☁️',value:'awan'},{text:'⚡',value:'kilat'}] },
    ]),
  },
  {
    id: 'memory-corak-warna',
    title: 'Ingat Corak Warna',
    emoji: '🎨',
    mode: 'sequence',
    objective: 'Ingat dan ulang urutan warna.',
    reward: 'Color memory',
    rounds: makeRounds([
      { items: ['🔴','🟡','🔵'], answer: ['🔴','🟡','🔵'] },
      { items: ['🟢','🟣','🟠'], answer: ['🟢','🟣','🟠'] },
      { items: ['🔴','🟡','🔵','🟢'], answer: ['🔴','🟡','🔵','🟢'] },
      { items: ['🟣','🟠','⚫','⚪'], answer: ['🟣','🟠','⚫','⚪'] },
      { items: ['🔴','🟡','🔵','🟢','🟣'], answer: ['🔴','🟡','🔵','🟢','🟣'] },
      { items: ['🟠','⚫','⚪','🔴','🟡'], answer: ['🟠','⚫','⚪','🔴','🟡'] },
      { items: ['🔴','🟡','🔵','🟢','🟣','🟠'], answer: ['🔴','🟡','🔵','🟢','🟣','🟠'] },
      { items: ['⚫','⚪','🔴','🟡','🔵','🟢'], answer: ['⚫','⚪','🔴','🟡','🔵','🟢'] },
      { items: ['🔴','🟡','🔵','🟢','🟣','🟠','⚫'], answer: ['🔴','🟡','🔵','🟢','🟣','🟠','⚫'] },
      { items: ['🔴','🟡','🔵','🟢','🟣','🟠','⚫','⚪'], answer: ['🔴','🟡','🔵','🟢','🟣','🟠','⚫','⚪'] },
    ]),
  },
  {
    id: 'memory-sukan',
    title: 'Padan Alat Sukan',
    emoji: '⚽',
    mode: 'tilematch',
    objective: 'Padankan sukan dengan namanya.',
    reward: 'Sport burst',
    rounds: makeRounds([
      { tiles: ['Bola Sepak', '⚽', 'Bola Keranjang', '🏀'] },
      { tiles: ['Tenis', '🎾', 'Badminton', '🏸'] },
      { tiles: ['Bola Sepak', '⚽', 'Bola Tampar', '🏐', 'Boling', '🎳'] },
      { tiles: ['Tenis', '🎾', 'Badminton', '🏸', 'Bola Keranjang', '🏀'] },
      { tiles: ['Berenang', '🏊', 'Lari', '🏃', 'Berbasikal', '🚴', 'Gimnastik', '🤸'] },
      { tiles: ['Bola Sepak', '⚽', 'Bola Tampar', '🏐', 'Boling', '🎳', 'Hoki', '🏑'] },
      { tiles: ['Tenis', '🎾', 'Badminton', '🏸', 'Bola Keranjang', '🏀', 'Bola Sepak', '⚽'] },
      { tiles: ['Berenang','🏊','Lari','🏃','Berbasikal','🚴','Gimnastik','🤸','Tinju','🥊'] },
      { tiles: ['Bola Sepak','⚽','Bola Tampar','🏐','Boling','🎳','Hoki','🏑','Golf','⛳'] },
      { tiles: ['Bola Sepak','⚽','Tenis','🎾','Badminton','🏸','Berenang','🏊','Lari','🏃','Boling','🎳'] },
    ]),
  },
  {
    id: 'memory-alat-sekolah',
    title: 'Padan Alat Sekolah',
    emoji: '✏️',
    mode: 'memory',
    objective: 'Padankan alat sekolah dengan namanya.',
    reward: 'Smart match',
    rounds: makeRounds([
      { pairs: [['✏️','Pensel'],['📚','Buku'],['🎒','Beg']] },
      { pairs: [['📏','Pembaris'],['✂️','Gunting'],['🖍️','Krayon']] },
      { pairs: [['✏️','Pensel'],['📚','Buku'],['🎒','Beg'],['📏','Pembaris']] },
      { pairs: [['✂️','Gunting'],['🖍️','Krayon'],['🖊️','Pen'],['📐','Set Sukat']] },
      { pairs: [['✏️','Pensel'],['📚','Buku'],['🎒','Beg'],['📏','Pembaris'],['✂️','Gunting']] },
      { pairs: [['🖍️','Krayon'],['🖊️','Pen'],['📐','Set Sukat'],['📓','Buku Nota'],['🧮','Sempoa']] },
      { pairs: [['✏️','Pensel'],['📚','Buku'],['🎒','Beg'],['📏','Pembaris'],['✂️','Gunting'],['🖍️','Krayon']] },
      { pairs: [['🖊️','Pen'],['📐','Set Sukat'],['📓','Buku Nota'],['🧮','Sempoa'],['📎','Klip Kertas'],['📌','Pin']] },
      { pairs: [['✏️','Pensel'],['📚','Buku'],['🎒','Beg'],['📏','Pembaris'],['✂️','Gunting'],['🖍️','Krayon'],['🖊️','Pen']] },
      { pairs: [['✏️','Pensel'],['📚','Buku'],['🎒','Beg'],['📏','Pembaris'],['✂️','Gunting'],['🖍️','Krayon'],['🖊️','Pen'],['📐','Set Sukat']] },
    ]),
  },
  {
    id: 'memory-pekerjaan',
    title: 'Ingat Pekerjaan',
    emoji: '👨‍⚕️',
    mode: 'sequence',
    objective: 'Ingat urutan pekerjaan yang ditunjuk.',
    reward: 'Career streak',
    rounds: makeRounds([
      { items: ['👨‍⚕️','👨‍🏫','👨‍🚒'], answer: ['👨‍⚕️','👨‍🏫','👨‍🚒'] },
      { items: ['👮','👨‍🍳','👨‍🌾'], answer: ['👮','👨‍🍳','👨‍🌾'] },
      { items: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮'], answer: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮'] },
      { items: ['👨‍🍳','👨‍🌾','👨‍🔧','👨‍🔬'], answer: ['👨‍🍳','👨‍🌾','👨‍🔧','👨‍🔬'] },
      { items: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳'], answer: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳'] },
      { items: ['👨‍🌾','👨‍🔧','👨‍🔬','👨‍💻','👨‍🎨'], answer: ['👨‍🌾','👨‍🔧','👨‍🔬','👨‍💻','👨‍🎨'] },
      { items: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳','👨‍🌾'], answer: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳','👨‍🌾'] },
      { items: ['👨‍🔧','👨‍🔬','👨‍💻','👨‍🎨','👨‍✈️','👨‍🚀'], answer: ['👨‍🔧','👨‍🔬','👨‍💻','👨‍🎨','👨‍✈️','👨‍🚀'] },
      { items: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳','👨‍🌾','👨‍🔧'], answer: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳','👨‍🌾','👨‍🔧'] },
      { items: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳','👨‍🌾','👨‍🔧','👨‍🔬'], answer: ['👨‍⚕️','👨‍🏫','👨‍🚒','👮','👨‍🍳','👨‍🌾','👨‍🔧','👨‍🔬'] },
    ]),
  },
  {
    id: 'memory-alam-semula-jadi',
    title: 'Cari Alam Semula Jadi',
    emoji: '🌳',
    mode: 'hidden_object',
    objective: 'Cari elemen alam yang dipilih.',
    reward: 'Nature badge',
    rounds: makeRounds([
      { target: '🌳', items: [{text:'🌳',value:'pokok'},{text:'🌸',value:'bunga'},{text:'🍄',value:'cendawan'}] },
      { target: '🌊', items: [{text:'🌊',value:'ombak'},{text:'🏔️',value:'gunung'},{text:'🏞️',value:'taman'}] },
      { target: '🌋', items: [{text:'🌋',value:'gunung berapi'},{text:'🏔️',value:'gunung'},{text:'🏞️',value:'taman'},{text:'🌳',value:'pokok'}] },
      { target: '🍄', items: [{text:'🍄',value:'cendawan'},{text:'🌸',value:'bunga'},{text:'🌻',value:'bunga matahari'},{text:'🌹',value:'bunga ros'}] },
      { target: '🏔️', items: [{text:'🏔️',value:'gunung'},{text:'🌋',value:'gunung berapi'},{text:'🏞️',value:'taman'},{text:'🌊',value:'ombak'},{text:'🌳',value:'pokok'}] },
      { target: '🌸', items: [{text:'🌸',value:'bunga'},{text:'🌻',value:'matahari'},{text:'🌹',value:'ros'},{text:'🌷',value:'tulip'},{text:'🌺',value:'hibiscus'}] },
      { target: '🌳', items: [{text:'🌳',value:'pokok'},{text:'🌲',value:'pokok pain'},{text:'🌴',value:'pokok kelapa'},{text:'🌵',value:'kaktus'},{text:'🍄',value:'cendawan'},{text:'🌿',value:'daun'}] },
      { target: '⛰️', items: [{text:'⛰️',value:'bukit'},{text:'🏔️',value:'gunung'},{text:'🌋',value:'gunung berapi'},{text:'🏞️',value:'taman'},{text:'🌊',value:'ombak'},{text:'🌳',value:'pokok'},{text:'🍄',value:'cendawan'}] },
      { target: '🌊', items: [{text:'🌊',value:'ombak'},{text:'🏔️',value:'gunung'},{text:'🌋',value:'gunung berapi'},{text:'🏞️',value:'taman'},{text:'⛰️',value:'bukit'},{text:'🌳',value:'pokok'},{text:'🌸',value:'bunga'}] },
      { target: '🌳', items: [{text:'🌳',value:'pokok'},{text:'🌲',value:'pain'},{text:'🌴',value:'kelapa'},{text:'🌵',value:'kaktus'},{text:'🌿',value:'daun'},{text:'🍄',value:'cendawan'},{text:'🌸',value:'bunga'},{text:'🌻',value:'matahari'}] },
    ]),
  },
  {
    id: 'memory-emosi',
    title: 'Padan Emosi dengan Situasi',
    emoji: '😊',
    mode: 'dragdrop',
    objective: 'Padankan emosi dengan situasi.',
    reward: 'Empathy badge',
    rounds: makeRounds([
      { items: ['😊','😢','😠'], targets: ['Gembira','Sedih','Marah'] },
      { items: ['😴','😋','😨'], targets: ['Mengantuk','Sedap','Takut'] },
      { items: ['😊','😢','😠','😴'], targets: ['Gembira','Sedih','Marah','Mengantuk'] },
      { items: ['😋','😨','😍','🤔'], targets: ['Sedap','Takut','Suka','Fikir'] },
      { items: ['😊','😢','😠','😴','😋'], targets: ['Gembira','Sedih','Marah','Mengantuk','Sedap'] },
      { items: ['😨','😍','🤔','😎','🤗'], targets: ['Takut','Suka','Fikir','Cool','Peluk'] },
      { items: ['😊','😢','😠','😴','😋','😨'], targets: ['Gembira','Sedih','Marah','Mengantuk','Sedap','Takut'] },
      { items: ['😍','🤔','😎','🤗','😭','😡'], targets: ['Suka','Fikir','Cool','Peluk','Menangis','Geram'] },
      { items: ['😊','😢','😠','😴','😋','😨','😍'], targets: ['Gembira','Sedih','Marah','Mengantuk','Sedap','Takut','Suka'] },
      { items: ['😊','😢','😠','😴','😋','😨','😍','🤔'], targets: ['Gembira','Sedih','Marah','Mengantuk','Sedap','Takut','Suka','Fikir'] },
    ]),
  },
  {
    id: 'memory-irama-muzik',
    title: 'Ikut Irama Muzik',
    emoji: '🎵',
    mode: 'rhythm_tap',
    objective: 'Ulang corak irama muzik.',
    reward: 'Rhythm star',
    rounds: makeRounds([
      { items: ['🥁 Dum','🥁 Dum'] },
      { items: ['🥁 Dum','🎵 Tut','🥁 Dum'] },
      { items: ['🎵 Tut','🥁 Dum','🎵 Tut'] },
      { items: ['🥁','🎵','🥁','🎵'] },
      { items: ['🥁','🥁','🎵','🥁','🎵'] },
      { items: ['🎵','🥁','🎵','🎵','🥁'] },
      { items: ['🥁','🎵','🥁','🎵','🥁','🎵'] },
      { items: ['🥁','🥁','🎵','🥁','🎵','🎵','🥁'] },
      { items: ['🥁','🎵','🥁','🎵','🥁','🎵','🥁','🎵'] },
      { items: ['🥁','🥁','🎵','🥁','🎵','🎵','🥁','🎵','🥁','🥁'] },
    ]),
  },
  {
    id: 'memory-padan-bayang',
    title: 'Padan Bayang Sama',
    emoji: '🪞',
    mode: 'tilematch',
    objective: 'Cari pasangan emoji yang serupa.',
    reward: 'Twin match',
    rounds: makeRounds([
      { tiles: ['🚗','🚗','✈️','✈️'] },
      { tiles: ['☀️','☀️','🌙','🌙','⭐','⭐'] },
      { tiles: ['🌳','🌳','🌸','🌸','🍄','🍄'] },
      { tiles: ['⚽','⚽','🏀','🏀','🎾','🎾','🏸','🏸'] },
      { tiles: ['🚗','🚗','🚌','🚌','✈️','✈️','🚂','🚂'] },
      { tiles: ['😊','😊','😢','😢','😠','😠','😴','😴'] },
      { tiles: ['🍎','🍎','🍌','🍌','🍇','🍇','🍓','🍓','🥝','🥝'] },
      { tiles: ['🐶','🐶','🐱','🐱','🐭','🐭','🐹','🐹','🐰','🐰'] },
      { tiles: ['🌧️','🌧️','☀️','☀️','❄️','❄️','🌈','🌈','⚡','⚡','🌪️','🌪️'] },
      { tiles: ['✏️','✏️','📚','📚','🎒','🎒','📏','📏','✂️','✂️','🖍️','🖍️'] },
    ]),
  },
];