// 🧠 MEMORY MASTER — 10 games × 10 rounds. Tema Malaysia. Setiap game guna mekanik berbeza.
import { makeRounds } from './_helpers.js';

export const memoryMasterGames = [
  {
    id: 'memory-haiwan-malaysia',
    title: 'Padan Haiwan Malaysia',
    emoji: '🐯',
    mode: 'memory',
    objective: 'Padankan haiwan tempatan dengan namanya.',
    reward: 'Memory streak',
    rounds: makeRounds([
      { pairs: [['🐯', 'Harimau'], ['🐘', 'Gajah'], ['🐒', 'Monyet']] },
      { pairs: [['🐢', 'Penyu'], ['🦋', 'Rama-rama'], ['🐦', 'Burung']] },
      { pairs: [['🦅', 'Helang'], ['🐍', 'Ular'], ['🦎', 'Cicak']] },
      { pairs: [['🐯', 'Harimau'], ['🦏', 'Badak'], ['🐊', 'Buaya'], ['🦌', 'Rusa']] },
      { pairs: [['🐘', 'Gajah'], ['🐅', 'Harimau Belang'], ['🦧', 'Mawas'], ['🐢', 'Tuntung']] },
      { pairs: [['🦋', 'Kupu-kupu'], ['🐝', 'Lebah'], ['🐞', 'Kumbang'], ['🐌', 'Siput']] },
      { pairs: [['🐯', 'Harimau'], ['🦁', 'Singa'], ['🦓', 'Kuda Belang'], ['🐆', 'Harimau Bintang'], ['🦒', 'Zirafah']] },
      { pairs: [['🦅', 'Helang'], ['🦉', 'Burung Hantu'], ['🦜', 'Bayan'], ['🐧', 'Penguin'], ['🦩', 'Flamingo']] },
      { pairs: [['🐠', 'Ikan'], ['🐬', 'Lumba-lumba'], ['🦈', 'Yu'], ['🐙', 'Sotong Kurita'], ['🦑', 'Sotong'], ['🦐', 'Udang']] },
      { pairs: [['🐯', 'Harimau'], ['🐘', 'Gajah'], ['🦏', 'Badak Sumbu'], ['🦌', 'Rusa Sambar'], ['🦧', 'Mawas'], ['🐊', 'Buaya Tembaga']] },
    ]),
  },
  {
    id: 'memory-buah-tempatan',
    title: 'Cari Buah Tempatan',
    emoji: '🥭',
    mode: 'hidden_object',
    objective: 'Cari buah sasaran dalam timbunan.',
    reward: 'Focus badge',
    rounds: makeRounds([
      { target: '🥭', items: [{text:'🥭',value:'mangga'},{text:'🍌',value:'pisang'},{text:'🍉',value:'tembikai'}] },
      { target: '🍍', items: [{text:'🍍',value:'nanas'},{text:'🥭',value:'mangga'},{text:'🥥',value:'kelapa'}] },
      { target: '🥥', items: [{text:'🥥',value:'kelapa'},{text:'🍌',value:'pisang'},{text:'🍍',value:'nanas'},{text:'🍇',value:'anggur'}] },
      { target: '🍌', items: [{text:'🍌',value:'pisang'},{text:'🥭',value:'mangga'},{text:'🍉',value:'tembikai'},{text:'🍓',value:'strawberi'}] },
      { target: '🍉', items: [{text:'🍉',value:'tembikai'},{text:'🍊',value:'oren'},{text:'🥝',value:'kiwi'},{text:'🍑',value:'pic'},{text:'🍒',value:'ceri'}] },
      { target: '🍊', items: [{text:'🍊',value:'oren'},{text:'🍋',value:'limau'},{text:'🍎',value:'epal'},{text:'🍏',value:'epal hijau'},{text:'🍐',value:'pear'}] },
      { target: '🥭', items: [{text:'🥭',value:'mangga'},{text:'🍌',value:'pisang'},{text:'🥥',value:'kelapa'},{text:'🍍',value:'nanas'},{text:'🍉',value:'tembikai'},{text:'🍇',value:'anggur'}] },
      { target: '🍍', items: [{text:'🍍',value:'nanas'},{text:'🥭',value:'mangga'},{text:'🥥',value:'kelapa'},{text:'🍌',value:'pisang'},{text:'🍉',value:'tembikai'},{text:'🍓',value:'strawberi'},{text:'🥝',value:'kiwi'}] },
      { target: '🥥', items: [{text:'🥥',value:'kelapa'},{text:'🍍',value:'nanas'},{text:'🍌',value:'pisang'},{text:'🥭',value:'mangga'},{text:'🍉',value:'tembikai'},{text:'🍇',value:'anggur'},{text:'🍒',value:'ceri'}] },
      { target: '🍌', items: [{text:'🍌',value:'pisang'},{text:'🥥',value:'kelapa'},{text:'🥭',value:'mangga'},{text:'🍍',value:'nanas'},{text:'🍉',value:'tembikai'},{text:'🍓',value:'strawberi'},{text:'🍑',value:'pic'},{text:'🍒',value:'ceri'}] },
    ]),
  },
  {
    id: 'memory-bendera-jiran',
    title: 'Ingat Susunan Bendera',
    emoji: '🇲🇾',
    mode: 'sequence',
    objective: 'Ingat dan ulang susunan bendera ASEAN.',
    reward: 'Genius combo',
    rounds: makeRounds([
      { items: ['🇲🇾','🇸🇬','🇮🇩'], answer: ['🇲🇾','🇸🇬','🇮🇩'] },
      { items: ['🇲🇾','🇹🇭','🇻🇳'], answer: ['🇲🇾','🇹🇭','🇻🇳'] },
      { items: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳'], answer: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳'] },
      { items: ['🇹🇭','🇻🇳','🇵🇭','🇰🇭'], answer: ['🇹🇭','🇻🇳','🇵🇭','🇰🇭'] },
      { items: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭'], answer: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭'] },
      { items: ['🇻🇳','🇰🇭','🇱🇦','🇲🇲','🇵🇭'], answer: ['🇻🇳','🇰🇭','🇱🇦','🇲🇲','🇵🇭'] },
      { items: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭','🇻🇳'], answer: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭','🇻🇳'] },
      { items: ['🇰🇭','🇱🇦','🇲🇲','🇵🇭','🇹🇭','🇻🇳'], answer: ['🇰🇭','🇱🇦','🇲🇲','🇵🇭','🇹🇭','🇻🇳'] },
      { items: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭','🇻🇳','🇵🇭'], answer: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭','🇻🇳','🇵🇭'] },
      { items: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭','🇻🇳','🇵🇭','🇰🇭'], answer: ['🇲🇾','🇸🇬','🇮🇩','🇧🇳','🇹🇭','🇻🇳','🇵🇭','🇰🇭'] },
    ]),
  },
  {
    id: 'memory-kad-makanan',
    title: 'Padan Kad Makanan Malaysia',
    emoji: '🍛',
    mode: 'tilematch',
    objective: 'Padankan jubin makanan dan keterangan.',
    reward: 'Tile burst',
    rounds: makeRounds([
      { tiles: ['Nasi Lemak', '🍛', 'Roti Canai', '🥞'] },
      { tiles: ['Satay', '🍢', 'Cendol', '🍧'] },
      { tiles: ['Laksa', '🍜', 'Rendang', '🥘', 'Teh Tarik', '🍵'] },
      { tiles: ['Nasi Lemak', '🍛', 'Roti Canai', '🥞', 'Satay', '🍢'] },
      { tiles: ['Laksa', '🍜', 'Cendol', '🍧', 'Rendang', '🥘', 'Teh Tarik', '🍵'] },
      { tiles: ['Nasi Lemak', '🍛', 'Satay', '🍢', 'Laksa', '🍜', 'Cendol', '🍧'] },
      { tiles: ['Roti Canai', '🥞', 'Rendang', '🥘', 'Teh Tarik', '🍵', 'Mee Goreng', '🍝'] },
      { tiles: ['Nasi Lemak','🍛','Satay','🍢','Cendol','🍧','Teh Tarik','🍵','Roti Canai','🥞'] },
      { tiles: ['Laksa','🍜','Rendang','🥘','Mee Goreng','🍝','Char Kuey Teow','🍳','Ais Kacang','🍨'] },
      { tiles: ['Nasi Lemak','🍛','Roti Canai','🥞','Satay','🍢','Laksa','🍜','Cendol','🍧','Rendang','🥘'] },
    ]),
  },
  {
    id: 'memory-bunyi-haiwan',
    title: 'Padan Bunyi Haiwan',
    emoji: '🐓',
    mode: 'memory',
    objective: 'Padankan haiwan dengan bunyinya.',
    reward: 'Sound match',
    rounds: makeRounds([
      { pairs: [['🐓','Kokok'],['🐄','Mooo'],['🐕','Wuf']] },
      { pairs: [['🐈','Meow'],['🐑','Mbek'],['🦆','Kuek']] },
      { pairs: [['🐓','Kokok'],['🐄','Mooo'],['🐈','Meow'],['🐕','Wuf']] },
      { pairs: [['🦆','Kuek'],['🐑','Mbek'],['🐖','Oink'],['🐎','Hiii']] },
      { pairs: [['🐓','Kokok'],['🐄','Mooo'],['🐈','Meow'],['🐕','Wuf'],['🦆','Kuek']] },
      { pairs: [['🐑','Mbek'],['🐖','Oink'],['🐎','Hiii'],['🐐','Embek'],['🦃','Glu-glu']] },
      { pairs: [['🐓','Kokok'],['🐄','Mooo'],['🐈','Meow'],['🐕','Wuf'],['🦆','Kuek'],['🐑','Mbek']] },
      { pairs: [['🐖','Oink'],['🐎','Hiii'],['🐐','Embek'],['🦃','Glu-glu'],['🦅','Skreek'],['🐦','Cicit']] },
      { pairs: [['🐓','Kokok'],['🐄','Mooo'],['🐈','Meow'],['🐕','Wuf'],['🦆','Kuek'],['🐑','Mbek'],['🐖','Oink']] },
      { pairs: [['🐓','Kokok'],['🐄','Mooo'],['🐈','Meow'],['🐕','Wuf'],['🦆','Kuek'],['🐑','Mbek'],['🐖','Oink'],['🐐','Embek']] },
    ]),
  },
  {
    id: 'memory-jersi-pasukan',
    title: 'Ingat Warna Jersi',
    emoji: '👕',
    mode: 'sequence',
    objective: 'Ingat susunan warna jersi pasukan.',
    reward: 'Color streak',
    rounds: makeRounds([
      { items: ['🟡','⚫','🟡'], answer: ['🟡','⚫','🟡'] },
      { items: ['🔴','⚪','🔴'], answer: ['🔴','⚪','🔴'] },
      { items: ['🟡','⚫','🔴','⚪'], answer: ['🟡','⚫','🔴','⚪'] },
      { items: ['🔵','⚪','🔴','🟢'], answer: ['🔵','⚪','🔴','🟢'] },
      { items: ['🟡','⚫','🔴','⚪','🟢'], answer: ['🟡','⚫','🔴','⚪','🟢'] },
      { items: ['🔵','🟡','🔴','🟢','⚫'], answer: ['🔵','🟡','🔴','🟢','⚫'] },
      { items: ['🟡','⚫','🔴','⚪','🟢','🔵'], answer: ['🟡','⚫','🔴','⚪','🟢','🔵'] },
      { items: ['🔴','⚪','🔵','🟢','🟡','⚫'], answer: ['🔴','⚪','🔵','🟢','🟡','⚫'] },
      { items: ['🟡','⚫','🔴','⚪','🟢','🔵','🟣'], answer: ['🟡','⚫','🔴','⚪','🟢','🔵','🟣'] },
      { items: ['🟡','⚫','🔴','⚪','🟢','🔵','🟣','🟠'], answer: ['🟡','⚫','🔴','⚪','🟢','🔵','🟣','🟠'] },
    ]),
  },
  {
    id: 'memory-kraf-tempatan',
    title: 'Cari Kraf Tempatan',
    emoji: '🪁',
    mode: 'hidden_object',
    objective: 'Cari kraf tradisional Malaysia.',
    reward: 'Heritage badge',
    rounds: makeRounds([
      { target: '🪁', items: [{text:'🪁',value:'wau'},{text:'🎏',value:'gasing'},{text:'🧶',value:'songket'}] },
      { target: '🎏', items: [{text:'🎏',value:'gasing'},{text:'🪁',value:'wau'},{text:'🧵',value:'batik'}] },
      { target: '🧶', items: [{text:'🧶',value:'songket'},{text:'🪁',value:'wau'},{text:'🎨',value:'batik'},{text:'🎏',value:'gasing'}] },
      { target: '🎨', items: [{text:'🎨',value:'batik'},{text:'🪁',value:'wau'},{text:'🧶',value:'songket'},{text:'🎏',value:'gasing'}] },
      { target: '🪁', items: [{text:'🪁',value:'wau'},{text:'🎏',value:'gasing'},{text:'🧶',value:'songket'},{text:'🎨',value:'batik'},{text:'🪕',value:'sape'}] },
      { target: '🪕', items: [{text:'🪕',value:'sape'},{text:'🥁',value:'kompang'},{text:'🎺',value:'serunai'},{text:'🪁',value:'wau'},{text:'🎏',value:'gasing'}] },
      { target: '🥁', items: [{text:'🥁',value:'kompang'},{text:'🪕',value:'sape'},{text:'🎺',value:'serunai'},{text:'🪁',value:'wau'},{text:'🎏',value:'gasing'},{text:'🧶',value:'songket'}] },
      { target: '🪁', items: [{text:'🪁',value:'wau'},{text:'🎏',value:'gasing'},{text:'🧶',value:'songket'},{text:'🎨',value:'batik'},{text:'🪕',value:'sape'},{text:'🥁',value:'kompang'},{text:'🎺',value:'serunai'}] },
      { target: '🎨', items: [{text:'🎨',value:'batik'},{text:'🪁',value:'wau'},{text:'🎏',value:'gasing'},{text:'🧶',value:'songket'},{text:'🪕',value:'sape'},{text:'🥁',value:'kompang'},{text:'🎺',value:'serunai'}] },
      { target: '🧶', items: [{text:'🧶',value:'songket'},{text:'🪁',value:'wau'},{text:'🎏',value:'gasing'},{text:'🎨',value:'batik'},{text:'🪕',value:'sape'},{text:'🥁',value:'kompang'},{text:'🎺',value:'serunai'},{text:'🪔',value:'pelita'}] },
    ]),
  },
  {
    id: 'memory-kelompok-warna',
    title: 'Padan Warna dengan Buah',
    emoji: '🍓',
    mode: 'dragdrop',
    objective: 'Letak buah pada warna yang sepadan.',
    reward: 'Combo solve',
    rounds: makeRounds([
      { items: ['🍓','🍌','🍇'], targets: ['Merah','Kuning','Ungu'] },
      { items: ['🍎','🍋','🥝'], targets: ['Merah','Kuning','Hijau'] },
      { items: ['🍓','🍌','🍇','🍊'], targets: ['Merah','Kuning','Ungu','Jingga'] },
      { items: ['🍎','🍋','🥝','🫐'], targets: ['Merah','Kuning','Hijau','Biru'] },
      { items: ['🍓','🍌','🍇','🍊','🥝'], targets: ['Merah','Kuning','Ungu','Jingga','Hijau'] },
      { items: ['🍎','🍋','🍐','🫐','🍑'], targets: ['Merah','Kuning','Hijau','Biru','Pic'] },
      { items: ['🍓','🍌','🍇','🍊','🥝','🍎'], targets: ['Merah Tua','Kuning','Ungu','Jingga','Hijau','Merah'] },
      { items: ['🍌','🥭','🍇','🍓','🍉','🥥'], targets: ['Kuning','Jingga','Ungu','Merah','Hijau','Coklat'] },
      { items: ['🍓','🍌','🍇','🍊','🥝','🍎','🫐'], targets: ['Merah','Kuning','Ungu','Jingga','Hijau','Merah Tua','Biru'] },
      { items: ['🍓','🍌','🍇','🍊','🥝','🍎','🫐','🍑'], targets: ['Merah','Kuning','Ungu','Jingga','Hijau','Merah Tua','Biru','Pic'] },
    ]),
  },
  {
    id: 'memory-tepuk-corak',
    title: 'Ikut Corak Tepuk',
    emoji: '👏',
    mode: 'rhythm_tap',
    objective: 'Ulang corak tepuk yang ditunjukkan.',
    reward: 'Rhythm combo',
    rounds: makeRounds([
      { items: ['👏 Tepuk','👏 Tepuk'] },
      { items: ['👏 Tepuk','🦶 Hentak','👏 Tepuk'] },
      { items: ['👏 Tepuk','👏 Tepuk','🦶 Hentak'] },
      { items: ['👏','👏','🦶','👏'] },
      { items: ['👏','🦶','👏','🦶','👏'] },
      { items: ['👏','👏','🦶','👏','🦶'] },
      { items: ['👏','🦶','👏','🦶','👏','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶','🦶','👏'] },
      { items: ['👏','🦶','👏','🦶','👏','🦶','👏','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶','🦶','👏','👏','🦶','👏'] },
    ]),
  },
  {
    id: 'memory-cermin-emoji',
    title: 'Cermin Emoji',
    emoji: '🪞',
    mode: 'tilematch',
    objective: 'Cari pasangan emoji yang sama.',
    reward: 'Mirror match',
    rounds: makeRounds([
      { tiles: ['🐯','🐯','🐘','🐘'] },
      { tiles: ['🍎','🍎','🍌','🍌','🍇','🍇'] },
      { tiles: ['🌸','🌸','🌻','🌻','🌹','🌹'] },
      { tiles: ['⭐','⭐','🌙','🌙','☀️','☀️','🌈','🌈'] },
      { tiles: ['🚗','🚗','🚌','🚌','🚲','🚲','✈️','✈️'] },
      { tiles: ['🐠','🐠','🐬','🐬','🐙','🐙','🦈','🦈'] },
      { tiles: ['⚽','⚽','🏀','🏀','🏐','🏐','🏈','🏈','🎾','🎾'] },
      { tiles: ['🎨','🎨','🖌️','🖌️','📚','📚','✏️','✏️','📝','📝'] },
      { tiles: ['🐯','🐯','🐘','🐘','🦋','🦋','🐢','🐢','🦅','🦅','🐍','🐍'] },
      { tiles: ['🌸','🌸','🌻','🌻','🌹','🌹','🌷','🌷','🌺','🌺','🪷','🪷'] },
    ]),
  },
];