// 🔷 PATTERN GENIUS — 10 games × 10 rounds. Tema campuran (corak, urutan, padanan).
import { makeRounds } from './_helpers.js';

export const patternGeniusGames = [
  {
    id: 'pattern-bentuk-3d',
    title: 'Padan Bentuk 3D',
    emoji: '🎲',
    mode: 'memory',
    objective: 'Padankan bentuk 3D dengan namanya.',
    reward: '3D match',
    rounds: makeRounds([
      { pairs: [['🎲','Kubus'],['⚽','Sfera']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon'],['📦','Kuboid']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon'],['📦','Kuboid'],['🏠','Prisma']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon'],['📦','Kuboid'],['🏠','Prisma'],['🎂','Silinder Besar']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon'],['📦','Kuboid'],['🏠','Prisma'],['🎂','Silinder Besar'],['🌍','Sfera Besar']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon'],['📦','Kuboid'],['🏠','Prisma'],['🎂','Silinder Besar'],['🌍','Sfera Besar'],['⛺','Piramid']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon'],['📦','Kuboid'],['🏠','Prisma'],['🎂','Silinder Besar'],['🌍','Sfera Besar'],['⛺','Piramid'],['🥚','Bujur']] },
      { pairs: [['🎲','Kubus'],['⚽','Sfera'],['🥫','Silinder'],['🍦','Kon'],['📦','Kuboid'],['🏠','Prisma'],['🎂','Silinder Besar'],['🌍','Sfera Besar'],['⛺','Piramid'],['🥚','Bujur'],['🎯','Cakera']] },
    ]),
  },
  {
    id: 'pattern-nombor-darab',
    title: 'Cari Nombor Pantas',
    emoji: '✖️',
    mode: 'picture_hunt',
    objective: 'Cari nombor sasaran dengan pantas.',
    reward: 'Math flow',
    rounds: makeRounds([
      { target: '4', items: ['2','3','4','5'] },
      { target: '6', items: ['4','5','6','7','8'] },
      { target: '9', items: ['6','7','8','9','10','11'] },
      { target: '12', items: ['8','10','12','14','16','18'] },
      { target: '15', items: ['10','12','14','15','16','18','20'] },
      { target: '20', items: ['12','14','16','18','20','22','24','26'] },
      { target: '25', items: ['15','17','19','21','23','25','27','29','31'] },
      { target: '30', items: ['20','22','24','26','28','30','32','34','36','38'] },
      { target: '36', items: ['24','26','28','30','32','34','36','38','40','42','44'] },
      { target: '49', items: ['35','37','39','41','43','45','47','49','51','53','55','57'] },
    ]),
  },
  {
    id: 'pattern-huruf-abjad',
    title: 'Lengkapkan Abjad',
    emoji: '🔠',
    mode: 'picture_hunt',
    objective: 'Cari huruf sasaran dalam susunan abjad.',
    reward: 'Alpha sequence',
    rounds: makeRounds([
      { target: 'B', items: ['A','B','C','D'] },
      { target: 'F', items: ['D','E','F','G','H'] },
      { target: 'I', items: ['G','H','I','J','K','L'] },
      { target: 'M', items: ['J','K','L','M','N','O','P'] },
      { target: 'P', items: ['M','N','O','P','Q','R','S','T'] },
      { target: 'S', items: ['P','Q','R','S','T','U','V','W','X'] },
      { target: 'V', items: ['S','T','U','V','W','X','Y','Z','A','B'] },
      { target: 'D', items: ['A','B','C','D','E','F','G','H','I','J','K'] },
      { target: 'H', items: ['A','B','C','D','E','F','G','H','I','J','K','L'] },
      { target: 'K', items: ['A','B','C','D','E','F','G','H','I','J','K','L','M'] },
    ]),
  },
  {
    id: 'pattern-tepuk-irama',
    title: 'Ikut Corak Irama',
    emoji: '👏',
    mode: 'rhythm_tap',
    objective: 'Ikut corak tepuk-hentak.',
    reward: 'Beat smart',
    rounds: makeRounds([
      { items: ['👏','👏'] },
      { items: ['👏','🦶'] },
      { items: ['👏','👏','🦶'] },
      { items: ['🦶','👏','🦶','👏'] },
      { items: ['👏','🦶','🦶','👏','👏'] },
      { items: ['🦶','👏','👏','🦶','👏','🦶'] },
      { items: ['👏','🦶','👏','🦶','👏','🦶','👏'] },
      { items: ['🦶','🦶','👏','👏','🦶','👏','🦶','👏'] },
      { items: ['👏','🦶','👏','🦶','🦶','👏','🦶','👏','👏'] },
      { items: ['👏','🦶','🦶','👏','🦶','👏','👏','🦶','👏','🦶'] },
    ]),
  },
  {
    id: 'pattern-sayur',
    title: 'Padan Sayur',
    emoji: '🥕',
    mode: 'memory',
    objective: 'Padankan sayur dengan namanya.',
    reward: 'Veggie flow',
    rounds: makeRounds([
      { pairs: [['🥕','Lobak'],['🥬','Sawi']] },
      { pairs: [['🥕','Lobak'],['🥬','Sawi'],['🥦','Brokoli']] },
      { pairs: [['🌽','Jagung'],['🥒','Timun'],['🍅','Tomato']] },
      { pairs: [['🥕','Lobak'],['🥬','Sawi'],['🥦','Brokoli'],['🌽','Jagung']] },
      { pairs: [['🥕','Lobak'],['🥬','Sawi'],['🥦','Brokoli'],['🌽','Jagung'],['🥒','Timun']] },
      { pairs: [['🌽','Jagung'],['🥒','Timun'],['🍅','Tomato'],['🥬','Sawi'],['🧅','Bawang']] },
      { pairs: [['🥕','Lobak'],['🥬','Sawi'],['🥦','Brokoli'],['🌽','Jagung'],['🍅','Tomato'],['🧅','Bawang']] },
      { pairs: [['🌽','Jagung'],['🥒','Timun'],['🍅','Tomato'],['🥬','Sawi'],['🧅','Bawang'],['🧄','Bawang Putih'],['🫑','Cili Hijau']] },
      { pairs: [['🥕','Lobak'],['🥬','Sawi'],['🥦','Brokoli'],['🌽','Jagung'],['🥒','Timun'],['🍅','Tomato'],['🧅','Bawang'],['🥔','Kentang']] },
      { pairs: [['🥕','Lobak'],['🥬','Sawi'],['🥦','Brokoli'],['🌽','Jagung'],['🥒','Timun'],['🍅','Tomato'],['🧅','Bawang'],['🥔','Kentang'],['🧄','Bawang Putih'],['🫑','Cili Hijau']] },
    ]),
  },
  {
    id: 'pattern-jam-masa',
    title: 'Padan Jam dengan Masa',
    emoji: '🕐',
    mode: 'memory',
    objective: 'Padankan jam dengan masa.',
    reward: 'Time master',
    rounds: makeRounds([
      { pairs: [['🕐','1:00'],['🕑','2:00']] },
      { pairs: [['🕐','1:00'],['🕑','2:00'],['🕒','3:00']] },
      { pairs: [['🕓','4:00'],['🕔','5:00'],['🕕','6:00']] },
      { pairs: [['🕐','1:00'],['🕑','2:00'],['🕒','3:00'],['🕓','4:00']] },
      { pairs: [['🕐','1:00'],['🕑','2:00'],['🕒','3:00'],['🕓','4:00'],['🕔','5:00']] },
      { pairs: [['🕕','6:00'],['🕖','7:00'],['🕗','8:00'],['🕘','9:00'],['🕙','10:00']] },
      { pairs: [['🕐','1:00'],['🕑','2:00'],['🕒','3:00'],['🕓','4:00'],['🕔','5:00'],['🕕','6:00']] },
      { pairs: [['🕖','7:00'],['🕗','8:00'],['🕘','9:00'],['🕙','10:00'],['🕚','11:00'],['🕛','12:00']] },
      { pairs: [['🕐','1:00'],['🕑','2:00'],['🕒','3:00'],['🕓','4:00'],['🕔','5:00'],['🕕','6:00'],['🕖','7:00']] },
      { pairs: [['🕐','1:00'],['🕑','2:00'],['🕒','3:00'],['🕓','4:00'],['🕔','5:00'],['🕕','6:00'],['🕖','7:00'],['🕗','8:00']] },
    ]),
  },
  {
    id: 'pattern-planet',
    title: 'Padan Planet',
    emoji: '🪐',
    mode: 'memory',
    objective: 'Padankan planet dengan namanya.',
    reward: 'Space genius',
    rounds: makeRounds([
      { pairs: [['🌍','Bumi'],['🌙','Bulan']] },
      { pairs: [['🌍','Bumi'],['🌙','Bulan'],['☀️','Matahari']] },
      { pairs: [['🌍','Bumi'],['🌙','Bulan'],['☀️','Matahari'],['⭐','Bintang']] },
      { pairs: [['🌍','Bumi'],['🪐','Saturn'],['☀️','Matahari'],['🌙','Bulan']] },
      { pairs: [['🌍','Bumi'],['🪐','Saturn'],['☀️','Matahari'],['🌙','Bulan'],['⭐','Bintang']] },
      { pairs: [['🌍','Bumi'],['🪐','Saturn'],['☀️','Matahari'],['🌙','Bulan'],['⭐','Bintang'],['☄️','Komet']] },
      { pairs: [['🌍','Bumi'],['🪐','Saturn'],['☀️','Matahari'],['🌙','Bulan'],['⭐','Bintang'],['☄️','Komet'],['🌌','Galaksi']] },
      { pairs: [['🌍','Bumi'],['🪐','Saturn'],['☀️','Matahari'],['🌙','Bulan'],['⭐','Bintang'],['☄️','Komet'],['🌌','Galaksi'],['🛸','UFO']] },
      { pairs: [['🌍','Bumi'],['🪐','Saturn'],['☀️','Matahari'],['🌙','Bulan'],['⭐','Bintang'],['☄️','Komet'],['🌌','Galaksi'],['🛸','UFO'],['🚀','Roket']] },
      { pairs: [['🌍','Bumi'],['🪐','Saturn'],['☀️','Matahari'],['🌙','Bulan'],['⭐','Bintang'],['☄️','Komet'],['🌌','Galaksi'],['🛸','UFO'],['🚀','Roket'],['👨‍🚀','Angkasawan']] },
    ]),
  },
  {
    id: 'pattern-jubin-warna',
    title: 'Padan Jubin Warna',
    emoji: '🟦',
    mode: 'tilematch',
    objective: 'Padankan jubin warna sama.',
    reward: 'Tile combo',
    rounds: makeRounds([
      { tiles: ['🔴','🔴','🔵','🔵'] },
      { tiles: ['🟡','🟡','🟢','🟢','🟠','🟠'] },
      { tiles: ['🔴','🔴','🔵','🔵','🟡','🟡','🟢','🟢'] },
      { tiles: ['🟣','🟣','🟠','🟠','🩷','🩷','🟤','🟤'] },
      { tiles: ['🔴','🔴','🔵','🔵','🟡','🟡','🟢','🟢','🟣','🟣'] },
      { tiles: ['⚫','⚫','⚪','⚪','🔴','🔴','🔵','🔵','🟡','🟡','🟢','🟢'] },
      { tiles: ['🟥','🟥','🟦','🟦','🟨','🟨','🟩','🟩','🟧','🟧','🟪','🟪'] },
      { tiles: ['🌹','🌹','🌻','🌻','🌷','🌷','🌺','🌺','💐','💐','🪷','🪷'] },
      { tiles: ['⭐','⭐','🌙','🌙','☀️','☀️','🌈','🌈','❄️','❄️','☁️','☁️','⚡','⚡'] },
      { tiles: ['🎈','🎈','🎁','🎁','🎀','🎀','🎂','🎂','🎉','🎉','🎊','🎊','🪅','🪅'] },
    ]),
  },
  {
    id: 'pattern-padan-bunyi-alat',
    title: 'Padan Alat Muzik',
    emoji: '🎸',
    mode: 'memory',
    objective: 'Padankan alat muzik dengan namanya.',
    reward: 'Music flow',
    rounds: makeRounds([
      { pairs: [['🎸','Gitar'],['🥁','Dram']] },
      { pairs: [['🎸','Gitar'],['🥁','Dram'],['🎹','Piano']] },
      { pairs: [['🎺','Trompet'],['🎷','Saksofon'],['🎻','Biola']] },
      { pairs: [['🎸','Gitar'],['🥁','Dram'],['🎹','Piano'],['🎺','Trompet']] },
      { pairs: [['🎸','Gitar'],['🥁','Dram'],['🎹','Piano'],['🎺','Trompet'],['🎷','Saksofon']] },
      { pairs: [['🎻','Biola'],['🎤','Mikrofon'],['🪕','Banjo'],['🎼','Skor'],['🎵','Nota']] },
      { pairs: [['🎸','Gitar'],['🥁','Dram'],['🎹','Piano'],['🎺','Trompet'],['🎷','Saksofon'],['🎻','Biola']] },
      { pairs: [['🎤','Mikrofon'],['🪕','Banjo'],['🎼','Skor'],['🪗','Akordion'],['🪘','Gendang'],['🎵','Nota'],['🎶','Lagu']] },
      { pairs: [['🎸','Gitar'],['🥁','Dram'],['🎹','Piano'],['🎺','Trompet'],['🎷','Saksofon'],['🎻','Biola'],['🎤','Mikrofon'],['🪕','Banjo']] },
      { pairs: [['🎸','Gitar'],['🥁','Dram'],['🎹','Piano'],['🎺','Trompet'],['🎷','Saksofon'],['🎻','Biola'],['🎤','Mikrofon'],['🪕','Banjo'],['🪗','Akordion'],['🪘','Gendang']] },
    ]),
  },
  {
    id: 'pattern-kelas-warna',
    title: 'Kelaskan Warna',
    emoji: '🎨',
    mode: 'sorting',
    objective: 'Asingkan warna ikut jenis.',
    reward: 'Color genius',
    rounds: makeRounds([
      { groups: ['Primer','Sekunder'], items: [{text:'🔴',group:'Primer'},{text:'🟢',group:'Sekunder'},{text:'🔵',group:'Primer'}] },
      { groups: ['Primer','Sekunder'], items: [{text:'🔴',group:'Primer'},{text:'🟢',group:'Sekunder'},{text:'🔵',group:'Primer'},{text:'🟠',group:'Sekunder'}] },
      { groups: ['Panas','Sejuk'], items: [{text:'🔴',group:'Panas'},{text:'🔵',group:'Sejuk'},{text:'🟠',group:'Panas'},{text:'🟢',group:'Sejuk'}] },
      { groups: ['Primer','Sekunder','Neutral'], items: [{text:'🔴',group:'Primer'},{text:'🟢',group:'Sekunder'},{text:'⚪',group:'Neutral'},{text:'🔵',group:'Primer'},{text:'🟠',group:'Sekunder'}] },
      { groups: ['Panas','Sejuk','Neutral'], items: [{text:'🔴',group:'Panas'},{text:'🔵',group:'Sejuk'},{text:'⚪',group:'Neutral'},{text:'🟠',group:'Panas'},{text:'🟢',group:'Sejuk'},{text:'⚫',group:'Neutral'}] },
      { groups: ['Pelangi','Bukan Pelangi'], items: [{text:'🔴',group:'Pelangi'},{text:'🟠',group:'Pelangi'},{text:'🟡',group:'Pelangi'},{text:'⚫',group:'Bukan Pelangi'},{text:'⚪',group:'Bukan Pelangi'},{text:'🟤',group:'Bukan Pelangi'}] },
      { groups: ['Primer','Sekunder','Tertier'], items: [{text:'🔴',group:'Primer'},{text:'🟢',group:'Sekunder'},{text:'🟤',group:'Tertier'},{text:'🔵',group:'Primer'},{text:'🟠',group:'Sekunder'},{text:'🩷',group:'Tertier'},{text:'🟡',group:'Primer'}] },
      { groups: ['Panas','Sejuk','Neutral','Pastel'], items: [{text:'🔴',group:'Panas'},{text:'🔵',group:'Sejuk'},{text:'⚪',group:'Neutral'},{text:'🩷',group:'Pastel'},{text:'🟠',group:'Panas'},{text:'🟢',group:'Sejuk'},{text:'⚫',group:'Neutral'},{text:'🩵',group:'Pastel'}] },
      { groups: ['Pelangi','Bukan Pelangi','Pastel'], items: [{text:'🔴',group:'Pelangi'},{text:'🟠',group:'Pelangi'},{text:'🟡',group:'Pelangi'},{text:'⚫',group:'Bukan Pelangi'},{text:'⚪',group:'Bukan Pelangi'},{text:'🩷',group:'Pastel'},{text:'🩵',group:'Pastel'},{text:'🟢',group:'Pelangi'}] },
      { groups: ['Primer','Sekunder','Panas','Sejuk'], items: [{text:'🔴',group:'Primer'},{text:'🟢',group:'Sekunder'},{text:'🟠',group:'Panas'},{text:'🔵',group:'Sejuk'},{text:'🟡',group:'Primer'},{text:'🟣',group:'Sekunder'},{text:'🟤',group:'Panas'},{text:'🩵',group:'Sejuk'}] },
    ]),
  },
];