// 🔷 PATTERN GENIUS — 10 games × 10 rounds. Pengecaman pola.
import { makeRounds } from './_helpers.js';

export const patternGeniusGames = [
  {
    id: 'pattern-bentuk',
    title: 'Padan Bentuk Geometri',
    emoji: '🔵',
    mode: 'memory',
    objective: 'Padankan bentuk dengan namanya.',
    reward: 'Pattern sparkle',
    rounds: makeRounds([
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga']] },
      { pairs: [['🟥','Segi Empat'],['🔵','Bulat'],['🔺','Segi Tiga']] },
      { pairs: [['🟦','Empat Sama'],['🟨','Empat Tepat'],['🔺','Tiga Sama']] },
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga'],['🟥','Segi Empat'],['⭐','Bintang']] },
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga'],['🟥','Segi Empat'],['⭐','Bintang'],['💎','Berlian']] },
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga'],['🟥','Segi Empat'],['⭐','Bintang'],['💎','Berlian'],['❤️','Hati']] },
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga'],['🟥','Segi Empat'],['⭐','Bintang'],['💎','Berlian'],['❤️','Hati'],['🟪','Heksagon']] },
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga'],['🟥','Segi Empat'],['⭐','Bintang'],['💎','Berlian'],['❤️','Hati'],['🟪','Heksagon'],['🟢','Bujur']] },
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga'],['🟥','Segi Empat'],['⭐','Bintang'],['💎','Berlian'],['❤️','Hati'],['🟪','Heksagon'],['🟢','Bujur'],['🔶','Rombus']] },
      { pairs: [['🔵','Bulat'],['🔺','Segi Tiga'],['🟥','Segi Empat'],['⭐','Bintang'],['💎','Berlian'],['❤️','Hati'],['🟪','Heksagon'],['🟢','Bujur'],['🔶','Rombus'],['➕','Salib']] },
    ]),
  },
  {
    id: 'pattern-nombor',
    title: 'Cari Nombor Seterusnya',
    emoji: '🔢',
    mode: 'picture_hunt',
    objective: 'Cari nombor yang ikut urutan.',
    reward: 'Number flow',
    rounds: makeRounds([
      { target: '3', items: ['1','2','3','5'] },
      { target: '5', items: ['3','5','7','9'] },
      { target: '6', items: ['2','4','6','8','10'] },
      { target: '10', items: ['2','4','6','8','10','12'] },
      { target: '15', items: ['5','10','15','20','25'] },
      { target: '12', items: ['3','6','9','12','15','18'] },
      { target: '25', items: ['5','10','15','20','25','30'] },
      { target: '49', items: ['7','14','21','28','35','42','49'] },
      { target: '64', items: ['8','16','24','32','40','48','56','64'] },
      { target: '100', items: ['10','20','30','40','50','60','70','80','90','100'] },
    ]),
  },
  {
    id: 'pattern-huruf',
    title: 'Cari Huruf Selepasnya',
    emoji: '🔤',
    mode: 'picture_hunt',
    objective: 'Cari huruf yang ikut abjad.',
    reward: 'Alpha streak',
    rounds: makeRounds([
      { target: 'C', items: ['A','B','C','D'] },
      { target: 'E', items: ['C','D','E','F','G'] },
      { target: 'G', items: ['A','C','E','G','I'] },
      { target: 'J', items: ['G','H','I','J','K','L'] },
      { target: 'M', items: ['J','K','L','M','N','O','P'] },
      { target: 'O', items: ['I','K','M','O','Q','S'] },
      { target: 'R', items: ['M','N','O','P','Q','R','S','T'] },
      { target: 'U', items: ['P','Q','R','S','T','U','V','W'] },
      { target: 'X', items: ['Q','R','S','T','U','V','W','X','Y'] },
      { target: 'Z', items: ['Q','R','S','T','U','V','W','X','Y','Z'] },
    ]),
  },
  {
    id: 'pattern-ritma',
    title: 'Ritma Tepuk Hentak',
    emoji: '👏',
    mode: 'rhythm_tap',
    objective: 'Ikut pola tepuk dan hentak.',
    reward: 'Rhythm sparkle',
    rounds: makeRounds([
      { items: ['👏','👏'] },
      { items: ['👏','🦶'] },
      { items: ['👏','👏','🦶'] },
      { items: ['👏','🦶','👏','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶'] },
      { items: ['👏','🦶','👏','👏','🦶','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶','👏','🦶'] },
      { items: ['👏','🦶','👏','🦶','👏','🦶','👏','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶','🦶','👏','👏','🦶'] },
      { items: ['👏','🦶','👏','👏','🦶','👏','🦶','🦶','👏','🦶'] },
    ]),
  },
  {
    id: 'pattern-buah',
    title: 'Padan Buah dengan Nama',
    emoji: '🍎',
    mode: 'memory',
    objective: 'Padankan buah tempatan dengan namanya.',
    reward: 'Fruit beat',
    rounds: makeRounds([
      { pairs: [['🍎','Epal'],['🍌','Pisang']] },
      { pairs: [['🍎','Epal'],['🍌','Pisang'],['🍇','Anggur']] },
      { pairs: [['🥭','Mangga'],['🍍','Nanas'],['🥥','Kelapa']] },
      { pairs: [['🍎','Epal'],['🍌','Pisang'],['🍇','Anggur'],['🥭','Mangga']] },
      { pairs: [['🍎','Epal'],['🍌','Pisang'],['🍇','Anggur'],['🥭','Mangga'],['🍍','Nanas']] },
      { pairs: [['🥭','Mangga'],['🍍','Nanas'],['🥥','Kelapa'],['🍌','Pisang'],['🍓','Strawberi']] },
      { pairs: [['🍎','Epal'],['🍌','Pisang'],['🍇','Anggur'],['🍊','Oren'],['🍓','Strawberi'],['🥝','Kiwi']] },
      { pairs: [['🥭','Mangga'],['🍍','Nanas'],['🥥','Kelapa'],['🍌','Pisang'],['🍓','Strawberi'],['🍑','Pic'],['🍒','Ceri']] },
      { pairs: [['🍎','Epal'],['🍌','Pisang'],['🍇','Anggur'],['🍊','Oren'],['🍓','Strawberi'],['🥝','Kiwi'],['🥭','Mangga'],['🍍','Nanas']] },
      { pairs: [['🍎','Epal'],['🍌','Pisang'],['🍇','Anggur'],['🍊','Oren'],['🍓','Strawberi'],['🥝','Kiwi'],['🥭','Mangga'],['🍍','Nanas'],['🥥','Kelapa'],['🍒','Ceri']] },
    ]),
  },
  {
    id: 'pattern-arah',
    title: 'Cari Arah Bertentangan',
    emoji: '⬆️',
    mode: 'memory',
    objective: 'Padankan arah dengan bertentangannya.',
    reward: 'Arrow combo',
    rounds: makeRounds([
      { pairs: [['⬆️','Atas'],['⬇️','Bawah']] },
      { pairs: [['⬅️','Kiri'],['➡️','Kanan'],['⬆️','Atas']] },
      { pairs: [['⬆️','Atas'],['⬇️','Bawah'],['⬅️','Kiri'],['➡️','Kanan']] },
      { pairs: [['↗️','Atas-Kanan'],['↙️','Bawah-Kiri'],['↖️','Atas-Kiri'],['↘️','Bawah-Kanan']] },
      { pairs: [['⬆️','Atas'],['⬇️','Bawah'],['⬅️','Kiri'],['➡️','Kanan'],['↗️','Serong']] },
      { pairs: [['⬆️','Utara'],['⬇️','Selatan'],['⬅️','Barat'],['➡️','Timur'],['↗️','Timur Laut'],['↘️','Tenggara']] },
      { pairs: [['⬆️','Utara'],['⬇️','Selatan'],['⬅️','Barat'],['➡️','Timur'],['↗️','Timur Laut'],['↘️','Tenggara'],['↖️','Barat Laut']] },
      { pairs: [['⬆️','Utara'],['⬇️','Selatan'],['⬅️','Barat'],['➡️','Timur'],['↗️','Timur Laut'],['↘️','Tenggara'],['↖️','Barat Laut'],['↙️','Barat Daya']] },
      { pairs: [['⬆️','Utara'],['⬇️','Selatan'],['⬅️','Barat'],['➡️','Timur'],['↗️','Timur Laut'],['↘️','Tenggara'],['↖️','Barat Laut'],['↙️','Barat Daya'],['🔄','Berpusing']] },
      { pairs: [['⬆️','Atas'],['⬇️','Bawah'],['⬅️','Kiri'],['➡️','Kanan'],['↗️','Atas-Kanan'],['↘️','Bawah-Kanan'],['↖️','Atas-Kiri'],['↙️','Bawah-Kiri'],['🔃','Pusing Belakang'],['🔁','Ulang']] },
    ]),
  },
  {
    id: 'pattern-warna-asean',
    title: 'Padan Bendera ASEAN',
    emoji: '🇲🇾',
    mode: 'memory',
    objective: 'Padankan bendera dengan negara.',
    reward: 'Flag flow',
    rounds: makeRounds([
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia']] },
      { pairs: [['🇲🇾','Malaysia'],['🇹🇭','Thailand'],['🇻🇳','Vietnam']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia'],['🇧🇳','Brunei']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia'],['🇧🇳','Brunei'],['🇹🇭','Thailand']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia'],['🇧🇳','Brunei'],['🇹🇭','Thailand'],['🇻🇳','Vietnam']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia'],['🇧🇳','Brunei'],['🇹🇭','Thailand'],['🇻🇳','Vietnam'],['🇵🇭','Filipina']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia'],['🇧🇳','Brunei'],['🇹🇭','Thailand'],['🇻🇳','Vietnam'],['🇵🇭','Filipina'],['🇰🇭','Kemboja']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia'],['🇧🇳','Brunei'],['🇹🇭','Thailand'],['🇻🇳','Vietnam'],['🇵🇭','Filipina'],['🇰🇭','Kemboja'],['🇱🇦','Laos']] },
      { pairs: [['🇲🇾','Malaysia'],['🇸🇬','Singapura'],['🇮🇩','Indonesia'],['🇧🇳','Brunei'],['🇹🇭','Thailand'],['🇻🇳','Vietnam'],['🇵🇭','Filipina'],['🇰🇭','Kemboja'],['🇱🇦','Laos'],['🇲🇲','Myanmar']] },
    ]),
  },
  {
    id: 'pattern-jubin',
    title: 'Cari Jubin Pasangan',
    emoji: '🟫',
    mode: 'tilematch',
    objective: 'Padankan jubin pola yang sama.',
    reward: 'Tile pair',
    rounds: makeRounds([
      { tiles: ['🟥','🟥','🟦','🟦'] },
      { tiles: ['🟥','🟥','🟦','🟦','🟨','🟨'] },
      { tiles: ['🟥','🟥','🟦','🟦','🟨','🟨','🟩','🟩'] },
      { tiles: ['🟥','🟥','🟦','🟦','🟨','🟨','🟩','🟩','🟧','🟧'] },
      { tiles: ['🟥','🟥','🟦','🟦','🟨','🟨','🟩','🟩','🟧','🟧','🟪','🟪'] },
      { tiles: ['◼️','◼️','◻️','◻️','◾','◾','◽','◽','▪️','▪️','▫️','▫️'] },
      { tiles: ['🔴','🔴','🟠','🟠','🟡','🟡','🟢','🟢','🔵','🔵','🟣','🟣'] },
      { tiles: ['🌸','🌸','🌻','🌻','🌹','🌹','🌷','🌷','🌺','🌺','🪷','🪷'] },
      { tiles: ['⭐','⭐','🌙','🌙','☀️','☀️','🌈','🌈','☁️','☁️','❄️','❄️'] },
      { tiles: ['🐯','🐯','🐘','🐘','🦋','🦋','🐢','🐢','🦅','🦅','🐍','🐍','🐠','🐠'] },
    ]),
  },
  {
    id: 'pattern-emoji-cuaca',
    title: 'Padan Cuaca dengan Aktiviti',
    emoji: '☀️',
    mode: 'memory',
    objective: 'Padankan cuaca dengan aktiviti sesuai.',
    reward: 'Weather flow',
    rounds: makeRounds([
      { pairs: [['☀️','Berenang'],['🌧️','Payung']] },
      { pairs: [['☀️','Berenang'],['🌧️','Payung'],['❄️','Jaket']] },
      { pairs: [['☀️','Berenang'],['🌧️','Payung'],['❄️','Jaket'],['⛅','Berjalan']] },
      { pairs: [['☀️','Berenang'],['🌧️','Payung'],['❄️','Jaket'],['⛅','Berjalan'],['⛈️','Duduk di Rumah']] },
      { pairs: [['☀️','Berenang'],['🌧️','Payung'],['❄️','Jaket'],['⛅','Berjalan'],['⛈️','Duduk di Rumah'],['🌪️','Berlindung']] },
      { pairs: [['☀️','Topi'],['🌧️','Payung'],['❄️','Skarf'],['⛅','Sunglass'],['⛈️','Lampu'],['🌪️','Rumah Kukuh'],['🌈','Bergambar']] },
      { pairs: [['☀️','Pantai'],['🌧️','Payung'],['❄️','Jaket'],['⛅','Berjalan'],['⛈️','Lampu'],['🌪️','Berlindung'],['🌈','Bergambar'],['🌊','Selamat']] },
      { pairs: [['🌅','Sarapan'],['☀️','Berenang'],['⛅','Berjalan'],['🌧️','Payung'],['⛈️','Duduk Rumah'],['🌆','Petang'],['🌃','Tidur'],['🌌','Bintang']] },
      { pairs: [['🌅','Sarapan'],['☀️','Berenang'],['⛅','Berjalan'],['🌧️','Payung'],['⛈️','Duduk Rumah'],['🌪️','Berlindung'],['❄️','Skarf'],['🌈','Bergambar'],['🌆','Petang']] },
      { pairs: [['🌅','Subuh'],['☀️','Tengah Hari'],['⛅','Pagi'],['🌧️','Hujan'],['⛈️','Ribut'],['🌪️','Puting Beliung'],['❄️','Sejuk'],['🌈','Pelangi'],['🌆','Petang'],['🌌','Malam']] },
    ]),
  },
  {
    id: 'pattern-skor-padan',
    title: 'Padan Pola dengan Kategori',
    emoji: '🎨',
    mode: 'sorting',
    objective: 'Asingkan corak ikut jenis.',
    reward: 'Pattern brain',
    rounds: makeRounds([
      { groups: ['Bulat','Bersudut'], items: [{text:'🔵',group:'Bulat'},{text:'🔺',group:'Bersudut'},{text:'⚫',group:'Bulat'}] },
      { groups: ['Bulat','Bersudut','Garis'], items: [{text:'🔵',group:'Bulat'},{text:'🔺',group:'Bersudut'},{text:'➖',group:'Garis'},{text:'⚫',group:'Bulat'}] },
      { groups: ['Bulat','Bersudut','Garis'], items: [{text:'🔵',group:'Bulat'},{text:'🔺',group:'Bersudut'},{text:'➖',group:'Garis'},{text:'⚫',group:'Bulat'},{text:'🟥',group:'Bersudut'}] },
      { groups: ['Lurus','Bengkok'], items: [{text:'➖',group:'Lurus'},{text:'〰️',group:'Bengkok'},{text:'➡️',group:'Lurus'},{text:'🌀',group:'Bengkok'},{text:'⬆️',group:'Lurus'}] },
      { groups: ['Geometri','Organik'], items: [{text:'🔵',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'⬛',group:'Geometri'},{text:'🌊',group:'Organik'}] },
      { groups: ['Simetri','Tak Simetri'], items: [{text:'🦋',group:'Simetri'},{text:'🍃',group:'Tak Simetri'},{text:'⭐',group:'Simetri'},{text:'🌪️',group:'Tak Simetri'},{text:'❄️',group:'Simetri'},{text:'🌊',group:'Tak Simetri'}] },
      { groups: ['Geometri','Organik','Abstrak'], items: [{text:'🔵',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'🌀',group:'Abstrak'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'✨',group:'Abstrak'},{text:'⬛',group:'Geometri'}] },
      { groups: ['Panas','Sejuk','Neutral'], items: [{text:'🔴',group:'Panas'},{text:'🔵',group:'Sejuk'},{text:'⚪',group:'Neutral'},{text:'🟠',group:'Panas'},{text:'🟢',group:'Sejuk'},{text:'⚫',group:'Neutral'},{text:'🟡',group:'Panas'}] },
      { groups: ['Berulang','Rawak','Pelangi'], items: [{text:'🔴🔴',group:'Berulang'},{text:'⭐🌙',group:'Rawak'},{text:'🌈',group:'Pelangi'},{text:'🟥🟥',group:'Berulang'},{text:'🌸🍃',group:'Rawak'}] },
      { groups: ['Geometri','Organik','Abstrak','Tipografi'], items: [{text:'🔵',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'🌀',group:'Abstrak'},{text:'A',group:'Tipografi'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'✨',group:'Abstrak'},{text:'B',group:'Tipografi'}] },
    ]),
  },
];