// 🔷 PATTERN GENIUS — 10 games × 10 rounds. Pengecaman pola.
import { makeRounds } from './_helpers.js';

export const patternGeniusGames = [
  {
    id: 'pattern-bentuk',
    title: 'Sambung Pola Bentuk',
    emoji: '🔵',
    mode: 'sequence',
    objective: 'Lengkapkan pola bentuk geometri.',
    reward: 'Pattern sparkle',
    rounds: makeRounds([
      { items: ['🔵','🔺','🔵','🔺'], answer: ['🔵','🔺','🔵','🔺'] },
      { items: ['🟥','🟦','🟥','🟦'], answer: ['🟥','🟦','🟥','🟦'] },
      { items: ['🔵','🔺','🟥','🔵','🔺'], answer: ['🔵','🔺','🟥','🔵','🔺'] },
      { items: ['🟦','🟨','🟥','🟦','🟨'], answer: ['🟦','🟨','🟥','🟦','🟨'] },
      { items: ['🔵','🔺','🟥','🟨','🔵','🔺'], answer: ['🔵','🔺','🟥','🟨','🔵','🔺'] },
      { items: ['🟣','🟢','🟠','🟣','🟢','🟠'], answer: ['🟣','🟢','🟠','🟣','🟢','🟠'] },
      { items: ['🔵','🔺','🟥','🟨','🟢','🔵','🔺'], answer: ['🔵','🔺','🟥','🟨','🟢','🔵','🔺'] },
      { items: ['🟦','🟨','🟥','🟢','🟠','🟣','🟦','🟨'], answer: ['🟦','🟨','🟥','🟢','🟠','🟣','🟦','🟨'] },
      { items: ['🔵','🔺','🟥','🟨','🟢','🟣','🟠','🟦','🔵'], answer: ['🔵','🔺','🟥','🟨','🟢','🟣','🟠','🟦','🔵'] },
      { items: ['🔵','🔺','🟥','🟨','🟢','🟣','🟠','🟦','⚫','⚪'], answer: ['🔵','🔺','🟥','🟨','🟢','🟣','🟠','🟦','⚫','⚪'] },
    ]),
  },
  {
    id: 'pattern-nombor',
    title: 'Sambung Nombor',
    emoji: '🔢',
    mode: 'connect_dots',
    objective: 'Tekan nombor mengikut turutan.',
    reward: 'Number flow',
    rounds: makeRounds([
      { items: ['1','2','3'] },
      { items: ['1','2','3','4'] },
      { items: ['1','2','3','4','5'] },
      { items: ['1','2','3','4','5','6'] },
      { items: ['1','2','3','4','5','6','7'] },
      { items: ['1','2','3','4','5','6','7','8'] },
      { items: ['1','2','3','4','5','6','7','8','9'] },
      { items: ['1','2','3','4','5','6','7','8','9','10'] },
      { items: ['2','4','6','8','10','12','14','16','18','20'] },
      { items: ['1','3','5','7','9','11','13','15','17','19'] },
    ]),
  },
  {
    id: 'pattern-huruf',
    title: 'Sambung Huruf',
    emoji: '🔤',
    mode: 'connect_dots',
    objective: 'Tekan huruf mengikut abjad.',
    reward: 'Alpha streak',
    rounds: makeRounds([
      { items: ['A','B','C'] },
      { items: ['A','B','C','D'] },
      { items: ['A','B','C','D','E'] },
      { items: ['A','B','C','D','E','F'] },
      { items: ['A','B','C','D','E','F','G'] },
      { items: ['A','B','C','D','E','F','G','H'] },
      { items: ['A','B','C','D','E','F','G','H','I'] },
      { items: ['A','B','C','D','E','F','G','H','I','J'] },
      { items: ['A','C','E','G','I','K','M','O','Q','S'] },
      { items: ['Z','Y','X','W','V','U','T','S','R','Q'] },
    ]),
  },
  {
    id: 'pattern-ritma',
    title: 'Ritma Tepuk Hentak',
    emoji: '👏',
    mode: 'rhythm_tap',
    objective: 'Ikut pola tepuk dan hentak.',
    reward: 'Rhythm sparkle',
    rounds: makeRounds([
      { items: ['👏','👏'] },
      { items: ['👏','🦶'] },
      { items: ['👏','👏','🦶'] },
      { items: ['👏','🦶','👏','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶'] },
      { items: ['👏','🦶','👏','👏','🦶','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶','👏','🦶'] },
      { items: ['👏','🦶','👏','🦶','👏','🦶','👏','🦶'] },
      { items: ['👏','👏','🦶','👏','🦶','🦶','👏','👏','🦶'] },
      { items: ['👏','🦶','👏','👏','🦶','👏','🦶','🦶','👏','🦶'] },
    ]),
  },
  {
    id: 'pattern-buah',
    title: 'Pola Buah-buahan',
    emoji: '🍎',
    mode: 'sequence',
    objective: 'Susun buah ikut pola berulang.',
    reward: 'Fruit beat',
    rounds: makeRounds([
      { items: ['🍎','🍌','🍎','🍌'], answer: ['🍎','🍌','🍎','🍌'] },
      { items: ['🥭','🍍','🥭','🍍'], answer: ['🥭','🍍','🥭','🍍'] },
      { items: ['🍎','🍌','🍇','🍎','🍌'], answer: ['🍎','🍌','🍇','🍎','🍌'] },
      { items: ['🥭','🍍','🥥','🥭','🍍'], answer: ['🥭','🍍','🥥','🥭','🍍'] },
      { items: ['🍎','🍌','🍇','🍊','🍎','🍌'], answer: ['🍎','🍌','🍇','🍊','🍎','🍌'] },
      { items: ['🥭','🍍','🥥','🍌','🍓','🥭'], answer: ['🥭','🍍','🥥','🍌','🍓','🥭'] },
      { items: ['🍎','🍌','🍇','🍊','🍓','🥝','🍎'], answer: ['🍎','🍌','🍇','🍊','🍓','🥝','🍎'] },
      { items: ['🥭','🍍','🥥','🍌','🍓','🍑','🍒','🥭'], answer: ['🥭','🍍','🥥','🍌','🍓','🍑','🍒','🥭'] },
      { items: ['🍎','🍌','🍇','🍊','🍓','🥝','🥭','🍍','🍎'], answer: ['🍎','🍌','🍇','🍊','🍓','🥝','🥭','🍍','🍎'] },
      { items: ['🍎','🍌','🍇','🍊','🍓','🥝','🥭','🍍','🥥','🍒'], answer: ['🍎','🍌','🍇','🍊','🍓','🥝','🥭','🍍','🥥','🍒'] },
    ]),
  },
  {
    id: 'pattern-arah',
    title: 'Pola Arah Anak Panah',
    emoji: '⬆️',
    mode: 'sequence',
    objective: 'Tekan arah mengikut pola.',
    reward: 'Arrow combo',
    rounds: makeRounds([
      { items: ['⬆️','⬇️'], answer: ['⬆️','⬇️'] },
      { items: ['⬅️','➡️'], answer: ['⬅️','➡️'] },
      { items: ['⬆️','⬇️','⬅️'], answer: ['⬆️','⬇️','⬅️'] },
      { items: ['⬆️','➡️','⬇️','⬅️'], answer: ['⬆️','➡️','⬇️','⬅️'] },
      { items: ['⬆️','⬆️','⬇️','⬇️','⬅️'], answer: ['⬆️','⬆️','⬇️','⬇️','⬅️'] },
      { items: ['⬆️','⬆️','⬇️','⬇️','⬅️','➡️'], answer: ['⬆️','⬆️','⬇️','⬇️','⬅️','➡️'] },
      { items: ['↗️','↘️','↙️','↖️','⬆️','⬇️'], answer: ['↗️','↘️','↙️','↖️','⬆️','⬇️'] },
      { items: ['⬆️','⬆️','⬇️','⬇️','⬅️','➡️','⬅️','➡️'], answer: ['⬆️','⬆️','⬇️','⬇️','⬅️','➡️','⬅️','➡️'] },
      { items: ['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️','⬆️'], answer: ['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️','⬆️'] },
      { items: ['⬆️','⬆️','⬇️','⬇️','⬅️','➡️','⬅️','➡️','🅱️','🅰️'], answer: ['⬆️','⬆️','⬇️','⬇️','⬅️','➡️','⬅️','➡️','🅱️','🅰️'] },
    ]),
  },
  {
    id: 'pattern-warna-asean',
    title: 'Pola Warna ASEAN',
    emoji: '🇲🇾',
    mode: 'sequence',
    objective: 'Susun warna bendera dalam pola.',
    reward: 'Flag flow',
    rounds: makeRounds([
      { items: ['🔴','⚪'], answer: ['🔴','⚪'] },
      { items: ['🔵','🔴'], answer: ['🔵','🔴'] },
      { items: ['🔴','⚪','🔵'], answer: ['🔴','⚪','🔵'] },
      { items: ['🔴','⚪','🔵','🟡'], answer: ['🔴','⚪','🔵','🟡'] },
      { items: ['🔴','⚪','🔵','🟡','🟢'], answer: ['🔴','⚪','🔵','🟡','🟢'] },
      { items: ['🔴','⚪','🔵','🟡','🟢','⚫'], answer: ['🔴','⚪','🔵','🟡','🟢','⚫'] },
      { items: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠'], answer: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠'] },
      { items: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠','🟣'], answer: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠','🟣'] },
      { items: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠','🟣','🟤'], answer: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠','🟣','🟤'] },
      { items: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠','🟣','🟤','🩷'], answer: ['🔴','⚪','🔵','🟡','🟢','⚫','🟠','🟣','🟤','🩷'] },
    ]),
  },
  {
    id: 'pattern-jubin',
    title: 'Cari Jubin Pasangan',
    emoji: '🟫',
    mode: 'tilematch',
    objective: 'Padankan jubin pola yang sama.',
    reward: 'Tile pair',
    rounds: makeRounds([
      { tiles: ['◼️','◻️','◼️','◻️'] },
      { tiles: ['🟥','🟦','🟥','🟦'] },
      { tiles: ['🟨','🟩','🟨','🟩','🟧','🟧'] },
      { tiles: ['🟥','🟦','🟨','🟩','🟥','🟦','🟨','🟩'] },
      { tiles: ['◼️','◻️','◼️','◻️','◾','◽','◾','◽'] },
      { tiles: ['🟪','🟫','🟪','🟫','🟥','🟦','🟥','🟦'] },
      { tiles: ['🟥','🟦','🟨','🟩','🟧','🟪','🟥','🟦','🟨','🟩'] },
      { tiles: ['◼️','◻️','◾','◽','▪️','▫️','◼️','◻️','◾','◽'] },
      { tiles: ['🟥','🟦','🟨','🟩','🟧','🟪','🟫','🟥','🟦','🟨','🟩','🟧'] },
      { tiles: ['🔴','🔵','🟡','🟢','🟠','🟣','🟤','🔴','🔵','🟡','🟢','🟠'] },
    ]),
  },
  {
    id: 'pattern-emoji-cuaca',
    title: 'Pola Cuaca',
    emoji: '☀️',
    mode: 'sequence',
    objective: 'Susun cuaca ikut pola.',
    reward: 'Weather flow',
    rounds: makeRounds([
      { items: ['☀️','🌧️'], answer: ['☀️','🌧️'] },
      { items: ['⛅','🌧️'], answer: ['⛅','🌧️'] },
      { items: ['☀️','⛅','🌧️'], answer: ['☀️','⛅','🌧️'] },
      { items: ['☀️','⛅','🌧️','⛈️'], answer: ['☀️','⛅','🌧️','⛈️'] },
      { items: ['☀️','⛅','🌧️','⛈️','❄️'], answer: ['☀️','⛅','🌧️','⛈️','❄️'] },
      { items: ['☀️','⛅','🌧️','⛈️','❄️','🌪️'], answer: ['☀️','⛅','🌧️','⛈️','❄️','🌪️'] },
      { items: ['☀️','⛅','🌧️','⛈️','❄️','🌪️','🌈'], answer: ['☀️','⛅','🌧️','⛈️','❄️','🌪️','🌈'] },
      { items: ['🌅','☀️','⛅','🌧️','⛈️','🌆','🌃','🌌'], answer: ['🌅','☀️','⛅','🌧️','⛈️','🌆','🌃','🌌'] },
      { items: ['🌅','☀️','⛅','🌧️','⛈️','🌪️','❄️','🌈','🌆'], answer: ['🌅','☀️','⛅','🌧️','⛈️','🌪️','❄️','🌈','🌆'] },
      { items: ['🌅','☀️','⛅','🌧️','⛈️','🌪️','❄️','🌈','🌆','🌌'], answer: ['🌅','☀️','⛅','🌧️','⛈️','🌪️','❄️','🌈','🌆','🌌'] },
    ]),
  },
  {
    id: 'pattern-skor-padan',
    title: 'Padan Pola dengan Kategori',
    emoji: '🎨',
    mode: 'sorting',
    objective: 'Asingkan corak ikut jenis.',
    reward: 'Pattern brain',
    rounds: makeRounds([
      { groups: ['Garis','Titik'], items: [{text:'➖',group:'Garis'},{text:'•',group:'Titik'},{text:'➖',group:'Garis'}] },
      { groups: ['Bulat','Bersudut'], items: [{text:'🔵',group:'Bulat'},{text:'🔺',group:'Bersudut'},{text:'⚫',group:'Bulat'}] },
      { groups: ['Bulat','Bersudut','Garis'], items: [{text:'🔵',group:'Bulat'},{text:'🔺',group:'Bersudut'},{text:'➖',group:'Garis'},{text:'⚫',group:'Bulat'}] },
      { groups: ['Bulat','Bersudut','Garis'], items: [{text:'🔵',group:'Bulat'},{text:'🔺',group:'Bersudut'},{text:'➖',group:'Garis'},{text:'⚫',group:'Bulat'},{text:'🟥',group:'Bersudut'}] },
      { groups: ['Lurus','Bengkok'], items: [{text:'➖',group:'Lurus'},{text:'〰️',group:'Bengkok'},{text:'➡️',group:'Lurus'},{text:'🌀',group:'Bengkok'},{text:'⬆️',group:'Lurus'}] },
      { groups: ['Geometri','Organik'], items: [{text:'🔵',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'⬛',group:'Geometri'},{text:'🌊',group:'Organik'}] },
      { groups: ['Simetri','Tak Simetri'], items: [{text:'🦋',group:'Simetri'},{text:'🍃',group:'Tak Simetri'},{text:'⭐',group:'Simetri'},{text:'🌪️',group:'Tak Simetri'},{text:'❄️',group:'Simetri'},{text:'🌊',group:'Tak Simetri'}] },
      { groups: ['Geometri','Organik','Abstrak'], items: [{text:'🔵',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'🌀',group:'Abstrak'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'✨',group:'Abstrak'},{text:'⬛',group:'Geometri'}] },
      { groups: ['Berulang','Rawak','Bertingkat'], items: [{text:'🔵🔵🔵',group:'Berulang'},{text:'⭐🌙☀️',group:'Rawak'},{text:'🔺🔵🟥',group:'Bertingkat'},{text:'🟥🟥🟥',group:'Berulang'},{text:'🌸🍃⭐',group:'Rawak'}] },
      { groups: ['Geometri','Organik','Abstrak','Tipografi'], items: [{text:'🔵',group:'Geometri'},{text:'🌸',group:'Organik'},{text:'🌀',group:'Abstrak'},{text:'A',group:'Tipografi'},{text:'🔺',group:'Geometri'},{text:'🍃',group:'Organik'},{text:'✨',group:'Abstrak'},{text:'B',group:'Tipografi'}] },
    ]),
  },
];