// 💡 PROBLEM SOLVER — 10 games × 10 rounds. Sebab + akibat.
import { makeRounds } from './_helpers.js';

export const problemSolverGames = [
  {
    id: 'problem-betul-salah-sains',
    title: 'Betul atau Salah: Sains',
    emoji: '🔬',
    mode: 'true_false',
    objective: 'Nilai fakta sains.',
    reward: 'Brain point',
    rounds: makeRounds([
      { statements: [{text:'Matahari terbit dari Timur.',answer:true},{text:'Ikan boleh hidup tanpa air.',answer:false}] },
      { statements: [{text:'Air mendidih pada 100°C.',answer:true},{text:'Bulan lebih besar dari Matahari.',answer:false}] },
      { statements: [{text:'Pokok hasilkan oksigen.',answer:true},{text:'Magnet menarik plastik.',answer:false},{text:'Ais ialah air sejuk beku.',answer:true}] },
      { statements: [{text:'Lebah membuat madu.',answer:true},{text:'Manusia ada 3 jantung.',answer:false},{text:'Cahaya bergerak laju.',answer:true},{text:'Burung tak boleh terbang.',answer:false}] },
      { statements: [{text:'Bumi berputar pada paksinya.',answer:true},{text:'Bulan menghasilkan cahaya sendiri.',answer:false},{text:'Tumbuhan perlukan cahaya matahari.',answer:true},{text:'Logam ringan dari air.',answer:false},{text:'Magnet ada dua kutub.',answer:true}] },
      { statements: [{text:'H2O ialah formula air.',answer:true},{text:'Manusia bernafas oksigen.',answer:true},{text:'Karbon dioksida untuk minum.',answer:false},{text:'Petir ada elektrik.',answer:true},{text:'Pelangi ada 7 warna.',answer:true},{text:'Ais lebih berat dari air cair.',answer:false}] },
      { statements: [{text:'Mata adalah deria penglihatan.',answer:true},{text:'Telinga deria perasa.',answer:false},{text:'Lidah deria rasa.',answer:true},{text:'Hidung deria bau.',answer:true},{text:'Kulit deria sentuhan.',answer:true},{text:'Otak organ pencernaan.',answer:false},{text:'Jantung mengepam darah.',answer:true}] },
      { statements: [{text:'Bumi planet ke-3 dari Matahari.',answer:true},{text:'Marikh disebut Planet Merah.',answer:true},{text:'Musytari planet terkecil.',answer:false},{text:'Pluto planet kerdil.',answer:true},{text:'Bumi ada satu bulan.',answer:true},{text:'Saturn ada gelang.',answer:true},{text:'Venus lebih sejuk dari Pluto.',answer:false},{text:'Galaksi kita Bima Sakti.',answer:true}] },
      { statements: [{text:'Manusia ada 206 tulang.',answer:true},{text:'Otot membantu kita bergerak.',answer:true},{text:'Hati membersihkan darah.',answer:true},{text:'Paru-paru bertugas mencerna.',answer:false},{text:'Sistem peredaran darah dipam jantung.',answer:true},{text:'Otak mengawal badan.',answer:true},{text:'Tulang lebih ringan dari logam.',answer:true},{text:'Otot tidak perlu nutrisi.',answer:false},{text:'Air kencing diproses ginjal.',answer:true}] },
      { statements: [{text:'Tanah lebih padat daripada air.',answer:true},{text:'Hutan hujan ada di Malaysia.',answer:true},{text:'Gajah pemakan daging.',answer:false},{text:'Buaya reptilia.',answer:true},{text:'Penyu bertelur di pantai.',answer:true},{text:'Harimau Malaya makan rumput.',answer:false},{text:'Pokok getah hasilkan susu getah.',answer:true},{text:'Padi tumbuh di gurun.',answer:false},{text:'Lebah pollinate bunga.',answer:true},{text:'Rama-rama dulunya ulat.',answer:true}] },
    ]),
  },
  {
    id: 'problem-mini-makmal',
    title: 'Mini Makmal',
    emoji: '🧪',
    mode: 'mini_simulation',
    objective: 'Pilih bahan ikut sifatnya.',
    reward: 'Lab zap',
    rounds: makeRounds([
      { target: 'Terapung', items: [{text:'Kayu',group:'Terapung'},{text:'Batu',group:'Tenggelam'}] },
      { target: 'Terapung', items: [{text:'Daun',group:'Terapung'},{text:'Besi',group:'Tenggelam'},{text:'Kapas',group:'Terapung'}] },
      { target: 'Tenggelam', items: [{text:'Batu',group:'Tenggelam'},{text:'Syiling',group:'Tenggelam'},{text:'Kayu',group:'Terapung'},{text:'Daun',group:'Terapung'}] },
      { target: 'Terapung', items: [{text:'Kayu',group:'Terapung'},{text:'Daun',group:'Terapung'},{text:'Batu',group:'Tenggelam'},{text:'Besi',group:'Tenggelam'},{text:'Kapas',group:'Terapung'}] },
      { target: 'Tenggelam', items: [{text:'Batu',group:'Tenggelam'},{text:'Syiling',group:'Tenggelam'},{text:'Paku',group:'Tenggelam'},{text:'Kayu',group:'Terapung'},{text:'Daun',group:'Terapung'},{text:'Kapas',group:'Terapung'}] },
      { target: 'Magnet', items: [{text:'Besi',group:'Magnet'},{text:'Paku',group:'Magnet'},{text:'Kayu',group:'Tidak'},{text:'Plastik',group:'Tidak'}] },
      { target: 'Larut Dalam Air', items: [{text:'Gula',group:'Larut Dalam Air'},{text:'Garam',group:'Larut Dalam Air'},{text:'Pasir',group:'Tidak Larut'},{text:'Minyak',group:'Tidak Larut'},{text:'Tepung',group:'Tidak Larut'}] },
      { target: 'Cair', items: [{text:'Air',group:'Cair'},{text:'Susu',group:'Cair'},{text:'Madu',group:'Cair'},{text:'Batu',group:'Pepejal'},{text:'Kayu',group:'Pepejal'},{text:'Wap',group:'Gas'}] },
      { target: 'Cair', items: [{text:'Air',group:'Cair'},{text:'Susu',group:'Cair'},{text:'Minyak',group:'Cair'},{text:'Madu',group:'Cair'},{text:'Batu',group:'Pepejal'},{text:'Kayu',group:'Pepejal'},{text:'Wap',group:'Gas'},{text:'Udara',group:'Gas'}] },
      { target: 'Konduktor Elektrik', items: [{text:'Besi',group:'Konduktor Elektrik'},{text:'Tembaga',group:'Konduktor Elektrik'},{text:'Aluminium',group:'Konduktor Elektrik'},{text:'Kayu',group:'Penebat'},{text:'Plastik',group:'Penebat'},{text:'Getah',group:'Penebat'},{text:'Kaca',group:'Penebat'},{text:'Air Suling',group:'Penebat'},{text:'Air Garam',group:'Konduktor Elektrik'},{text:'Emas',group:'Konduktor Elektrik'}] },
    ]),
  },
  {
    id: 'problem-fizik',
    title: 'Fizik untuk Kanak-kanak',
    emoji: '⚙️',
    mode: 'true_false',
    objective: 'Fikir sebab dan akibat.',
    reward: 'Thinker badge',
    rounds: makeRounds([
      { statements: [{text:'Bola lebih mudah bergolek dari kotak.',answer:true},{text:'Objek berat jatuh lebih perlahan.',answer:false}] },
      { statements: [{text:'Magnet menarik besi.',answer:true},{text:'Cermin pantulkan cahaya.',answer:true}] },
      { statements: [{text:'Air mengalir dari tinggi ke rendah.',answer:true},{text:'Wap naik ke atas.',answer:true},{text:'Ais lebih ringan dari air.',answer:true}] },
      { statements: [{text:'Daya geseran perlahankan kereta.',answer:true},{text:'Roda bulat lebih mudah bergerak.',answer:true},{text:'Permukaan licin tahan gerakan.',answer:false},{text:'Brek henti kereta menggunakan geseran.',answer:true}] },
      { statements: [{text:'Cahaya bergerak lurus.',answer:true},{text:'Bunyi bergerak laju dari cahaya.',answer:false},{text:'Gema disebabkan oleh pantulan bunyi.',answer:true},{text:'Kelawar guna bunyi untuk navigasi.',answer:true},{text:'Cermin rata pantulkan imej dengan tepat.',answer:true}] },
      { statements: [{text:'Graviti tarik objek ke bawah.',answer:true},{text:'Di angkasa lepas tiada graviti.',answer:false},{text:'Bulan ada graviti.',answer:true},{text:'Apple jatuh kerana graviti.',answer:true},{text:'Astronot terapung kerana mikrograviti.',answer:true},{text:'Berat sama dengan jisim.',answer:false}] },
      { statements: [{text:'Daya mengubah arah gerakan.',answer:true},{text:'Tolakan dan tarikan adalah daya.',answer:true},{text:'Objek diam tidak ada daya bertindak.',answer:false},{text:'Daya boleh hentikan objek bergerak.',answer:true},{text:'Daya graviti tarik ke atas.',answer:false},{text:'Magnet ada daya tarikan.',answer:true},{text:'Springs ada daya regangan.',answer:true}] },
      { statements: [{text:'Pengumpil ringankan kerja.',answer:true},{text:'Takal angkat objek berat.',answer:true},{text:'Skru bukan mesin ringkas.',answer:false},{text:'Roda dan gandar mesin ringkas.',answer:true},{text:'Satah condong jimat tenaga.',answer:true},{text:'Baji pisahkan objek.',answer:true},{text:'Mesin ringkas hanya untuk dewasa.',answer:false},{text:'Gunting ada dua bilah pengumpil.',answer:true}] },
      { statements: [{text:'Bunyi perlu medium untuk bergerak.',answer:true},{text:'Di ruang vakum tiada bunyi.',answer:true},{text:'Bunyi bergerak lebih laju dalam pepejal.',answer:true},{text:'Frekuensi tinggi bunyi nada tinggi.',answer:true},{text:'Telinga manusia dengar 20Hz-20kHz.',answer:true},{text:'Bunyi bergerak lebih cepat dari cahaya.',answer:false},{text:'Echo adalah pantulan bunyi.',answer:true},{text:'Pemampatan udara hasilkan bunyi.',answer:true},{text:'Bunyi tidak boleh dipantulkan.',answer:false}] },
      { statements: [{text:'Tenaga tidak boleh dimusnahkan.',answer:true},{text:'Tenaga boleh berubah bentuk.',answer:true},{text:'Bateri menyimpan tenaga kimia.',answer:true},{text:'Solar guna tenaga matahari.',answer:true},{text:'Tenaga kinetik = tenaga gerakan.',answer:true},{text:'Tenaga keupayaan = tenaga simpanan.',answer:true},{text:'Air terjun guna tenaga kimia.',answer:false},{text:'Kincir angin guna tenaga angin.',answer:true},{text:'Tenaga elektrik tak boleh disimpan.',answer:false},{text:'Tenaga haba beralih dari panas ke sejuk.',answer:true}] },
    ]),
  },
  {
    id: 'problem-padan-sebab',
    title: 'Padan Sebab dan Akibat',
    emoji: '🔗',
    mode: 'tilematch',
    objective: 'Padankan sebab dengan akibat.',
    reward: 'Logic chain',
    rounds: makeRounds([
      { tiles: ['Hujan','Banjir','Panas','Peluh'] },
      { tiles: ['Hujan','Banjir','Panas','Peluh','Sejuk','Mengigil'] },
      { tiles: ['Tidur Lewat','Mengantuk','Belajar Rajin','Pandai','Lapar','Makan'] },
      { tiles: ['Tidak Mandi','Berbau','Tak Gosok Gigi','Reput Gigi','Tak Makan','Lemah'] },
      { tiles: ['Berlari Laju','Penat','Minum Cukup','Sihat','Tidur Cukup','Segar','Senaman','Kuat'] },
      { tiles: ['Tidak Sapu Sampah','Kotor','Tidak Pakai Helmet','Cedera','Tidak Belajar','Gagal','Tidak Mandi','Bau'] },
      { tiles: ['Hujan Lebat','Banjir','Cuaca Panas','Kemarau','Angin Kuat','Pokok Tumbang','Gempa','Bangunan Roboh'] },
      { tiles: ['Makan Manis','Gemuk','Tidur Lewat','Letih','Tidak Senaman','Lemah','Tidak Sapu Sampah','Kotor','Tak Gosok Gigi','Karies'] },
      { tiles: ['Belajar Tekun','Lulus','Makan Sayur','Sihat','Senaman','Kuat','Tidur Cukup','Segar','Minum Air','Tak Dehidrasi'] },
      { tiles: ['Hujan','Banjir','Panas','Peluh','Sejuk','Mengigil','Letih','Tidur','Lapar','Makan','Haus','Minum'] },
    ]),
  },
  {
    id: 'problem-pilih-bijak',
    title: 'Pilih Tindakan Bijak',
    emoji: '🤔',
    mode: 'story',
    objective: 'Selesaikan masalah harian.',
    reward: 'Smart choice',
    rounds: makeRounds([
      { scenes: [{text:'Hujan tiba-tiba turun. Apa kau buat?',choices:['Buka payung','Lari saja','Tunggu'],answer:0}] },
      { scenes: [{text:'Tangan luka kecil. Apa langkah pertama?',choices:['Basuh dengan air bersih','Sapu tanah','Biarkan'],answer:0}] },
      { scenes: [{text:'Periuk di dapur terbakar. Apa nak buat?',choices:['Tutup dengan tudung','Siram dengan air','Tinggalkan'],answer:0}] },
      { scenes: [{text:'Adik tertelan benda kecil. Apa nak buat?',choices:['Beri air banyak','Hubungi 999','Diamkan'],answer:1}] },
      { scenes: [{text:'Kucing tersesat di rumah. Apa nak buat?',choices:['Beri makan dan tanya jiran','Halau','Tendang'],answer:0}] },
      { scenes: [{text:'Pintu kereta terkunci, kunci dalam. Apa nak buat?',choices:['Pecahkan cermin','Hubungi spare key/locksmith','Tinggalkan'],answer:1}] },
      { scenes: [{text:'Phone bateri 1%. Cara terbaik?',choices:['Charge dan hantar mesej penting dulu','Main game','Hantar TikTok'],answer:0}] },
      { scenes: [{text:'Tergelincir di tangga. Tindakan?',choices:['Tahan pemegang tangga','Lompat','Pejam mata'],answer:0}] },
      { scenes: [{text:'Buku catatan hilang sebelum exam. Apa nak buat?',choices:['Cari sistematik di tempat biasa','Menangis','Tinggalkan'],answer:0}] },
      { scenes: [{text:'Lampu padam tiba-tiba di malam hari. Apa nak buat?',choices:['Cari lampu suluh','Lari ke luar','Menjerit'],answer:0}] },
    ]),
  },
  {
    id: 'problem-matematik-mudah',
    title: 'Matematik Pantas',
    emoji: '➕',
    mode: 'typing_challenge',
    objective: 'Jawab soalan matematik mudah.',
    reward: 'Math snap',
    rounds: makeRounds([
      { target: '4', prompt: '2 + 2 = ?' },
      { target: '5', prompt: '3 + 2 = ?' },
      { target: '10', prompt: '7 + 3 = ?' },
      { target: '12', prompt: '6 + 6 = ?' },
      { target: '15', prompt: '8 + 7 = ?' },
      { target: '20', prompt: '15 + 5 = ?' },
      { target: '25', prompt: '13 + 12 = ?' },
      { target: '50', prompt: '25 + 25 = ?' },
      { target: '100', prompt: '50 + 50 = ?' },
      { target: '144', prompt: '12 × 12 = ?' },
    ]),
  },
  {
    id: 'problem-rangkai-akhir',
    title: 'Cari Penyelesaian',
    emoji: '💡',
    mode: 'dragdrop',
    objective: 'Letak penyelesaian untuk setiap masalah.',
    reward: 'Solution match',
    rounds: makeRounds([
      { items: ['Air','Makanan'], targets: ['Haus','Lapar'] },
      { items: ['Payung','Selimut'], targets: ['Hujan','Sejuk'] },
      { items: ['Air','Makanan','Tidur'], targets: ['Haus','Lapar','Letih'] },
      { items: ['Doktor','Polis','Bomba'], targets: ['Sakit','Kecurian','Kebakaran'] },
      { items: ['Air','Makanan','Tidur','Mandi'], targets: ['Haus','Lapar','Letih','Bau'] },
      { items: ['Doktor','Polis','Bomba','Ambulans'], targets: ['Sakit','Kecurian','Kebakaran','Kemalangan'] },
      { items: ['Belajar','Senaman','Rehat','Air','Makan Sayur'], targets: ['Bodoh','Lemah','Letih','Haus','Sakit'] },
      { items: ['Payung','Selimut','Cermin Mata Hitam','Kipas','Pemanas'], targets: ['Hujan','Sejuk','Cahaya Terik','Panas','Sangat Sejuk'] },
      { items: ['Doktor Gigi','Optometri','Doktor Telinga','Doktor Kulit','Pakar Sukan','Doktor Am'], targets: ['Sakit Gigi','Mata Kabur','Telinga Bermasalah','Gatal Kulit','Cedera Sukan','Demam Biasa'] },
      { items: ['Belajar','Senaman','Tidur Cukup','Air Cukup','Makan Sayur','Tak Tonton Phone Lewat Malam','Mandi','Sayang Keluarga'], targets: ['Tak Lulus','Lemah','Mengantuk','Dehidrasi','Sakit','Mata Penat','Bau','Sedih'] },
    ]),
  },
  {
    id: 'problem-padan-alat',
    title: 'Padan Alat Bantuan',
    emoji: '🛠️',
    mode: 'dragdrop',
    objective: 'Padankan masalah dengan alat penyelesaian.',
    reward: 'Tool wisdom',
    rounds: makeRounds([
      { items: ['Tukul','Pisau'], targets: ['Paku','Sayur'] },
      { items: ['Berus','Gunting'], targets: ['Gigi','Kertas'] },
      { items: ['Tukul','Pisau','Berus','Gunting'], targets: ['Paku','Sayur','Gigi','Kertas'] },
      { items: ['Tukul','Pisau','Berus','Gunting','Pemadam'], targets: ['Paku','Sayur','Gigi','Kertas','Pensel'] },
      { items: ['Pen','Pemadam','Pembaris','Mesin Kira','Kunci'], targets: ['Menulis','Membetulkan Pensel','Ukur Lurus','Kira Nombor','Buka Pintu'] },
      { items: ['Tukul','Pemutar Skru','Spanar','Pisau','Berus Gigi','Sikat'], targets: ['Paku','Skru','Bolts','Sayur','Gigi','Rambut'] },
      { items: ['Stetoskop','Termometer','Picagari','Pembedahan','Plaster','Kapas'], targets: ['Dengar Jantung','Ukur Suhu','Ubat Cucuk','Pembedahan','Tutup Luka','Membersih Luka'] },
      { items: ['Sapu','Mop','Vakum','Span','Tuala','Berus','Sabun','Sabun Pinggan'], targets: ['Sampah','Lantai Basah','Habuk','Pinggan','Lap','Kasut','Cuci Tangan','Pinggan Berminyak'] },
      { items: ['Tukul','Skru','Spanar','Pisau','Berus','Sikat','Pen','Pemadam','Mesin Kira'], targets: ['Paku','Bolts Kecil','Bolts Besar','Sayur','Gigi','Rambut','Tulis','Pensel','Kira'] },
      { items: ['Stetoskop','Termometer','Picagari','Pisau Pembedah','Plaster','Kapas','Penekan Lidah','Cermin Doktor Gigi','Suntikan','Penimbang'], targets: ['Jantung','Suhu','Cucuk','Bedah','Luka','Bersih Luka','Tekak','Gigi','Vaksin','Berat'] },
    ]),
  },
  {
    id: 'problem-sumber-bahan',
    title: 'Dari Mana Datangnya?',
    emoji: '🌾',
    mode: 'sorting',
    objective: 'Asingkan bahan ikut sumbernya.',
    reward: 'Source smart',
    rounds: makeRounds([
      { groups: ['Tumbuhan','Haiwan'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'}] },
      { groups: ['Tumbuhan','Haiwan'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'},{text:'Telur',group:'Haiwan'}] },
      { groups: ['Tumbuhan','Haiwan'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'},{text:'Telur',group:'Haiwan'},{text:'Gula',group:'Tumbuhan'}] },
      { groups: ['Tumbuhan','Haiwan','Galian'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'},{text:'Garam',group:'Galian'},{text:'Telur',group:'Haiwan'}] },
      { groups: ['Tumbuhan','Haiwan','Galian'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'},{text:'Garam',group:'Galian'},{text:'Telur',group:'Haiwan'},{text:'Madu',group:'Haiwan'},{text:'Kelapa',group:'Tumbuhan'}] },
      { groups: ['Tumbuhan','Haiwan','Galian','Buatan'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'},{text:'Garam',group:'Galian'},{text:'Plastik',group:'Buatan'},{text:'Telur',group:'Haiwan'},{text:'Kelapa',group:'Tumbuhan'}] },
      { groups: ['Tumbuhan','Haiwan','Galian','Buatan'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'},{text:'Garam',group:'Galian'},{text:'Plastik',group:'Buatan'},{text:'Telur',group:'Haiwan'},{text:'Kelapa',group:'Tumbuhan'},{text:'Tembaga',group:'Galian'},{text:'Polyester',group:'Buatan'}] },
      { groups: ['Boleh Dimakan','Tidak Boleh'], items: [{text:'Pisang',group:'Boleh Dimakan'},{text:'Plastik',group:'Tidak Boleh'},{text:'Nasi',group:'Boleh Dimakan'},{text:'Batu',group:'Tidak Boleh'},{text:'Roti',group:'Boleh Dimakan'},{text:'Logam',group:'Tidak Boleh'},{text:'Air',group:'Boleh Dimakan'}] },
      { groups: ['Sumber Asli','Sumber Buatan'], items: [{text:'Kayu',group:'Sumber Asli'},{text:'Plastik',group:'Sumber Buatan'},{text:'Air',group:'Sumber Asli'},{text:'Kaca',group:'Sumber Buatan'},{text:'Kapas',group:'Sumber Asli'},{text:'Polyester',group:'Sumber Buatan'},{text:'Emas',group:'Sumber Asli'},{text:'Tembaga',group:'Sumber Asli'},{text:'Tayar Getah',group:'Sumber Buatan'}] },
      { groups: ['Tumbuhan','Haiwan','Galian','Buatan','Lautan'], items: [{text:'Beras',group:'Tumbuhan'},{text:'Susu',group:'Haiwan'},{text:'Garam',group:'Galian'},{text:'Plastik',group:'Buatan'},{text:'Ikan',group:'Lautan'},{text:'Telur',group:'Haiwan'},{text:'Kelapa',group:'Tumbuhan'},{text:'Tembaga',group:'Galian'},{text:'Polyester',group:'Buatan'},{text:'Mutiara',group:'Lautan'}] },
    ]),
  },
  {
    id: 'problem-hitung-cepat',
    title: 'Hitung Wang Pantas',
    emoji: '💰',
    mode: 'typing_challenge',
    objective: 'Hitung jumlah wang dengan cepat.',
    reward: 'Money math',
    rounds: makeRounds([
      { target: '3', prompt: 'RM1 + RM2 = RM?' },
      { target: '10', prompt: 'RM5 + RM5 = RM?' },
      { target: '15', prompt: 'RM10 + RM5 = RM?' },
      { target: '20', prompt: 'RM10 + RM10 = RM?' },
      { target: '50', prompt: 'RM20 + RM30 = RM?' },
      { target: '75', prompt: 'RM50 + RM25 = RM?' },
      { target: '100', prompt: 'RM50 + RM50 = RM?' },
      { target: '150', prompt: 'RM100 + RM50 = RM?' },
      { target: '200', prompt: 'RM150 + RM50 = RM?' },
      { target: '500', prompt: 'RM250 + RM250 = RM?' },
    ]),
  },
];