// 💡 PROBLEM SOLVER — 10 games × 10 rounds. Tema campuran (sebab, akibat, penyelesaian).
import { makeRounds } from './_helpers.js';

export const problemSolverGames = [
  {
    id: 'problem-pilih-makan',
    title: 'Pilih Makanan Bijak',
    emoji: '🥦',
    mode: 'story',
    objective: 'Pilih makanan paling sihat.',
    reward: 'Health smart',
    rounds: makeRounds([
      { scenes: [{text:'Mana lebih sihat untuk sarapan?',choices:['Bubur oat','Kek manis','Donut'],answer:0}] },
      { scenes: [{text:'Untuk dahaga, mana terbaik?',choices:['Air kosong','Air gula','Kopi'],answer:0}] },
      { scenes: [{text:'Mana protein terbaik?',choices:['Ikan kukus','Goreng','Gula-gula'],answer:0}] },
      { scenes: [{text:'Snek paling sihat?',choices:['Buah segar','Cip','Coklat'],answer:0}] },
      { scenes: [{text:'Untuk tumbesaran tulang, mana terbaik?',choices:['Susu','Soda','Teh'],answer:0}] },
      { scenes: [{text:'Mana boleh kurangkan berat?',choices:['Sayur dan senaman','Makan banyak gula','Tidur sahaja'],answer:0}] },
      { scenes: [{text:'Untuk otak cerdas, mana terbaik?',choices:['Ikan dan kacang','Mee segera','Hanya kek'],answer:0}] },
      { scenes: [{text:'Untuk gigi kuat, mana terbaik?',choices:['Susu dan keju','Gula tin','Soda'],answer:0}] },
      { scenes: [{text:'Untuk badan kuat, mana terbaik?',choices:['Daging tanpa lemak + sayur','Makanan goreng','Hanya gula-gula'],answer:0}] },
      { scenes: [{text:'Untuk mata tajam, mana terbaik?',choices:['Lobak merah dan ikan','Hanya cip','Hanya teh'],answer:0}] },
    ]),
  },
  {
    id: 'problem-sains-larut',
    title: 'Bahan Larut Atau Tidak?',
    emoji: '🧪',
    mode: 'mini_simulation',
    objective: 'Pilih bahan ikut sifatnya.',
    reward: 'Lab smart',
    rounds: makeRounds([
      { target: 'Larut', items: [{text:'Gula',group:'Larut'},{text:'Pasir',group:'Tidak Larut'}] },
      { target: 'Larut', items: [{text:'Garam',group:'Larut'},{text:'Pasir',group:'Tidak Larut'},{text:'Gula',group:'Larut'}] },
      { target: 'Tidak Larut', items: [{text:'Pasir',group:'Tidak Larut'},{text:'Minyak',group:'Tidak Larut'},{text:'Gula',group:'Larut'},{text:'Garam',group:'Larut'}] },
      { target: 'Larut', items: [{text:'Gula',group:'Larut'},{text:'Garam',group:'Larut'},{text:'Pasir',group:'Tidak Larut'},{text:'Minyak',group:'Tidak Larut'},{text:'Tepung',group:'Tidak Larut'}] },
      { target: 'Larut', items: [{text:'Gula',group:'Larut'},{text:'Garam',group:'Larut'},{text:'Coklat Serbuk',group:'Larut'},{text:'Pasir',group:'Tidak Larut'},{text:'Minyak',group:'Tidak Larut'},{text:'Tepung',group:'Tidak Larut'}] },
      { target: 'Terapung', items: [{text:'Kayu',group:'Terapung'},{text:'Batu',group:'Tenggelam'},{text:'Daun',group:'Terapung'},{text:'Besi',group:'Tenggelam'}] },
      { target: 'Terapung', items: [{text:'Kayu',group:'Terapung'},{text:'Daun',group:'Terapung'},{text:'Kapas',group:'Terapung'},{text:'Batu',group:'Tenggelam'},{text:'Besi',group:'Tenggelam'},{text:'Syiling',group:'Tenggelam'}] },
      { target: 'Magnet Tarik', items: [{text:'Besi',group:'Magnet Tarik'},{text:'Paku',group:'Magnet Tarik'},{text:'Kayu',group:'Tidak'},{text:'Plastik',group:'Tidak'},{text:'Kertas',group:'Tidak'}] },
      { target: 'Cair', items: [{text:'Air',group:'Cair'},{text:'Susu',group:'Cair'},{text:'Minyak',group:'Cair'},{text:'Madu',group:'Cair'},{text:'Batu',group:'Pepejal'},{text:'Kayu',group:'Pepejal'},{text:'Wap',group:'Gas'}] },
      { target: 'Konduktor', items: [{text:'Besi',group:'Konduktor'},{text:'Tembaga',group:'Konduktor'},{text:'Aluminium',group:'Konduktor'},{text:'Emas',group:'Konduktor'},{text:'Kayu',group:'Penebat'},{text:'Plastik',group:'Penebat'},{text:'Getah',group:'Penebat'},{text:'Kaca',group:'Penebat'},{text:'Kertas',group:'Penebat'},{text:'Air Garam',group:'Konduktor'}] },
    ]),
  },
  {
    id: 'problem-betul-salah-sosial',
    title: 'Adab Betul Atau Salah',
    emoji: '🤝',
    mode: 'true_false',
    objective: 'Nilai adab dan sopan-santun.',
    reward: 'Manner scout',
    rounds: makeRounds([
      { statements: [{text:'Ucap "terima kasih" bila dapat hadiah.',answer:true},{text:'Bersorak waktu kawan menangis.',answer:false}] },
      { statements: [{text:'Salam dengan orang tua.',answer:true},{text:'Tutup pintu kuat-kuat.',answer:false}] },
      { statements: [{text:'Tunggu giliran.',answer:true},{text:'Potong barisan.',answer:false},{text:'Senyum bila bertemu.',answer:true}] },
      { statements: [{text:'Tolong kawan yang susah.',answer:true},{text:'Buli adik kecil.',answer:false},{text:'Hormati guru.',answer:true},{text:'Cakap kasar dengan ibu.',answer:false}] },
      { statements: [{text:'Buang sampah dalam tong.',answer:true},{text:'Buang sampah merata-rata.',answer:false},{text:'Berkongsi mainan.',answer:true},{text:'Mengganggu kelas.',answer:false},{text:'Beri laluan kepada warga emas.',answer:true}] },
      { statements: [{text:'Cuci tangan sebelum makan.',answer:true},{text:'Tak gosok gigi sebelum tidur.',answer:false},{text:'Lap mulut dengan tuala kertas.',answer:true},{text:'Bercakap dengan mulut penuh makanan.',answer:false},{text:'Pakai kasut dalam rumah.',answer:false},{text:'Tukar baju lepas main bola.',answer:true}] },
      { statements: [{text:'Ucap "Assalamualaikum" masuk rumah.',answer:true},{text:'Buka kasut sebelum masuk rumah.',answer:true},{text:'Bercakap kuat-kuat dalam masjid.',answer:false},{text:'Berdoa sebelum makan.',answer:true},{text:'Buang masa main game waktu solat.',answer:false},{text:'Tolong ibu di dapur.',answer:true},{text:'Bunuh haiwan tanpa sebab.',answer:false}] },
      { statements: [{text:'Hormati lampu isyarat.',answer:true},{text:'Lintas di tempat ditetapkan.',answer:true},{text:'Pakai tali pinggang keledar.',answer:true},{text:'Telefon waktu memandu.',answer:false},{text:'Pakai helmet naik motosikal.',answer:true},{text:'Mengaibkan pemandu lain.',answer:false},{text:'Beri laluan kepada ambulan.',answer:true},{text:'Pandu laju dalam taman.',answer:false}] },
      { statements: [{text:'Tahniah waktu kawan menang.',answer:true},{text:'Iri hati dengan kawan.',answer:false},{text:'Jujur bila buat silap.',answer:true},{text:'Salahkan orang lain.',answer:false},{text:'Maaf bila tersalah.',answer:true},{text:'Senyap bila ada masalah.',answer:false},{text:'Hormati pendapat lain.',answer:true},{text:'Berkasar dengan kawan.',answer:false},{text:'Sokong yang tertindas.',answer:true}] },
      { statements: [{text:'Belajar sungguh-sungguh.',answer:true},{text:'Curi jawapan exam.',answer:false},{text:'Buat kerja rumah sendiri.',answer:true},{text:'Tipu cikgu.',answer:false},{text:'Beri perhatian dalam kelas.',answer:true},{text:'Tidur dalam kelas.',answer:false},{text:'Hormati kawan.',answer:true},{text:'Maki guru.',answer:false},{text:'Datang sekolah awal.',answer:true},{text:'Ponteng sekolah.',answer:false}] },
    ]),
  },
  {
    id: 'problem-padan-akibat',
    title: 'Padan Sebab Akibat',
    emoji: '🔗',
    mode: 'tilematch',
    objective: 'Padankan tindakan dengan akibat.',
    reward: 'Logic chain',
    rounds: makeRounds([
      { tiles: ['Belajar','Pandai','Lari','Penat'] },
      { tiles: ['Tidur','Segar','Makan','Kenyang'] },
      { tiles: ['Hujan','Basah','Cuci','Bersih','Tanam','Tumbuh'] },
      { tiles: ['Belajar','Lulus','Senaman','Sihat','Mandi','Wangi'] },
      { tiles: ['Tipu','Tak Dipercayai','Tolong','Disayangi','Jujur','Dihormati','Tabah','Berjaya'] },
      { tiles: ['Berbasikal','Cergas','Tidur Cukup','Segar','Minum Air','Tak Dahaga','Makan Sayur','Sihat'] },
      { tiles: ['Tak Belajar','Gagal','Tak Mandi','Bau','Tak Gosok Gigi','Karies','Tak Tidur','Mengantuk','Tak Senaman','Lemah'] },
      { tiles: ['Tanam Pokok','Hijau','Buang Sampah','Kotor','Kitar Semula','Selamatkan Bumi','Tebang Hutan','Banjir','Cemar Air','Sakit'] },
      { tiles: ['Hormati Guru','Dihargai','Tolong Kawan','Dipercayai','Belajar Tekun','Pandai','Sukan','Cergas','Doa','Tenang','Membaca','Berilmu'] },
      { tiles: ['Hujan Lebat','Banjir','Panas','Peluh','Sejuk','Mengigil','Letih','Tidur','Lapar','Makan','Haus','Minum','Sakit','Doktor'] },
    ]),
  },
  {
    id: 'problem-pilih-tindakan',
    title: 'Pilih Tindakan Selamat',
    emoji: '🦺',
    mode: 'story',
    objective: 'Selesaikan situasi keselamatan.',
    reward: 'Safety smart',
    rounds: makeRounds([
      { scenes: [{text:'Periuk berasap di dapur. Apa pertama?',choices:['Tutup tudung','Tuang air banyak','Tinggalkan'],answer:0}] },
      { scenes: [{text:'Pakaian terbakar. Apa nak buat?',choices:['Berbaring dan bergolek','Lari','Lompat'],answer:0}] },
      { scenes: [{text:'Tersedak makanan. Apa nak buat?',choices:['Batuk kuat-kuat','Minum banyak','Tidur'],answer:0}] },
      { scenes: [{text:'Nampak wayar terbuka. Apa nak buat?',choices:['Beritahu orang dewasa','Sentuh','Pijak'],answer:0}] },
      { scenes: [{text:'Gas terbau. Apa pertama?',choices:['Buka tingkap & beritahu','Cuci tangan','Buka api'],answer:0}] },
      { scenes: [{text:'Tergelincir di lantai basah. Apa nak buat?',choices:['Bangun perlahan periksa','Lari pantas','Tendang lantai'],answer:0}] },
      { scenes: [{text:'Anjing menyalak galak. Apa nak buat?',choices:['Berdiri diam, jangan lari','Lari kuat-kuat','Tendang'],answer:0}] },
      { scenes: [{text:'Terdengar bunyi pecah masuk rumah. Apa nak buat?',choices:['Sembunyi & telefon 999','Lawan sendiri','Bukan pintu'],answer:0}] },
      { scenes: [{text:'Kepala pening dan loya. Apa nak buat?',choices:['Berbaring, panggil dewasa','Lari','Main game'],answer:0}] },
      { scenes: [{text:'Phone basah jatuh dalam air. Apa nak buat?',choices:['Keringkan dengan beras','Charge terus','Pukul'],answer:0}] },
    ]),
  },
  {
    id: 'problem-kira-pantas',
    title: 'Kira Pantas Mental',
    emoji: '🧮',
    mode: 'typing_challenge',
    objective: 'Jawab soalan kira pantas.',
    reward: 'Mental math',
    rounds: makeRounds([
      { target: '5', prompt: '2 + 3 = ?' },
      { target: '10', prompt: '6 + 4 = ?' },
      { target: '8', prompt: '15 - 7 = ?' },
      { target: '20', prompt: '4 × 5 = ?' },
      { target: '6', prompt: '24 ÷ 4 = ?' },
      { target: '36', prompt: '6 × 6 = ?' },
      { target: '50', prompt: '100 ÷ 2 = ?' },
      { target: '75', prompt: '100 - 25 = ?' },
      { target: '99', prompt: '100 - 1 = ?' },
      { target: '121', prompt: '11 × 11 = ?' },
    ]),
  },
  {
    id: 'problem-padan-penyelesaian',
    title: 'Padan Masalah Penyelesaian',
    emoji: '💡',
    mode: 'dragdrop',
    objective: 'Letak penyelesaian untuk setiap masalah.',
    reward: 'Solver star',
    rounds: makeRounds([
      { items: ['Air','Tidur'], targets: ['Dahaga','Letih'] },
      { items: ['Payung','Selimut'], targets: ['Hujan','Sejuk'] },
      { items: ['Doktor','Polis','Bomba'], targets: ['Sakit','Kecurian','Kebakaran'] },
      { items: ['Air','Tidur','Makan','Mandi'], targets: ['Dahaga','Letih','Lapar','Bau'] },
      { items: ['Doktor','Polis','Bomba','Ambulans'], targets: ['Sakit','Kecurian','Kebakaran','Kemalangan'] },
      { items: ['Belajar','Senaman','Rehat','Air','Makan Sayur'], targets: ['Tak Pandai','Lemah','Letih','Haus','Sakit'] },
      { items: ['Payung','Selimut','Kipas','Pemanas','Topi'], targets: ['Hujan','Sejuk','Panas','Sangat Sejuk','Matahari'] },
      { items: ['Doktor','Polis','Bomba','Plumber','Tukang Kunci','Elektrik'], targets: ['Sakit','Kecurian','Kebakaran','Paip Bocor','Pintu Terkunci','Lampu Padam'] },
      { items: ['Pen','Pemadam','Pembaris','Mesin Kira','Kunci','Lampu Suluh'], targets: ['Menulis','Padam','Ukur','Kira','Buka Pintu','Lihat Gelap'] },
      { items: ['Air','Tidur','Makan','Mandi','Belajar','Senaman','Sayur','Mainan'], targets: ['Dahaga','Letih','Lapar','Bau','Tak Pandai','Lemah','Sakit','Bosan'] },
    ]),
  },
  {
    id: 'problem-asingkan-bahan',
    title: 'Asingkan Bahan',
    emoji: '♻️',
    mode: 'sorting',
    objective: 'Asingkan sampah ikut jenis.',
    reward: 'Eco smart',
    rounds: makeRounds([
      { groups: ['Boleh Kitar Semula','Tidak Boleh'], items: [{text:'Botol Plastik',group:'Boleh Kitar Semula'},{text:'Makanan Basi',group:'Tidak Boleh'}] },
      { groups: ['Boleh Kitar Semula','Tidak Boleh'], items: [{text:'Kertas',group:'Boleh Kitar Semula'},{text:'Tisu Pakai',group:'Tidak Boleh'},{text:'Aluminium',group:'Boleh Kitar Semula'}] },
      { groups: ['Plastik','Kertas','Logam'], items: [{text:'Botol',group:'Plastik'},{text:'Buku',group:'Kertas'},{text:'Tin',group:'Logam'}] },
      { groups: ['Plastik','Kertas','Logam','Kaca'], items: [{text:'Botol Plastik',group:'Plastik'},{text:'Surat Khabar',group:'Kertas'},{text:'Tin Aluminium',group:'Logam'},{text:'Botol Kaca',group:'Kaca'}] },
      { groups: ['Organik','Bukan Organik'], items: [{text:'Daun',group:'Organik'},{text:'Plastik',group:'Bukan Organik'},{text:'Kulit Pisang',group:'Organik'},{text:'Tin',group:'Bukan Organik'},{text:'Telur',group:'Organik'}] },
      { groups: ['Plastik','Kertas','Logam','Kaca','Organik'], items: [{text:'Botol Plastik',group:'Plastik'},{text:'Surat Khabar',group:'Kertas'},{text:'Tin',group:'Logam'},{text:'Botol Kaca',group:'Kaca'},{text:'Sisa Makanan',group:'Organik'},{text:'Beg Plastik',group:'Plastik'}] },
      { groups: ['Boleh Pakai Semula','Sekali Guna'], items: [{text:'Botol Air Sendiri',group:'Boleh Pakai Semula'},{text:'Straw Plastik',group:'Sekali Guna'},{text:'Beg Kain',group:'Boleh Pakai Semula'},{text:'Tisu',group:'Sekali Guna'},{text:'Bekal Makanan',group:'Boleh Pakai Semula'}] },
      { groups: ['Plastik','Kertas','Logam','Kaca','Organik','E-Waste'], items: [{text:'Botol',group:'Plastik'},{text:'Buku',group:'Kertas'},{text:'Tin',group:'Logam'},{text:'Botol Kaca',group:'Kaca'},{text:'Daun',group:'Organik'},{text:'Bateri',group:'E-Waste'},{text:'Telefon Rosak',group:'E-Waste'}] },
      { groups: ['Boleh Kitar','Berbahaya','Organik'], items: [{text:'Botol Plastik',group:'Boleh Kitar'},{text:'Bateri',group:'Berbahaya'},{text:'Sisa Makanan',group:'Organik'},{text:'Tin',group:'Boleh Kitar'},{text:'Ubat Lama',group:'Berbahaya'},{text:'Daun',group:'Organik'},{text:'Kertas',group:'Boleh Kitar'}] },
      { groups: ['Plastik','Kertas','Logam','Kaca','Organik','E-Waste','Berbahaya'], items: [{text:'Botol Plastik',group:'Plastik'},{text:'Surat Khabar',group:'Kertas'},{text:'Tin',group:'Logam'},{text:'Botol Kaca',group:'Kaca'},{text:'Daun',group:'Organik'},{text:'Bateri',group:'E-Waste'},{text:'Cat Lama',group:'Berbahaya'},{text:'Beg Plastik',group:'Plastik'},{text:'Sisa Makanan',group:'Organik'}] },
    ]),
  },
  {
    id: 'problem-padan-alat',
    title: 'Padan Pekerjaan dan Alat',
    emoji: '🔧',
    mode: 'dragdrop',
    objective: 'Padankan alat dengan pekerjaan.',
    reward: 'Tool wisdom',
    rounds: makeRounds([
      { items: ['Stetoskop','Pembaris'], targets: ['Doktor','Cikgu'] },
      { items: ['Stetoskop','Pembaris','Berus Cat'], targets: ['Doktor','Cikgu','Pelukis'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon','Tukul'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi','Tukang Kayu'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon','Tukul','Periuk'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi','Tukang Kayu','Chef'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon','Tukul','Periuk','Hose Bomba'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi','Tukang Kayu','Chef','Bomba'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon','Tukul','Periuk','Hose Bomba','Cangkul'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi','Tukang Kayu','Chef','Bomba','Petani'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon','Tukul','Periuk','Hose Bomba','Cangkul','Topi Keledar'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi','Tukang Kayu','Chef','Bomba','Petani','Polis'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon','Tukul','Periuk','Hose Bomba','Cangkul','Topi Keledar','Komputer'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi','Tukang Kayu','Chef','Bomba','Petani','Polis','Pengaturcara'] },
      { items: ['Stetoskop','Pembaris','Berus Cat','Mikrofon','Tukul','Periuk','Hose Bomba','Cangkul','Topi Keledar','Komputer','Pesawat','Buku Cerita'], targets: ['Doktor','Cikgu','Pelukis','Penyanyi','Tukang Kayu','Chef','Bomba','Petani','Polis','Pengaturcara','Juruterbang','Penulis'] },
    ]),
  },
  {
    id: 'problem-fakta-am',
    title: 'Fakta Umum',
    emoji: '📚',
    mode: 'true_false',
    objective: 'Nilai fakta umum dengan tepat.',
    reward: 'Knowledge star',
    rounds: makeRounds([
      { statements: [{text:'Bumi mengelilingi matahari.',answer:true},{text:'Setahun ada 100 hari.',answer:false}] },
      { statements: [{text:'Manusia perlu air.',answer:true},{text:'Pokok tak perlu cahaya matahari.',answer:false}] },
      { statements: [{text:'Setahun ada 12 bulan.',answer:true},{text:'Seminggu ada 5 hari.',answer:false},{text:'Sehari ada 24 jam.',answer:true}] },
      { statements: [{text:'Sejam ada 60 minit.',answer:true},{text:'Seminit ada 100 saat.',answer:false},{text:'Pelangi ada 7 warna.',answer:true},{text:'Matahari sejuk.',answer:false}] },
      { statements: [{text:'Ais terjadi dari air.',answer:true},{text:'Salji bukan air.',answer:false},{text:'Pokok hasilkan oksigen.',answer:true},{text:'Burung tak boleh terbang.',answer:false},{text:'Ikan hidup dalam air.',answer:true}] },
      { statements: [{text:'Bahasa Inggeris ada 26 huruf.',answer:true},{text:'Vokal A E I O U.',answer:true},{text:'Konsonan hanya 5 huruf.',answer:false},{text:'5 + 5 = 10.',answer:true},{text:'10 × 0 = 10.',answer:false},{text:'Sifar tak bernilai.',answer:false}] },
      { statements: [{text:'Sepak takraw guna kaki.',answer:true},{text:'Badminton guna raket.',answer:true},{text:'Bola sepak guna tangan.',answer:false},{text:'Renang dalam air.',answer:true},{text:'Olimpik setiap 4 tahun.',answer:true},{text:'SEA Games di Eropah.',answer:false},{text:'Lari maraton sangat jauh.',answer:true}] },
      { statements: [{text:'Tujuh benua di dunia.',answer:true},{text:'Asia benua terbesar.',answer:true},{text:'Antartika sangat panas.',answer:false},{text:'Sahara gurun terbesar.',answer:true},{text:'Amazon sungai panjang.',answer:true},{text:'Everest gunung tertinggi.',answer:true},{text:'Lautan Pasifik kecil.',answer:false},{text:'Australia satu benua.',answer:true}] },
      { statements: [{text:'Sistem suria ada 8 planet.',answer:true},{text:'Pluto planet kerdil.',answer:true},{text:'Bumi planet ke-3.',answer:true},{text:'Marikh planet merah.',answer:true},{text:'Musytari planet terbesar.',answer:true},{text:'Saturn ada cincin.',answer:true},{text:'Bulan adalah bintang.',answer:false},{text:'Matahari bintang.',answer:true},{text:'Komet ialah planet.',answer:false}] },
      { statements: [{text:'Manusia ada 5 deria.',answer:true},{text:'Otak organ paling penting.',answer:true},{text:'Jantung memompa darah.',answer:true},{text:'Paru-paru untuk bernafas.',answer:true},{text:'Manusia ada 32 gigi dewasa.',answer:true},{text:'Manusia ada 4 mata.',answer:false},{text:'Manusia perlu tidur 7-9 jam.',answer:true},{text:'Manusia tak perlu makan.',answer:false},{text:'Manusia bercakap dengan otak.',answer:true},{text:'Bayi sejak lahir boleh berjalan.',answer:false}] },
    ]),
  },
];