// ⚡ SPEED FOCUS — 10 games × 10 rounds. Refleks pantas.
import { makeRounds } from './_helpers.js';

export const speedFocusGames = [
  {
    id: 'speed-reaction-tap',
    title: 'Tap Pantas',
    emoji: '👆',
    mode: 'reaction_speed',
    objective: 'Tekan butang ketika ia bertukar hijau.',
    reward: 'Speed medal',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({signal:'GO',delayMs:1500-i*100}))),
  },
  {
    id: 'speed-tangkap-bintang',
    title: 'Tangkap Bintang Jatuh',
    emoji: '⭐',
    mode: 'falling_catch',
    objective: 'Tangkap bintang sahaja, abaikan yang lain.',
    reward: 'Star catch',
    rounds: makeRounds([
      { target: '⭐', items: ['⭐','💎','⭐','🌙','⭐'] },
      { target: '⭐', items: ['⭐','☄️','⭐','🌙','💎','⭐'] },
      { target: '🌙', items: ['🌙','⭐','🌙','☄️','💎','🌙'] },
      { target: '⭐', items: ['⭐','💎','☄️','🌙','⭐','💎','⭐'] },
      { target: '💎', items: ['💎','⭐','🌙','💎','☄️','💎','⭐'] },
      { target: '⭐', items: ['⭐','💎','☄️','🌙','⭐','💎','⭐','🌟'] },
      { target: '🌟', items: ['🌟','⭐','💫','🌟','✨','🌟','⭐','💎'] },
      { target: '☄️', items: ['☄️','💫','🌟','⭐','☄️','🌙','💎','☄️','✨'] },
      { target: '✨', items: ['✨','⭐','🌟','💫','✨','💎','☄️','🌙','✨','⚡'] },
      { target: '⚡', items: ['⚡','✨','⭐','🌟','💫','⚡','💎','☄️','🌙','⚡','🌟'] },
    ]),
  },
  {
    id: 'speed-pop-belon',
    title: 'Pop Belon Berwarna',
    emoji: '🎈',
    mode: 'balloon_pop',
    objective: 'Pop hanya belon warna sasaran.',
    reward: 'Pop streak',
    rounds: makeRounds([
      { target: '🔴', items: ['🔴','🔵','🔴'] },
      { target: '🔵', items: ['🔵','🟡','🔵','🟢'] },
      { target: '🟡', items: ['🟡','🔴','🟡','🔵','🟢'] },
      { target: '🟢', items: ['🟢','🟡','🟢','🔵','🔴','🟢'] },
      { target: '🟣', items: ['🟣','🔴','🟣','🟡','🟣','🟢','🔵'] },
      { target: '🟠', items: ['🟠','🟣','🟠','🔴','🟠','🟡','🟢','🔵'] },
      { target: '🔴', items: ['🔴','🟠','🟣','🔴','🟡','🟢','🔴','🔵','🔴'] },
      { target: '🟡', items: ['🟡','🟠','🟣','🔴','🟡','🟢','🟡','🔵','🟡','⚪'] },
      { target: '🔵', items: ['🔵','🟠','🟣','🔵','🟡','🟢','🔴','🔵','⚪','⚫','🔵'] },
      { target: '⚫', items: ['⚫','⚪','🟠','🟣','⚫','🟡','🟢','🔴','🔵','⚫','⚪','⚫'] },
    ]),
  },
  {
    id: 'speed-typing-kata',
    title: 'Taip Perkataan Pantas',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan yang ditunjukkan.',
    reward: 'Type sprint',
    rounds: makeRounds([
      { target: 'kucing' },{ target: 'tikus' },{ target: 'pisang' },
      { target: 'sekolah' },{ target: 'matahari' },{ target: 'kemerdekaan' },
      { target: 'menjelajah' },{ target: 'pemandangan' },{ target: 'persahabatan' },{ target: 'kebudayaan' },
    ]),
  },
  {
    id: 'speed-swipe-warna',
    title: 'Swipe Warna Sasaran',
    emoji: '🌈',
    mode: 'swipe_select',
    objective: 'Pilih warna sasaran secepat mungkin.',
    reward: 'Color zip',
    rounds: makeRounds([
      { groups: ['Merah','Biru'], items: [{text:'🍎',group:'Merah'},{text:'🫐',group:'Biru'},{text:'🌹',group:'Merah'}] },
      { groups: ['Kuning','Hijau'], items: [{text:'🌻',group:'Kuning'},{text:'🥝',group:'Hijau'},{text:'🍋',group:'Kuning'},{text:'🌿',group:'Hijau'}] },
      { groups: ['Merah','Biru','Kuning'], items: [{text:'🍎',group:'Merah'},{text:'🫐',group:'Biru'},{text:'🌻',group:'Kuning'},{text:'🌹',group:'Merah'},{text:'🍋',group:'Kuning'}] },
      { groups: ['Merah','Biru','Hijau'], items: [{text:'🍎',group:'Merah'},{text:'🫐',group:'Biru'},{text:'🥝',group:'Hijau'},{text:'🌹',group:'Merah'},{text:'🌿',group:'Hijau'},{text:'🦋',group:'Biru'}] },
      { groups: ['Merah','Biru','Kuning','Hijau'], items: [{text:'🍎',group:'Merah'},{text:'🫐',group:'Biru'},{text:'🌻',group:'Kuning'},{text:'🥝',group:'Hijau'},{text:'🌹',group:'Merah'},{text:'🍋',group:'Kuning'}] },
      { groups: ['Merah','Biru','Kuning','Hijau','Ungu'], items: [{text:'🍎',group:'Merah'},{text:'🫐',group:'Biru'},{text:'🌻',group:'Kuning'},{text:'🥝',group:'Hijau'},{text:'🍇',group:'Ungu'},{text:'🌹',group:'Merah'},{text:'🦋',group:'Biru'}] },
      { groups: ['Merah','Biru','Kuning','Hijau','Ungu','Jingga'], items: [{text:'🍎',group:'Merah'},{text:'🫐',group:'Biru'},{text:'🌻',group:'Kuning'},{text:'🥝',group:'Hijau'},{text:'🍇',group:'Ungu'},{text:'🍊',group:'Jingga'},{text:'🌹',group:'Merah'},{text:'🦋',group:'Biru'}] },
      { groups: ['Hangat','Sejuk'], items: [{text:'🔴',group:'Hangat'},{text:'🟠',group:'Hangat'},{text:'🔵',group:'Sejuk'},{text:'🟢',group:'Sejuk'},{text:'🟡',group:'Hangat'},{text:'🟣',group:'Sejuk'},{text:'🟤',group:'Hangat'},{text:'⚪',group:'Sejuk'}] },
      { groups: ['Pelangi','Bukan Pelangi'], items: [{text:'🔴',group:'Pelangi'},{text:'🟠',group:'Pelangi'},{text:'🟡',group:'Pelangi'},{text:'🟢',group:'Pelangi'},{text:'🔵',group:'Pelangi'},{text:'🟣',group:'Pelangi'},{text:'⚫',group:'Bukan Pelangi'},{text:'⚪',group:'Bukan Pelangi'},{text:'🟤',group:'Bukan Pelangi'}] },
      { groups: ['Primer','Sekunder'], items: [{text:'🔴',group:'Primer'},{text:'🔵',group:'Primer'},{text:'🟡',group:'Primer'},{text:'🟢',group:'Sekunder'},{text:'🟠',group:'Sekunder'},{text:'🟣',group:'Sekunder'},{text:'🟤',group:'Sekunder'},{text:'⚪',group:'Sekunder'},{text:'⚫',group:'Sekunder'},{text:'🩷',group:'Sekunder'}] },
    ]),
  },
  {
    id: 'speed-pop-nombor',
    title: 'Pop Nombor Pantas',
    emoji: '🔢',
    mode: 'balloon_pop',
    objective: 'Pop nombor genap sahaja.',
    reward: 'Math pop',
    rounds: makeRounds([
      { target: '2', items: ['2','1','2'] },
      { target: '4', items: ['4','3','4','5'] },
      { target: '6', items: ['6','5','6','7','6'] },
      { target: '8', items: ['8','7','8','9','8','10'] },
      { target: '10', items: ['10','11','10','9','10','12','13'] },
      { target: '12', items: ['12','11','12','13','12','14','15','12'] },
      { target: '14', items: ['14','13','14','15','14','16','17','14','18'] },
      { target: '20', items: ['20','19','20','21','20','22','23','20','24','25'] },
      { target: '50', items: ['50','49','50','51','50','52','53','50','54','55','56'] },
      { target: '100', items: ['100','99','100','101','100','102','103','100','104','105','106','107'] },
    ]),
  },
  {
    id: 'speed-falling-huruf',
    title: 'Tangkap Huruf Vokal',
    emoji: '🔤',
    mode: 'falling_catch',
    objective: 'Tangkap huruf vokal (A E I O U).',
    reward: 'Vowel master',
    rounds: makeRounds([
      { target: 'A', items: ['A','B','A','C'] },
      { target: 'E', items: ['E','F','E','G','E'] },
      { target: 'I', items: ['I','J','I','K','I','L'] },
      { target: 'O', items: ['O','P','O','Q','O','R','O'] },
      { target: 'U', items: ['U','V','U','W','U','X','U','Y'] },
      { target: 'A', items: ['A','B','C','A','D','A','E','F','A'] },
      { target: 'E', items: ['E','F','A','I','E','U','E','O','E','B'] },
      { target: 'I', items: ['I','A','E','U','O','I','B','C','I','D','I'] },
      { target: 'O', items: ['O','A','E','I','U','O','B','C','D','O','E','O'] },
      { target: 'U', items: ['U','A','E','I','O','U','B','C','D','E','U','F','U'] },
    ]),
  },
  {
    id: 'speed-roda-pantas',
    title: 'Pop Vokal Pantas',
    emoji: '🅰️',
    mode: 'balloon_pop',
    objective: 'Pop huruf vokal sahaja (A E I O U).',
    reward: 'Vowel zap',
    rounds: makeRounds([
      { target: 'A', items: ['A','B','A','C'] },
      { target: 'E', items: ['E','D','E','F','G'] },
      { target: 'I', items: ['I','H','I','J','K','I'] },
      { target: 'O', items: ['O','N','O','P','Q','O','R'] },
      { target: 'U', items: ['U','S','U','T','V','U','W','X'] },
      { target: 'A', items: ['A','B','C','A','D','A','E','F','A'] },
      { target: 'E', items: ['E','F','G','H','E','I','E','J','E','K'] },
      { target: 'I', items: ['I','A','B','I','C','D','I','E','I','F','G'] },
      { target: 'O', items: ['O','A','B','C','O','D','E','O','F','G','H','O'] },
      { target: 'U', items: ['U','A','E','I','O','U','B','C','D','U','F','G','U'] },
    ]),
  },
  {
    id: 'speed-cari-cepat',
    title: 'Cari Pantas',
    emoji: '🔍',
    mode: 'picture_hunt',
    objective: 'Cari objek sasaran dengan cepat.',
    reward: 'Hunt streak',
    rounds: makeRounds([
      { target: '⭐', items: ['🌙','⭐','☀️'] },
      { target: '🌙', items: ['⭐','🌙','☀️','🌈'] },
      { target: '🌈', items: ['⭐','🌙','☀️','🌈','☁️'] },
      { target: '☀️', items: ['⭐','🌙','☀️','🌈','☁️','❄️'] },
      { target: '❄️', items: ['⭐','🌙','☀️','🌈','☁️','❄️','⚡'] },
      { target: '⚡', items: ['⭐','🌙','☀️','🌈','☁️','❄️','⚡','🌪️'] },
      { target: '🌪️', items: ['⭐','🌙','☀️','🌈','☁️','❄️','⚡','🌪️','🌊'] },
      { target: '🌊', items: ['⭐','🌙','☀️','🌈','☁️','❄️','⚡','🌪️','🌊','🔥'] },
      { target: '🔥', items: ['⭐','🌙','☀️','🌈','☁️','❄️','⚡','🌪️','🌊','🔥','💧'] },
      { target: '💧', items: ['⭐','🌙','☀️','🌈','☁️','❄️','⚡','🌪️','🌊','🔥','💧','🌍'] },
    ]),
  },
  {
    id: 'speed-pop-bentuk',
    title: 'Pop Bentuk Sama',
    emoji: '🔺',
    mode: 'balloon_pop',
    objective: 'Pop bentuk yang sama dengan sasaran.',
    reward: 'Shape pop',
    rounds: makeRounds([
      { target: '🔺', items: ['🔺','🔵','🔺'] },
      { target: '🔵', items: ['🔵','🟥','🔵','🔺'] },
      { target: '🟥', items: ['🟥','🔵','🟥','🔺','🟥'] },
      { target: '🟨', items: ['🟨','🟥','🟨','🔵','🟨','🔺'] },
      { target: '🟪', items: ['🟪','🟨','🟪','🟥','🟪','🔵','🟪'] },
      { target: '🟫', items: ['🟫','🟪','🟫','🟨','🟫','🟥','🟫','🔵'] },
      { target: '⬛', items: ['⬛','🟫','⬛','🟪','⬛','🟨','⬛','🟥','⬛'] },
      { target: '⬜', items: ['⬜','⬛','⬜','🟫','⬜','🟪','⬜','🟨','⬜','🟥'] },
      { target: '🔴', items: ['🔴','⬜','🔴','⬛','🔴','🟫','🔴','🟪','🔴','🟨','🔴'] },
      { target: '🟢', items: ['🟢','🔴','🟢','⬜','🟢','⬛','🟢','🟫','🟢','🟪','🟢','🟨'] },
    ]),
  },
];