// ⚡ SPEED FOCUS — 10 games × 10 rounds. Refleks pantas + fokus mata.
import { makeRounds } from './_helpers.js';

export const speedFocusGames = [
  {
    id: 'speed-tap-warna',
    title: 'Tap Bila Warna Hijau',
    emoji: '🟢',
    mode: 'reaction_speed',
    objective: 'Tekan butang ketika ia bertukar hijau.',
    reward: 'Speed star',
    rounds: makeRounds(Array.from({length:10},(_,i)=>({signal:'HIJAU',delayMs:1500-i*100}))),
  },
  {
    id: 'speed-pop-emoji-haiwan',
    title: 'Pop Emoji Haiwan',
    emoji: '🐶',
    mode: 'balloon_pop',
    objective: 'Pop hanya emoji haiwan.',
    reward: 'Animal pop',
    rounds: makeRounds([
      { target: '🐶', items: ['🐶','🍎','🐶'] },
      { target: '🐱', items: ['🐱','🚗','🐱','🌸'] },
      { target: '🐭', items: ['🐭','📚','🐭','🍌','🐭'] },
      { target: '🐰', items: ['🐰','⭐','🐰','🎈','🐰','🍕'] },
      { target: '🐯', items: ['🐯','🌙','🐯','🎨','🐯','📱','🐯'] },
      { target: '🐸', items: ['🐸','🍎','🐸','⚽','🐸','🎵','🐸','📚'] },
      { target: '🐵', items: ['🐵','🍓','🐵','🚌','🐵','✏️','🐵','🌺','🐵'] },
      { target: '🐔', items: ['🐔','🍔','🐔','🎂','🐔','🚲','🐔','📷','🐔','💎'] },
      { target: '🦊', items: ['🦊','🌈','🦊','🎁','🦊','🍰','🦊','📖','🦊','🚀','🦊'] },
      { target: '🦁', items: ['🦁','☀️','🦁','🍦','🦁','🎵','🦁','📦','🦁','🎈','🦁','🌲'] },
    ]),
  },
  {
    id: 'speed-tangkap-hujan',
    title: 'Tangkap Titisan Hujan',
    emoji: '💧',
    mode: 'falling_catch',
    objective: 'Tangkap simbol cuaca sasaran sahaja.',
    reward: 'Rain catch',
    rounds: makeRounds([
      { target: '💧', items: ['💧','🍃','💧'] },
      { target: '💧', items: ['💧','🍃','💧','⚡'] },
      { target: '💧', items: ['💧','🍃','💧','⚡','❄️'] },
      { target: '❄️', items: ['❄️','💧','🍃','❄️','⚡','💧'] },
      { target: '⚡', items: ['⚡','💧','🍃','⚡','❄️','☁️','⚡'] },
      { target: '☁️', items: ['☁️','⚡','💧','🍃','☁️','❄️','🌪️','☁️'] },
      { target: '🌪️', items: ['🌪️','☁️','⚡','💧','🍃','🌪️','❄️','🔥','🌪️'] },
      { target: '🔥', items: ['🔥','🌪️','☁️','⚡','💧','🔥','❄️','🍃','🌊','🔥'] },
      { target: '🌊', items: ['🌊','🔥','🌪️','☁️','⚡','🌊','💧','❄️','🍃','💦','🌊'] },
      { target: '💦', items: ['💦','🌊','🔥','🌪️','☁️','💦','⚡','💧','❄️','🍃','🌧️','💦'] },
    ]),
  },
  {
    id: 'speed-taip-haiwan',
    title: 'Taip Nama Haiwan',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip nama haiwan yang ditunjukkan.',
    reward: 'Type sprint',
    rounds: makeRounds([
      { target: 'kucing' },{ target: 'anjing' },{ target: 'tikus' },
      { target: 'burung' },{ target: 'monyet' },{ target: 'harimau' },
      { target: 'gajah' },{ target: 'helang' },{ target: 'penyu' },{ target: 'kupu-kupu' },
    ]),
  },
  {
    id: 'speed-swipe-besar-kecil',
    title: 'Swipe Besar atau Kecil',
    emoji: '🔍',
    mode: 'swipe_select',
    objective: 'Pilih objek besar atau kecil dengan cepat.',
    reward: 'Size zip',
    rounds: makeRounds([
      { groups: ['Besar','Kecil'], items: [{text:'🐘',group:'Besar'},{text:'🐜',group:'Kecil'},{text:'🐋',group:'Besar'}] },
      { groups: ['Besar','Kecil'], items: [{text:'🏠',group:'Besar'},{text:'🐭',group:'Kecil'},{text:'🚌',group:'Besar'},{text:'🍒',group:'Kecil'}] },
      { groups: ['Besar','Kecil'], items: [{text:'🐘',group:'Besar'},{text:'🐜',group:'Kecil'},{text:'🐋',group:'Besar'},{text:'🐭',group:'Kecil'},{text:'🦒',group:'Besar'}] },
      { groups: ['Besar','Kecil','Sederhana'], items: [{text:'🐘',group:'Besar'},{text:'🐜',group:'Kecil'},{text:'🐕',group:'Sederhana'},{text:'🐋',group:'Besar'},{text:'🐭',group:'Kecil'}] },
      { groups: ['Tinggi','Pendek'], items: [{text:'🦒',group:'Tinggi'},{text:'🐢',group:'Pendek'},{text:'🌳',group:'Tinggi'},{text:'🍄',group:'Pendek'},{text:'🗼',group:'Tinggi'}] },
      { groups: ['Berat','Ringan'], items: [{text:'🏋️',group:'Berat'},{text:'🪶',group:'Ringan'},{text:'🪨',group:'Berat'},{text:'🎈',group:'Ringan'},{text:'⚓',group:'Berat'},{text:'🪁',group:'Ringan'}] },
      { groups: ['Panjang','Pendek'], items: [{text:'🐍',group:'Panjang'},{text:'🐛',group:'Pendek'},{text:'🚂',group:'Panjang'},{text:'🚗',group:'Pendek'},{text:'📏',group:'Panjang'},{text:'📎',group:'Pendek'}] },
      { groups: ['Bulat','Bersudut'], items: [{text:'⚽',group:'Bulat'},{text:'🟥',group:'Bersudut'},{text:'🍎',group:'Bulat'},{text:'🔺',group:'Bersudut'},{text:'⭕',group:'Bulat'},{text:'⬛',group:'Bersudut'},{text:'🌕',group:'Bulat'}] },
      { groups: ['Hidup','Mati'], items: [{text:'🌳',group:'Hidup'},{text:'🪨',group:'Mati'},{text:'🐠',group:'Hidup'},{text:'⚽',group:'Mati'},{text:'🌸',group:'Hidup'},{text:'📚',group:'Mati'},{text:'🐝',group:'Hidup'},{text:'🚗',group:'Mati'}] },
      { groups: ['Boleh Terbang','Tak Boleh Terbang'], items: [{text:'🦅',group:'Boleh Terbang'},{text:'🐢',group:'Tak Boleh Terbang'},{text:'✈️',group:'Boleh Terbang'},{text:'🚗',group:'Tak Boleh Terbang'},{text:'🦋',group:'Boleh Terbang'},{text:'🐟',group:'Tak Boleh Terbang'},{text:'🚁',group:'Boleh Terbang'},{text:'🚌',group:'Tak Boleh Terbang'}] },
    ]),
  },
  {
    id: 'speed-pop-bilangan',
    title: 'Pop Nombor Ganjil',
    emoji: '1️⃣',
    mode: 'balloon_pop',
    objective: 'Pop nombor ganjil sahaja.',
    reward: 'Odd pop',
    rounds: makeRounds([
      { target: '1', items: ['1','2','1'] },
      { target: '3', items: ['3','4','3','2'] },
      { target: '5', items: ['5','4','5','6','5'] },
      { target: '7', items: ['7','6','7','8','7','10'] },
      { target: '9', items: ['9','8','9','10','9','11','12'] },
      { target: '11', items: ['11','10','11','12','11','14','16','11'] },
      { target: '13', items: ['13','12','13','14','13','16','20','13','18'] },
      { target: '15', items: ['15','14','15','16','15','18','22','15','20','24'] },
      { target: '17', items: ['17','16','17','18','17','20','26','17','22','28','24'] },
      { target: '19', items: ['19','18','19','20','19','22','28','19','24','30','26','32'] },
    ]),
  },
  {
    id: 'speed-falling-bentuk',
    title: 'Tangkap Bentuk Bulat',
    emoji: '⭕',
    mode: 'falling_catch',
    objective: 'Tangkap bentuk bulat sahaja.',
    reward: 'Round catch',
    rounds: makeRounds([
      { target: '⭕', items: ['⭕','🔺','⭕'] },
      { target: '🔵', items: ['🔵','🔺','🔵','🟥'] },
      { target: '🟢', items: ['🟢','🔺','🟢','🟥','🟢'] },
      { target: '🌕', items: ['🌕','🔺','🌕','🟥','🌕','🟨'] },
      { target: '⚽', items: ['⚽','🔺','⚽','🟥','⚽','🟨','⚽'] },
      { target: '🍎', items: ['🍎','🔺','🍎','🟥','🍎','🟨','🍎','▶️'] },
      { target: '🟠', items: ['🟠','🔺','🟠','🟥','🟠','🟨','🟠','▶️','🟠'] },
      { target: '🟣', items: ['🟣','🔺','🟣','🟥','🟣','🟨','🟣','▶️','🟣','🔻'] },
      { target: '⚪', items: ['⚪','🔺','⚪','🟥','⚪','🟨','⚪','▶️','⚪','🔻','⚪'] },
      { target: '⚫', items: ['⚫','🔺','⚫','🟥','⚫','🟨','⚫','▶️','⚫','🔻','⚫','🔶'] },
    ]),
  },
  {
    id: 'speed-pop-konsonan',
    title: 'Pop Huruf Konsonan',
    emoji: '🔡',
    mode: 'balloon_pop',
    objective: 'Pop konsonan sahaja (bukan vokal).',
    reward: 'Consonant zap',
    rounds: makeRounds([
      { target: 'B', items: ['B','A','B'] },
      { target: 'C', items: ['C','E','C','I'] },
      { target: 'D', items: ['D','O','D','U','D'] },
      { target: 'F', items: ['F','A','F','E','F','I'] },
      { target: 'G', items: ['G','A','G','E','G','I','G'] },
      { target: 'H', items: ['H','A','E','I','H','O','H','U'] },
      { target: 'J', items: ['J','A','E','I','J','O','U','J','A'] },
      { target: 'K', items: ['K','A','E','I','O','K','U','K','A','E'] },
      { target: 'L', items: ['L','A','E','I','O','U','L','A','L','E','I'] },
      { target: 'M', items: ['M','A','E','I','O','U','M','A','E','M','I','O'] },
    ]),
  },
  {
    id: 'speed-cari-objek-pantas',
    title: 'Cari Objek Pantas',
    emoji: '🔎',
    mode: 'picture_hunt',
    objective: 'Cari objek sasaran dengan cepat.',
    reward: 'Hunt sprint',
    rounds: makeRounds([
      { target: '🚗', items: ['🚗','🚲','🏠'] },
      { target: '🍎', items: ['🍎','🍌','🍇','🥝'] },
      { target: '⭐', items: ['⭐','🌙','☀️','🌈','☁️'] },
      { target: '🎈', items: ['🎈','🎁','🎂','🎉','🎊','🎀'] },
      { target: '🐶', items: ['🐶','🐱','🐭','🐰','🦊','🐻','🐯'] },
      { target: '⚽', items: ['⚽','🏀','🎾','🏐','🏈','🥎','🎱','🏓'] },
      { target: '✏️', items: ['✏️','📚','🎒','📏','✂️','🖍️','🖊️','📐','📓'] },
      { target: '🌸', items: ['🌸','🌻','🌹','🌷','🌺','🪷','💐','🌼','🪻','🌾'] },
      { target: '🐠', items: ['🐠','🐟','🐡','🐬','🦈','🐢','🐙','🦀','🦐','🦞','🦑'] },
      { target: '🚀', items: ['🚀','✈️','🚁','🛸','🛩️','🚂','🚙','🚌','🚲','🛴','⛵','🛶'] },
    ]),
  },
  {
    id: 'speed-pop-emoji-makanan',
    title: 'Pop Emoji Makanan',
    emoji: '🍕',
    mode: 'balloon_pop',
    objective: 'Pop hanya emoji makanan.',
    reward: 'Food zap',
    rounds: makeRounds([
      { target: '🍕', items: ['🍕','🚗','🍕'] },
      { target: '🍔', items: ['🍔','📚','🍔','🌸'] },
      { target: '🍟', items: ['🍟','⭐','🍟','🎈','🍟'] },
      { target: '🌭', items: ['🌭','🐶','🌭','📱','🌭','🚌'] },
      { target: '🥗', items: ['🥗','🌈','🥗','🎵','🥗','📦','🥗'] },
      { target: '🍣', items: ['🍣','🎁','🍣','🚀','🍣','🌲','🍣','💎'] },
      { target: '🍩', items: ['🍩','📷','🍩','🎂','🍩','🌺','🍩','✏️','🍩'] },
      { target: '🍦', items: ['🍦','🚲','🍦','🎨','🍦','📖','🍦','☀️','🍦','💧'] },
      { target: '🎂', items: ['🎂','🎈','🎂','🌙','🎂','🚌','🎂','📱','🎂','🐱','🎂'] },
      { target: '🍿', items: ['🍿','🌈','🍿','🚂','🍿','🎁','🍿','📷','🍿','🏠','🍿','🌳'] },
    ]),
  },
];