// 📖 MEMBACA — kemahiran literasi: kenal huruf, suku kata, perkataan.
// Untuk prasekolah + darjah rendah. Guna mekanik sedia ada (MiniGameModeRenderer).
import { makeRounds } from '../miniGames/_helpers.js';

export const membacaGames = [
  {
    id: 'baca-kenal-huruf',
    title: 'Kenal Huruf',
    emoji: '🔤',
    mode: 'hidden_object',
    objective: 'Cari huruf yang betul.',
    reward: 'Huruf badge',
    rounds: makeRounds([
      { target: 'A', items: [{text:'A',value:'a'},{text:'B',value:'b'},{text:'C',value:'c'}] },
      { target: 'E', items: [{text:'E',value:'e'},{text:'F',value:'f'},{text:'G',value:'g'}] },
      { target: 'I', items: [{text:'I',value:'i'},{text:'J',value:'j'},{text:'K',value:'k'},{text:'L',value:'l'}] },
      { target: 'O', items: [{text:'O',value:'o'},{text:'P',value:'p'},{text:'Q',value:'q'},{text:'R',value:'r'}] },
      { target: 'U', items: [{text:'U',value:'u'},{text:'V',value:'v'},{text:'W',value:'w'},{text:'X',value:'x'},{text:'Y',value:'y'}] },
      { target: 'M', items: [{text:'M',value:'m'},{text:'N',value:'n'},{text:'W',value:'w'},{text:'V',value:'v'},{text:'U',value:'u'}] },
      { target: 'S', items: [{text:'S',value:'s'},{text:'Z',value:'z'},{text:'C',value:'c'},{text:'G',value:'g'},{text:'O',value:'o'},{text:'Q',value:'q'}] },
      { target: 'B', items: [{text:'B',value:'b'},{text:'D',value:'d'},{text:'P',value:'p'},{text:'R',value:'r'},{text:'F',value:'f'},{text:'E',value:'e'}] },
      { target: 'D', items: [{text:'D',value:'d'},{text:'B',value:'b'},{text:'P',value:'p'},{text:'O',value:'o'},{text:'Q',value:'q'},{text:'G',value:'g'},{text:'C',value:'c'}] },
      { target: 'K', items: [{text:'K',value:'k'},{text:'X',value:'x'},{text:'H',value:'h'},{text:'R',value:'r'},{text:'N',value:'n'},{text:'M',value:'m'},{text:'A',value:'a'},{text:'V',value:'v'}] },
    ]),
  },
  {
    id: 'baca-huruf-besar-kecil',
    title: 'Padan Huruf Besar & Kecil',
    emoji: '🅰️',
    mode: 'memory',
    objective: 'Padankan huruf besar dengan huruf kecil.',
    reward: 'Match huruf',
    rounds: makeRounds([
      { pairs: [['A','a'],['B','b'],['C','c']] },
      { pairs: [['D','d'],['E','e'],['F','f']] },
      { pairs: [['A','a'],['B','b'],['C','c'],['D','d']] },
      { pairs: [['G','g'],['H','h'],['I','i'],['J','j']] },
      { pairs: [['A','a'],['E','e'],['I','i'],['O','o'],['U','u']] },
      { pairs: [['K','k'],['L','l'],['M','m'],['N','n'],['O','o']] },
      { pairs: [['A','a'],['B','b'],['C','c'],['D','d'],['E','e'],['F','f']] },
      { pairs: [['P','p'],['Q','q'],['R','r'],['S','s'],['T','t'],['U','u']] },
      { pairs: [['A','a'],['B','b'],['C','c'],['D','d'],['E','e'],['F','f'],['G','g']] },
      { pairs: [['M','m'],['N','n'],['O','o'],['P','p'],['Q','q'],['R','r'],['S','s'],['T','t']] },
    ]),
  },
  {
    id: 'baca-suku-kata',
    title: 'Bina Suku Kata',
    emoji: '🧩',
    mode: 'wordbuilder',
    objective: 'Susun suku kata jadi perkataan.',
    reward: 'Suku kata star',
    rounds: makeRounds([
      { target: 'BABA', letters: ['BA','BA'] },
      { target: 'MAMA', letters: ['MA','MA'] },
      { target: 'BATU', letters: ['BA','TU'] },
      { target: 'BUKU', letters: ['BU','KU'] },
      { target: 'KERETA', letters: ['KE','RE','TA'] },
      { target: 'BUNGA', letters: ['BU','NGA'] },
      { target: 'KELAPA', letters: ['KE','LA','PA'] },
      { target: 'BASIKAL', letters: ['BA','SI','KAL'] },
      { target: 'SEKOLAH', letters: ['SE','KO','LAH'] },
      { target: 'KOMPUTER', letters: ['KOM','PU','TER'] },
    ]),
  },
  {
    id: 'baca-padan-perkataan-gambar',
    title: 'Padan Perkataan & Gambar',
    emoji: '🖼️',
    mode: 'tilematch',
    objective: 'Padankan perkataan dengan gambar.',
    reward: 'Word match',
    rounds: makeRounds([
      { tiles: ['Kucing', '🐱', 'Anjing', '🐶'] },
      { tiles: ['Epal', '🍎', 'Pisang', '🍌'] },
      { tiles: ['Kereta', '🚗', 'Bas', '🚌', 'Basikal', '🚲'] },
      { tiles: ['Matahari', '☀️', 'Bulan', '🌙', 'Bintang', '⭐'] },
      { tiles: ['Rumah', '🏠', 'Pokok', '🌳', 'Bunga', '🌸', 'Ikan', '🐟'] },
      { tiles: ['Buku', '📚', 'Pensel', '✏️', 'Beg', '🎒', 'Gunting', '✂️'] },
      { tiles: ['Ayam', '🐔', 'Itik', '🦆', 'Lembu', '🐄', 'Kambing', '🐐'] },
      { tiles: ['Bola', '⚽', 'Belon', '🎈', 'Hadiah', '🎁', 'Kek', '🎂', 'Lilin', '🕯️'] },
      { tiles: ['Hujan', '🌧️', 'Pelangi', '🌈', 'Salji', '❄️', 'Awan', '☁️', 'Kilat', '⚡'] },
      { tiles: ['Doktor', '👨‍⚕️', 'Guru', '👨‍🏫', 'Polis', '👮', 'Bomba', '👨‍🚒', 'Petani', '👨‍🌾', 'Cef', '👨‍🍳'] },
    ]),
  },
  {
    id: 'baca-eja-perkataan',
    title: 'Eja Perkataan',
    emoji: '✍️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan mengikut gambar.',
    reward: 'Spell badge',
    rounds: makeRounds([
      { prompt: '🐱 Haiwan ini dipanggil?', target: 'kucing' },
      { prompt: '🍎 Buah ini ialah?', target: 'epal' },
      { prompt: '🚗 Kenderaan ini ialah?', target: 'kereta' },
      { prompt: '🏠 Tempat tinggal kita?', target: 'rumah' },
      { prompt: '🌳 Tumbuhan tinggi ini?', target: 'pokok' },
      { prompt: '☀️ Yang bersinar di siang hari?', target: 'matahari' },
      { prompt: '🐟 Hidup dalam air?', target: 'ikan' },
      { prompt: '🚲 Ada dua tayar, dikayuh?', target: 'basikal' },
      { prompt: '🏫 Tempat kita belajar?', target: 'sekolah' },
      { prompt: '🌈 Warna-warni selepas hujan?', target: 'pelangi' },
    ]),
  },
  {
    id: 'baca-padan-suku-kata',
    title: 'Padan Suku Kata',
    emoji: '🔡',
    mode: 'tilematch',
    objective: 'Padankan suku kata yang sama.',
    reward: 'Reading focus',
    rounds: makeRounds([
      { tiles: ['BA', 'BA', 'MA', 'MA'] },
      { tiles: ['KU', 'KU', 'TU', 'TU'] },
      { tiles: ['BA', 'BA', 'KU', 'KU', 'LA', 'LA'] },
      { tiles: ['SE', 'SE', 'KO', 'KO', 'LAH', 'LAH'] },
      { tiles: ['BU', 'BU', 'NGA', 'NGA', 'KE', 'KE', 'RE', 'RE'] },
      { tiles: ['MA', 'MA', 'TA', 'TA', 'RI', 'RI', 'HA', 'HA'] },
      { tiles: ['PE', 'PE', 'LA', 'LA', 'JAR', 'JAR', 'AN', 'AN'] },
      { tiles: ['KOM', 'KOM', 'PU', 'PU', 'TER', 'TER', 'KAN', 'KAN'] },
      { tiles: ['BA', 'BA', 'SI', 'SI', 'KAL', 'KAL', 'TU', 'TU', 'JU', 'JU'] },
      { tiles: ['TE', 'TE', 'LE', 'LE', 'VI', 'VI', 'SYEN', 'SYEN', 'KA', 'KA', 'WAN', 'WAN'] },
    ]),
  },
];