// 📖 MEMBACA — disusun ikut Konstruk LINUS Literasi BM rasmi (Konstruk 1–8).
// Fokus kemahiran MEMBACA: kenal huruf → suku kata terbuka → perkataan terbuka →
// suku kata tertutup → perkataan tertutup → 'ng' → diftong → vokal berganding.
// Guna pelbagai mekanik mini-game (MiniGameModeRenderer).
import { makeRounds } from '../miniGames/_helpers.js';

export const membacaGames = [
  // ── KONSTRUK 1: Membaca huruf vokal & konsonan ──
  {
    id: 'baca-k1-huruf',
    title: 'Konstruk 1: Kenal Huruf',
    emoji: '🔤',
    mode: 'hidden_object',
    objective: 'Cari huruf vokal & konsonan yang betul.',
    reward: 'Huruf badge',
    rounds: makeRounds([
      { target: 'A', items: [{text:'A',value:'a'},{text:'B',value:'b'},{text:'C',value:'c'}] },
      { target: 'E', items: [{text:'E',value:'e'},{text:'F',value:'f'},{text:'I',value:'i'}] },
      { target: 'I', items: [{text:'I',value:'i'},{text:'J',value:'j'},{text:'K',value:'k'},{text:'L',value:'l'}] },
      { target: 'O', items: [{text:'O',value:'o'},{text:'P',value:'p'},{text:'Q',value:'q'},{text:'U',value:'u'}] },
      { target: 'U', items: [{text:'U',value:'u'},{text:'V',value:'v'},{text:'W',value:'w'},{text:'O',value:'o'},{text:'A',value:'a'}] },
      { target: 'M', items: [{text:'M',value:'m'},{text:'N',value:'n'},{text:'W',value:'w'},{text:'V',value:'v'},{text:'U',value:'u'}] },
      { target: 'S', items: [{text:'S',value:'s'},{text:'Z',value:'z'},{text:'C',value:'c'},{text:'G',value:'g'},{text:'O',value:'o'},{text:'Q',value:'q'}] },
      { target: 'B', items: [{text:'B',value:'b'},{text:'D',value:'d'},{text:'P',value:'p'},{text:'R',value:'r'},{text:'F',value:'f'},{text:'E',value:'e'}] },
      { target: 'D', items: [{text:'D',value:'d'},{text:'B',value:'b'},{text:'P',value:'p'},{text:'O',value:'o'},{text:'Q',value:'q'},{text:'G',value:'g'},{text:'C',value:'c'}] },
      { target: 'K', items: [{text:'K',value:'k'},{text:'X',value:'x'},{text:'H',value:'h'},{text:'R',value:'r'},{text:'N',value:'n'},{text:'M',value:'m'},{text:'A',value:'a'},{text:'V',value:'v'}] },
    ]),
  },
  // ── KONSTRUK 2: Membaca suku kata TERBUKA (KV) ──
  {
    id: 'baca-k2-suku-terbuka',
    title: 'Konstruk 2: Suku Kata Terbuka',
    emoji: '🅰️',
    mode: 'tilematch',
    objective: 'Padankan suku kata terbuka (KV) yang sama.',
    reward: 'Suku terbuka',
    rounds: makeRounds([
      { tiles: ['BA', 'BA', 'BI', 'BI'] },
      { tiles: ['BU', 'BU', 'BO', 'BO'] },
      { tiles: ['MA', 'MA', 'MI', 'MI', 'MU', 'MU'] },
      { tiles: ['KA', 'KA', 'KI', 'KI', 'KU', 'KU'] },
      { tiles: ['SA', 'SA', 'SI', 'SI', 'SU', 'SU', 'SE', 'SE'] },
      { tiles: ['LA', 'LA', 'LI', 'LI', 'LU', 'LU', 'LO', 'LO'] },
      { tiles: ['TA', 'TA', 'TI', 'TI', 'TU', 'TU', 'TE', 'TE'] },
      { tiles: ['NA', 'NA', 'NI', 'NI', 'NU', 'NU', 'NE', 'NE', 'NO', 'NO'] },
      { tiles: ['PA', 'PA', 'PI', 'PI', 'PU', 'PU', 'PE', 'PE', 'PO', 'PO'] },
      { tiles: ['GA', 'GA', 'GI', 'GI', 'GU', 'GU', 'GE', 'GE', 'GO', 'GO', 'JA', 'JA'] },
    ]),
  },
  // ── KONSTRUK 3: Membaca perkataan suku kata TERBUKA (KV+KV) ──
  {
    id: 'baca-k3-perkataan-terbuka',
    title: 'Konstruk 3: Perkataan Suku Terbuka',
    emoji: '🧩',
    mode: 'wordbuilder',
    objective: 'Bina perkataan suku kata terbuka (cth: BA+TU).',
    reward: 'Word terbuka',
    rounds: makeRounds([
      { target: 'BABA', letters: ['BA','BA'] },
      { target: 'MAMA', letters: ['MA','MA'] },
      { target: 'BATU', letters: ['BA','TU'] },
      { target: 'BUKU', letters: ['BU','KU'] },
      { target: 'DADU', letters: ['DA','DU'] },
      { target: 'SAPU', letters: ['SA','PU'] },
      { target: 'KUDA', letters: ['KU','DA'] },
      { target: 'MEJA', letters: ['ME','JA'] },
      { target: 'KELAPA', letters: ['KE','LA','PA'] },
      { target: 'KERETA', letters: ['KE','RE','TA'] },
    ]),
  },
  // ── KONSTRUK 4 & 5: Suku kata & perkataan suku kata TERTUTUP (KVK) ──
  {
    id: 'baca-k5-perkataan-tertutup',
    title: 'Konstruk 4–5: Suku Kata Tertutup',
    emoji: '🔡',
    mode: 'wordbuilder',
    objective: 'Bina perkataan suku kata tertutup (KVK).',
    reward: 'Word tertutup',
    rounds: makeRounds([
      { target: 'BAS', letters: ['BAS'] },
      { target: 'CAT', letters: ['CAT'] },
      { target: 'BOLA', letters: ['BO','LA'] },
      { target: 'KASUT', letters: ['KA','SUT'] },
      { target: 'BASKET', letters: ['BAS','KET'] },
      { target: 'KAMBING', letters: ['KAM','BING'] },
      { target: 'TEMPAT', letters: ['TEM','PAT'] },
      { target: 'LAMPU', letters: ['LAM','PU'] },
      { target: 'PENSEL', letters: ['PEN','SEL'] },
      { target: 'KOMPUTER', letters: ['KOM','PU','TER'] },
    ]),
  },
  // ── KONSTRUK 6: Perkataan dengan suku kata tertutup 'ng' ──
  {
    id: 'baca-k6-ng',
    title: 'Konstruk 6: Bunyi "ng"',
    emoji: '🎵',
    mode: 'hidden_object',
    objective: 'Cari perkataan yang ada bunyi "ng".',
    reward: 'NG badge',
    rounds: makeRounds([
      { target: 'BUNGA', items: [{text:'BUNGA'},{text:'BUKU'},{text:'BATU'}] },
      { target: 'TANGAN', items: [{text:'TANGAN'},{text:'TALAM'},{text:'TASIK'}] },
      { target: 'BINTANG', items: [{text:'BINTANG'},{text:'BISKUT'},{text:'BOLA'},{text:'BATAS'}] },
      { target: 'KANGKUNG', items: [{text:'KANGKUNG'},{text:'KASUT'},{text:'KAMERA'},{text:'KATIL'}] },
      { target: 'LADANG', items: [{text:'LADANG'},{text:'LAMPU'},{text:'LARI'},{text:'LAUK'},{text:'LABU'}] },
      { target: 'TONGKAT', items: [{text:'TONGKAT'},{text:'TOPI'},{text:'TIKAR'},{text:'TALI'},{text:'TUDUNG'}] },
      { target: 'JAGUNG', items: [{text:'JAGUNG'},{text:'JALAN'},{text:'JARI'},{text:'JAM'},{text:'JALA'},{text:'JAGA'}] },
      { target: 'GUNUNG', items: [{text:'GUNUNG'},{text:'GIGI'},{text:'GARAM'},{text:'GULA'},{text:'GARPU'},{text:'GETAH'}] },
      { target: 'BURUNG', items: [{text:'BURUNG'},{text:'BANTAL'},{text:'BUKIT'},{text:'BAJU'},{text:'BATU'},{text:'BOLA'},{text:'BAKUL'}] },
      { target: 'PAYUNG', items: [{text:'PAYUNG'},{text:'PINTU'},{text:'PASU'},{text:'POKOK'},{text:'PAGAR'},{text:'PANTUN'},{text:'PISAU'},{text:'PAKU'}] },
    ]),
  },
  // ── KONSTRUK 7 & 8: Diftong (ai, au, oi) & vokal berganding ──
  {
    id: 'baca-k7-diftong',
    title: 'Konstruk 7–8: Diftong (ai, au, oi)',
    emoji: '🖼️',
    mode: 'tilematch',
    objective: 'Padankan perkataan diftong dengan gambar.',
    reward: 'Diftong star',
    rounds: makeRounds([
      { tiles: ['Harimau', '🐯', 'Kerbau', '🐃'] },
      { tiles: ['Pisau', '🔪', 'Pulau', '🏝️'] },
      { tiles: ['Kedai', '🏪', 'Limau', '🍊', 'Sungai', '🏞️'] },
      { tiles: ['Pantai', '🏖️', 'Tupai', '🐿️', 'Kuih', '🧁'] },
      { tiles: ['Harimau', '🐯', 'Pisau', '🔪', 'Limau', '🍊', 'Pulau', '🏝️'] },
      { tiles: ['Pantai', '🏖️', 'Sungai', '🏞️', 'Tupai', '🐿️', 'Kedai', '🏪'] },
      { tiles: ['Kerbau', '🐃', 'Buaya', '🐊', 'Kuih', '🧁', 'Air', '💧', 'Daun', '🍃'] },
      { tiles: ['Pisau', '🔪', 'Limau', '🍊', 'Pantai', '🏖️', 'Tupai', '🐿️', 'Pulau', '🏝️'] },
      { tiles: ['Harimau', '🐯', 'Kerbau', '🐃', 'Buaya', '🐊', 'Kedai', '🏪', 'Sungai', '🏞️', 'Laut', '🌊'] },
      { tiles: ['Pantai', '🏖️', 'Pisau', '🔪', 'Limau', '🍊', 'Tupai', '🐿️', 'Kuih', '🧁', 'Daun', '🍃', 'Air', '💧'] },
    ]),
  },
  // ── KONSTRUK 1: Padan huruf besar & kecil ──
  {
    id: 'baca-k1-besar-kecil',
    title: 'Konstruk 1: Huruf Besar & Kecil',
    emoji: '🔠',
    mode: 'tilematch',
    objective: 'Padankan huruf besar dengan huruf kecil.',
    reward: 'Case match',
    rounds: makeRounds([
      { tiles: ['A', 'a', 'B', 'b'] },
      { tiles: ['C', 'c', 'D', 'd'] },
      { tiles: ['E', 'e', 'F', 'f', 'G', 'g'] },
      { tiles: ['H', 'h', 'I', 'i', 'J', 'j'] },
      { tiles: ['K', 'k', 'L', 'l', 'M', 'm', 'N', 'n'] },
      { tiles: ['O', 'o', 'P', 'p', 'Q', 'q', 'R', 'r'] },
      { tiles: ['S', 's', 'T', 't', 'U', 'u', 'V', 'v', 'W', 'w'] },
      { tiles: ['B', 'b', 'D', 'd', 'P', 'p', 'Q', 'q', 'G', 'g'] },
      { tiles: ['A', 'a', 'E', 'e', 'M', 'm', 'N', 'n', 'U', 'u', 'V', 'v'] },
      { tiles: ['X', 'x', 'Y', 'y', 'Z', 'z', 'F', 'f', 'L', 'l', 'T', 't'] },
    ]),
  },
  // ── KONSTRUK 1: Huruf awal perkataan ──
  {
    id: 'baca-k1-huruf-awal',
    title: 'Konstruk 1: Huruf Awal',
    emoji: '🅰️',
    mode: 'hidden_object',
    objective: 'Cari huruf awal bagi gambar.',
    reward: 'Awal badge',
    rounds: makeRounds([
      { target: 'A', items: [{text:'A'},{text:'B'},{text:'C'}] },        // 🍍 Ananas
      { target: 'B', items: [{text:'B'},{text:'D'},{text:'P'}] },        // 🐝 Bee/Bunga
      { target: 'I', items: [{text:'I'},{text:'U'},{text:'O'},{text:'A'}] }, // 🐟 Ikan
      { target: 'K', items: [{text:'K'},{text:'G'},{text:'T'},{text:'D'}] }, // 🚗 Kereta
      { target: 'M', items: [{text:'M'},{text:'N'},{text:'W'},{text:'H'},{text:'B'}] }, // 🥭 Mangga
      { target: 'R', items: [{text:'R'},{text:'P'},{text:'B'},{text:'K'},{text:'D'}] }, // 🏠 Rumah
      { target: 'S', items: [{text:'S'},{text:'Z'},{text:'C'},{text:'F'},{text:'T'},{text:'L'}] }, // 🐟 Siakap
      { target: 'T', items: [{text:'T'},{text:'F'},{text:'L'},{text:'K'},{text:'I'},{text:'E'}] }, // ✋ Tangan
      { target: 'B', items: [{text:'B'},{text:'P'},{text:'D'},{text:'R'},{text:'G'},{text:'K'},{text:'V'}] }, // ⚽ Bola
      { target: 'G', items: [{text:'G'},{text:'K'},{text:'C'},{text:'J'},{text:'Q'},{text:'O'},{text:'D'},{text:'B'}] }, // 🐘 Gajah
    ]),
  },
  // ── KONSTRUK 2: Padan suku kata terbuka dengan gambar ──
  {
    id: 'baca-k2-suku-gambar',
    title: 'Konstruk 2: Suku Kata & Gambar',
    emoji: '🖼️',
    mode: 'tilematch',
    objective: 'Padan suku kata pertama dengan gambar.',
    reward: 'Suku gambar',
    rounds: makeRounds([
      { tiles: ['BU', '📚', 'KU', '🐎'] },
      { tiles: ['SA', '🧹', 'ME', '🪑'] },
      { tiles: ['BO', '⚽', 'BA', '🚌', 'DA', '🎲'] },
      { tiles: ['KE', '🚗', 'PI', '🍌', 'GI', '🦷'] },
      { tiles: ['BU', '🌸', 'KU', '🐱', 'TA', '✋', 'MA', '👁️'] },
      { tiles: ['RO', '🤖', 'KA', '👟', 'LA', '🪔', 'TI', '🎫'] },
      { tiles: ['SU', '🥄', 'PE', '✏️', 'BU', '📖', 'NA', '🍍', 'RU', '🏠'] },
      { tiles: ['GE', '🥁', 'JA', '🕐', 'LO', '🛎️', 'CA', '🎨', 'PI', '🍕'] },
      { tiles: ['BA', '🦇', 'KO', '🍪', 'DU', '💰', 'SA', '🦷', 'TO', '🎩', 'RA', '👑'] },
      { tiles: ['BU', '🐻', 'NA', '🐍', 'KU', '🥝', 'MI', '🥛', 'PA', '🌴', 'LE', '🍋'] },
    ]),
  },
  // ── KONSTRUK 3: Cari perkataan suku terbuka yang betul ──
  {
    id: 'baca-k3-cari-perkataan',
    title: 'Konstruk 3: Cari Perkataan Terbuka',
    emoji: '🔍',
    mode: 'hidden_object',
    objective: 'Cari perkataan yang dieja betul.',
    reward: 'Cari terbuka',
    rounds: makeRounds([
      { target: 'BATU', items: [{text:'BATU'},{text:'BTAU'},{text:'TABU'}] },
      { target: 'BUKU', items: [{text:'BUKU'},{text:'KUBU'},{text:'BKUU'}] },
      { target: 'KUDA', items: [{text:'KUDA'},{text:'DUKA'},{text:'KDUA'},{text:'AKUD'}] },
      { target: 'MEJA', items: [{text:'MEJA'},{text:'JEMA'},{text:'MAJE'},{text:'EJAM'}] },
      { target: 'SAPU', items: [{text:'SAPU'},{text:'PUSA'},{text:'SUPA'},{text:'APUS'},{text:'PASU'}] },
      { target: 'DADU', items: [{text:'DADU'},{text:'DUDA'},{text:'ADDU'},{text:'UDAD'},{text:'DADA'}] },
      { target: 'BOLA', items: [{text:'BOLA'},{text:'LOBA'},{text:'BALO'},{text:'ALOB'},{text:'OBAL'},{text:'LABO'}] },
      { target: 'KELAPA', items: [{text:'KELAPA'},{text:'PELAKA'},{text:'KEPALA'},{text:'LEKAPA'},{text:'KALEPA'},{text:'APAKEL'}] },
      { target: 'KERETA', items: [{text:'KERETA'},{text:'TERAKE'},{text:'RETAKE'},{text:'KETERA'},{text:'EKARET'},{text:'TAREKE'},{text:'RAKETE'}] },
      { target: 'CAWAN', items: [{text:'CAWAN'},{text:'WACAN'},{text:'NAWAC'},{text:'CANWA'},{text:'AWCAN'},{text:'WANCA'},{text:'NACAW'},{text:'CAWNA'}] },
    ]),
  },
  // ── KONSTRUK 5: Cari perkataan suku tertutup yang betul ──
  {
    id: 'baca-k5-cari-tertutup',
    title: 'Konstruk 5: Cari Perkataan Tertutup',
    emoji: '🔎',
    mode: 'hidden_object',
    objective: 'Cari perkataan suku kata tertutup yang betul.',
    reward: 'Cari tertutup',
    rounds: makeRounds([
      { target: 'BAS', items: [{text:'BAS'},{text:'SAB'},{text:'ABS'}] },
      { target: 'KASUT', items: [{text:'KASUT'},{text:'SAKUT'},{text:'KATUS'}] },
      { target: 'LAMPU', items: [{text:'LAMPU'},{text:'PAMLU'},{text:'MALPU'},{text:'LUMPA'}] },
      { target: 'POKOK', items: [{text:'POKOK'},{text:'KOPOK'},{text:'KOKOP'},{text:'POKKO'}] },
      { target: 'RUMAH', items: [{text:'RUMAH'},{text:'MURAH'},{text:'HAMUR'},{text:'RAMUH'},{text:'MARUH'}] },
      { target: 'PENSEL', items: [{text:'PENSEL'},{text:'SELPEN'},{text:'PESNEL'},{text:'NESPEL'},{text:'LENPES'}] },
      { target: 'TEMPAT', items: [{text:'TEMPAT'},{text:'PATTEM'},{text:'MATPET'},{text:'TEPMAT'},{text:'PETMAT'},{text:'TAMPET'}] },
      { target: 'BASKET', items: [{text:'BASKET'},{text:'KETBAS'},{text:'SABKET'},{text:'BESKAT'},{text:'KASBET'},{text:'TEKBAS'}] },
      { target: 'KAMBING', items: [{text:'KAMBING'},{text:'BINGKAM'},{text:'KABMING'},{text:'MAKBING'},{text:'KAMGINB'},{text:'BIMKANG'},{text:'NGAMBIK'}] },
      { target: 'KOMPUTER', items: [{text:'KOMPUTER'},{text:'PUTERKOM'},{text:'KOMTUPER'},{text:'MOKPUTER'},{text:'KOPMUTER'},{text:'TERKOMPU'},{text:'PUKOMTER'},{text:'KOMPUTRE'}] },
    ]),
  },
  // ── KONSTRUK 11: Baca & padan ayat mudah dengan gambar ──
  {
    id: 'baca-k11-ayat-gambar',
    title: 'Konstruk 11: Ayat & Gambar',
    emoji: '🗯️',
    mode: 'tilematch',
    objective: 'Padan ayat mudah dengan gambar yang betul.',
    reward: 'Ayat baca',
    rounds: makeRounds([
      { tiles: ['Budak makan', '🍽️', 'Budak tidur', '😴'] },
      { tiles: ['Kucing lari', '🐈', 'Burung terbang', '🐦'] },
      { tiles: ['Ibu memasak', '👩‍🍳', 'Bapa membaca', '📰', 'Adik bermain', '🧸'] },
      { tiles: ['Hujan turun', '🌧️', 'Matahari naik', '🌅', 'Bulan bersinar', '🌙'] },
      { tiles: ['Saya menulis', '✍️', 'Saya melukis', '🎨', 'Saya menyanyi', '🎤', 'Saya menari', '💃'] },
      { tiles: ['Ikan berenang', '🐟', 'Kuda berlari', '🐎', 'Arnab melompat', '🐇', 'Ular menjalar', '🐍'] },
      { tiles: ['Pokok tumbuh', '🌳', 'Bunga kembang', '🌸', 'Buah masak', '🍎', 'Daun gugur', '🍂', 'Air mengalir', '💧'] },
      { tiles: ['Murid belajar', '📚', 'Cikgu mengajar', '🧑‍🏫', 'Doktor merawat', '🩺', 'Polis menjaga', '👮', 'Petani bertani', '🌾'] },
      { tiles: ['Kereta laju', '🏎️', 'Kapal belayar', '⛵', 'Bas berhenti', '🚌', 'Kapal terbang', '✈️', 'Basikal pusing', '🚲', 'Keretapi jalan', '🚆'] },
      { tiles: ['Bayi menangis', '👶', 'Kanak gembira', '😄', 'Atuk berehat', '🧓', 'Abang bersukan', '⚽', 'Kakak membaca', '📖', 'Nenek memasak', '🍲'] },
    ]),
  },
  // ── KONSTRUK 1: Ingat huruf (memory) ──
  {
    id: 'baca-k1-memory-huruf',
    title: 'Konstruk 1: Ingatan Huruf',
    emoji: '🧠',
    mode: 'memory',
    objective: 'Padan kad huruf besar yang sama.',
    reward: 'Memory huruf',
    rounds: makeRounds([
      { pairs: [['A','A'],['B','B']] },
      { pairs: [['C','C'],['D','D']] },
      { pairs: [['E','E'],['F','F'],['G','G']] },
      { pairs: [['H','H'],['I','I'],['J','J']] },
      { pairs: [['K','K'],['L','L'],['M','M']] },
      { pairs: [['N','N'],['O','O'],['P','P']] },
      { pairs: [['B','B'],['D','D'],['P','P'],['Q','Q']] },
      { pairs: [['R','R'],['S','S'],['T','T'],['U','U']] },
      { pairs: [['V','V'],['W','W'],['X','X'],['Y','Y'],['Z','Z']] },
      { pairs: [['A','A'],['M','M'],['S','S'],['K','K'],['B','B']] },
    ]),
  },
  // ── KONSTRUK 2: Ingat suku kata terbuka (memory) ──
  {
    id: 'baca-k2-memory-suku',
    title: 'Konstruk 2: Ingatan Suku Kata',
    emoji: '🃏',
    mode: 'memory',
    objective: 'Padan kad suku kata terbuka yang sama.',
    reward: 'Memory suku',
    rounds: makeRounds([
      { pairs: [['BA','BA'],['BI','BI']] },
      { pairs: [['MA','MA'],['MU','MU']] },
      { pairs: [['KA','KA'],['KI','KI'],['KU','KU']] },
      { pairs: [['SA','SA'],['SI','SI'],['SU','SU']] },
      { pairs: [['LA','LA'],['LI','LI'],['LU','LU']] },
      { pairs: [['TA','TA'],['TI','TI'],['TU','TU']] },
      { pairs: [['NA','NA'],['NI','NI'],['NU','NU'],['NE','NE']] },
      { pairs: [['PA','PA'],['PI','PI'],['PU','PU'],['PO','PO']] },
      { pairs: [['GA','GA'],['GI','GI'],['GU','GU'],['GE','GE'],['GO','GO']] },
      { pairs: [['JA','JA'],['CA','CA'],['DA','DA'],['RA','RA'],['WA','WA']] },
    ]),
  },
  // ── KONSTRUK 3: Bina perkataan terbuka (huruf) ──
  {
    id: 'baca-k3-bina-huruf',
    title: 'Konstruk 3: Bina dari Huruf',
    emoji: '🔡',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan suku kata terbuka.',
    reward: 'Bina terbuka',
    rounds: makeRounds([
      { target: 'BATU', letters: ['B','A','T','U'] },
      { target: 'BUKU', letters: ['B','U','K','U'] },
      { target: 'KUDA', letters: ['K','U','D','A'] },
      { target: 'MEJA', letters: ['M','E','J','A'] },
      { target: 'SAPU', letters: ['S','A','P','U'] },
      { target: 'BOLA', letters: ['B','O','L','A'] },
      { target: 'CAWAN', letters: ['C','A','W','A','N'] },
      { target: 'KELAPA', letters: ['K','E','L','A','P','A'] },
      { target: 'KERETA', letters: ['K','E','R','E','T','A'] },
      { target: 'SEPATU', letters: ['S','E','P','A','T','U'] },
    ]),
  },
  // ── KONSTRUK 4: Surih suku kata tertutup ──
  {
    id: 'baca-k4-suku-tertutup-tile',
    title: 'Konstruk 4: Suku Kata Tertutup',
    emoji: '🔒',
    mode: 'tilematch',
    objective: 'Padan suku kata tertutup (KVK) yang sama.',
    reward: 'Tertutup match',
    rounds: makeRounds([
      { tiles: ['BAS', 'BAS', 'TIN', 'TIN'] },
      { tiles: ['CAT', 'CAT', 'TOP', 'TOP'] },
      { tiles: ['LAM', 'LAM', 'PUN', 'PUN', 'SET', 'SET'] },
      { tiles: ['KAN', 'KAN', 'BIL', 'BIL', 'TUK', 'TUK'] },
      { tiles: ['MAN', 'MAN', 'DOK', 'DOK', 'RIP', 'RIP', 'GAL', 'GAL'] },
      { tiles: ['SEN', 'SEN', 'POT', 'POT', 'JUM', 'JUM', 'KAS', 'KAS'] },
      { tiles: ['BAN', 'BAN', 'TUN', 'TUN', 'PEL', 'PEL', 'GIM', 'GIM', 'ROK', 'ROK'] },
      { tiles: ['MAT', 'MAT', 'KUN', 'KUN', 'SEL', 'SEL', 'PIT', 'PIT', 'GAS', 'GAS'] },
      { tiles: ['BEK', 'BEK', 'TUP', 'TUP', 'LON', 'LON', 'DAS', 'DAS', 'RUM', 'RUM', 'KAM', 'KAM'] },
      { tiles: ['SOK', 'SOK', 'TAN', 'TAN', 'PIL', 'PIL', 'MUK', 'MUK', 'JOL', 'JOL', 'BES', 'BES'] },
    ]),
  },
  // ── KONSTRUK 9: Digraf & konsonan bergabung ──
  {
    id: 'baca-k9-digraf',
    title: 'Konstruk 9: Digraf (sy, kh, gh)',
    emoji: '🔤',
    mode: 'hidden_object',
    objective: 'Cari perkataan dengan digraf yang betul.',
    reward: 'Digraf badge',
    rounds: makeRounds([
      { target: 'SYUKUR', items: [{text:'SYUKUR'},{text:'SUKUR'},{text:'SIUKUR'}] },
      { target: 'KHEMAH', items: [{text:'KHEMAH'},{text:'KEMAH'},{text:'KHAMAH'}] },
      { target: 'GHAIB', items: [{text:'GHAIB'},{text:'GAIB'},{text:'GHIAB'},{text:'GHABI'}] },
      { target: 'NYAMUK', items: [{text:'NYAMUK'},{text:'NAMUK'},{text:'NYAUMK'},{text:'MANYUK'}] },
      { target: 'SYARIKAT', items: [{text:'SYARIKAT'},{text:'SARIKAT'},{text:'SYAIRKAT'},{text:'SYARITAK'},{text:'KATSYARI'}] },
      { target: 'KHIDMAT', items: [{text:'KHIDMAT'},{text:'KIDMAT'},{text:'KHIMDAT'},{text:'KHADMIT'},{text:'MATKHID'}] },
      { target: 'NYANYI', items: [{text:'NYANYI'},{text:'NANYI'},{text:'NYAINY'},{text:'YANYIN'},{text:'NYINYA'},{text:'ANYNYI'}] },
      { target: 'GHARIB', items: [{text:'GHARIB'},{text:'GARIB'},{text:'GHAIRB'},{text:'GHABIR'},{text:'RIBGHA'},{text:'GHARBI'}] },
      { target: 'SYAITAN', items: [{text:'SYAITAN'},{text:'SAITAN'},{text:'SYAINTA'},{text:'SYATIAN'},{text:'TANSYAI'},{text:'SYANITA'},{text:'NAITSYA'}] },
      { target: 'KHAZANAH', items: [{text:'KHAZANAH'},{text:'KAZANAH'},{text:'KHANAZAH'},{text:'KHAZAHAN'},{text:'NAHKHAZA'},{text:'ZAKHANAH'},{text:'KHAZNAAH'},{text:'HKAZANAH'}] },
    ]),
  },
  // ── KONSTRUK 10: Baca perkataan berimbuhan ──
  {
    id: 'baca-k10-imbuhan-cari',
    title: 'Konstruk 10: Perkataan Berimbuhan',
    emoji: '🔗',
    mode: 'tilematch',
    objective: 'Padan perkataan berimbuhan dengan maksud.',
    reward: 'Imbuhan baca',
    rounds: makeRounds([
      { tiles: ['Bermain', '🧸', 'Membaca', '📖'] },
      { tiles: ['Berlari', '🏃', 'Melukis', '🎨'] },
      { tiles: ['Memasak', '🍳', 'Menulis', '✍️', 'Menyanyi', '🎤'] },
      { tiles: ['Berenang', '🏊', 'Menari', '💃', 'Memancing', '🎣'] },
      { tiles: ['Makanan', '🍱', 'Minuman', '🥤', 'Mainan', '🪀', 'Pakaian', '👕'] },
      { tiles: ['Pelukis', '🧑‍🎨', 'Penyanyi', '🎙️', 'Pemandu', '🚕', 'Pekebun', '🧑‍🌾'] },
      { tiles: ['Bersih', '🧼', 'Kebersihan', '🧹', 'Membersih', '🧽', 'Pembersih', '🪣', 'Berhias', '💄'] },
      { tiles: ['Belajar', '📚', 'Pelajar', '🧑‍🎓', 'Pelajaran', '📝', 'Mengajar', '🧑‍🏫', 'Pengajaran', '🎓'] },
      { tiles: ['Bertani', '🌾', 'Petani', '👨‍🌾', 'Pertanian', '🚜', 'Berniaga', '🛒', 'Peniaga', '💼', 'Perniagaan', '🏪'] },
      { tiles: ['Berbasikal', '🚲', 'Bermotor', '🏍️', 'Berkereta', '🚗', 'Berperahu', '🛶', 'Berbas', '🚌', 'Berkapal', '🚢'] },
    ]),
  },
  // ── KONSTRUK 3: Eja perkataan ikut huruf (sequence) ──
  {
    id: 'baca-k3-eja-urutan',
    title: 'Konstruk 3: Eja Ikut Urutan',
    emoji: '🔤',
    mode: 'sequence',
    objective: 'Susun huruf ikut ejaan perkataan yang betul.',
    reward: 'Eja star',
    rounds: makeRounds([
      { items: ['B','A','T','U'], answer: ['B','A','T','U'] },
      { items: ['B','U','K','U'], answer: ['B','U','K','U'] },
      { items: ['K','U','D','A'], answer: ['K','U','D','A'] },
      { items: ['B','O','L','A'], answer: ['B','O','L','A'] },
      { items: ['M','E','J','A'], answer: ['M','E','J','A'] },
      { items: ['S','A','P','U'], answer: ['S','A','P','U'] },
      { items: ['R','O','T','I'], answer: ['R','O','T','I'] },
      { items: ['C','A','W','A','N'], answer: ['C','A','W','A','N'] },
      { items: ['K','E','L','A','P','A'], answer: ['K','E','L','A','P','A'] },
      { items: ['K','E','R','E','T','A'], answer: ['K','E','R','E','T','A'] },
    ]),
  },
  // ── KONSTRUK 11: Baca & taip perkataan ──
  {
    id: 'baca-k11-baca-taip',
    title: 'Konstruk 11: Baca & Taip',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Baca perkataan & taip semula dengan betul.',
    reward: 'Baca taip',
    rounds: makeRounds([
      { prompt: 'Baca & taip: BUKU', target: 'buku' },
      { prompt: 'Baca & taip: KASUT', target: 'kasut' },
      { prompt: 'Baca & taip: RUMAH', target: 'rumah' },
      { prompt: 'Baca & taip: BUNGA', target: 'bunga' },
      { prompt: 'Baca & taip: PAYUNG', target: 'payung' },
      { prompt: 'Baca & taip: HARIMAU', target: 'harimau' },
      { prompt: 'Baca & taip: PANTAI', target: 'pantai' },
      { prompt: 'Baca & taip: KOMPUTER', target: 'komputer' },
      { prompt: 'Baca & taip: BERMAIN', target: 'bermain' },
      { prompt: 'Baca & taip: PERMAINAN', target: 'permainan' },
    ]),
  },
  // ── KONSTRUK 12: Faham ayat — pilih jawapan (story) ──
  {
    id: 'baca-k12-faham-ayat',
    title: 'Konstruk 12: Faham Bacaan',
    emoji: '📚',
    mode: 'story',
    objective: 'Baca ayat & pilih jawapan yang betul.',
    reward: 'Faham bacaan',
    rounds: makeRounds([
      { scenes: [{ text: 'Ali makan epal. Apa Ali makan?', choices: ['Epal','Nasi','Roti'], answer: 0 }] },
      { scenes: [{ text: 'Kucing itu hitam. Apa warna kucing?', choices: ['Putih','Hitam','Merah'], answer: 1 }] },
      { scenes: [{ text: 'Siti pergi ke sekolah. Siti pergi ke mana?', choices: ['Pasar','Rumah','Sekolah'], answer: 2 }] },
      { scenes: [{ text: 'Burung terbang tinggi. Burung buat apa?', choices: ['Terbang','Berenang','Berlari'], answer: 0 }] },
      { scenes: [{ text: 'Ibu memasak nasi di dapur. Ibu memasak apa?', choices: ['Roti','Nasi','Kuih'], answer: 1 }] },
      { scenes: [{ text: 'Abang bermain bola di padang. Abang main di mana?', choices: ['Bilik','Dapur','Padang'], answer: 2 }] },
      { scenes: [{ text: 'Hari hujan, Aminah bawa payung. Apa Aminah bawa?', choices: ['Payung','Beg','Topi'], answer: 0 }] },
      { scenes: [{ text: 'Adik tidur pada waktu malam. Bila adik tidur?', choices: ['Pagi','Malam','Petang'], answer: 1 }] },
      { scenes: [{ text: 'Petani menanam padi di sawah. Apa petani tanam?', choices: ['Jagung','Sayur','Padi'], answer: 2 }] },
      { scenes: [{ text: 'Doktor merawat pesakit di hospital. Siapa rawat pesakit?', choices: ['Doktor','Cikgu','Polis'], answer: 0 }] },
    ]),
  },
];