// 🔢 MENGIRA — disusun ikut Konstruk LINUS Numerasi rasmi.
// K1 pra-nombor & kenal angka → K2 membilang → K3 nilai nombor → K4 seriasi →
// K5 mata wang → K6 waktu → K7 operasi asas (tambah/tolak) → K11 aplikasi harian.
// Guna pelbagai mekanik mini-game (MiniGameModeRenderer).
import { makeRounds } from '../miniGames/_helpers.js';

export const mengiraGames = [
  // ── KONSTRUK 1: Pra-nombor & mengenal angka ──
  {
    id: 'kira-k1-kenal-angka',
    title: 'Konstruk 1: Kenal Angka',
    emoji: '1️⃣',
    mode: 'hidden_object',
    objective: 'Cari angka yang betul (0–20).',
    reward: 'Number badge',
    rounds: makeRounds([
      { target: '1', items: [{text:'1',value:'1'},{text:'2',value:'2'},{text:'3',value:'3'}] },
      { target: '4', items: [{text:'4',value:'4'},{text:'5',value:'5'},{text:'6',value:'6'}] },
      { target: '7', items: [{text:'7',value:'7'},{text:'8',value:'8'},{text:'9',value:'9'},{text:'10',value:'10'}] },
      { target: '5', items: [{text:'5',value:'5'},{text:'2',value:'2'},{text:'8',value:'8'},{text:'6',value:'6'}] },
      { target: '9', items: [{text:'9',value:'9'},{text:'6',value:'6'},{text:'3',value:'3'},{text:'8',value:'8'},{text:'4',value:'4'}] },
      { target: '10', items: [{text:'10',value:'10'},{text:'1',value:'1'},{text:'7',value:'7'},{text:'4',value:'4'},{text:'6',value:'6'}] },
      { target: '8', items: [{text:'8',value:'8'},{text:'3',value:'3'},{text:'6',value:'6'},{text:'9',value:'9'},{text:'2',value:'2'},{text:'5',value:'5'}] },
      { target: '13', items: [{text:'13',value:'13'},{text:'31',value:'31'},{text:'12',value:'12'},{text:'30',value:'30'},{text:'3',value:'3'},{text:'11',value:'11'}] },
      { target: '15', items: [{text:'15',value:'15'},{text:'51',value:'51'},{text:'14',value:'14'},{text:'50',value:'50'},{text:'5',value:'5'},{text:'16',value:'16'},{text:'13',value:'13'}] },
      { target: '20', items: [{text:'20',value:'20'},{text:'2',value:'2'},{text:'12',value:'12'},{text:'22',value:'22'},{text:'10',value:'10'},{text:'21',value:'21'},{text:'30',value:'30'},{text:'18',value:'18'}] },
    ]),
  },
  // ── KONSTRUK 2: Membilang objek ──
  {
    id: 'kira-k2-membilang',
    title: 'Konstruk 2: Membilang',
    emoji: '🍎',
    mode: 'typing_challenge',
    objective: 'Bilang bilangan objek & taip jumlahnya.',
    reward: 'Counting star',
    rounds: makeRounds([
      { prompt: '🍎🍎 — Berapa epal?', target: '2' },
      { prompt: '⭐⭐⭐ — Berapa bintang?', target: '3' },
      { prompt: '🐟🐟🐟🐟 — Berapa ikan?', target: '4' },
      { prompt: '🎈🎈🎈🎈🎈 — Berapa belon?', target: '5' },
      { prompt: '🍌🍌🍌🍌🍌🍌 — Berapa pisang?', target: '6' },
      { prompt: '🌸🌸🌸🌸🌸🌸🌸 — Berapa bunga?', target: '7' },
      { prompt: '🚗🚗🚗🚗🚗🚗🚗🚗 — Berapa kereta?', target: '8' },
      { prompt: '🐱🐱🐱🐱🐱🐱🐱🐱🐱 — Berapa kucing?', target: '9' },
      { prompt: '🎁🎁🎁🎁🎁🎁🎁🎁🎁🎁 — Berapa hadiah?', target: '10' },
      { prompt: '⚽⚽⚽⚽⚽⚽ ➕ ⚽⚽⚽⚽⚽⚽ — Jumlah bola?', target: '12' },
    ]),
  },
  // ── KONSTRUK 3: Memahami nilai nombor (ganjil/genap, besar/kecil) ──
  {
    id: 'kira-k3-nilai-nombor',
    title: 'Konstruk 3: Nilai Nombor',
    emoji: '⚖️',
    mode: 'swipe_select',
    objective: 'Kelaskan nombor — besar atau kecil, ganjil atau genap.',
    reward: 'Compare badge',
    rounds: makeRounds([
      { groups: ['Kecil', 'Besar'], items: [
        { text: '2', group: 'Kecil' }, { text: '9', group: 'Besar' }, { text: '1', group: 'Kecil' }, { text: '8', group: 'Besar' },
      ] },
      { groups: ['Kecil', 'Besar'], items: [
        { text: '3', group: 'Kecil' }, { text: '7', group: 'Besar' }, { text: '10', group: 'Besar' }, { text: '4', group: 'Kecil' },
      ] },
      { groups: ['Kurang 5', 'Lebih 5'], items: [
        { text: '2', group: 'Kurang 5' }, { text: '8', group: 'Lebih 5' }, { text: '6', group: 'Lebih 5' }, { text: '3', group: 'Kurang 5' },
      ] },
      { groups: ['Kurang 10', 'Lebih 10'], items: [
        { text: '7', group: 'Kurang 10' }, { text: '15', group: 'Lebih 10' }, { text: '12', group: 'Lebih 10' }, { text: '4', group: 'Kurang 10' },
      ] },
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '2', group: 'Genap' }, { text: '3', group: 'Ganjil' }, { text: '4', group: 'Genap' }, { text: '5', group: 'Ganjil' },
      ] },
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '6', group: 'Genap' }, { text: '7', group: 'Ganjil' }, { text: '8', group: 'Genap' }, { text: '9', group: 'Ganjil' },
      ] },
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '10', group: 'Genap' }, { text: '11', group: 'Ganjil' }, { text: '12', group: 'Genap' }, { text: '13', group: 'Ganjil' }, { text: '14', group: 'Genap' },
      ] },
      { groups: ['Kurang 10', 'Lebih 10'], items: [
        { text: '8', group: 'Kurang 10' }, { text: '14', group: 'Lebih 10' }, { text: '9', group: 'Kurang 10' }, { text: '20', group: 'Lebih 10' }, { text: '6', group: 'Kurang 10' }, { text: '18', group: 'Lebih 10' },
      ] },
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '15', group: 'Ganjil' }, { text: '16', group: 'Genap' }, { text: '17', group: 'Ganjil' }, { text: '18', group: 'Genap' }, { text: '19', group: 'Ganjil' }, { text: '20', group: 'Genap' },
      ] },
      { groups: ['Kurang 50', 'Lebih 50'], items: [
        { text: '30', group: 'Kurang 50' }, { text: '70', group: 'Lebih 50' }, { text: '45', group: 'Kurang 50' }, { text: '80', group: 'Lebih 50' }, { text: '25', group: 'Kurang 50' }, { text: '60', group: 'Lebih 50' }, { text: '90', group: 'Lebih 50' },
      ] },
    ]),
  },
  // ── KONSTRUK 4: Seriasi (susun nombor menaik/menurun & corak) ──
  {
    id: 'kira-k4-seriasi',
    title: 'Konstruk 4: Susun Seriasi',
    emoji: '🔁',
    mode: 'sequence',
    objective: 'Susun nombor ikut urutan & corak.',
    reward: 'Pattern brain',
    rounds: makeRounds([
      { items: ['1','2','3'], answer: ['1','2','3'] },
      { items: ['2','4','6'], answer: ['2','4','6'] },
      { items: ['1','2','3','4'], answer: ['1','2','3','4'] },
      { items: ['5','10','15','20'], answer: ['5','10','15','20'] },
      { items: ['2','4','6','8','10'], answer: ['2','4','6','8','10'] },
      { items: ['10','9','8','7','6'], answer: ['10','9','8','7','6'] },
      { items: ['1','3','5','7','9'], answer: ['1','3','5','7','9'] },
      { items: ['3','6','9','12','15'], answer: ['3','6','9','12','15'] },
      { items: ['10','20','30','40','50','60'], answer: ['10','20','30','40','50','60'] },
      { items: ['100','90','80','70','60','50'], answer: ['100','90','80','70','60','50'] },
    ]),
  },
  // ── KONSTRUK 5: Mengenal mata wang Malaysia ──
  {
    id: 'kira-k5-mata-wang',
    title: 'Konstruk 5: Mata Wang Malaysia',
    emoji: '💰',
    mode: 'typing_challenge',
    objective: 'Kira nilai duit syiling & not RM.',
    reward: 'Duit badge',
    rounds: makeRounds([
      { prompt: '🪙 10 sen + 🪙 10 sen = ? sen', target: '20' },
      { prompt: '🪙 20 sen + 🪙 5 sen = ? sen', target: '25' },
      { prompt: '🪙 50 sen + 🪙 50 sen = RM ?', target: '1' },
      { prompt: '💵 RM1 + 💵 RM1 = RM ?', target: '2' },
      { prompt: '💵 RM5 + 💵 RM5 = RM ?', target: '10' },
      { prompt: '💵 RM10 + 💵 RM5 = RM ?', target: '15' },
      { prompt: '💵 RM2 + 💵 RM2 + 💵 RM1 = RM ?', target: '5' },
      { prompt: '💵 RM20 - 💵 RM5 = RM ?', target: '15' },
      { prompt: 'Beli aiskrim RM3, bayar RM5. Baki = RM ?', target: '2' },
      { prompt: 'Beli buku RM12, bayar RM20. Baki = RM ?', target: '8' },
    ]),
  },
  // ── KONSTRUK 6: Menyatakan waktu ──
  {
    id: 'kira-k6-waktu',
    title: 'Konstruk 6: Menyatakan Waktu',
    emoji: '🕐',
    mode: 'hidden_object',
    objective: 'Pilih waktu yang betul ikut jam.',
    reward: 'Jam badge',
    rounds: makeRounds([
      { target: '🕐 1:00', items: [{text:'🕐 1:00'},{text:'🕒 3:00'},{text:'🕔 5:00'}] },
      { target: '🕕 6:00', items: [{text:'🕕 6:00'},{text:'🕗 8:00'},{text:'🕙 10:00'}] },
      { target: '🕛 12:00', items: [{text:'🕛 12:00'},{text:'🕘 9:00'},{text:'🕓 4:00'},{text:'🕖 7:00'}] },
      { target: 'Pagi 🌅', items: [{text:'Pagi 🌅'},{text:'Malam 🌙'},{text:'Tengah hari ☀️'}] },
      { target: 'Malam 🌙', items: [{text:'Malam 🌙'},{text:'Pagi 🌅'},{text:'Petang 🌇'},{text:'Tengah hari ☀️'}] },
      { target: 'Sarapan 🍳', items: [{text:'Sarapan 🍳'},{text:'Makan malam 🍽️'},{text:'Tidur 😴'},{text:'Mandi 🚿'}] },
      { target: '🕞 3:30', items: [{text:'🕞 3:30'},{text:'🕒 3:00'},{text:'🕟 4:30'},{text:'🕝 2:30'},{text:'🕓 4:00'}] },
      { target: '7 hari = 1 minggu', items: [{text:'7 hari = 1 minggu'},{text:'5 hari = 1 minggu'},{text:'10 hari = 1 minggu'},{text:'30 hari = 1 minggu'}] },
      { target: '12 bulan = 1 tahun', items: [{text:'12 bulan = 1 tahun'},{text:'10 bulan = 1 tahun'},{text:'7 bulan = 1 tahun'},{text:'24 bulan = 1 tahun'},{text:'6 bulan = 1 tahun'}] },
      { target: '60 minit = 1 jam', items: [{text:'60 minit = 1 jam'},{text:'30 minit = 1 jam'},{text:'100 minit = 1 jam'},{text:'24 minit = 1 jam'},{text:'12 minit = 1 jam'}] },
    ]),
  },
  // ── KONSTRUK 7: Operasi asas — Tambah ──
  {
    id: 'kira-k7-tambah',
    title: 'Konstruk 7: Tambah',
    emoji: '➕',
    mode: 'typing_challenge',
    objective: 'Selesaikan operasi tambah.',
    reward: 'Plus master',
    rounds: makeRounds([
      { prompt: '1 + 1 = ?', target: '2' },
      { prompt: '2 + 1 = ?', target: '3' },
      { prompt: '2 + 3 = ?', target: '5' },
      { prompt: '4 + 3 = ?', target: '7' },
      { prompt: '5 + 4 = ?', target: '9' },
      { prompt: '6 + 4 = ?', target: '10' },
      { prompt: '7 + 5 = ?', target: '12' },
      { prompt: '8 + 6 = ?', target: '14' },
      { prompt: '9 + 8 = ?', target: '17' },
      { prompt: '12 + 9 = ?', target: '21' },
    ]),
  },
  // ── KONSTRUK 7: Operasi asas — Tolak ──
  {
    id: 'kira-k7-tolak',
    title: 'Konstruk 7: Tolak',
    emoji: '➖',
    mode: 'typing_challenge',
    objective: 'Selesaikan operasi tolak.',
    reward: 'Minus master',
    rounds: makeRounds([
      { prompt: '2 - 1 = ?', target: '1' },
      { prompt: '3 - 1 = ?', target: '2' },
      { prompt: '5 - 2 = ?', target: '3' },
      { prompt: '7 - 3 = ?', target: '4' },
      { prompt: '9 - 4 = ?', target: '5' },
      { prompt: '10 - 4 = ?', target: '6' },
      { prompt: '12 - 5 = ?', target: '7' },
      { prompt: '15 - 7 = ?', target: '8' },
      { prompt: '18 - 9 = ?', target: '9' },
      { prompt: '20 - 8 = ?', target: '12' },
    ]),
  },
  // ── KONSTRUK 11: Aplikasi harian (masalah perkataan, nombor bulat) ──
  {
    id: 'kira-k11-aplikasi',
    title: 'Konstruk 11: Masalah Harian',
    emoji: '🧠',
    mode: 'typing_challenge',
    objective: 'Selesaikan masalah matematik harian.',
    reward: 'Problem solver',
    rounds: makeRounds([
      { prompt: 'Ali ada 3 gula-gula, beli 2 lagi. Jumlah?', target: '5' },
      { prompt: 'Ada 6 burung, 2 terbang pergi. Tinggal?', target: '4' },
      { prompt: 'Siti ada 4 belon, kakak beri 3. Jumlah?', target: '7' },
      { prompt: '10 biji telur, pecah 3. Tinggal?', target: '7' },
      { prompt: '5 murid + 5 murid masuk kelas. Jumlah?', target: '10' },
      { prompt: 'Ada 12 epal, makan 4. Tinggal?', target: '8' },
      { prompt: '3 kotak, setiap kotak 2 bola. Jumlah bola?', target: '6' },
      { prompt: '15 pelajar, 6 perempuan. Berapa lelaki?', target: '9' },
      { prompt: 'Beli 4 pen RM2 setiap satu. Jumlah bayar RM?', target: '8' },
      { prompt: '20 kerusi, susun 5 satu baris. Berapa baris?', target: '4' },
    ]),
  },
  // ── KONSTRUK 1: Ingat angka (memory) ──
  {
    id: 'kira-k1-memory-angka',
    title: 'Konstruk 1: Ingatan Angka',
    emoji: '🧠',
    mode: 'memory',
    objective: 'Padan kad angka yang sama.',
    reward: 'Memory angka',
    rounds: makeRounds([
      { pairs: [['1','1'],['2','2']] },
      { pairs: [['3','3'],['4','4']] },
      { pairs: [['5','5'],['6','6'],['7','7']] },
      { pairs: [['8','8'],['9','9'],['10','10']] },
      { pairs: [['2','2'],['4','4'],['6','6']] },
      { pairs: [['1','1'],['3','3'],['5','5']] },
      { pairs: [['11','11'],['12','12'],['13','13'],['14','14']] },
      { pairs: [['15','15'],['16','16'],['17','17'],['18','18']] },
      { pairs: [['10','10'],['20','20'],['30','30'],['40','40'],['50','50']] },
      { pairs: [['6','6'],['12','12'],['18','18'],['24','24'],['30','30']] },
    ]),
  },
  // ── KONSTRUK 2: Padan bilangan dengan angka (tilematch) ──
  {
    id: 'kira-k2-padan-bilangan',
    title: 'Konstruk 2: Padan Bilangan',
    emoji: '🔢',
    mode: 'tilematch',
    objective: 'Padan kumpulan objek dengan angka betul.',
    reward: 'Padan bilang',
    rounds: makeRounds([
      { tiles: ['🍎', '1', '🍎🍎', '2'] },
      { tiles: ['⭐⭐⭐', '3', '🐟🐟🐟🐟', '4'] },
      { tiles: ['🎈🎈', '2', '🍌🍌🍌🍌🍌', '5', '🚗🚗🚗', '3'] },
      { tiles: ['🐱', '1', '🌸🌸🌸🌸', '4', '🎁🎁🎁🎁🎁🎁', '6'] },
      { tiles: ['⚽⚽⚽⚽⚽', '5', '🐶🐶', '2', '🦋🦋🦋🦋🦋🦋🦋', '7', '🍪🍪🍪', '3'] },
      { tiles: ['🌟', '1', '🍓🍓🍓🍓', '4', '🐰🐰🐰🐰🐰🐰', '6', '🎵🎵🎵🎵🎵🎵🎵🎵', '8'] },
      { tiles: ['🐝🐝🐝', '3', '🍇🍇🍇🍇🍇', '5', '🐧🐧', '2', '🌻🌻🌻🌻🌻🌻🌻', '7', '🎯🎯🎯🎯', '4'] },
      { tiles: ['🍉', '1', '🐠🐠🐠🐠🐠🐠', '6', '🌈🌈🌈', '3', '🦄🦄🦄🦄🦄🦄🦄🦄', '8', '🎂🎂🎂🎂🎂', '5'] },
      { tiles: ['🍒🍒', '2', '🐸🐸🐸🐸', '4', '🌺🌺🌺🌺🌺🌺', '6', '🐢🐢🐢🐢🐢🐢🐢🐢', '8', '⚡⚡⚡', '3', '🎨🎨🎨🎨🎨', '5'] },
      { tiles: ['9', '🌟🌟🌟🌟🌟🌟🌟🌟🌟', '10', '🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭', '7', '🐞🐞🐞🐞🐞🐞🐞', '5', '🎪🎪🎪🎪🎪', '6', '🎈🎈🎈🎈🎈🎈'] },
    ]),
  },
  // ── KONSTRUK 3: Banding nombor (story) ──
  {
    id: 'kira-k3-banding',
    title: 'Konstruk 3: Banding Nombor',
    emoji: '⚖️',
    mode: 'story',
    objective: 'Pilih nombor yang lebih besar atau lebih kecil.',
    reward: 'Banding badge',
    rounds: makeRounds([
      { scenes: [{ text: 'Mana lebih BESAR?', choices: ['3','7','1'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih KECIL?', choices: ['8','2','5'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih BESAR?', choices: ['4','9','6'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih KECIL?', choices: ['10','3','7'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih BESAR?', choices: ['12','8','5'], answer: 0 }] },
      { scenes: [{ text: 'Mana lebih KECIL?', choices: ['15','20','6'], answer: 2 }] },
      { scenes: [{ text: 'Mana lebih BESAR?', choices: ['18','25','11'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih KECIL?', choices: ['30','14','22'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih BESAR?', choices: ['45','38','50'], answer: 2 }] },
      { scenes: [{ text: 'Mana lebih KECIL?', choices: ['60','75','55'], answer: 2 }] },
    ]),
  },
  // ── KONSTRUK 4: Cari nombor hilang dalam corak (story) ──
  {
    id: 'kira-k4-nombor-hilang',
    title: 'Konstruk 4: Nombor Hilang',
    emoji: '🔍',
    mode: 'story',
    objective: 'Cari nombor yang hilang dalam urutan.',
    reward: 'Corak badge',
    rounds: makeRounds([
      { scenes: [{ text: '1, 2, ?, 4', choices: ['3','5','6'], answer: 0 }] },
      { scenes: [{ text: '2, 4, ?, 8', choices: ['5','6','7'], answer: 1 }] },
      { scenes: [{ text: '5, ?, 15, 20', choices: ['10','12','8'], answer: 0 }] },
      { scenes: [{ text: '10, 9, ?, 7', choices: ['6','8','5'], answer: 1 }] },
      { scenes: [{ text: '1, 3, 5, ?', choices: ['6','7','8'], answer: 1 }] },
      { scenes: [{ text: '3, 6, ?, 12', choices: ['9','10','8'], answer: 0 }] },
      { scenes: [{ text: '20, ?, 40, 50', choices: ['25','30','35'], answer: 1 }] },
      { scenes: [{ text: '2, 4, 6, ?, 10', choices: ['7','8','9'], answer: 1 }] },
      { scenes: [{ text: '100, 90, ?, 70', choices: ['85','80','75'], answer: 1 }] },
      { scenes: [{ text: '5, 10, 15, ?, 25', choices: ['18','20','22'], answer: 1 }] },
    ]),
  },
  // ── KONSTRUK 5: Padan duit dengan nilai (tilematch) ──
  {
    id: 'kira-k5-padan-duit',
    title: 'Konstruk 5: Padan Nilai Duit',
    emoji: '💵',
    mode: 'tilematch',
    objective: 'Padan duit dengan nilai yang betul.',
    reward: 'Duit padan',
    rounds: makeRounds([
      { tiles: ['🪙', '10 sen', '💵', 'RM1'] },
      { tiles: ['🪙🪙', '20 sen', '💵💵', 'RM2'] },
      { tiles: ['🪙 50 sen', 'Setengah RM', '💵 RM5', 'Lima ringgit', '💵 RM10', 'Sepuluh ringgit'] },
      { tiles: ['RM1', '💵', 'RM20', '💴', 'RM50', '💶'] },
      { tiles: ['5 sen', '🪙', 'RM1', '💵', 'RM5', '💴', 'RM10', '💶'] },
      { tiles: ['2 keping RM5', 'RM10', '5 keping RM2', 'RM10', '10 keping RM1', 'RM10', '20 keping 50 sen', 'RM10'] },
      { tiles: ['RM2 + RM3', 'RM5', 'RM10 + RM5', 'RM15', 'RM1 + RM1', 'RM2', 'RM20 + RM10', 'RM30', 'RM5 + RM5', 'RM10'] },
      { tiles: ['Beli RM3 bayar RM5', 'Baki RM2', 'Beli RM7 bayar RM10', 'Baki RM3', 'Beli RM12 bayar RM20', 'Baki RM8', 'Beli RM15 bayar RM20', 'Baki RM5', 'Beli RM8 bayar RM10', 'Baki RM2'] },
      { tiles: ['10 sen', '🪙', '20 sen', '🪙🪙', '50 sen', '🪙🪙🪙🪙🪙', 'RM1', '💵', 'RM5', '💴', 'RM10', '💶'] },
      { tiles: ['RM4', '💵💵💵💵', 'RM6', '💵💵💵💵💵💵', 'RM8', '💵×8', 'RM3', '💵💵💵', 'RM9', '💵×9', 'RM7', '💵×7'] },
    ]),
  },
  // ── KONSTRUK 6: Padan aktiviti dengan waktu (tilematch) ──
  {
    id: 'kira-k6-padan-waktu',
    title: 'Konstruk 6: Padan Waktu',
    emoji: '🕐',
    mode: 'tilematch',
    objective: 'Padan aktiviti harian dengan waktu yang sesuai.',
    reward: 'Waktu padan',
    rounds: makeRounds([
      { tiles: ['Sarapan', '🌅 Pagi', 'Tidur', '🌙 Malam'] },
      { tiles: ['Bangun', '🌅', 'Makan malam', '🌃'] },
      { tiles: ['Ke sekolah', '🌅 Pagi', 'Balik sekolah', '🌇 Petang', 'Solat Isyak', '🌙 Malam'] },
      { tiles: ['🕐 1:00', 'Pukul satu', '🕕 6:00', 'Pukul enam', '🕘 9:00', 'Pukul sembilan'] },
      { tiles: ['7 hari', '1 minggu', '12 bulan', '1 tahun', '60 minit', '1 jam', '30 hari', '1 bulan'] },
      { tiles: ['Senaman pagi', '🌅', 'Makan tengah hari', '☀️', 'Mandi petang', '🌇', 'Baca buku malam', '🌙'] },
      { tiles: ['🕒 3:00', 'Tiga', '🕗 8:00', 'Lapan', '🕛 12:00', 'Dua belas', '🕔 5:00', 'Lima', '🕙 10:00', 'Sepuluh'] },
      { tiles: ['Isnin', 'Hari 1', 'Selasa', 'Hari 2', 'Rabu', 'Hari 3', 'Khamis', 'Hari 4', 'Jumaat', 'Hari 5'] },
      { tiles: ['Januari', 'Bulan 1', 'April', 'Bulan 4', 'Julai', 'Bulan 7', 'Oktober', 'Bulan 10', 'Disember', 'Bulan 12'] },
      { tiles: ['Semalam', 'Lepas', 'Hari ini', 'Sekarang', 'Esok', 'Depan', 'Pagi', '🌅', 'Malam', '🌙', 'Petang', '🌇'] },
    ]),
  },
  // ── KONSTRUK 7: Tambah (story bergambar) ──
  {
    id: 'kira-k7-tambah-gambar',
    title: 'Konstruk 7: Tambah Bergambar',
    emoji: '➕',
    mode: 'story',
    objective: 'Kira jumlah objek & pilih jawapan.',
    reward: 'Tambah gambar',
    rounds: makeRounds([
      { scenes: [{ text: '🍎 ➕ 🍎 = ?', choices: ['1','2','3'], answer: 1 }] },
      { scenes: [{ text: '⭐⭐ ➕ ⭐ = ?', choices: ['2','3','4'], answer: 1 }] },
      { scenes: [{ text: '🐟🐟 ➕ 🐟🐟 = ?', choices: ['3','4','5'], answer: 1 }] },
      { scenes: [{ text: '🎈🎈🎈 ➕ 🎈🎈 = ?', choices: ['4','5','6'], answer: 1 }] },
      { scenes: [{ text: '🍌🍌🍌 ➕ 🍌🍌🍌 = ?', choices: ['5','6','7'], answer: 1 }] },
      { scenes: [{ text: '🚗🚗🚗🚗 ➕ 🚗🚗🚗 = ?', choices: ['6','7','8'], answer: 1 }] },
      { scenes: [{ text: '🐱🐱🐱🐱🐱 ➕ 🐱🐱🐱 = ?', choices: ['7','8','9'], answer: 1 }] },
      { scenes: [{ text: '🎁🎁🎁🎁🎁 ➕ 🎁🎁🎁🎁 = ?', choices: ['8','9','10'], answer: 1 }] },
      { scenes: [{ text: '⚽×6 ➕ ⚽×5 = ?', choices: ['10','11','12'], answer: 1 }] },
      { scenes: [{ text: '🌸×8 ➕ 🌸×6 = ?', choices: ['13','14','15'], answer: 1 }] },
    ]),
  },
  // ── KONSTRUK 7: Tolak (story bergambar) ──
  {
    id: 'kira-k7-tolak-gambar',
    title: 'Konstruk 7: Tolak Bergambar',
    emoji: '➖',
    mode: 'story',
    objective: 'Kira baki objek & pilih jawapan.',
    reward: 'Tolak gambar',
    rounds: makeRounds([
      { scenes: [{ text: '🍎🍎 ➖ 🍎 = ?', choices: ['1','2','0'], answer: 0 }] },
      { scenes: [{ text: '⭐⭐⭐ ➖ ⭐ = ?', choices: ['1','2','3'], answer: 1 }] },
      { scenes: [{ text: '🐟🐟🐟🐟 ➖ 🐟🐟 = ?', choices: ['1','2','3'], answer: 1 }] },
      { scenes: [{ text: '🎈🎈🎈🎈🎈 ➖ 🎈🎈 = ?', choices: ['2','3','4'], answer: 1 }] },
      { scenes: [{ text: '🍌×6 ➖ 🍌×2 = ?', choices: ['3','4','5'], answer: 1 }] },
      { scenes: [{ text: '🚗×7 ➖ 🚗×3 = ?', choices: ['3','4','5'], answer: 1 }] },
      { scenes: [{ text: '🐱×8 ➖ 🐱×3 = ?', choices: ['4','5','6'], answer: 1 }] },
      { scenes: [{ text: '🎁×9 ➖ 🎁×4 = ?', choices: ['4','5','6'], answer: 1 }] },
      { scenes: [{ text: '⚽×10 ➖ ⚽×4 = ?', choices: ['5','6','7'], answer: 1 }] },
      { scenes: [{ text: '🌸×12 ➖ 🌸×5 = ?', choices: ['6','7','8'], answer: 1 }] },
    ]),
  },
  // ── KONSTRUK 9: Ukur panjang/saiz (story) ──
  {
    id: 'kira-k9-ukur',
    title: 'Konstruk 9: Ukur Panjang & Saiz',
    emoji: '📏',
    mode: 'story',
    objective: 'Banding panjang, tinggi & saiz objek.',
    reward: 'Ukur badge',
    rounds: makeRounds([
      { scenes: [{ text: 'Mana lebih PANJANG? 🐍 atau 🐛', choices: ['Ular 🐍','Ulat 🐛'], answer: 0 }] },
      { scenes: [{ text: 'Mana lebih TINGGI? 🦒 atau 🐈', choices: ['Zirafah 🦒','Kucing 🐈'], answer: 0 }] },
      { scenes: [{ text: 'Mana lebih BESAR? 🐘 atau 🐭', choices: ['Tikus 🐭','Gajah 🐘'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih PENDEK? ✏️ atau 📏', choices: ['Pensel ✏️','Pembaris 📏'], answer: 0 }] },
      { scenes: [{ text: 'Mana lebih BERAT? 🪨 atau 🪶', choices: ['Batu 🪨','Bulu 🪶'], answer: 0 }] },
      { scenes: [{ text: 'Mana lebih KECIL? 🍉 atau 🍓', choices: ['Tembikai 🍉','Strawberi 🍓'], answer: 1 }] },
      { scenes: [{ text: 'Mana lebih TINGGI? 🏢 atau 🏠', choices: ['Bangunan 🏢','Rumah 🏠'], answer: 0 }] },
      { scenes: [{ text: 'Mana isipadu lebih BANYAK? 🪣 atau 🥤', choices: ['Baldi 🪣','Cawan 🥤'], answer: 0 }] },
      { scenes: [{ text: 'Mana lebih LAJU? 🐆 atau 🐌', choices: ['Harimau bintang 🐆','Siput 🐌'], answer: 0 }] },
      { scenes: [{ text: 'Mana lebih JAUH? 🌍 ke 🌙 atau 🏠 ke 🏫', choices: ['Bumi ke Bulan','Rumah ke Sekolah'], answer: 0 }] },
    ]),
  },
  // ── KONSTRUK 1: Cari angka tersembunyi (hidden) ──
  {
    id: 'kira-k1-cari-angka',
    title: 'Konstruk 1: Cari Angka',
    emoji: '🔍',
    mode: 'hidden_object',
    objective: 'Cari angka yang disebut.',
    reward: 'Cari angka',
    rounds: makeRounds([
      { target: '2', items: [{text:'2'},{text:'5'},{text:'8'}] },
      { target: '6', items: [{text:'6'},{text:'9'},{text:'3'}] },
      { target: '4', items: [{text:'4'},{text:'7'},{text:'1'},{text:'9'}] },
      { target: '7', items: [{text:'7'},{text:'2'},{text:'5'},{text:'10'}] },
      { target: '11', items: [{text:'11'},{text:'1'},{text:'7'},{text:'4'},{text:'9'}] },
      { target: '14', items: [{text:'14'},{text:'41'},{text:'4'},{text:'40'},{text:'13'}] },
      { target: '17', items: [{text:'17'},{text:'71'},{text:'7'},{text:'70'},{text:'16'},{text:'18'}] },
      { target: '25', items: [{text:'25'},{text:'52'},{text:'5'},{text:'20'},{text:'15'},{text:'35'}] },
      { target: '30', items: [{text:'30'},{text:'3'},{text:'13'},{text:'33'},{text:'20'},{text:'40'},{text:'31'}] },
      { target: '50', items: [{text:'50'},{text:'5'},{text:'15'},{text:'55'},{text:'40'},{text:'60'},{text:'51'},{text:'30'}] },
    ]),
  },
  // ── KONSTRUK 4: Susun seriasi menurun (sequence) ──
  {
    id: 'kira-k4-seriasi-turun',
    title: 'Konstruk 4: Seriasi Menurun',
    emoji: '🔻',
    mode: 'sequence',
    objective: 'Susun nombor dari besar ke kecil.',
    reward: 'Seriasi turun',
    rounds: makeRounds([
      { items: ['3','2','1'], answer: ['3','2','1'] },
      { items: ['6','4','2'], answer: ['6','4','2'] },
      { items: ['5','4','3','2'], answer: ['5','4','3','2'] },
      { items: ['10','8','6','4'], answer: ['10','8','6','4'] },
      { items: ['9','7','5','3','1'], answer: ['9','7','5','3','1'] },
      { items: ['10','9','8','7','6'], answer: ['10','9','8','7','6'] },
      { items: ['20','15','10','5'], answer: ['20','15','10','5'] },
      { items: ['12','9','6','3'], answer: ['12','9','6','3'] },
      { items: ['50','40','30','20','10'], answer: ['50','40','30','20','10'] },
      { items: ['100','80','60','40','20'], answer: ['100','80','60','40','20'] },
    ]),
  },
  // ── KONSTRUK 7: Darab mudah (typing) ──
  {
    id: 'kira-k7-darab',
    title: 'Konstruk 7: Darab Mudah',
    emoji: '✖️',
    mode: 'typing_challenge',
    objective: 'Selesaikan operasi darab asas.',
    reward: 'Darab master',
    rounds: makeRounds([
      { prompt: '2 × 1 = ?', target: '2' },
      { prompt: '2 × 2 = ?', target: '4' },
      { prompt: '2 × 3 = ?', target: '6' },
      { prompt: '3 × 2 = ?', target: '6' },
      { prompt: '3 × 3 = ?', target: '9' },
      { prompt: '4 × 2 = ?', target: '8' },
      { prompt: '5 × 2 = ?', target: '10' },
      { prompt: '4 × 3 = ?', target: '12' },
      { prompt: '5 × 3 = ?', target: '15' },
      { prompt: '5 × 4 = ?', target: '20' },
    ]),
  },
  // ── KONSTRUK 8: Wang & operasi (typing) ──
  {
    id: 'kira-k8-wang-operasi',
    title: 'Konstruk 8: Operasi Wang',
    emoji: '🧮',
    mode: 'typing_challenge',
    objective: 'Selesaikan operasi melibatkan wang.',
    reward: 'Wang kira',
    rounds: makeRounds([
      { prompt: 'RM2 × 3 buku = RM ?', target: '6' },
      { prompt: 'RM5 × 2 pen = RM ?', target: '10' },
      { prompt: 'RM10 ÷ 2 orang = RM ? seorang', target: '5' },
      { prompt: 'RM3 × 4 aiskrim = RM ?', target: '12' },
      { prompt: 'RM20 ÷ 4 = RM ?', target: '5' },
      { prompt: 'RM50 - RM35 = RM ?', target: '15' },
      { prompt: '3 budak beli RM4 setiap satu = RM ?', target: '12' },
      { prompt: 'RM100 - RM75 = RM ?', target: '25' },
      { prompt: 'RM8 × 5 = RM ?', target: '40' },
      { prompt: 'RM30 ÷ 3 = RM ?', target: '10' },
    ]),
  },
  // ── KONSTRUK 12: Aplikasi wang, masa & ukuran (typing) ──
  {
    id: 'kira-k12-aplikasi-lanjut',
    title: 'Konstruk 12: Aplikasi Harian Lanjutan',
    emoji: '🧠',
    mode: 'typing_challenge',
    objective: 'Masalah harian libatkan wang, masa & ukuran.',
    reward: 'Aplikasi pro',
    rounds: makeRounds([
      { prompt: 'Kelas mula 8 pagi, habis 12 tengah hari. Berapa jam?', target: '4' },
      { prompt: 'Pita 10 cm dipotong 3 cm. Tinggal berapa cm?', target: '7' },
      { prompt: 'Beli 2 buku RM6 setiap satu. Jumlah RM?', target: '12' },
      { prompt: '1 jam = berapa minit?', target: '60' },
      { prompt: 'Lari 5 km pagi, 3 km petang. Jumlah km?', target: '8' },
      { prompt: 'Bayar RM50 untuk barang RM38. Baki RM?', target: '12' },
      { prompt: '1 minggu = berapa hari?', target: '7' },
      { prompt: 'Air 2 liter, tuang 1 liter. Tinggal berapa liter?', target: '1' },
      { prompt: 'Filem 2 jam = berapa minit?', target: '120' },
      { prompt: 'Tali 15 m dibahagi 3. Setiap bahagian berapa m?', target: '5' },
    ]),
  },
  // ── KONSTRUK 2: Membilang & taip (lanjutan) ──
  {
    id: 'kira-k2-bilang-lanjut',
    title: 'Konstruk 2: Membilang (Lanjutan)',
    emoji: '🔢',
    mode: 'typing_challenge',
    objective: 'Bilang objek sehingga 20 & taip jumlahnya.',
    reward: 'Bilang pro',
    rounds: makeRounds([
      { prompt: '🍓×11 — Berapa strawberi?', target: '11' },
      { prompt: '⭐×12 — Berapa bintang?', target: '12' },
      { prompt: '🐝×13 — Berapa lebah?', target: '13' },
      { prompt: '🍎×14 — Berapa epal?', target: '14' },
      { prompt: '🎈×15 — Berapa belon?', target: '15' },
      { prompt: '🐟×16 — Berapa ikan?', target: '16' },
      { prompt: '🌸×17 — Berapa bunga?', target: '17' },
      { prompt: '🚗×18 — Berapa kereta?', target: '18' },
      { prompt: '🎁×19 — Berapa hadiah?', target: '19' },
      { prompt: '⚽×20 — Berapa bola?', target: '20' },
    ]),
  },
  // ── KONSTRUK 3: Kelas nombor (sorting) ──
  {
    id: 'kira-k3-kelas-sorting',
    title: 'Konstruk 3: Kelaskan Nombor',
    emoji: '🗂️',
    mode: 'sorting',
    objective: 'Asingkan nombor ikut kumpulan.',
    reward: 'Kelas badge',
    rounds: makeRounds([
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '2', group: 'Genap' }, { text: '3', group: 'Ganjil' }, { text: '4', group: 'Genap' }, { text: '5', group: 'Ganjil' },
      ] },
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '6', group: 'Genap' }, { text: '7', group: 'Ganjil' }, { text: '8', group: 'Genap' }, { text: '9', group: 'Ganjil' },
      ] },
      { groups: ['Kecil dari 5', 'Besar dari 5'], items: [
        { text: '2', group: 'Kecil dari 5' }, { text: '8', group: 'Besar dari 5' }, { text: '3', group: 'Kecil dari 5' }, { text: '9', group: 'Besar dari 5' },
      ] },
      { groups: ['1 digit', '2 digit'], items: [
        { text: '5', group: '1 digit' }, { text: '12', group: '2 digit' }, { text: '8', group: '1 digit' }, { text: '20', group: '2 digit' },
      ] },
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '10', group: 'Genap' }, { text: '11', group: 'Ganjil' }, { text: '12', group: 'Genap' }, { text: '13', group: 'Ganjil' }, { text: '14', group: 'Genap' },
      ] },
      { groups: ['Kecil dari 10', 'Besar dari 10'], items: [
        { text: '7', group: 'Kecil dari 10' }, { text: '15', group: 'Besar dari 10' }, { text: '4', group: 'Kecil dari 10' }, { text: '18', group: 'Besar dari 10' }, { text: '9', group: 'Kecil dari 10' },
      ] },
      { groups: ['1 digit', '2 digit'], items: [
        { text: '6', group: '1 digit' }, { text: '14', group: '2 digit' }, { text: '9', group: '1 digit' }, { text: '25', group: '2 digit' }, { text: '3', group: '1 digit' }, { text: '40', group: '2 digit' },
      ] },
      { groups: ['Genap', 'Ganjil'], items: [
        { text: '15', group: 'Ganjil' }, { text: '16', group: 'Genap' }, { text: '17', group: 'Ganjil' }, { text: '18', group: 'Genap' }, { text: '19', group: 'Ganjil' }, { text: '20', group: 'Genap' },
      ] },
      { groups: ['Kecil dari 50', 'Besar dari 50'], items: [
        { text: '30', group: 'Kecil dari 50' }, { text: '70', group: 'Besar dari 50' }, { text: '45', group: 'Kecil dari 50' }, { text: '80', group: 'Besar dari 50' }, { text: '25', group: 'Kecil dari 50' }, { text: '90', group: 'Besar dari 50' },
      ] },
      { groups: ['2 digit', '3 digit'], items: [
        { text: '45', group: '2 digit' }, { text: '120', group: '3 digit' }, { text: '88', group: '2 digit' }, { text: '300', group: '3 digit' }, { text: '50', group: '2 digit' }, { text: '999', group: '3 digit' }, { text: '12', group: '2 digit' },
      ] },
    ]),
  },
  // ── KONSTRUK 4: Susun seriasi menaik (sequence lanjutan) ──
  {
    id: 'kira-k4-seriasi-naik2',
    title: 'Konstruk 4: Seriasi Menaik (Lanjutan)',
    emoji: '🔺',
    mode: 'sequence',
    objective: 'Susun nombor dari kecil ke besar.',
    reward: 'Seriasi naik',
    rounds: makeRounds([
      { items: ['4','5','6'], answer: ['4','5','6'] },
      { items: ['7','8','9'], answer: ['7','8','9'] },
      { items: ['11','12','13','14'], answer: ['11','12','13','14'] },
      { items: ['4','8','12','16'], answer: ['4','8','12','16'] },
      { items: ['1','4','7','10','13'], answer: ['1','4','7','10','13'] },
      { items: ['25','30','35','40'], answer: ['25','30','35','40'] },
      { items: ['15','25','35','45','55'], answer: ['15','25','35','45','55'] },
      { items: ['6','12','18','24','30'], answer: ['6','12','18','24','30'] },
      { items: ['20','40','60','80','100'], answer: ['20','40','60','80','100'] },
      { items: ['11','22','33','44','55','66'], answer: ['11','22','33','44','55','66'] },
    ]),
  },
  // ── KONSTRUK 7: Tambah & tolak campur (typing) ──
  {
    id: 'kira-k7-campur',
    title: 'Konstruk 7: Tambah & Tolak Campur',
    emoji: '🔢',
    mode: 'typing_challenge',
    objective: 'Selesaikan operasi tambah & tolak bercampur.',
    reward: 'Campur master',
    rounds: makeRounds([
      { prompt: '2 + 3 - 1 = ?', target: '4' },
      { prompt: '5 - 2 + 4 = ?', target: '7' },
      { prompt: '6 + 2 - 3 = ?', target: '5' },
      { prompt: '8 - 4 + 5 = ?', target: '9' },
      { prompt: '10 - 3 - 2 = ?', target: '5' },
      { prompt: '7 + 5 - 4 = ?', target: '8' },
      { prompt: '12 - 5 + 3 = ?', target: '10' },
      { prompt: '9 + 6 - 5 = ?', target: '10' },
      { prompt: '15 - 8 + 6 = ?', target: '13' },
      { prompt: '20 - 7 - 3 = ?', target: '10' },
    ]),
  },
  // ── KONSTRUK 11: Masalah harian (lanjutan, story) ──
  {
    id: 'kira-k11-masalah-story',
    title: 'Konstruk 11: Masalah Harian (Pilih)',
    emoji: '🧩',
    mode: 'story',
    objective: 'Baca masalah & pilih jawapan yang betul.',
    reward: 'Masalah pilih',
    rounds: makeRounds([
      { scenes: [{ text: 'Ada 5 burung, 2 terbang pergi. Berapa tinggal?', choices: ['2','3','4'], answer: 1 }] },
      { scenes: [{ text: 'Siti ada 3 gula, beli 4 lagi. Jumlah?', choices: ['6','7','8'], answer: 1 }] },
      { scenes: [{ text: '8 epal dibahagi 2 budak. Setiap budak?', choices: ['3','4','5'], answer: 1 }] },
      { scenes: [{ text: '10 kerusi, 3 rosak. Berapa elok?', choices: ['6','7','8'], answer: 1 }] },
      { scenes: [{ text: '4 kotak, setiap kotak 3 bola. Jumlah bola?', choices: ['10','12','14'], answer: 1 }] },
      { scenes: [{ text: '15 murid, 7 lelaki. Berapa perempuan?', choices: ['7','8','9'], answer: 1 }] },
      { scenes: [{ text: 'Beli 5 pen RM2 satu. Jumlah bayar?', choices: ['RM8','RM10','RM12'], answer: 1 }] },
      { scenes: [{ text: '20 biskut, makan 8. Berapa tinggal?', choices: ['10','11','12'], answer: 2 }] },
      { scenes: [{ text: '6 + 6 + 6 = ?', choices: ['16','18','20'], answer: 1 }] },
      { scenes: [{ text: '24 pelajar, susun 6 satu baris. Berapa baris?', choices: ['3','4','5'], answer: 1 }] },
    ]),
  },
];