// 🔢 MENGIRA — kemahiran numerasi: kenal nombor, kira, tambah & tolak asas.
// Untuk prasekolah + darjah rendah. Guna mekanik sedia ada (MiniGameModeRenderer).
import { makeRounds } from '../miniGames/_helpers.js';

export const mengiraGames = [
  {
    id: 'kira-kenal-nombor',
    title: 'Kenal Nombor',
    emoji: '1️⃣',
    mode: 'hidden_object',
    objective: 'Cari nombor yang betul.',
    reward: 'Number badge',
    rounds: makeRounds([
      { target: '1', items: [{text:'1',value:'1'},{text:'2',value:'2'},{text:'3',value:'3'}] },
      { target: '4', items: [{text:'4',value:'4'},{text:'5',value:'5'},{text:'6',value:'6'}] },
      { target: '7', items: [{text:'7',value:'7'},{text:'8',value:'8'},{text:'9',value:'9'},{text:'10',value:'10'}] },
      { target: '5', items: [{text:'5',value:'5'},{text:'2',value:'2'},{text:'8',value:'8'},{text:'6',value:'6'}] },
      { target: '9', items: [{text:'9',value:'9'},{text:'6',value:'6'},{text:'3',value:'3'},{text:'8',value:'8'},{text:'4',value:'4'}] },
      { target: '10', items: [{text:'10',value:'10'},{text:'1',value:'1'},{text:'7',value:'7'},{text:'4',value:'4'},{text:'6',value:'6'}] },
      { target: '8', items: [{text:'8',value:'8'},{text:'3',value:'3'},{text:'6',value:'6'},{text:'9',value:'9'},{text:'2',value:'2'},{text:'5',value:'5'}] },
      { target: '13', items: [{text:'13',value:'13'},{text:'31',value:'31'},{text:'12',value:'12'},{text:'30',value:'30'},{text:'3',value:'3'},{text:'11',value:'11'}] },
      { target: '15', items: [{text:'15',value:'15'},{text:'51',value:'51'},{text:'14',value:'14'},{text:'50',value:'50'},{text:'5',value:'5'},{text:'16',value:'16'},{text:'13',value:'13'}] },
      { target: '20', items: [{text:'20',value:'20'},{text:'2',value:'2'},{text:'12',value:'12'},{text:'22',value:'22'},{text:'10',value:'10'},{text:'21',value:'21'},{text:'30',value:'30'},{text:'18',value:'18'}] },
    ]),
  },
  {
    id: 'kira-bilang-objek',
    title: 'Bilang Objek',
    emoji: '🍎',
    mode: 'typing_challenge',
    objective: 'Kira bilangan objek dan taip jawapan.',
    reward: 'Counting star',
    rounds: makeRounds([
      { prompt: '🍎🍎 — Berapa epal?', target: '2' },
      { prompt: '⭐⭐⭐ — Berapa bintang?', target: '3' },
      { prompt: '🐟🐟🐟🐟 — Berapa ikan?', target: '4' },
      { prompt: '🎈🎈🎈🎈🎈 — Berapa belon?', target: '5' },
      { prompt: '🍌🍌🍌🍌🍌🍌 — Berapa pisang?', target: '6' },
      { prompt: '🌸🌸🌸🌸🌸🌸🌸 — Berapa bunga?', target: '7' },
      { prompt: '🚗🚗🚗🚗🚗🚗🚗🚗 — Berapa kereta?', target: '8' },
      { prompt: '🐱🐱🐱🐱🐱🐱🐱🐱🐱 — Berapa kucing?', target: '9' },
      { prompt: '🎁🎁🎁🎁🎁🎁🎁🎁🎁🎁 — Berapa hadiah?', target: '10' },
      { prompt: '⚽⚽⚽⚽⚽⚽ ➕ ⚽⚽⚽⚽⚽⚽ — Jumlah bola?', target: '12' },
    ]),
  },
  {
    id: 'kira-tambah-asas',
    title: 'Tambah Asas',
    emoji: '➕',
    mode: 'typing_challenge',
    objective: 'Selesaikan operasi tambah dan taip jawapan.',
    reward: 'Plus master',
    rounds: makeRounds([
      { prompt: '1 + 1 = ?', target: '2' },
      { prompt: '2 + 1 = ?', target: '3' },
      { prompt: '2 + 3 = ?', target: '5' },
      { prompt: '4 + 3 = ?', target: '7' },
      { prompt: '5 + 4 = ?', target: '9' },
      { prompt: '6 + 4 = ?', target: '10' },
      { prompt: '7 + 5 = ?', target: '12' },
      { prompt: '8 + 6 = ?', target: '14' },
      { prompt: '9 + 8 = ?', target: '17' },
      { prompt: '12 + 9 = ?', target: '21' },
    ]),
  },
  {
    id: 'kira-tolak-asas',
    title: 'Tolak Asas',
    emoji: '➖',
    mode: 'typing_challenge',
    objective: 'Selesaikan operasi tolak dan taip jawapan.',
    reward: 'Minus master',
    rounds: makeRounds([
      { prompt: '2 - 1 = ?', target: '1' },
      { prompt: '3 - 1 = ?', target: '2' },
      { prompt: '5 - 2 = ?', target: '3' },
      { prompt: '7 - 3 = ?', target: '4' },
      { prompt: '9 - 4 = ?', target: '5' },
      { prompt: '10 - 4 = ?', target: '6' },
      { prompt: '12 - 5 = ?', target: '7' },
      { prompt: '15 - 7 = ?', target: '8' },
      { prompt: '18 - 9 = ?', target: '9' },
      { prompt: '20 - 8 = ?', target: '12' },
    ]),
  },
  {
    id: 'kira-corak-nombor',
    title: 'Corak Nombor',
    emoji: '🔁',
    mode: 'sequence',
    objective: 'Susun nombor mengikut corak.',
    reward: 'Pattern brain',
    rounds: makeRounds([
      { items: ['1','2','3'], answer: ['1','2','3'] },
      { items: ['2','4','6'], answer: ['2','4','6'] },
      { items: ['1','2','3','4'], answer: ['1','2','3','4'] },
      { items: ['5','10','15','20'], answer: ['5','10','15','20'] },
      { items: ['2','4','6','8','10'], answer: ['2','4','6','8','10'] },
      { items: ['10','9','8','7','6'], answer: ['10','9','8','7','6'] },
      { items: ['1','3','5','7','9'], answer: ['1','3','5','7','9'] },
      { items: ['3','6','9','12','15'], answer: ['3','6','9','12','15'] },
      { items: ['10','20','30','40','50','60'], answer: ['10','20','30','40','50','60'] },
      { items: ['100','90','80','70','60','50'], answer: ['100','90','80','70','60','50'] },
    ]),
  },
  {
    id: 'kira-banyak-sedikit',
    title: 'Banyak atau Sedikit',
    emoji: '⚖️',
    mode: 'swipe_select',
    objective: 'Pilih kumpulan yang lebih banyak.',
    reward: 'Compare badge',
    rounds: makeRounds([
      { items: [{ text: '🍎🍎 vs 🍎🍎🍎', group: 'Kanan' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '⭐⭐⭐⭐ vs ⭐⭐', group: 'Kiri' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '🐟 vs 🐟🐟🐟', group: 'Kanan' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '🎈🎈🎈🎈🎈 vs 🎈🎈', group: 'Kiri' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '3 vs 7', group: 'Kanan' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '9 vs 4', group: 'Kiri' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '6 vs 8', group: 'Kanan' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '12 vs 5', group: 'Kiri' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '15 vs 20', group: 'Kanan' }], groups: ['Kiri', 'Kanan'] },
      { items: [{ text: '30 vs 18', group: 'Kiri' }], groups: ['Kiri', 'Kanan'] },
    ]),
  },
];