// ✍️ MENULIS — kemahiran motor: surih huruf, nombor & susun tulisan.
// Untuk prasekolah + darjah rendah. Guna mekanik sedia ada (MiniGameModeRenderer).
import { makeRounds } from '../miniGames/_helpers.js';

export const menulisGames = [
  {
    id: 'tulis-surih-huruf',
    title: 'Surih Huruf',
    emoji: '🅰️',
    mode: 'tracing',
    objective: 'Surih huruf mengikut titik bernombor.',
    reward: 'Tracing star',
    rounds: makeRounds([
      { letters: ['A'] },
      { letters: ['B'] },
      { letters: ['C'] },
      { letters: ['D'] },
      { letters: ['E'] },
      { letters: ['M'] },
      { letters: ['S'] },
      { letters: ['R'] },
      { letters: ['K'] },
      { letters: ['G'] },
    ]),
  },
  {
    id: 'tulis-surih-nombor',
    title: 'Surih Nombor',
    emoji: '🔢',
    mode: 'tracing',
    objective: 'Surih nombor mengikut titik bernombor.',
    reward: 'Number trace',
    rounds: makeRounds([
      { letters: ['1'] },
      { letters: ['2'] },
      { letters: ['3'] },
      { letters: ['4'] },
      { letters: ['5'] },
      { letters: ['6'] },
      { letters: ['7'] },
      { letters: ['8'] },
      { letters: ['9'] },
      { letters: ['0'] },
    ]),
  },
  {
    id: 'tulis-urutan-huruf',
    title: 'Susun Urutan Huruf',
    emoji: '🔤',
    mode: 'sequence',
    objective: 'Susun huruf mengikut urutan abjad.',
    reward: 'ABC order',
    rounds: makeRounds([
      { items: ['A','B','C'], answer: ['A','B','C'] },
      { items: ['D','E','F'], answer: ['D','E','F'] },
      { items: ['A','B','C','D'], answer: ['A','B','C','D'] },
      { items: ['E','F','G','H'], answer: ['E','F','G','H'] },
      { items: ['A','B','C','D','E'], answer: ['A','B','C','D','E'] },
      { items: ['F','G','H','I','J'], answer: ['F','G','H','I','J'] },
      { items: ['A','B','C','D','E','F'], answer: ['A','B','C','D','E','F'] },
      { items: ['K','L','M','N','O','P'], answer: ['K','L','M','N','O','P'] },
      { items: ['A','B','C','D','E','F','G'], answer: ['A','B','C','D','E','F','G'] },
      { items: ['Q','R','S','T','U','V','W'], answer: ['Q','R','S','T','U','V','W'] },
    ]),
  },
  {
    id: 'tulis-susun-perkataan',
    title: 'Susun Huruf Jadi Perkataan',
    emoji: '🧩',
    mode: 'wordbuilder',
    objective: 'Susun huruf untuk bina perkataan.',
    reward: 'Word build',
    rounds: makeRounds([
      { target: 'BOLA', letters: ['B','O','L','A'] },
      { target: 'MEJA', letters: ['M','E','J','A'] },
      { target: 'BUKU', letters: ['B','U','K','U'] },
      { target: 'KASUT', letters: ['K','A','S','U','T'] },
      { target: 'BAJU', letters: ['B','A','J','U'] },
      { target: 'RUMAH', letters: ['R','U','M','A','H'] },
      { target: 'POKOK', letters: ['P','O','K','O','K'] },
      { target: 'BUNGA', letters: ['B','U','N','G','A'] },
      { target: 'KERETA', letters: ['K','E','R','E','T','A'] },
      { target: 'SEKOLAH', letters: ['S','E','K','O','L','A','H'] },
    ]),
  },
  {
    id: 'tulis-urutan-nombor',
    title: 'Susun Urutan Nombor',
    emoji: '🔢',
    mode: 'sequence',
    objective: 'Susun nombor mengikut urutan menaik.',
    reward: 'Number order',
    rounds: makeRounds([
      { items: ['1','2','3'], answer: ['1','2','3'] },
      { items: ['4','5','6'], answer: ['4','5','6'] },
      { items: ['1','2','3','4'], answer: ['1','2','3','4'] },
      { items: ['5','6','7','8'], answer: ['5','6','7','8'] },
      { items: ['1','2','3','4','5'], answer: ['1','2','3','4','5'] },
      { items: ['6','7','8','9','10'], answer: ['6','7','8','9','10'] },
      { items: ['1','2','3','4','5','6'], answer: ['1','2','3','4','5','6'] },
      { items: ['10','20','30','40','50'], answer: ['10','20','30','40','50'] },
      { items: ['2','4','6','8','10'], answer: ['2','4','6','8','10'] },
      { items: ['5','10','15','20','25','30'], answer: ['5','10','15','20','25','30'] },
    ]),
  },
  {
    id: 'tulis-eja-nama',
    title: 'Taip Perkataan',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan yang ditunjuk dengan tepat.',
    reward: 'Typing badge',
    rounds: makeRounds([
      { prompt: 'Taip: BOLA', target: 'bola' },
      { prompt: 'Taip: MEJA', target: 'meja' },
      { prompt: 'Taip: BUKU', target: 'buku' },
      { prompt: 'Taip: BAJU', target: 'baju' },
      { prompt: 'Taip: RUMAH', target: 'rumah' },
      { prompt: 'Taip: POKOK', target: 'pokok' },
      { prompt: 'Taip: BUNGA', target: 'bunga' },
      { prompt: 'Taip: KERETA', target: 'kereta' },
      { prompt: 'Taip: SEKOLAH', target: 'sekolah' },
      { prompt: 'Taip: KOMPUTER', target: 'komputer' },
    ]),
  },
];