// ✍️ MENULIS — disusun ikut Konstruk LINUS Literasi BM rasmi (fokus MENULIS).
// Surih huruf → susun urutan abjad → tulis suku kata → bina perkataan terbuka →
// bina perkataan tertutup → tulis perkataan berimbuhan (Konstruk 10) → ayat mudah (Konstruk 11).
// Guna pelbagai mekanik mini-game (MiniGameModeRenderer).
import { makeRounds } from '../miniGames/_helpers.js';

export const menulisGames = [
  // ── KONSTRUK 1: Menulis huruf (surih) ──
  {
    id: 'tulis-k1-surih-huruf',
    title: 'Konstruk 1: Surih Huruf',
    emoji: '🅰️',
    mode: 'tracing',
    objective: 'Surih huruf vokal & konsonan ikut titik.',
    reward: 'Tracing star',
    rounds: makeRounds([
      { letters: ['A'] }, { letters: ['E'] }, { letters: ['I'] }, { letters: ['O'] }, { letters: ['U'] },
      { letters: ['B'] }, { letters: ['M'] }, { letters: ['S'] }, { letters: ['K'] }, { letters: ['R'] },
    ]),
  },
  // ── KONSTRUK 1: Susun urutan abjad (kemahiran tulis berurutan) ──
  {
    id: 'tulis-k1-urutan-abjad',
    title: 'Konstruk 1: Susun Abjad',
    emoji: '🔤',
    mode: 'sequence',
    objective: 'Susun huruf ikut urutan abjad sebelum menulis.',
    reward: 'ABC order',
    rounds: makeRounds([
      { items: ['A','B','C'], answer: ['A','B','C'] },
      { items: ['D','E','F'], answer: ['D','E','F'] },
      { items: ['A','B','C','D'], answer: ['A','B','C','D'] },
      { items: ['E','F','G','H'], answer: ['E','F','G','H'] },
      { items: ['A','B','C','D','E'], answer: ['A','B','C','D','E'] },
      { items: ['F','G','H','I','J'], answer: ['F','G','H','I','J'] },
      { items: ['A','B','C','D','E','F'], answer: ['A','B','C','D','E','F'] },
      { items: ['K','L','M','N','O','P'], answer: ['K','L','M','N','O','P'] },
      { items: ['A','B','C','D','E','F','G'], answer: ['A','B','C','D','E','F','G'] },
      { items: ['Q','R','S','T','U','V','W'], answer: ['Q','R','S','T','U','V','W'] },
    ]),
  },
  // ── KONSTRUK 2–3: Menulis suku kata & perkataan TERBUKA ──
  {
    id: 'tulis-k3-perkataan-terbuka',
    title: 'Konstruk 2–3: Tulis Perkataan Terbuka',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan suku kata terbuka (KV+KV).',
    reward: 'Typing terbuka',
    rounds: makeRounds([
      { prompt: 'Taip: BATU', target: 'batu' },
      { prompt: 'Taip: BUKU', target: 'buku' },
      { prompt: 'Taip: DADU', target: 'dadu' },
      { prompt: 'Taip: KUDA', target: 'kuda' },
      { prompt: 'Taip: MEJA', target: 'meja' },
      { prompt: 'Taip: SAPU', target: 'sapu' },
      { prompt: 'Taip: BOLA', target: 'bola' },
      { prompt: 'Taip: BAJU', target: 'baju' },
      { prompt: 'Taip: KELAPA', target: 'kelapa' },
      { prompt: 'Taip: KERETA', target: 'kereta' },
    ]),
  },
  // ── KONSTRUK 4–5: Menulis perkataan suku kata TERTUTUP (KVK) ──
  {
    id: 'tulis-k5-perkataan-tertutup',
    title: 'Konstruk 4–5: Tulis Perkataan Tertutup',
    emoji: '🧩',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan suku kata tertutup.',
    reward: 'Word tertutup',
    rounds: makeRounds([
      { target: 'BAS', letters: ['B','A','S'] },
      { target: 'CAT', letters: ['C','A','T'] },
      { target: 'KASUT', letters: ['K','A','S','U','T'] },
      { target: 'RUMAH', letters: ['R','U','M','A','H'] },
      { target: 'POKOK', letters: ['P','O','K','O','K'] },
      { target: 'LAMPU', letters: ['L','A','M','P','U'] },
      { target: 'PENSEL', letters: ['P','E','N','S','E','L'] },
      { target: 'TEMPAT', letters: ['T','E','M','P','A','T'] },
      { target: 'BASKET', letters: ['B','A','S','K','E','T'] },
      { target: 'KOMPUTER', letters: ['K','O','M','P','U','T','E','R'] },
    ]),
  },
  // ── KONSTRUK 10: Menulis perkataan berimbuhan awalan & akhiran ──
  {
    id: 'tulis-k10-imbuhan',
    title: 'Konstruk 10: Perkataan Berimbuhan',
    emoji: '🔗',
    mode: 'wordbuilder',
    objective: 'Cantum imbuhan untuk bina perkataan (cth: ber+main).',
    reward: 'Imbuhan badge',
    rounds: makeRounds([
      { target: 'BERMAIN', letters: ['BER','MAIN'] },
      { target: 'MEMBACA', letters: ['MEM','BACA'] },
      { target: 'MAKANAN', letters: ['MAKAN','AN'] },
      { target: 'BERLARI', letters: ['BER','LARI'] },
      { target: 'MELUKIS', letters: ['ME','LUKIS'] },
      { target: 'PERMAINAN', letters: ['PER','MAIN','AN'] },
      { target: 'PELAJARAN', letters: ['PE','LAJAR','AN'] },
      { target: 'MENULIS', letters: ['ME','NULIS'] },
      { target: 'KEBERSIHAN', letters: ['KE','BERSIH','AN'] },
      { target: 'MEMBERSIHKAN', letters: ['MEM','BERSIH','KAN'] },
    ]),
  },
  // ── KONSTRUK 11: Menulis ayat mudah (susun perkataan jadi ayat) ──
  {
    id: 'tulis-k11-ayat-mudah',
    title: 'Konstruk 11: Susun Ayat Mudah',
    emoji: '📝',
    mode: 'sequence',
    objective: 'Susun perkataan ikut urutan jadi ayat yang betul.',
    reward: 'Ayat badge',
    rounds: makeRounds([
      { items: ['Saya','makan','nasi'], answer: ['Saya','makan','nasi'] },
      { items: ['Ali','bermain','bola'], answer: ['Ali','bermain','bola'] },
      { items: ['Ibu','memasak','di','dapur'], answer: ['Ibu','memasak','di','dapur'] },
      { items: ['Adik','membaca','buku','cerita'], answer: ['Adik','membaca','buku','cerita'] },
      { items: ['Kucing','itu','minum','susu'], answer: ['Kucing','itu','minum','susu'] },
      { items: ['Saya','pergi','ke','sekolah'], answer: ['Saya','pergi','ke','sekolah'] },
      { items: ['Bapa','membaca','surat','khabar','pagi'], answer: ['Bapa','membaca','surat','khabar','pagi'] },
      { items: ['Burung','itu','terbang','tinggi','sekali'], answer: ['Burung','itu','terbang','tinggi','sekali'] },
      { items: ['Kami','suka','bermain','di','taman'], answer: ['Kami','suka','bermain','di','taman'] },
      { items: ['Pelajar','itu','menulis','karangan','dengan','tekun'], answer: ['Pelajar','itu','menulis','karangan','dengan','tekun'] },
    ]),
  },
  // ── KONSTRUK 1: Surih huruf vokal & konsonan lain ──
  {
    id: 'tulis-k1-surih-lanjut',
    title: 'Konstruk 1: Surih Huruf (Lanjutan)',
    emoji: '✏️',
    mode: 'tracing',
    objective: 'Surih lebih banyak huruf ikut titik.',
    reward: 'Tracing pro',
    rounds: makeRounds([
      { letters: ['C'] }, { letters: ['D'] }, { letters: ['F'] }, { letters: ['G'] }, { letters: ['H'] },
      { letters: ['L'] }, { letters: ['N'] }, { letters: ['P'] }, { letters: ['T'] }, { letters: ['W'] },
    ]),
  },
  // ── KONSTRUK 1: Surih nombor ──
  {
    id: 'tulis-k1-surih-nombor',
    title: 'Konstruk 1: Surih Nombor',
    emoji: '🔢',
    mode: 'tracing',
    objective: 'Surih nombor 0–9 ikut titik.',
    reward: 'Nombor surih',
    rounds: makeRounds([
      { letters: ['1'] }, { letters: ['2'] }, { letters: ['3'] }, { letters: ['4'] }, { letters: ['5'] },
      { letters: ['6'] }, { letters: ['7'] }, { letters: ['8'] }, { letters: ['9'] }, { letters: ['0'] },
    ]),
  },
  // ── KONSTRUK 2: Susun suku kata jadi perkataan ──
  {
    id: 'tulis-k2-susun-suku',
    title: 'Konstruk 2: Susun Suku Kata',
    emoji: '🧩',
    mode: 'wordbuilder',
    objective: 'Cantum suku kata jadi perkataan terbuka.',
    reward: 'Susun suku',
    rounds: makeRounds([
      { target: 'BUKU', letters: ['BU','KU'] },
      { target: 'BATU', letters: ['BA','TU'] },
      { target: 'KUDA', letters: ['KU','DA'] },
      { target: 'MEJA', letters: ['ME','JA'] },
      { target: 'ROTI', letters: ['RO','TI'] },
      { target: 'DADU', letters: ['DA','DU'] },
      { target: 'CAWAN', letters: ['CA','WAN'] },
      { target: 'KELAPA', letters: ['KE','LA','PA'] },
      { target: 'KERETA', letters: ['KE','RE','TA'] },
      { target: 'SEPATU', letters: ['SE','PA','TU'] },
    ]),
  },
  // ── KONSTRUK 3: Eja perkataan terbuka (sequence) ──
  {
    id: 'tulis-k3-eja-terbuka',
    title: 'Konstruk 3: Eja Perkataan',
    emoji: '🔡',
    mode: 'sequence',
    objective: 'Susun huruf ikut ejaan yang betul.',
    reward: 'Eja tulis',
    rounds: makeRounds([
      { items: ['B','A','T','U'], answer: ['B','A','T','U'] },
      { items: ['B','U','K','U'], answer: ['B','U','K','U'] },
      { items: ['M','E','J','A'], answer: ['M','E','J','A'] },
      { items: ['K','U','D','A'], answer: ['K','U','D','A'] },
      { items: ['S','A','P','U'], answer: ['S','A','P','U'] },
      { items: ['B','O','L','A'], answer: ['B','O','L','A'] },
      { items: ['R','O','T','I'], answer: ['R','O','T','I'] },
      { items: ['C','A','W','A','N'], answer: ['C','A','W','A','N'] },
      { items: ['K','E','L','A','P','A'], answer: ['K','E','L','A','P','A'] },
      { items: ['K','E','R','E','T','A'], answer: ['K','E','R','E','T','A'] },
    ]),
  },
  // ── KONSTRUK 5: Taip perkataan tertutup ──
  {
    id: 'tulis-k5-taip-tertutup',
    title: 'Konstruk 5: Taip Perkataan Tertutup',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan suku kata tertutup (KVK).',
    reward: 'Taip tertutup',
    rounds: makeRounds([
      { prompt: 'Taip: BAS', target: 'bas' },
      { prompt: 'Taip: CAT', target: 'cat' },
      { prompt: 'Taip: KASUT', target: 'kasut' },
      { prompt: 'Taip: LAMPU', target: 'lampu' },
      { prompt: 'Taip: POKOK', target: 'pokok' },
      { prompt: 'Taip: RUMAH', target: 'rumah' },
      { prompt: 'Taip: PENSEL', target: 'pensel' },
      { prompt: 'Taip: TEMPAT', target: 'tempat' },
      { prompt: 'Taip: KAMBING', target: 'kambing' },
      { prompt: 'Taip: KOMPUTER', target: 'komputer' },
    ]),
  },
  // ── KONSTRUK 6: Tulis perkataan 'ng' ──
  {
    id: 'tulis-k6-ng',
    title: 'Konstruk 6: Tulis Bunyi "ng"',
    emoji: '🎵',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan berbunyi "ng".',
    reward: 'NG tulis',
    rounds: makeRounds([
      { target: 'BUNGA', letters: ['B','U','N','G','A'] },
      { target: 'TANGAN', letters: ['T','A','N','G','A','N'] },
      { target: 'BURUNG', letters: ['B','U','R','U','N','G'] },
      { target: 'PAYUNG', letters: ['P','A','Y','U','N','G'] },
      { target: 'GUNUNG', letters: ['G','U','N','U','N','G'] },
      { target: 'JAGUNG', letters: ['J','A','G','U','N','G'] },
      { target: 'LADANG', letters: ['L','A','D','A','N','G'] },
      { target: 'PISANG', letters: ['P','I','S','A','N','G'] },
      { target: 'BINTANG', letters: ['B','I','N','T','A','N','G'] },
      { target: 'KANGKUNG', letters: ['K','A','N','G','K','U','N','G'] },
    ]),
  },
  // ── KONSTRUK 7: Tulis perkataan diftong ──
  {
    id: 'tulis-k7-diftong',
    title: 'Konstruk 7: Tulis Diftong',
    emoji: '🖊️',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan diftong (ai, au, oi).',
    reward: 'Diftong tulis',
    rounds: makeRounds([
      { target: 'PANTAI', letters: ['P','A','N','T','A','I'] },
      { target: 'TUPAI', letters: ['T','U','P','A','I'] },
      { target: 'KEDAI', letters: ['K','E','D','A','I'] },
      { target: 'PISAU', letters: ['P','I','S','A','U'] },
      { target: 'LIMAU', letters: ['L','I','M','A','U'] },
      { target: 'PULAU', letters: ['P','U','L','A','U'] },
      { target: 'HARIMAU', letters: ['H','A','R','I','M','A','U'] },
      { target: 'KERBAU', letters: ['K','E','R','B','A','U'] },
      { target: 'SUNGAI', letters: ['S','U','N','G','A','I'] },
      { target: 'AMBOI', letters: ['A','M','B','O','I'] },
    ]),
  },
  // ── KONSTRUK 8: Tulis perkataan vokal berganding ──
  {
    id: 'tulis-k8-vokal-ganding',
    title: 'Konstruk 8: Vokal Berganding',
    emoji: '✒️',
    mode: 'wordbuilder',
    objective: 'Susun huruf jadi perkataan vokal berganding.',
    reward: 'Vokal tulis',
    rounds: makeRounds([
      { target: 'AIR', letters: ['A','I','R'] },
      { target: 'BAIK', letters: ['B','A','I','K'] },
      { target: 'KUIH', letters: ['K','U','I','H'] },
      { target: 'BUIH', letters: ['B','U','I','H'] },
      { target: 'NAIK', letters: ['N','A','I','K'] },
      { target: 'MAIN', letters: ['M','A','I','N'] },
      { target: 'LAUK', letters: ['L','A','U','K'] },
      { target: 'DAUN', letters: ['D','A','U','N'] },
      { target: 'BUAYA', letters: ['B','U','A','Y','A'] },
      { target: 'TAHUN', letters: ['T','A','H','U','N'] },
    ]),
  },
  // ── KONSTRUK 10: Taip perkataan berimbuhan ──
  {
    id: 'tulis-k10-taip-imbuhan',
    title: 'Konstruk 10: Taip Imbuhan',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan berimbuhan dengan betul.',
    reward: 'Imbuhan taip',
    rounds: makeRounds([
      { prompt: 'Taip: BERMAIN', target: 'bermain' },
      { prompt: 'Taip: MEMBACA', target: 'membaca' },
      { prompt: 'Taip: MAKANAN', target: 'makanan' },
      { prompt: 'Taip: BERLARI', target: 'berlari' },
      { prompt: 'Taip: MELUKIS', target: 'melukis' },
      { prompt: 'Taip: MENULIS', target: 'menulis' },
      { prompt: 'Taip: PERMAINAN', target: 'permainan' },
      { prompt: 'Taip: PELAJARAN', target: 'pelajaran' },
      { prompt: 'Taip: KEBERSIHAN', target: 'kebersihan' },
      { prompt: 'Taip: MEMBERSIHKAN', target: 'membersihkan' },
    ]),
  },
  // ── KONSTRUK 11: Susun ayat mudah (lanjutan) ──
  {
    id: 'tulis-k11-ayat-lanjut',
    title: 'Konstruk 11: Susun Ayat (Lanjutan)',
    emoji: '📝',
    mode: 'sequence',
    objective: 'Susun perkataan jadi ayat yang betul.',
    reward: 'Ayat pro',
    rounds: makeRounds([
      { items: ['Saya','suka','membaca'], answer: ['Saya','suka','membaca'] },
      { items: ['Kucing','minum','susu'], answer: ['Kucing','minum','susu'] },
      { items: ['Ali','menendang','bola','itu'], answer: ['Ali','menendang','bola','itu'] },
      { items: ['Ibu','membeli','sayur','segar'], answer: ['Ibu','membeli','sayur','segar'] },
      { items: ['Kami','belajar','di','sekolah'], answer: ['Kami','belajar','di','sekolah'] },
      { items: ['Burung','itu','terbang','ke','awan'], answer: ['Burung','itu','terbang','ke','awan'] },
      { items: ['Adik','melukis','gambar','yang','cantik'], answer: ['Adik','melukis','gambar','yang','cantik'] },
      { items: ['Bapa','memandu','kereta','ke','pejabat'], answer: ['Bapa','memandu','kereta','ke','pejabat'] },
      { items: ['Murid','rajin','itu','membaca','banyak','buku'], answer: ['Murid','rajin','itu','membaca','banyak','buku'] },
      { items: ['Petani','menanam','padi','di','sawah','luas'], answer: ['Petani','menanam','padi','di','sawah','luas'] },
    ]),
  },
  // ── KONSTRUK 12: Tulis ayat ikut gambar (typing) ──
  {
    id: 'tulis-k12-ayat-gambar',
    title: 'Konstruk 12: Tulis Ikut Gambar',
    emoji: '🖼️',
    mode: 'typing_challenge',
    objective: 'Lihat gambar & taip perkataan yang sesuai.',
    reward: 'Tulis gambar',
    rounds: makeRounds([
      { prompt: '🍎 Apa ini? (taip)', target: 'epal' },
      { prompt: '🐱 Apa ini? (taip)', target: 'kucing' },
      { prompt: '🏠 Apa ini? (taip)', target: 'rumah' },
      { prompt: '⚽ Apa ini? (taip)', target: 'bola' },
      { prompt: '🌸 Apa ini? (taip)', target: 'bunga' },
      { prompt: '🐟 Apa ini? (taip)', target: 'ikan' },
      { prompt: '🚗 Apa ini? (taip)', target: 'kereta' },
      { prompt: '🌳 Apa ini? (taip)', target: 'pokok' },
      { prompt: '☂️ Apa ini? (taip)', target: 'payung' },
      { prompt: '🦋 Apa ini? (taip)', target: 'rama-rama' },
    ]),
  },
  // ── KONSTRUK 1: Susun abjad (lanjutan) ──
  {
    id: 'tulis-k1-abjad-lanjut',
    title: 'Konstruk 1: Susun Abjad (Lanjutan)',
    emoji: '🔤',
    mode: 'sequence',
    objective: 'Susun huruf ikut urutan abjad.',
    reward: 'Abjad pro',
    rounds: makeRounds([
      { items: ['H','I','J'], answer: ['H','I','J'] },
      { items: ['M','N','O'], answer: ['M','N','O'] },
      { items: ['R','S','T','U'], answer: ['R','S','T','U'] },
      { items: ['W','X','Y','Z'], answer: ['W','X','Y','Z'] },
      { items: ['G','H','I','J','K'], answer: ['G','H','I','J','K'] },
      { items: ['L','M','N','O','P'], answer: ['L','M','N','O','P'] },
      { items: ['P','Q','R','S','T','U'], answer: ['P','Q','R','S','T','U'] },
      { items: ['A','C','E','G','I'], answer: ['A','C','E','G','I'] },
      { items: ['B','D','F','H','J'], answer: ['B','D','F','H','J'] },
      { items: ['U','V','W','X','Y','Z'], answer: ['U','V','W','X','Y','Z'] },
    ]),
  },
  // ── KONSTRUK 2: Taip suku kata terbuka ──
  {
    id: 'tulis-k2-taip-suku',
    title: 'Konstruk 2: Taip Suku Kata',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip suku kata terbuka yang dipaparkan.',
    reward: 'Suku taip',
    rounds: makeRounds([
      { prompt: 'Taip: BA', target: 'ba' },
      { prompt: 'Taip: MU', target: 'mu' },
      { prompt: 'Taip: KI', target: 'ki' },
      { prompt: 'Taip: SO', target: 'so' },
      { prompt: 'Taip: LE', target: 'le' },
      { prompt: 'Taip: TU', target: 'tu' },
      { prompt: 'Taip: NA', target: 'na' },
      { prompt: 'Taip: PO', target: 'po' },
      { prompt: 'Taip: GI', target: 'gi' },
      { prompt: 'Taip: RU', target: 'ru' },
    ]),
  },
  // ── KONSTRUK 5: Eja perkataan tertutup (sequence) ──
  {
    id: 'tulis-k5-eja-tertutup',
    title: 'Konstruk 5: Eja Perkataan Tertutup',
    emoji: '🔡',
    mode: 'sequence',
    objective: 'Susun huruf ikut ejaan perkataan tertutup.',
    reward: 'Eja tertutup',
    rounds: makeRounds([
      { items: ['B','A','S'], answer: ['B','A','S'] },
      { items: ['C','A','T'], answer: ['C','A','T'] },
      { items: ['K','A','S','U','T'], answer: ['K','A','S','U','T'] },
      { items: ['L','A','M','P','U'], answer: ['L','A','M','P','U'] },
      { items: ['P','O','K','O','K'], answer: ['P','O','K','O','K'] },
      { items: ['R','U','M','A','H'], answer: ['R','U','M','A','H'] },
      { items: ['P','E','N','S','E','L'], answer: ['P','E','N','S','E','L'] },
      { items: ['T','E','M','P','A','T'], answer: ['T','E','M','P','A','T'] },
      { items: ['B','A','S','K','E','T'], answer: ['B','A','S','K','E','T'] },
      { items: ['K','A','M','B','I','N','G'], answer: ['K','A','M','B','I','N','G'] },
    ]),
  },
  // ── KONSTRUK 10: Cantum imbuhan (wordbuilder) ──
  {
    id: 'tulis-k10-cantum-imbuhan',
    title: 'Konstruk 10: Cantum Imbuhan',
    emoji: '🔗',
    mode: 'wordbuilder',
    objective: 'Cantum awalan/akhiran jadi perkataan.',
    reward: 'Cantum imbuhan',
    rounds: makeRounds([
      { target: 'BERMAIN', letters: ['BER','MAIN'] },
      { target: 'MEMBACA', letters: ['MEM','BACA'] },
      { target: 'MAKANAN', letters: ['MAKAN','AN'] },
      { target: 'BERLARI', letters: ['BER','LARI'] },
      { target: 'MELUKIS', letters: ['ME','LUKIS'] },
      { target: 'MENULIS', letters: ['ME','NULIS'] },
      { target: 'PERMAINAN', letters: ['PER','MAIN','AN'] },
      { target: 'PELAJARAN', letters: ['PE','LAJAR','AN'] },
      { target: 'KEBERSIHAN', letters: ['KE','BERSIH','AN'] },
      { target: 'MEMBERSIHKAN', letters: ['MEM','BERSIH','KAN'] },
    ]),
  },
  // ── KONSTRUK 11: Taip ayat mudah ──
  {
    id: 'tulis-k11-taip-ayat',
    title: 'Konstruk 11: Taip Ayat Mudah',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip ayat mudah dengan betul.',
    reward: 'Taip ayat',
    rounds: makeRounds([
      { prompt: 'Taip: saya makan nasi', target: 'saya makan nasi' },
      { prompt: 'Taip: ali main bola', target: 'ali main bola' },
      { prompt: 'Taip: ibu masak di dapur', target: 'ibu masak di dapur' },
      { prompt: 'Taip: adik baca buku', target: 'adik baca buku' },
      { prompt: 'Taip: kucing minum susu', target: 'kucing minum susu' },
      { prompt: 'Taip: saya pergi sekolah', target: 'saya pergi sekolah' },
      { prompt: 'Taip: burung terbang tinggi', target: 'burung terbang tinggi' },
      { prompt: 'Taip: kami suka bermain', target: 'kami suka bermain' },
      { prompt: 'Taip: bapa membaca surat', target: 'bapa membaca surat' },
      { prompt: 'Taip: pelajar menulis karangan', target: 'pelajar menulis karangan' },
    ]),
  },
  // ── KONSTRUK 12: Lengkapkan ayat ikut gambar (story) ──
  {
    id: 'tulis-k12-lengkap-ayat',
    title: 'Konstruk 12: Lengkapkan Ayat',
    emoji: '✏️',
    mode: 'story',
    objective: 'Pilih perkataan yang sesuai untuk lengkapkan ayat.',
    reward: 'Lengkap ayat',
    rounds: makeRounds([
      { scenes: [{ text: 'Saya makan ___ 🍎', choices: ['epal','kereta','rumah'], answer: 0 }] },
      { scenes: [{ text: 'Kucing ___ susu 🥛', choices: ['terbang','minum','tidur'], answer: 1 }] },
      { scenes: [{ text: 'Burung ___ di langit 🐦', choices: ['berenang','berlari','terbang'], answer: 2 }] },
      { scenes: [{ text: 'Ibu ___ di dapur 👩‍🍳', choices: ['memasak','melukis','menyanyi'], answer: 0 }] },
      { scenes: [{ text: 'Adik ___ bola ⚽', choices: ['membaca','bermain','menulis'], answer: 1 }] },
      { scenes: [{ text: 'Saya pergi ke ___ 🏫', choices: ['pasar','dapur','sekolah'], answer: 2 }] },
      { scenes: [{ text: 'Hujan ___ dari langit 🌧️', choices: ['turun','naik','lari'], answer: 0 }] },
      { scenes: [{ text: 'Petani menanam ___ 🌾', choices: ['kereta','padi','buku'], answer: 1 }] },
      { scenes: [{ text: 'Doktor ___ pesakit 🩺', choices: ['mengajar','memandu','merawat'], answer: 2 }] },
      { scenes: [{ text: 'Ikan ___ di dalam air 🐟', choices: ['berenang','terbang','berjalan'], answer: 0 }] },
    ]),
  },
  // ── KONSTRUK 3: Taip perkataan terbuka (lanjutan) ──
  {
    id: 'tulis-k3-taip-lanjut',
    title: 'Konstruk 3: Taip Perkataan (Lanjutan)',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan suku kata terbuka.',
    reward: 'Taip terbuka',
    rounds: makeRounds([
      { prompt: 'Taip: BATU', target: 'batu' },
      { prompt: 'Taip: BUKU', target: 'buku' },
      { prompt: 'Taip: DADU', target: 'dadu' },
      { prompt: 'Taip: KUDA', target: 'kuda' },
      { prompt: 'Taip: MEJA', target: 'meja' },
      { prompt: 'Taip: SAPU', target: 'sapu' },
      { prompt: 'Taip: ROTI', target: 'roti' },
      { prompt: 'Taip: CAWAN', target: 'cawan' },
      { prompt: 'Taip: KELAPA', target: 'kelapa' },
      { prompt: 'Taip: KERETA', target: 'kereta' },
    ]),
  },
  // ── KONSTRUK 6: Eja perkataan 'ng' (sequence) ──
  {
    id: 'tulis-k6-eja-ng',
    title: 'Konstruk 6: Eja Bunyi "ng"',
    emoji: '🔡',
    mode: 'sequence',
    objective: 'Susun huruf jadi perkataan berbunyi "ng".',
    reward: 'NG eja',
    rounds: makeRounds([
      { items: ['B','U','N','G','A'], answer: ['B','U','N','G','A'] },
      { items: ['T','A','N','G','A','N'], answer: ['T','A','N','G','A','N'] },
      { items: ['B','U','R','U','N','G'], answer: ['B','U','R','U','N','G'] },
      { items: ['P','A','Y','U','N','G'], answer: ['P','A','Y','U','N','G'] },
      { items: ['G','U','N','U','N','G'], answer: ['G','U','N','U','N','G'] },
      { items: ['J','A','G','U','N','G'], answer: ['J','A','G','U','N','G'] },
      { items: ['L','A','D','A','N','G'], answer: ['L','A','D','A','N','G'] },
      { items: ['P','I','S','A','N','G'], answer: ['P','I','S','A','N','G'] },
      { items: ['B','I','N','T','A','N','G'], answer: ['B','I','N','T','A','N','G'] },
      { items: ['K','A','N','G','K','U','N','G'], answer: ['K','A','N','G','K','U','N','G'] },
    ]),
  },
  // ── KONSTRUK 7: Eja perkataan diftong ──
  {
    id: 'tulis-k7-eja-diftong',
    title: 'Konstruk 7: Eja Diftong',
    emoji: '🔡',
    mode: 'sequence',
    objective: 'Susun huruf jadi perkataan diftong.',
    reward: 'Diftong eja',
    rounds: makeRounds([
      { items: ['T','U','P','A','I'], answer: ['T','U','P','A','I'] },
      { items: ['K','E','D','A','I'], answer: ['K','E','D','A','I'] },
      { items: ['P','I','S','A','U'], answer: ['P','I','S','A','U'] },
      { items: ['L','I','M','A','U'], answer: ['L','I','M','A','U'] },
      { items: ['P','U','L','A','U'], answer: ['P','U','L','A','U'] },
      { items: ['P','A','N','T','A','I'], answer: ['P','A','N','T','A','I'] },
      { items: ['S','U','N','G','A','I'], answer: ['S','U','N','G','A','I'] },
      { items: ['K','E','R','B','A','U'], answer: ['K','E','R','B','A','U'] },
      { items: ['H','A','R','I','M','A','U'], answer: ['H','A','R','I','M','A','U'] },
      { items: ['A','M','B','O','I'], answer: ['A','M','B','O','I'] },
    ]),
  },
  // ── KONSTRUK 8: Taip perkataan vokal berganding ──
  {
    id: 'tulis-k8-taip-vokal',
    title: 'Konstruk 8: Taip Vokal Berganding',
    emoji: '⌨️',
    mode: 'typing_challenge',
    objective: 'Taip perkataan vokal berganding.',
    reward: 'Vokal taip',
    rounds: makeRounds([
      { prompt: 'Taip: AIR', target: 'air' },
      { prompt: 'Taip: BAIK', target: 'baik' },
      { prompt: 'Taip: KUIH', target: 'kuih' },
      { prompt: 'Taip: BUIH', target: 'buih' },
      { prompt: 'Taip: NAIK', target: 'naik' },
      { prompt: 'Taip: MAIN', target: 'main' },
      { prompt: 'Taip: LAUK', target: 'lauk' },
      { prompt: 'Taip: DAUN', target: 'daun' },
      { prompt: 'Taip: BUAYA', target: 'buaya' },
      { prompt: 'Taip: TAHUN', target: 'tahun' },
    ]),
  },
  // ── KONSTRUK 9: Tulis perkataan digraf ──
  {
    id: 'tulis-k9-digraf',
    title: 'Konstruk 9: Tulis Digraf',
    emoji: '✒️',
    mode: 'wordbuilder',
    objective: 'Susun jadi perkataan dengan digraf (sy, kh, ny, gh).',
    reward: 'Digraf tulis',
    rounds: makeRounds([
      { target: 'SYUKUR', letters: ['SYU','KUR'] },
      { target: 'KHEMAH', letters: ['KHE','MAH'] },
      { target: 'NYAMUK', letters: ['NYA','MUK'] },
      { target: 'GHAIB', letters: ['GHA','IB'] },
      { target: 'SYARIKAT', letters: ['SYA','RI','KAT'] },
      { target: 'KHIDMAT', letters: ['KHID','MAT'] },
      { target: 'NYANYI', letters: ['NYA','NYI'] },
      { target: 'GHARIB', letters: ['GHA','RIB'] },
      { target: 'SYAITAN', letters: ['SYAI','TAN'] },
      { target: 'KHAZANAH', letters: ['KHA','ZA','NAH'] },
    ]),
  },
  // ── KONSTRUK 12: Tulis ayat ikut gambar (lanjutan) ──
  {
    id: 'tulis-k12-ayat-gambar2',
    title: 'Konstruk 12: Tulis Ikut Gambar (Lanjutan)',
    emoji: '🖼️',
    mode: 'typing_challenge',
    objective: 'Lihat gambar & taip perkataan yang sesuai.',
    reward: 'Tulis gambar 2',
    rounds: makeRounds([
      { prompt: '🐘 Apa ini? (taip)', target: 'gajah' },
      { prompt: '🦁 Apa ini? (taip)', target: 'singa' },
      { prompt: '🌙 Apa ini? (taip)', target: 'bulan' },
      { prompt: '⭐ Apa ini? (taip)', target: 'bintang' },
      { prompt: '🍌 Apa ini? (taip)', target: 'pisang' },
      { prompt: '🐢 Apa ini? (taip)', target: 'kura-kura' },
      { prompt: '🪑 Apa ini? (taip)', target: 'kerusi' },
      { prompt: '📖 Apa ini? (taip)', target: 'buku' },
      { prompt: '🚲 Apa ini? (taip)', target: 'basikal' },
      { prompt: '🐓 Apa ini? (taip)', target: 'ayam' },
    ]),
  },
];